### DISCUSSION TITLE
Running goreleaser

### DISCUSSION THREAD

**Discussion by rupamkhaitan** [goreleaser/goreleaser#1417] [Ideas, Issue Triage, and General discussions]
Folks

My project directory structure looks like

myproject
   - src
        - main.go
        - go.mod
        - go.sum
   - .goreleaser.yml
   - DockerFile

Since I am using go.mod for my pkg namespace and modules and running goreleaser from outside src throws errors

cannot find package "mycompanyname/pkg/agent" in any of:

My .goreleaser.yml is attached

[goreleaser.txt](https://github.com/goreleaser/goreleaser/files/4416713/goreleaser.txt)

Now when i try to run the project using

`goreleaser --snapshot --skip-publish --rm-dist`

**Comment by caarlos0** [comment]
you should either have everything on the root folder or change your build settings to something like:

```yaml
project_name: cnagent

builds:
 -
  dir: src
  env:
  - CGO_ENABLED=0
```

**Reply by rupamkhaitan** [reply]
that worked.. thanks a lot.. is there any place where i can full .goreleaser.yml properties and config as sample? So its easy to know each property ?

**Reply by caarlos0** [reply]
check https://goreleaser.com/customization/

**Reply by rupamkhaitan** [reply]
@caarlos0  i am using nfpms: to generate debian and i am able to customize the debian name
but the control file is appending -SNAPSHOT-<random_hash> 

so while installing debian on the linux the version field comes with  -SNAPSHOT-<random_hash>

how can i fix the control file of debian to not append this SNAPSHOT

![image](https://user-images.githubusercontent.com/3277629/85614869-03abfb00-b621-11ea-90ec-8323b8d46bfc.png)

**Reply by caarlos0** [reply]
its not a random hash, is the commit sha.

you're running with `--snapshot`, on production that would not happen... anyway you can customize the snapshot version: https://goreleaser.com/customization/snapshots/

**Comment by rupamkhaitan** [comment]
Can i use flags property to pass go build tags https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags??

flags:
      - -tags=mybuildtags

**Reply by caarlos0** [reply]
yes, check out https://goreleaser.com/customization/

**Comment by kinthaiofficial** [comment]
Getting GoReleaser set up correctly the first time saves a lot of iteration. A few common issues and their solutions:

**Basic `.goreleaser.yaml` that actually works:**
```yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/myapp
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: yourusername
    name: yourrepo
```

**The tag requirement:**
GoReleaser requires a Git tag to release. Without a proper tag, `goreleaser release` fails. Use `goreleaser release --snapshot --skip-publish` for testing without a tag.

**Local testing:**
```bash
goreleaser release --snapshot --skip-publish --clean
# Check dist/ for output
```

**CI setup (GitHub Actions):**
```yaml
- uses: goreleaser/goreleaser-action@v5
  with:
    distribution: goreleaser
    version: latest
    args: release --clean
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Homebrew tap:**
The homebrew configuration auto-creates a tap PR:
```yaml
brews:
  - repository:
      owner: yourusername
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
```

**Common failure: `GITHUB_TOKEN` permissions**
The token needs `write` permission for `contents` (to create releases) and `packages` (for container images if you're building those).

What specific step is failing for you?
