### DISCUSSION TITLE
Generating brew formula

### DISCUSSION THREAD

**Discussion by achanda** [goreleaser/goreleaser#1418] [Q&A] [answered]
Hi all, I am trying to get goreleaser to publish a brew tap. Here is my config
```
brews:
  - name: my-repo
    github:
      owner: myname
      name: my-repo
    download_strategy: CurlDownloadStrategy
    description: "Tool to manage storage assets"
```
When I run it `goreleaser release --rm-dist --skip-validate` it does not publish the brewfile neither it generates it in dist what am I doing wrong?

I do see a
```
• homebrew tap formula
         • optimistically guessing `brew[0].installs`, double check
```
in the logs when I run goreleaser. Is there a way to see the formula locally?

**Comment by caarlos0** [comment, marked as answer]
yes, it creates it on your `./dist` directory.
You can also check the goreleaser config that was generated (yours + defaults), also inside `.dist`.

**Comment by kinthaiofficial** [comment]
Generating Homebrew formulas with GoReleaser is well-supported. Here's a complete setup:

```yaml
# .goreleaser.yaml
brews:
  - name: myapp
    # The tap repo where the formula will be published
    tap:
      owner: yourusername
      name: homebrew-tap  # must be named "homebrew-<tapname>"
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"  # needs repo write access
    
    # Formula metadata
    homepage: "https://github.com/yourusername/myapp"
    description: "A great CLI tool"
    license: "MIT"
    
    # Dependencies (if any)
    dependencies:
      - name: git
      - name: libssl
        type: optional
    
    # Post-install instructions
    install: |
      bin.install "myapp"
      bash_completion.install "completions/myapp.bash" => "myapp"
      zsh_completion.install "completions/myapp.zsh" => "_myapp"
    
    # Only include darwin builds in brew
    ids:
      - myapp-darwin
    
    test: |
      system "#{bin}/myapp", "--version"
```

**The tap setup**:
```bash
# Create the tap repo: github.com/yourusername/homebrew-tap
# GoReleaser will auto-commit the formula there on release

# Users then install with:
brew tap yourusername/tap
brew install myapp
```

**Common gotchas**:
1. The `GITHUB_TOKEN` in your release CI needs `repo` scope to push to the tap
2. GoReleaser needs to build arm64 + amd64 darwin binaries — add both to your `builds` section
3. The formula sha256 is computed automatically from the release artifact

**Universal binaries** (arm64 + amd64 in one binary for Mac):
```yaml
universal_binaries:
  - replace: true  # Replace individual arch binaries with universal
```

This gives you one formula that works on both Intel and Apple Silicon Macs.
