### DISCUSSION TITLE
goreleaser: release fails

### DISCUSSION THREAD

**Discussion by nodece** [goreleaser/goreleaser#1426] [Q&A] [answered]
**Describe the bug**

The following is my log:
```
 ⨯ release failed after 0.08s error=git tag v2.2.2 was not made against commit 04c96314107df0803aa1e7ffaf3cd4784911a88c
```

It looks a `git` issue.  

track https://github.com/goreleaser/goreleaser/blob/master/internal/git/git.go#L31 and https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/git/git.go#L108, I found `error` is `exit status 128` .

What did `validate` do?  

**To Reproduce**

```yaml
project_name: casbin

release:
  github:
    owner: casbin
    name: casbin

  disable: true

  name_template: "Casbin {{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

It is working.

**Environment (please complete the following information):**

- OS:  mac
- OS version:  10.14.6
- GoReleaser Version [0.131.1]
- GitLab version (if using a private hosted one)
- Git: `git version 2.21.1 (Apple Git-122.3)`

**Additional context**
