### DISCUSSION TITLE
error=found 2 builds with the ID 'ytdlgo', please fix your config

### DISCUSSION THREAD

**Discussion by wedojava** [goreleaser/goreleaser#1427] [Q&A] [answered]
```
project_name: ytdlgo

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
- goos:
  - linux
  - darwin
  - windows
archives:
- files:
    - none*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

how to fix the error? this is my repo: https://github.com/wedojava/ytdlgo

thanks

**Comment by caarlos0** [comment, marked as answer]
```yaml
- env:
  - CGO_ENABLED=0
- goos:
  - linux
  - darwin
  - windows
```

this creates two build, you should probably remove the `-` from the beginning of `goos`:

```yaml
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
```
