### DISCUSSION TITLE
Detect binary is installed with snap

### DISCUSSION THREAD

**Discussion by guumaster** [goreleaser/goreleaser#1428] [Q&A] [answered]
Not sure if this is a question for `goreleaser` or a more general question on go builds. 

Is there a way to detect if a binary was installed with snap? Maybe a build flag or a configuration parameter on `.goreleaser.yml` that activate some flag and let the binary know it is on a snap confined installation?

Thanks

**Comment by caarlos0** [comment]
by default, no.. but you could had something in the lines of:

- adding one more build section, with different ldflags
- use the binaries from that section on the snap only

its a bit hacky and I haven't tested it, but I think it would work...

**Reply by guumaster** [reply]
Thanks, I'll try that.

**Reply by caarlos0** [reply]
Let me know if it works :)

**Comment by guumaster** [comment, marked as answer]
I can't manage to make it work properly. This is the relevant part of the config:

```yaml

builds:
  - id: hostctl
    binary: hostctl
    main: main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/guumaster/hostctl/cmd.version={{.Version}}

  - id: hostctl-snap
    binary: hostctl-snap
    main: main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/guumaster/hostctl/cmd.version={{.Version}} -X github.com/guumaster/hostctl/cmd.snap=on

....
snapcrafts:
  - id: hostctl-snap
    name: hostctl
    builds:
      - hostctl-snap
    summary: Your dev tool to manage /etc/hosts like a pro
    ....



```

The file `hostctl.snap` has the `snap` flag set to `on` and works properly. But then the normal binary `hostctl` also have the flag set to `on`. 

Do you see a way around that with this config?

**Reply by caarlos0** [reply]
Tried here:

###### `main.go`:

```go
package main

var snap = "off"

func main() {
	println("snap: " + snap)
}
```

###### `.goreleaser.yaml`:

```yaml
builds:
- id: foo
  binary: foo
  main: main.go
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X main.version={{.Version}}

- id: snap
  binary: foo-snap
  main: main.go
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.snap=on
```

###### outputs

```console
$ goreleaser --rm-dist --skip-validate --skip-publish

   • releasing using goreleaser 0.131.1...
   • loading config file       file=.goreleaser.yaml
   • running before hooks
   • loading environment variables
      • pipe skipped              error=publishing is disabled
   • getting and validating git state
      • releasing v20.1.0, commit 23f1d61f636b0e23a839344d984fb378c0764bf0
      • pipe skipped              error=validation is disabled
   • parsing tag
   • setting defaults
      • snapshoting
      • github/gitlab/gitea releases
      • project name
      • building binaries
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images
      • artifactory
      • blobs
      • homebrew tap formula
      • scoop manifests
   • snapshoting
      • pipe skipped              error=not a snapshot
   • checking ./dist
      • --rm-dist is set, cleaning it up
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • building                  binary=/Users/carlos/Code/caarlos0/test/dist/foo_darwin_amd64/foo
      • building                  binary=/Users/carlos/Code/caarlos0/test/dist/snap_darwin_amd64/foo-snap
   • archives
      • creating                  archive=dist/test_20.1.0_darwin_amd64.tar.gz
   • linux packages
   • snapcraft packages
   • calculating checksums
      • checksumming              file=test_20.1.0_darwin_amd64.tar.gz
   • signing artifacts
   • docker images
      • pipe skipped              error=docker section is not configured
   • publishing
      • pipe skipped              error=publishing is disabled
   • release succeeded after 0.65s


$ ./dist/foo_darwin_amd64/foo
snap: off

$ ./dist/snap_darwin_amd64/foo-snap
snap: on
```

so, not sure what's the issue on your side... maybe your code is setting `snap=on` by default? 🤔
