### DISCUSSION TITLE
releasing on privately hosted Gitlab

### DISCUSSION THREAD

**Discussion by DerNasenach** [goreleaser/goreleaser#1440] [Q&A] [answered]
First things first, is goreleaser able to release on private repos? Thought as the API-Token is mandatory it might be possible, but I was not able to make it work yet.

**Describe the bug**

Wanted to integrate goreleaser into the gitlab-CI pipeline of a gitlab repo, privately hosted by my company. Did not even get to set it up manually though, keeps aborting at: 

`⨯ release failed after 31.15s error=github/gitlab/gitea releases: failed to publish artifacts: GET https://gitlab.mycompany.net/api/v4/projects/path/to/myproject/releases/1.0.1: 404 {message: 404 Project Not Found}`

The project repo itself is hosted at https://gitlab.mycompany.net/path/to/my/project/myproject/ and it's visibility is set to private. Thus I am not sure wether or not this makes it not visible at all from the API's perspective, but I hoped specifying an API-Token might be enough to get the job done.
Is there a way to further specify the repository to use, or otherwise release from a private repository? Migrating it to a public Gitlab is an option as well, even though I would like to avoid having to do that.

**To reproduce**

```yaml
project_name: myproject
before:
  hooks:
    - go get -v -d ./...
    - go generate ./...

gitlab_urls:
  api: https://gitlab.mycompany.net/api/v4
  download: https://gitlab.mycompany.net/path/to/my/project/myproject/-/archive/1.0.1/myproject-1.0.1.tar.gz
  skip_tls_verify: false

release:
  prerelease: true

builds:
- env:
  - CGO_ENABLED=0

archives:
- replacements:
    darwin: Darwin
    linux: Linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - name: myproject
    gitlab:
      owner: mycompany
      name: myproject
    commit_author:
      name: mycompany
      email: info@mycompany.com
    folder: Formula
    homepage: https://mycompany.de/
    description: My Tools description
```

**Expected behaviour**

Creating a release page with corresponding archives at https://gitlab.mycompany.net/path/to/my/project/myproject/-/archive/1.0.1/

**Environment**

+ OS: macOS
+ OS version: 10.15.3
+ GoReleaser version: 0.131.1
+ GitLab version: 12.9.2-ee
+ Git: git version 2.26.0

**Additional Context**

Thanks for every help I can get, I am quite new to Software engineering and accordingly unexperienced.

**Comment by caarlos0** [comment]
I think whats missing is that on the `release` section, you need to add the `gitlab` section as well... like the `brew` one.

can you try that?

**Reply by DerNasenach** [reply]
Added the 
```yaml
 gitlab:
      owner: mycompany
      name: myproject
```
section to the release section. Sadly this didn't change any behavior.

**Comment by caarlos0** [comment, marked as answer]
did you assure that the gitlab api token you're using has access to this repo?

judging by 404, maybe that's it...

**Reply by DerNasenach** [reply]
Tokens access rights weren't the problem, but this lead me to the bug to fix my problem. Thanks a lot! 

One last question remains though: Goreleaser now builds my archives + brew formula and uploads them to my private repo. Homebrew on the other hand specifies all formula contributions to be open source. Can I customize goreleaser to generate a brew-cask instead of a formula, or maybe it supports a different package manager, able to release from private repos?

I'm going to have a look at the other supported options for myself, but I thought maybe you might know a way, that is coming to your mind. 

Even if there isn't, thank you for your help and quick response, much appreciated!

**Reply by caarlos0** [reply]
> Tokens access rights weren't the problem, but this lead me to the bug to fix my problem. Thanks a lot!

I'm curious about what was the problem... can you share?

> Can I customize goreleaser to generate a brew-cask instead of a formula

goreleaser only generates a brew cask formulas... so I think you should be good :)

**Reply by DerNasenach** [reply]
Well the URL-path to the repo being owned by my company being rather bulky lead to some errors when specifying the urls for goreleaser to use. At first I was not aware it uses the `owner:` and `name` fields specified to build the URL to use, so I thought specifying the `gitlab_urls:` field would do the job. I also recall the documentation to state at customization -> release, that goreleaser uses the URL it finds in the git remote, which kind of lead me on a wrong trail. Quote:
```yml
# .goreleaser.yml
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: user
    name: repo
```


I think either you are misunderstanding my last question, or I didn't get the difference between Brew-Core and Cask yet. From my understanding, the formula goreleaser generated is a core formula, core being open-source only, looking like this:
```yaml
# This file was generated by GoReleaser. DO NOT EDIT.
class Myproject < Formula
  desc "My tools Description"
  homepage "https://mycompany.de/"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://gitlab.mycompany.net/path/to/myproject/uploads/62f2353c9cd124a5502a2b60ce6c82fe/myproject_1.0.1_macOS_64-bit.tar.gz"
    sha256 "14ea8e994220888901bce54736c6bc9fce7698dabab5ddedd4020b4c05ba2a3b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://gitlab.gitlab.mycompany.net/path/to/myproject/uploads/62f2353c9cd124a5502a2b60ce6c82fe/myproject_1.0.1_Linux_64-bit.tar.gz"
      sha256 "70b0c35f7bf78c41884df8dd8ae425cb466edac78b156958f467f3187a98b929"
    end
  end

  def install
    bin.install "my project"
  end
end

```

Casks on the other hand can be closed-source and need to be in app-format, as specified at the [homebrew-github](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md). Or is it possible to add a formula in the Cask Repository as well?

Anyway, I will post the same question to the brew devs, as I suppose they are the right guys to ask this. Thanks again though for your help and quick response!

**Reply by caarlos0** [reply]
oh, sorry, I for some reason read `tap` instead of `cask`. You're right, goreleaser do not generate cask formulas.

thanks for the details on the url thing, will try to make the docs better 🙏

**Comment by thynquest** [comment]
Hello There 

Actually I am facing the same issue with gitlab. it takes the path/name of the project instead of the project id. I have checked the gitlab token and it has the required rights. Do you know how to fix this ? 

thank you for your help  

````yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
gitlab_urls:
  api: https://my.gitlab.com/api/v4
  download: https://my.gitlab.com
project_name: sample
builds:
  - binary: ./bin/sample
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=vendor
    ldflags:
      - -X main.GitVersion=v{{.Version}}
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
     - LICENSE
````
and this is the error

`failed to publish artifacts: GET https://my.gitlab.com/api/v4/projects/path/sample/releases/v0.1.2: 404 {message: 404 Project Not Found}`
