### DISCUSSION TITLE
Double-templated variables not resolved

### DISCUSSION THREAD

**Discussion by ViRb3** [goreleaser/goreleaser#1461] [Ideas, Issue Triage, and General discussions]
Consider the following YAML:
```yml
builds:
  - #
    id: "{{.ProjectName}}-nowindow"
    binary: "{{.ProjectName}}-nowindow"
    goos:
      - windows
    goarch:
      - 386
    hooks:
      post: cp example.txt "{{dir .Path}}/"
```

The template from `builds.binary` is not resolved when returned through `Path` in `builds.hooks.post`, resulting in a double-template, which is never resolved:
```
{{.Path}} -> /drone/src/dist/{{.ProjectName}}-nowindow_windows_386/
```

Therefore, commands will take `{{.ProjectName}}` literally without resolving it:
```
• running hook              hook=cp sample.txt "/drone/src/dist/{{.ProjectName}}-nowindow_windows_386/
```
