### DISCUSSION TITLE
nightly or "next" release

### DISCUSSION THREAD

**Discussion by gianarb** [goreleaser/goreleaser#1534] [Ideas, Issue Triage, and General discussions]
Hello!

I saw some issues related to push snapshots and I know @caarlos0 has some concerns. But I have a project that pushes Docker images when master changes.

It will be nice to actually update a release for that. Even if not a tag is assigned to it, otherwise we will end up with too many releases.

According to my current experience, the closes things to this look a lot like "pushing" a snapshot.

Am I wrong? How can I solve a problem like this with GoReleaser?

**Comment by caarlos0** [comment]
I'm pretty sure you can't do this with goreleaser right now.

I also can't think on a good way to express that on the current config format 🤔

**Reply by johnbuhay** [reply]
For your consideration:

```
goreleaser release --rm-dist --snapshot --skip-publish=false
```

Allow the `--skip-publish` flag to override or take precedence over the default from `--snapshot`

This would allow me to do something like:

```
artifactories:
  - name: <name>
    target: https://<artifactory_base_url>/binaries{{ if .IsSnapshot }}-snapshots-local{{ end }}/<bin_org_path>/{{ .ProjectName }}/{{ .Version }}/
    ...
```

Or maybe it is worth putting this logic into its own command:

```
goreleaser publish --snapshot --publisher-id 'artifactories[0]'
```
