### DISCUSSION TITLE
nfpm - how to create a meta package

### DISCUSSION THREAD

**Discussion by reddec** [goreleaser/goreleaser#1612] [Ideas, Issue Triage, and General discussions]
Good day everyone!

I have a client/server application (trusted-cgi) in one project. I would like to separate generated debian packages into three packages:

- trusted-cgi-server (binary for server platform)
- trusted-cgi-ctl (binary for client tools)
- trusted-cgi (package without binary but with dependencies on both two)

However, empty array in `ids` section in `nfpm` means that all builds will be included to a target package (that I am trying to avoid).

Simplified yaml (I tried to remove as much as possible):

```yaml
project_name: trusted-cgi
builds:
- main: ./cmd/trusted-cgi/main.go
  id: server
  binary: trusted-cgi
   # ...
- main: ./cmd/cgi-ctl
  id: client
  binary: cgi-ctl
  # ...
nfpms:
  - id: debian-server
    file_name_template: "{{ .ProjectName }}-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - server
    formats:
      - deb
    # ...
  - id: debian-tools
    builds:
      - client
    file_name_template: "{{ .ProjectName }}-ctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - deb
  - id: debian
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds: []
    formats:
      - deb
    dependencies:
      - trusted-cgi-ctl
      - trusted-cgi-server
```

`debain` target is a source of my question...

Thanks a lot!

P.S.

If it is not possible, maybe it will make sense to distinguish `nil` and empty array: `nil` - keep as is, empty - make "meta" package without binaries
