### DISCUSSION TITLE
Is it possible to change the homebrew tap class name that gets generated

### DISCUSSION THREAD

**Discussion by geoffjay** [goreleaser/goreleaser#1652] [Q&A] [answered]
My repository starts with a number so the ruby class that's generated by `goreleaser` fails when you try to use it. For now, that means changing it manually, but it would be great if there was a way to fix that without having to rename my repository.

**Comment by radeksimko** [comment, marked as answer]
It appears the Ruby class for the formula is currently generated from the `name` option:

```yaml
brews:
  -
    # Name template of the recipe
    # Default to project name
    name: myproject
```
which is also used for the filename. Is that what you're looking for?
