### DISCUSSION TITLE
How to set `-ldflags` values for each target in Goreleaser?

### DISCUSSION THREAD

**Discussion by adityakrgupta25** [goreleaser/goreleaser#1709] [Q&A] [answered]
I need to set the Os/Arch variable for each build target. My initial thought was to have a script that would calculate these variables and using hooks to run this script every target.

`.goreleaser.yaml`:
```
builds:
  hooks:
    pre:
      - sh variables.sh
  ldflags:
    - -s -w -X "main.goversion={{.Env.GOVERSION}}"
    - -s -w -X "main.commit={{.Env.GITCOMMIT}}"
    - -s -w -X "main.os={{.Env.GOOS}}"
    - -s -w -X "main.arch={{.Env.GOARCH}}"
    - -s -w -X "main.commit={{.Env.GITCOMMIT}}"
    - -s -w -X "main.date={{.Env.BUILDTIME}}"

```

`variables.sh`

```
#!/bin/bash

export GITCOMMIT=${GITCOMMIT:-$(git rev-parse --short HEAD 2> /dev/null || true)}
export BUILDTIME=${BUILDTIME:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
export GOOS="${GOOS:-$(go env GOHOSTOS)}"
export GOARCH="${GOARCH:-$(go env GOHOSTARCH)}"
export GOVERSION=$(go version | awk '{print $3;}')
```

But as the variables are not defined anywhere in the config, so it seems it fails to recognize them, throwing: 

```
release failed after 0.45s error=template: tmpl:1:31: executing "tmpl" at <.Env.GOVERSION>: map has no entry for key "GOVERSION"
```

Which makes sense. 
But now I am concerned about how do I set target-specific variables for each target?

**Comment by caarlos0** [comment, marked as answer]
the problem with this is that the hook will not export the envs to the build it self... 

if you want to do that, you should probably run like `./variables.sh && goreleaser --etc`

**Reply by bradleyjames** [reply]
I may be missing something but I think the command needs to be`. ./variables.sh && goreleaser --etc`.  It was missing the initial "." to source the script to export the variables.

**Comment by vvrnv** [comment]
@caarlos0 Hi! is it possible to set ldflags for each target without bash script?
    ldflags:
    - -X github.com/vvrnv/gossl/cmd.Arch={{ .Runtime.Goarch }}
    - -X github.com/vvrnv/gossl/cmd.Os={{ .Runtime.Goos }}
    
    I mean, how do I pass variables go env GOOS, go env GOARCH for each build id?

**Reply by vvrnv** [reply]
found solution
```
builds:
  - id: gossl-linux-amd
    binary: gossl
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
    - -X github.com/vvrnv/gossl/cmd.Version={{ .Tag }}
    - -X github.com/vvrnv/gossl/cmd.Arch={{ .Env.ARCH }}
    - -X github.com/vvrnv/gossl/cmd.Os={{ .Env.OS }}
    - -X github.com/vvrnv/gossl/cmd.Date={{ .Date }}
    - -X github.com/vvrnv/gossl/cmd.Commit={{ .FullCommit }}
    env:
      - CGO_ENABLED=0
      - ARCH=amd64
      - OS=linux
```

**Reply by caarlos0** [reply]
You can use `{{ .Os }}` and `{{ .Arch }}`.

Docs: https://goreleaser.com/customization/templates/#single-artifact-extra-fields

Example:

```yaml
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
    - -X main.Version={{ .Tag }}
    - -X main.Arch={{ .Arch }}
    - -X main.Os={{ .Os }}
    - -X main.Date={{ .Date }}
    - -X main.Commit={{ .FullCommit }}
```
