### DISCUSSION TITLE
Compile the specified CPU architecture

### DISCUSSION THREAD

**Discussion by lostmaniac** [goreleaser/goreleaser#1777] [Q&A] [answered]
For example, I want to compile only x86_64 files. But I think there are many defaults. Does it support specific CPU architecture? I searched the documentation, but did not find any relevant instructions. thank you very much.

**Comment by caarlos0** [comment, marked as answer]
you can specify `goarch: ['amd64']` on the build section.

check https://goreleaser.com/customization/build/ for more details.

**Comment by lostmaniac** [comment]
I have no build here:
How should I write it? thank you very much.


```yaml
name: Release
on:
  create:
    tags:
    - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Validates GO releaser config
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: check

    - name: Create release on GitHub
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
