### DISCUSSION TITLE
Can archive wrap directory have a different name for the archive file?

### DISCUSSION THREAD

**Discussion by csreesan** [goreleaser/goreleaser#1811] [Q&A] [answered]
What I would like to do is to wrap archived files in a directory, but have the directory with a different name than the archive file itself.
e.g. archive name : cli_darwin_amd64.tar.gz 
       extracted wrapped folder name: cli

Currently I am doing this which leads to the same name between archive file and wrap folder
```
archives:
   - id: archive
     name_template: "cli_{{ .Os }}_{{.Arch}}"
      format: tar.gz
     wrap_in_directory: true
     files:
       - LICENSE
```
Is there a way to also have name template for the wrap directory?
