### DISCUSSION TITLE
linux build problem for golang application

### DISCUSSION THREAD

**Discussion by Tsovak** [goreleaser/goreleaser#1824] [Q&A] [answered]
Hey, 

I have a repository https://github.com/Tsovak/go-test-parser where I'm using goreleaser for different OS. 
the build and release have done successfully for Linux, windows and darwin, but only the Linux binary working not correct. 

Inside the binary, I store the html file, so running in Linux says that the file does not exist. 
I cloned the repository to Linux machine and build with the command `make build` (`go build -ldflags "" -o bin/go-test-parser cmd/go-test-parser/*.go `), and all works correctly.  

I think the problem with goreleaser because build on the Linux machine working correctly. 

So the .goreleaser.yml is 
```
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - id: "go-runner"
    main: ./cmd/go-runner
    binary: go-runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
  - id: "go-test-parser"
    main: ./cmd/go-test-parser
    binary: go-test-parser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

with Github actions 
```
name: goreleaser

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"

env:
  GO_VERSION: 1.14

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
