### DISCUSSION TITLE
Github action to elease golang library

### DISCUSSION THREAD

**Discussion by bygui86** [goreleaser/goreleaser#1850] [Q&A] [answered]
Hi guys,

I'm trying to release a `golang library` using goreleaser from `github actions`, but I fail and I don't properly understand what I miss.

This is the library: https://github.com/bygui86/multi-profile

This is the `.goreleaser.yaml`:
```yaml
project_name: multi-profile
builds:
  - skip: true
archives:
  - replacements:
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

I tried this config as well, but still fails:
```yaml
project_name: multi-profile
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    skip: true
archives:
  - replacements:
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

This is the `github workflow`:
```yaml
name: release
on:
  push:
    tags:
      - v*
env:
  GO111MODULE: "on"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # WARN: 'fetch-depth: 0' is required for the changelog to work correctly
          fetch-depth: 0
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -count=3 -race ./...
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This are logs from github actions:
```
Run goreleaser/goreleaser-action@v2
  with:
    version: latest
    args: release --rm-dist
    workdir: .
  env:
    GO111MODULE: on
    GOROOT: /opt/hostedtoolcache/go/1.15.2/x64
    GITHUB_TOKEN: ***
✅ GoReleaser version found: v0.144.0
⬇️ Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.144.0/goreleaser_Linux_x86_64.tar.gz...
📦 Extracting GoReleaser...
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/f1685cd4-0bc5-4337-9ecc-860cd175f3b6 -f /home/runner/work/_temp/d77b4540-087a-49d7-8d52-4e364e0e63ba
✅ v1.3.0-alpha5 tag found for commit '74ae51d'
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.144.0/x64/goreleaser release --rm-dist

   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v1.3.0-alpha5, commit 74ae51dd2db19ac1ab38cd9bd9adcc998c46c413
   • parsing tag      
   • running before hooks
   • setting defaults 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • snapshotting     
      • pipe skipped              error=not a snapshot
   • checking ./dist  
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • skip is set               id=multi-profile
   • archives         
   ⨯ release failed after 0.03s error=invalid archive: 0: archive has different count of built binaries for each platform, which may cause your users confusion. Please make sure all builds used have the same set of goos/goarch/etc or split it into multiple archives
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.144.0/x64/goreleaser' failed with exit code 1
```

Every comments, tips or help are more than welcome!
Thanks :)

**Comment by caarlos0** [comment, marked as answer]
I think the config should be only:

```yaml
project_name: multi-profile
builds:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```
