### DISCUSSION TITLE
How to set up GPG passphrase from stdin?

### DISCUSSION THREAD

**Discussion by tommyalatalo** [goreleaser/goreleaser#1895] [Q&A] [answered]
I'm trying to set up GPG signing with the passphrase from stdin, but not succeeding
This is what I have in my goreleaser.yml
```
signs:
  - artifacts: checksum
    stdin: "{{ .Env.GPG_KEY_PASSPHRASE }}"
    args: ["--output", "${signature}", "--detach-sign", "${artifact}"]
```
I have exported the `GPG_KEY_PASSPHRASE` variable in my shell, but goreleaser still asks me to enter the passphrase in a popup dialog when I try running it with `goreleaser release --rm-dist --skip-publish --skip-validate`

I was expecting the passphrase to be loaded and used by the `stdin` field, any ideas as to why this wouldn't be working?
