### DISCUSSION TITLE
How to use environment variables created during hook execution?

### DISCUSSION THREAD

**Discussion by swithek** [goreleaser/goreleaser#1905] [Q&A] [answered]
Is there a way to use an environment variable that was created and exported during the hook execution? My configuration is as follows: 
```yaml
before:
  hooks:
   - ./scripts/extract_version {{ .Major }} {{ .Minor }} # determines the version name based on the major and minor versions, sets and exports VERSION_NAME
builds:
  -
    main: ./cmd/main.go
    ldflags:
      - '-X main.versionName={{ .Env.VERSION_NAME }}'

```

**Comment by swithek** [comment]
Echoing the result from the script and assigning to a global env variable doesn't seem to work as well:
```yaml
env:
   - VERSION_NAME=$(./scripts/extract_version {{ .Major }} {{ .Minor }})
builds:
  -
    main: ./cmd/main.go
    ldflags:
      - '-X main.versionName={{ .Env.VERSION_NAME }}'
```
