### DISCUSSION TITLE
Including icons for windows builds

### DISCUSSION THREAD

**Discussion by jftuga** [goreleaser/goreleaser#1929] [Q&A] [answered]
I want to build Windows binaries that include an icon.  

This is what my file tree looks like. It contains 3 separate binaries:

    ├───cmd
    │   ├───a
    │   ├───b
    │   ├───c

I first run these commands, which I have also added to my `before hooks` in my `.goreleaser.yml` file:

    go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    go generate ./...

When running `go generate ./...`, it will creates a new file in each subdirectory called: `resource_windows_amd64.syso`.

___

In each subdirectory, I have one file called `main.go` and one file called `versioninfo.json`.  

The `json` file simply includes the `IconPath` to my `.ico` file, which is needed by the `goversioninfo` program:

    {
        "IconPath": "cmd\\a\\a.ico"
    }

`go build` knows about this file because the first line of `main.go` is:

    //go:generate goversioninfo -icon=a.ico -platform-specific=true

___

If I were to run the following commands by hand, I would successfully build an `exe` file that includes the icon:

    go generate ./...
    cd cmd\a
    : (the resource_windows_amd64.syso is in this directory along with main.go)
    go build

If I then browse to this folder in the Windows `File Explorer`, I will see that `a.exe` is using `a.ico` as its icon.

___

I am trying to get this working in my `.goreleaser.yml` file, but the binaries under the `dist` folder do not include the icon.

```yml
  project_name: my_project
  before:
    hooks:
      - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
      - go generate ./..
  builds:
    - main: ./cmd/a/main.go
      id: "a"
      binary: a
      goos:
        - linux
        - darwin
        - windows
      goarch:
        - amd64
        - arm
      goarm:
        - 7
```
  
The `.syso` file is safely ignored for other OSs and architectures by `go build`.

___

When running:

    goreleaser build --rm-dist --snapshot

the `resource_windows_amd64.syso` file is successfully created in the `cmd\a` folder, but not used for the final `.exe` creation.

___

What do I need to change in my `.goreleaser.yml` to get this working such that the windows binaries will contain their associated icon?

Thanks.

**Comment by jftuga** [comment, marked as answer]
I just figured this out.

This is what I changed in my `.goreleaser.yml` file:

```yml
  builds:
    - main: .
      id: "a"
      binary: a
      dir: ./cmd/a
```

Are there any problems with this type of configuration?

___

In case anyone else is interested, here is my working `.goreleaser.yml` file:

https://github.com/jftuga/sqs_clipboard/blob/main/.goreleaser.yml
