### DISCUSSION TITLE
Global hook for build

### DISCUSSION THREAD

**Discussion by depado** [goreleaser/goreleaser#1950] [Q&A] [answered]
Hello everyone
I'd like to execute a hook for a whole build section and not for every individual step. For example, an old project of mine is using [rice](https://github.com/GeertJohan/go.rice) to embed static files into the binary and since there's no point in executing the `rice embed-go` command every time (unless the builds are isolated? But I don't think so), I'd like to define a "per-build section hook".

So I know there's a global hook that can be defined, but the thing is, I want to also provide builds with no embedded static files for people to edit the templates/CSS files manually if they feel like it. So I have two build sections, one with `rice generate-go` and one which deletes the generated file. The thing is, those steps are basically walking on each other's steps since goreleaser compiles multiple versions at once, so sometimes the hooks create a race condition. 

Is there a way to define per-build section hooks? 

`.goreleaser.yml`
```yaml
builds:
- id: standalone-servers
  goarch: [amd64, arm, arm64, 386]
  goarm: [6, 7]
  goos: [linux,darwin,windows]
  ignore:
  - goos: darwin
    goarch: 386
  dir: server
  hooks:
    pre: 
      - make -s ensure-rice
  env:
  - CGO_ENABLED=0
  main: main.go
  binary: goploader
  ldflags:
   - -s -w -X "main.Version={{ .Env.TAG }}" -X "main.Build={{ .Env.BUILD }}"

- id: servers
  goarch: [amd64, arm, arm64, 386]
  goarm: [6, 7]
  goos: [linux,darwin,windows]
  ignore:
  - goos: darwin
    goarch: 386
  dir: server
  hooks:
    pre: 
      - make -s ensure-norice
  env:
  - CGO_ENABLED=0
  main: main.go
  binary: goploader
  ldflags:
   - -s -w -X "main.Version={{ .Env.TAG }}" -X "main.Build={{ .Env.BUILD }}"
```

`Makefile`
```make
ensure-rice:
	if [ ! -f server/rice-box.go ]; then rice embed-go; fi

ensure-norice:
	if [ -f server/rice-box.go ]; then rm server/rice-box.go; fi
```
