### DISCUSSION TITLE
Failed to build (package error)?

### DISCUSSION THREAD

**Discussion by vesche** [goreleaser/goreleaser#1992] [Q&A] [answered]
Hey there- new to goreleaser. I probably have something really obvious wrong, but I can't figure it out. I went thru the [Quick Start](https://goreleaser.com/quick-start/) and when I got to testing building the release, `goreleaser --snapshot --skip-publish --rm-dist` I am getting this error:

```
release failed after 0.15s error=failed to build for windows_386: package github.com/foo/bar
```

(using foo/bar here as an example)

I'm using pretty much the exact yml from the quick start:
```
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
archives:
  - replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

I think something might be wrong with my `main.go`? Maybe this isn't the right way to do an entry point?

```
package main

import (
    "github.com/foo/bar/src/gui"
)

func main() {
    gui.Run()
}
```

The program runs fine if I do `go run main.go` or `go build`. That package is in my `~/go/src/github.com/foo/bar` etc

Any help would be awesome, thanks in advance.
