### DISCUSSION TITLE
How do you know the service url of a Gitea release?

### DISCUSSION THREAD

**Discussion by gabyx** [goreleaser/goreleaser#2023] [Q&A] [answered]
I wonder how you know the service URL of a Gitea hosted Repository. I mean the Gitea GO SDK needs a url + owner + repo etc.
https://godoc.org/code.gitea.io/sdk/gitea#NewClient

Your example states:

```yaml
# .goreleaser.yml
release:
  # Same as for github and gitlab
  # Note: it can only be one: either github, gitlab or gitea
  gitea:
    owner: user
    name: repo
```

How is that possible to work? Thanks :-)
