### DISCUSSION TITLE
What is the best way to upload/push build artifacts after the build is done via github actions?

### DISCUSSION THREAD

**Discussion by hellt** [goreleaser/goreleaser#2076] [Q&A] [answered]
Hi all,
I have a goreleaser pipeline that builds binaries and rpm/deb packages.
Once the build is done I need to push deb/rpm packages to an apt/yum repo enabled by fury.io

The push is trivial via curl:

```
curl -F package=@filename https://${{ secrets.TOKEN }}@push.fury.io/$account-name/
```

I wonder where can I incorporate this `curl` step if I am using Github actions? Should it be in the posthooks?
Or should it be after the goreleaser step is done? If it should be done after the goreleaser step, what path should I look for to get the built packages?

**Comment by hellt** [comment, marked as answer]
or should it rather be [custom publisher](https://goreleaser.com/customization/publishers/)?

**Reply by hellt** [reply]
following best practices, answering my own question:

adding deb/rpm packages to a free apt/yum repository provided by fury.io can be easily done with Goreleaser' [customer publisher](https://goreleaser.com/customization/publishers/).

## 1 Add fury token to env vars of github actions
```yaml
---
name: Release
on:
  push:
    tags:
      - v*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.155.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURYPUSHTOKEN }}
```

## 2 Add ID to nfpm packages
By adding ID to NFMP portion of `.goreleaser.yml` we will be able to use it in a custom publisher to filter only packages artifacts for upload

```yaml
<SNIP>
nfpms:
  - id: packages
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
<SNIP>
```

## 3 Add custom publisher section
And now tie it all together

```yaml
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/netdevops/
```
