### DISCUSSION TITLE
How do I publish only packages (deb/rpm) and _not_ binaries or tarballs?

### DISCUSSION THREAD

**Discussion by eriksw** [goreleaser/goreleaser#2096] [Q&A] [answered]
I want to publish _only_ fpm packages (i.e. `.deb`, `.rpm` etc), how can I do that?

Suppressing the checksums was easy (`disable: true`).

However, for the binaries, I've only found the option to publish a loose binary instead of a tarball (`format: binary`).

How do I suppress tarball/binary publishing entirely, leaving only the packages?

**Comment by caarlos0** [comment, marked as answer]
You should be able to do that by putting an id on the nfpm pipe and then filtering by that id on the releases pipe

Something like:

```yaml
nfpms:
- id: include-this
archives:
- id: default # default is the default id for everything
release:
  ids:
  - include-this
```

https://goreleaser.com/customization/nfpm/
https://goreleaser.com/customization/release/
