### DISCUSSION TITLE
How to release mutiple builds on github action?

### DISCUSSION THREAD

**Discussion by hi20160616** [goreleaser/goreleaser#2111] [Q&A] [answered]
ok, guys, I asked and answered myself as the title

In short: written and pass test `.goreleaser.yml` for mutiple build, but release via github action.

There are Steps:
1. write and pass test goreleaser local machine config `.goreleaser.yml`, look the code below or my goreleaser config file here: https://github.com/hi20160616/yt_fetcher/blob/main/.goreleaser.yml
2. add a github action workflow, just install goreleaser and run command on docker, look the code below or my github action config file here: https://github.com/hi20160616/yt_fetcher/blob/main/.github/workflows/goreleaser.yml

- `.goreleaser.yml`:
```yaml
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - main: ./cmd/yt_fetcher/server/server.go
    id: "server"
    binary: server
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: 386
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
        
  - main: ./cmd/yt_fetcher/manager/manager.go
    id: "manager"
    binary: manager
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: 386
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64

  - main: ./cmd/yt_fetcher/jobs/jobs.go
    id: "jobs"
    binary: jobs
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: 386
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64


archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

- `.github/workflows/goreleaser.yml`:
```yaml
name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      -
        name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      -
        name: GoReleaser Release
        run: goreleaser --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
