### DISCUSSION TITLE
Can we add an additional file to the archive for Windows only?

### DISCUSSION THREAD

**Discussion by mrkurt** [goreleaser/goreleaser#2140] [Q&A] [answered]
We need to include an additional dependency with our windows build. Is it possible to do that in our single config, or do we need to create a windows-only config?

**Comment by caarlos0** [comment, marked as answer]
something like:

```yaml
builds:
- id: build1
  goos: ['linux', 'darwin']
- id: build2
  goos: ['darwin']
archives:
- id: archive1
  ids: ['build1']
- id: archive2
  ids: ['build2']
  files:
    - extra_file_windows_only
```

should work
