### DISCUSSION TITLE
Multiple Archives?

### DISCUSSION THREAD

**Discussion by ainsleyclark** [goreleaser/goreleaser#2216] [Q&A] [answered]
Hi there,

Thanks for the great project.
Im just wondering how to release multiple archives for my application 
Ive had a look at [#705](https://github.com/goreleaser/goreleaser/issues/705) and it seems as if it has been implemented but can't see a way to do it [here](https://goreleaser.com/customization/archive/).

Hope someone can help :)

Many thanks.

**Comment by caarlos0** [comment, marked as answer]
`archives` is a YAML list, just add several entries and their configs:

```yaml
archives:
  - id: archive1
     # etc...
  - id: archive2
      # etc...
```
