### DISCUSSION TITLE
Publishing scoop/brews to an internal git server [gitblit]?

### DISCUSSION THREAD

**Discussion by eolder** [goreleaser/goreleaser#2240] [Q&A] [answered]
Hello, I'm hoping someone here can help me with this. I wasn't sure if it was a bug or a bad config, so I posted here rather than open an issue.

Right now I'm using Go Releaser to help build&package a CLI. The packaging and building is working excellently! However, I was hoping I'd be able to use Go Releaser to deploy scoops/brews to some internal repositories. This doesn't seem to be possible currently? 

When I run Go Releaser with the following configuration,
```
project_name: ....

# BUILD STEP
builds:
    some stuff

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: x86
      amd64: x86_64

brews:
  -
    #skip_upload: true
    url_template: "https://eolder@Y.X.com/gitblit/r/homebrew-X.git/{{ .ArtifactName }}"
    homepage: "https://www.X.com"
    description: "X command line utility"
    tap:
      owner: Xowner
      name: Xname
    install: |
      bin.install "Xutil"

scoop:
    #skip_upload: true
    url_template: "https://eolder@Y.X.com/gitblit/r/scoop-X.git/{{ .ArtifactName }}"
    homepage: "https://www.X.com"
    description: "X command line utility"
    # The project name and current git tag are used in the format string.
    commit_msg_template: "release: X command line utility: {{ .Version }} for Windows"
    bucket:
      owner: Xowner
      name: Xname
# Ignore the default git release
release:
  disable: true
```
it gives the following output.
```
<hooks/builds/archiving/etc steps>
• publishing       
      • blobs            
      • http upload      
      • custom publisher 
      • artifactory      
      • docker images    
      • docker manifests 
      • snapcraft packages
      • github/gitlab/gitea releases
      • homebrew tap formula
         • writing                   formula=dist/Xutil.rb
         • pushing                   formula=Xutil.rb repo=X/Y
   ⨯ release failed after 9.27s error=homebrew tap formula: failed to publish artifacts: GET https://api.github.com/repos/Xowner/Xname/contents/Xutil.rb: 401 Bad credentials []
```
It seems to be completely ignoring my URL template. Is there a way to achieve what I'm trying to do here? Thanks!
