### DISCUSSION TITLE
Context when buildfing image

### DISCUSSION THREAD

**Discussion by sgaunet** [goreleaser/goreleaser#2244] [Q&A] [answered]
Hello,

I'm a bit lost with the build of a docker image. I want to add the build of a Docker image and the build failed because of file not found. I'm in the good folder when executing goreleaser but maybe the dir field places the program in the wong directory. 

[The project is here.](https://github.com/sgaunet/gitlab-backup)

I'm adding a Dockerfile at the root of the project and here is my gitreleaser configuration file :

```
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    dir: src
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    hooks:
      post:
        - upx "{{ .Path }}"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  # You can have multiple Docker images.
  -
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Templates of the Docker image names.
    image_templates:
    - "sgaunet/gitlab-backup:latest"
    - "sgaunet/gitlab-backup:{{ .Tag }}"
    - "sgaunet/gitlab-backup:v{{ .Major }}"

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

```

The Dockerfile : 

```
FROM golang:1.15.0-alpine AS builder
LABEL stage=builder

# ARG GITLAB_TOKEN
# ARG USERNAME

RUN apk add --no-cache git

#ENV GOPRIVATE="gitlab.com/.../.../libs/golibexample/golibexample"

# RUN echo "machine gitlab.com" > ~/.netrc
# RUN echo "    login ${USERNAME}" >> ~/.netrc
# RUN echo "    password ${GITLAB_TOKEN}" >> ~/.netrc

# Install UPX
ADD https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz /usr/local
RUN xz -d -c /usr/local/upx-3.96-amd64_linux.tar.xz | \
    tar -xOf - upx-3.96-amd64_linux/upx > /bin/upx
RUN chmod a+x /bin/upx

COPY src/  /go/src/gitlab-backup/src/
COPY src/go.mod /go/src/gitlab-backup/

WORKDIR /go/src/gitlab-backup/src
RUN go get && \
    CGO_ENABLED=0 GOOS=linux go build #-a gitlab-backup

RUN /bin/upx /go/src/gitlab-backup/src/gitlab-backup
##################################################################


FROM alpine:3.12.1

COPY --from=builder /go/src/gitlab-backup/src/gitlab-backup            /usr/bin/gitlab-backup
RUN chmod +x /usr/bin/gitlab-backup

```

I know I could do simpler but I like the idea of multi stage build. 

Hereis the error : 

```
Step 6/14 : RUN chmod a+x /bin/upx
 ---> Using cache
 ---> a6700be3b3ee
Step 7/14 : COPY src/  /go/src/gitlab-backup/src/
COPY failed: file not found in build context or excluded by .dockerignore: stat src/: file does not exist
: exit status 1
```

Even if I write the Dockerfile as the docker build was executedin src dir, I've got same error. So where is executed docker build ? Thanks
