### DISCUSSION TITLE
Exclude Binary Folder

### DISCUSSION THREAD

**Discussion by ainsleyclark** [goreleaser/goreleaser#2296] [Q&A] [answered]
Hi, 
Apologies if this has been covered before. 
I'm looking to create an archive only for my release with no directories containing the binary.
I have tried using `skip` on the build, but this skips, the archive too.
Many thanks in advance.

```yaml
project_name: project
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "mac"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    binary: "build/project"
archives:
  -
    id: mac
    builds:
      - mac
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "project"
    files:
      - README.md
      - LICENCE
      - build
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```
