### DISCUSSION TITLE
GitHub Action does always skip the Release

### DISCUSSION THREAD

**Discussion by JeromeK13** [goreleaser/goreleaser#2299] [Q&A] [answered]
Hey Guys

Im currently running the following action with success, but be builded binaries do not get release.

(Normal push to master)

```yaml
name: release

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./src
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASE_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

```

Output:
```
[...,]
  • building binaries
      • building                  binary=/home/runner/work/ops/ops/src/dist/ops_darwin_arm64/ops
      • building                  binary=/home/runner/work/ops/ops/src/dist/ops_linux_386/ops
      • building                  binary=/home/runner/work/ops/ops/src/dist/ops_linux_amd64/ops
      • building                  binary=/home/runner/work/ops/ops/src/dist/ops_linux_arm64/ops
      • building                  binary=/home/runner/work/ops/ops/src/dist/ops_darwin_amd64/ops
   • archives         
      • creating                  archive=dist/ops_v0.0.0-SNAPSHOT-809d6be_darwin_amd64.tar.gz
      • creating                  archive=dist/ops_v0.0.0-SNAPSHOT-809d6be_darwin_arm64.tar.gz
      • creating                  archive=dist/ops_v0.0.0-SNAPSHOT-809d6be_linux_amd64.tar.gz
      • creating                  archive=dist/ops_v0.0.0-SNAPSHOT-809d6be_linux_arm64.tar.gz
      • creating                  archive=dist/ops_v0.0.0-SNAPSHOT-809d6be_linux_386.tar.gz
   • creating source archive
   • linux packages   
   • snapcraft packages
   • calculating checksums
      • checksumming              file=ops_v0.0.0-SNAPSHOT-809d6be_linux_386.tar.gz
      • checksumming              file=ops_v0.0.0-SNAPSHOT-809d6be_darwin_amd64.tar.gz
      • checksumming              file=ops_v0.0.0-SNAPSHOT-809d6be_linux_arm64.tar.gz
      • checksumming              file=ops_v0.0.0-SNAPSHOT-809d6be_darwin_arm64.tar.gz
      • checksumming              file=ops_v0.0.0-SNAPSHOT-809d6be_linux_amd64.tar.gz
   • signing artifacts
   • docker images    
   • publishing       
      • blobs            
      • http upload      
      • custom publisher 
      • artifactory      
      • docker images    
         • pipe skipped              error=publishing is disabled
      • docker manifests 
         • pipe skipped              error=publishing is disabled
      • snapcraft packages
         • pipe skipped              error=publishing is disabled
      • github/gitlab/gitea releases
         • pipe skipped              error=publishing is disabled
      • homebrew tap formula
      • scoop manifests  
         • pipe skipped              error=publishing is disabled
      • milestones       
         • pipe skipped              error=publishing is disabled
   • announcing       
      • twitter          
         • pipe skipped              error=announcing is disabled
   • release succeeded after 90.13s

```

Also tried it with added Tags for the Push, which only created the normal Tag-release with the sourcode as zip

Any Ideas?

Greets Jerome

**Comment by caarlos0** [comment, marked as answer]
you need to push a tag, and also your workflow needs to run on tags, not just main and PRs...

https://goreleaser.com/ci/actions/

**Reply by JeromeK13** [reply]
Strange, i tried that one with the following config now
But i only get the Tag release with Source-Code
```yml
name: release

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./src
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASE_TOKEN }}
```
