### DISCUSSION TITLE
goreleaser archive - zip format

### DISCUSSION THREAD

**Discussion by HarshaVardhanNakkina** [goreleaser/goreleaser#2313] [Q&A] [answered]
```yaml
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```
I was using the above config for my project [go-wallpaper](https://github.com/HarshaVardhanNakkina/go-wallpaper)
When I use this config, goreleaser generates files without any error, in tar.gz format
but it is giving me the following error
when I use this config
```yaml
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  - format: zip
  - replacements:
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

![error](https://user-images.githubusercontent.com/48801182/123514613-7bd45300-d6b1-11eb-9956-5085c2070898.png)
I just changed the default format (which is tar.gz) to zip
when is this behaviour?
Please help me

**Comment by caarlos0** [comment, marked as answer]
It has nothing to do with the format, you're accidentally creating 2 archives:

```yaml
archives:
  - format: zip
  - replacements:
      amd64: x86_64
```

needs to be:

```yaml
archives:
  - format: zip
    replacements:
      amd64: x86_64
```
