### DISCUSSION TITLE
With docker_manifests enabled, how not to push docker image

### DISCUSSION THREAD

**Discussion by Loyalsoldier** [goreleaser/goreleaser#2317] [Q&A] [answered]
With the following docker and docker_manifests config, docker images `username/myrepo:latest-386`, `username/myrepo:latest-amd64` and `username/myrepo:latest-arm64` will also be pushed to DockerHub.

I wonder how to only push image `username/myrepo:latest`?

```yaml
dockers:
  - build_flag_templates:
      - --platform=linux/386
      - --pull
    use_buildx: true
    dockerfile: ./Dockerfile
    image_templates:
      - "username/myrepo:latest-386"

  - build_flag_templates:
      - --platform=linux/amd64
      - --pull
    use_buildx: true
    dockerfile: ./Dockerfile
    image_templates:
      - "username/myrepo:latest-amd64"

  - build_flag_templates:
      - --platform=linux/arm64
      - --pull
    use_buildx: true
    dockerfile: ./Dockerfile
    image_templates:
      - "username/myrepo:latest-arm64"

docker_manifests:
  - name_template: "username/myrepo:latest"
    image_templates:
      - "username/myrepo:latest-386"
      - "username/myrepo:latest-amd64"
      - "username/myrepo:latest-arm64"
```

**Comment by caarlos0** [comment, marked as answer]
afaik its not possible because the manifest tool needs the images to be pushed... you can try to create a manifest locally with unpushed images and it will fail as well...

**Reply by Loyalsoldier** [reply]
BTW, I don't know why this Docker multi-platform build failed(without docker_manifests):

```yaml
dockers:
  - use: buildx
    dockerfile: ./Dockerfile
    build_flag_templates:
      - --pull
      - --output=registry
      - --platform=linux/386,linux/amd64,linux/arm64
    image_templates:
      - "username/myrepo:latest"
      - "username/myrepo:{{ .Tag }}"
      - "username/myrepo:v{{ .Major }}"
      - "username/myrepo:v{{ .Major }}.{{ .Minor }}"
    ids:
      - mybuild
```

Any suggestion? Thanks!

**Comment by Loyalsoldier** [comment]
AFAIK, run the following command will build and push multi-platform images to DockerHub without redundant images `username/myrepo:latest-386`, `username/myrepo:latest-amd64` and `username/myrepo:latest-arm64`:

```shell
docker buildx build --platform linux/386,linux/amd64,linux/arm64 \
                    --output=registry \
                    --tag "username/myrepo:latest" \
                    --file Dockerfile .
```

It seems Goreleaser doesn't support this.

**Reply by caarlos0** [reply]
that's assuming all images are built from the same dockerfile, which is something goreleaser can't assume...

goreleaser first builds the images, pushes them, and then uses `docker manifest create`  to create the manifest and then push it.

**Reply by Loyalsoldier** [reply]
Why not extend it? I think the following configs are intuitive:

```yaml
dockers:
  - use: buildx
    dockerfile: ./Dockerfile
    build_flag_templates:
      - --pull
      - --output=registry
      - --platform=linux/386,linux/amd64,linux/arm64
    image_templates:
      - "username/myrepo:latest"
      - "username/myrepo:{{ .Tag }}"
      - "username/myrepo:v{{ .Major }}"
      - "username/myrepo:v{{ .Major }}.{{ .Minor }}"
    ids:
      - mybuild
```

or

```yaml
dockers:
  - use: buildx
    dockerfile: ./Dockerfile
    buildx_flag:
      - --pull
      - --output=registry
      - --platform=linux/386,linux/amd64,linux/arm64
      - --tag=latest
      - --tag={{ .Tag }}
      - --tag=v{{ .Major }}
      - --tag=v{{ .Major }}.{{ .Minor }}
    ids:
      - mybuild
    owner: username
    repo: myrepo
```
