### DISCUSSION TITLE
File name has project name twice

### DISCUSSION THREAD

**Discussion by ciokan** [goreleaser/goreleaser#2337] [Q&A] [answered]
given a project name of `foobar` and a `name_template` of `{{.ProjectName}}-v{{.Version}}` my files are produces like: `foobar_foobar-v1.0.0_linux_amd64`. Any ideas why `foobar` is repeated?

**Comment by caarlos0** [comment]
Can you share your full configuration? Also, which goreleaser version?

**Comment by ciokan** [comment]
It's all good. It's doing this way only when doing snapshots it seems. Not on release. I do have a `name_template` on snapshot as well though: `name_template: '{{.ProjectName}}-v1.0.0'` 

The following is the generated config (inside the dist folder):

```
project_name: foobar
release:
  name_template: '{{.ProjectName}}-v{{.Version}}'
milestones:
- repo:
  name_template: '{{ .Tag }}'
brews:
- name: foobar
  tap:
    owner: foobar
    name: homebrew-tap
  install: bin.install "foobar"
  homepage: https://foobar.com
  goarm: "6"
scoop:
  name: foobar
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
builds:
- id: foobar-nohttp3
  goos:
  - freebsd
  - netbsd
  - openbsd
  - dragonfly
  - linux
  - darwin
  - windows
  goarch:
  - "386"
  - arm
  - mips
  - mipsle
  - mips64
  - mips64le
  goarm:
  - "5"
  - "6"
  - "7"
  gomips:
  - softfloat
  - hardfloat
  targets:
  - freebsd_386
  - freebsd_arm_5
  - freebsd_arm_6
  - freebsd_arm_7
  - netbsd_386
  - netbsd_arm_5
  - netbsd_arm_6
  - netbsd_arm_7
  - openbsd_386
  - openbsd_arm_5
  - openbsd_arm_6
  - openbsd_arm_7
  - linux_386
  - linux_arm_5
  - linux_arm_6
  - linux_arm_7
  - linux_mips_softfloat
  - linux_mips_hardfloat
  - linux_mipsle_softfloat
  - linux_mipsle_hardfloat
  - linux_mips64_softfloat
  - linux_mips64_hardfloat
  - linux_mips64le_softfloat
  - linux_mips64le_hardfloat
  - windows_386
  - windows_arm_5
  - windows_arm_6
  - windows_arm_7
  dir: .
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    -X main.builtBy=goreleaser
  binary: foobar
  env:
  - CGO_ENABLED=0
  lang: go
  gobinary: go
- id: foobar
  goos:
  - freebsd
  - netbsd
  - openbsd
  - dragonfly
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  goarm:
  - "6"
  gomips:
  - hardfloat
  targets:
  - freebsd_amd64
  - freebsd_arm64
  - netbsd_amd64
  - openbsd_amd64
  - openbsd_arm64
  - dragonfly_amd64
  - linux_amd64
  - linux_arm64
  - darwin_amd64
  - darwin_arm64
  - windows_amd64
  dir: .
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    -X main.builtBy=goreleaser
  flags:
  - -tags=http3
  binary: foobar
  env:
  - CGO_ENABLED=0
  lang: go
  gobinary: go
archives:
- id: default
  builds:
  - foobar-nohttp3
  - foobar
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  allow_different_binary_count: false
nfpms:
- file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if
    .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
  package_name: foobar
  dependencies:
  - curl
  apk:
    scripts:
      postupgrade: .goreleaser/apk/post-upgrade
  overrides:
    apk:
      scripts:
        postinstall: .goreleaser/apk/post-install
        preremove: .goreleaser/apk/pre-deinstall
    deb:
      scripts:
        postinstall: .goreleaser/deb/postinst
        preremove: .goreleaser/deb/prerm
    rpm:
      scripts:
        postinstall: .goreleaser/rpm/postinst
        preremove: .goreleaser/rpm/prerm
  id: default
  builds:
  - foobar-nohttp3
  - foobar
  formats:
  - deb
  - rpm
  - apk
  section: net
  priority: standard
  bindir: /usr/bin
snapshot:
  name_template: '{{.ProjectName}}-v1.0.0'
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^foobar:'
  sort: asc
dist: dist
signs:
- id: default
  cmd: gpg
  args:
  - -u
  - office@foobar.com
  - --output
  - ${signature}
  - --detach-sign
  - ${artifact}
  signature: ${artifact}.sig
  artifacts: all
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
before:
  hooks:
  - go mod tidy
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
gomod:
  gobinary: go
announce:
  twitter:
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .GitURL
      }}/releases/tag/{{ .Tag }}'
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com

```
