### DISCUSSION TITLE
How to publish `latest` s3 blob?

### DISCUSSION THREAD

**Discussion by ruudk** [goreleaser/goreleaser#2375] [Q&A] [answered]
I'm publishing my releases to S3 using the `blobs` feature:
```yaml
blobs:
  -
    provider: s3
    region: eu-west-1
    bucket: my-bucket
    folder: "{{ .ProjectName }}/{{.Tag}}"
```

On the consumer side, I want to always download the `latest` version. 

Does anybody have a trick how to do this?

I was thinking of putting a `latest` file on the bucket that contains the latest version. The consumer can download that first, and then download `bucket.s3.eu-west-1.amazonaws.com/projectname/{latest}/binary.{latest}.tar.gz`.

How do I do this easily? Or are there better ways to do this?

**Comment by caarlos0** [comment, marked as answer]
You would probably have to change the `archive` name template to not have a version, and then you could have:

```yaml
blobs:
  -
    provider: s3
    region: eu-west-1
    bucket: my-bucket
    folder: "{{ .ProjectName }}/{{.Tag}}"
  -
    provider: s3
    region: eu-west-1
    bucket: my-bucket
    folder: "{{ .ProjectName }}/latest"
```

so it would have both `v1.2.3/myapp.tar.gz` and `latest/myapp.tar.gz`.
