### DISCUSSION TITLE
Cannot Release Homebrew Tap to GITHUB while Releases are on Gitlab

### DISCUSSION THREAD

**Discussion by danielsatanik** [goreleaser/goreleaser#2443] [Q&A] [answered]
Hi,

I'm using Gitlab CI/CD to test, build and publish to Gitlab. But for Homebrew its more convenient to have the tap repo on github, as I do not have to write down the repo URL as a second parameter. When I first set it up for Gitlab, it worked out of the box.

To use it on Gitlab I first created a personal access token with repo rights and then added it to the variables of the CI/CD settings of the gitlab project. Afterwards I adapted the .gitlab-ci.yaml to pass on the variable to goreleaser. I then added the token to the brews[0].tab.token in the .goreleaser.yaml. From that point on it continously failed with:

```
⨯ error getting file for brew formula err=GET https://gitlab.com/api/v4/projects/<owner>/<tap-repo>/repository/files/<app>.rb: 401 {message: 401 Unauthorized} fileName=<app>.rb projectID=<owner>/<tap-repo> ref=master statusCode=401
257   ⨯ release failed after 155.55s error=homebrew tap formula: failed to publish artifacts: GET https://gitlab.com/api/v4/projects/<owner>/<tap-repo>/repository/files/<app>.rb: 401 {message: 401 Unauthorized}
```

I thought it is weird that it even tries to get the formula from that location because it should be on the release page or the target at least on github. Either way I then also provided the correct url_template from the examples. For whatever reason though it just keeps telling me 401 Unauthorized. Have I missed an important step?

```yaml
# .gitlab-ci.yaml
variables:
  REPO_NAME: gitlab.com/<owner>/<app-repo>

stages:
  - test
  - release

test:
  stage: test
  image: golang:latest
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  only:
    refs:
      - tags
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
    GIT_DEPTH: 0
    HOMEBREW_TAP_GITHUB_TOKEN: $HOMEBREW_TAP_GITHUB_TOKEN
  script: |
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/<owner>/<app-repo> \
      -w /go/src/gitlab.com/<owner>/<app-repo> \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      -e HOMEBREW_TAP_GITHUB_TOKEN \
      goreleaser/goreleaser:v0.173.2 release --rm-dist
```

```yaml
# .goreleaser.yaml
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: <app>
    binary: <app>
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - '-s'
      - '-w'
archives:
  - id: <app>
    builds:
      - <app>
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
nfpms:
  - id: <app>
    package_name: <app>
    builds:
      - <app>
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    maintainer: <owner>
    license: <license>
    formats:
      - apk
      - deb
      - rpm
brews:
  - name: <app>
    tap:
      owner: <owner>
      name: <tap-repo>
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/<owner>/<tap-repo>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      bin.install "<app>"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

Any idea in which step I messed up?
