### DISCUSSION TITLE
HTTPS Error 500 - Internal Server Error while trying to download a RPM package created using goreleaser

### DISCUSSION THREAD

**Discussion by pskrbasu** [goreleaser/goreleaser#2499] [Q&A] [answered]
Hi,
We have been using goreleaser to create Linux packages for our project [Steampipe](https://github.com/turbot/steampipe). We used NFPM customization to create RPM and DEB packages. We tried something like this:
```
nfpms:
  - id: "steampipe"
    builds: ['steampipe']
    formats:
      - deb
      - rpm
    vendor: "steampipe.io"
    homepage: "https://steampipe.io/"
    maintainer: "Turbot <puskar@turbot.com>"
    description: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    rpm:
      summary: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
```
(https://github.com/turbot/steampipe/pull/797/files#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689R27) 
to create the packages. 
The DEB package works perfectly as per our expectations, but the RPM package generated by this after uploading to a `yum repository` in Google Artifact Registry returns an `HTTPS Error 500 - Internal Server Error while trying to download` error.
We have verified creating the RPM package from source using the classic `rpm-build`, that the yum repository set up in Google Cloud works.
Is there something we are missing to add as part of our NFPM goreleaser configuration? Can anyone point us what we might need to add/do to make it work?
