### DISCUSSION TITLE
404 project not found error while releasing in gitlab CE

### DISCUSSION THREAD

**Discussion by SindhuSrinivas08** [goreleaser/goreleaser#2517] [Q&A] [answered]
I am using golang to create a simple CLI application. I am using GoReleaser to release this to Gitlab. I followed the steps outlined in https://goreleaser.com/quick-start/ to release changes to gitlab.
I have generated a personal access token with API scope. I am tagging the changes and pushing them before I use the goreleaser to publish artifacts. 

I always get the error which says release failed after 452.34s error=github/gitlab/gitea releases: failed to publish artifacts: Get "https://PRIVATEGITLABURL/api/v4/projects/PRIVATE_GITLAB_PROJECT/releases/v1%2E0%2E3": dial tcp IP_ADDRESS:443: connect: operation timed out.

My .gorelease.yml file

```
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# .goreleaser.yml
gitlab_urls:
  api: https://PRIVATE_GITLAB_REPO/api/v4/
  download: https://PRIVATE_GITLAB_REPO
  # set to true if you use a self-signed certificate
  skip_tls_verify: false 
```
My gitlab version is GitLab Enterprise Edition 14.1.5-ee 

As an alternative, I added a .gitlab-ci.yml file and pushed my changes. GitLab pipeline fails saying  ⨯ release failed after 39.66s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://PRIVATE_REPO/api/v4/projects/[MASKED]@PRIVATE_REPO/PRIVATE_PROJECT_PATH/releases: 404 {message: 404 Project Not Found}

**Comment by developer-guy** [comment, marked as answer]
hi @SindhuSrinivas08, please you can follow this [configuration](https://goreleaser.com/customization/release/#gitlab), and set the release section according to your project settings like the following:

```YAML
# .goreleaser.yml
release:
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # You can also use Gitlab's internal project id by setting it in the name
  #  field and leaving the owner field empty.
  gitlab:
    owner: user
    name: repo. 
```

maybe this one can help 🤝🙋🏻‍♂️
