### DISCUSSION TITLE
How to debug ”not publishing“

### DISCUSSION THREAD

**Discussion by pgundlach** [goreleaser/goreleaser#2611] [Q&A] [answered]
I have a young repository on Github and I'd like to publish a package. This repository has no tags, two commits and no releases yet.

I run `goreleaser release --snapshot --rm-dist --debug`. A directory `dist` gets created (looks good) but the last debug lines show:

```
• skipped signing artifacts
• skipped docker images    
• skipped publishing       
• skipped announcing       
• release succeeded after 4.23s
```

And nothing gets published to the GitHub repo. 

How can I debug this? Is there anything I can provide (config files, output, ...) that would help you pointing me in the right direction?

I am in the top directory of the git repository where the `.goreleaser.yml` file resides. This is the end of the file (after the contents that `goreleaser init` created`).

```
release:
  github:
    owner: speedata
    name: ets
  draft: false
  discussion_category_name: General
  prerelease: auto
  header: |
    ## Some title ({{ .Date }})

    Welcome to this new release!

  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

  # You can change the name of the release.
  # Default is `{{.Tag}}` on OSS and `{{.PrefixedTag}}` on Pro.
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
  disable: false
```

`goreleaser check` gives me:

```
   • loading config file       file=.goreleaser.yml
   • checking config: 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • loading go mod information
      • building binaries
      • universal binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images    
      • docker manifests 
      • artifactory      
      • blobs            
      • homebrew tap formula
      • gofish fish food cookbook
      • scoop manifests  
      • discord          
      • reddit           
      • slack            
      • teams            
      • twitter          
      • smtp             
      • mattermost       
      • milestones       
      • telegram         
   • config is valid  
```

```
goreleaser --version
goreleaser version 0.183.0
commit: be6199f08167cc85b0b16cefc02d8106237853b1
built by: homebrew

https://goreleaser.com
```
