### DISCUSSION TITLE
Execution order of multiple archives

### DISCUSSION THREAD

**Discussion by faenschi** [goreleaser/goreleaser#2628] [Q&A] [answered]
hi

is it possible to define the execution order or the archives? i want to create a .zip archive and then another one, which contains the zip i created first (zipTwo depends on zipOne):

```
archives:
    - id: bindelivery
      name_template: '{{ .ProjectName }}-{{ .Version }}.bin'
      format: binary
      allow_different_binary_count: false
    - id: zipOne
      name_template: '{{ .ProjectName }}-deploy-{{ .Version }}'
      format: zip
      allow_different_binary_count: false
      files:
        - src: '<someFiles>'
          dst: '/bin'
          strip_parent: true
    - id: zipTwo
      name_template: 'RemoteInstaller-{{ .ProjectName }}-{{ .Version }}'
      format: zip
      allow_different_binary_count: false
      files:
        - src: 'dist/{{ .ProjectName }}-deploy-{{ .Version }}.zip'
          dst: '/'
          strip_parent: true
        - src: 'somemorefiles'
          dst: '/'
          strip_parent: true
```

as i recognized the order of archive generation is random, so sometimes it works and sometimes not :-(

regards angela
