### DISCUSSION TITLE
How to pass --config file to github action?

### DISCUSSION THREAD

**Discussion by ItsIgnacioPortal** [goreleaser/goreleaser#2644] [Q&A] [answered]
I have the following gorelease.yml:

```yml
name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        run: cd $GITHUB_WORKSPACE && wget https://raw.githubusercontent.com/PinkDev1/hacker-scoper/main/.github/.goreleaser.yml && pwd
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      -
        name: run GoReleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: latest
          args: release --rm-dist --config $GITHUB_WORKSPACE/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
```

but it can never open the config file:
```
   ⨯ release failed after 0.00s error=open $GITHUB_WORKSPACE/.goreleaser.yml: no such file or directory
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.184.0/x64/goreleaser' failed with exit code 1
```

How should I supply a config file to the github action?

**Comment by crazy-max** [comment]
@PinkDev1 shell vars are not expanded for the actions inputs but you can use `${{ github.workspace }}/.goreleaser.yml`. Also looking at your workflow it's not necessary to pass the `--config` flag because it already defaults to the current working dir.

**Reply by ItsIgnacioPortal** [reply]
I've tried what you suggested:

```yml
name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        run: cd ${{ github.workspace }} && wget https://raw.githubusercontent.com/PinkDev1/hacker-scoper/main/.github/.goreleaser.yml && pwd
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      -
        name: run GoReleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: latest
          args: release --rm-dist --config ${{ github.workspace }}/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
```

But it fails with the same error 🤨
```
   ⨯ release failed after 0.00s error=open /home/runner/work/hacker-scoper/hacker-scoper/.goreleaser.yml: no such file or directory
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.184.0/x64/goreleaser' failed with exit code 1
```

I've made the repo public so you can see the full output, if that helps: https://github.com/PinkDev1/hacker-scoper/runs/4142305376?check_suite_focus=true
