### DISCUSSION TITLE
How to notarize zip file

### DISCUSSION THREAD

**Discussion by pgundlach** [goreleaser/goreleaser#2664] [Q&A] [answered]
I feel embarrassed to ask this question, but how do I notarize a ZIP file? The ZIP file includes the binary and other assets.

My `.goreleaser.yml` file has a section `builds`:

```yml
builds:
  - id: "notmac"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    main:
      ./ets/ets
    binary:
      bin/ets
  - id: "mac"
    binary:
      bin/ets
    goos:
      - darwin
    goarch:
      - amd64
    main:
      ./ets/ets
    env:
      - CGO_ENABLED=0
    hooks:
      post: gon config.hcl
```

and I can see that the binary is signed. 

My `config.hcl` looks like this:

```
source = ["./dist/mac_darwin_amd64/bin/ets"]
bundle_id = "de.speedata.ets"

apple_id {
  username = "@env:AC_USERNAME"
  password = "@env:AC_PASSWORD"
}

sign {
  application_identity = "Developer ID Application: myname (someid)"
}
```

I assume I need to add some config to run notarisation for the mac zip file. Should I put the `xcrun altool --notarize-app .. ` command line in the `sings:` section of the config file? But there is no signature file for that which should go in the configuration `signature: `

**Comment by dirien** [comment]
Ping in help from @caarlos0 :)

**Comment by caarlos0** [comment]
I don't know either, we don't notarize our macos releases (we should).

Eventually (next year more likely) I'll get an "apple developer whatever-its-called thingy" so I can experiment with this.

I thinks its likely we'll do some sort of native integration and/or broad the signing API and document examples et al.

All that being said, there is an example on the gon's readme but I'm not sure its complete: https://github.com/mitchellh/gon#usage-with-goreleaser

**Comment by pgundlach** [comment, marked as answer]
What works for me is 

```
signs:
  - id: macsign
    cmd: xcrun
    args: ["altool", "--notarize-app", "--primary-bundle-id", "myid" , "-u", "myusername , "-t" ,"osx","-f", "${artifact}"]
    artifacts: archive
    ids:
      - mac
    stdin: '{{ .Env.AC_PASSWORD }}'
```

I have not released anything for some time, but I believe that this worked.
