### DISCUSSION TITLE
Gitlab CI does not upload to generic packages repo

### DISCUSSION THREAD

**Discussion by jabbrwcky** [goreleaser/goreleaser#2718] [Q&A] [answered]
Hi,

I am building a releasing a small go tool to our internal Gitlab instance using goreleaser 1.1.0. The release works fine but the HTTP upload fails to upload any artifacts (and no the debug output is not really helpful in that case):

```
   • publishing       
      • skipped blobs            
      • http upload      
         • will upload 0 artifacts 
```

As for the configuration the project does nothing fancy:

```yaml
gitlab_urls:
  api: https://<gitlab host>/api/v4/
  download: https:/<gitlab host>

uploads:
  - name: gitlab
    mode: binary
    target: "{{ .Env.CI_API_V4_URL }}/projects/{{ .Env.CI_PROJECT_ID }}/packages/generic/{{ .ProjectName }}/{{ .Version }}/"
    method: PUT
    custom_headers:
      JOB-TOKEN: "{{ .Env.CI_JOB_TOKEN }}"

universal_binaries:
- replace: true
```

The debug output shows that there are a number of binaries built:

```
   • building binaries
      • building                  build={terragrunt-pipeline [linux darwin] [amd64 arm64 386] [6] [hardfloat] [linux_amd64 linux_arm64 linux_386 darwin_amd64 darwin_arm64] [] . . [-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser] [] [] terragrunt-pipeline {[] []} [] go [] []  false go false  }
      • building                  binary=/builds/k8s/terragrunt-pipeline/dist/terragrunt-pipeline_linux_386/terragrunt-pipeline
      • building                  binary=/builds/k8s/terragrunt-pipeline/dist/terragrunt-pipeline_darwin_arm64/terragrunt-pipeline
      • building                  binary=/builds/k8s/terragrunt-pipeline/dist/terragrunt-pipeline_linux_amd64/terragrunt-pipeline
      • building                  binary=/builds/k8s/terragrunt-pipeline/dist/terragrunt-pipeline_linux_arm64/terragrunt-pipeline
      • building                  binary=/builds/k8s/terragrunt-pipeline/dist/terragrunt-pipeline_darwin_amd64/terragrunt-pipeline
```

Any idea what could be amiss here?
