### DISCUSSION TITLE
GoReleaser no remote configure to life refs from

### DISCUSSION THREAD

**Discussion by eofreternal** [goreleaser/goreleaser#2755] [Q&A] [answered]
GoReleaser check spits out
```
   • loading config file       file=.goreleaser.yml
   • checking config: 
      • snapshotting     
      • scm releases     
   ⨯ config is invalid error=no remote configured to list refs from
   ⨯ command failed            error=invalid config: no remote configured to list refs from
```

this is my .goreleaser.yml file
```
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

project_name: Golang-AutoClicker
```
