### DISCUSSION TITLE
How to use build tags properly

### DISCUSSION THREAD

**Discussion by sebbbastien** [goreleaser/goreleaser#2887] [Q&A] [answered]
Hi,

I'm using go build tags to compile the `main.go`, but with different `config.go` files, one config file for each customer.

In `.goreleaser-pro.yml` file, I have multiple builds defined:
```yaml
[...]
builds:
  - id: myProg-customerA
    binary: myProg
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X "main.buildVersion={{ .Version }}"
      - -X "main.commitID={{ .Commit }}"
      - -X "main.buildDate={{ .Date }}"
    tags:
      - customerA
    env:
      - CUSTOMER=customerA
    hooks:
      pre: go generate ./...

  - id: myProg-customerB
    binary: myProg
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X "main.buildVersion={{ .Version }}"
      - -X "main.commitID={{ .Commit }}"
      - -X "main.buildDate={{ .Date }}"
    tags:
      - customerB
    env:
      - CUSTOMER=customerB
    hooks:
      pre: go generate ./...

  - id: myProg-customerC
    binary: myProg
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X "main.buildVersion={{ .Version }}"
      - -X "main.commitID={{ .Commit }}"
      - -X "main.buildDate={{ .Date }}"
    tags:
      - customerC
    env:
      - CUSTOMER=customerC
    hooks:
      pre: go generate ./...

[...]
```

On each build entry I must have the same lines, just the customer name is changing.
I use the CUSTOMER environment variable to tell go generate the files it have to create.

Is there another way to do that without copy/paste?

Thanks in advance, and thanks for your time!
