### DISCUSSION TITLE
help when building apk packages with NFPM

### DISCUSSION THREAD

**Discussion by artynet** [goreleaser/goreleaser#2901] [Q&A] [answered]
hello folks, please herlp figure out what i am missing....this is a basic template for building cross-platform tarballs and packages:
```
build:
  binary: <binary>
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
  ignore:
    - goos: darwin
      goarch: 386
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w # Don't set main.version.

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
  format_overrides:
    - goos: windows
      format: zip

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "task_checksums.txt"

# Override default project name and settings.
project_name: <binary>

nfpm:
    vendor: <vendor>
    homepage: <url>
    maintainer: <maintainer>
    description: <description>
    license: <license>
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk
```
anyway, I am not able to build the APK packages getting this error:
```
⨯ release failed after 1.51s error=no packager registered for the format apk
```
what am i missing ? For sure i have to install the **rpmbuild** tool on my ubuntu system to pack the RPM binaries but I don't know how to install the alpine/android packager. My setup is:

* Ubuntu 21.04
* goreleaser 1.4.1
* nfpm 2.12.2

thanks in advance for your help.
 
Arturo

**Comment by caarlos0** [comment]
Shouldn't need to install anything besides goreleaser...

How did you install goreleaser?

Oh, and the nfpm field should be pluralized, and an array. 

Please refer to the docs for details

**Comment by artynet** [comment]
I have installed goreleaser and nfpm both as binary DEB packages on my system. Building an array-like this:

```
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage: https://nfpm.goreleaser.com
  description: |-
    Simple, 0-dependencies, deb, rpm and apk packager.
    nFPM (not FPM) is configurable via YAML and does not need any
    packaging software installed.
  maintainer: Carlos Alexandro Becker <carlos@becker.software>
  license: MIT
  vendor: GoReleaser
  formats:
  - apk
  - deb
  - rpm
  bindir: /usr/bin
  section: utils
```

taken from the nfpm main source, together with the **builds** construct brings me another error like this:

```
  • releasing using goreleaser dev...
   • loading config file       file=.goreleaser.yml
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 40: field nfpms not found in type config.Project
```
