### DISCUSSION TITLE
goreleaser build docker images successfully but publish failed

### DISCUSSION THREAD

**Discussion by alexcdever** [goreleaser/goreleaser#2915] [Q&A] [answered]
The goreleaser was executing in github action, and I found the docker step of goreleaser will automatically skip the publish step, but I can push manually the docker image in the step of github action. Do you know why?

github action configuration file:
```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        uses: docker/login-action@v1.12.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: # optional
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_HUB_PASSWORD}}
          # Specifies whether the given registry is ECR (auto, true or false)
          # ecr: # optional, default is auto
          # Log out from the Docker registry at the end of a job
          # logout: # optional, default is true
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - 
        name: get docker info
        run: docker info
      
      - name: push docker image
        run: docker push alexcdever/image-hosting-service:main-amd64

```

goreleaser configuration file:

```yaml

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy -v
builds:
  -
    dir: media
    main: media.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - 
    goarch: "amd64"
    goos: "linux"
    skip_push: false
    image_templates:
      - "alexcdever/{{ .ProjectName }}:{{ .Branch }}-amd64"
      - "alexcdever/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=cn.alexc.image.created={{.Date}}"
      - "--label=cn.alexc.image.title={{.ProjectName}}"
      - "--label=cn.alexc.image.revision={{.FullCommit}}"
      - "--label=cn.alexc.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - media/etc/media-api.yaml
  - 
    goarch: "arm64"
    goos: "linux"
    skip_push: false
    image_templates:
      - "alexcdever/{{ .ProjectName }}:{{ .Branch }}-arm64v8"
      - "alexcdever/{{ .ProjectName }}:latest-arm64v8"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=cn.alexc.image.created={{.Date}}"
      - "--label=cn.alexc.image.title={{.ProjectName}}"
      - "--label=cn.alexc.image.revision={{.FullCommit}}"
      - "--label=cn.alexc.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
    extra_files:
      - media/etc/media-api.yaml
docker_manifests:

- name_template: alexcdever/{{ .ProjectName }}:{{ .Branch }}
  image_templates:
  - alexcdever/{{ .ProjectName }}:{{ .Branch }}-amd64
  - alexcdever/{{ .ProjectName }}:{{ .Branch }}-arm64v8
  skip_push: false

- name_template: alexcdever/{{ .ProjectName }}:latest
  image_templates:
  - alexcdever/{{ .ProjectName }}:{{ .Branch }}-amd64
  - alexcdever/{{ .ProjectName }}:{{ .Branch }}-arm64v8
  skip_push: false

#snapshot:
#  name_template: "{{ incpatch .Version }}-next"
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
```

the github action log of goreleaser step:
```
Run goreleaser/goreleaser-action@v2
  with:
    distribution: goreleaser
    version: latest
    args: release --rm-dist
    workdir: .
    install-only: false
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    GOROOT: /opt/hostedtoolcache/go/1.17.7/x64
    GITHUB_TOKEN: 
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.5.0/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/ba596b1d-6ecc-4830-add7-8570327c9e63 -f /home/runner/work/_temp/507b[44](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:6:44)e4-39c6-[49](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:6:49)32-89f9-bc10e03dbb1d
GoReleaser latest installed successfully
No tag found for commit '28b8389'. Snapshot forced
/opt/hostedtoolcache/goreleaser-action/1.5.0/x64/goreleaser release --rm-dist --snapshot
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • couldn't find any tags before "0.0.1"
      • building...               commit=28b83890c98b372b6b2bbf6b19901[58](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:6:58)5d17afd88 latest tag=0.0.1
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag      
   • running before hooks
      • running                   hook=go mod tidy -v
   • setting defaults 
   • snapshotting     
      • building snapshot...      version=0.0.1-SNAPSHOT-[28](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:6:28)b8[38](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:6:38)9
   • checking distribution directory
   • loading go mod information
   • build prerequisites
   • writing effective config file
      • writing                   config=dist/config.yaml
   • building binaries
      • building                  binary=dist/image-hosting-service_darwin_arm64/image-hosting-service
      • building                  binary=dist/image-hosting-service_windows_amd64/image-hosting-service.exe
      • building                  binary=dist/image-hosting-service_windows_arm64/image-hosting-service.exe
      • building                  binary=dist/image-hosting-service_darwin_amd64/image-hosting-service
      • building                  binary=dist/image-hosting-service_linux_arm64/image-hosting-service
      • building                  binary=dist/image-hosting-service_linux_amd64/image-hosting-service
   • archives         
      • creating                  archive=dist/image-hosting-service_Windows_arm64.zip
      • creating                  archive=dist/image-hosting-service_Linux_arm64.tar.gz
      • creating                  archive=dist/image-hosting-service_Windows_x86_64.zip
      • creating                  archive=dist/image-hosting-service_Darwin_arm64.tar.gz
      • creating                  archive=dist/image-hosting-service_Darwin_x86_64.tar.gz
      • creating                  archive=dist/image-hosting-service_Linux_x86_64.tar.gz
   • calculating checksums
   • docker images    
      • building docker image     image=***/image-hosting-service:main-arm64v8
      • building docker image     image=***/image-hosting-service:main-amd64
      • pipe skipped              error=publishing is disabled
   • storing release metadata
      • writing                   file=dist/artifacts.json
      • writing                   file=dist/metadata.json
   • release succeeded after 197.87s
```

the log of pushing docker image manually step:
```
Run docker push ***/image-hosting-service:main-amd64
  docker push ***/image-hosting-service:main-amd64
  shell: /usr/bin/bash -e {0}
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    GOROOT: /opt/hostedtoolcache/go/1.17.7/x64
The push refers to repository [docker.io/***/image-hosting-service]
b065b1deb6e6: Preparing
c[2](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:2)84[3](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:3)551ee17: Preparing
01a82[4](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:4)44431e: Preparing
[5](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:5)4cb5c9cc08a: Preparing
8d3ac348999[6](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:6): Preparing
8d3ac3489996: Mounted from library/alpine
b065b1deb6e6: Pushed
01a82444431e: Pushed
54cb5c9cc08a: Pushed
c2843551ee1[7](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:7): Pushed
main-amd64: digest: sha256:b91292cae236[8](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:8)2a552f543a1db142c21cd1f733b03aab37dba24204f0a[9](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:9)22b20 size: [13](https://github.com/alexcdever/image-hosting-service/runs/5226534745?check_suite_focus=true#step:8:13)62
```
