### DISCUSSION TITLE
Docker images section not appearing in release section

### DISCUSSION THREAD

**Discussion by xoanmm** [goreleaser/goreleaser#2972] [Q&A] [answered]
I've been following the steps in the [tutorial](https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/) posted for publishing multi-platform docker images with goreleaser, and I noticed that I don't get the Docker Images section in the releases section, as shown in the [tutorial image](https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/54b3b826-1a23-4b6f-a9a9-aaba029fabd1.png)

I leave below information about the scenario in which this case occurred:
- [generated release](https://github.com/xoanmm/check-christmas-lottery-numbers/releases/tag/v1.1.64)
- [github actions configuration for release](https://github.com/xoanmm/check-christmas-lottery-numbers/blob/main/.github/workflows/release.yml)
- [goreleaser configuration](https://github.com/xoanmm/check-christmas-lottery-numbers/blob/main/goreleaser.yml)

Has anything changed in the latest versions of goreleaser or do I need to configure something additional to be able to see this section?

**Comment by caarlos0** [comment, marked as answer]
Hey, that tutorial is from November 2020, so its a bit outdated.

That feature was removed in v1.2.0 - see https://github.com/goreleaser/goreleaser/pull/2708

You can add it back by customizing the release footer with something like:

```
## Docker Images

- `myuser/myimg:{{ .Version }}`
- `otherregistry.foo/user/img:{{ .Version }}`
```

See https://goreleaser.com/customization/release/ for more options

**Reply by xoanmm** [reply]
Hello,

Thanks for your quick response, I have updated the [goreleaser configuration](https://github.com/xoanmm/check-christmas-lottery-numbers/blob/main/goreleaser.yml) following the instructions that you mention, I added the section with footer:
```
release:
  github:
    owner: xoanmm
    name: check-christmas-lottery-numbers
  footer: |
    ## Docker Images
    - `xoanmallon/check-christmas-lottery-numbers:{{ trimprefix .Tag "v" }}`
    - `xoanmallon/check-christmas-lottery-numbers:latest`
    - `ghcr.io/xoanmm/check-christmas-lottery-numbers:{{ trimprefix .Tag "v" }}`
    - `ghcr.io/xoanmm/check-christmas-lottery-numbers:latest`
```

But in the [last release](https://github.com/xoanmm/check-christmas-lottery-numbers/releases/tag/v1.1.67) is still without this footer. 

I think that the workflow configuration has the necessary permissions, as it has write permissions for both packages and contents. Is it necessary to perform any additional steps?
