### DISCUSSION TITLE
Can't get it to work with go1.18

### DISCUSSION THREAD

**Discussion by enex** [goreleaser/goreleaser#2991] [Q&A] [answered]
I have a simple `.goreleaser.yml` file that looks like
```yaml
project_name: notes
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/notes
    id: notes
    binary: notes
    goos:
      - linux
      #- windows
      #- darwin
    goarch:
      - amd64
      #- arm64
```
And I have go 1.18 installed and it works if i just compile it with the terminal. However if I execute `goreleaser build --snapshot --rm-dist`It always error with
` ⨯ build failed after 9.04s error=failed to parse dir: cmd/notes: cmd/notes/main.go:29:13: expected ']', found any (and 5 more errors)`
This seems to me as if it is assuming it where go1.17 or earlier because this was not valid in this version. How can I fix that?
