### DISCUSSION TITLE
Checksums not identical with two builds using two config files

### DISCUSSION THREAD

**Discussion by steffakasid** [goreleaser/goreleaser#3002] [Q&A] [answered]
Hi,

for some reasons I need to use two config files as with one I publish to artifactory with the other I generate a brew tap and publish to GitLab. I expected that the outcome from goreleaser for both would be the same and generally when using gorleaser build it looks like that. But when the artifacts are getting published, the checksums are different. Is there any explanation for that behavior:

Regards
Steffen

**Comment by caarlos0** [comment]
can you provide a reproducible?

**Comment by steffakasid** [comment]
Yes I can reproduce it with the two .goreleaser config files:

.goreleaser-gitlab.yaml
```
before:
  hooks:
    - go mod tidy
builds:
  - id: cli
    tags:
      - build
    ldflags:
      - -X main.appVersion={{.Version}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums-{{ .Tag }}.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gitlab_urls:
  api: https://local-url.de/api/v4/
  download: https://local-url.de
  use_package_registry: false
release:
  mode: replace
brews:
  - tap:
      owner: inner-source
      name: tokenizer
      branch: master
    url_template: "{{ .Env.ARTIFACTORY_REPO }}/{{ .ProjectName }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaser
      email: dummy@somehost.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: https://local-url.de:inner-source/tokenizer
    license: DBISL
```

.goreleaser.yaml
```
before:
  hooks:
    - go mod tidy
builds:
  - id: cli
    tags:
      - build
    ldflags:
      - -X main.appVersion={{.Version}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums-{{ .Tag }}.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gitlab_urls:
  api: https://local-url.de/api/v4/
  download: https://local-url.de
  use_package_registry: false
release:
  disable: true
artifactories:
  - name: production
    mode: archive
    target: "{{ .Env.ARTIFACTORY_REPO }}/{{ .ProjectName }}/"
    checksum: true
    signature: true
```

Afterward I run the following:

1.  `goreleaser release --skip-publish --rm-dist --config .goreleaser-gitlab.yaml`
2. `shasum -a 256 dist/tokenizer_0.10.0-next_Darwin_arm64.tar.gz` which prints: `1c056afb4ad843109bd9ea000b600991126da605cad828744c51cd391ba739a1  dist/tokenizer_0.10.0-next_Darwin_arm64.tar.gz`
3. `goreleaser release --skip-publish --rm-dist`
4. `shasum -a 256 dist/tokenizer_0.10.0-next_Darwin_arm64.tar.gz` which prints `e0c87415d135143ae57c83ccaa7d7dab4c51f76d86c2ce76c699d26a21bda80a  dist/tokenizer_0.10.0-next_Darwin_arm64.tar.gz`

So we have two builds with two different checksums on the same tagged source code.
