### DISCUSSION TITLE
goreleaser triggers a docker build fail.

### DISCUSSION THREAD

**Discussion by remyleone** [goreleaser/goreleaser#3014] [Q&A] [answered]
Hello, I got the following configuration:

https://github.com/scaleway/scaleway-cli/blob/master/.goreleaser.yml

Which lead to the following logs:

https://github.com/scaleway/scaleway-cli/runs/5772430036?check_suite_focus=true

I have no idea why the docker command failed to copy. When I do it in local with docker it works natively, the go.mod file is also present at the root of the repository. Do you have any idea why it might go wrong?

**Comment by caarlos0** [comment, marked as answer]
the dockerfile should merely copy an already built binary, archive or package

check https://goreleaser.com/customization/docker/#how-it-works for more info

**Reply by remyleone** [reply]
The copy is not working. So even if it was something really simple like a copy I don't see how it could work. Are the docker commands launched from the root of the repository?

**Reply by caarlos0** [reply]
it didn't work because its trying to copy the source... only the binaries/archives for the platform being built are available... 

example: https://github.com/goreleaser/goreleaser/blob/main/Dockerfile#L23

Also, take a look at the documentation, it should be explained there: https://goreleaser.com/customization/docker

**Reply by djarbz** [reply]
I'm stuck on this as well, I'm trying to build for Linux amd64, arm64, armv6, and armv7.
```
   • building binaries        
      • building                  binary=dist/smtpsmartrelay_linux_amd64/smtpSmartRelay
      • building                  binary=dist/smtpsmartrelay_linux_arm64/smtpSmartRelay
      • building                  binary=dist/smtpsmartrelay_linux_arm_6/smtpSmartRelay
      • building                  binary=dist/smtpsmartrelay_linux_arm_7/smtpSmartRelay
```

Docker section of the .goreleaser.yaml
```
dockers:
  # https://goreleaser.com/customization/docker/
  # Linux/amd64
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:latest'
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

  # Linux/arm64v8
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-arm64v8'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-arm64v8'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64v8'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-arm64v8'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:latest'
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

  # Linux/armv6
  - use: buildx
    goos: linux
    goarch: arm
    goarm: '6'
    image_templates:
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-armv6'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-armv6'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-armv6'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-armv6'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:latest'
    build_flag_templates:
      - --platform=linux/armv6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

  # Linux/armv7
  - use: buildx
    goos: linux
    goarch: arm7
    image_templates:
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-armv7'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-armv7'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-armv7'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-armv7'
      - 'registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:latest'
    build_flag_templates:
      - --platform=linux/armv7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://gitlab.com/djarbz/golang/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  # Tag
  - name_template: registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-amd64
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-armv6
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Tag }}-armv7

  # Version
  - name_template: registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-amd64
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-armv6
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-armv7

  # Major.Minor
  - name_template: registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
    image_templates:
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64v8
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-armv6
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-armv7

  # Major
  - name_template: registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}
    image_templates:
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-amd64
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-arm64v8
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-armv6
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Major }}-armv7

  # Latest
  - name_template: registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:latest
    image_templates:
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-amd64
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-armv6
      - registry.gitlab.com/djarbz/golang/{{ .ProjectName }}:{{ .Version }}-armv7
```

Dockerfile
```
FROM scratch
COPY smtpSmartRelay /usr/bin/smtpSmartRelay
ENTRYPOINT ["/usr/bin/smtpSmartRelay"]
```

Fail Log
```
• docker images            
      • building docker image     image=registry.gitlab.com/djarbz/golang/smtpsmartrelay:0.0.1-alpha02
      • building docker image     image=registry.gitlab.com/djarbz/golang/smtpsmartrelay:0.0.1-alpha02
      • building docker image     image=registry.gitlab.com/djarbz/golang/smtpsmartrelay:0.0.1-alpha02
      • building docker image     image=registry.gitlab.com/djarbz/golang/smtpsmartrelay:0.0.1-alpha02
   ⨯ release failed after 425.02s error=failed to build registry.gitlab.com/djarbz/golang/smtpsmartrelay:0.0.1-alpha02: exit status 1: #1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 133B done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s
#3 [internal] load build context
#3 transferring context: 2B done
#3 DONE 0.0s
#4 [1/1] COPY smtpSmartRelay /usr/bin/smtpSmartRelay
#4 ERROR: "/smtpSmartRelay" not found: not found
------
 > [1/1] COPY smtpSmartRelay /usr/bin/smtpSmartRelay:
------
error: failed to solve: failed to compute cache key: "/smtpSmartRelay" not found: not found
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

How can I specify which binary gets copied into the docker image?
