### DISCUSSION TITLE
Reproducible build using go build

### DISCUSSION THREAD

**Discussion by h0x0er** [goreleaser/goreleaser#3099] [Q&A] [answered]
I am trying to create reproducible build of the binary created using `goreleaser` with `go build`. But the checksum is not matching.
 Is it possible to have same checksum ?

Below is the yaml file I am using
```yml
# .goreleaser.yml
builds:
  # You can have multiple builds defined as a yaml list
  -
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64

    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}


    # Optionally override the matrix generation and specify only the final list of targets.
    # Format is `{goos}_{goarch}` with optionally a suffix with `_{goarm}` or `_{gomips}`.
    # This overrides `goos`, `goarch`, `goarm`, `gomips` and `ignores`.
    targets:
      - linux_amd64
```
Below is the `go build ` command I am using
```bash 
go build -trimpath -ldflags="-s -w -X main.version='<tag>' -X main.commit='<commitSHA>' -X main.date='<commitDate>'" 
```
