### DISCUSSION TITLE
Archive by build id

### DISCUSSION THREAD

**Discussion by mrpalide** [goreleaser/goreleaser#3104] [Q&A] [answered]
Hey guys.
Does available anyway to archive by build id beside goos-goarch?
Means if I have these two builds:
```
builds:
  - id: app
    binary: app
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/app/

  - id: app-nightly
    binary: app
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
    tags:
      - nightly
    env:
      - CGO_ENABLED=0
    main: ./cmd/app/
```
after building, they will be in separated folders `app_xxx` and `app-nightly_xxx`.
Does available anyway to make two archive file that once be `app_xxx.tar.gz` and other be `app-nightly_xxx.tar.gz` that contain related folder files? Also, could be multiple binary with multiple nightly or normal folder, means `app_xxx` and `app-update_xxx` and two others for nightly.

**Comment by mrpalide** [comment, marked as answer]
Oh! Find it! Should use `builds` filed in `archives` part. Like this:
```
archives:
  - id: normal
    format: tar.gz
    wrap_in_directory: false
    name_template: 'app-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - app
      - app-update
  - id: nightly
    format: tar.gz
    wrap_in_directory: false
    name_template: 'app-nightly-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - app-nightly
      - app-update-nightly
```
