### DISCUSSION TITLE
GoReleaser reports successful twitter notification, but no update in twitter

### DISCUSSION THREAD

**Discussion by ga-paul-t** [goreleaser/goreleaser#3112] [Q&A] [answered]
Having successfully created a Twitter developer app with elevated access, I configured GoReleaser to publish a notification as follows:

```yaml
announce:
  skip: "{{gt .Patch 0}}"

  twitter:
    enabled: true
    message_template: "My custom message"
```

GoReleaser reports a successful post to Twitter, but nothing appears in the Twitter feed of my account:

```sh
   • announcing       
      • twitter          
         • posting: 'My custom message'
```

Just wondering if anyone else has experienced this?
