### DISCUSSION TITLE
prebuilt: Multiple paths

### DISCUSSION THREAD

**Discussion by rfay** [goreleaser/goreleaser#3188] [Ideas, Issue Triage, and General discussions]
I'm experimenting with Goreleaser Pro's prebuilt feature.

For Windows, DDEV has not just the standard ddev.exe binary, but also has a ddev_windows_installer.exe binary. But it seems that only one path is allowed in `prebuilt:`. What's the "path" around this?

Here's what I'm currently experimenting with:

https://github.com/rfay/ddev/blob/aae7346797e193a698ac040047d6f686866863e4/.goreleaser.yml#L15-L17

Edit: I'm going to assume you just have to have multiple "builds" for this case?

**Comment by caarlos0** [comment]
You're correct! You'd need multiple builds, probably with different binary names as well.

Something like:

```yaml
builds:
- id: default 
  builder: prebuilt
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  goamd64: [v1]
  ignore:
    - goos: windows
      goarch: arm64
  prebuilt:
    path: .gotmp/bin/{{.Os}}_{{.Arch}}/ddev{{.Ext}}
  binary: ddev
- id: windows-installer
  builder: prebuilt
  goos: [windows]
  goarch: [amd64]
  goamd64: [v1]
  prebuilt:
    path: .gotmp/bin/windows_amd64/ddev_windows_installer.exe
  binary: ddev_installer
```
