### DISCUSSION TITLE
Homebrew config: Token for owner

### DISCUSSION THREAD

**Discussion by rfay** [goreleaser/goreleaser#3197] [Ideas, Issue Triage, and General discussions]
In the [homebrew config](https://goreleaser.com/customization/homebrew/?h=brew) you specify the setup of the tap with an owner and a name:

```
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: repo-owner
      name: homebrew-tap
```

Is there a token I can use to set the owner to the current repo's owner? I need this for testing, as I will push to drud/homebrew-ddev in production, but I typically need to test lots on rfay/homebrew-ddev. And if I fiddle with the `owner` entry it's too likely that I'll mess up and leave it as the wrong one.
