### DISCUSSION TITLE
GitHub Action to build multiple, independent executable targets (not just GOOS...)?

### DISCUSSION THREAD

**Discussion by mgingios** [goreleaser/goreleaser#3244] [Q&A] [answered]
How can I configure the GoReleaser GitHub Action to build multiple, independent executable targets?  I have a repository that contains a subdirectory to build a gRPC server (server/main.go) and other directory to build an http proxy for the gRPC server (proxy/main.go).  I can build one or the other of these servers, but cannot figure out how to build both as part of the build release action.  I am using Go, and will take advantage of the cross-platform builds for each of them.  Here are the two release configurations...  Ideally, the build artifacts for the proxy server would have "-proxy-" in the name.  I'd appreciate any help...  I am sure that others must be trying to do this kind of thing... It could be a good CookBook item, I think.

```
#      - name: Run GoReleaser for the gRPC Server
#        uses: goreleaser/goreleaser-action@v3
#        with:
#          # either 'goreleaser' (default) or 'goreleaser-pro'
#          distribution: goreleaser
#          version: latest
#          args: "release --rm-dist"
#          workdir: "server"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

      - name: Run GoReleaser for the HTTP Proxy Server
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: "release --rm-dist"
          workdir: "proxy"
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
```
