### DISCUSSION TITLE
How to add 'docker save' compressed images in a release?

### DISCUSSION THREAD

**Discussion by mgingios** [goreleaser/goreleaser#3246] [Q&A] [answered]
Hello,  In my GitHub Action, I generate two docker images using Paketo BuildPacks and save them to tar.gz files.  I would like to include these compressed tar.gz files in the release.  I've tried to use the archive.files and release.extra_files options, but neither of them populate these files in the draft release.  Can you please help me to achieve this goal?  I've included the .goreleaser.yaml file, below.

```
      - name: Export Dockers to tar.gz
        run: |
          docker save "abcd.azurecr.io/track-service-amd64-linux:4.1.0.rc2"       | gzip > track-service-amd64-linux_4.1.0.rc2.tar.gz
```

```
## .goreleaser.yaml
project_name: track

builds:
  - skip: true

release:
  draft: true
#  extra_files:
#    - glob: ./track-service-amd64-linux_4.1.0.rc2.tar.gz
#    - glob: ./track-service-proxy-amd64-linux_4.1.0.rc2.tar.gz

archives:
  - files:
      - track-service-amd64-linux_4.1.0.rc21tar.gz
      - track-service-proxy-amd64-linux_4.1.0.rc2.tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```
