### DISCUSSION TITLE
Can a GitHub secret be using in .goreleaser.yaml?

### DISCUSSION THREAD

**Discussion by mgingios** [goreleaser/goreleaser#3250] [Q&A] [answered]
Hello,

I am configuring signing in .goreleaser.yaml.  Is it possible to use a GitHub Secret for the 'stdin' field?  Something like, 

${{ secret.COSIGN_PWD }}

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PWD }}'
    args: ["sign-blob", "-key=security/cosign.key", "-output=${signature}", "${artifact}"]
    artifacts: checksum

**Comment by mgingios** [comment, marked as answer]
Here is the way to use a GitHub Secret with goreleaser's signing:

Created a signing key-pair using the cosign cli.
Copy the private key file, cosign.key, into your source tree.  I put mine in a folder named 'security'.
Create a GitHub Secret named, "COSIGN_PWD", and set its value to the password you used when creating the key-pair.
In your workflow file, add an environment variable for COSIGN_PWD to goreleaser:

```
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
```

In your .goreleaser.yaml file, configure signing using the environment variable.  Here is what I did for my use-case:

```
checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    args: ["sign-blob", "--key=security/cosign.key", "--output-signature=${signature}", "${artifact}"]
    stdin: '{{ .Env.COSIGN_PWD }}'
    artifacts: all

docker_signs:
  - cmd: cosign
    args: ["sign-blob", "--key=security/cosign.key", "--output-signature=${signature}", "${artifact}"]
    stdin: '{{ .Env.COSIGN_PWD }}'
    artifacts: all
```

In my release flow, I add the cosign cli to the release, so the binary exists to validate checksums regardless of whether it is supported in the future.

This configuration is working properly.  There are other ways to perform signing so I will leave it up to others to post variations.  I invite the goreleaser team to correct anything that I've posted, if necessary.

I hope that this is helpful.
