### DISCUSSION TITLE
how do I change the output path of the binary to be built?

### DISCUSSION THREAD

**Discussion by tigerinus** [goreleaser/goreleaser#3290] [Q&A] [answered]
The expected structure of archive is:

```
/build/bin/output_binary
/build/etc/...
/build/usr/lib...
```

Currently the binary is put at

```
/build/bin/
/build/etc/...
/build/usr/lib...
output_binary <- here
```

How do I configure such that the `output_binary` is put under the desired path?

Thanks!

**Comment by tigerinus** [comment, marked as answer]
I should've read the doc thoroughly:

```yaml
# .goreleaser.yaml
builds:
  -
    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: program
```
