### DISCUSSION TITLE
Multi-line variable

### DISCUSSION THREAD

**Discussion by grzesuav** [goreleaser/goreleaser#3300] [Q&A] [answered]
Hi,

I am experimenting with `gorelease`, one thing which is missing on my setup is that configuration is very big
* configuration - https://github.com/grzesuav/metacontroller/blob/master/.goreleaser.yaml
is there a way I could use some templating to i.e. set `image labels` once and then re-use them ?

Help appreciated !

**Comment by caarlos0** [comment, marked as answer]
On the [pro](https://goreleaser.com/pro) you can use the `variables` section: https://goreleaser.com/customization/templates/#custom-variables

On OSS, you might be able to get around with the root environment section.

On both, you might be able to reuse some code with advanced yaml features (like referencing parts of the config in other places), although it arguably looks less readable than just repeating the code...

Hope this helps

**Reply by grzesuav** [reply]
Actually I tried https://stackoverflow.com/questions/24656798/is-it-possible-to-anchor-a-literal-block-in-yaml however gorleleaser does not accept that. I tried multiline env variables but it does not want to work (or I do it wrongly)

Will try more approach, was hoping someone have example at hand

**Reply by caarlos0** [reply]
its hard to help without an example of the code that fails and which error you're getting though...

**Reply by grzesuav** [reply]
I tried https://github.com/metacontroller/metacontroller/pull/593 but got an error 
```
release failed after 0s                  error=yaml: line 1: did not find expected '-' indicator
```

**Reply by grzesuav** [reply]
will do some testing today also, but on local env

**Reply by caarlos0** [reply]
yes, that will not work because env only accepts an array of envs...

**Reply by grzesuav** [reply]
I also tried 
```yaml
env:
  - REPOSITORY_OWNER={{ if index .Env "REPOSITORY_OWNER"  }}{{ .Env.REPOSITORY_OWNER }}{{ else }}local{{ end }}
  - DOCKER_BUILD_FLAGS=--label=org.opencontainers.image.title={{ .ProjectName }} \
    --label=org.opencontainers.image.description={{ .ProjectName }} \
    --label=org.opencontainers.image.url=https://github.com/metacontroller/{{ .ProjectName }} \
    --label=org.opencontainers.image.source=https://github.com/metacontroller/{{ .ProjectName }} \
    --label=org.opencontainers.image.version=v{{ .Version }} \
    --label=org.opencontainers.image.created={{ .Date }} \
    --label=org.opencontainers.image.revision={{ .FullCommit }} \
    --label=org.opencontainers.image.licenses=Apache-2.0
...
dockers:
- image_templates:
  - "{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:v{{ .Version }}-amd64"
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
    - --platform=linux/amd64
    - "{{ .Env.DOCKER_BUILD_FLAGS }}"

```
however it does not resolves correctly: 
```json
"Labels": {
                "org.opencontainers.image.title": " \\ --label=org.opencontainers.image.description= \\ --label=org.opencontainers.image.url=https://github.com/metacontroller/ \\ --label=org.opencontainers.image.source=https://github.com/metacontroller/ \\ --label=org.opencontainers.image.version=v \\ --label=org.opencontainers.image.created=2022-08-15T11:16:35Z \\ --label=org.opencontainers.image.revision= \\ --label=org.opencontainers.image.licenses=Apache-2.0"
            }
```

**Reply by grzesuav** [reply]
It seems if I use variables in env, not all of them are resolved. Nevethless I tried 
```
env:
  - REPOSITORY_OWNER={{ if index .Env "REPOSITORY_OWNER"  }}{{ .Env.REPOSITORY_OWNER }}{{ else }}local{{ end }}
  - DOCKER_BUILD_FLAGS= 
    --label=org.opencontainers.image.title="Metacontroller"
    --label=org.opencontainers.image.description="Metacontroller"
    --label=org.opencontainers.image.url=https://github.com/metacontroller/metacontroller
    --label=org.opencontainers.image.source=https://github.com/metacontroller/metacontroller
    --label=org.opencontainers.image.version=v{{ .Version }}
    --label=org.opencontainers.image.created={{ .Date }}
    --label=org.opencontainers.image.revision={{ .FullCommit }}
    --label=org.opencontainers.image.licenses=Apache-2.0
```
however in debug mode I can observe
```shell
    • running args=[--builder default build . --load -t localio/metacontroller:v4.3.1-next-amd64 -t ghcr.io/local/metacontroller:v4.3.1-next-amd64 --platform=linux/amd64  --label=org.opencontainers.image.title="Metacontroller" --label=org.opencontainers.image.description="Metacontroller" --label=org.opencontainers.image.url=https://github.com/metacontroller/metacontroller --label=org.opencontainers.image.source=https://github.com/metacontroller/metacontroller --label=org.opencontainers.image.version=v --label=org.opencontainers.image.created=2022-08-15T11:30:31Z --label=org.opencontainers.image.revision= --label=org.opencontainers.image.licenses=Apache-2.0] cmd=[docker buildx] cwd=dist/goreleaserdocker1269598216
    • error: "docker buildx build" requires exactly 1 argument. cmd=[docker buildx] cwd=dist/goreleaserdocker1269598216

```

**Reply by caarlos0** [reply]
you won't be able to do that... 

what I meant by using env would be to avoid repetition of the templates themselves, e.g.:

```yaml
env:
  label1: --label=org.opencontainers.image.version=v{{ .Version }}
  label2: etc...

dockers:
- build_flag_templates:
  - label1
  - label2
```

**Reply by grzesuav** [reply]
ah, got it. Was hoping on something like in gitlab - https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#yaml-anchors-for-scripts

**Reply by grzesuav** [reply]
@caarlos0 would you be interested if I open feature request to allow multiline templating ? I think everyone building multiple images will appreciate that

**Reply by caarlos0** [reply]
I think you don't need to change anything in goreleaser tbh...

```yaml
dockers:
- image_templates:
  - "{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:v{{ .Version }}-amd64"
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates: &build-flags
    - --label=org.opencontainers.image.title="Metacontroller"
    - --label=org.opencontainers.image.description="Metacontroller"
    - --label=org.opencontainers.image.url=https://github.com/metacontroller/metacontroller
    - --label=org.opencontainers.image.source=https://github.com/metacontroller/metacontroller
    - --label=org.opencontainers.image.version=v{{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=Apache-2.0
    - --platform=linux/amd64
- image_templates: [etc]
  build_flag_templates: 
    - *build-flags
    - --platform=linux/arm64
```

something like that could work

but again, this IMHO just make the config harder to read, I'd rather do a little repetition... specially since when things don't work, people will open issues, and I'll have to review them... 😂

**Reply by grzesuav** [reply]
Tried that and with
```yaml
build_flag_templates: 
    - *build-flags
```
have 
```yaml
  ⨯ build failed after 0s                    error=yaml: unmarshal errors:
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
  line 41: cannot unmarshal !!seq into string
```
(line 41 is the one with `build_flag_templates: &build-flags`)

also tried
```yaml
    build_flag_templates:
      *build-flags
      - --platform=linux/arm64/v8
```

which also does not work


What works is 
```yaml
    build_flag_templates: *build-flags
```


however I cannot override any values this way...
