### DISCUSSION TITLE
need to create a manifest of built files but build hooks don't seem to help

### DISCUSSION THREAD

**Discussion by tigerinus** [goreleaser/goreleaser#3308] [Q&A] [answered]
Hello,

I am trying to create a manifest file of all built files, just so that I can use it for uninstallation purpose.

I have following `build`:

```yaml
  - 
    binary: build/sysroot/usr/bin/myapp # along with other files under build/sysroot/
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - find build/sysroot -type f | xargs -L 1 realpath --relative-to=build/sysroot > build/sysroot.manifest
```

I have following `archive`

```yaml
  -
    name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-v{{ .Version }}"
    files:
      - build/**/*
```

However I don't see the `build/systroot.manifest` in the archive.

Am I missing anything?

Thanks.
