### DISCUSSION TITLE
Complete Gon/goreleaser workflow for signing and notarizing

### DISCUSSION THREAD

**Discussion by dekimsey** [goreleaser/goreleaser#3350] [Ideas, Issue Triage, and General discussions]
I was trying to use gon and goreleaser together and couldn't find decent example of how to make them play together _especially_ with any name template usage. It's messy.

I think the crux of the issue is that gon and goreleaser have differing workflows. We have somewhat conflicting interests. For instance:
  - goreleaser builds the binary
  - goreleaser wants to archive the binary
  - But gon needs to sign the binary first, in goreleaser's workflow this happens last
  - gon also is config driven
  - user needs to notarize the package (dmg, zip)
  - but notarize requires signed binaries in the archive
  - gon will archive if you give it the binaries

Etc.

The docs on either side (goreleaser's or gon's) are incomplete in how to wire up a complete solution (sign & notarize) or when they do, they gloss over the unsupported hard-coded naming behavior.

Here is an end-to-end example I was able to make work (required acquiring the Developer ID (for signing) and an Installer ID (for notarizing) cert [as documented](https://github.com/mitchellh/gon#prerequisite-acquiring-a-developer-id-certificate) in hon). Having to generate the gon.hcl on the fly makes it pretty clunky. Ideally, I think instead of trying to shell-out to gon, gorealeaer integrates it as a library and triggers the requisite steps (sign binary after build, perform notarize after archive) correctly.

I'm sharing this in hopes that it might motivate creating a better workflow or integration.

Thank you!

<details><summary>complete goreleaser.yml config</summary>
<p>

```
# .goreleaser.yml
project_name: myapp
before:
  hooks:
    - go mod tidy
    - go mod download

env:
  - CGO_ENABLED=0
  # Signing parameters. Check gon's documentation on what the appropriate values should be.
  - BUNDLE_ID=com.example.myapp
  - APPLE_ID_USERNAME=dekimsey@example.com
  - APPLE_ID_PASSWORD=@keychain:m1-gon
  - "APPLE_APPLICATION_IDENTITY=Developer ID Application: Daniel Kimsey"

builds:
  - id: default
    goos: [linux, windows]
    goarch: [arm64, amd64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    ignore:
      - goos: darwin
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    mod_timestamp: "{{ .CommitTimestamp }}"
# The mac builds need to be separate because we have to sign the binaries themselves. Ideally,
# we'd do this at the sign step. But we are notarizing during the sign step. And notarizing requires
# signed binaries, but all we get from goreleaser is the archive.
  - id: macos
    goos: [darwin]
    goarch: [arm64, amd64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - |
          sh -c '
          fn=dist/macos_{{.Target}}/gon.hcl
          cat >"$fn" <<EOF
          bundle_id = "{{.Env.BUNDLE_ID}}"
          apple_id {
            username = "{{.Env.APPLE_ID_USERNAME}}"
            password = "{{.Env.APPLE_ID_PASSWORD}}"
          }
          source = ["dist/macos_{{.Target}}/{{.Name}}"]
          sign {
            application_identity = "{{.Env.APPLE_APPLICATION_IDENTITY}}"
          }
          EOF
          '
        - "gon 'dist/macos_{{.Target}}/gon.hcl'"

archives:
  - format: zip
    builds: [default]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: linux
        format: tar.gz
# We want a separate archive ID, so we can make sure to Release the correct artifact.
  - id: macos
    builds: [macos]
# Important: zip/dmg is required for notarization. 
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

signs:
# Here we do a specific notarize step _replacing_ the original artifact in-place. One could generate
# a separate archive, just be sure not to Release it.
  - id: mac-notarize
    artifacts: archive
    ids: [macos]
    signature: "${artifact}"
    output: true
    cmd: sh
    args:
      - "-c"
      - |-
        cat >"dist/gon.notarize.hcl" <<EOF
        apple_id {
          username = "{{.Env.APPLE_ID_USERNAME}}"
          password = "{{.Env.APPLE_ID_PASSWORD}}"
        }
        notarize {
          path = "${artifact}"
          bundle_id = "{{.Env.BUNDLE_ID}}"
        }
        EOF
        gon "dist/gon.notarize.hcl"

release:
  ids:
# The default artifacts for the other OS's and our notarized artifacts for OSX.
# If we don't specify this, goreleaser will double-count the artifacts from previous steps (artifacts, sign) during the Release step.
# That will fail, since our sign step replaced the originals. So we explictly inform goreleaser which artifacts to upload.
    - default
    - mac-notarize

```
</p>
</details>

For those that don't want to use gon to notarize, the notarize bits above could be replaced with:

<details><summary>notarize with notarytool</summary>
<p>

Note: notarytool will need a keychain profile pre-created to store the credentials. Run `xcrun notarytool store-credentials --apple-id "name@example.com" --team-id "DEADBEEF"` to generate profile, substituting the correct values for your Developer ID as needed.

```
    cmd: xcrun
    args:
      - "notarytool"
      - "submit"
      - "--verbose"
      - "--wait"
      - "--progress"
      - "--keychain-profile"
      - "...my-profile-name-from-the-store-credentials-line...."
      - "${artifact}"
```

</p>
</details>

Regardless, a distribution then looks like:
<details><summary>run log</summary>
<p>

**goreleaser release --rm-dist --skip-publish --skip-validate**
```
  • starting release...
  • loading config file                              file=.goreleaser.yml
  • loading environment variables
  • getting and validating git state
    • building...                                    commit=e18db40ee723b883a8c4068a3c387a92323bfc1b latest tag=v0.2.0
    • pipe skipped                                   reason=validation is disabled
  • parsing tag
  • setting defaults
  • running before hooks
    • running                                        hook=go mod tidy
    • running                                        hook=go mod download
  • checking distribution directory
    • --rm-dist is set, cleaning it up
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • generating changelog
    • writing                                        changelog=dist/CHANGELOG.md
  • building binaries
    • building                                       binary=dist/macos_darwin_amd64_v1/myapp
    • building                                       binary=dist/myapp_linux_amd64_v1/myapp
    • building                                       binary=dist/myapp_linux_arm64/myapp
    • building                                       binary=dist/macos_darwin_arm64/myapp
    • building                                       binary=dist/myapp_windows_amd64_v1/myapp.exe
    • running hook                                   hook=sh -c '
fn=dist/macos_darwin_amd64_v1/gon.hcl
cat >"$fn" <<EOF
source = ["dist/macos_darwin_amd64_v1/myapp"]
bundle_id = "com.example.myapp"
apple_id {
  username = "dekimsey@example.com"
  password = "@keychain:m1-gon"
}
sign {
  application_identity = "Developer ID Application: Daniel Kimsey"
}
EOF
'

    • running hook                                   hook=gon "dist/macos_darwin_amd64_v1/gon.hcl"
    • running hook                                   hook=sh -c '
fn=dist/macos_darwin_arm64/gon.hcl
cat >"$fn" <<EOF
source = ["dist/macos_darwin_arm64/myapp"]
bundle_id = "com.example.myapp"
apple_id {
  username = "dekimsey@example.com"
  password = "@keychain:m1-gon"
}
sign {
  application_identity = "Developer ID Application: Daniel Kimsey"
}
EOF
'

    • running hook                                   hook=gon "dist/macos_darwin_arm64/gon.hcl"
    • took: 3s
  • archives
    • creating                                       archive=dist/myapp_0.2.0_darwin_arm64.zip
    • creating                                       archive=dist/myapp_0.2.0_darwin_amd64.zip
    • took: 4s
  • calculating checksums
  • signing artifacts
    • signing                                        artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    • ==> 🍎  Notarizing...                           artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     Path: dist/myapp_0.2.0_darwin_arm64.zip  artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     Submitting file for notarization...        artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     Submitted. Request UUID: deadbeef-uuid-here-1 artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     Waiting for results from Apple. This can take minutes to hours. artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     Status: in progress                        artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     Status: success                            artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •     File notarized!                            artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •                                                artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    • Notarization complete! Notarized files:        artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    •   - dist/myapp_0.2.0_darwin_arm64.zip (notarized) artifact=myapp_0.2.0_darwin_arm64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_arm64.zip
    • signing                                        artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    • ==> 🍎  Notarizing...                           artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     Path: dist/myapp_0.2.0_darwin_amd64.zip  artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     Submitting file for notarization...        artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     Submitted. Request UUID: deadbeef-uuid-here-2 artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     Waiting for results from Apple. This can take minutes to hours. artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     Status: in progress                        artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     Status: success                            artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •     File notarized!                            artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •                                                artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    • Notarization complete! Notarized files:        artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    •   - dist/myapp_0.2.0_darwin_amd64.zip (notarized) artifact=myapp_0.2.0_darwin_amd64.zip cmd=sh signature=dist/myapp_0.2.0_darwin_amd64.zip
    • refreshing checksums                           file=myapp_0.2.0_SHA256SUMS
    • took: 3m15s
  • storing release metadata
    • writing                                        file=dist/artifacts.json
    • writing                                        file=dist/metadata.json
  • release succeeded after 3m21s
```

</p>
</details>

References:
  - https://scriptingosx.com/2021/07/notarize-a-command-line-tool-with-notarytool/
  - https://github.com/junegunn/fzf/blob/master/.goreleaser.yml#L17
  - https://github.com/goreleaser/goreleaser/discussions/2102
  - https://github.com/mitchellh/gon#usage-with-goreleaser
  - https://medium.com/anchore-engineering/developers-need-to-handle-macos-binary-signing-how-we-automated-the-solution-part-2-ad1e08caff0f
