### DISCUSSION TITLE
how build for private project, push other public project，Only release binaries?

### DISCUSSION THREAD

**Discussion by hktalent** [goreleaser/goreleaser#3449] [Q&A] [answered]
how build for private project
and push to other public project?

thanks

**Comment by hktalent** [comment]
I'd like to be able to automate compilation from a private project and just publish the binaries to another, public project of my own, without the source code

**Comment by caarlos0** [comment, marked as answer]
Docs: https://goreleaser.com/customization/release/

```yaml
# .goreleaser.yaml
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: user
    name: repo
```

---

A couple of tips for the future:
- please use discussions for questions. A good indicator you were using the wrong medium was that you couldn't properly fill the issue template.
- always search the docs first.
