### DISCUSSION TITLE
Goreleaser fails in AzureDevOps Pipeline with ##[error]Unhandled: Unexpected identifier

### DISCUSSION THREAD

**Discussion by heilingbrunner** [goreleaser/goreleaser#3515] [Q&A] [answered]
Hello,

i try to run a simple pipeline script, but it always fails with the error mentioned above.
I have searched for `goreleaser ##[error]Unhandled: Unexpected identifier` but i found no result.

My script:

```
# customize trigger to your needs
trigger:
  branches:
    include:
      - main
      - refs/tags/*

variables:
  GO_VERSION: "1.19.2"

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Release
    steps:
      - task: GoTool@0
        inputs:
          version: "$(GO_VERSION)"
        displayName: Install Go
      - task: goreleaser@0
        inputs:
          version: 'latest'
          distribution: 'goreleaser'
          args: ''
          workdir: '$(Build.SourcesDirectory)'
```

The result from the pipeline:

```
Starting: goreleaser
==============================================================================
Task         : GoReleaser
Description  : GoReleaser integration for Azure DevOps
Version      : 0.1.8
Author       : Engin Diri
Help         : https://goreleaser.com/intro/
==============================================================================
##[error]Unhandled: Unexpected identifier
Finishing: goreleaser

```

My question: What is missing ?

Thank you in advance.

**Comment by caarlos0** [comment]
maybe @dirien has an idea?

**Reply by dirien** [reply]
I will check this! 😔

**Comment by heilingbrunner** [comment]
This is my goreleaser.yaml:

```
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  -
    format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
  algorithm: md5

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```
