### DISCUSSION TITLE
Errors when adding a changelog to Slack announcements

### DISCUSSION THREAD

**Discussion by seanhoughton** [goreleaser/goreleaser#3598] [Q&A] [answered]
I'd like to include the changelog in my Slack announcements. I've tried using the following configuration:

```yaml
announce:
  slack:
    enabled: true
    message_template: "MyProduct {{.Tag}} has been released! Check it out at {{ .ReleaseURL }}"
    channel: "#my-channel"
    blocks:
      - type: "section"
        text:
          type: "plain_text"
          text: "{{ .ReleaseNotes }}"
```

However, I get the following error

```
error=slack: failed to announce release: announce: slack blocks: announce: failed to unmarshal into target: invalid character '\n' in string literal
```

I've been trying to dig through the code to understand where this is coming from. Are the release notes in plain text or markdown or html? Does anyone have any nice examples of release announcements in Slack? I've tried to search github a bit but can't find any examples.
