### DISCUSSION TITLE
[ Need help ] I can not build windows package

### DISCUSSION THREAD

**Discussion by leiyi-weee** [goreleaser/goreleaser#3632] [Q&A]
I followed the documentation tips，and run 
``` shell
goreleaser release --snapshot --rm-dist
```
But there is no windows packages, only build Linux and darwin

![image](https://user-images.githubusercontent.com/82796241/206966179-e40afe4d-63d9-486e-be8e-f771bba62af3.png)

this is the setting file, i did't do any change: 
``` yaml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

```
