### DISCUSSION TITLE
How to use plugins while building the binary?

### DISCUSSION THREAD

**Discussion by deepjyoti30** [goreleaser/goreleaser#3701] [Q&A] [answered]
Hey there! We have a repo where we are using multiple plugins that we compile into the final archive during the build. We use a makefile to build all the plugins and then we build the final binary which then uses these plugins when it runs.

I looked through `go-releaser` docs but could not find any mention of how to support plugin builds.

One possible solution at the top of my mind is using multiple builders for each plugin, however I am not sure if that is an efficient way of doing it. Is there a better approach that I was unable to find in the docs?

Can anyone point me in the right direction of how I can support plugins being built?

[For instance, this is the makefile we are using for building the plugins](https://github.com/appbaseio/reactivesearch-api/blob/dev/Makefile)

**Comment by caarlos0** [comment]
by plugins you mean what exactly?

glancing at the makefile, you seem to just build multiple binaries which are elasticsearch plugins? If so, you just need multiple `builds` in your `.goreleaser.yaml`:

```yaml
builds:
- id: plugin1
  main: .
  ldflags: [etc]
- id: plugin2
  main: .
  ldflags: [etc]
```

https://goreleaser.com/customization/build/

**Comment by deepjyoti30** [comment, marked as answer]
> by plugins you mean what exactly?

I mean go plugins that can be built with the `--buildmode=plugin` [as stated here](https://pkg.go.dev/plugin) option and can later be used in the main go file using the path of the built plugins. I am not sure if they are binaries since the built plugins have a `.so` extension.

> glancing at the makefile, you seem to just build multiple binaries which are elasticsearch plugins? If so, you just need multiple builds in your .goreleaser.yaml

I am trying this approach out to see if this works based on the requirements, I essentially want to dynamically build all the plugins in the `plugins` directory.

**Reply by caarlos0** [reply]
ah, ok, `--buildmode` is a flag, so you can use the `builds[i].flags` to specify it

**Reply by deepjyoti30** [reply]
Yeah, I already used it and getting an error, can you shed some light on this?

```
 release failed after 8s
 error=failed to build for linux_amd64_v1: exit status 1: buildmode=plugin -o ./plugins/auth.so github.com/appbaseio/reactivesearch-api/plugins/auth/main not supported
 ```
 
 Here's the config I used:
 
 ```yaml
 
-  id: plugin pipelines
    binary: plugins/pipelines.so
    flags:
      - --buildmode=plugin -o ./plugins/auth.so github.com/appbaseio/reactivesearch-api/plugins/auth/main
 ```

**Reply by caarlos0** [reply]
Flags is an array, each option needs to go as an item in it

**Reply by caarlos0** [reply]
Also you should omit the -o as it's handled by goreleaser

**Reply by caarlos0** [reply]
And the import path should be an option in the build struct as well.

**Reply by deepjyoti30** [reply]
Hey @caarlos0 thanks for the inputs. I am still getting an error even after making the changes that you suggested. Following is my updated build defined:

```yaml
- id: plugin_pipelines
    binary: auth.so
    flags:
      - --buildmode=plugin
      - github.com/appbaseio/reactivesearch-api/plugins/auth/main
    goos:
      - linux
```

Error I am getting is the following:

```sh
 error=failed to build for linux_amd64_v1: exit status 1: malformed import path "-ldflags=-s -w -X main.version=8.8.2-next -X main.commit=6a57029d4fb7e081abc9554f2c21613581c51ef7 -X main.date=2023-01-18T17:25:12Z -X main.builtBy=goreleaser": leading dash
malformed import path "-o": leading dash

stat /Users/deepjyoti30/git/reactivesearch/dist/plugin_pipelines_linux_amd64_v1/pipelines.so: directory not found
```

I am not sure how the `-o` is getting passed as I have already removed it from the yaml as you can see above.

Also, why is the directory error being thrown? I am not specifying any custom directory except the binary name.

**Reply by caarlos0** [reply]
please take a look at https://goreleaser.com/customization/build/?h=c+shared#building-shared-or-static-libraries

your config should probably be something like:

```yaml
- id: plugin_pipelines
  binary: auth.so
  main: ./plugins/auth/main
  buildmode: plugin
  goos:
  - linux
```
