### DISCUSSION TITLE
Passwordless authentication not working with custom publisher that executes scp [SOLVED]

### DISCUSSION THREAD

**Discussion by ArnoSen** [goreleaser/goreleaser#3740] [Q&A]
Hi,

I have been investigating an issue that I encounter when using a bespoke publisher using scp.

My publisher looks like this:
```
publishers:
  - name: send_somewhere
    cmd: /usr/bin/scp -i /home/me/.ssh/myprivatekey {{ abs .ArtifactPath }} user@host:/dir
```

When running the command locally, scp authenticates without asking a password.
But when the publishing action is kicked of via goreleaser, it asks for a password.
I tried specifying an identity like above, but still I am asked for a password.

Just after writing above question, I decided to give it one more go and I added an env var like this:
```
publishers:
  - name: send_somewhere
    cmd: /usr/bin/scp -i /home/me/.ssh/myprivatekey {{ abs .ArtifactPath }} user@host:/dir
    env: 
        - SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
```

This did the trick :-)

I thought that it would be good to still add this to the Q&A if somebody would run into the same situation.
