### DISCUSSION TITLE
Is it possible to use rendered template files as a source to nfpm contents?

### DISCUSSION THREAD

**Discussion by ryancurrah** [goreleaser/goreleaser#3842] [Ideas, Issue Triage, and General discussions]
I would like to use the new https://goreleaser.com/customization/templatefiles/ feature to provide rendered files to the `nfpms[0].contents` section. Where the `src` would be a rendered file from a template. Is it possible to do that? This would help us reduce a lot of manual editing of nfpm scripts.

```
nfpms:
    - id: widgetmaker-service-deb
      contents:
        - src: '.packaging/systemd_starter.sh'
          dst: '/opt/acme/bin/systemd_starter.sh'
        - src: '.packaging/systemd_unit.service'
          dst: '/opt/acme/etc/{{.Binary}}.service'
```

**Comment by caarlos0** [comment]
not at this moment, but I plan to make it available directly into some pipes, e.g.:

```yaml
nfpms:
    - id: widgetmaker-service-deb
      contents:
        - src_template_file: '.packaging/systemd_starter.sh.tpl'
          dst: '/opt/acme/bin/systemd_starter.sh'

# or:
      template_contents:
        - src: '.packaging/systemd_unit.service.tpl'
          dst: '/opt/acme/etc/{{.Binary}}.service'
```

that was my idea, at least. Any thoughts?

**Reply by ryancurrah** [reply]
I think that would be great. I can make a contribution if you don't have the time at the moment and have decided on a how to surface this up in the config.

My preference would probably be `template_contents` as it is clear that source files in this struct are going to be rendered as a template. As long as maintaining another `Contents` struct isn't to burdensome. I'm assuming you would compose the `Contents` struct in a `TemplateContents` struct.

Just throwing out more ideas, maybe a `is_template: true`, `src_is_template: true` or something in the `Contents`.

**Reply by ryancurrah** [reply]
@caarlos0 any update on this? I'm also wanting to template a `Dockerfile`.

**Reply by caarlos0** [reply]
hey, it was released in v1.17 pro:

- https://goreleaser.com/customization/nfpm/ (`templated_contents`)
- https://goreleaser.com/customization/docker/ (`templated_extra_files`)

**Reply by ryancurrah** [reply]
Is it possible to template Dockerfiles?

**Reply by caarlos0** [reply]
oh, the dockerfile contents itself not at the moment, sounds like something nice to add though 🤔

**Reply by caarlos0** [reply]
https://github.com/goreleaser/goreleaser/issues/4166

**Reply by ryancurrah** [reply]
@caarlos0 are we able to template `scripts` as well?

```yaml
scripts:
  preinstall: "scripts/preinstall.sh"
  postinstall: "scripts/postinstall.sh"
  preremove: "scripts/preremove.sh"
  postremove: "scripts/postremove.sh"
```
