### DISCUSSION TITLE
why ldflags don't take effect

### DISCUSSION THREAD

**Discussion by Fly-Playgroud** [goreleaser/goreleaser#3868] [Q&A] [answered]
This is my full config.yaml. But `ldflags` don't take effect on building

```yaml

gomod:
  proxy: true
  env:
    - GOPROXY=https://goproxy.cn,direct
    - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
- flags:
    - -trimpath
  ldflags:
    - -s -w -X ./cmd/cmd.Version={{ .Version }}
    - -X ./cmd/cmd.BuildTime={{ .Date }}
    - -X ./cmd/cmd.Commit={{ .ShortCommit }}
  env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  main: ./cmd

dockers:
-

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

announce:
  slack:
    enabled: true
    channel: '#release'
    username: GoReleaser
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'

  discord:
    enabled: true
    message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'

```
