### DISCUSSION TITLE
Docker multiplatform build fails with "unknown flag: --platform"

### DISCUSSION THREAD

**Discussion by eneskaya** [goreleaser/goreleaser#3881] [Q&A]
Hi everyone,

I have a problem when attempting to build multiplatform Docker images with goreleaser. The `dockers` section of my .goreleaser.yml file looks like this:

```
dockers:
  - image_templates:
      - tailwarden/komiser:latest
      - tailwarden/komiser:{{ .Tag }}
      - tailwarden/komiser:{{ .FullCommit }}
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform linux/amd64,linux/arm64
      - --build-arg SEGMENT_WRITE_KEY=$SEGMENT_WRITE_KEY
```

And the resulting error is 

```
    • building docker image                          image=tailwarden/komiser:v3.0.6
  ⨯ release failed after 11s                 error=docker build failed: failed to build tailwarden/komiser:v3.0.6: exit status 125: unknown flag: --platform linux/amd64,linux/arm64
```

It fails both locally, and on GitHub Actions. I followed the documentation and the tutorial here: https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/

Some environment info:

goreleaser:
```
goreleaser version 1.16.1
commit: ba2c93bf2036905fe00fd8482f293febd58c1a81
built by: homebrew
goos: darwin
goarch: arm64
```

Docker:
```
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:35:19 2023
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true
```

When I run the `docker buildx  build ...` command directly, everything works fine. What am I missing here?

Best
Enes
