### DISCUSSION TITLE
What does v1 mean in amd64_v1 ?

### DISCUSSION THREAD

**Discussion by stephane-archer** [goreleaser/goreleaser#3931] [Q&A] [answered]
With the following config:
```
project_name: MyApp
builds:
  - goos:
      - darwin
    goarch:
      - amd64
```
result in the following file:
```dist/MyApp_darwin_amd64_v1/MyApp```

I'm just wondering why is there a `_v1`? What does it mean? Can I remove it?
