### DISCUSSION TITLE
Build arm Docker image on linux runner

### DISCUSSION THREAD

**Discussion by till** [goreleaser/goreleaser#3948] [Q&A] [answered]
Hey,

I ran into a weird issue. Right now, I can build Docker images for multiple architectures locally:

```
❯ docker images|grep dnsbl
ghcr.io/luzilla/dnsbl_exporter                            0.5.0-arm64                                                                  f1d1e8edbd38   14 minutes ago   84MB
ghcr.io/luzilla/dnsbl_exporter                            0.5.0-amd64  
```

But when I run the build on github actions, I get an `exec format error` which supposedly only happens when you mix binaries from different platforms. Thing is, `copy dnsbl_exporter` works and it fails on `mkdir -p ...` step.

The build is here:
https://github.com/Luzilla/dnsbl_exporter/actions/runs/4733141988/jobs/8400262395

I am sure I am doing something wrong? :) But any help appreciated.

Till

**Comment by caarlos0** [comment]
I think you need to install binfmt in your workflow too

**Reply by till** [reply]
Is this a dependency of goreleaser when used for cross platform Docker images?

**Reply by caarlos0** [reply]
It's a dependency of Docker afaik

**Reply by till** [reply, marked as answer]
Thanks for helping @caarlos0! Appreciate it.

I haven't done a release in a while and I thought this worked before. But maybe it was something that changed on the runner or in the docker actions. The following works (`docker/setup-qemu-action` takes care of it):

```yaml
on:
  pull_request:

jobs:
  release_test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --clean
```
