### DISCUSSION TITLE
ARM 32 bit build

### DISCUSSION THREAD

**Discussion by suntong** [goreleaser/goreleaser#3975] [Q&A]
All my builds are 64b, but one request came and asked for ARM 32 bit build specifically -- https://github.com/suntong/html2md/issues/3

How to make all my builds 64b, yet allow one ARM 32 bit build at the same time please?

**Comment by caarlos0** [comment]
You can add as many goos/goarch/goarm/etc you need.

Refer to docs for more info: https://goreleaser.com/customization/builds/

**Reply by suntong** [reply]
OK, let me be very specific. Here is my builds:

```yaml
builds:
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
```

which make all my builds 64b, and I want to add ARM 32 bit build for linux (raspb).

what's the syntax to add a _**single build**_ combination please? I've checked https://goreleaser.com/customization/builds/ but didn't find what I was looking for. Please help!
