### DISCUSSION TITLE
Files not added to package after upgrading to Go Releaser pro

### DISCUSSION THREAD

**Discussion by maidul98** [goreleaser/goreleaser#3991] [Q&A] [answered]
We have recently upgraded to Go Releaser pro because we needed the mono repo [taged prefix support](https://goreleaser.com/customization/monorepo/?h=mon). However, after adding this block to our goreleaser.yaml

```
monorepo:
  tag_prefix: infisical-cli/
  dir: cli
``` 

all of the custom files that are added on top of the binary are no longer found during installation of the package. For example, the block below used to work just fine but after the upgrade when we install it, we get the following error

```
aurs:
  - name: infisical-bin
    homepage: "https://infisical.com"
    description: "The official Infisical CLI"
    maintainers:
      - Infisical, Inc <support@infisical.com>
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/infisical-bin.git"
    package: |-
      # bin
      install -Dm755 "./infisical" "${pkgdir}/usr/bin/infisical"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/infisical/LICENSE"
```

```
=> Starting package()...
install: cannot stat './LICENSE': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: infisical-bin-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
infisical-bin - exit status 4
```

The files that it is complaining about are indeed present. I think this may have to do with the `dir` property of the monorepo block but I am unsure. 

Here is the full config file https://github.com/Infisical/infisical/blob/main/.goreleaser.yaml. Please let me know if I have missed something, thank you!

**Comment by caarlos0** [comment]
hey @maidul98 , yes, its mentioned in the docs that everything will be prefixed by that dir... 

since it uses an `fs.FS` for it, the bad thing is that you can't even escape it with `../`.

I'm working on a PR to automatically try the root directory if it doesn't match any files in the subdir, so this problem should go away.


I'm also adding a warn for when no files get matched, so its more clear what happened.

You can confirm that by running `goreleaser release --clean --snapshot` and `tar tvf <file>.tar.gz`.

Will update here once I have news, but I intent to release it today or Monday.

**Reply by caarlos0** [reply]
released https://github.com/goreleaser/goreleaser-pro/releases/tag/v1.18.2-pro

**Reply by caarlos0** [reply, marked as answer]
You'll need to change your archives section to:

```yaml
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - ../README*
      - ../LICENSE*
      - ../manpages/*
      - ../completions/*
```

and everything should work... but please let me know if it doesn't or you find any other issue :) 

Thanks!
