### DISCUSSION TITLE
Push docker image to private ECR ?

### DISCUSSION THREAD

**Discussion by rgarrigue** [goreleaser/goreleaser#4005] [Q&A] [answered]
Hi there

I'm trying to push a docker image to a private ECR. 

```
  • docker images
    • building docker image                          image=1234567890.dkr.ecr.eu-central-1.amazonaws.com/rainbow:1.1.2
  • publishing
    • docker images
      • pushing                                      image=1234567890.dkr.ecr.eu-central-1.amazonaws.com/rainbow:1.1.2
  ⨯ release failed after 2m41s               error=docker images: failed to publish artifacts: failed to push 1234567890.dkr.ecr.eu-central-1.amazonaws.com/rainbow:1.1.2: exit status 1: no basic auth credentials
The push refers to repository [1234567890.dkr.ecr.eu-central-1.amazonaws.com/rainbow]
a3bf08f97d50: Preparing
```

My .gitlab-ci.yml

```yaml
stages:
  - release

release:
  stage: release
  tags:
    - aws-developers-runner
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - goreleaser release --clean
```

And the .goreleaser.yml (removed gitlab config, changelog, before hooks, 

```yml
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqojbefore:
---
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "728080024150.dkr.ecr.eu-central-1.amazonaws.com/rainbow:{{ .Version }}"
      - "728080024150.dkr.ecr.eu-central-1.amazonaws.com/rainbow:{{ .Tag }}"
      - "728080024150.dkr.ecr.eu-central-1.amazonaws.com/rainbow:{{ .Major }}"
      - "728080024150.dkr.ecr.eu-central-1.amazonaws.com/rainbow:{{ .Major }}.{{ .Minor }}"
      - "728080024150.dkr.ecr.eu-central-1.amazonaws.com/rainbow:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
     ...
```

I added a docker login in the gitlab-ci.yml, no success still the same error. Tried an over privileged EC2 gitlab runnertoo, not better. Last I tried moving the docker login to goreleaser pre-hook, didn't worked. What am I missing ?
