### DISCUSSION TITLE
Is this possible to sign images built with ko ?

### DISCUSSION THREAD

**Discussion by eddycharly** [goreleaser/goreleaser#4026] [Q&A] [answered]
We use goreleaser with ko and tried to sign images with cosign but it looks like cosign sees nothing to sign.

GitHub [logs](https://github.com/kyverno/playground/actions/runs/5054823339/jobs/9070223468):

```shell
    ....
    • signing docker images
      • no artifacts matching the given filters found
    ....
```

Our [goreleaser config](https://github.com/kyverno/playground/blob/main/backend/.goreleaser.yaml):

```yaml
kos:
  - repository: ghcr.io/kyverno/playground
    tags:
      - '{{.Tag}}'
    bare: true
    preserve_import_paths: false
    sbom: none
    platforms:
      - all
    ldflags:
      - -s -w

docker_signs:
  - artifacts: all
    args:
      - 'sign'
      - '${artifact}'
      - "--yes"
```
