### DISCUSSION TITLE
Is this possible to tag docker images with `latest` only when it's not a prerelease ?

### DISCUSSION THREAD

**Discussion by eddycharly** [goreleaser/goreleaser#4042] [Q&A] [answered]
We are using goreleaser to build docker images (with `ko`), and configured `prerelease: auto`.

Now we don't want to tag images with `latest` when it is a prerelease (we want `latest` only on stable releases).

Our config looks like this:
```yaml
kos:
  - repository: ghcr.io/kyverno/playground
    tags:
      - '{{.Tag}}'
      - latest # can we make this conditional to exclude prereleases ?
```

Is there a syntax (template) we can use for that ?

**Comment by caarlos0** [comment, marked as answer]
```
kos:
  - repository: ghcr.io/kyverno/playground
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}latest{{ end }}' 
```

Can you check if this works?

EDIT: fixed typo
