### DISCUSSION TITLE
Having checksums.txt file content as part of release body

### DISCUSSION THREAD

**Discussion by sethiyash** [goreleaser/goreleaser#4063] [Q&A] [answered]
Hi Team, 
We are using Goreleaser extensively for release. Thanks, for such a fantastic tool. Although in our efforts to further automate our release process and remove some of the manual work. 

I'm looking to print the content of the checksum file in the release body as [this](https://github.com/carvel-dev/ytt/releases/tag/v0.45.1) is the format we follow for release notes and we want to print the checksums as part of the release notes. 

```
# this is how we are generating checksum file
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  disable: false
...
# as part of release I'm trying to print content of checksum file in footer
release:
  # Repo in which the release will be created.
  github:
    owner: sethiyash
    name: imgpkg

  draft: true
  prerelease: auto

  footer: |
    # :open_file_folder: Files Checksum
    ```
    # how to print checksum.txt file here?
    ```
  name_template: "{{.Tag}}"
  disable: false
```

**Comment by caarlos0** [comment, marked as answer]
https://github.com/goreleaser/goreleaser/pull/4064 would this work?

**Reply by sethiyash** [reply]
Definitely. Thanks for adding this feature with lightning speed.

**Comment by sethiyash** [comment]
@caarlos0 when this will be available as part of goreleaser/goreleaser-action

When I'm trying with version 1.19.0 in goreleaser-action it is throwing the below error -

```
{{ .Checksums }}
 } [] [] [] [] [] [] [] { [] {    {  } {false {  } false}} {    {  } {false {  } false}}  { }      []  [] [] [] [] } [] [{ [linux windows darwin] [amd64 arm64] [] [] [] [] [{windows arm64   }]  ./cmd/kapp kapp-{{ .Os }}-{{ .Arch }} {[] []}   false   false false   { [-buildid= -X github.com/vmware-tanzu/carvel-kapp/pkg/kapp/version.Version={{ .Version }}] [] [-trimpath] [] [] [CGO_ENABLED=0]} []}] [{ [] {  ----------  0001-01-01 00:00:00 +0000 UTC} {{ .Binary }} binary []  false  [] false false}] [] [] {{{ .Tag }}-next} {checksums.txt sha[25](https://github.com/sethiyash/carvel-kapp/actions/runs/5463677938/jobs/9944668053#step:5:26)6 [] false []} [] [] [] [] [] [] {{[] [^docs: typo]} asc false  [] 0}  [] [] {  } {[]} {  false  [] } {false []  } { {false } {false  } {false     } {false      [] []} {false    } {false    } {false  0   []   false} {false       } {false } {false   } {false false   map[] } {false   }} [] [] { } false [] [] { [] [] [] [] [] [] []    {[] []}   false   false false   { [] [] [] [] [] []} []}  {   false} {  false false false} {  false}}
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 29: field replacements not found in type config.Archive
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.19.0/x64/goreleaser' failed with exit code 1
```

**Comment by sethiyash** [comment]
This is how my release section of .goreleaser.yml look like -
```
release:
  # Repo in which the release will be created.
  github:
    owner: carvel-dev
    name: kapp

  draft: true

  prerelease: auto

  footer: |
    # :open_file_folder: Files Checksum
    ```
    {{ .Checksums }}
    ```

  # use to change the name of the release.
  name_template: "{{.Tag}}"
  ```
