### DISCUSSION TITLE
Different Docker image tags for release and snapshot

### DISCUSSION THREAD

**Discussion by mih-kopylov** [goreleaser/goreleaser#4085] [Q&A] [answered]
The goal is to make `goreleaser release --snapshot` to build and push a docker image with `{{ .Tag }}-SNAPSHOT` tag only, while `goreleaser release` will push an image with all tags, including `latest`.

I've prepared two `docker` profiles for that, but struggling how to pass an id to `goreleaser release` command. 

```
dockers:
  - id: release
    image_templates:
      - "repo/name:{{ .Tag }}"
      - "repo/name:{{ .Major }}"
      - "repo/name:{{ .Major }}.{{ .Minor }}"
      - "repo/name:latest"
  - id: snapshot
    image_templates:
      - "repo/name:{{ .Tag }}-SNAPSHOT"
```

How to do that?

**Comment by caarlos0** [comment, marked as answer]
you can't pass ids to the release command.

you can use `{{.IsSnapshot}}` in the templates though.

PS: empty image names are ignored, so if you could do something like:

```yaml
dockers:
  - 
    image_templates:
      - "{{ if not .IsSnapshot }}repo/name:{{ .Tag }}{{ end }}"
      - "{{ if not .IsSnapshot }}repo/name:{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}repo/name:{{ .Major }}.{{ .Minor }}{{ end }}"
      - "{{ if not .IsSnapshot }}repo/name:latest{{ end }}"
      - "{{ if .IsSnapshot }}repo/name:{{ .Tag }}-SNAPSHOT{{ end }}"

```

finally, if you want to push snapshots, you'll need to do it manually, or use the nightly feature from [goreleaser-pro](https://goreleaser.com/pro).
