### DISCUSSION TITLE
Build failure with crypto11.go

### DISCUSSION THREAD

**Discussion by IdanAdar** [goreleaser/goreleaser#4192] [Q&A] [answered]
I'm using Goreleaser 1.10.3.
I've hit a new error. From the build log:

```
...
...
go: downloading github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
# github.com/ThalesIgnite/crypto11
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:127:16: undefined: pkcs11.ObjectHandle
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:146:22: undefined: pkcs11.ObjectHandle
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:174:14: undefined: pkcs11.Ctx
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:177:16: undefined: pkcs11.TokenInfo
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:183:27: undefined: pkcs11.SessionHandle
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/aead.go:56:78: undefined: pkcs11.Mechanism
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/aead.go:56:97: undefined: pkcs11.GCMParams
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/attributes.go:15:25: undefined: pkcs11.Attribute
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/sessions.go:34:17: undefined: pkcs11.Ctx
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/sessions.go:35:16: undefined: pkcs11.SessionHandle
/go/pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:146:22: too many errors
```

This is the gorelease.yaml
```
# .goreleaser.yaml
project_name: xxx

github_urls:
  api: https://github.com/api/v3/
  upload: https://github.com/api/uploads/
  download: https://github.com/
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

builds:
  - # Path to main.go file or main package.
    main: cmd/plugin/main.go

    # Custom asmflags templates.
    asmflags:

    # Custom gcflags templates.
    gcflags:

    # Custom environment variables to be set during the builds.
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

    # Custom flags templates.
    flags:
      - -installsuffix
      - -extldflags "-static"
      - -tags=netgo

    # GOOS list to build for.
    goos:
      - linux

    # GOARCH to build for.
    goarch:
      - amd64

archives:
  - id: plugin
    format: binary
    name_template: "xxxx-{{.Os}}-{{.Arch}}-{{.Version}}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
```

Any clues as to where is it actually failing?
