### DISCUSSION TITLE
Archive binaries into tar.gz and zip for windows

### DISCUSSION THREAD

**Discussion by ShiranAvidov** [goreleaser/goreleaser#4203] [Q&A] [answered]
Currently I have a build with goos: darwin, linux and windows. All binaries will be archived into tar.gz files (default). I want to archive all windows binaries into tar.gz and zip files. I tried to use `format_overrides` with format zip, but only zip files were created.  How can I do that without creating another build for windows zip format?

**Comment by caarlos0** [comment, marked as answer]
unfortunately there's no obvious way of doing this right now...

You could add another archive item with `zip` as format, but it would apply to all platforms, not only windows.

Format overrides don't work because, as the name implies, they override the pre-defined format.

What you could do is something like this:

```yaml
builds:
- id: windows-only
  goos: [windows]
  # etc...
- id: default 
  goos: [linux, darwin]
  # etc...

archives:
- id: windows-only
  builds: [windows-only]
  format: zip 
  # etc...
- id: default 
  builds: [default, windows-only]
  format: tar.gz
  # etc...
```

This would generate `.tar.gz` archive for all three platforms, plus `zip` archives for windows.

**Reply by ShiranAvidov** [reply]
thanks for the quick reply

**Comment by petems** [comment]
For anyone else googling how to do Zip specific builds on WIndows in 2025 with the v2 version of goreleaser:

```
archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    files:
      - README.md
      - LICENSE.md
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
 ```
 
My full working config for any google-r in the future as well 🫡 

 ```
 version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.gitCommit={{.Commit}}
    binary: gitsweeper

archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    files:
      - README.md
      - LICENSE.md
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# This is correct, Cursor stop telling me it's wrong: https://goreleaser.com/customization/homebrew_casks/
homebrew_casks:
  - name: gitsweeper
    repository:
      owner: petems
      name: homebrew-gitsweeper
      branch: master
      # Create a Github Finegrained Access Token
      # https://github.com/settings/personal-access-tokens
      # Set the scope to just the petems/homebrew-gitsweeper repo, with pull-request write permissions
      # Open https://github.com/petems/gitsweeper/settings/secrets/actions
      # Create a new secret called HOMEBREW_TOKEN with the value of the token you created
      token: "{{.Env.GITHUB_TOKEN}}"
    homepage: "https://github.com/petems/gitsweeper"
    description: "A command-line tool for cleaning up merged Git branches"
    license: "MIT"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    commit_msg_template: "Bump {{ .ProjectName }} to {{ .Tag }}"
    caveats: |
      gitsweeper is a tool for cleaning up merged Git branches.
      
      To get started:
        gitsweeper --help
```
