### DISCUSSION TITLE
How to make a cross-repository pull requests (for Winget) using a private key?

### DISCUSSION THREAD

**Discussion by kaplas** [goreleaser/goreleaser#4321] [Q&A] [answered]
Hi!

I'm trying to get our tool [Jalapeno](https://github.com/futurice/jalapeno) into some package managers. We are releasing it on behalf of [our company](https://github.com/futurice/), and thus it belongs to the company's GitHub orgasation. One consequence of this is that **we are trying to get the package manager -related publishing to work using GitHub deploy keys**, instead of Personal Access Tokens (to make it sure that the pipeline won't break when the token owners decides to switch jobs).

The first one I configured was a homebrew tap [(link to related commit)](https://github.com/futurice/jalapeno/blob/11451750101bf816f8dfc2d747a0a6c3c35e4993/.goreleaser.yaml#L37-L42):

```yaml
brews:
  - name: jalapeno
    repository:
      owner: futurice
      name: homebrew-jalapeno
      git:
        url: "git@github.com:futurice/homebrew-jalapeno.git"
        private_key: "{{ .Env.HOMEBREW_TAP_PRIVATE_KEY }}"
```

...which worked really nicely. I had to use the `git` attribute to be able to define the private key to be used, but I got it working.

Next up I decided that it's time to support our Windows users, and thus started configuring Winget support. Here's where I'm strugling. With Homebrew tap, I can just commit directly to the `main` branch of the listed repo. With [microsoft/winget-pkgs repo](https://github.com/microsoft/winget-pkgs) I should be committing to a named branch in our own [futurice/winget-pkgs fork](https://github.com/futurice/winget-pkgs), and then making a cross-repository pull requests to the Microsoft repo. **However I can not get this to work with a private/deploy key**.

[I tried defining the branch attribute](https://github.com/futurice/jalapeno/blob/3a3ae274cc0cd5afa0f18114d9434e33aaa49c59/.goreleaser.yaml#L95-L101):

```yaml
  repository:
    owner: futurice
    name: winget-pkgs
    branch: "{{.ProjectName}}-{{.Version}}"
    git:
      url: "git@github.com:futurice/winget-pkgs.git"
      private_key: "{{ .Env.WINGET_PKGS_PRIVATE_KEY }}"
```

...but the commit went to the main branch instead of the named branch. [Then I tried defining the branch in the Git URL](https://github.com/futurice/jalapeno/blob/5017e125fa4a52842a47e78dafd261406cd362f7/.goreleaser.yaml#L95-L101) as well:

```yaml
    git:
      url: "git@github.com:futurice/winget-pkgs.git#{{.ProjectName}}-{{.Version}}"
```

...but then cloning the repo didn't work. I even checked [goreleaser own YAML file](https://github.com/goreleaser/goreleaser/blob/695a56feaa9dbc34a138f7150e5f733c1170f3e5/.goreleaser.yaml#L212-L228) for some inspiration, and saw that they are not using anything extra in their token configs. I thought this sounded weird, as I had read that [token's permissions are limited to the repository that contains the workflow](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), but [I even tried that](https://github.com/futurice/jalapeno/blob/0b408e92b193c759394edd45db7347b2a21520f4/.goreleaser.yaml#L95-L101):

```yaml
  repository:
    owner: futurice
    name: winget-pkgs
    branch: "{{.ProjectName}}-{{.Version}}"
```

...and it failed as well.

How should I do this? Is this even possible to accomplish using write-enabled deploy keys? For now I would really like to get this working without using user-owned PATs. I found [an issue where someone](https://github.com/goreleaser/goreleaser/issues/4283) had circumvented this by using [tibdex/github-app-token](https://github.com/tibdex/github-app-token) as a helper. But _shouldn't_ this be possible also with deploy keys?

Thank you for your help in advance!
