### DISCUSSION TITLE
v3 wish list

### DISCUSSION THREAD

**Discussion by caarlos0** [goreleaser/goreleaser#4341] [Ideas, Issue Triage, and General discussions]
Hey GoReleaser community!

I started to work on ~~v2~~ v3, which will have breaking changes... so, if you have suggestions, the time is now!

Throw here your wishes for goreleaser v2+, even if it breaks old configurations 🙏

**Comment by ryancurrah** [comment]
- Custom publish artifacts by package type (deb, rpm, docker, etc). Or some sort of custom filter that has access to multiple properties.
- Configuration templates for sections to make it easier to manage hundreds of GoReleaser configurations.
- Splitting up artifact creation and artifact publishing configuration. So we have new top level sections, `packages` and `publish`. Creating an artifact and publishing are two different operations and being able to split it up and provide specific publish configuration for each artifact would make the publish operation more usable. Note: We currently do not use GoReleaser to publish any of our artifacts today, we use a make target.
- Build support for other languages, Python, Rust, etc. (Not a high priority but hey while we are wishing). The `builds` sections would look like `builds.go[]`, `builds.python[]`, `builds.rust[]`. Even if you don't want to support multiple languages right now, adding a subsection of `go` would allow for it in the future.

An issue we struggle with is making sweeping changes to the GoReleaser configuration across repositories. Most of our GoReleaser configurations are the same for builds, nfpms, dockers, etc. With the occasional extra file copied to a debian or docker image. One feature that would make my life wayyyy easier is to some how allow specifying a template to use, but still allow overriding specific parts. Something like...

For the template idea we would go from this...

```yaml
builds:
  - id: acme-cli
    main: ./cmd/acme-cli
    binary: acme-cli
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    
archives:
  - id: acme-cli
    name_template: '{{ replace .Binary "_" "-" }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
   
brews:
  - name: acme-cli
    ids:
      - acme-cli
    repository:
      owner: acme-cli
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@acme.com
    url_template: '{{ .Env.ARTIFACTS_BASE_URL }}/{{ .Env.ARTIFACTS_ARCHIVE_REPOSITORY }}/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }}'
    homepage: '{{ .GitURL }}'
    folder: Formula
    skip_upload: true
```

To this...

```yaml
includes:
  - from_file:
      path: .goreleaser.templates.yml

builds:
  - id: acme-cli
    main: ./cmd/acme-cli
    binary: acme-cli
    template: cloud-cli-builds

archives:
  - id: acme-cli
    template: cloud-cli-archives

brews:
  - name: acme-cli
    ids:
      - acme-cli
    template: cloud-cli-homebrew
```

Then the template section might look like...

```yaml
templates:
  builds:
    - id: cloud-cli-builds
      template:
        flags:
          - -trimpath
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - amd64
          - arm64
        env:
          - CGO_ENABLED=0

  archives:
    - id: cloud-cli-archives
      template:
        name_template: '{{ replace .Binary "_" "-" }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
        format_overrides:
          - goos: windows
            format: zip
        files:
          - none*

  brews:
    - id: cloud-cli-homebrew
      template:
        repository:
          owner: acme-cli
          name: homebrew-tap
        commit_author:
          name: goreleaserbot
          email: goreleaser@acme.com
        url_template: '{{ .Env.ARTIFACTS_BASE_URL }}/{{ .Env.ARTIFACTS_ARCHIVE_REPOSITORY }}/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }}'
        homepage: '{{ .GitURL }}'
        folder: Formula
        skip_upload: true
```

This would allow us to fix most breaking changes in one file instead of hundreds.
