### DISCUSSION TITLE
Passing variables from github to .goreleaser.yaml

### DISCUSSION THREAD

**Discussion by fiddlermikey** [goreleaser/goreleaser#4345] [Q&A] [answered]
I am trying to setup a workflow with goreleaser that first determines if the prerelease property should be true or false. But I cannot figure out how to pass the environment variable correctly.

On the [documentation page for Environment Variables](https://goreleaser.com/customization/env/) it shows some code used to set a property 
```# .goreleaser.yaml
env:
  - FOO={{ .Env.FOOBAR }}
```
The explanation says that if you have an environment variable FOOBAR set to 'on', the go build (and I assume release) will have the variable FOO set to 'on'. The explanation would be more helpful to see how the FOO variable is referenced later in the .goreleaser.yaml file.

It does not look like the value passed from the workflow is being honored by the yaml file, so I am probably not doing it the right way.

At the top of my .goreleaser file
```
env:
  - PRERELEASE={{.Env.PRE}}
```
And in the release section I have
```
release:
  prerelease: "{{.Env.PRERELEASE}}" # I have tried this with and without quotes
```

I am setting the env PRE: true in the call to goreleaser-action
```
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          PRE: true
```

Are there any examples showing how to reference the environment variables? Is there a way to debug what values are being set and available during the goreleaser target?
