### DISCUSSION TITLE
Syntax for signing lists of artifacts

### DISCUSSION THREAD

**Discussion by ross-spencer** [goreleaser/goreleaser#4460] [Q&A] [answered]
My YAML is rusty but it looks like it should be possible for some sort of list object to be used for signing. I have tried a few approaches unsuccessfully, my last is:

```yaml
signs:
  - id: one
    artifacts: checksum
  - id: two
    artifacts: binary
```

The YAML is parsed, but Goreleaser only recognizes the first ID. From the docs, I am starting to get the impression it's not going to be possible to cherry-pick artifacts. Can anyone help confirm the syntax if it is possible?

**Comment by ross-spencer** [comment]
Okay, so inspecting the detail of the docs a little further, it is possible, but other conditions must be met. If signing `binary` you cannot also sign more typical archive formats, the format in the `archives` section must be set to: `binary` also, so you can do the following:

```yaml
signs:
  - id: checksum_objects
    artifacts: checksum
  - id: binary_objects
    artifacts: binary
  - id: <other artifact>
    artifacts: ...
```

or:

```yaml
signs:
  - id: archive_objects
    artifacts: archive
  - id: checksum_objects
    artifacts: checksum
  - id: <other artifact>
    artifacts: ...
```

Depending on how that archive section is configured. (At least that's how it's working, and I don't see a way to have both types signed).
