### DISCUSSION TITLE
How do I skip building certain docker images based on the `--id` flag?

### DISCUSSION THREAD

**Discussion by TylerHelmuth** [goreleaser/goreleaser#4469] [Q&A] [answered]
I'd like to use the `--id` flag to tell the goreleaser-action which build in [my config ](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.goreleaser.yaml) should be built for a particular github action:

```yaml
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: --snapshot --clean --skip-sign --skip-sbom --timeout 2h --split --id otelcol-contrib
```

This works exactly like I want it to until goreleaser starts building the docker images, where fails when [it starts building images](https://github.com/TylerHelmuth/opentelemetry-collector-releases/actions/runs/7174226133/job/19535220042) for a build that wasn't specified in the `--id` flag.

I thought I could use the `ids` configuration option to specify which docker images to build, but that didn't work either:

```yaml
    - goos: linux
      goarch: "386"
      ids:
        - otelcol
      dockerfile: distributions/otelcol/Dockerfile
      image_templates:
        - otel/opentelemetry-collector:{{ .Version }}-386
        - otel/opentelemetry-collector:latest-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:{{ .Version }}-386
        - ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest-386
      extra_files:
        - configs/otelcol.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/386
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
```
still builds even when `--ids otelcol-contrib` is specified.

Is what I'm trying to achieve possible? If you're interested, the backstory is here: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/429
