### DISCUSSION TITLE
nix user repo and order of pipelines

### DISCUSSION THREAD

**Discussion by till** [goreleaser/goreleaser#4479] [Q&A] [answered]
Hi,

we wanted to create a nix user repository to publish a cli tool (code is private for now). So far, our release workflow looks like this:

```yaml
# pseudo workflow
job1
  steps:
  - goreleaser release [all bunch of targets (docker, homebrew, nix, ...) 
  - action/upload_artifacts
 
job2:
  needs: job1
  steps:
  - download artifacts
  - upload to s3 bucket, etc.
 ```

I noticed that the nix build tries to "validate" a pre fetch thing (I am a nix-noob still). And that URL points to our s3, which is not available yet (error 404) as the artifacts are uploaded in the other `job2`. Therefor, publishing/updating of the nur fails the release job (it doesn't skip, it actually fails the job).

Long story short, I saw there are `blobs` now and custom publishers. What is the order of these things? So for example, when I upload a bunch of artifacts using a blob (to s3), will this be available before the nur is build?

Thank you!
