### DISCUSSION TITLE
upload artifacts to existing release

### DISCUSSION THREAD

**Discussion by bluebrown** [goreleaser/goreleaser#4524] [Q&A] [answered]
Hi, I want to use gorelease with https://github.com/marketplace/actions/release-please-action. 

So I would like to upload the assets to the release created by the other tool

Something like this

```yaml
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v4
      with:
        release-type: go
        bump-minor-pre-major: true
        bump-patch-for-minor-pre-major: true

    - name: Upload Release Artifact
      if: ${{ steps.release.outputs.release_created }}
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release # something here to upload only
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ steps.release.outputs.tag_name }}
```

Is this possible somehow?
