### DISCUSSION TITLE
How to keep builds.binary in Snapcraft?

### DISCUSSION THREAD

**Discussion by cpunion** [goreleaser/goreleaser#4536] [Q&A] [answered]
Hi,

I have a config:

```yaml
builds:
  - main: ./cmd/gop
    binary: bin/gop
    main: ./cmd/gopfmt
    binary: bin/gopfmt

snapcrafts:
  - name: goplus
```

After build and install `.snap` file, it be installed as `/snap/goplus/current/{gop,gopfmt}`, expect it be `/snap/goplus/current/bin/{gop,gopfmt}` and then link into `/snap/bin`. How to solve it?
