### DISCUSSION TITLE
nix pkg: Why is sourceRoot hardcoded to a system?

### DISCUSSION THREAD

**Discussion by till** [goreleaser/goreleaser#4549] [Q&A] [answered]
When goreleaser creates a package, it seems to render the default for the `sourceRoot` like so:

```nix
pkgs.stdenv.mkDerivation {
  pname = "foo";
  version = "1.4.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = "foo_Darwin_arm64";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./foo $out/bin/foo
  '';

  system = system;

  meta = {
    description = "foo";
    homepage = "https://example.org";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
```

A colleague suggested adding this to the package:

```nix
  sourceRootMap = {
    i686-linux = "foo_Linux_i386";
    x86_64-linux = "foo_Linux_x86_64";
    aarch64-linux = "foo_Linux_arm64";
    x86_64-darwin = "foo_Darwin_x86_64";
    aarch64-darwin = "foo_Darwin_arm64";
  };
```

And then using it:

```
sourceRoot = sourceRootMap.${system};
```

Thoughts?

**Comment by till** [comment]
Should have tried this before to add more details. When I install my package:

```
❯ NIXPKGS_ALLOW_UNFREE=1 nix shell --impure 'github:till/bar#foo'
error: builder for '/nix/store/48cac8n2lf2w4d1gxr2drdn7rjl55kx6-foo-1.4.0.drv' failed with exit code 1;
       last 4 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/m2fk1g1msfnwkyayfv6zw7xlqf7kds0w-foo_Darwin_x86_64.tar.gz
       > source root is foo_Darwin_arm64
       > chmod: cannot access 'foo_Darwin_arm64': No such file or directory
       For full logs, run 'nix log /nix/store/48cac8n2lf2w4d1gxr2drdn7rjl55kx6-foo-1.4.0.drv'.
```

So, turns out, this has to be set. But maybe I am doing wrong?

**Comment by caarlos0** [comment]
ahh, are you setting `archives.wrap_in_directory`? looks like a bug, probably

that said, your suggestion is good, goreleaser should do it automatically though

**Reply by till** [reply]
@caarlos0 never heard of that setting, should I? :D 

I think the bug is happening because I am on an intel mac and it seems to expect arm?

**Reply by till** [reply]
@caarlos0 I can do a PR, lmk.

**Reply by caarlos0** [reply]
Can you share your goreleaser config file?

**Reply by till** [reply]
```yaml
before:
  hooks:
  - go fmt ./...
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.Version={{.Version}}
  main: ./cmd/foo
  goos:
  - linux
  - windows
  - darwin
archives:
- id: archive
  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "darwin" }}Darwin {{- else if eq .Arch "linux" }}Linux {{- else if eq .Arch "386" }}i386 {{- else if eq .Arch "amd64" }}x86_64 {{- else }}{{ .Arch }}{{ end }}
  wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
- id: exec
  format: binary
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "r.example.org/foo-public/foo:latest-amd64"
  - "r.example.org/foo-public/foo:{{ .Version }}-amd64"
  - "r.example.org/foo-public/foo:{{ .Major }}-amd64"
  - "r.example.org/foo-public/foo:{{ .Major }}.{{ .Minor }}-amd64"
  dockerfile: 'cli.Dockerfile'
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- goos: linux
  goarch: arm64
  image_templates:
  - "r.example.org/foo-public/foo:latest-arm64v8"
  - "r.example.org/foo-public/foo:{{ .Version }}-arm64v8"
  - "r.example.org/foo-public/foo:{{ .Major }}-arm64v8"
  - "r.example.org/foo-public/foo:{{ .Major }}.{{ .Minor }}-arm64v8"
  dockerfile: 'cli.Dockerfile'
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
- name_template: r.example.org/foo-public/foo:latest
  image_templates:
  - r.example.org/foo-public/foo:latest-amd64
  - r.example.org/foo-public/foo:latest-arm64v8
- name_template: r.example.org/foo-public/foo:{{ .Version }}
  image_templates:
  - r.example.org/foo-public/foo:{{ .Version }}-amd64
  - r.example.org/foo-public/foo:{{ .Version }}-arm64v8
- name_template: r.example.org/foo-public/foo:{{ .Major }}
  image_templates:
  - r.example.org/foo-public/foo:{{ .Major }}-amd64
  - r.example.org/foo-public/foo:{{ .Major }}-arm64v8
- name_template: r.example.org/foo-public/foo:{{ .Major }}.{{ .Minor }}
  image_templates:
  - r.example.org/foo-public/foo:{{ .Major }}.{{ .Minor }}-amd64
  - r.example.org/foo-public/foo:{{ .Major }}.{{ .Minor }}-arm64v8
release:
  disable: true
publishers:
- name: version-bucket
  cmd: ./.goreleaser/publish {{.Version}} {{ abs .ArtifactPath }}
  ids:
  - archive
- name: latest-bucket
  cmd: ./.goreleaser/publish latest {{ abs .ArtifactPath }}
  ids:
  - exec
brews:
- name: foo
  ids:
  - archive
  goarm: 6
  goamd64: v1
  url_template: "https://download.example.org/foo/{{ .Version }}/{{ .ArtifactName }}"
  download_strategy: CurlDownloadStrategy
  commit_author:
    name: user
    email: team@example.org
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  folder: Formula
  caveats: "Run `foo login` to get started, and `foo install-completions` to install auto-complete"
  homepage: "https://foo.example.org/"
  description: "The foo CLI."
  license: "proprietary"
  skip_upload: false
  dependencies: []
  conflicts: []
  test: |
    system "#{bin}/foo version"
  repository:
    owner: example
    name: homebrew-foo
    token: "{{ .Env.foo_RELEASE_PUBLISHER }}"
nix:
- name: foo
  ids:
  - archive
  goamd64: v1
  url_template: "https://download.example.org/foo/{{ .Version }}/{{ .ArtifactName }}"
  commit_author:
    name: user
    email: team@example.org
  commit_msg_template: "nur update for {{ .ProjectName }} version {{ .Tag }}"
  path: pkgs/foo/default.nix
  homepage: "https://foo.example.org/"
  description: "The foo CLI."
  license: unfree
  skip_upload: false
  dependencies: []
  repository:
    owner: example
    name: nur
    token: "{{ .Env.foo_RELEASE_PUBLISHER }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```
