### DISCUSSION TITLE
Unable to publish to private instance of artifactory

### DISCUSSION THREAD

**Discussion by GaikwadPratik** [goreleaser/goreleaser#4585] [Q&A] [answered]
I am trying to publish a go library to privately hosted Artifactory instance. The goreleaser yaml is as follows:

```
---
project_name: commonframework
env: GO111MODULE=on CGO_ENABLED=0
before:
  hooks: 
      go mod download 
      go mod tidy
gomod:
  env: 
     GOPRIVATE=*.own.com
     GOPR[OXY=https://artifactory.own.com/artifactory/go-proxygolang-remote/
builds:
  skip: true
gitlab_urls:
  api: https://gitlab.own.com/api/v4/
  download: https://gitlab.own.com/
  use_package_registry: false
  use_job_token: true

artifactories:
  name: commonframework
  target: https://artifactory.own.com/artifactory/api/go/own-go/{{ .ProjectName  }}/{{ .Version }}
  mode: archive
  checksum: true
  signature: true
```

I have defined `ARTIFACTORY_COMMONFRAMEWORK_SECRET` and `ARTIFACTORY_COMMONFRAMEWORK_USERNAME` variables defined in privately hosted GitLab CI/CD section.  The pipeline job is successful but I don't see package published in artifactory. What am I missing? I followed all the docs from https://goreleaser.com/customization/artifactory/#customization
