### DISCUSSION TITLE
Issues with multiple build artifacts and packaging into archives

### DISCUSSION THREAD

**Discussion by safaci2000** [goreleaser/goreleaser#4624] [Q&A] [answered]
I'm trying to release an application that contains multiple binaries/entrypoints.  This seems to work for almost everything except Archives and homebrews that's giving me some issues.  What am I doing wrong here?

Every artifact is supposed to have two binaries, `gdg` and `gdg-generate`.

Here's the output of homebrew which reflects what is in the archives as well.

Basically, 

gdg is in: gdg_Darwin_all.tar.gz
gdg-generate is in:  gdg_Darwin_arm64.tar.gz, gdg_Darwin_x86_64.tar.gz
contains both: gdg_Linux_arm64.tar.gz, gdg_Linux_x86_64.tar.gz

Every package should contain all builds, so what am I missing?  What behavior is making some tar.gz contain one or both.  It seems like it's specific to OSX Darwin build while the Linux and windows artifacts seems to work fine (Windows not listed above but that packages up correctly)

#### **`Forumula.rb`**
```rb|
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdg < Formula
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines."
  homepage "https://software.es.net/gdg"
  version "0.5.2-rc1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/esnet/gdg/releases/download/v0.5.2-rc1/gdg_Darwin_arm64.tar.gz"
      sha256 "3e1687d0f4bbf4b80b762839400b368864fad4e815cb9be52322114547e84bc4"

      def install
        bin.install "gdg-generate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/esnet/gdg/releases/download/v0.5.2-rc1/gdg_Darwin_x86_64.tar.gz"
      sha256 "7ea56a295b4a41fc10529b43b1750a745bf283f513c3cecb4a48d52aa82fa9f7"

      def install
        bin.install "gdg-generate"
      end
    end
    url "https://github.com/esnet/gdg/releases/download/v0.5.2-rc1/gdg_Darwin_all.tar.gz"
    sha256 "4971196448428bcb5f255be6b9ddd862161fb6142886fd4521dda2aff1f03fff"

    def install
      bin.install "gdg"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/esnet/gdg/releases/download/v0.5.2-rc1/gdg_Linux_arm64.tar.gz"
      sha256 "115735fdcd4f461e069b808993cc97942c0b15f545a76acfcec2b681f5d24dce"

      def install
        bin.install "gdg"
        bin.install "gdg-generate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/esnet/gdg/releases/download/v0.5.2-rc1/gdg_Linux_x86_64.tar.gz"
      sha256 "b7921b984860f92ecccdecd3cd5691aa61570758caf99d57c1e87898159326c4"

      def install
        bin.install "gdg"
        bin.install "gdg-generate"
      end
    end
  end
end
```

#### **`.goreleaser.yaml`**

```yaml
before:
  hooks:
    - go mod tidy
    - go generate ./...

source:
  rlcp: true

builds:
  - id: gdg
    env:
      - CGO_ENABLED=0
    binary: gdg
    ldflags: -s -w -X github.com/esnet/gdg/internal/version.GitCommit={{ .Commit }} -X github.com/esnet/gdg/internal/version.BuildDate={{ .Date }}  -X github.com/esnet/gdg/internal/version.Version={{ .Tag }}
    main: ./cmd/gdg
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - 386
      - amd64
  - id: gdg-generate
    env:
      - CGO_ENABLED=0
    binary: gdg-generate
    ldflags: -s -w -X github.com/esnet/gdg/internal/version.GitCommit={{ .Commit }} -X github.com/esnet/gdg/internal/version.BuildDate={{ .Date }}  -X github.com/esnet/gdg/internal/version.Version={{ .Tag }}
    main: ./cmd/gen
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - 386
      - amd64


universal_binaries:
  - replace: true

release:
  prerelease: auto


brews:
  - name: gdg
    homepage: https://software.es.net/gdg
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines.
    folder: Formula
    repository:
      owner: esnet
      name: homebrew-gdg
      token: "{{ .Env.HOMEBREW_TOKEN }}"
      branch: main
    commit_author:
      name: GDG ESNet
      email: gdg@es.net

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - gdg
      - gdg-generate
    files:
      - README*
      - config/importer-example.yml
      - config/templates-example.yml

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

```

**Comment by caarlos0** [comment]
I tried your config here, and it seems to have worked properly:

```rb
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdg < Formula
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines."
  homepage "https://software.es.net/gdg"
  version "v0.0.0-next"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com///releases/download/v0.0.0/foo_Darwin_x86_64.tar.gz"
      sha256 "f5c1c9991a73361e0131af12e94dc22a11cb1741fcd0ab53f28ae5f97bdd4636"

      def install
        bin.install "gdg"
        bin.install "gdg-generate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com///releases/download/v0.0.0/foo_Darwin_arm64.tar.gz"
      sha256 "9f476de26f9323adf1ca515fd40b1d2abe9e2d70e6a9501ad9b56878ed5c5994"

      def install
        bin.install "gdg"
        bin.install "gdg-generate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com///releases/download/v0.0.0/foo_Linux_x86_64.tar.gz"
      sha256 "4369f5afb293a464a93996f60c8f9098403ca64d5c3049b0fecfe7e30d5092e8"

      def install
        bin.install "gdg"
        bin.install "gdg-generate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com///releases/download/v0.0.0/foo_Linux_arm64.tar.gz"
      sha256 "ea7d87f00f00f1797c757c34a2ac97a6d9d754d3f8e2f6e71c4cd081f1d02781"

      def install
        bin.install "gdg"
        bin.install "gdg-generate"
      end
    end
  end
end
```

which version of goreleaser are you using?

**Reply by safaci2000** [reply]
I had this issue
GitVersion:    v1.22.1
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     h1:7+P9DHpKPmg160mni77AC6x43tch0DKNqULIfrYRyOU=
Platform:      darwin/arm64

The initial issue forced me to add  allow_different_binary_count: true options.  If you try removing that, I believe that fails the build completely.  

I used this command for reference to run test the build:  `goreleaser release --skip=publish,validate`

**Reply by caarlos0** [reply]
can you try in the last goreleaser version?

**Reply by safaci2000** [reply]
I upgraded to the latest version. ( v1.24.0)

https://github.com/esnet/gdg/tree/feature/goreleaserDebug here's the branch I'm testing on.  

If I set the `allow_different_binary_count: false` it fails with: ` error=invalid archive: 0: archive has different count of binaries for each platform, which may cause your users confusion.`

If I set it true, the result archives exhibits the behavior already pasted above. For example, gdg_Darwin_all.tar.gz contains only gdg, while gdg_Linux_x86_64.tar.gz contains both binaries.

**Reply by caarlos0** [reply]
thanks for the reproducible.

You're missing adding both binaries to the `universalbinaries` config:

![CleanShot 2024-02-12 at 12 05 23@2x](https://github.com/goreleaser/goreleaser/assets/245435/3abb9814-540f-476f-9018-310e82e592ce)

It was doing it only for `gdg`, as per [docs](https://goreleaser.com/customization/universalbinaries/?h=id)

**Reply by safaci2000** [reply]
One final question and I don't really see any reason why I'm seeing this behavior, but if I use:

```yaml
     ids:
       - gdg
       - gdg-generate
```

it doesn't seem to work while the code you linked or the one below does.  Any reason I would be seeing this behavior?

```
    ids: [ gdg gdg-generate ]
```

I'm also seeing a warning about: 

```• pipe skipped                                   reason=no darwin binaries found with id "gdg"```

Is this some yaml bug i'm seeing? I'm not sure why the code would differentiate between the two array representations.

I'm especially asking since the docs reference the former rather than the latter in the example code.

**Reply by caarlos0** [reply]
might be, have you tried quoting them?

**Reply by safaci2000** [reply]
That didn't change anything.  I'm not sure why it's exhibiting this behavior.  I guess an FYI.  It's not a blocker for me but a it odd.  

Also, thank you so much for your assistance @caarlos0 it's really appreciated.

**Reply by caarlos0** [reply, marked as answer]
ah, I actually gave you bad feedback it seems

it should be:

```yaml
universal_binaries:
  - id: gdg
    name_template: gdg
    replace: true
    ids: [gdg]
  - id: gdg-generate
    name_template: gdg-generate
    replace: true
    ids: [gdg-generate]

```

you need to create one universal binary for each binary you are building... the `ids: [foo bar]` thing "worked" because it actually matched nothing, as `foo bar` was treated as a single item (it should have beend `[foo, bar]`.

Anyway, the snipped above will fix all your problems :D
