### DISCUSSION TITLE
Is GoReleaser Pro required for footer release?

### DISCUSSION THREAD

**Discussion by cafferata** [goreleaser/goreleaser#4646] [Q&A] [answered]
I have a [pull request](https://github.com/cafferata/dnscontrol/pull/7/commits/3989dd2d72a4f3319f410d4b1fdeba224b99aba5) and [test setup/GoReleaser release](https://github.com/cafferata/dnscontrol/actions/runs/8032801662/job/21942598186) ready for the [GoReleaser release footer](https://goreleaser.com/customization/release/?h=footer#github). However, I started to doubt whether this feature is available without the Pro because I could not get it to work out of the box. That's why I'm checking in, can I use this feature? Or am I overlooking something else?

```yaml
   # Footer for the release body.
   #
   # Templates: allowed
   footer: |
     ## Thanks

     Those were the changes on {{ .Tag }}!

   # Footer for the release body.
   #
   # This feature is only available in GoReleaser Pro.
   # Since v1.20 (pro)
   footer:
     # Loads from a URL.
     from_url:
       # Templates: allowed
       URL: https://foo.bar/footer.md
       footers:
         x-api-token: "${MYCOMPANY_TOKEN}"

     # Loads from a local file.
     # Overrides `from_url`.
     from_file:
       # Templates: allowed
       path: ./footer.md
```
Source: _https://goreleaser.com/customization/release/?h=footer#github_
