### DISCUSSION TITLE
Upload to artifactory only

### DISCUSSION THREAD

**Discussion by lucas-dehandschutter** [goreleaser/goreleaser#4660] [Q&A] [answered]
Hi,

I want to upload my artifact to artifactory only.

here is my goreleaser.yaml file:

```
#version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: "{{ .ProjectName }}"

nfpms:
  - id: "madm"
    vendor: "Myself"
    homepage: "https://git.me/madm"
    maintainer: "me@myself.com"
    description: "This application configures MinIO site replication, policies and users from a config.yml file."
    license: "MIT"
    formats:
      - deb
    bindir: "/usr/local/bin"

artifactories:
  - name: production
    target: https://my-artifactory.com/artifactory/minio-deb/
    # export ARTIFACTORY_PRODUCTION_USERNAME=yourUsername
    # export ARTIFACTORY_PRODUCTION_SECRET=yourPasswordOrAPIKey

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```
I have created the ARTIFACTORY_PRODUCTION_USERNAME and  ARTIFACTORY_PRODUCTION_SECRET  environment variables as described in the documentation.
Then I launch goreleaser and got the following error:

```
$ goreleaser release 
  • starting release...
  • loading                                          path=.goreleaser.yaml
  • loading environment variables
  ⨯ release failed after 0s                  error=missing GITHUB_TOKEN, GITLAB_TOKEN and GITEA_TOKEN
```
I dont want to upload to any git repository, we use git as source repo only and artifactory as artefact repo.

Here is my goreleaser version:

```
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.24.0
GitCommit:     00c2ff733758f63201811c337f8d043e8fcc9d58
GitTreeState:  false
BuildDate:     2024-02-05T12:18:01Z
BuiltBy:       goreleaser
GoVersion:     go1.21.6
Compiler:      gc
ModuleSum:     h1:jsoS5T2CvPKOyECPATAo8hCvUaX8ok4iAq9m5Zyl1L0=
Platform:      linux/amd64

```

How can I fix this?

Thx
