### DISCUSSION TITLE
Inquiry about publishing Homebrew tap from private GitLab CI to public GitHub repository at ORG level

### DISCUSSION THREAD

**Discussion by Noush-012** [goreleaser/goreleaser#4723] [Q&A] [answered]
Hi

Thank you so much for the wonderful project !!!
 I'm curious if anyone has successfully set up a workflow to publish Homebrew taps from a GitLab CI pipeline to a GitHub repository.

Specifically, I'm interested in understanding:

Whether it's feasible to publish Homebrew taps directly from a GitLab CI pipeline to a GitHub repository?
Any potential challenges or best practices in accomplishing this integration?
Any existing workflows or examples that demonstrate this setup?
Any insights, tips, or pointers to relevant resources would be greatly appreciated. Thank you in advance for your help!

**Comment by caarlos0** [comment]
Thanks!

Currently goreleaser uses whatever is available (e.g. if GITHUB_TOKEN is set, it'll push everything to github), maybe we should allow to set a "provider" or something like that

In the meantime, it might be possible if you push to git directly instead of using the APIs, e.g.

```yaml
brews:
  - ...: ...
    repository:
      owner: foo
      name: bar
      git:
        url: 'ssh://git@github.com:foo/bar.git'
        private_key: '{{ .Env.PRIVATE_KEY_PATH }}'
```

PS: I haven't test this particular scenario

**Comment by Noush-012** [comment]
Since there is only one SCM allowed for one configuration, I thought of using another pipeline job that only takes care of the GitHub token forcefuly and publishes the Brew formula while skipping the upload to the SCM. please your thoughts?

.goreleaser-brew.yml
```
  # Homebrew tap
version: 1
project_name: helloworld

builds:
  - main: ./cmd/server/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

universal_binaries:
  - replace: true
force_token: github
release:
 skip_upload: true

brews:
  - name: helloworld
    description: "helloworld program."
    repository:
      owner: foo
      name: bar
```
