### DISCUSSION TITLE
Pre-hook error: "cd": executable file not found in $PATH

### DISCUSSION THREAD

**Discussion by dehanj** [goreleaser/goreleaser#4772] [Q&A] [answered]
Hi,

We have an error that we don't really can wrap our heads around.

Long story short, when building our windows binaries we are using [`go-winres`](https://github.com/tc-hib/go-winres) to embed icons which are used, for example, in the Windows tray.

We use this as a pre-hook when building our Windows binary, but when we run this on Ubuntu or Archlinux we get this error:
```
  ⨯ release failed after 13s                 error=pre hook failed: shell: 'cd ./cmd/tkey-ssh-agent': exec: "cd": executable file not found in $PATH: [no output]
```

Note that this works well on macos.

Here is our configuration for that binary that fails:
```
  - id: windows-tray
    main: ./cmd/tkey-ssh-agent-tray
    binary: tkey-ssh-agent-tray
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=0

    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -H windowsgui -buildid=

    hooks:
      pre: cd ./cmd/tkey-ssh-agent-tray && go-winres make --arch amd64
```

When running the troublesome line (`cd ./cmd/tkey-ssh-agent-tray && go-winres make --arch amd64`) in our makefile or simply on the command line it works well, so everything is in PATH. 

Our limited knowledge on how Goreleaser actually runs makes this hard for us to troubleshoot, what shell is it running in etc.

Help would be appreciated!
