### DISCUSSION TITLE
Adding additional metadata to an SBOM

### DISCUSSION THREAD

**Discussion by idunbarh** [goreleaser/goreleaser#4796] [Q&A] [answered]
I'm using [Cataloging Artifacts](https://goreleaser.com/customization/sbom/#usage) to generate SBOMs for artifacts. I'd like add additional metadata to the cyclonedx sboms like author, license, etc ...

Whats the best way to run multiple commands within the artifact cataloging?

Typically I run ...
```
sboms:
  - id: generate-cyclonedx
    artifacts: archive
    documents: [$artifact.cdx.json]
    cmd: syft
    args: [scan, $artifact, --output, cyclonedx-json=$document]
```
and I'd like to include a command like ...
```
jq -s '.[0] * .[1]' $document sbom_metadata/metadata.cdx.json > combined.cdx.json
```
... to merge the syft generated sbom with another containing the custom metadata.

Is the best solution to create a shell script and call that instead of syft?
