### DISCUSSION TITLE
need help with this error: field token not found in type config.Homebrew

### DISCUSSION THREAD

**Discussion by jftuga** [goreleaser/goreleaser#4924] [Q&A] [answered]
I have a code repo and want to use goreleaser to build binaries and then push to a separate homebrew-tap repo.  I am seeing this error with `goreleaser 2.0.0` when I run `goreleaser check`:

    field token not found in type config.Homebrew

Here is the `brews` section of my `.goreleaser.yml` file:

```yaml
brews:
  - name: xxx
    repository:
      owner: jftuga
      name: homebrew-tap
    commit_author:
      name: xxx
      email: xxx
    homepage: xxx
    description: xxx
    test: system "#{bin}/dtdiff -v"
    token: "{{ .Env.HOMEBREW_TOKEN }}"
    install: bin.install "xxx"
```

How can I fix this?

This works without `token` if i manually run it from my local system, but I now want this to be apart of a GitHub Action.

Thanks.
