### DISCUSSION TITLE
Homebrew tokens in GitHub

### DISCUSSION THREAD

**Discussion by jftuga** [goreleaser/goreleaser#4926] [Q&A] [answered]
I have one more question about these. I now haven `token` in the correct location within my `.goreleaser.yml` file.  I now see this error in GitHub Actions:

    homebrew tap formula: template: tmpl:1:7: executing "tmpl" at <.Env.HOMEBREW_TOKEN>: map has no entry for key "HOMEBREW_TOKEN"

This is what I've done in GitHUb, but it must not be correct:
* clicked on repo `Settings`
* on the left side, `Secrets and Variables` and then `Actions` 
* on the right side, clicked the `Variables` tab
* added a `HOMEBREW_TOKEN` token

What could I be missing?

Thanks.

**Comment by gruffyn** [comment]
Have you passed the variable as an environment variable to the goreleaser action? Something like:
```
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ var.HOMEBREW_TOKEN }}
```

Though given it's a pat that can work on other repos, I'd probably change it to be a secret rather than a variable.

**Reply by jftuga** [reply, marked as answer]
I got this working with the assistance of @gruffyn and ChatGPT.  I am posting a full answer in case anyone else runs into this same problem.  I've also created a [GoReleaser and Hombrew](https://gist.github.com/jftuga/ee3f132ff315fdc1d1459256c16557c2) public Gist with slightly more details.

____

In my `.github/workflows/release.yml` file:

```yaml
      - name: run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --clean
```

___

In my `.goreleaser.yml` file:

```yaml
brews:
  - name: xxx
    repository:
      owner: xxx
      name: xxx-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
```

___


This is what I've done in GitHub in the Repo settings:

* clicked on repo Settings
* on the left side, Secrets and Variables and then Actions *(which is hidden until you click Secrets and Variables)*
* on the right side, clicked the Secrets tab
* click `New Repository Secret` button
* added a HOMEBREW_TOKEN token
