### DISCUSSION TITLE
`ko` pipeline throws `package command-line-arguments is not in std` error

### DISCUSSION THREAD

**Discussion by Dentrax** [goreleaser/goreleaser#4971] [Q&A] [answered]
Hey!

I just tried to add `kos:` pipeline into `.goreleaser.yaml` file and ran into an issue.

```
kos:
  - repository: example.com/foo/bar
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
```

On local, I tested the following command is working, exits with `0`:
```
KO_DOCKER_REPO=example.com/foo/bar ko build --bare --platform=linux/amd64 --tags latest,v0.0.0 --push=false
```

Any thoughts on this? Error message seems a bit confusing. Thanks.

```
  • publishing
    • ko
2024/07/03 15:08:20 Building command-line-arguments for linux/amd64
2024/07/03 15:08:20 Unexpected error running "go build": exit status 1
package command-line-arguments is not in std (/usr/local/go/src/command-line-arguments)
      • took: 2s
  • took: 2s
  ⨯ release failed after 8s                  error=ko: failed to publish artifacts: build: exit status 1
```

**Comment by caarlos0** [comment, marked as answer]
maybe needs to set the `main` for `go build`?

**Reply by Dentrax** [reply]
It actually set:

```
builds:
  - id: app
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
    binary: app
    ldflags:
      - -s -w
```

**Reply by caarlos0** [reply]
I mean... I think you need to set it in the KO config too?

**Reply by Dentrax** [reply]
No luck with this `.ko.yaml`:

```
defaultBaseImage: gcr.io/distroless/static:nonroot

builds:
  - id: foo
    dir: .
    main: .
```
