### DISCUSSION TITLE
How to sign with a separate tool?

### DISCUSSION THREAD

**Discussion by pcolmer** [goreleaser/goreleaser#4989] [Q&A] [answered]
https://goreleaser.com/customization/sign/ says:
> You can sign with any command that either outputs a file or modify the file being signed.

but I'm unclear how to set that up in the configuration. I have a tool that has `--in` and `--out` parameters to specify the file to read for signing and the output file that will be the signed version. I'm struggling to divine from the documentation what arguments I should pass to my signing tool in order to give it the built-but-unsigned file and what to specify as the output file.

Thanks.

**Comment by caarlos0** [comment]
Something like this, probably:

```yaml
signs:
  - signature: "${artifact}.sig"
    cmd: your-tool-name
    args: ["--in", "${artifact}", "--out", "${signature}"]
```
