### DISCUSSION TITLE
How does `archive.files` work?

### DISCUSSION THREAD

**Discussion by stdedos** [goreleaser/goreleaser#5020] [Q&A] [answered]
In the documentation here https://goreleaser.com/customization/archive/?h=archives it says that

> ```yaml
>     # Additional files/globs you want to add to the archive.
>     #
>     # Default: [ 'LICENSE*', 'README*', 'CHANGELOG', 'license*', 'readme*', 'changelog'].
>     # Templates: allowed.
>     files:
> ```

I am trying to add _additionally_ `dist/source.sbom.spdx.json`. So I thought the correct way to go was this:

```yaml
    files:
      - 'LICENSE*'
      - 'README*'
      - 'CHANGELOG'
      - 'license*'
      - 'readme*'
      - 'changelog'
      # Defaults ^^^
      - src: "dist/source.sbom.spdx.json"
        strip_parent: true
```

However, that leads to "not found" errors https://github.com/stdedos/junit2html/actions/runs/10072198510/job/27843687785#step:7:51

- Is documentation out date? Or are the default `archive.files` processed differently from the defined `archive.files`?
- Maybe support `archive.add_files`, and/or `archive.remove_files`?
  
  Tools like e.g. https://flake8.pycqa.org/en/latest/user/configuration.html have supported `extend-ignore` to "avoid mutating the defaults", but the users can add their extra configuration on top of the tool's suggestions.

  ofc that increases maintenance burden, I get that. I haven't found out a new way of "keep accepting defaults in array values, and piece-wise mutate them on local config". I'd be glad to hear your opinion, even if `x_files` is out of the question.

... I think that's impossible? It seems that `sbom:` comes after `archives:` - and I haven't seen a way to adjust the "build order"
