### DISCUSSION TITLE
Multi-arch builds with cgo deps?

### DISCUSSION THREAD

**Discussion by shell-skrimp** [goreleaser/goreleaser#5030] [Q&A] [answered]
This one is tricky I think. I have a cgo project that depends on some libraries and builds fine on both amd64 and arm64.

Sample yaml:

```yaml
builds:
  - id: asdf
    main: ./cmd/asdf/main.go
    binary: asdf
    env:
    - CGO_ENABLED=1
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    goos:
      - linux
    goarch:
      - amd64
```

If I add:

```yaml
goarch
  - amd64
  - arm64
```

It'll fail with this error:

```
  ⨯ release failed after 9s                  error=failed to build for linux_arm64: exit status 1: # runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:30: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:34: Error: too many memory references for `mov'
gcc_arm64.S:36: Error: no such instruction: `stp x19,x20,[sp,'
gcc_arm64.S:39: Error: no such instruction: `stp x21,x22,[sp,'
gcc_arm64.S:42: Error: no such instruction: `stp x23,x24,[sp,'
gcc_arm64.S:45: Error: no such instruction: `stp x25,x26,[sp,'
gcc_arm64.S:48: Error: no such instruction: `stp x27,x28,[sp,'
gcc_arm64.S:52: Error: too many memory references for `mov'
gcc_arm64.S:53: Error: too many memory references for `mov'
gcc_arm64.S:54: Error: too many memory references for `mov'
gcc_arm64.S:56: Error: no such instruction: `blr x20'
gcc_arm64.S:57: Error: no such instruction: `blr x19'
gcc_arm64.S:59: Error: no such instruction: `ldp x27,x28,[sp,'
gcc_arm64.S:62: Error: no such instruction: `ldp x25,x26,[sp,'
gcc_arm64.S:65: Error: no such instruction: `ldp x23,x24,[sp,'
gcc_arm64.S:68: Error: no such instruction: `ldp x21,x22,[sp,'
gcc_arm64.S:71: Error: no such instruction: `ldp x19,x20,[sp,'
gcc_arm64.S:74: Error: no such instruction: `ldp x29,x30,[sp],'
```

If I replace `amd64` with `arm64` and build on a dedicated arm64 system with the deps it builds fine.

How should I handle this with goreleaser? Just two separate files one for amd64 and one for arm64?
