### DISCUSSION TITLE
How can I give executable permissions to binary files within a compressed package?

### DISCUSSION THREAD

**Discussion by noovertime7** [goreleaser/goreleaser#5132] [Q&A] [answered]
I use Go language to write programs and use Goreleaser for packaging, but after packaging, the binary files in the compressed package do not have executable permissions.

**Comment by caffeine-addictt** [comment]
@noovertime7

Generally, the bins should have exec perms if built correctly.
You can try updating goreleaser (if your not on the latest version already).

It will also help if you can provide more context:

- Link or provide your `.goreleaser.yml` file code
- Link or provide any other build step scripts' code
- Which compression format is causing the issue?
- For which platform does this issue occur? (linux? windows? macos?)
- Reproduction steps?
- output of `file <your bin path>`
- output of `ldd <your bin path>`
- output of `stat <your bin path>`

If it is similar enough, I also encourage you to refer to [goreleaser's config](https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml) and other projects using goreleaser.

**Reply by noovertime7** [reply]
My Goreleaser version is: GitVersion: v2.0.1 Platform: windows/amd64

The problematic compression format is tar.gz on the Linux platform. Here is my .goreleaser.yaml file. I don't know where the problem is. 
```yaml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: "xuanwu-chaos-agent"
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: 386
    binary: xuanwu-chaos-agent  # 这里替换为你的二进制文件名称
    ldflags:
      - "-X chaos-agent/version.Version={{.Version}}"  # 添加 ldflags，动态使用 Version
archives:
  - format: tar.gz
    wrap_in_directory: "chaos"
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: deploy/*
        dst: ./         # 将文件移动到压缩包的当前目录
        info:
          mode: 0755

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```
