### DISCUSSION TITLE
How do I include a file in my build? GH Action

### DISCUSSION THREAD

**Discussion by NoobTaco** [goreleaser/goreleaser#5254] [Q&A] [answered]
Hello there. I have a small go app that so far is building correctly, however I have not been able to figure out how to have the GoReleaser action add another file to the release.

I have a config.yaml file in the same directory as my main.go and need it in the package created.

here is my goreleaser.yml file
```

name: goreleaser

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

```

How do I tell the action to include my config.yaml in the built package?

Thank you for any help.
