### DISCUSSION TITLE
builds overrides getting ignored? (arm64)

### DISCUSSION THREAD

**Discussion by thediveo** [goreleaser/goreleaser#5297] [Q&A] [answered]
I want to build and release multi-arch binaries for amd64(_v1) as well as arm64, building them on amd64.

goreleaser v2.4.7 installed using `go install ...`.

```yaml
builds:
  - id: default
    main: ./cmd/xxx
    binary: xxx
    targets:
      - linux_amd64_v1
      - linux_arm64
    tags:
      - netgo
      - osusergo
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'
    env:
      - CGO_ENABLED=1
end }}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
```

From manual building I know what I need not only to set `CGO_ENABLED=1`, but for cross-compiling to arm64 I additionally need to set `CC=aarch64-linux-gnu-gcc`.

My problem now is that obviously the overrides get completely ignored, and the build fails with the probably well-known "no such instruction" assembler errors.

What am I overlooking and doing wrong here?
