### DISCUSSION TITLE
Is There a Better Way to Include Files Outside the Repository in GoReleaser Archives?

### DISCUSSION THREAD

**Discussion by ryancurrah** [goreleaser/goreleaser#5313] [Q&A] [answered]
I'm currently using GoReleaser and need to include a file (`wasm_exec.js`) located outside the repository path (`{{ .Env.GOROOT }}/misc/wasm/wasm_exec.js`) in an archive. Since GoReleaser archives can only include files within the build path, I've worked around this limitation by copying the file into the build path using `hooks` as shown below:

```yaml
archives:
  - id: cel_wasm
    builds: [cel_wasm]
    format: zip
    files:
      - dist/assets/wasm_exec.js
    hooks:
      before:
        - mkdir -p dist/assets
        - cp '{{ .Env.GOROOT }}/misc/wasm/wasm_exec.js' dist/assets/
```

This approach works, but I'm wondering if there's a cleaner or more efficient way to achieve this. Specifically:  
- Does GoReleaser have a built-in feature for including files from outside the repository path?
- Am I handling the file path correctly to ensure the archive structure is as intended?
- Is there a better way to structure the resulting archive so that `wasm_exec.js` does not appear in `dist/assets/wasm_exec.js`?

Looking forward to hearing your thoughts and suggestions!

Thanks,  
Ryan Currah

**Comment by caarlos0** [comment, marked as answer]
Hey!

Yeah, that is a good way to do it. You could also copy it to the root of the repo and add it to gitignore, which would also solve your 3rd point there.

GoReleaser doesn't have a feature to automatically import files that way, but it is a good suggestion, I think. Might be worth investigating 📓 

The path looks correct to me, if the archive isn't right, you can also use something like:

```yaml
archives:
  - 
    files:
      - src: dist/assets/wasm_exec.js
        dst: ./path/to/wasm_exec.js
```

Hope that helps!
