### DISCUSSION TITLE
Publishing to 2 different ECR repos using ko goreleaser

### DISCUSSION THREAD

**Discussion by Junaid82774464** [goreleaser/goreleaser#5318] [Q&A] [answered]
I have 2 projects in a repository. 
How can I use two different repos.

```
- name: Run GoReleaser
        id: build-image
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Tried setting `KO_DOCKER_REPO: ${{ steps.login-ecr-private.outputs.registry }}` and tried to reference it in the repository tag like this:
`repository: "{{.Env.KO_DOCKER_REPO}}/repo1"` 

```
kos:
  - id: project1
    build: build1
    bare: true
    sbom: none
    repository: {KO_DOCKER_REPO}/(repo1_name)
    tags:
      - "v{{.Version}}"
      - latest
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

  - id: project 2
    build: build 2
    bare: true
    sbom: none
    repository: {KO_DOCKER_REPO}/(repo2_name)
    tags:
      - "v{{.Version}}"
      - latest
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
 ```
 
 This approach doesn't work. Takes just the base value and throws an error.

**Comment by caarlos0** [comment, marked as answer]
I think you might need to pass the env to the workflow:

```yaml
      - name: Run GoReleaser
        id: build-image
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KO_DOCKER_REPO_1: ${{ steps.login-ecr-private.outputs.registry }}
          KO_DOCKER_REPO_2: ${{ steps.login-ecr-other.outputs.registry }} # I think you'll need to set it here
```

and in your configuration you can set repository to `{{.Env.KO_DOCKER_REPO_1}}` and `{{.Env.KO_DOCKER_REPO_2}}`.

https://goreleaser.com/customization/ko/

**Reply by Junaid82774464** [reply]
Tried it out. Doesn't seem to work.

```
- name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CA_NAMESPACE: ${{ vars.CA_NAMESPACE }}
          KO_DOCKER_REPO_CR: ${{ steps.login-ecr-private.outputs.registry }}/project1_repo
          KO_DOCKER_REPO_SU: ${{ steps.login-ecr-private.outputs.registry }}/project2_repo
```

```
kos:
  - id: project1
    build: project1
    bare: true
    sbom: none
    repository: "{{.Env.KO_DOCKER_REPO_CR}}"
    tags:
      - "v{{.Version}}"
      - latest
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

  - id: project2
    build: project2
    bare: true
    sbom: none
    repository: "{{.Env.KO_DOCKER_REPO_SU}}"
    tags:
      - "v{{.Version}}"
      - latest
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
```

This is the exact code that I have.
Does it explicitly have to be KO_DOCKER_REPO_1 , 2 for each number of repos? Or can it have any suffix?
When I checked the Github Actions, it's still tagging and publishing to ghcr.io/{org}/{repo}.

What am I missing?
