### DISCUSSION TITLE
MacOS: cannot build with -B gobuildid

### DISCUSSION THREAD

**Discussion by andig** [goreleaser/goreleaser#5321] [Q&A] [answered]
Trying to fix https://github.com/golang/go/issues/68678 for my build I have something like this in the goreleaser config (shortened version):

```yaml
builds:
  - id: evcc
    main: .
    flags:
      - -trimpath
      - -tags=release
    ldflags:
      - -X github.com/evcc-io/evcc/server.Version={{ .Version }} -X github.com/evcc-io/evcc/vehicle/tesla.TESLA_CLIENT_ID={{ .Env.TESLA_CLIENT_ID }} -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    overrides:
      - goos: darwin
        ldflags:
          - -B gobuildid
```

Verbose build shows:

```
  • building binaries
    • building                                       build={evcc [darwin] [arm64] [v1] [sse2] [6] [v8.0] [hardfloat] [power8] [rva20u64] [darwin_arm64_v8.0] [{windows arm       } {windows arm64       }] . . evcc {[] []} go   go build  false   { [-X github.com/evcc-io/evcc/server.Version={{ .Version }} -X github.com/evcc-io/evcc/vehicle/tesla.TESLA_CLIENT_ID={{ .Env.TESLA_CLIENT_ID }} -s -w] [] [-trimpath -tags=release] [] [] [CGO_ENABLED=0]} [{darwin         { [-B gobuildid] [] [] [] [] []}}]}
    • building                                       binary=release/evcc_darwin_arm64_v8.0/evcc
    • env "CGO_ENABLED=0" evaluated to "CGO_ENABLED=0"
    • running
    • added new artifact                             name=evcc type=Binary path=release/evcc_darwin_arm64_v8.0/evcc
```

I see that `-B gobuildid` is part of the build config, but I cannot see the actual build command run.

Final binary does not not work according to https://github.com/evcc-io/evcc/issues/17251, apparently because the buildid is still not applied?
