### DISCUSSION TITLE
Multi-module (go.work) build error, how to configure correctly

### DISCUSSION THREAD

**Discussion by ruanun** [goreleaser/goreleaser#5326] [Q&A]
Project file tree：

```shell
│  .goreleaser.yaml
│  Dockerfile
│  go.work
│  go.work.sum
├─module1
│  │  go.mod
│  │  go.sum
│  │  main.go
├─module2
│  │  go.mod
│  │  go.sum
│  │  main.go
```

.goreleaser.yaml

```yml
version: 2
builds:
  - id: module1
    binary: module1
    main: ./module1/main.go
    hooks:
      pre:
        - go mod tidy
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
  - id: module2
    binary: module2
    main: ./module2/main.go
    hooks:
      pre:
        - go mod tidy
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - id: module1
    builds:
      - module1
    format: tar.gz
    wrap_in_directory: true
    name_template: 'module1-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
  - id: module2
    builds:
      - module2
    format: tar.gz
    wrap_in_directory: true
    name_template: 'module2-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
dockers:
  - id: module2
    dockerfile: ./Dockerfile
    use: buildx
    image_templates:
      - "module/module2:{{ .Version }}"
```

An error occurred when executing the command `goreleaser release --snapshot --clean`

The error log is `pre hook failed: shell: 'go mod tidy': exit status 1: go: go.mod file not found in current directory or any parent directory; see 'go help modules'`

**Comment by caarlos0** [comment]
I think you'll need to set `builds.*.dir` instead of `main`

**Reply by ruanun** [reply]
Thank you for your answer. But after trying to modify it, it still has the same error as before.

```
builds:
  - id: module1
    binary: module1
    dir: module1
    hooks:
      pre:
        - go mod tidy
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
     .........
```

**Reply by caarlos0** [reply]
i think your actual config file has before hook calling `go mod tidy`?

because goreleaser itself never calls it...

I tested this on charmbraceled/x, both of these work:

```yaml
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    main: ./exp/open/cmd/
```

```yaml
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    dir: ./exp/open
    main: ./cmd
    binary: open
```


```sh
GORELEASER_CURRENT_TAG=v0.1.0 goreleaser r --snapshot --clean
```
