### DISCUSSION TITLE
What is the best way to configure docker image parties for building multiple platforms?

### DISCUSSION THREAD

**Discussion by ruanun** [goreleaser/goreleaser#5391] [Q&A] [answered]
This is the configuration:
```yaml
project_name: myproject
version: 2
builds:
  - id: multiarch
    binary: multiarch
    hooks:
      pre:
        - go mod tidy
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
 .....
dockers:
  - id: multiarch-linux-amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - "ruanun/multiarch:{{ .Version }}"
      - "ruanun/multiarch:latest"
  - id: multiarch-linux-arm64
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - "ruanun/multiarch:{{ .Version }}"
      - "ruanun/multiarch:latest"
docker_manifests:
  - id: multiarch
    name_template: "ruanun/multiarch:{{ .Version }}"
    image_templates:
      - "ruanun/multiarch:{{ .Version }}"
      - "ruanun/multiarch:latest"

```

I expected that:
The docker registry has two tags “ruanun/multiarch:1.0.0” and “ruanun/multiarch:latest”, which support arm64 and amd64
