### DISCUSSION TITLE
Customisation to allow for manual release process

### DISCUSSION THREAD

**Discussion by michealroberts** [goreleaser/goreleaser#5499] [Q&A]
Hello everyone 👋 

I am very new to go releaser, but I want to check the possibility of something before proceeding any deeper / further.

I like to have manual control of the release process, so I tag via the release functionality here on GitHub and amend the generated release notes to organize the conventional commits merged into main by what they affect. Anyways, I was wondering if it were possible to upload the release artifacts when this process is triggered manually back to the same release notes?

So the workflow would be:

release & tag => build artifacts => upload back to the same release ...

Would there be a limited number of customizations I would need to make here: https://goreleaser.com/customization/release/

If yes, would anyone be able to advise on this and on what a release.yml GitHub action should correspond to?

Many thanks!

**Comment by caarlos0** [comment]
You could:

1. set the release to draft - in that way, it would allow you to customize the release notes and then publish it
1. depending on how you want to group commits, goreleaser's changelog configuration allows you to do that automatically https://goreleaser.com/customization/changelog/
1. you could also build the release notes before hand, and pass them down to the release using the `--release-notes` flag https://goreleaser.com/cmd/goreleaser_release/


hope that helps!

**Reply by michealroberts** [reply]
@caarlos0 Ok cool I am looking at some of the release customisations, we have:

```yaml
release:
  # Whether to remove existing draft releases with the same name before creating
  # a new one.
  replace_existing_draft: false
  # Whether to use an existing draft release as the target release.
  use_existing_draft: true
```

And then this as well:

```yaml
release:
  ... 
  # What to do with the release notes in case there the release already exists.
  # Default: `keep-existing`.
  mode: append
```
