### DISCUSSION TITLE
[HELP] Automating the goreleaser process with GitHub Actions

### DISCUSSION THREAD

**Discussion by michealroberts** [goreleaser/goreleaser#5548] [Q&A] [answered]
I currently have a setup whereby I like to write the release notes so I can ensure consistency and pin any further notes I would like.

However, I am struggling to ensure the artifacts are uploaded to the repository.

My goreleaser strategy is as follows:

- When ready to release, tag and release from GitHub writing the release notes
- This triggers a build process (attached below) that then aims to attach the created artifacts back to the release.
- Done

This is my .goreleaser.yaml file:

```yaml
# @see goreleaser documentation at https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      # use commit date instead of current date as main.date
      # only needed if you actually use those things in your main package, otherwise can be ignored.
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

archives:
  # this name template makes the OS and Arch compatible with the results of `uname`.
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  # Whether to remove existing draft releases with the same name before creating a new one.
  replace_existing_draft: false
  # Whether to use an existing draft release as the target release.
  use_existing_draft: true
  # What to do with the release notes in case there the release already exists.
  mode: keep-existing
```

And this is the github action I am using to release:

```yaml
name: skysolve/release

on:
  pull_request:
    branches:
      - main

  release:
    types: [released]Is

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Import GPG Key
        id: gpgkey
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.gpgkey.outputs.fingerprint }}
```

The release process runs without failure, e.g., see [https://github.com/observerly/skysolve/actions/runs/13272439829](https://github.com/observerly/skysolve/actions/runs/13272439829) ... however, the artifacts are not attached to the release associated to it.

I'm wondering around these points:

- Is the release strategy in the .goreleaser.yaml file correct, e.g., replace_existing_draft and use_existing_draft etc ?
- Should I be using --snapshot ?
- Do I need to use the actions/upload-artifact@v4 action in combination with the goreleaser github action?
- Have I missed something else?
