### DISCUSSION TITLE
Changelog generation produces no lines if format does not begin with SHA

### DISCUSSION THREAD

**Discussion by shillberry** [goreleaser/goreleaser#5556] [Ideas, Issue Triage, and General discussions]
**Expected Behavior:** I expect to put the SHA at the end of the changelog commit (or exclude it altogether).
**Observed Behavior:** If I omit the SHA from the changelog format (or put it at the end), the changelog is empty.

**How to reproduce:**
Here is the changelog configuration I am using.

```yaml
changelog:
  disable: false
  use: gitlab
  format: "{{.Message}} (@{{.AuthorName}})"
  sort: asc
  abbrev: 6
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo
    include:
      - "^feat:"
      - "^fix:"
``` 

The Changelog that is generated appears empty:
```
## Changelog
```

If instead the format is provided with the SHA in the first position, the Changelog includes the expected rows:
```yaml
format: "{{ .SHA }}: {{ .Message }} (@{{.AuthorName}})"
```

Results in:
```
## Changelog   
### Features   
* 123abc feat: This is some feature (@user)
### Bug fixes   
* abc123 fix: This is some fix (@user)
```
