### DISCUSSION TITLE
Goreleaser Pro issue: custom release tag is not being taken into account for homebrew-tap updates

### DISCUSSION THREAD

**Discussion by skatkov** [goreleaser/goreleaser#5589] [Q&A] [answered]
Good day,

I have the couple of TUI apps with private source code, but I publish releases in a single github tap for them. This is done, so I can distribute binaries.

Here: https://github.com/skatkov/homebrew-tap

I was afraid, that releases for multiple software products in a single repository would collide due to similar release tags/names. So I bought Goreleaser Pro to resolve this issue.

Now I prefix all releases with "software-name"-v"number" -> https://github.com/skatkov/homebrew-tap/releases/tag/devtui-v0.5.2

I achieved this with a following goreleaser config:

```yaml
release:
  github:
    owner: skatkov
    name: homebrew-tap
  tag: "devtui-{{ .Tag }}"
  name_template: "devtui-{{ .Tag }}"

brews:
  - description: "A Swiss Army knife for developers"
    name: devtui
    repository:
      owner: skatkov
      name: homebrew-tap
```

But the problem is, that this has broken download urls for homebrew releases. 

See here:
https://github.com/skatkov/homebrew-tap/blob/master/devtui.rb

Download url is `https://github.com/skatkov/homebrew-tap/releases/download/v0.5.2/devtui_Darwin_x86_64.tar.gz`. Custom tag is not used, so this fails.

I would expect it to be:
https://github.com/skatkov/homebrew-tap/releases/download/devtui-v0.5.2/devtui_Darwin_x86_64.tar.gz
