### DISCUSSION TITLE
Including signature and certificate in archives when using cosign keyless

### DISCUSSION THREAD

**Discussion by mrh-chain** [goreleaser/goreleaser#5604] [Q&A] [answered]
I am trying to use cosign in keyless mode on GitHub Actions in conjunction with goreleaser, and it appears to be signing things as expected.

Unfortunately, I've noticed that the signature and certificates isn't added to the archives. I've configured my "artifactories" target to include "signature", but it would appear that the signatures are added at the same level as each archive. Because my signature and certificate has a static name, this causes them to override each other which means that what gets uploaded is only good to verify one of the archives binary.

From the docs I can see that `binary_signs` "runs during the build phase", which gives me a hope that the files could somehow be added to the archives, but I'm unsure how to configure that - Could someone help?

My current config (which causes the signature and certificates to overwrite each other) is:
```yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  skip_upload: true

artifactories:
  - name: production
    target: https://[REDACTED]/artifactory/[REDACTED]/{{ .ProjectName }}/{{ .Version }}/
    checksum: true
    meta: true
    signature: true

binary_signs:
  - cmd: cosign
    certificate: '{{ trimsuffix .Env.artifact "tar.gz" }}.pem'
    signature: "${artifact}_sig"
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"
```

**Comment by mrh-chain** [comment]
I found a way to include signature and certificate in the archive. I noticed that `binary_signs` adds the files defined by its children `certificate` and `signature` to a folder for each binary. For my MacOS Arm64, that folder was `dist/darwin_arm64_v8.0` and for Linux AMD64 it was `dist/linux/amd64_v1`.

Given these are created before the archiving phase, I figured I'd be able to define them using the `files` child of `archives`. Unfortunately, I couldn't find a way to define the target repo using a template. So I had to define each build and archive separately.

It works, but it isn't pretty. Additionally, I removed `artifactories[0].signature` as I don't think I would need this.

Would be **very** nice if there was a way to specify the directory used by `binary_signs` for its certificate and signature during the archiving phase.

Working example:

```yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
  - id: darwin-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  - id: linux-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: linux-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

archives:
  - id: darwin-arm64
    builds: [ "darwin-arm64"]
    formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_Darwin_arm64"
    files:
      - README.md
      - LICENSE.md
      - src: "dist/darwin-arm64_darwin_arm64_v8.0/[REDACTED].sig"
        strip_parent: true
      - src: "dist/darwin-arm64_darwin_arm64_v8.0/[REDACTED].pem"
        strip_parent: true
  - id: darwin-amd64
    builds: [ "darwin-amd64"]
    formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_Darwin_x86_64"
    files:
      - README.md
      - LICENSE.md
      - src: "dist/darwin-amd64_darwin_amd64_v1/[REDACTED].sig"
        strip_parent: true
      - src: "dist/darwin-amd64_darwin_amd64_v1/[REDACTED].pem"
        strip_parent: true
  - id: linux-amd64
    builds: [ "linux-amd64"]
    formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_Linux_x86_64"
    files:
      - README.md
      - LICENSE.md
      - src: "dist/linux-amd64_linux_amd64_v1/[REDACTED].sig"
        strip_parent: true
      - src: "dist/linux-amd64_linux_amd64_v1/[REDACTED].pem"
        strip_parent: true
  - id: linux-arm64
    builds: [ "linux-arm64"]
    formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_Linux_arm64"
    files:
      - README.md
      - LICENSE.md
      - src: "dist/linux-arm64_linux_arm64_v8.0/[REDACTED].sig"
        strip_parent: true
      - src: "dist/linux-arm64_linux_arm64_v8.0/[REDACTED].pem"
        strip_parent: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  skip_upload: true

artifactories:
  - name: production
    target: https://[REDACTED]/artifactory/[REDACTED]/{{ .ProjectName }}/{{ .Version }}/
    checksum: true
    meta: true

binary_signs:
  - cmd: cosign
    certificate: '{{ trimsuffix .Env.artifact "tar.gz" }}.pem'
    signature: "${artifact}.sig"
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"
```

**Reply by caarlos0** [reply, marked as answer]
You can do something like this in the archives:

```yaml
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

binary_signs:
  - cmd: cosign
    certificate: '{{ trimsuffix .Env.artifact "tar.gz" }}.pem'
    signature: "${artifact}.sig"
    output: true
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

archives:
  - formats: ["tar.gz"]
    files:
      - README.md
      - LICENSE.md
      - src: "dist/foo_{{ .Os }}_{{ .Arch }}*/foo.sig"
        strip_parent: true
      - src: "dist/foo_{{ .Os }}_{{ .Arch }}*/foo.pem"
        strip_parent: true
```

final result tar.gz would look like this:

```console
$ tar tvf dist/foo_0.0.0-SNAPSHOT-none_darwin_amd64.tar.gz
-rw-r--r--  0 carlos wheel       0 Mar  5 10:27 LICENSE.md
-rw-r--r--  0 carlos wheel       0 Mar  5 10:27 README.md
-rw-------  0 carlos wheel    1396 Mar  5 10:30 foo.pem
-rw-------  0 carlos wheel      96 Mar  5 10:30 foo.sig
-rwxr-xr-x  0 carlos staff  910112 Mar  5 10:30 foo
```

Then the artifactories would include the tar.gz with the signature in it - which I think is what you want?
