### DISCUSSION TITLE
`schema.json` lists the MacOS Notarize `timeout` field as `integer`

### DISCUSSION THREAD

**Discussion by briangardner** [goreleaser/goreleaser#5616] [Ideas, Issue Triage, and General discussions]
The `timeout` field in `notarize.macos.notarize` is a `time.Duration`, meaning it needs to be a string to support values like `20m`.

Example Notarize block:
```yaml
notarize:
  macos:
    - ids:
      - build1
      enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: '{{.Env.MACOS_SIGN_P12 }}'
        password: '{{.Env.MACOS_SIGN_P12_PASSWORD }}'
      notarize:
        issuer_id: '{{.Env.MACOS_SIGN_ISSUER_ID }}'
        key: '{{.Env.MACOS_SIGN_KEY }}'
        key_id: {{.Env.MACOS_SIGN_KEY_ID }}'
        wait: true
        timeout: 20
```

This will generate the error
```
error=
    │ failed to load configuration: yaml: unmarshal errors:
    │   line 108: cannot unmarshal !!int `20` into time.Duration
```
