### DISCUSSION TITLE
goreleaser release: brews committed update to wrong path

### DISCUSSION THREAD

**Discussion by till** [goreleaser/goreleaser#5665] [Q&A] [answered]
Hi,

I have a pretty standard brews configuration, but I noticed that goreleaser now updates a file `cli.rb` in the root of the repository, and no longer in Formula folder. Has something changed here?

```yaml
brews:
- name: cli
  ids:
  - archive
  goarm: 6
  goamd64: v1

  url_template: "https://download.example.org/cli/{{ .Version }}/{{ .ArtifactName }}"
  download_strategy: CurlDownloadStrategy
  commit_author:
    name: user
    email: email@example.org
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  caveats: "Run `cli login` to get started, and `cli install-completions` to install auto-complete"

  homepage: ""
  description: "My CLI."
  license: "proprietary"
  skip_upload: false
  dependencies: []
  conflicts: []
  test: |
    system "#{bin}/cli version"
```

Till

**Comment by till** [comment]
Maybe for completeness, this is how we release:

```
    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: nightly
        args: release --clean --release-header-tmpl release.tmpl.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ANOTHER_TOKEN: ${{ secrets.ANOTHER_TOKEN }}
```
