### DISCUSSION TITLE
How to set buildmode only for architectures that support it?

### DISCUSSION THREAD

**Discussion by alexbozhenko** [goreleaser/goreleaser#5680] [Q&A] [answered]
Hi, Noble people!

When I set 
```
buildmode: pie
```
(https://pkg.go.dev/cmd/go#hdr-Build_modes)

I got:
```
 ⨯ release failed after 49s                
    error=
    │ build failed: exit status 1: -buildmode=pie not supported on linux/mips64le
    target=linux_mips64le_hardfloat
```

That's because not all arches support it: https://github.com/golang/go/issues/64875

Is there a way to override build mode to default for `goarch`es that do not support it, without duplicating the entire build config?

I guess I can list all of the os X arch combinations that do not support the buildmode, but is there a better way?
```
    overrides:
      - goos: linux
        goarch: mips64le
        buildmode: "exe"
      - goos: linux
        goarch: 386
        buildmode: "exe"
      - goos: linux
        goarch: arm
        buildmode: "exe"
      - goos: linux
        goarch: s390x
        buildmode: "exe"
```

Thanks.

**Comment by alexbozhenko** [comment]
Found this example:
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/708/files
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/726/files
But they actually have code generating the goreleaser config.

**Comment by caarlos0** [comment, marked as answer]
Hey!

I believe you'll have to create one build with the targets that support it, and another build with the targets that don't.

As long as you're not filtering anything by id later (i.e. setting `ids: `), it should all work fine.

Note that you'll need to add an ID to both builds, e.g.:

```yaml
builds:
- id: pie
  buildmode: pie
  targets: [ ... ]
- id: nopie
  targets: [ ... ]
```

Hope this helps!
