### DISCUSSION TITLE
I just want to package the current file to dist. What should I do? All suggestions are appreciated

### DISCUSSION THREAD

**Discussion by super-sunshines** [goreleaser/goreleaser#5686] [Q&A] [answered]
```
E:\Project\RC01-RS-IPV\server git:[main]
goreleaser release --snapshot --clean --skip=validate  --snapshot
  • skipping announce, publish, and validate...
  • cleaning distribution directory
  • loading environment variables
  • getting and validating git state
    • couldn't find any tags before "V1.0.0.0"
    • git state                                      commit=5513a9147964a158cd0c5e7e655804f15ee347ad branch=main current_tag=V1.0.0.0 previous_tag=<unknown> dirty=true
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  ⨯ release failed after 0s                  error=failed to parse tag 'V1.0.0.0' as semver: Invalid Semantic Version
```

```yaml

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
#      - windows
    goarch:
      - amd64
#      - arm64
    ignore:
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: darwin
        goarch: 386


```
