### DISCUSSION TITLE
How can we integrate the Datadog orchestrion with GoReleaser?

### DISCUSSION THREAD

**Discussion by imzza** [goreleaser/goreleaser#5702] [Q&A] [answered]
For Datadog APM, we need to build the binary with the Datadog package. This suggests using the following build command:

```bash
orchestrion go build .
```
I have tried using a pre-hook with:
```bash
orchestrion go generate ./...
```
but it didn't work.

Does anyone have any ideas on how to integrate this with GoReleaser?

Here is my complete GoReleaser config for reference:
```yaml
project_name: testapp
builds:
  - id: testapp
    main: ./cmd/main.go
    no_main_check: false
    binary: testapp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    targets:
      - linux_amd64
      - windows_amd64
  - id: testapp-datagog
    main: ./cmd/main.go
    no_main_check: false
    binary: testapp-datagog
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    targets:
      - linux_amd64
      - windows_amd64
upx:
  - # Whether to enable it or not.
    enabled: true
    
    # Filter by build ID.
    ids: [testapp, testapp-datagog]

    # Filter by GOOS.
    goos: [linux, darwin]

    # Filter by GOARCH.
    goarch: [arm, amd64]

    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best

    # Whether to try LZMA (slower).
    lzma: true

    # Whether to try all methods and filters (slow).
    brute: true
```

**Comment by caarlos0** [comment, marked as answer]
I never used it, but you can probably set `builds.tool` and `builds.command` https://goreleaser.com/customization/builds/go/

```yaml
# ...
builds:
  - tool: orchestration
    command: build
    # ...
```
