### DISCUSSION TITLE
upx evaluation bug?

### DISCUSSION THREAD

**Discussion by LeeTeng2001** [goreleaser/goreleaser#5718] [Ideas, Issue Triage, and General discussions]
```yaml
upx:
  - enabled: false
    ids: [binary1]
    compress: 1
    lzma: true
  - enabled: true
    ids: [binary2]
    compress: 1
    lzma: true
```
upx will not run even though binary2 is enabled, there might be an evaluation bug in upx configuration
