### DISCUSSION TITLE
`error=failed to add: 'dist/whats_x86_64-linux-gnu/whats' -> 'whats': add whats: file already exists`

### DISCUSSION THREAD

**Discussion by mrusme** [goreleaser/goreleaser#5721] [Ideas, Issue Triage, and General discussions]
Zig project.

```yaml
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - builder: zig
    flags:
      - -Doptimize=ReleaseSafe
    targets:
      - aarch64-linux
      - aarch64-macos
      - aarch64-windows
      - arm-linux
      - x86_64-linux-gnu
      - x86_64-linux-musl
      - x86_64-macos
      - x86_64-windows

archives:
  - formats: [tar.gz]
    allow_different_binary_count: true
    name_template: >-
      {{ .ProjectName }}_{{- .Target }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  disable: false
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: ""

```

```sh
goreleaser release --clean --snapshot                                                                                master 4eb500
  • skipping announce, publish, and validate...
  • cleaning distribution directory
  • loading environment variables
    • using token from  $GITHUB_TOKEN
  • getting and validating git state
    • ignoring errors because this is a snapshot     error=git doesn't contain any tags - either add a tag or use --snapshot
    • git state                                      commit=4eb5007dcb9a893f01f390820c16db08fc7ce641 branch=master current_tag=v0.0.0 previous_tag=<unknown> dirty=false
    • pipe skipped or partially skipped              reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
    • you are using the experimental Zig builder
  • snapshotting
    • building snapshot...                           version=0.0.0-SNAPSHOT-4eb5007
  • ensuring distribution directory
  • setting up metadata
  • writing release metadata
  • build prerequisites
  • building binaries
    • building                                       binary=dist/whats_aarch64-macos/whats
    • building                                       binary=dist/whats_aarch64-windows/whats.exe
    • building                                       binary=dist/whats_x86_64-windows/whats.exe
    • building                                       binary=dist/whats_arm-linux/whats
    • building                                       binary=dist/whats_x86_64-macos/whats
    • building                                       binary=dist/whats_x86_64-linux-musl/whats
    • building                                       binary=dist/whats_aarch64-linux/whats
    • building                                       binary=dist/whats_x86_64-linux-gnu/whats
  • archives
    • archiving                                      name=dist/whats_aarch64-macos.tar.gz
    • archiving                                      name=dist/whats_aarch64-windows.zip
    • archiving                                      name=dist/whats_arm-linux.tar.gz
    • archiving                                      name=dist/whats_x86_64-windows.zip
    • archiving                                      name=dist/whats_x86_64-linux-musl.tar.gz
    • archiving                                      name=dist/whats_x86_64-macos.tar.gz
    • archiving                                      name=dist/whats_aarch64-linux.tar.gz
  ⨯ release failed after 0s                  error=failed to add: 'dist/whats_x86_64-linux-gnu/whats' -> 'whats': add whats: file already exists
```

```sh
ls -R dist                                                                                                           master 4eb500
0644 .rw-r--r-- 3.6Ki mrus mrus 1 minute -I  config.yaml
0644 .rw-r--r--   233 mrus mrus 1 minute -I  metadata.json
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_aarch64-linux
0644 .rw-r--r-- 781Ki mrus mrus 1 minute -I  whats_aarch64-linux.tar.gz
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_aarch64-macos
0644 .rw-r--r-- 182Ki mrus mrus 1 minute -I  whats_aarch64-macos.tar.gz
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_aarch64-windows
0644 .rw-r--r-- 239Ki mrus mrus 1 minute -I  whats_aarch64-windows.zip
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_arm-linux
0644 .rw-r--r-- 893Ki mrus mrus 1 minute -I  whats_arm-linux.tar.gz
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_x86_64-linux-gnu
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_x86_64-linux-musl
0644 .rw-r--r-- 818Ki mrus mrus 1 minute -I  whats_x86_64-linux-musl.tar.gz
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_x86_64-macos
0644 .rw-r--r-- 191Ki mrus mrus 1 minute -I  whats_x86_64-macos.tar.gz
0755 drwxr-xr-x     - mrus mrus 1 minute -I  whats_x86_64-windows
0644 .rw-r--r-- 255Ki mrus mrus 1 minute -I  whats_x86_64-windows.zip

dist/whats_aarch64-linux:
0755 .rwxr-xr-x 2.7Mi mrus mrus 1 minute -I  whats

dist/whats_aarch64-macos:
0755 .rwxr-xr-x 363Ki mrus mrus 1 minute -I  whats

dist/whats_aarch64-windows:
0755 .rwxr-xr-x 608Ki mrus mrus 1 minute -I  whats.exe

dist/whats_arm-linux:
0755 .rwxr-xr-x 2.5Mi mrus mrus 1 minute -I  whats

dist/whats_x86_64-linux-gnu:
0755 .rwxr-xr-x 2.8Mi mrus mrus 1 minute -I  whats

dist/whats_x86_64-linux-musl:
0755 .rwxr-xr-x 2.8Mi mrus mrus 1 minute -I  whats

dist/whats_x86_64-macos:
0755 .rwxr-xr-x 385Ki mrus mrus 1 minute -I  whats

dist/whats_x86_64-windows:
0755 .rwxr-xr-x 675Ki mrus mrus 1 minute -I  whats.exe
```

```sh
jq < dist/metadata.json                                                                                              master 4eb500
{
  "project_name": "whats",
  "tag": "v0.0.0",
  "previous_tag": "",
  "version": "0.0.0-SNAPSHOT-4eb5007",
  "commit": "4eb5007dcb9a893f01f390820c16db08fc7ce641",
  "date": "2025-04-14T19:59:58.150340793-05:00",
  "runtime": {
    "goos": "linux",
    "goarch": "amd64"
  }
}
```
