### DISCUSSION TITLE
Simplier Multiarch Docker Build

### DISCUSSION THREAD

**Discussion by shyim** [goreleaser/goreleaser#5730] [Ideas, Issue Triage, and General discussions]
Right now it's pretty ugly how to manage docker images and if they are multi-arch it gets worse

See here as an example:

https://github.com/shopware/shopware-cli/blob/main/.goreleaser.yaml#L46-L188

It would be nice if this could be somehow easier configurable and not so verbose:

```
dockers:
  - use: buildx
     arch:
        - arm64
        - amd64
    image_templates:
      - my-image name
```
