### DISCUSSION TITLE
Is is possible to use common templates as the default value in the global environment section?

### DISCUSSION THREAD

**Discussion by timflannagan** [goreleaser/goreleaser#5740] [Q&A] [answered]
I'm trying to onboard goreleaser on a new repository, following the https://goreleaser.com/customization/env/ instructions, and trying to see whether the gauge whether following is supported:

```
version: 2
env:
  - IMAGE_TAG={{ if index .Env "IMAGE_TAG"  }}{{ .Env.IMAGE_TAG }}{{ else }}{{ .Tag }}{{ end }}
before:
  hooks:
    - go mod tidy
    - go mod download
...
dockers:
  - image_templates:
      - &controller-amd64 "ghcr.io/<substituted>:{{ .Env.IMAGE_TAG }}-amd64"
...
```

When the env.IMAGE_TAG value is unset, I'm seeing the default value render to an empty value and an invalid container image format. Same if I replace the `{{ .Tag }}` with `{{ .ShortCommit }}` for the default value clause. Is it possible to use https://goreleaser.com/customization/templates/#common-fields within the global environment template or is that unsupported?

As always, thanks for the great project!
