### DISCUSSION TITLE
MD5 and SHA1 checksum header for Artifactory

### DISCUSSION THREAD

**Discussion by skycaptain** [goreleaser/goreleaser#5742] [Ideas, Issue Triage, and General discussions]
This is a follow-up on #752. Artifactory seem to require the SHA256 checksum from the client along with MD5 and SHA1 checksums in the request header. Without all three checksums, Artifactory reports insufficient client checksums. As shown in the screenshot, while the SHA256 is marked as `(Uploaded: Identical)`, the other checksums are marked as `(Uploaded: None)`:

![Screenshot 2025-04-26 at 11 16 49](https://github.com/user-attachments/assets/35260168-2507-4905-b1c0-0c46d0482f5e)

Several possible solutions come to my mind:

- Allow adding multiple `checksum_header`
- Hard-code these headers directly in `internal/pipe/artifactory`, since they're always needed for Artifactory.
- Use Jfrog’s official Go library, which automatically handles the right headers: https://github.com/jfrog/jfrog-client-go
- Add a `checksum` function to the template function map, allow adding the checksums via `custom_headers` e.g.:

```yaml
artifactories:
  - name: production
    target: http://<Your-Instance>:8081/artifactory/example-repo-local/{{ .ProjectName }}/{{ .Version }}/
    custom_headers:
      X-Checksum-MD5: "{{ md5 .ArtifactPath }}"
      X-Checksum-SHA1: "{{ sha1 .ArtifactPath }}"
      X-Checksum-SHA256: "{{ sha256 .ArtifactPath }}"
```

I prefer the last option as it's the simplest to implement without breaking existing features. Adding hashing functions to templates would also enable their use elsewhere—for example, uploading files to object storage using paths like `https://artifacts.example.com/{{ sha256 .ArtifactPath }}/`.

EDIT: Applied suggestion from https://github.com/goreleaser/goreleaser/pull/5743#discussion_r2063509674. 
<details>

<summary>Original suggestion</summary>

```yaml
artifactories:
  - name: production
    target: http://<Your-Instance>:8081/artifactory/example-repo-local/{{ .ProjectName }}/{{ .Version }}/
    custom_headers:
      X-Checksum-MD5: "{{ checksum .ArtifactPath \"md5\" }}"
      X-Checksum-SHA1: "{{ checksum .ArtifactPath \"sha1\" }}"
      X-Checksum-SHA256: "{{ checksum .ArtifactPath \"sha256\" }}"
```

</details>
