### DISCUSSION TITLE
Cloudsmiths: looks like "set multiple distributions for a format" isn't work as expected

### DISCUSSION THREAD

**Discussion by Nmishin** [goreleaser/goreleaser#5758] [Ideas, Issue Triage, and General discussions]
After upgrading to the new goreleaser version, I updated cloudsmiths config as described in the docks:
```
cloudsmiths:
  - organization: tofuutils
    repository: tenv
    distributions:
      deb:
        - "ubuntu/focal"
        - "ubuntu/jammy"
        - "ubuntu/noble"
```
Commit with full code change: https://github.com/tofuutils/tenv/commit/b66c29e25b2f54f949130fc6c201c5efb86369b6

But when we tried to release, we discovered an issue with publishing artifacts to cloudsmiths:
```
 release failed after 6m54s               error=cloudsmith: failed to publish artifacts: cloudsmith: failed to upload package: dist/tenv_v4.5.0_arm.deb: request failed to https://api.cloudsmith.io/v1/packages/tofuutils/tenv/upload/deb/: 422 Unprocessable Entity
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.9.0/x64/goreleaser' failed with exit code 1
```

Failed release job: https://github.com/tofuutils/tenv/actions/runs/14861654351/job/41727848912
Successful release job, before config update: https://github.com/tofuutils/tenv/actions/runs/14019801719/job/39250219595

Config looks correct, and match to the example: https://goreleaser.com/customization/cloudsmith/#customization

Maybe I missing something here?
