### DISCUSSION TITLE
Error while using goreleaser cross compilation for Rust

### DISCUSSION THREAD

**Discussion by Propfend** [goreleaser/goreleaser#5790] [Ideas, Issue Triage, and General discussions]
```bash
goreleaser init
```
the goreleaser.yml generated:
```yml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # if you don't do these things before calling goreleaser, it might be a
    # good idea to do them here:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      # - x86_64-apple-darwin
      # - x86_64-pc-windows-gnu
      # - aarch64-unknown-linux-gnu
      # - aarch64-apple-darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

```
activating in ubuntu-latest by:
```yml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
running on `ubuntu-latest` and always get same problem:
```bash
Compiling regex v1.11.1
    │ warning: openssl-sys@0.9.104: In file included from build/expando.c:1:
    │ warning: openssl-sys@0.9.104: In file included from /usr/include/openssl/opensslv.h:109:
    │ warning: openssl-sys@0.9.104: /usr/include/openssl/macros.h:14:10: fatal error: 'openssl/opensslconf.h' file not found
    │ warning: openssl-sys@0.9.104:    14 | #include <openssl/opensslconf.h>
    │ warning: openssl-sys@0.9.104:       |          ^~~~~~~~~~~~~~~~~~~~~~~
    │ warning: openssl-sys@0.9.104: 1 error generated.
    │ error: failed to run custom build command for `openssl-sys v0.9.104`
    │ Caused by:
    │   process didn't exit successfully: `/home/runner/work/paddler/paddler/target/release/build/openssl-sys-23fc553afe785810/build-script-main` (exit status: 101)
    │   --- stdout
    │   cargo:rustc-check-cfg=cfg(osslconf, values("OPENSSL_NO_OCB", "OPENSSL_NO_SM4", "OPENSSL_NO_SEED", "OPENSSL_NO_CHACHA", "OPENSSL_NO_CAST", "OPENSSL_NO_IDEA", "OPENSSL_NO_CAMELLIA", "OPENSSL_NO_RC4", "OPENSSL_NO_BF", "OPENSSL_NO_PSK", "OPENSSL_NO_DEPRECATED_3_0", "OPENSSL_NO_SCRYPT", "OPENSSL_NO_SM3", "OPENSSL_NO_RMD160", "OPENSSL_NO_EC2M", "OPENSSL_NO_OCSP", "OPENSSL_NO_CMS", "OPENSSL_NO_COMP", "OPENSSL_NO_SOCK", "OPENSSL_NO_STDIO", "OPENSSL_NO_EC", "OPENSSL_NO_SSL3_METHOD", "OPENSSL_NO_KRB5", "OPENSSL_NO_TLSEXT", "OPENSSL_NO_SRP", "OPENSSL_NO_RFC3779", "OPENSSL_NO_SHA", "OPENSSL_NO_NEXTPROTONEG", "OPENSSL_NO_ENGINE", "OPENSSL_NO_BUF_FREELISTS"))
    │   cargo:rustc-check-cfg=cfg(openssl)
    │   cargo:rustc-check-cfg=cfg(libressl)
    │   cargo:rustc-check-cfg=cfg(boringssl)
    │   cargo:rustc-check-cfg=cfg(libressl250)
    │   cargo:rustc-check-cfg=cfg(libressl251)
    │   cargo:rustc-check-cfg=cfg(libressl252)
    │   cargo:rustc-check-cfg=cfg(libressl261)
    │   cargo:rustc-check-cfg=cfg(libressl270)
    │   cargo:rustc-check-cfg=cfg(libressl271)
    │   cargo:rustc-check-cfg=cfg(libressl273)
    │   cargo:rustc-check-cfg=cfg(libressl280)
    │   cargo:rustc-check-cfg=cfg(libressl281)
    │   cargo:rustc-check-cfg=cfg(libressl291)
    │   cargo:rustc-check-cfg=cfg(libressl310)
    │   cargo:rustc-check-cfg=cfg(libressl321)
    │   cargo:rustc-check-cfg=cfg(libressl332)
    │   cargo:rustc-check-cfg=cfg(libressl340)
    │   cargo:rustc-check-cfg=cfg(libressl350)
    │   cargo:rustc-check-cfg=cfg(libressl360)
    ��   cargo:rustc-check-cfg=cfg(libressl361)
    │   cargo:rustc-check-cfg=cfg(libressl370)
    │   cargo:rustc-check-cfg=cfg(libressl380)
    │   cargo:rustc-check-cfg=cfg(libressl381)
    │   cargo:rustc-check-cfg=cfg(libressl382)
    │   cargo:rustc-check-cfg=cfg(libressl390)
    │   cargo:rustc-check-cfg=cfg(libressl400)
    │   cargo:rustc-check-cfg=cfg(ossl101)
    │   cargo:rustc-check-cfg=cfg(ossl102)
    │   cargo:rustc-check-cfg=cfg(ossl102f)
    │   cargo:rustc-check-cfg=cfg(ossl102h)
    │   cargo:rustc-check-cfg=cfg(ossl110)
    │   cargo:rustc-check-cfg=cfg(ossl110f)
    │   cargo:rustc-check-cfg=cfg(ossl110g)
    │   cargo:rustc-check-cfg=cfg(ossl110h)
    │   cargo:rustc-check-cfg=cfg(ossl111)
    │   cargo:rustc-check-cfg=cfg(ossl111b)
    │   cargo:rustc-check-cfg=cfg(ossl111c)
    │   cargo:rustc-check-cfg=cfg(ossl111d)
    │   cargo:rustc-check-cfg=cfg(ossl300)
    │   cargo:rustc-check-cfg=cfg(ossl310)
    │   cargo:rustc-check-cfg=cfg(ossl320)
    │   cargo:rustc-check-cfg=cfg(ossl330)
    │   cargo:rustc-check-cfg=cfg(ossl340)
    │   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
    │   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
    │   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
    │   OPENSSL_LIB_DIR unset
    │   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
    │   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
    │   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
    │   OPENSSL_INCLUDE_DIR unset
    │   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
    │   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
    │   cargo:rerun-if-env-changed=OPENSSL_DIR
    │   OPENSSL_DIR unset
    │   cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
    │   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
    │   cargo:rerun-if-env-changed=PKG_CONFIG
    │   cargo:rerun-if-env-changed=OPENSSL_STATIC
    │   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
    │   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
    │   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
    │   cargo:rerun-if-env-changed=SYSROOT
    │   cargo:rerun-if-env-changed=OPENSSL_STATIC
    │   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
    │   cargo:rustc-link-lib=ssl
    │   cargo:rustc-link-lib=crypto
    │   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
    │   cargo:rerun-if-env-changed=PKG_CONFIG
    │   cargo:rerun-if-env-changed=OPENSSL_STATIC
    │   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
    │   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
    │   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
    │   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
    │   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
    │   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
    │   cargo:rerun-if-changed=build/expando.c
    │   OPT_LEVEL = Some(3)
    │   OUT_DIR = Some(/home/runner/work/paddler/paddler/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-3ebba3e0b690f3a9/out)
    │   TARGET = Some(x86_64-unknown-linux-gnu)
    │   HOST = Some(x86_64-unknown-linux-gnu)
    │   cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
    │   CC_x86_64-unknown-linux-gnu = None
    │   cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
    │   CC_x86_64_unknown_linux_gnu = Some(/home/runner/.cache/cargo-zigbuild/0.20.0/zigcc-x86_64-unknown-linux-gnu-de6.sh)
    │   RUSTC_WRAPPER = None
    │   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
    │   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
    │   CRATE_CC_NO_DEFAULTS = None
    │   DEBUG = Some(false)
    │   cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
    │   CFLAGS_x86_64-unknown-linux-gnu = None
    │   cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
    │   CFLAGS_x86_64_unknown_linux_gnu = None
    │   cargo:rerun-if-env-changed=HOST_CFLAGS
    │   HOST_CFLAGS = None
    │   cargo:rerun-if-env-changed=CFLAGS
    │   CFLAGS = None
    │   cargo:warning=In file included from build/expando.c:1:
    │   cargo:warning=In file included from /usr/include/openssl/opensslv.h:109:
    │   cargo:warning=/usr/include/openssl/macros.h:14:10: fatal error: 'openssl/opensslconf.h' file not found
    │   cargo:warning=   14 | #include <openssl/opensslconf.h>
    │   cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~
    │   cargo:warning=1 error generated.
    │   --- stderr
    │   thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-[194](https://github.com/Propfend/paddler/actions/runs/15228759823/job/42834028472#step:4:195)9cf8c6b5b557f/openssl-sys-0.9.104/build/main.rs:264:13:
    │   Header expansion error:
    │   Error { kind: ToolExecError, message: "Command \"/home/runner/.cache/cargo-zigbuild/0.20.0/zigcc-x86_64-unknown-linux-gnu-de6.sh\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"--target=x86_64-unknown-linux-gnu\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args zigcc-x86_64-unknown-linux-gnu-de6.sh did not execute successfully (status code exit status: 1)." }
    │   Failed to find OpenSSL development headers.
    │   You can try fixing this setting the `OPENSSL_DIR` environment variable
    │   pointing to your OpenSSL installation or installing OpenSSL headers package
    │   specific to your distribution:
    │       # On Ubuntu
    │       sudo apt-get install pkg-config libssl-dev
    │       # On Arch Linux
    │       sudo pacman -S pkgconf openssl
    │       # On Fedora
    │       sudo dnf install pkgconf perl-FindBin perl-IPC-Cmd openssl-devel
    │       # On Alpine Linux
    │       apk add pkgconf openssl-dev
    │   See rust-openssl documentation for more information:
    │       https://docs.rs/openssl
    │   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    │ warning: build failed, waiting for other jobs to finish...
    target=x86_64-unknown-linux-gnu
``` 
tried:
- Different zig versions
- Running `sudo apt-get install pkg-config libssl-dev`
- Manually linking `OPENSSL_DIR`
