### DISCUSSION TITLE
CGO_ENABLED builds.<id>.env seems broken in goreleaser 2.10.2

### DISCUSSION THREAD

**Discussion by nwcs-sh** [goreleaser/goreleaser#5832] [Q&A] [answered]
`goreleaser` version: 2.10.2
`go` version: 1.24.4

When I try to build a CGO required project it fails, below output:

```
  - id: mybin
    main: ./cmd/mybin/main.go
    binary: bin/mybin
    env:
    - CGO_ENABLED=1
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    goos:
      - linux
    goarch:
      - amd64
```

The error:

```
  ⨯ release failed after 1s                 
    error=
    │ build failed: exit status 1: # github.com/blah/blah
    │ vendor/blah/blah...: undefined: Return
    ...
```

If I do the build manually with go it builds fine, if I do the build with `CGO_ENABLED=0` the exact same error is returned. Is the env variable not being passed?
