### DISCUSSION TITLE
Using GoReleaser to build and push Kubernetes manifests and Helm charts

### DISCUSSION THREAD

**Discussion by nourspace** [goreleaser/goreleaser#5851] [Q&A] [answered]
I have Kubernetes manifests that I'd like to push to an OCI repository as part of my release workflow. I'm using a custom publisher to achieve this. The goal is to create two **tagged Docker images** and two **tagged Kubernetes manifest artifacts**, with their digests showing in my release notes (which is somewhat achievable).

The challenge is pinning container images in the Kubernetes manifests to their relevant Docker image tags and digests. **How should I approach this?**

The issues I'm facing are mostly related to not having access to the digest in my custom publisher. The normal `goreleaser release` builds the images, runs custom publishers, then pushes the images (making the digest available only after custom publishers run).

### Solutions I've considered:

1. **Pushing the image in my custom publisher to capture the digest**
  - Haven't tried this yet
  - Could skip pushing in the Docker step, but would lose the digest in release notes

2. **Using the [Split & Merge](https://goreleaser.com/customization/partial/) flow**
  - Ensures Docker images are pushed first
  - Adds complexity: more steps, extra env vars required
  - Results in GitHub release notes with only changelog (missing custom header/footer unlike regular `release`)

### Nice-to-have features
- Ability to define custom artifact kinds
  I think Helm charts and Kubernetes manifests are common to have and deserve own type
- Ability to set the digest of artifacts published with a custom publisher
  This way it is possible to iterate these artifacts and display their digest in release notes; like the published docker images

### Snippet from my `goreleaser.yaml`:
> I use the Pro version.

```yaml
# Build and push Docker images
# https://goreleaser.com/customization/docker/
dockers:
  - ids: [ default ]
    image_templates:
      - "{{ .Env.IMAGE_REPO }}:v{{ .Version }}"
      - "{{ .Env.IMAGE_REPO }}:latest"
    templated_dockerfile: ../../Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.description=Ondo GM {{ .Var.GMService }} Service"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{ .Env.REPO_URL }}"
      - "--platform=linux/amd64"

archives:
  # The service binary will be archived into a tar.gz file.
  - id: default-archive
    formats: [ 'tar.gz' ]
    ids: [ default ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  # These two placeholder archives will be passed to oci-repository custom publisher
  # Which only runs against targets. The given names are OCI repo name plus latest/version tags
  - id: kube-manifests-latest-archive
    formats: [ 'binary' ]
    name_template: "{{ .Env.OCI_REPO }}:latest"
  - id: kube-manifests-version-archive
    formats: [ 'binary' ]
    name_template: "{{ .Env.OCI_REPO }}:v{{ .Version }}"

publishers:
  # Create and push two OCI artifacts from kube base and eks overlay
  - name: oci-repository
    ids: [ kube-manifests-latest-archive, kube-manifests-version-archive ]
    cmd: >-
      mise run kube_publish
        --service {{ .Var.GMService }}
        --version {{ .Version }}
        --oci {{ .ArtifactName }}
        --source {{ .Env.REPO_URL }}
        --revision {{ .Branch }}@sha1:{{ .FullCommit }}

# Todo (Nour): Include digest for kube manifests
release:
  ids: [ default-archive ]
  footer: |-
    ## Docker images
    {{- range .Artifacts }}
    {{- if eq .Type 10 }}
    * `{{ .Name }}@{{ .Extra.Digest }}`
    {{- end }}
    {{- end }}

    ## Kube manifests
    * `{{ .Env.OCI_REPO }}:v{{ .Version }}`
    * `{{ .Env.OCI_REPO }}:latest`

```

**Comment by caarlos0** [comment]
Hey!

I don't think there's a specific reason why custom publishers runs at the time it does (need to confirm), but could probably put it more towards the end - which I think is what most people expect anyway. 

If not, could also have a `after: docker` thing and call the it multiple times 🤔

**Reply by nourspace** [reply]
I'm happy with either solutions 🙏

**Reply by nourspace** [reply]
Any thoughts on capturing outputs/digests from custom publishers to be used in release notes?

**Reply by caarlos0** [reply]
Might be interesting to explore, will think about it. 🙏🏻

**Reply by caarlos0** [reply, marked as answer]
custom publishers now run last: 4d9c105228d346021514e25cf51336440de79850

**Reply by caarlos0** [reply]
also pushed the custom output stuff, on pro, though. 

if you don't have a license, hit me up at carlos at becker dot software

**Reply by nourspace** [reply]
I got two 😂 
One for myself, I think it is ending, and another one I made them buy at our company for the entire team.

**Reply by nourspace** [reply]
Is there a new version? I still see the 2.10.2 from two weeks ago.

**Reply by nourspace** [reply]
> custom publishers now run last: [4d9c105](https://github.com/goreleaser/goreleaser/commit/4d9c105228d346021514e25cf51336440de79850)

Checking the order, I see you even have a comment to make the release one of the last. If it is to me, I would have it the very last one. This way whatever happens in the other publisher, including custom ones, can be used to create the release notes.

```
			// This should be one of the last stepsMore actions
			release.Pipe{},
```

**Comment by nourspace** [comment]
another thing to note, is there a reason why custom publisher command can only be a single line?

```yaml
publishers:
  - name: test-multi
    cmd: |-
      echo one
      echo two
      echo three
```

The above results in sending `echo one echo two echo three`
