### DISCUSSION TITLE
S3 upload doesn't happen because build generates a "Binary" type artifact

### DISCUSSION THREAD

**Discussion by anr** [goreleaser/goreleaser#5856] [Q&A] [answered]
Hello,

After some debugging I found out that `gorelease build` is generating an artifact with type "Binary", which is not included in the filter here:

https://github.com/goreleaser/goreleaser/blob/main/internal/pipe/blob/upload.go#L155

Types "Binary" and "UploadableBinary" have the same string representation, but are different. If I add the "Binary" type to the filter my upload works.

Is it working as intended? If so, how could I change the build config to generate an "UploadableBinary"?

I used version 2.10.2, and my config looks like:

```yaml
version: 2

before:
  hooks:
    - go mod download
  
builds:
  - env:
      - CGO_ENABLED=0
      ...
    goos:
      - linux
    goarch:
       - amd64

blobs:
  - provider: s3
    bucket: arts
    endpoint: https://s3....     
```

Thanks
