### ISSUE TITLE
Global envs doesn't works on builds PRE and POST hooks

### ISSUE THREAD

**Issue by moisespsena** [goreleaser/goreleaser#1004]
The hooks doesn't receive global envs. Similar to #940

```yaml
builds:
  - hooks:
      pre: pre-script.sh
      post: post-script.sh
```

**Comment by caarlos0** [comment]
I did the following:

```yaml
# goreleaser.yaml
env:
  - SOMEENV=somedir
before:
  hooks:
    - sh ./foo.sh
```

```sh
#!/bin/sh
# foo.sh
mkdir $SOMEENV
```

and ran goreleaser, the dir `somedir` was created... 

what exactly didn't work for you?
