### ISSUE TITLE
Docker image publishing is always disabled

### ISSUE THREAD

**Issue by prvst** [goreleaser/goreleaser#1023]
**Describe the bug**

I'm following the example described on the Customization page, everything works fine and my Docker image is built correctly, but I always get the error message saying `pipe skipped              error=publishing is disabled` 

**To Reproduce**

I'm just running goreleaser on a repo with a .goreleaser.yml file

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: philosopher

before:
  hooks:
    #- ginkgo -r

builds:
- env:
  - CGO_ENABLED=0

  ldflags:
    - -w -s -X main.Version=${VERSION} -X main.Build=${BUILD}

  goos:
    - freebsd
    - windows
    - linux
    - darwin

  goarch:
    - amd64
    - arm64

  goarm:
    - 6
    - 7

archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    amd64: x86_64

  format: zip

  files:
    - License
    - README.md
    - Changelog

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

#sign:
#  artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
-
  #id: "default"

  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  builds:

  replacements:
    amd64: 64-bit
    darwin: macOS

  bindir: "/usr/local/bin"

  formats:
    - deb
    - rpm

release:

  github:

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - philosopher
    image_templates:
    - "prvst/philosopher:latest"
    - "prvst/philosopher:{{ .Version }}"
    
    dockerfile: Dockerfile

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Defaults to false.
    skip_push: false
```

**Expected behavior**

a Docker image built and deployed

**Environment (please complete the following information):**

- OS: Linux Mint
- OS version: 4.15.0-50-generic
- GoReleaser Version dev, commit none, built at unknown

**Additional context**
