### ISSUE TITLE
GOARCH=arm GOARM=6 produces `armel` instead of `armhf`

### ISSUE THREAD

**Issue by troian** [goreleaser/goreleaser#1026]
RPI B+ Rev 1.2 is `ARMv6` and uses `armhf` debian base.
goreleaser meanwhile builds `armel` deb|rpm

```
builds:
- main: ./cmd/<cmd>
  binary: <bin>
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - 6
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  formats:
  - deb
  - rpm
```
