### ISSUE TITLE
Snapcraft command has a space character at the end

### ISSUE THREAD

**Issue by tobias-kuendig** [goreleaser/goreleaser#1034]
When I build a snap without args...

```yaml

snapcraft:
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name: myapp
    publish: true
    summary: X
    description: X
    grade: devel
    confinement: strict
    license: MIT
    base: core18
    apps:
        myapp:
            daemon: simple
            plugs: ["network", "network-bind"]
```

...the resulting snap.yaml is...

```yaml
name: myapp
version: v0.0.0-next
summary: X
description: X
base: core18
license: MIT
grade: devel
confinement: strict
architectures:
- amd64
apps:
  myapp:
    command: 'myapp '
    plugs:
    - network
    - network-bind
    daemon: simple
```

Note the `command` line contains a space at the end.

I guess this line needs a TrimSpace?

https://github.com/goreleaser/goreleaser/blob/d355350f63315c1ef4bda13e9682c96783ebd5b2/internal/pipe/snapcraft/snapcraft.go#L208

0.107.0, commit ec13cb32489f2edebd1b093c43d67e676bd73616, built at 2019-05-25T21:20:21Z
