### ISSUE TITLE
Environment variables not replaced in brew install block

### ISSUE THREAD

**Issue by ericofusco** [goreleaser/goreleaser#1044]
**Describe the bug**

When custom environment variables are created, they're not replaced in brew install block.

**To Reproduce**

```yaml
env:
  - MY_VARIABLE="Hello World"

brew:
  github:
    owner: ericofusco
    name: my_repo
  homepage: "https://github.com/ericofusco/my_repo"

  install: |
      bin.install "my_binary"
      system "echo {{.Env.MY_VARIABLE}}"
```

Formula doesn't replace with my environment variables.

```rb
def install
    bin.install "my_binary"
    system "echo {{.Env.MY_VARIABLE}}"
end
```

**Expected behavior**

Formula generated with environment variables configured.

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin C02W309THV2V 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- GoReleaser Version 
version: 0.109.0
commit: 7ee486fc9b58171e70eec99ecdbeac4c99cc82d0
built at: 2019-06-09T15:24:06Z
built by: goreleaser

**Additional context**

**Comment by rogchap** [comment]
I ran into a similar problem when creating the test script:

```yaml
brew:
  test: |
    system "#{bin}/{{ .ProjectName }} version"
```
