### ISSUE TITLE
Generated tap formula is invalid when download strategy is used

### ISSUE THREAD

**Issue by rafaelmagu** [goreleaser/goreleaser#1047]
**Describe the bug**

When using `download_strategy` with the `brews` output, if a project is built for multiple OS targets the formula generated by GoReleaser is invalid:

```ruby
# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Tool < Formula
  desc "A CLI utility"
  homepage "https://github.com/company/tool"
  version "1.5.6"

  if OS.mac?
    url "https://bucket.s3-us-west-2.amazonaws.com/brew/tool/v1.5.6/tool_1.5.6_darwin_amd64.tar.gz"
    sha256 "10529fca770152cb1e614d2195432dcc5519ff1367fe809235402d4d2fdfa07f"
  elsif OS.linux?
    url "https://bucket.s3-us-west-2.amazonaws.com/brew/tool/v1.5.6/tool_1.5.6_linux_amd64.tar.gz"
    sha256 "724f5fcb04700c42de0e833d3909de60822e6d69911e2d912b6db0b6a0058ade"
  end, :using => S3DownloadStrategy # <- this is invalid Ruby

  def install
    bin.install "tool"
  end

  test do
    system "#{bin}/tool version"
  end
end
```

**To Reproduce**

1. Add the following configuration to `.goreleaser.yml`:
```yaml
brews:
  - name: tool
    url_template: "https://bucket.s3-us-west-2.amazonaws.com/brew/tool/{{.Tag}}/{{.ArtifactName}}"
    github:
      owner: company
      name:  tap
    folder: Formula
    download_strategy: S3DownloadStrategy
    custom_require: "../custom_download_strategy"
    homepage: https://github.com/company/tool
    description: A CLI utility
    test: |
      system "#{bin}/tool version"
```
2. Run `goreleaser release`
3. Install formula:
```
$ brew install tool
Error: tool: /usr/local/Homebrew/Library/Taps/company/homebrew-tap/Formula/tool.rb:14: syntax error, unexpected ',', expecting keyword_end
  end, :using => S3DownloadStrategy
```

**Expected behavior**

I expected `brew install tool` to install `tool`.

**Environment (please complete the following information):**

- OS: macOS Mojave
- OS version: 10.14.5
- GoReleaser Version dev (forked from master)
