### ISSUE TITLE
No error if a single dockers step fails

### ISSUE THREAD

**Issue by zegl** [goreleaser/goreleaser#1053]
**Describe the bug**

There is no error message from goreleaser if one of many docker files fails to build.

Goreleaser succeeds and exists with code 0, even if a step could not be built.

```
   • DOCKER IMAGES
      • building docker image     image=foo:true
      • building docker image     image=foo:false
      • pipe skipped              error=publishing is disabled
```

**To Reproduce**

```yaml
project_name: foo

dockers:
- goos: linux
  goarch: amd64
  binaries:
  - foo
  image_templates:
  - "foo:true"
  dockerfile: true.Dockerfile

- goos: linux
  goarch: amd64
  binaries:
  - foo
  image_templates:
  - "foo:false"
  dockerfile: false.Dockerfile
```

```
~/s/goreleaser-bug (master) cat false.Dockerfile
FROM alpine
RUN false
~/s/goreleaser-bug (master) cat true.Dockerfile
FROM alpine
RUN true
```

**Expected behavior**

If there's only one docker step, and that single step fails, goreleaser gives the following error. I expect the same error message to be printed if one image fails to build, and one succeeds.

```
   • DOCKER IMAGES
      • building docker image     image=foo:false
   ⨯ release failed after 4.16s error=failed to build docker image:
Sending build context to Docker daemon  1.414MB
Step 1/2 : FROM alpine
 ---> cdf98d1859c1
Step 2/2 : RUN false
 ---> Running in 25842c04d65a
The command '/bin/sh -c false' returned a non-zero code: 1
: exit status 1
```

**Environment (please complete the following information):**

- OS: macOS
- OS version: N/A
- GoReleaser Version [goreleaser --version]: 0.110.0
