### ISSUE TITLE
Templating in binary field of build

### ISSUE THREAD

**Issue by kristofferahl** [goreleaser/goreleaser#1059]
**Describe the bug**

Not sure if this is really a bug or simply a change in behavior between versions. However, in version 0.85.1 you were able to use templating for binary names.

Given the following yaml:
```yaml
builds:
- binary: "{{ .ProjectName }}_{{ .Tag }}"
```

In version 0.85.1, the binary ended up in the following path:
```
dist/darwin_386/terraform-provider-healthchecksio_v1.3.0
```

In version 0.110.0, the binary ends up in a path suggesting templating is no longer supported or broken:
```
dist/{{ .ProjectName }}_{{ .Tag }}_darwin_386/terraform-provider-healthchecksio_v1.3.0
```

I would prefer to keep the old style. Is there a way to configure the final dist path (including the directory name and binary name) in v 0.110.0 and above?

**To Reproduce**

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
- binary: "{{ .ProjectName }}_{{ .Tag }}"
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^examples:'
    - '^docs:'
    - '^test:'
```

**Expected behavior**

I expect the binary field to support templating as it did in version 0.85.1 or other option to replicate the old behavior. 

**Environment (please complete the following information):**

- OS: mac
- OS version: darwin
- GoReleaser Version: 0.110.0

**Comment by caarlos0** [comment]
OK, workaround: 

```yaml
builds:
- id: my-build-id 
  binary: "{{ .ProjectName }}_{{ .Tag }}"
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
```


thanks for reporting!
