### ISSUE TITLE
BLOB object key contains local dist path

### ISSUE THREAD

**Issue by kei2100** [goreleaser/goreleaser#1081]
**Describe the bug**
I tried to use [BLOB pipe](https://goreleaser.com/blob/) to deploy artifacts instead of the deprecated [S3](https://goreleaser.com/deprecations/#s3), but that blob object key contains local `dist` path.

This previous `S3` config outputs following artifacts.
```yml
# .goreleaser.yml
s3:
- bucket: my-bucket
  region: ap-northeast-1
  folder: releases/{{.Tag}}

dist: .dist
archives:
- id: default
  format: binary
```

```
s3://my-bucket/releases/v0.0.1/my-binary_0.0.1_linux_amd64
```

This `BLOB` config outputs following artifacts.

```yml
# .goreleaser.yml
blob:
- provider: s3
  bucket: my-bucket
  folder: releases/{{.Tag}}

dist: .dist
archives:
- id: default
  format: binary
```

```
s3://my-bucket/releases/v0.0.1/dist/my-binary_linux_amd64/my-binary
```

**To Reproduce**

```yaml
project_name: my-project
builds:
- main: ./main.go
  binary: my-binary
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 7
dist: .dist
archives:
- id: default
  format: binary
checksum:
  name_template: 'checksums-my-binary.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .FullCommit }}"
blob:
- provider: s3
  bucket: my-bucket
  folder: releases/{{.Tag}}
# s3:
# - bucket: my-bucket
#   region: ap-northeast-1
#   folder: releases/{{.Tag}}
```

Run `goreleaser`, output following artifacts.

```
s3://my-bucket/releases/v0.0.1/dist/my-binary_linux_amd64/my-binary
```

**Expected behavior**

Output following artifacts.

```
s3://my-bucket/releases/v0.0.1/my-binary_0.0.1_linux_amd64
```

I think this will be fixed by this commit https://github.com/kei2100/goreleaser/commit/0f4c2ad9a0371d5f6d85b2ecb1f34406f8b02b4c

**Environment (please complete the following information):**

- OS: macOS
- OS version: 10.14.4
- GoReleaser Version: 0.112.2
