### ISSUE TITLE
support multiple signing actions

### ISSUE THREAD

**Issue by joemiller** [goreleaser/goreleaser#1087]
related to https://github.com/goreleaser/goreleaser/issues/835 ..

I see that macOS code-signing could likely be implemented via something like:

```yaml
sign:
  cmd: codesign
  args: ['-s', 'Developer ID Application: FOO BAR (BAZ)', '${artifact}']
```

It would be great if one could execute both GPG signing and macOS code-signing. eg:
- gpg sign the checksum file
- custom sign an arbitrary binary ID, eg: codesign the macOS binary

Most of the other stages of the release pipeline have been extended to allow multiple instances, could this also be added to the `sign` stage?

**Comment by caarlos0** [comment]
seems like a good addition indeed, thanks for the suggestion!

**Comment by joemiller** [comment]
I think I found another way to have both GPG + macOS codesigning using per-build post hooks, eg:

```
  - binary: foo
    id: macos
...
    hooks:
      post: codesign -s 'developer identity here' ./dist/macos_darwin_amd64/foo
```

Still I think it's a good idea to consider supporting multiple `sign` steps though. Logically I think of `codesign` as a similar step as GPG signing the artifacts. And other platforms could have their own code signing steps here.
