### ISSUE TITLE
error=found 2 items with the ID

### ISSUE THREAD

**Issue by hhrutter** [goreleaser/goreleaser#1090]
goreleaser --snapshot --skip-publish --rm-dist

returns this error, I have no idea what this means:

releasing using goreleaser 0.113.0...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
   • LOADING ENVIRONMENT VARIABLES
      • pipe skipped              error=publishing is disabled
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.2.1, commit 5a9514239fe29bae57debc6a4775fe289f946f36
      • pipe skipped              error=disabled during snapshot mode
   • PARSING TAG
   • SETTING DEFAULTS
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING
      • GITHUB/GITLAB RELEASES
      • PROJECT NAME
      • BUILDING BINARIES
   ⨯ release failed after 0.05s error=found 2 items with the ID 'pdfcpu', please fix your config

```yaml
before:
  hooks:
builds:
- main: ./cmd/pdfcpu/main.go
- env:
  - CGO_ENABLED=0
dist: ./dist
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

**Expected behavior**
Snapshot creation

Env:
- OS: mac
- OS version: 18.6.0 Darwin Kernel Version 18.6.0
- GoReleaser Version: 0.113.0

The problem seems to be my custom main path.

**Comment by caarlos0** [comment]
you have 2 builds:

```yaml
builds:
- main: ./cmd/pdfcpu/main.go
- env:
  - CGO_ENABLED=0
```

builds have an `id` field, so you can archive specific build results... they have a default mechanism, which in your case gave both the same ID: `pdfcpu`

anyway, your config seems to have a typo, should probably be:

```yaml
builds:
- main: ./cmd/pdfcpu/main.go
  env:
  - CGO_ENABLED=0
```

**Comment by hhrutter** [comment]
Thanks for the quick response!

With that fix I get further, but now I get a strange compile error.
Regardless which goos/goarch combination I am choosing I am always getting smth like:

...
• BUILDING BINARIES
      • building                  binary=dist/pdfcpu_windows_amd64/pdfcpu.exe
      • building                  binary=dist/pdfcpu_linux_386/pdfcpu
      • building                  binary=dist/pdfcpu_linux_amd64/pdfcpu
      • building                  binary=dist/pdfcpu_darwin_386/pdfcpu
      • building                  binary=dist/pdfcpu_darwin_amd64/pdfcpu
      • building                  binary=dist/pdfcpu_windows_386/pdfcpu.exe
   ⨯ release failed after 0.67s error=failed to build for windows_amd64: # command-line-arguments
cmd/pdfcpu/main.go:36:33: undefined: CommandMap
cmd/pdfcpu/main.go:80:18: undefined: NewCommandMap
cmd/pdfcpu/main.go:81:31: undefined: Command
cmd/pdfcpu/main.go:90:23: undefined: NewCommandMap
cmd/pdfcpu/main.go:91:31: undefined: Command
cmd/pdfcpu/main.go:98:17: undefined: NewCommandMap
cmd/pdfcpu/main.go:99:31: undefined: Command
cmd/pdfcpu/main.go:106:11: undefined: NewCommandMap
cmd/pdfcpu/main.go:108:31: undefined: Command
cmd/pdfcpu/main.go:195:22: undefined: Command
cmd/pdfcpu/main.go:108:31: too many errors

Do you have an idea what's going on here?
I am not aware of any compile errors in my project.

I don't think .goreleaser.yaml is the issue but here it is:
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
- main: ./cmd/pdfcpu/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
dist: ./dist
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

**Comment by hhrutter** [comment]
Never mind I got it working:
main: ./cmd/pdfcpu

**Comment by johanbrandhorst** [comment]
FYI I was also seeing this error with a completely legitimate configuration (that used to work):
```
builds:
  - main: ./protoc-gen-grpc-gateway/main.go
    binary: protoc-gen-grpc-gateway
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - main: ./protoc-gen-swagger/main.go
    binary: protoc-gen-swagger
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archive:
  name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format: binary
  replacements:
    amd64: x86_64
dist: _output
```

I expect this behavioral change will break more users than just me and @hhrutter.

**Comment by caarlos0** [comment]
yes the ID thing is required for multiple builds now... sorry about breaking it for you... but it was required to add other things in a more reliable way...

**Comment by till** [comment]
I installed `goreleaser` today, generated a config (`goreleaser init`) and started building — 🎉 

---

Just got home, ran `goreleaser --snapshot --rm-dist` again, and I keep getting the error this ticket is about.

My config is pretty stock:

```
project_name: foo

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- files:
  - none*
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

**Comment by caarlos0** [comment]
the problem is in your config:

```
archives:
- files:
  - none*
- replacements: ## HERE
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
```

replacements and `- none*` are missing an indent, and replacements is not an list:

```yaml
project_name: foo

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- files:
    - none*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```
