### ISSUE TITLE
Failing to create/update release and publish artifacts on GitLab CE

### ISSUE THREAD

**Issue by dkorunic** [goreleaser/goreleaser#1091]
**Describe the bug**

On GitLab CE 10.5.6, goreleaser 0.113.0 is failing to create/update release and publish artifacts.

**To Reproduce**

`GITLAB_TOKEN='...' goreleaser release --rm-dist
`
Fails with:

```
      • GITHUB/GITLAB RELEASES
         • creating or updating release repo= tag=v0.3.2
   ⨯ release failed after 3.10s error=GitHub/GitLab Releases: failed to publish artifacts: GET https://company.url/api/v4/projects/dkorunic/sslcheck/releases/v0.3.2: 404 {error: 404 Not Found}
```

Likely cause is due to not using Project ID (https://docs.gitlab.com/ce/api/projects.html#get-single-project) but Namespace/Project_name instead. It should be possible to use GitLab v4 API to get Project ID out of project listing (https://docs.gitlab.com/ce/api/projects.html#list-all-projects) and prefer Project ID to make goreleaser work with older GitLab releases too.

```yaml
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
archive:
  replacements:
    linux: Linux
    darwin: Darwin
    windows: Windows
    freebsd: FreeBSD
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
gitlab_urls:
  api: https://company.url/api/v4/
  download: https://company.url
  skip_tls_verify: false
```

**Expected behavior**

Create tag/release (doesn't happen) on remote GitLab CE, upload artifacts/release.

**Environment (please complete the following information):**

- OS: [macOS]
- OS version: [10.14.6]
- GoReleaser Version [0.113.0]

**Additional context**

...
      • GITHUB/GITLAB RELEASES
         • creating or updating release repo= tag=v0.3.2
   ⨯ release failed after 3.10s error=GitHub/GitLab Releases: failed to publish artifacts: GET https://company.url/api/v4/projects/dkorunic/sslcheck/releases/v0.3.2: 404 {error: 404 Not Found}
