### ISSUE TITLE
config unmarshal error on []config.Blob

### ISSUE THREAD

**Issue by gnosthi** [goreleaser/goreleaser#1094]
**Describe the bug**

When trying to use the blob storage option in the .goreleaser.yml file an error is thrown stating the following

➜ goreleaser release

   • releasing using goreleaser 0.113.1...
   • loading config file       file=.goreleaser.yml
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 52: cannot unmarshal !!map into []config.Blob

**To Reproduce**

Download goreleaser release for commit : 7871c58ac2b054da7ef6e10b394346ddab3a6765
or install version 0.113.1 through brew. 

create .goreleaser.yml file with a blob: field.
run goreleaser release.

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - source .goreleaser_env
    # Start with a clean slate
    - make clean all
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  # Set up GO111MODULE variable
  - GO111MODULE=on
  # Disable CGO support
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
##nfpms:
#  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#  vendor: ""
#  maintainer: ""
#  description: Stand alone splunk query client.
#  license: ""
#  formats:
#    - deb
#    - rpm
 # suggests:
 #   - zsh
 # bindir: /usr/bin
 # overrides:
  #  rpm:
  #    replacements:
  #      amd64: x86_64
  #      name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
release:
  github:
  disable: true
blob:
   provider: azblob
   bucket: splunkclient
   folder: artifacts/"{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

**Expected behavior**

goreleaser creates the release and uploads the artifacts to blob storage.

**Environment (please complete the following information):**

- OS: Mac
- OS version: Darwin pepaul01551 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
- GoReleaser Version version: 0.113.1 commit: 7871c58ac2b054da7ef6e10b394346ddab3a6765 built at: 2019-08-01T11:37:16Z built by: goreleaser

**Additional context**
 goreleaser --debug release

   • releasing using goreleaser 0.113.1...
   • loading config file       file=.goreleaser.yml
   • loaded config file        config={ [] {  false true  } {  { }     []  []        []} [] {  { }     []} [{ [] [] [] [] []  [] []  { } [GO111MODULE=on CGO_ENABLED=0] [] []}] { []  map[386:i386 amd64:x86_64 darwin:Darwin linux:Linux windows:Windows]  []  []} [] {{  map[] [] [] [] [] [] map[] map[] {   }} map[]  [] []      } [] { map[] false  []        map[] map[]} [] {{{ .Tag }}-next} {checksums.txt } [] [] [] [] [] {{[^docs: ^test:]} asc false}  { []  } [{ []  checksum}] { } {[source .goreleaser_env make clean all go mod download go generate ./...]} { [] [] [] [] []  [] []  { } []  [] []} {   false} {  false}}
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 52: cannot unmarshal !!map into []config.Blob

**Comment by caarlos0** [comment]
`blob` is a list, so you need to change it to:

```yaml

blob:
- provider: azblob
   bucket: splunkclient
   folder: artifacts/"{{ .Version }}"
```

I'll rename this to `blobs` instead. Thanks for reporting it btw :)
