### ISSUE TITLE
Multiple brew formulas fail to upload to the same repository Github

### ISSUE THREAD

**Issue by rvolosatovs** [goreleaser/goreleaser#1120]
**Describe the bug**

When multiple brew builds are to be uploaded to the same Github repository, the 2nd upload always fails with:
```
   ⨯ release failed after 256.66s error=homebrew tap formula: failed to publish artifacts: PUT https://api.github.com/repos/rvolosatovs/homebrew-lorawan-stack/contents/ttn-lw-stack.rb: 409 is at db682719df1aa4f8e5e008d5fdb594abd1874714 but expected 7ce90d2d931b623e69b39ab43e0c3a88c973bac1 []
```
Only one of the formulas is uploaded and commited.

The issue happens, since by default `goreleaser` runs in parallel and hence there is a possible race condition, when multiple `brew` formulas are updated/created.
Assume: 
- there are 2 brew formulas to upload
- the original `HEAD` of the remote repository is `A`
- there are 2 goroutines each uploading a different formula to the same remote repository - R1 and R2 respectively
- R1 is the first goroutine to call github API and upload the new formula

Consider R1 successfully uploaded the updated formula and `HEAD` of the remote repository is changed to `B`.

At this point 
https://github.com/goreleaser/goreleaser/blob/0847b30afa7778f7647df29f452d896b60d91845/internal/client/github.go#L95 the SHA set here may be equal to either `A` or `B`, depending on when R2 called https://github.com/goreleaser/goreleaser/blob/0847b30afa7778f7647df29f452d896b60d91845/internal/client/github.go#L74
Apparently Github expects `SHA` to represent the SHA of `HEAD` and not the latest commit, in which the file was changed.

I see 2 solutions here:
1. (simplest) do not execute `brew` builds in parallel (confirmed by https://github.com/rvolosatovs/lorawan-stack/commit/e3409efd95d7dc2d65fdd2b9ed7e2e22b4bcebf7, which fixes the issue)
2. (possibly better) use a per-repository mutex in `githubClient` and only update 1 file per-repository at a time.

Not sure if the same issue is present in `gitlabClient` - it seems to me that it's free of it, but I'm not familiar with Gitlab API.

**To Reproduce**

(irrelevant outputs removed)
```yaml
project_name: lorawan-stack

changelog:
  skip: true

release:
  prerelease: auto

builds:
  - id: stack
    main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

  - id: cli
    main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: stack
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
      - stack
    files:
      - LICENSE
      - README.md
      - doc/**/*
      - docker-compose.yml
      - public/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: cli
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
    files:
      - LICENSE
      - README.md
      - doc/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: ttn-lw-stack
    ids:
      - stack
    github:
      owner: rvolosatovs
      name: homebrew-lorawan-stack
    commit_author:
      name: ttn-ci
      email: stack@thethingsnetwork.org
    homepage: https://www.thethingsnetwork.org
    description: The Things Stack for LoRaWAN
    conflicts:
      - ttn-lw-cli
    skip_upload: auto
    install: |
      bin.install "ttn-lw-cli"
      libexec.install %w[ttn-lw-stack public doc]
      env = {
          :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
      }
      (bin/"ttn-lw-stack").write_env_script libexec/"ttn-lw-stack", env

  - name: ttn-lw-cli
    ids:
      - cli
    github:
      owner: rvolosatovs
      name: homebrew-lorawan-stack
    commit_author:
      name: ttn-ci
      email: stack@thethingsnetwork.org
    homepage: https://www.thethingsnetwork.org
    description: CLI of The Things Stack for LoRaWAN
    conflicts:
      - ttn-lw-stack
    skip_upload: auto
    install: |
      bin.install "ttn-lw-cli"
      libexec.install doc
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

Both formulas uploaded successfully

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] linux (Travis CI)
- OS version: [uname -a] `4.15.0-1028-gcp`
- GoReleaser Version [goreleaser --version] `v0.116.0` versioned via go modules

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.

I'd be happy to contribute by implementing either the solution (1.), (2.) or something else?
