### ISSUE TITLE
Probably user error, but need help.

### ISSUE THREAD

**Issue by gnosthi** [goreleaser/goreleaser#1122]
**Describe the bug**

When running goreleaser release the following error is presented.

```
 ⨯ release failed after 3.60s error=found 5 builds with the ID 'myapp', please fix your config
```

Additionally when I run goreleaser check -f .goreleaser.yml
I get this error:  
`goreleaser: error: unexpected check, try --help`

**To Reproduce**

create a golang project, edit .goreleaser.yml, run goreleaser release

```yaml
before:
  hooks:
    - make clean all
    - go mod download
    - go generate ./...
    - golangci-lint run ./...
builds:
- id: "{{ .ProjectName }}-{{ .Version }}"
- ldflags:
  - -s -w -X main.versionNumber={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.author={{ .Env.Author }} -X main.copyright={{ .Env.CopyRight }}
- gcflags:
  - -trimpath={{ Env.GOPATH }}
- asmflags:
  - trimpath={{ Env.GOPATH }}
- flags:
  - -buildmod=pie
- env:
  # Set up GO111MODULE variable
  - GO111MODULE=on
  # Disable CGO support
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
  disable: true
blob:
  - provider: azblob
    bucket: myapp
    folder: artifacts/"{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

goreleaser should build the application with the specified options and upload the artifact to azure blob storage. 

**Environment (please complete the following information):**

- OS: Mac
- OS version: Darwin Kernel Version 16.7.0:
- GoReleaser Version 
```
version: 0.113.1
commit: 7871c58ac2b054da7ef6e10b394346ddab3a6765
built at: 2019-08-01T11:37:16Z
built by: goreleaser
```
- GitLab version: NONE

**Additional context**
I have done this using this same config on another project and it worked once but failed when trying to run it a second time with the same error as this project. 
The az buckets for the two projects are different buckets but the same storage account.
Not sure what's going on here. I tried searching for the error both in bugs and through google-fu and wasn't able to turn anything up. 
I'm sure I'm doing something incorrectly and it's probably a simple fix if you know what you're doing but I'm stuck and any help would be greatly appreciated. 

Thanks!

**Comment by gnosthi** [comment]
Updated to latest release and changed config to use blobs instead of blob. 
Still get the same error. 
Here is the debug output of the config 

```
 ➜ goreleaser --debug release

   • releasing using goreleaser 0.116.0...
   • loading config file       file=.goreleaser.yml
   • loaded config file        config={ [] {  false true  } {   { }     []  []        []} [] {  { }     []} [{{{ .ProjectName }}-{{ .Version }} [] [] [] [] []  [] []  { } []  [] []} { [] [] [] [] []  [-s -w -X main.versionNumber={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.author={{ .Env.Author }} -X main.copyright={{ .Env.CopyRight }}] []  { } []  [] []} { [] [] [] [] []  [] []  { } []  [] [-trimpath={{ Env.GOPATH }}]} { [] [] [] [] []  [] []  { } []  [trimpath={{ Env.GOPATH }}] []} { [] [] [] [] []  [] [-buildmod=pie]  { } []  [] []} { [] [] [] [] []  [] []  { } [GO111MODULE=on CGO_ENABLED=0]  [] []}] { []  map[386:i386 amd64:x86_64 darwin:Darwin linux:Linux windows:Windows]  []  []} [] {{  map[] [] [] [] [] [] map[] map[] {   }} map[]  [] []      } [] { map[] false  []        map[] map[]} [] {{{ .Tag }}-next} {checksums.txt } [] [] [] [] [] [{adaptiveauth azblob artifacts/"{{ .Version }}"  []}] {{[^docs: ^test:]} asc false}  { []  } [{ []  checksum}] { } {[make clean all go mod download go generate ./...]} { [] [] [] [] []  [] []  { } []  [] []} {   false} {  false}}
   • parallelism: 4           
   • RUNNING BEFORE HOOKS
      • running make clean all
      • -n >> CLEAN
-n >> BUILD, version = 0.1.0/db64aca0, output = aauth)
 [OK] 

      • running go mod download
      • warning: pattern "all" matched no module dependencies

      • running go generate ./...
      •                          
   • LOADING ENVIRONMENT VARIABLES
      • pipe skipped              error=release pipe is disabled
   • GETTING AND VALIDATING GIT STATE
      • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
      • git result                output=true

      • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
      • git result                output=true

      • running git               args=[-c log.showSignature=false show --format='%h' HEAD -q]
      • git result                output='db64aca'

      • running git               args=[-c log.showSignature=false show --format='%H' HEAD -q]
      • git result                output='db64aca0888687257500128f68edf9882a313248'

      • running git               args=[-c log.showSignature=false ls-remote --get-url]
      • git result                output=ssh://<redacted>:7999/serpm/myapp.git

      • running git               args=[-c log.showSignature=false describe --tags --abbrev=0]
      • git result                output=v0.1.1-r2

      • releasing v0.1.1-r2, commit db64aca0888687257500128f68edf9882a313248
      • running git               args=[-c log.showSignature=false status --porcelain]
      • git result                output=
      • running git               args=[-c log.showSignature=false describe --exact-match --tags --match v0.1.1-r2]
      • git result                output=v0.1.1-r2

   • PARSING TAG      
   • SETTING DEFAULTS 
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING      
      • GITHUB/GITLAB RELEASES
         • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
         • git result                output=true

         • running git               args=[-c log.showSignature=false config --get remote.origin.url]
         • git result                output=https://<redacted>/scm/serpm/myapp.git

         • pre-release for tag v0.1.1-r2 set to false
      • PROJECT NAME     
      • BUILDING BINARIES
   ⨯ release failed after 2.11s error=found 5 builds with the ID 'myapp', please fix your config
```

**Comment by caarlos0** [comment]
```yaml
builds:
- id: "{{ .ProjectName }}-{{ .Version }}"
- ldflags:
  - -s -w -X main.versionNumber={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.author={{ .Env.Author }} -X main.copyright={{ .Env.CopyRight }}
- gcflags:
  - -trimpath={{ Env.GOPATH }}
- asmflags:
  - trimpath={{ Env.GOPATH }}
- flags:
  - -buildmod=pie
- env:
  # Set up GO111MODULE variable
  - GO111MODULE=on
  # Disable CGO support
  - CGO_ENABLED=0
```

this should probably be 1 item:

```yaml
builds:
- id: "{{ .ProjectName }}-{{ .Version }}"
  ldflags:
  - -s -w -X main.versionNumber={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.author={{ .Env.Author }} -X main.copyright={{ .Env.CopyRight }}
  gcflags:
  - -trimpath={{ Env.GOPATH }}
  asmflags:
  - trimpath={{ Env.GOPATH }}
  flags:
  - -buildmod=pie
  env:
  # Set up GO111MODULE variable
  - GO111MODULE=on
  # Disable CGO support
  - CGO_ENABLED=0
```
