### ISSUE TITLE
error=homebrew tap formula: failed to publish artifacts: one tap can handle only 1 linux and 1 macos archive

### ISSUE THREAD

**Issue by gamelife1314** [goreleaser/goreleaser#1146]
**Describe the bug**

error=homebrew tap formula: failed to publish artifacts: one tap can handle only 1 linux and 1 macos archive

[travis build error information](https://travis-ci.org/bigfile/bigfile/builds/585422830)

**To Reproduce**

Nothing changes, it goes wrong suddenly.

> .goreleaser.yml

```yaml
project_name: bigfile

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  -
    id: bigfile
    main: ./artisan/bigfile.go
    binary: bigfile
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "bigfile/bigfile:latest"
        - "bigfile/bigfile:{{ .Tag }}"
        - "bigfile/bigfile:v{{ .Major }}"
      skip_push: false
      dockerfile: Dockerfile
      binaries:
        - bigfile
      build_flag_templates:
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=com.github.actions.description=a file transfer system that supports http, rpc and ftp protocols"
        - "--label=com.github.actions.icon=terminal"
        - "--label=com.github.actions.color=blue"
        - "--label=repository=https://github.com/bigfile/bigfile"
        - "--label=homepage=http://bigfile.site"
        - "--label=maintainer=bigfilefu <bigfilefu@gmail.com>"
brews:
  -
    github:
      owner: bigfile
      name: homebrew-tap
    folder: Formula
    homepage:  https://bigfile.site
    caveats: start mysql before starting bigfile
    description: A file transfer system that supports http, rpc and ftp protocols
    test: |
      system "#{bin}/bigfile -v"

scoop:
  bucket:
    owner: bigfile
    name: scoop-bucket
  homepage:  https://bigfile.site
  description: A file transfer system that supports http, rpc and ftp protocols
  license: MIT

nfpms:
  -
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://bigfile.site
    description: A file transfer system that supports http, rpc and ftp protocols
    maintainer: bigfilefu <bigfilefu@gmail.com>
    license: MIT
    vendor: Bigfile
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - rpm

snapcrafts:
  -
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: A file transfer system that supports http, rpc and ftp protocols
    description: |
      Bigfile can be used to transfer files by multiple protolcs, eg: http, rpc
      and ftp.
    grade: stable
#    grade: devel
    confinement: classic
    publish: true
    name: bigfile
    license: MIT
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: MacOS

release:
  prerelease: auto
```

> .travis.yml

```yml
dist: trusty
sudo: required

language: go

addons:
  apt:
    packages:
      - rpm
      - snapd

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+[-\.0-9a-zA-Z]*/

services:
  - mysql
  - docker

matrix:
  fast_finish: true
  include:
    - go: 1.12.x

env:
  global:
    - GO111MODULE=on
    - BIGFILE_DEFAULT_DB_USER=root
    - BIGFILE_DEFAULT_DB_PWD=
    - BIGFILE_MODE=dev
    - PATH=/snap/bin:$PATH

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
#  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/mgechev/revive
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/tools/cmd/goimports

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - sudo snap install snapcraft --classic

go_import_path: github.com/bigfile/bigfile

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bigfile;'
  - go run artisan/bigfile.go --db-pass=  migrate:refresh

script:
  - misspell -error ./
  - diff <(goimports -l .) <(printf "")
  - diff <(revive ./...) <(printf "")
#  - golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && docker login -u=bigfile -p="$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && openssl aes-256-cbc -K $encrypted_27812f9c1870_key -iv $encrypted_27812f9c1870_iv -in snap.login.enc -out snap.login -d
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:
  - provider: script
    skip_cleanup: true
    script:  bash .scripts/goreleaser.sh
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
      all_branches: true

```

**Comment by compleatang** [comment]
@gamelife1314 I'm getting the same error. How did you fix / why did you close?

**Comment by gamelife1314** [comment]
I solved this error by reading the source code. I found that there some errors in my `.goreleaser` config file. It should like this:

```
builds:
  -
    id: bigfile
    main: ./artisan/bigfile.go
    binary: bigfile
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6  // this should be commented, or you should create another `build` for homebrew
      - 7
```
