### ISSUE TITLE
.Os, .Arch, etc. not available

### ISSUE THREAD

**Issue by 1138-4EB** [goreleaser/goreleaser#1151]
I'm trying to use `{{.Os}}` or `{{.Arch}}` to define `binary` and/or `name_template`, but I get:

```
   ⨯ release failed after 0.21s error=failed to generate snapshot name: template: tmpl:1:11: executing "tmpl" at <.Arch>: map has no entry for key "Arch"
```

**To Reproduce**

```yaml
project_name: issue-runner

builds:
  - binary: issue-runner-{{.Os}}-{{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

snapshot:
  # Default is `SNAPSHOT-{{.ShortCommit}}`.
  name_template: SNAPSHOT-{{.Arch}}-{{.Commit}}
```

**Environment:**

- OS: Win10
- OS version: MINGW64_NT-10.0-18362 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
- GoReleaser Version version: 0.118.0 commit: 3120a38c640db05b7ca6e985dfd09fd609d68667 built at: 2019-09-14T20:18:49Z built by: goreleaser

**Additional context**

```sh
# goreleaser --snapshot --rm-dist

   • releasing using goreleaser 0.118.0...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
   • LOADING ENVIRONMENT VARIABLES
      • pipe skipped              error=publishing is disabled
   • GETTING AND VALIDATING GIT STATE
      • ignoring errors because this is a snapshot error=git doesn't contain any tags. Either add a tag or use --snapshot
      • releasing v0.0.0, commit 6f977c5647506dd6c3ef60664cdc919ecf5c3bc9
      • pipe skipped              error=disabled during snapshot mode
   • PARSING TAG
   • SETTING DEFAULTS
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING
      • GITHUB/GITLAB/GITEA RELEASES
      • PROJECT NAME
      • BUILDING BINARIES
      • ARCHIVES
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES
      • ARTIFACTORY
      • S3
      • BLOB
      • HOMEBREW TAP FORMULA
         • optimistically guessing `brew[0].installs`, double check
      • SCOOP MANIFEST
   • SNAPSHOTING
   ⨯ release failed after 0.21s error=failed to generate snapshot name: template: tmpl:1:11: executing "tmpl" at <.Arch>: map has no entry for key "Arch"
```
