### ISSUE TITLE
TravisCI builds utilizing goreleaser have started failing after recent nfpm change

### ISSUE THREAD

**Issue by zenmetsu** [goreleaser/goreleaser#1193]
**Describe the bug**

When attempting builds via TravisCI on repositories which previously built sucessfully, the following error is thrown:
```
$ go get github.com/goreleaser/goreleaser

# github.com/goreleaser/goreleaser/internal/pipe/nfpm

../../goreleaser/goreleaser/internal/pipe/nfpm/nfpm.go:176:24: cannot use info (type nfpm.Info) as type *nfpm.Info in argument to nfpm.Validate

../../goreleaser/goreleaser/internal/pipe/nfpm/nfpm.go:192:46: cannot use info (type nfpm.Info) as type *nfpm.Info in argument to nfpm.WithDefaults

The command "go get github.com/goreleaser/goreleaser" failed and exited with 2 during .
```

**To Reproduce**

.goreleaser.yml
```
builds:
  # List of builds
  - # First Build
    env:
    - CGO_ENABLED=0
    main: main.go
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - solaris
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      # TODO: add freebsd/arm support to gopsutil
      - goos: freebsd
        goarch: arm

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256-checksums.txt"

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- GoReleaser Version [goreleaser --version]
- GitLab version (if using a private hosted one)

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.
