### ISSUE TITLE
Error unmarshaling multiple archives

### ISSUE THREAD

**Issue by Miguel-Dorta** [goreleaser/goreleaser#1199]
**Describe the bug**

Goreleaser will not unmarshal multiple archives.

**To Reproduce**

```yaml
env:
  - GO111MODULE=on
builds:
  - id: generic
    main: cmd/web-msg-handler/main.go
    binary: web-msg-handler
    ldflags: -X github.com/Miguel-Dorta/web-msg-handler/internal.Version={{.Version}}
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64

  - id: linux
    main: cmd/web-msg-handler/main.go
    binary: web-msg-handler
    ldflags: -X github.com/Miguel-Dorta/web-msg-handler/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archive:
  - id: archiveGeneric
    builds:
      - generic
    format: zip
    replacements:
      amd64: x86-64
      darwin: macOS
    files:
      - examples/config.json
      - LICENSE
      - README.md

  - id: archiveLinux
    builds:
      - linux
    format: tar.gz
    files:
      - configs/systemd/web-msg-handler.service
      - examples/config.json
      - install.sh
      - LICENSE
      - README.md
```

**Expected behavior**

A successful unmarshal

**Environment (please complete the following information):**

- OS: Manjaro Linux
- OS version: Linux platon 5.3.6-1-MANJARO #1 SMP PREEMPT Sat Oct 12 09:30:05 UTC 2019 x86_64 GNU/Linux
- GoReleaser Version:
    version: 0.119.0
    commit: 39d07c375df531aa0c55df868d26f8dcc4bf37e1
    built at: 2019-10-07T01:47:00Z
    built by: goreleaser

**Additional context**
Following https://goreleaser.com/customization/#Archive
