### ISSUE TITLE
Building a dll in windows using c-shared buildmode generates a dll with .exe extension

### ISSUE THREAD

**Issue by qmuntal** [goreleaser/goreleaser#1221]
**Describe the bug**

When building a binary using `-buildmode=c-shared` in windows go generates a dll, not an executable, but goreleaser always add the extension `.exe` to all the binaries generated with goos=windows, at least this is what I can see in the [source code](https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/build/build.go#L131).

**To Reproduce**

```yaml
builds:
  - id: "testdll"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags: -buildmode=c-shared
    ldflags: -s -w
    main: .
    binary: test.dll
archives:
  - format: binary
    builds:
      - testdll
```

**Expected behavior**

I'm expecting a binary archive named `test.dll`, but I get a `test.dll.exe` archive.

**Environment (please complete the following information):**

- OS: windows
- OS version: windows 10 x64
- GoReleaser Version: 0.120.3
