### ISSUE TITLE
Edge case in DEB package version

### ISSUE THREAD

**Issue by wagoodman** [goreleaser/goreleaser#1236]
**Describe the bug**
It appears that when using github actions to create a snapshot release, the output deb has the incorrect version:
```
Get:1 /src/dist/dive_SNAPSHOT-4c07245_linux_amd64.deb dive amd64 SNAPSHOT-4c07245 [4742 kB]
debconf: delaying package configuration, since apt-utils is not installed
dpkg: error processing archive /src/dist/dive_SNAPSHOT-4c07245_linux_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'dive':
 error in 'Version' field string 'SNAPSHOT-4c07245': version number does not start with digit
Errors were encountered while processing:
 /src/dist/dive_SNAPSHOT-4c07245_linux_amd64.deb
```
Confirmed with dpkg:
```
dpkg -I dist/dive_*.deb
 new Debian package, version 2.0.
 size 4741720 bytes: control archive=349 bytes.
       1 bytes,     0 lines      conffiles            
     207 bytes,     9 lines      control              
      53 bytes,     1 lines      md5sums              
 Package: dive
 Version: SNAPSHOT-4c07245
 Section: 
 Priority: 
 Architecture: amd64
 Maintainer: Alex Goodman
 Installed-Size: 12044
 Homepage: https://github.com/wagoodman/dive/
 Description: no description given
```
It does not seem to matter if there is a git tag present.

**To Reproduce**

I have not been able to reproduce the behavior locally, however, in github actions it is reproducible. 

goreleaser:
```yaml
release:
  prerelease: true

builds:
  - binary: dive
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: MIT
    maintainer: Alex Goodman
    homepage: https://github.com/wagoodman/dive/
    formats:
      - rpm
      - deb

dockers:
  -
    binaries:
      - dive
    dockerfile: Dockerfile
    image_templates:
      - "wagoodman/dive:latest"
      - "wagoodman/dive:{{ .Tag }}"
      - "wagoodman/dive:v{{ .Major }}"
      - "wagoodman/dive:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--build-arg=ALPINE_VERSION={{.Env.ALPINE_VERSION}}"
      - "--build-arg=DOCKER_CLI_VERSION={{.Env.DOCKER_CLI_VERSION}}"
```

Here is the Makefile I'm using:
```
ci-install-go-tools:
	curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sudo sh -s -- -b /usr/local/bin/ latest
	curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sudo sh -s -- -b /usr/local/bin/ latest


ci-build-packages:
	ALPINE_VERSION=3.10 \
	DOCKER_CLI_VERSION=19.03.1 \
	goreleaser \
		--snapshot \
		--skip-publish \
		--rm-dist

make ci-test-deb-package-install:
	docker run \
		-v //var/run/docker.sock://var/run/docker.sock \
		-v /${PWD}://src \
		-w //src \
		ubuntu:latest \
			/bin/bash -c "\
			    apt update && \
				apt install ./dist/dive_*_linux_amd64.deb -y && \
				dive hello-world --ci \
			"
```

And the github action that fails:
```
name: 'app-pipeline'
on: [ push, pull_request ]
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'

    - uses: actions/checkout@v1
    
    - name: Install tools & OS dependencies
      run: |
        make ci-install-go-tools
   
    - name: Install go dependencies
      run: go get ./...
    
    - name: Build artifacts
      run: make ci-build-packages

    - name: Test DEB package installation
      run: make ci-test-deb-package-install

    - uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: dist
```

**Expected behavior**

Regardless of the version goreleaser uses, a valid deb version must be supplied.  That is `dpkg -I dist/dive_*.deb` should have listed a version that starts with a number.

**Environment (please complete the following information):**

- OS: ubuntu-latest in github actions
- GoReleaser Version:  0.120.8 for v0.120.8/Linux/x86_64

**Additional context**
The odd thing is that if use the makefile locally, it all works fine! It seems that the current conditions in github actions are what seems to matter. I've tried reproducing the git environment with no avail:
```
$ history
....
 2011  git init
 2012  git remote add origin git@github.com:wagoodman/dive.git
 2013  git config gc.auto 0
 2014  git config --get-all http.https://github.com/wagoodman/dive.extraheader
 2015  git config --get-all http.proxy
 2018  git fetch --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/*
 2022  git checkout --progress --force <git commit>
```

**Comment by wagoodman** [comment]
Though I've noticed that you have a github action that you've published... which seems to work fine!
```
    - name: Build artifacts
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALPINE_VERSION: "3.10"
        DOCKER_CLI_VERSION: "19.03.1"
```
This will do well for me, however, I'll leave the ticket open since there still is an underlying problem.

**Comment by wagoodman** [comment]
Looks like I spoke too soon... same problem occurred for a build without a tag with the published github actions:
```
+ apt install ./dist/dive_SNAPSHOT-4f330ed_linux_amd64.deb -y

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  dive
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4742 kB of archives.
After this operation, 12.3 MB of additional disk space will be used.
Get:1 /src/dist/dive_SNAPSHOT-4f330ed_linux_amd64.deb dive amd64 SNAPSHOT-4f330ed [4742 kB]
debconf: delaying package configuration, since apt-utils is not installed
dpkg: error processing archive /src/dist/dive_SNAPSHOT-4f330ed_linux_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'dive':
 error in 'Version' field string 'SNAPSHOT-4f330ed': version number does not start with digit
Errors were encountered while processing:
 /src/dist/dive_SNAPSHOT-4f330ed_linux_amd64.deb
```

Action:
```
   - name: Build artifacts
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
