### ISSUE TITLE
Name template not working for rpm metadata.

### ISSUE THREAD

**Issue by zbindenren** [goreleaser/goreleaser#1238]
**Describe the bug**

Yum uses the `Name` from the RPMs metadata to reference a package.

**To Reproduce**

With a name_template configuration like:
```yaml
...
nfpms:
  - formats:
      - rpm
    name_template: "{{.ProjectName}}-agent-{{.Version}}.el{{.Env.OS_VERSION}}.{{.Arch}}"
...
```
the following package filename  is correctly generated (when ProjectName is `mule`):

```
dist/mule-agent-1.4.6-102.el7.x86_64.rpm
```
But I cannot install this package with `yum` because in the metadata I have:
```
rpm -qip dist/mule-agent-1.4.6-102.el7.x86_64.rpm
Name        : mule
Version     : 1.4.6
Release     : 102
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 14951190
License     : Die Schweizerische Post - PostFinance
Signature   : (none)
Source RPM  : mule-1.4.6-102.src.rpm
```

Both Name and Souce RPM are the ProjectName i.e `mule`.

**Expected behavior**

Something like this would be great:
```
rpm -qip dist/mule-agent-1.4.6-102.el7.x86_64.rpm
Name        : mule-agent
Version     : 1.4.6
Release     : 102
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 14951190
License     : Die Schweizerische Post - PostFinance
Signature   : (none)
Source RPM  : mule-agent-1.4.6-102.src.rpm
```

I cannot create multiple rpms (for example `mule-server` and `mule-agent`) with goreleaser and install them with yum because both will have the same name in the metadata. Am I missing something?

The easiest solution would be  use the `id` as name if it is not `default`:
```yaml
nfpms:
    id: mule-agent
    name_template: "{{.ProjectName}}-agent-{{.Version}}.el{{.Env.OS_VERSION}}.{{.Arch}}"
...
```
What do you think?
