### ISSUE TITLE
Reference specific builds in dockers config

### ISSUE THREAD

**Issue by eversC** [goreleaser/goreleaser#1241]
**Is your feature request related to a problem? Please describe.**
When building docker images, if I have multiple builds defined, I have to give the builds unique binary names, otherwise I get the error:

```
release failed after 78.17s error=2 binaries match docker definition: [my-binary]: linux_amd64_, should be 1
```

**Describe the solution you'd like**
I'd like to be able to reference the Id of the `build` I want to use from within the `dockers` config, akin to how you can specify builds in `archives` config.

**Comment by caarlos0** [comment]
can you provide your config file?

**Comment by eversC** [comment]
```yaml
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - id: binary
    format: binary
    builds:
    - binary-build
  - id: zip
    format: zip
    builds:
    - lambda-build
    files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Version }}_lambda"
builds:
  - id: binary-build
    binary: cloud-key-rotator
    main: ./cmd/
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: lambda-build
    binary: cloud-key-rotator-lambda
    main: ./cmd/
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - cloud-key-rotator
    image_templates:
    - "ovotech/cloud-key-rotator:{{ .Tag }}"
    - "ovotech/cloud-key-rotator:v{{ .Major }}"
    - "ovotech/cloud-key-rotator:v{{ .Major }}.{{ .Minor }}"
    - "ovotech/cloud-key-rotator:latest"
```
