### ISSUE TITLE
Fail try to publish using azblob provider 'azureblob.OpenBucket: accountName is required'

### ISSUE THREAD

**Issue by avenda** [goreleaser/goreleaser#1260]
**Describe the bug**

While i try to made a release, i have the follow message:
```
$ goreleaser release --rm-dist
.
.
.
  • PUBLISHING       
      • S3               
         • pipe skipped              error=s3 section is not configured
      • BLOB             
   ⨯ release failed after 2.24s error=Blob: failed to publish artifacts: azureblob.OpenBucket: accountName is required
```

**To Reproduce**

```yaml
blobs:
  # You can have multiple blob configs
  -
    # Template for the cloud provider name
    # s3 for AWS S3 Storage
    # azblob for Azure Blob Storage
    # gs for Google Cloud Storage
    provider: azblob

    # Set a custom endpoint, useful if you're using a minio backend or
    # other s3-compatible backends.
    # Implies s3ForcePathStyle and requires provider to be `s3`
    #endpoint: 

    # Template for the bucket name
    bucket: AzureBlobContainerName

    # IDs of the artifacts you want to upload.
    ids:
    - IdFromBuild

    # Template for the path/name inside the bucket.
    # Default is `{{ .ProjectName }}/{{ .Tag }}`
    folder: "{{ .ProjectName }}/{{ .Tag }}"
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.
```
   • loading config file       file=.goreleaser.yml
   • checking config: 
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING      
      • GITHUB/GITLAB/GITEA RELEASES
      • PROJECT NAME     
      • BUILDING BINARIES
      • ARCHIVES         
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES    
      • ARTIFACTORY      
      • S3               
      • BLOB             
      • HOMEBREW TAP FORMULA
         • optimistically guessing `brew[0].installs`, double check
      • SCOOP MANIFEST   
   • config is valid 
```

**Expected behavior**

goreleaser should publish the artifact to blob using the specific provider.

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
- GoReleaser Version:
`
version: 0.122.0
commit: 173edbac545df7796ca2c4eb5ea3a1817920b562
built at: 2019-11-16T13:25:00Z
built by: goreleaser
`
