### ISSUE TITLE
post build hook with artifact templating context

### ISSUE THREAD

**Issue by fredbi** [goreleaser/goreleaser#1261]
**Is your feature request related to a problem? Please describe.**
I am running `upx` as a post build hook to compress binary artifacts.
At the moment, I need to script this and figure out what is the target to pass to upx.
Unfortunately, the build post hook cannot resolve templated attributes of the build artifcact context
(such as `{{ .Binary }}` and only knows about the global templating context).

**Describe the solution you'd like**
I'd like to be able to specify a post build hook directly like this, without having to create a script:
```yaml
builds:
  id: mytarget
  hooks:
   post: upx {{ .Binary }}
```

**Describe alternatives you've considered**
The current workaround I found is clumsy but works:
```yaml
builds:
  id: mytarget
  hooks:
   post: post.sh myTarget
```

`post.sh`:
```
#! /bin/bash
find dist -type f -name $1|xargs upx
```

**Additional context**
