### ISSUE TITLE
nfpms.files section completely ignore directories

### ISSUE THREAD

**Issue by toby3d** [goreleaser/goreleaser#1266]
## Description
The `files` configuration section basically ignores directory keys, no matter how they are indicated:

```yaml
files:
  "debian/usr/bin": "/usr/bin" # without slash on end
  "debian/usr/bin/": "/usr/bin" # slash for key only
  "debian/usr/bin": "/usr/bin/" # slash for value only
  "debian/usr/bin/": "/usr/bin/" # slash for both parts
```

As a result of this, I have to list all the files in the directory one-by-one:
```yaml
files:
  "debian/usr/bin/someload": "/usr/bin/someload"
  "debian/usr/bin/someinit": "/usr/bin/someinit"
  "debian/usr/bin/someclean": "/usr/bin/someclean"
```

The problem persists for any directories of any nesting level.

## Examples for reproduce
The project directory:
```
* github.com/toby3d/project
  * debian/
    * etc/
      * rsyslog.d/
        * ...
    * usr/
      * bin/
        * someclean
        * someload
        * someinit
      * share/
        ...
    * rules
    * control
    * rules
    * ...
  * .goreleaser.yaml
  * cmd/
    * api/
      * main.go
    * frontend/
      * main.go
  * ...
```

Example config:
```yaml
project_name: project
env:
- GO111MODULE=on
- CGO_ENABLED=0
builds:
- id: api
  main: ./cmd/api/
  binary: api
  goos:
  - linux
  goarch:
  - amd64
- id: frontend
  main: ./cmd/frontend/
  binary: frontend
  goos:
  - linux
  goarch:
  - amd64
nfpms:
- id: project
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  builds:
  - api
  - frontend
  bindir: /usr/bin
  formats:
  - deb
  dependencies: # doesn't matter
  files:
    "debian/etc/": "/etc"
    "debian/usr/bin/": "/usr/bin"
  config_files:
    "debian/etc/project/config.ini": "/etc/project/config.ini"
  scripts:
    preinstall: "debian/project.preinst"
    postinstall: "debian/project.postinst"
    preremove: "debian/project.prerm"
    postremove: "debian/project.postrm"
changelog:
  skip: true
```

## Checks
> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

```bash
• loading config file       file=.goreleaser.yml
• checking config: 
   • LOADING ENVIRONMENT VARIABLES
   • SNAPSHOTING      
   • GITHUB/GITLAB/GITEA RELEASES
   • PROJECT NAME     
   • BUILDING BINARIES
   • ARCHIVES         
   • LINUX PACKAGES WITH NFPM
   • SNAPCRAFT PACKAGES
   • CALCULATING CHECKSUMS
   • SIGNING ARTIFACTS
   • DOCKER IMAGES    
   • ARTIFACTORY      
   • S3               
   • BLOB             
   • HOMEBREW TAP FORMULA
      • optimistically guessing `brew[0].installs`, double check
   • SCOOP MANIFEST   
• config is valid  
```

## Expected behavior

The specified directory keys add all the files they contain to the package.

## Environment
- OS: linux
- OS version: `Linux toby3d-pc 5.3.12-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:55:53 UTC 2019 x86_64 GNU/Linux`
- GoReleaser Version:
  ```bash
  version: 0.123.1
  commit: 10862ff7601571dd983bfed63d06dd9fe4599aae
  built at: 2019-11-21T00:59:34Z
  built by: goreleaser
  ```
