### ISSUE TITLE
Full changelog is not uploaded to release page

### ISSUE THREAD

**Issue by amir20** [goreleaser/goreleaser#1284]
**Describe the bug**

When releasing with goreleaser, I see that the correct content `dist/CHANGELOG.md` but on the release page I only see the first line. I suspect this is a problem with my CI because I use github actions and there isn't an easy way for me to be able to debug this. I am hoping you can shed some light. 

**To Reproduce**

```yaml
before:
  hooks:
    - npm run clean
    - npm run build
    - packr -z
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - replacements:
      amd64: 64-bit
      386: 32-bit
      arm64: ARM_64-bit
      arm: ARM_32-bit
      linux: Linux
      darwin: Darwin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - "amir20/dozzle:{{ .Tag }}"
      - "amir20/dozzle:v{{ .Major }}.{{ .Minor }}"
      - amir20/dozzle:latest
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.build-date={{.Date}}"
      - "--label=org.label-schema.vcs-ref={{.ShortCommit}}"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name=Dozzle"
      - "--label=org.label-schema.url=https://dozzle.dev/"
      - "--label=org.label-schema.vcs-url=https://github.com/amir20/dozzle"
      - "--label=org.label-schema.description=Dozzle is a real-time log viewer for docker containers."

```

**Expected behavior**

When I run `goreleaser --rm-dist --debug --skip-validate --skip-publish` I get a changelog that looks like this: 

```
## Changelog

b41f315 1.20.6
376ee2d Adds compression

```

However, as seen [here](https://github.com/amir20/dozzle/releases/tag/v1.20.6) only the first line is displayed. 

**Additional context**
I am using Github actions to create the release.  Here is my [Dockerfile](https://github.com/amir20/dozzle/blob/master/.github/goreleaser/Dockerfile) that prepares the environment. 

Any help would be appreciated to get the right changelog.
