### ISSUE TITLE
Issue while archiving files not under the same folder

### ISSUE THREAD

**Issue by shriramsharma** [goreleaser/goreleaser#1285]
**Describe the bug**
The problem is that I need a file in the archive but that file is two levels up in a folder.
When I do something like this
```
archive:
  format: tar.gz
  files:
    - ../../script/test.sh
```
and run goreleaser, it works but the tar.gz is corrupted.
This is the error that I get when I try to untar the archive
```x ../../script/test.sh: Path contains '..'```

**To Reproduce**
Create a goreleaser yaml file similar to the following

```yaml
builds:
  - binary: someBinary
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - ../../test.sh
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  github:
    owner: shriramsharma
    name: someProject
```

**Expected behavior**
The tar file should be valid and should include the files even if the file path is relative to the goreleaser config file.

**Environment (please complete the following information):**

- OS: MAC
- OS version: Darwin m-c02x60b4jgh7 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64
- GoReleaser Version 0.87.0, commit 4206de324e2b0637ecdaa0779b5ac7154d4bc9bc, built at 2018-09-18T13:36:59Z
