### ISSUE TITLE
Fails to retrieve AWS credentials from env

### ISSUE THREAD

**Issue by jecoz** [goreleaser/goreleaser#1297]
**Describe the bug**
When the the time comes for uploading artifacts to `s3` using the `blob` customization, if the credentials are provided through env variables (set in the `env` section of the `.goreleaser` file), goreleaser fails to authenticate with error:
```
NoCredentialProviders: no valid providers in chain. Deprecated.
```

**To Reproduce**

```yaml
project_name: bpp
env:
  - GO111MODULE=on
  - AWS_ACCESS_KEY=<public key>
  - AWS_SECRET_KEY=<secret key>

before:
  hooks:
    - go get -u --insecure ./...
builds:
  -
    binary: bin/{{ .ProjectName }}
    main: ./cmd/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
blobs:
  -
    provider: s3
    bucket: <bucket>
    region: <region>
    folder: "{{ .ProjectName }}/{{ .Version }}"
release:
  disable: true

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "<my key>", "--output", "${signature}", "--detach-sign", "${artifact}"]
changelog:
  sort: asc
```

> Make sure your config file is valid by running: done
> `goreleaser check -f path-to-config-file`.

**Expected behavior**
I expect goreleaser to use the environment variables I set.

**Environment (please complete the following information):**

- OS: `mac`
- OS version: `Darwin jecoz.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`
- GoReleaser Version: `version: 0.124.1
commit: c63a57eaa05d79c619cfc9825e973006bb59bfc0
built at: 2020-01-08T12:55:18Z
built by: goreleaser`
- GitLab version: `GitLab Community Edition 12.6.2`

**Additional context**
If I run
```
env AWS_ACCESS_KEY=<public key> env AWS_SECRET_KEY=<secret key> goreleaser release
```
The process works indeed.
