### ISSUE TITLE
Goreleaser builds binarys not asked to build / gon example in docs does not work

### ISSUE THREAD

**Issue by roffe** [goreleaser/goreleaser#1301]
**Describe the bug**

Goreleaser insist on creating 386 binarys even though not told to do so also it produces double binarys with said invalid platforms

**To Reproduce**

try to use goreleaser

```yaml
env:
- GO111MODULE=on
- CGO_ENABLED=0
builds:
- binary: tjek
  id: tjek
  goos:
  - linux
  - windows
  goarch:
  - amd64
# notice that we need a separated build for the macos binary only:
- binary: tjek
  id: tjek-macos
  goos:
  - darwin
  goarch:
  - amd64
- ldflags:
  - -X github.com/roffe/tjek-cli/cmd.version={{ .Version }}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - signature: "./dist/${artifact}.dmg"
    ids:
    - tjek-macos # here we filter the macos only build id
    # you'll need to have gon on PATH
    cmd: gon
    # you can follow the gon docs to properly create the gon.hcl config file:
    # https://github.com/mitchellh/gon
    args:
    - .gon.hcl
    artifacts: all
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

*NOT* build 386 binarys, and *NOT* create tjek-cli only *tjek* as defined in the config

```
   • BUILDING BINARIES
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek_windows_amd64/tjek.exe
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek_linux_amd64/tjek
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek-macos_darwin_amd64/tjek
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek-cli_darwin_386/tjek-cli
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek-cli_darwin_amd64/tjek-cli
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek-cli_linux_386/tjek-cli
      • building                  binary=/Users/asdf/tjek-cli/dist/tjek-cli_linux_amd64/tjek-cli
```
the 386 binarys should never be build and why is it creating double binarys of everything? one named after the folder of the sourcecode and one named what i asked it to name it

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] osx
- OS version: [uname -a] Darwin Ratchbook.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
- GoReleaser Version [goreleaser --version] compiled from master today
- GitLab version (if using a private hosted one)

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.
