### ISSUE TITLE
ProjectName empty when releasing to gitlab

### ISSUE THREAD

**Issue by acobaugh** [goreleaser/goreleaser#1337]
**Describe the bug**

`.ProjectName` appears to be empty when releasing to gitlab. I'm trying to build a reusable CI pipeline, so I don't want to set the `project_name` setting in `.goreleaser.yml` if I can avoid it.

**To Reproduce**

```yaml
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    #- go mod tidy
builds:
- ldflags:
  - -X git.psu.edu/swe-golang/buildversion.commit={{.ShortCommit}}
  - -X git.psu.edu/swe-golang/buildversion.version={{.Version}}
  - -X git.psu.edu/swe-golang/buildversion.buildDate={{.Date}}
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - Merge pull request
    - Merge branch
gitlab_urls:
  api: https://git.psu.edu/api/v4/
  download: https://git.psu.edu
  skip_tls_verify: false
release:
  gitlab:
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

.ProjectName is set correctly.

**Environment (please complete the following information):**

- OS: linux
- OS version: golang:1.12-alpine
- GoReleaser Version v0.126.0
- GitLab: Community Edition 12.6.6

**Additional context**
This appears to be caused by https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/project/project.go#L16
