### ISSUE TITLE
Snapcraft bash completion support does not work if completer is in a subdirectory

### ISSUE THREAD

**Issue by twpayne** [goreleaser/goreleaser#1343]
**Describe the bug**

I use Goreleaser to release [chezmoi](https://github.com/twpayne/chezmoi), including building snaps. This has worked very well for several months. On 6 February 2020 tried to release a new version, but the snap was automatically rejected by the snap store with the message:

    chezmoi-completion.bash does not exist lint-snap-v2_completer (chezmoi)

The log from the release process is [here](https://github.com/twpayne/chezmoi/runs/430851329?check_suite_focus=true).

**To Reproduce**

The relevant lines from my `.goreleaser.yaml` file are:

```yaml
snapcrafts:
- builds:
  - chezmoi-cgo-snap
  - chezmoi-nocgo-snap
  summary: "Manage your dotfiles across multiple machines, securely."
  description: "Manage your dotfiles across multiple machines, securely."
  publish: true
  grade: stable
  confinement: classic
  apps:
    chezmoi:
      completer: completions/chezmoi-completion.bash
```

**Expected behavior**

I expected the snap to pass the snap linter and be accepted by the snap store.

**Environment (please complete the following information):**

- OS: Linux
- OS version: Ubuntu 18.04.3 LTS
- GoReleaser Version 0.126.0

**Additional context**

I suspect (but am not sure) that the this is due to commit is a4c91105, and specifically the call to `filepath.Base` at line 245 (new version) which strips the directory from the path to the completer script. This (I think) needs to be replaced with a function that maintains the relative path to the completer script.
