### ISSUE TITLE
Variables in archives.files not respected

### ISSUE THREAD

**Issue by ostrowr** [goreleaser/goreleaser#1347]
**Describe the bug**

I have three directories that look like

- `extras/linux/executable`
- `extras/windows/executable`
- `extras/darwin/executable`

and I'd like to include each executable in its respective archive; i.e.

```yaml
archives:
-
  files:
      - ./extras/{{.Os}}/executable
 ```

No errors are thrown, but the resulting archive does not contain the executable.

**To Reproduce**

Using

```yaml
archives:
-
  files:
      - ./extras/{{.Os}}/executable
 ```

doesn't work, while

```yaml
archives:
-
  files:
      - ./extras/darwin/executable
 ```

does.

**Expected behavior**

The {{.Os}} variable is passed through properly.

**Environment**

- OS: mac
- OS version: macos 10.15
- GoReleaser Version 0.126.0

**Additional context**
Oddly, if I do something like

```yaml
archives:
-
  files:
      - ./extras/{{.Os}}/executablethatdoesntexist
 ```

then I do get an error. So the globbing is happening but the files just aren't getting sent to the archive.
