### ISSUE TITLE
RFE: Make source archive a first-class release artifact?

### ISSUE THREAD

**Issue by tjanez** [goreleaser/goreleaser#1359]
**Is your feature request related to a problem? Please describe.**

We successfully use GoReleaser for [Oasis Core](https://github.com/oasislabs/oasis-core) and we would like to start signing our releases which would mean signing the checksum file of all release's artifacts. In addition to the produced binary artifacts, we would also like to sign the whole source code in the form of a source archive.

**Describe the solution you'd like**

Ideally, GoReleaser would support creating a source archive via SCM's tools, something like:
```bash
git archive {{.FullCommit}} | gzip > ./dist/{{.ProjectName}}-{{.Version}}.tar.gz
```
and treat is as other release artifacts, meaning it would be included in the generated checksum file and uploaded to GitHub/GitLab/... when creating a release.

**Describe alternatives you've considered**

I was motivated by the recent addition of [support for uploading of extra files to the release](https://github.com/goreleaser/goreleaser/pull/1333) and tried to use a combination of:

```yaml
builds:
  - id: oasis-node
    ... configuration trimmed ...
    hooks:
      post: ./scripts/make-source-archive.sh {{.FullCommit}} ./dist/oasis-core-{{.Version}}.tar.gz
```
and:

```yaml
release:
  name_template: "{{.ProjectName}} {{.Version}}"
  extra_files:
    - glob: ./dist/oasis-core-{{.Version}}.tar.gz
```
but that would not work for our use case since extra files are not included in the checksum file which we would sign.
