### ISSUE TITLE
Using `dir` option in `builds` ignores all other options

### ISSUE THREAD

**Issue by theganyo** [goreleaser/goreleaser#1362]
**Describe the bug**

If I add the "dir" option to a "build" section array element, it ignores all the other options that are specified therein and builds using defaults.

**To Reproduce**

I changed my build file from this:
```
builds:
  - main: ./apigee-istio/main.go
    binary: apigee-istio
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
```
To this:
```
builds:
  - dir: apigee-istio
    binary: apigee-istio
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
```
At which point it started building 386 archs and stopped building the windows dist. In addition, instead of building the files in `$root/dist`, it started building everything in `$root/apigee-istio/dist` and naming them `istio-mixer-adapter` instead of in the root and using the specified `apigee-istio`. 

Thus, it would appear that goreleaser seemed to simply change directories and try to execute itself in the new directory.

**Expected behavior**

I expected the `$root/dist` directory to still be created with the appropriate files in that directory.

**Environment (please complete the following information):**

- OS: mac
- OS version: 19.3.0
- GoReleaser Version: 0.127.0
