### ISSUE TITLE
goreleaser attempts to push to snap store when publish is set to false

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [goreleaser/goreleaser#1365]
**Describe the bug**

goreleaser attempts to push to snap store, even if `publish` is set to false in the snapcraft configuration

**To Reproduce**

```yaml
project_name: f1viewer
builds:
  - 
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
archives:
  -
    format: binary
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    files:
      - none*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
nfpms:
  -
    description: TUI client for F1TV
    license: GPL-3.0
    homepage: https://github.com/SoMuchForSubtlety/f1viewer/
    maintainer: SoMuchForSubtlety <s0muchfrsubtlety@gmail.com>
    replacements:
      darwin: macOS
    formats:
      - deb
      - rpm
    dependencies:
      - mpv
    recommends:
      - xclip
snapcrafts:
  -
    replacements:
      darwin: macOS
    publish: false
    summary: TUI client for F1TV
    description: |
      F1viewer is a terminal F1TV client that lets you watch F1 with mpv
      or any other player that supports HLS streams.
    grade: stable
    confinement: classic
    license: GPL-3.0
    base: core18
brews:
  -
    description: TUI client for F1TV
    homepage: https://github.com/SoMuchForSubtlety/f1viewer/
    folder: Formula
    github:
      owner: SoMuchForSubtlety
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    dependencies:
      - mpv
```

**Expected behavior**

Publishing to the snap store is skipped.

**Environment (please complete the following information):**

[executed in a GitHub action](https://github.com/SoMuchForSubtlety/f1viewer/blob/6f24dc0599344963d46d31ad69ff8175c7564d2d/.github/workflows/release.yml)

**Additional context**
```
[...]
       • SNAPCRAFT PACKAGES       
         • pushing snap              snap=f1viewer_1.0.0_linux_amd64.snap
         • pushing snap              snap=f1viewer_1.0.0_linux_386.snap
   ⨯ release failed after 77.27s error=Snapcraft Packages: failed to publish artifacts: failed to push dist/f1viewer_1.0.0_linux_386.snap package: Preparing to push 'f1viewer_1.0.0_linux_386.snap'.
After pushing, the resulting snap revision will be released to 'stable' when it passes the Snap Store review.
Install the review-tools from the Snap Store for enhanced checks before uploading this snap.
Pushing 'f1viewer_1.0.0_linux_386.snap' [================================] 100%
Received:
- macaroon-permission-required: Permission "channel" is required as a macaroon caveat.
##[error]The process '/home/runner/work/_temp/56153f7c-7f35-4ffe-8488-507790be17a4/goreleaser' failed with exit code 1
```
