### ISSUE TITLE
Using a private gitlab results in blank "{{ .ProjectName }}" 

### ISSUE THREAD

**Issue by pschulten** [goreleaser/goreleaser#1367]
Using a private gitlab the binary name in the archive is blank
```console
Archive:  dist/_0.0.12_darwin_amd64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  9450616  03-01-2020 16:32
---------                     -------
  9450616                     1 file
```

```yaml
# WORKAROUND (remove go reproduce)
release:
  github:
    name: now-i-have-a-name
# END WORKAROUND
gitlab_urls:
  api: https://git.example.com/api/v4/
  download: https://git.example.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
  - format: zip
    files:
      - none*
```
- OS: mac
- OS version: 19.3.0
- GoReleaser Version 
  ```
  version: 0.127.0
  commit: 33d39188fa74ff03bb134b092386c9525da6b53a
  built by: homebrew
  ```
- GitLab version 12.8.1 

**Additional context**
ref: Setting "wrap_in_directory: true" results in blank "{{ .ProjectName }}" #607
your fix uses the gitHUB name (see workaround)
