### ISSUE TITLE
cmd/go: unsupported GOOS/GOARCH pair freebsd/arm64

### ISSUE THREAD

**Issue by klauspost** [goreleaser/goreleaser#1385]
**Describe the bug**

After https://github.com/goreleaser/goreleaser/issues/1376 releases fail unless Go 1.14 is used.

I am seeing regression in speed for Go 1.14, so I want to stick with Go 1.13. It should be possible to guard #1376 with a Go version check.

**To Reproduce**

https://travis-ci.org/github/klauspost/compress/jobs/661040751

```yaml
before:
  hooks:
builds:
  -
    id: "s2c"
    binary: s2c
    main: ./s2/cmd/s2c/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - netbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips64
      - mips64le
    goarm:
      - 7
  -
    id: "s2d"
    binary: s2d
    main: ./s2/cmd/s2d/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - netbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips64
      - mips64le
    goarm:
      - 7

archives:
  -
    id: s2-binaries
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      freebsd: FreeBSD
      netbsd: NetBSD
    format_overrides:
      - goos: windows
        format: zip
    files:
      - s2/LICENSE
      - s2/README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  -
    vendor: Klaus Post
    homepage: https://github.com/klauspost/compress
    maintainer: Klaus Post <klauspost@gmail.com>
    description: S2 Compression Tool
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
    replacements:
      darwin: Darwin
      linux: Linux
      freebsd: FreeBSD
      amd64: x86_64
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

Builds and uploads.

**Environment (please complete the following information):**

- OS: linux
- OS version: xenial 4.15.0-1028-gcp
- GoReleaser Version  `releasing using goreleaser 0.128.0`

**Additional context**

Failed job: https://travis-ci.org/github/klauspost/compress/jobs/661040751
