### ISSUE TITLE
Snapshot build doesn't obey `name_template`

### ISSUE THREAD

**Issue by ChernikovP** [goreleaser/goreleaser#1388]
**Describe the bug**

Snapshot build doesn't obey `name_template` and use solely latest tag in its name

**To Reproduce**

- Run `goreleaser --snapshot --skip-publish --rm-dist`
- Given following `.gorelaeser.yml`

```yaml
project_name: terraform-provider-assert
builds:
  - binary: "{{ .ProjectName }}_{{ .Tag }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
checksum:
   name_template: "{{ .ProjectName }}_{{ .Tag }}_checksums.txt"
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      # A hack to package only binaries, as goreleaser will always add 
      # the README and LICENSE files to the archive.
      - none*
```
**Expected behavior**

`dist` folder to contain builds with `SNAPSHOT` and short commit in their names. Instead I got just the most recent tag . See output:

```
pchernikov$ goreleaser --snapshot --skip-publish --rm-dist

   • releasing using goreleaser 0.128.0...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
   • LOADING ENVIRONMENT VARIABLES
      • pipe skipped              error=publishing is disabled
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.1.0, commit d276f92fe683931c70934de99e4a84fd274a6693
      • pipe skipped              error=disabled during snapshot mode
   • PARSING TAG      
   • SETTING DEFAULTS 
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING      
      • GITHUB/GITLAB/GITEA RELEASES
      • PROJECT NAME     
      • BUILDING BINARIES
      • ARCHIVES         
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES    
      • ARTIFACTORY      
      • BLOB             
      • HOMEBREW TAP FORMULA
      • SCOOP MANIFEST   
   • SNAPSHOTING      
   • CHECKING ./DIST  
      • --rm-dist is set, cleaning it up
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG
      • pipe skipped              error=not available for snapshots
   • BUILDING BINARIES
      • building                  binary=<path_to_project>/terraform-provider-assert/dist/terraform-provider-assert_darwin_amd64/terraform-provider-assert_v0.1.0
      • building                  binary=<path_to_project>/terraform-provider-assert/dist/terraform-provider-assert_linux_amd64/terraform-provider-assert_v0.1.0
      • building                  binary=<path_to_project>/terraform-provider-assert/dist/terraform-provider-assert_windows_amd64/terraform-provider-assert_v0.1.0.exe
   • ARCHIVES         
      • creating                  archive=dist/terraform-provider-assert_v0.1.0_windows_amd64.zip
      • creating                  archive=dist/terraform-provider-assert_v0.1.0_darwin_amd64.tar.gz
      • creating                  archive=dist/terraform-provider-assert_v0.1.0_linux_amd64.tar.gz
   • LINUX PACKAGES WITH NFPM
   • SNAPCRAFT PACKAGES
   • CALCULATING CHECKSUMS
      • checksumming              file=terraform-provider-assert_v0.1.0_darwin_amd64.tar.gz
      • checksumming              file=terraform-provider-assert_v0.1.0_linux_amd64.tar.gz
      • checksumming              file=terraform-provider-assert_v0.1.0_windows_amd64.zip
   • SIGNING ARTIFACTS
      • pipe skipped              error=artifact signing is disabled
   • DOCKER IMAGES    
      • pipe skipped              error=docker section is not configured
   • PUBLISHING       
      • pipe skipped              error=publishing is disabled
   • release succeeded after 3.95s

```
**Environment (please complete the following information):**

- OS: `mac`
- OS version: `Darwin bos-pchernikov-mac.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64`
- GoReleaser Version `0.128.0`
