### ISSUE TITLE
Gorelease fails to create an archive when the builds > binary field contains a sub-folder

### ISSUE THREAD

**Issue by andrewkav** [goreleaser/goreleaser#1398]
**Describe the bug**
Goreleaser fails to create an archive when binary contains a sub folder in builds scetion.
```
 error=failed to create directory dist/test/test_1.3.0-test_Linux_x86_64.tar.gz: open dist/test/test_1.3.0-test_Linux_x86_64.tar.gz: no such file or directory
```

**To Reproduce**

```yaml
builds:
  - id: test
    dir: test
    binary: ./test/test
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: test
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - test
    replacements:
      linux: Linux
      amd64: x86_64

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

It should not fail and create a subfolder.

here is a potential fix for `create` function in `internal/pipe/archive/archive.go`
```
	if err := os.MkdirAll(filepath.Dir(archivePath), 0755|os.ModeDir); err != nil {
		return err
	}
```

**Environment (please complete the following information):**

- OS: Ubuntu
- OS version: 19.10
- GoReleaser Version [goreleaser --version]: latest from master
