### ISSUE TITLE
field dir not found in type config.Build

### ISSUE THREAD

**Issue by iverson-lu** [goreleaser/goreleaser#1403]
Thanks for anyone who can help.

Everything works fine until i moved the code to src folder. I tried to point the yml file to use dir as src but got the below error. I'm using azure pipeline with goreleaser installed on a linux agent.

   • releasing using goreleaser 0.119.0...
   • loading config file       file=.goreleaser.yml
   ⨯ release failed after 0.00s error=yaml: unmarshal errors:
  line 9: field dir not found in type config.Build

```yaml
project_name: myapp
before:
  hooks:
    - go mod download
builds:
  - 
    dir: src
    main: ./src/main.go
    env:
    - GO111MODULE=on
    - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
archives:
  -
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

**Additional context**
it works well actually without the dir but by doing that i will have to move everything back to the project root folder, which is the last thing i want to do.
