### ISSUE TITLE
Support Closing GitHub Milestone

### ISSUE THREAD

**Issue by bflad** [goreleaser/goreleaser#1415]
**Is your feature request related to a problem? Please describe.**

It would be great if we could automatically close an associated [GitHub milestone](https://help.github.com/en/github/managing-your-work-on-github/about-milestones) when releasing. Currently this is done manually. Our milestones are named matching the target release tag name, e.g. `v1.2.3`.

**Describe the solution you'd like**

New configuration to enable the handling of GitHub milestones, e.g.

```yaml
# .goreleaser.yml
milestones:
  # You can have multiple milestone configs
  -
    # Repo for the milestone.
    # Default is extracted from the origin remote URL.
    github:
      owner: user
      name: repo

    # Whether to close the milestone
    # Disable to skip performing the milestone action
    close: true

    # Handling for missing milestone when closing the milestone
    #   error: Prevent release if missing
    #   skip: Skip if missing
    #
    # Default: skip
    missing_on_close: error|skip

    # Name of milestone
    #
    # Default: {{ .Tag }}
    name: Current Release

    # Other potential settings after initial implementation

    # Handling for open issues when closing the milestone
    #   error: Prevent release if open issues in milestone
    #   leave: Leave open in milestone
    #   move: Move issues from this milestone to next
    #
    # Default: none
    open_issues_on_close: error|leave|move

    # Whether to open the milestone
    # Disable to skip the milestone action
    # Note: it can only be one: either close or open
    #
    # Default: false
    open: true

    # Name of next milestone
    next_name: Next Release
```

When added with `close: true`, this configuration triggers logic to find the GitHub milestone by name to fetch its ID, then close the milestone.

**Describe alternatives you've considered**

Externally running a script to wrap the goreleaser process or separate build step with its own script to handle this.

**Additional context**

The closing of the milestone triggers other automated behaviors in our repositories, such as commenting on all issues and pull requests associated with that milestone to let folks know the functionality or fix has been released and how to update. That additional functionality seems out of scope for this project. 😄 

Thank you for the consideration! I am willing to contribute if this would be approved.
