### ISSUE TITLE
cmd/go: unsupported GOOS/GOARCH pair .../...

### ISSUE THREAD

**Issue by pyed** [goreleaser/goreleaser#142]
consider the following `goreleaser.yml`

```yml
# goreleaser.yml
# Build customization
build:
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
    - 386
```

trying to releaser it will hit the following error
```cmd/go: unsupported GOOS/GOARCH pair windows/arm64```

isn't it supposed to skip unsupported pairs ?
