### ISSUE TITLE
Login to GitHub/GitLab Docker Registry automatically

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#1431]
Both GitHub and GitLab offer their own public Docker Registry:
https://github.com/features/packages
https://docs.gitlab.com/ee/user/packages/container_registry/

Gitea doesn't seem offer one [yet](https://github.com/go-gitea/gitea/issues/2316).

**Describe the solution you'd like**

It would be great if GoReleaser could just automatically authenticate with the given registry on hostname/image match if it already has all it needs for authentication (token), e.g.

```yml
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.pkg.github.com/org/repo/image-name:latest"
      - "docker.pkg.github.com/org/repo/image-name:{{ .Tag }}"
      - "docker.pkg.github.com/org/repo/image-name:v{{ .Major }}"
```
would automatically trigger logging into GitHub's Docker Registry if `GITHUB_TOKEN` is available - which is high chance, as uploading to GitHub's Registry from GitLab or Gitea seems like unlikely scenario.

**Describe alternatives you've considered**

Logging in as a separate GitHub Action step:

```yml
...
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
...
      -
        name: Login to Docker Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login docker.pkg.github.com -u docker --password-stdin
      -
        name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Additional context**
