### ISSUE TITLE
Snap packages with multiple apps use the wrong binaries

### ISSUE THREAD

**Issue by neoaggelos** [goreleaser/goreleaser#1448]
**Describe the bug**

When building snap packages with multiple builds, there is a bug where the application names are being overwritten.

Context: https://github.com/TheThingsNetwork/lorawan-stack/issues/2351

**To Reproduce**

Relevant part of the .goreleaser.yaml file below.

```yaml
builds:
  - id: stack
    main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
  - id: cli
    main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
snapcrafts:
  - id: stack
    builds:
      - cli
      - stack
    apps:
      ttn-lw-stack:
        plugs: [ home, network, network-bind ]
      ttn-lw-cli:
        plugs: [ home, network, network-bind ]
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

`ttn-lw-stack` should execute the binary `ttn-lw-stack`.
`ttn-lw-stack.ttn-lw-cli` should execute the binary `ttn-lw-cli`. 

**Environment (please complete the following information):**

- OS: ubuntu
- OS version: Linux matrix 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser Version: dev (running from latest master)
- GitLab version (if using a private hosted one)

**Additional context**

See https://github.com/TheThingsNetwork/lorawan-stack/issues/2351#issuecomment-614949533 

Tested with `v0.124.1` and the bug is not present, so I would assume that the bug was introduced with this commit: https://github.com/goreleaser/goreleaser/commit/eb528971b9da279084886d2dba5f47bbd6df8fdd
