### ISSUE TITLE
build post hook fails when using name template as argument

### ISSUE THREAD

**Issue by zam6ak** [goreleaser/goreleaser#1456]
version: 0.131.1
commit: dec22cf0c8a6464390ea26b42086d242e396ecda
built at: 2020-04-03T02:28:47Z
built by: goreleaser

When specifying build post hook with argument using name template I get and error: 

> release failed after 16.24s error=post hook failed: template: tmpl:1:18: executing "tmpl" at <.ArtifactName>: map has no entry for key "ArtifactName"

Relevant config part is:

```yaml
builds:
  -
    id: "tool_extended_windows"
    binary: tool
    main: ./cmd/tool/main.go
    ldflags:
      - -s -w -X tool.version={{.Version}} -X tool.commit={{.ShortCommit}} -X tool.date={{.Date}}
      - -H windowsgui
    flags:
      - -tags
      - extended
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      post: ./buildmsi.cmd {{ .ArtifactName }} 
```

running goreleaser check returns valid result
