### ISSUE TITLE
Docker section not finding binary

### ISSUE THREAD

**Issue by terrabitz** [goreleaser/goreleaser#1462]
**Describe the bug**

After the recent release of goreleaser v0.132.0, it seems that the `dockers` section can no longer find my templated binary name (though it can find it just fine in v0.131.1).

**To Reproduce**

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: gowebapptemplate

before:
  hooks:
    - go get
    - ./install-dep.sh
    - make build-ui
    - go mod tidy
    - docker login registry.gitlab.com -u terrabitz -p {{ .Env.GITLAB_TOKEN }}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    binary: "{{.ProjectName}}"
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
nfpms:
  -
    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Linux

    # Your app's vendor.
    # Default is empty.
    vendor: Hack_and_Sla.sh
    # Your app's homepage.
    # Default is empty.
    homepage: https://hackandsla.sh

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Trevor Taubitz <terrabitz@protonmail.com>

    # Your app's description.
    # Default is empty.
    description: A template for golang web apps

    # Your app's license.
    # Default is empty.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # empty_folders:
    #   - "/var/log/gowebapptemplate"

    # config_files:
    #   "etc/example-config.yaml": "/etc/gowebapptemplate/gowebapptemplate-config.yaml"

dockers:
  - # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    binaries:
      - "{{ .ProjectName }}"
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    image_templates:
      - "terrabitz/{{.ProjectName}}:{{ .Tag }}"
      - "terrabitz/{{.ProjectName}}:v{{ .Major }}"
      - "terrabitz/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "terrabitz/{{.ProjectName}}:latest"
      - "registry.gitlab.com/terrabitz/{{.ProjectName}}:{{ .Tag }}"
      - "registry.gitlab.com/terrabitz/{{.ProjectName}}:v{{ .Major }}"
      - "registry.gitlab.com/terrabitz/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "registry.gitlab.com/terrabitz/{{.ProjectName}}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.label-schema.build-date={{.Date}}" 
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.url='{{ .GitURL }}'" 
      - "--label=org.label-schema.vcs-ref={{ .ShortCommit }}"
      - "--label=org.label-schema.vcs-url='{{ .GitURL }}'" 
      - "--label=org.label-schema.vendor='hack_and_sla.sh'" 
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.schema-version=1.0"
      - "--build-arg=BIN={{ .ProjectName }}"

```

**Expected behavior**

Goreleaser should be able to find a binary by templated name.

**Environment (please complete the following information):**

- OS: Docker
- GoReleaser Version v0.132.0

**Additional context**

```none
   • releasing using goreleaser 0.132.0...
163    • loading config file       file=.goreleaser.yml
164    • running before hooks     
165       • running go get           
166       • running ./install-dep.sh 
167       • running make build-ui    
168       • running go mod tidy      
169       • running docker login registry.gitlab.com -u terrabitz -p {{ .Env.GITLAB_TOKEN }}
170    • loading environment variables
171    • getting and validating git state
172       • releasing v0.0.8, commit 088b32aeab024a8c6e91856d5b08967a08de667a
173    • parsing tag              
174    • setting defaults         
175       • snapshotting             
176       • github/gitlab/gitea releases
177       • project name             
178       • building binaries        
179       • creating source archive  
180       • archives                 
181       • linux packages           
182       • snapcraft packages       
183       • calculating checksums    
184       • signing artifacts        
185       • docker images            
186       • artifactory              
187       • blobs                    
188       • homebrew tap formula     
189       • scoop manifests          
190    • snapshotting             
191       • pipe skipped              error=not a snapshot
192    • checking ./dist          
193    • writing effective config file
194       • writing                   config=dist/config.yaml
195    • generating changelog     
196       • writing                   changelog=dist/CHANGELOG.md
197    • building binaries        
198       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_darwin_386/gowebapptemplate
199       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_freebsd_amd64/gowebapptemplate
200       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_windows_amd64/gowebapptemplate.exe
201       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_freebsd_386/gowebapptemplate
202       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_windows_386/gowebapptemplate.exe
203       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_linux_amd64/gowebapptemplate
204       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_linux_386/gowebapptemplate
205       • building                  binary=/go/src/gitlab.com/terrabitz/GoWebAppTemplate/dist/gowebapptemplate_darwin_amd64/gowebapptemplate
206    • archives                 
207       • creating                  archive=dist/gowebapptemplate_0.0.8_macOS_i386.tar.gz
208       • creating                  archive=dist/gowebapptemplate_0.0.8_Linux_x86_64.tar.gz
209       • creating                  archive=dist/gowebapptemplate_0.0.8_Windows_i386.tar.gz
210       • creating                  archive=dist/gowebapptemplate_0.0.8_Linux_i386.tar.gz
211       • creating                  archive=dist/gowebapptemplate_0.0.8_macOS_x86_64.tar.gz
212       • creating                  archive=dist/gowebapptemplate_0.0.8_Windows_x86_64.tar.gz
213       • creating                  archive=dist/gowebapptemplate_0.0.8_freebsd_i386.tar.gz
214       • creating                  archive=dist/gowebapptemplate_0.0.8_freebsd_x86_64.tar.gz
215    • creating source archive  
216       • pipe skipped              error=source pipe is disabled
217    • linux packages           
218       • creating                  arch=i386 file=dist/gowebapptemplate_0.0.8_Linux_32-bit.rpm package=gowebapptemplate_0.0.8_Linux_32-bit.rpm
219       • creating                  arch=amd64 file=dist/gowebapptemplate_0.0.8_Linux_64-bit.deb package=gowebapptemplate_0.0.8_Linux_64-bit.deb
220       • creating                  arch=i386 file=dist/gowebapptemplate_0.0.8_Linux_32-bit.deb package=gowebapptemplate_0.0.8_Linux_32-bit.deb
221       • creating                  arch=amd64 file=dist/gowebapptemplate_0.0.8_Linux_64-bit.rpm package=gowebapptemplate_0.0.8_Linux_64-bit.rpm
222    • snapcraft packages       
223    • calculating checksums    
224       • checksumming              file=gowebapptemplate_0.0.8_Linux_64-bit.rpm
225       • checksumming              file=gowebapptemplate_0.0.8_Linux_i386.tar.gz
226       • checksumming              file=gowebapptemplate_0.0.8_Windows_i386.tar.gz
227       • checksumming              file=gowebapptemplate_0.0.8_macOS_i386.tar.gz
228       • checksumming              file=gowebapptemplate_0.0.8_Linux_x86_64.tar.gz
229       • checksumming              file=gowebapptemplate_0.0.8_freebsd_i386.tar.gz
230       • checksumming              file=gowebapptemplate_0.0.8_Windows_x86_64.tar.gz
231       • checksumming              file=gowebapptemplate_0.0.8_macOS_x86_64.tar.gz
232       • checksumming              file=gowebapptemplate_0.0.8_freebsd_x86_64.tar.gz
233       • checksumming              file=gowebapptemplate_0.0.8_Linux_32-bit.deb
234       • checksumming              file=gowebapptemplate_0.0.8_Linux_64-bit.deb
235       • checksumming              file=gowebapptemplate_0.0.8_Linux_32-bit.rpm
236    • signing artifacts        
237    • docker images            
238    ⨯ release failed after 421.14s error=0 binaries match docker definition: [{{ .ProjectName }}]: linux_amd64_, should be 1
239
Running after_script
00:01
240
Uploading artifacts for failed job
00:01
241 ERROR: Job failed: exit code 1
```

**Comment by terrabitz** [comment]
After a lot more trial-and-error, I think I've narrowed down the scope of the problem. It seems like the problem only manifests if a templated value is used in the `builds[].binary` section. For example, the docker pipeline in this `.goreleaser.yml` works just fine:

```yaml
project_name: gowebapptemplate
builds:
  - 
    goos:
      - linux

dockers:
  - 
    image_templates:
      - "terrabitz/{{ .ProjectName }}:latest"
```

However, this `.goreleaser.yml` says that it can't find the binary during the docker phase:

```yaml
project_name: gowebapptemplate
builds:
  - 
    goos:
      - linux
    binary: "{{ .ProjectName }}"
dockers:
  - 
    image_templates:
      - "terrabitz/{{ .ProjectName }}:latest"
```

This problem seems to be isolated to using a templated value like `"{{ .ProjectName }}"` in `builds[].binary`. For example, the following works just fine

```yaml
project_name: gowebapptemplate
builds:
  - 
    goos:
      - linux
    binary: foo
dockers:
  - 
    binaries:
      - foo
    image_templates:
      - "terrabitz/{{ .ProjectName }}:latest"
```
