### ISSUE TITLE
bug: brew taps broken on gitlab

### ISSUE THREAD

**Issue by mavogel** [goreleaser/goreleaser#1463]
**Describe the bug**

Due to #1425 the `ArtifactUploadHash` variable is not present any more while templating the `.rb` formula for `brew` in gitlab. Note: the `scoop` formula still contains it

- `"%s/%s/%s/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}",`
- `
`https://gitlab.com/mavogel/release-testing/uploads//release-testing_0.3.40_Darwin_x86_64.tar.gz`  <- note the two `//` with the missing string

**To Reproduce**

- use the https://gitlab.com/mavogel/release-testing repo
- git tag 0.3.42
- git push origin master 0.3.42

The job builds show that brew does not have the `artifactsUploadHash` in the `.Extra` map, whereas scoop has it: 
- brew: https://gitlab.com/mavogel/release-testing/-/jobs/521972792#L327
- scoop: https://gitlab.com/mavogel/release-testing/-/jobs/521972792#L403

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: release-testing

release:
  gitlab:
    owner: mavogel # TODO determine it from git or how if not set?
    name: release-testing
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    #skip_upload: true
    name: release-testing
    gitlab:
      owner: mavogel
      name: homebrew-tab
    commit_author:
      name: "Manuel Vogel"
      email: mavogel@posteo.de
    folder: Formula
    homepage: "https://gitlab.com/mavogel/release-testing"
    description: "Software to create fast and easy drum rolls."
    test: |
      system "#{bin}/release-testing -r"
    install: |
      bin.install "release-testing"

scoop:
  bucket:
    owner: mavogel
    name: scoop-bucket
  commit_author:
    name: "Manuel Vogel"
    email: mavogel@posteo.de
  homepage: "https://gitlab.com/mavogel/release-testing"
  description: "Software to create fast and easy drum rolls."
  license: MIT
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. mac, Linux]: both
- OS version: [uname -a]
- GoReleaser Version [goreleaser --version]: 0.132.0
- GitLab version (if using a private hosted one)

**Additional context**
I think we need to rerun the URL templating step (`func dataFor(...)`) again after releasing to gitlab
