### ISSUE TITLE
Homebrew Manifests Broken in GitLab, Incorrect {{ .ArtifactUploadHash }}

### ISSUE THREAD

**Issue by kaepora** [goreleaser/goreleaser#1473]
**Describe the bug**

Ever since a few weeks ago, whenever Goreleaser generates a Homebrew manifest, the URIs don't work. Here's what the manifest looks like:

```ruby
# This file was generated by GoReleaser. DO NOT EDIT.
class Verifpal < Formula
  desc "Cryptographic protocol analysis for students and engineers."
  homepage "https://verifpal.com"
  version "0.13.1"
  bottle :unneeded

  if OS.mac?
    url "https://source.symbolic.software/verifpal/verifpal/uploads//verifpal_0.13.1_macos_amd64.zip"
    sha256 "b93cf10c49094913120c7cecfe8a70c7ff4f93f248bdfb00aa79f5d6ca7fc538"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://source.symbolic.software/verifpal/verifpal/uploads//verifpal_0.13.1_linux_amd64.zip"
      sha256 "690cfefb4644fe64b536eed85909ec7b5c5a3ee760771b6d727142bac96d8201"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://source.symbolic.software/verifpal/verifpal/uploads//verifpal_0.13.1_linux_arm64.zip"
        sha256 "07d5acd7422bd2e4c781ad09c3eb6e2d70383409f807d332d79c7ef7f2dae7bf"
      else
        url "https://source.symbolic.software/verifpal/verifpal/uploads//verifpal_0.13.1_linux_armv6.zip"
        sha256 "30ddf0e8e6183e0bf13be582dde352cb68740956ecdbaa8506c13f02c2eff9a7"
      end
    end
  end

  def install
    bin.install "verifpal"
  end
end
```

The problem lies in the `uploads//` part of the URI. Clearly, an element between the first and second slash (referred to in the Goreleaser templating logic as `{{ .ArtifactUploadHash }}`)in the aforementioned string is missing. If we go to the GitLab releases page, we can check out the full links generated by GitLab and thereby recover these missing elements, for example, `https://source.symbolic.software/verifpal/verifpal/uploads/8c2ada3d8bfe7ce61aebd1c2d982e2a0/verifpal_0.13.1_macos_amd64.zip`.

Replacing the above URIs with their correct counterparts fixes the issue, and Homebrew works correctly again for install and update procedures:

```ruby
# This file was generated by GoReleaser. DO NOT EDIT.
class Verifpal < Formula
  desc "Cryptographic protocol analysis for students and engineers."
  homepage "https://verifpal.com"
  version "0.13.1"
  bottle :unneeded

  if OS.mac?
    url "https://source.symbolic.software/verifpal/verifpal/uploads/8c2ada3d8bfe7ce61aebd1c2d982e2a0/verifpal_0.13.1_macos_amd64.zip"
    sha256 "b93cf10c49094913120c7cecfe8a70c7ff4f93f248bdfb00aa79f5d6ca7fc538"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://source.symbolic.software/verifpal/verifpal/uploads/5427bb06a82be372b3a4bef6b0e116ab/verifpal_0.13.1_linux_amd64.zip"
      sha256 "690cfefb4644fe64b536eed85909ec7b5c5a3ee760771b6d727142bac96d8201"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://source.symbolic.software/verifpal/verifpal/uploads/c1a0444b863602c82abdf997ac1cca35/verifpal_0.13.1_linux_arm64.zip"
        sha256 "07d5acd7422bd2e4c781ad09c3eb6e2d70383409f807d332d79c7ef7f2dae7bf"
      else
        url "https://source.symbolic.software/verifpal/verifpal/uploads/ea23e9c00326f8254178d615b9cf9420/verifpal_0.13.1_linux_armv6.zip"
        sha256 "30ddf0e8e6183e0bf13be582dde352cb68740956ecdbaa8506c13f02c2eff9a7"
      end
    end
  end

  def install
    bin.install "verifpal"
  end
end
```

**To Reproduce**

Here is our Goreleaser confg file:

```yaml
project_name: verifpal

gitlab_urls:
  api: https://source.symbolic.software/api/v4/
  download: https://source.symbolic.software
  skip_tls_verify: false

before:
  hooks:
    - go generate ./...

builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
      - arm

archives:
  - replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE
      - examples/*
      - README.md
    wrap_in_directory: true

changelog:
  skip: false
  sort: asc

release:
  gitlab:
    owner: verifpal
    name: verifpal

brews:
  - gitlab:
      owner: verifpal
      name: verifpal
    url_template: "https://source.symbolic.software/verifpal/verifpal/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
    commit_author:
      name: drone
      email: drone@symbolic.software
    folder: HomebrewFormula
    homepage: "https://verifpal.com"
    description: "Cryptographic protocol analysis for students and engineers."

scoop:
  bucket:
    owner: verifpal
    name: verifpal
  url_template: "https://source.symbolic.software/verifpal/verifpal/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
  commit_author:
    name: drone
    email: drone@symbolic.software
  homepage: "https://verifpal.com"
  description: "Cryptographic protocol analysis for students and engineers."
  license: "https://www.gnu.org/licenses/gpl-3.0.en.html"
```

**Expected behavior**

Homebrew URIs correctly include `{{ .ArtifactUploadHash }}` correctly.

**Environment (please complete the following information):**

- OS version: `Linux localhost 5.4.10-x86_64-linode132 #1 SMP PREEMPT Thu Jan 9 21:17:12 UTC 2020 x86_64 GNU/Linux`
- GoReleaser Version: `0.132.1`
- GitLab version: `12.10.1-ee (695c29abcf7)`

**Additional context**
It's unfortunate to see issues like this cropping up; just last week we had the highly similar #1447. A lot of projects use Goreleaser in production. I know I'm complaining, so I've added myself as a sponsor to this project so that I can at least put my money where my mouth is.
