### ISSUE TITLE
It tries to add README.md when format: gz

### ISSUE THREAD

**Issue by Miguel-Dorta** [goreleaser/goreleaser#1479]
**Describe the bug**

Format gz (gzip) only accepts one file. When it's specified in the archive format, it tries to add README.md (and possibly README* LICENSE* LICENCE* and CHANGELOG*, I haven't tried it).

**To Reproduce**

Have a project with a README.md file, and add a goreleaser which archive format is "gz"

```yaml
env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy

builds:
  - id: gkup-cli-build
    main: ./cmd/gkup-cli
    binary: gkup
    ldflags: -X github.com/Miguel-Dorta/gkup-cli/internal.Version={{.Version}}
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: gkup-cli-archive
    builds:
      - gkup-cli-build
    format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
```

**Why do you use "{{ .ProjectName }}" instead of "{{ .Binary }}" in the name template?**
According to the [documentation](https://goreleaser.com/archive/):
```yaml
# Archive name template.
# Defaults:
# - if format is `tar.gz`, `tar.xz`, `gz` or `zip`:
#   - `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}`
# - if format is `binary`:
#   - `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}`
```
I also see it a little weird, but ok.

**Expected behavior**

It should build and compress the binary without trying to add any more files

**Actual behavior**

It fails with the following message: 

> ⨯ release failed after 1.61s error=failed to add README.md to the archive: gzip: failed to add README.md, only one file can be archived in gz format

**Environment (please complete the following information):**

- OS: Linux
- OS version: Linux platon 5.6.7-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:50:31 UTC 2020 x86_64 GNU/Linux
- GoReleaser Version:
version: 0.132.1
commit: 244ca69a09735fdd712bd802ff4aefb5d5da60cd
built at: 2020-04-23T02:12:42Z
built by: goreleaser
