### ISSUE TITLE
Bucket path error in s3 blob deploy from windows machine

### ISSUE THREAD

**Issue by taglme** [goreleaser/goreleaser#1510]
When we try to make deploy to aws s3 blob from windows machine there is an error in path delimiter.

**Expected behavior**

In config file "folder" param is set to  "apps/somefolder". But archives uploaded to the root of bucket with name: "apps\somefolder\archive_name" instead of desired folder of bucket.

```yaml
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
release:
  disable: true
archives:
- id: latest
  name_template: "{{ .ProjectName }}_{{ .Os }}_latest"
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - app_icon.png
blobs:
- provider: s3
  region: eu-west-1
  disableSSL: true
  bucket: mybucket
  ids:
    - latest
  folder: "apps/somefolder"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

```

**Environment:**

- OS: windows
- OS version: windows 10
- GoReleaser Version 0.133.0
