### ISSUE TITLE
Doc: improve documentation regarding integration with the gitlab subgroup.

### ISSUE THREAD

**Issue by gauthierc** [goreleaser/goreleaser#1616]
When using subgroups in gitlab, it's necessary to specify the subgroup name in release>gitlab>owner in the .goreleaser.yml file, like this:
```
release:
  gitlab:
    owner: mygroup/mysubgroup
    name: myapps
gitlab_urls:
  api: https://gitlab.mycompany.com/api/v4/
  download: https://gitlab.company.com
```

Otherwise, goreleaser returns this error `"error=github/gitlab/gitea releases: failed to publish artifacts: GET https://gitlab.mycompany.com/api/v4projects/mysubgroup/myapps/releases:v0.0.1  404 {message: 404 Project Not Found} "`
