### ISSUE TITLE
Artifactory throws EOF during upload

### ISSUE THREAD

**Issue by r0goyal** [goreleaser/goreleaser#1631]
**Describe the bug**

Hi, 

I am using artifactory extension to upload my build artifacts. While uploading the artifacts, goreleaser fails with following exception

` ⨯ artifactory: upload failed error=EOF instance=production username=debtest`

Note that I am trying to upload a debian package generated using `nfpm` to artifactory. I have setup debian repository on my artifactory instance

**To Reproduce**

Just build any package and try to upload to artifactory. 

```yaml
# .goreleaser.yml

project_name: package

source:
  enabled: false

archives:
  - format: binary

release:
  disable: true

builds:
  - goos:
      - linux
    goarch:
      - amd64

artifactories:
  - name: production
    target: http://<artifactory-server>/content/sites/apt/{{ .ProjectName }}/{{ .Version }}/{{ .Os }}/{{ .Arch }}

nfpms:
  - id: package

    package_name: package

    # You can change the file name of the package.
    # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}`
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults to all builds.
    builds:
      - package

    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:

    # Your app's license.
    # Default is empty.
    license: Apache 2.0

    # Formats to be generated.
    formats:
      - deb

    # Packages your package depends on.
    dependencies:

    # Packages your package recommends installing.
    recommends:

    # Packages your package suggests installing.
    suggests:

    # Packages that conflict with your package.
    conflicts:

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

    # Package epoch.
    # Defaults to empty.
    epoch: 1

    # Package release.
    # Defaults to empty.
    release: 1

    # Empty folders that should be created and managed by the packager
    # implementation.
    # Default is empty.
    empty_folders:
      - /var/log/package

    # Files to add to your package (beyond the binary).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    # Use globs to add all contents of a folder.
    files:

    # Config files to add to your package. They are about the same as
    # the files keyword, except package managers treat them differently (while
    # uninstalling, mostly).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    config_files:

    # Scripts to execute during the installation of the package.
    # Keys are the possible targets during the installation process
    # Values are the paths to the scripts which will be executed
    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"

    # Some attributes can be overrided per package format.
    overrides:
      deb:
        conflicts:
        dependencies:
        suggests:
        recommends:
        empty_folders:
          - /var/log/package

```

**Expected behavior**

Package should be uploaded without any issue

**Environment (please complete the following information):**

- OS: Mac
- OS version: 10.15.4
- GoReleaser Version: 0.138.0
- Artifactory version: 2.14.17

**Additional context**
Going through goreleaser codebase, I figured that after successful upload (status code between 200 and 299), it tries to unmarshal response into `artifactoryResponse` struct. 

Artifactory version I am using is 2.14 which is not the latest one (3.x). 
Not aware of API responses of 3.x PUT API but 2.xx PUT API returns 201 status code with no response body which I suspect is causing EOF since there is nothing to unmarshal. Is there any plan to support artifactory 2.x or is my debugging incorrect ?

Also noticed that output of API response is actually discarded in `artifactory.go`. Following is the code snippet - 
```go
		var r artifactoryResponse
		err := json.NewDecoder(res.Body).Decode(&r)
		return err
```

Is there any reason of parsing the response if it just going to be discarded ? This looks redundant since status code is anyway checked for proper range (between 200 & 299)
