### ISSUE TITLE
NFPM does not apply "recommends" to RPMs

### ISSUE THREAD

**Issue by rbtr** [goreleaser/goreleaser#1636]
**Describe the bug**

The "recommends" nfpm config field is ignored for RPMs.

**To Reproduce**

1) Build an RPM via goreleaser, with a `recommends` in the NFPM config.

```yaml
[...]
nfpms:
  recommends:
  - any package
```

2) Check the produced RPM for it's recommended packages:

```
$ sudo dnf repoquery --recommends ./my-app.rpm
< no values >
```

**Expected behavior**

Recommends should be applied to the RPM.
