### ISSUE TITLE
enable templates in nfpms files

### ISSUE THREAD

**Issue by rbonthond** [goreleaser/goreleaser#1637]
I'm building multiple artifacts with nmpfs, and each has it's on documentation/settings/etc. I would like to use template names in the "files" field under nfpms.

Something like:
```
nfpms:
  - <<: &nfpms_defaults
      vendor: "ACME"
      description: "cmdA"
      file_name_template: "{{ .ProjectName }}-{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
      bindir: "/usr/share/{{ .ProjectName }}/{{ .Binary }}"
      files:
        "pkg/{{ .Binary }}/etc/**": "/usr/share/{{ .ProjectName }}/{{ .Binary }}/etc"
        "pkg/{{ .Binary }}/doc/**": "/usr/share/{{ .ProjectName }}/{{ .Binary }}/doc"
      formats:
        - deb
        - rpm
    id: cmdA
    builds: [cmdA]
  - <<: *nfpms_defaults
    id: cmdB
    builds: [cmdB]
  - <<: *nfpms_defaults
    id: cmdC
    builds: [cmdC]
```
