### ISSUE TITLE
enable file mapping in archives

### ISSUE THREAD

**Issue by rbonthond** [goreleaser/goreleaser#1638]
I'm building multiple artifacts with archives, and each has it's on documentation/settings/etc. I would like to be able to map files to a different location using "files" field.

Something like:

```
archives:
  - <<: &archive_defaults
      name_template: "{{ .ProjectName }}-{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
      format: tar.gz
      wrap_in_directory: true
      files:
        - pkg/{{ .Binary }}/etc/**:etc/**
        - pkg/{{ .Binary }}/doc/**:doc/**
    id: cmdA
    builds: [cmdA]
  - <<: *archive_defaults
    id: cmdB
    builds: [cmdB]
  - <<: *archive_defaults
    id: cmdC
    builds: [cmdC]
```
