### ISSUE TITLE
Support custom token for Homebrew & Scoop pushes

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#1643]
**Is your feature request related to a problem? Please describe.**

Currently Homebrew and Scoop publishing relies on the single token given to GoReleaser.

Usually Homebrew/Scoop formulas/manifests don't live in the same repo and in such cases publishing to Homebrew or Scoop requires passing a custom token with elevated privileges (push to both Homebrew and Scoop repositories).

This makes it inflexible for organisations with good security hygiene where Homebrew tap and Scoop bucket may be each managed centrally and tokens issued separately with just access to each individual repository.

**Describe the solution you'd like**

Allow specifying custom token for Homebrew and for Scoop, e.g.

```yaml
brews:
  -
    github:
      owner: github-user
      name: homebrew-tap
      token: {{ .Env.HOMEBREW_TOKEN }}
```

```yaml
scoop:
  bucket:
    owner: github-user
    name: scoop-bucket
    token: {{ .Env.SCOOP_TOKEN }}
```

**Describe alternatives you've considered**

 - Providing a single token with access to (1) current repository, (2) Homebrew tap, and (3) Scoop bucket
 - Use `skip_upload: true` for Homebrew and handle commit & push outside of GoReleaser
