### ISSUE TITLE
Builds have default GOOS & GOARCH even for explicit targets

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#1653]
**Describe the bug**

When building for explicit targets, the internal `config.Build` receives default GoOS and GoArch
https://github.com/goreleaser/goreleaser/blob/752d4e5435468a9c4b9e911840101d2af2f5acaa/internal/builders/golang/build.go#L44-L49

which then trips up this logic in Homebrew pipe:
https://github.com/goreleaser/goreleaser/blob/752d4e5435468a9c4b9e911840101d2af2f5acaa/internal/pipe/brew/brew.go#L116-L123

as it falsely identifies builds as Homebrew when they're not.

The combination (multiple builds + use of explicit targets + homebrew) is rare enough that it doesn't affect as many people I suppose, but it does result in duplicate `install` stanzas in the published formula:

```ruby
  def install
    bin.install "binary-name"
    bin.install "binary-name"
  end
```

**To Reproduce**

```yaml
builds:
  -
    targets:
      - darwin_amd64
      - windows_386
      - windows_amd64
  -
    targets:
      - linux_386
      - linux_amd64
brews:
  -
    tap:
      owner: myself
      name: homebrew-tap
```

**Expected behavior**

 - GoOS & GoArch remains empty if targets are explicitly defined
 - Homebrew doesn't publish duplicate `install` stanza

**Environment (please complete the following information):**

- OS: macOS
- OS version: 10.15.5
- GoReleaser Version: v0.139.0

**Workaround:**

This can be probably worked around by specifying the `install` config option which overrides the detection:

```yaml
install: |
      bin.install "program"
```
