### ISSUE TITLE
Snapcraft build failures when using completers

### ISSUE THREAD

**Issue by neoaggelos** [goreleaser/goreleaser#1678]
**Describe the bug**

When creating a snap package with multiple builds and multiple apps, setting a completer on the application fails.

**To Reproduce**
```yaml
snap:
  builds:
  - build1
  - build2
  apps:
    app1:
      completer: app1.completer
    app2:
      completer: app2.completer
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

The snap to build successfully

**Environment (please complete the following information):**

- OS: all
- OS version: all
- GoReleaser 0.140.0
- GitLab version n/a

**Additional context**

This occurs because https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/snapcraft/snapcraft.go#L273 is executer per application per binary, so `os.Link` fails the second time around with a `File Exists` error.
