### ISSUE TITLE
archive replacements not working for format binary

### ISSUE THREAD

**Issue by marcofranssen** [goreleaser/goreleaser#1685]
**Describe the bug**

`replacements` not working when archive format is `binary`.

Outputs:

```
• building                  binary=/Users/marco/code/my-project/dist/binary_darwin_amd64/my-project
```

**To Reproduce**

When using the following config:

```yml
archives:
  - id: binary
    format: binary
    replacements:
      darwin: macOS
```

```yaml
your goreleaser config file
```

**Expected behavior**

Outputs:

```
• building                  binary=/Users/marco/code/my-project/dist/binary_macOS_amd64/my-project
```

**Environment (please complete the following information):**

- OS: `mac`
- OS version: `Darwin MACC02X31SVJGH8 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`
- goreleaser version dev
