### ISSUE TITLE
Provide a name template for the current build module/package

### ISSUE THREAD

**Issue by dionysius** [goreleaser/goreleaser#1688]
**Is your feature request related to a problem? Please describe.**
I have version informations in an separate package within the same repo, since I provide functions to use, handle and display version related informations differently. That means I can't use `-X main.xyz=...` and am forced to give the full go package name to that package in ldflag's `-X` argument. There seems to be no module related name in https://goreleaser.com/customization/templates/

**Describe the solution you'd like**
- I'd like to have a name for the current _root_ package, which is a module in my case, which would be `<"current-dir">/<builds.dir>`. Suggestion `.Module`
- And/Or a name for the current binary package, which would be `<"current-dir">/<builds[].dir>/<builds[].main>`. Suggestion `.Package` (read: package of the binary)

- If I had a `.Module` I could do `-X "{{.Module}}/cli/version.Version={{.Version}}"`
- If I had a `.Package` I could do `-X "{{replace .Package "/cmd/lxe" ""}}/cli/version.Version={{.Version}}"`

Reference:
- `go list -m` prints the module
- `go list -f {{ .ImportPath }} <dir>` prints the package

```bash
$ go list -m
github.com/automaticserver/lxe
$ go list -f '{{ .ImportPath }}' ./cmd/lxe/
github.com/automaticserver/lxe/cmd/lxe
$ go list -f '{{ .ImportPath }}' ./cli/version/
github.com/automaticserver/lxe/cli/version
$ cd cmd/lxe/; go list -m # module is printed in every subpackage
github.com/automaticserver/lxe
```

**Describe alternatives you've considered**
A working alternative is providing that path hardcoded in the environment:
```yaml
builds:
- binary: lxe
  main: cmd/lxe/main.go
  env:
  - GO111MODULE=on
  - GO_MODULENAME=github.com/automaticserver/lxe
  ldflags: 
    - -s -w
    - -X "{{.Env.GO_MODULENAME}}/cli/version.Version={{replace .Version (print "-" .ShortCommit) ""}}"
    - -X "{{.Env.GO_MODULENAME}}/cli/version.GitCommit={{.FullCommit}}"
    - -X "{{.Env.GO_MODULENAME}}/cli/version.BuildDate={{time "Mon, 02 Jan 2006 15:04:05 -0700"}}"
    - -X "{{.Env.GO_MODULENAME}}/cli/version.PackageName={{.ProjectName}}"
```
I want to prevent hardcoding such paths and honor a single source of truth, which is go module in this case. So forking and changing the module path is less of a pain.

**Additional context**
- Hint: A go module and a go package is not the same thing
- I'm not quite sure, but I think there's no guarantee that the PackageRoot is always a Module. (As a hint to help to find the best naming). In my case, it would be. But I think the rule of thumb would be if it has a go.mod (or just check with `go list -m`, that it can be treated as a Module - but there might be a better declaration.
