### ISSUE TITLE
Changelog listing entire commit history

### ISSUE THREAD

**Issue by infixint943** [goreleaser/goreleaser#1712]
**Describe the bug**
Instead of listing all commit changes from the last release, goreleaser now lists commit changes right from the first commit.

**To Reproduce**

```yaml
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    
    files:
      - none*

builds:
  -
    goos:
      - linux
      - darwin
      - windows
  
    goarch:
      - "386"
      - "amd64" 
    
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  draft: true

```

**Expected behavior**
Only commit log from the last release should be displayed.

**Environment (please complete the following information):**
(Github actions. I'm not sure what the values are)
