### ISSUE TITLE
Git is currently in a dirty state

### ISSUE THREAD

**Issue by jimafisk** [goreleaser/goreleaser#1714]
**Describe the bug**

When I run goreleaser via GitHub Actions on [my project](https://github.com/plentico/plenti), I receive the following error:
```
⨯ release failed after 6.85s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
 M generated/defaults.go
```

I believe this may have something to do with the fact that the `go generate` content is very long (~40k lines, see [this](https://github.com/plentico/plenti/blob/9af14c4788a3e678980b204857c5964ea58c709f/generated/defaults.go)). It's possible that something is timing out when trying to verify this in CI. 

It would be helpful to be able to get more debugging info regarding the git diff, as proposed in this ticket: https://github.com/goreleaser/goreleaser/issues/1005

Potential solutions:
1. In my `.goreleaser.yml` config file, comment out the `before > hooks > go generate` info to stop this check
2. Adjust timeout settings if possible / applicable

**To Reproduce**

1. Commit a really long file of generated content (embedded static files)
2. Run a `go generate` via your `.goreleaser.yml` config file

<details>
<summary>My .goreleaser.yml file</summary>
<br />

Link: https://github.com/plentico/plenti/blob/9af14c4788a3e678980b204857c5964ea58c709f/.goreleaser.yml

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  ignore:
  - goos: darwin
    goarch: 386
archives:
- replacements:
    darwin: Mac
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: plenti
    github:
      owner: plentico
      name: homebrew-plenti
    homepage: "https://plenti.co/"
    description: "Dead simple SSG with Svelte frontend and Go CLI."
snapcrafts:
  -
    id: plenti
    name: plenti
    publish: true # publish the snap to the snapcraft store.
    summary: A simple static site generator for the JAMstack. 
    description: Dead simple SSG with Svelte frontend and Go CLI.
    grade: stable
    confinement: strict
    license: Apache-2.0
    # allow read/write to user's filesystem.
    apps:
      plenti:
        plugs: ["home", "network-bind", "removable-media"]
scoop:
  bucket:
    owner: plentico
    name: scoop-plenti
  description: "Dead simple SSG with Svelte frontend and Go CLI."
  license: Apache-2.0
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - plenti
    image_templates:
    - "plentico/plenti:latest"
    - "plentico/plenti:{{ .Tag }}"
```
</details>

<details>
<summary>Valid .goreleaser.yml config file</summary>
<br />

Running the following:

> `goreleaser check -f .goreleaser.yml`

returns: `error=config is valid, but uses deprecated properties, check logs above for details`

</details>

**Expected behavior**

I expected that there would not be a diff between CI (GitHub Actions) and my local (Ubuntu 18.04) laptop. If I run `go generate ./...` locally there are no changes recognized by git.

**Environment (please complete the following information):**

- OS: Ubuntu (On GitHub Actions)
- OS version: 18.04.4 (On GitHub Actions)
- GoReleaser Version: v0.140.1
- GitLab version: N/A, using GitHub Actions

**Additional context**

Failing build: https://github.com/plentico/plenti/runs/928964007#step:8:26

My analysis could be wrong, but figured I would flag this in case it's an issue that other folks might run into. Thanks for the help!
