### ISSUE TITLE
brews only evaluates first formula

### ISSUE THREAD

**Issue by travisgroth** [goreleaser/goreleaser#1719]
**Describe the bug**

When two formulas are in the `brews` section, it looks like only the first one listed is created/updated.

**To Reproduce**

```yaml
brews:
  - name: app-cli
    ids:
      - app-cli
    tap:
      owner: app
      name: homebrew-tap

  - name: app
    ids:
      - app

    tap:
      owner: app
      name: homebrew-tap
```

only dist/app-cli.rb will be generated.

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

Since `brews` is a list, and there can be multiple releasable builds/archives in goreleaser, I'd expect two formulas to be generated.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]: OSX
- OS version: [uname -a]: `Darwin XXXX 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64`
- GoReleaser Version [goreleaser --version]: 
```
goreleaser version 0.140.1
commit: 47e88b9bcf6d9567ee95db4d3d1b2516734386e6
built by: homebrew
```
**Additional context**
It doesn't look like debug logs contain any information about brew creation.
