### ISSUE TITLE
arrary of archives doesn't follow name template

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#1720]
**Describe the bug**

I'm working around the question #1708 so I have 2 archives, one for windows and one for Unix:

```
archives:
- id: foo-unix
  builds:
    - foo
    - foo-1
  replacements:
    amd64: x64
  files:
    - foo-extra-file
  name_template: "{{ .ProjectName }}-{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
- id: foo-windows
  builds:
    - foo-windows
    - foo-windows-1
  replacements:
    amd64: x64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - foo-extra-file.cmd
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
```

and my archive is being built like so:

```
• archives
      • creating                  archive=dist/foo-pkg/v2.7.1_darwin_x64.tar.gz
      • creating                  archive=dist/foo-pkg/v2.7.1-windows-x64.zip
      • creating                  archive=dist/foo-pkg/v2.7.1_linux_x64.tar.gz
   • creating source archive
```

It seems the project name is being added to a new directory, rather than the archive name

**To Reproduce**

See above config

**Expected behavior**

This should be creating a package like so:

```
• archives
      • creating                  archive=dist/foo-v2.7.1_darwin_x64.tar.gz
      • creating                  archive=dist/foo-v2.7.1-windows-x64.zip
      • creating                  archive=dist/foo-v2.7.1_linux_x64.tar.gz
   • creating source archive
```

It seems to be the name_template of `archive` is broken when archive is an array?
