### ISSUE TITLE
Getting invalid object name 'tags/warning' when attempting to release 

### ISSUE THREAD

**Issue by AndreasBieber** [goreleaser/goreleaser#1734]
**Describe the bug**

When attempting to release via Azure DevOps Pipeline I get the following during the changelog generation which breaks the release in the end:
```
• generating changelog     
      • running git               args=[-c log.showSignature=false describe --tags --abbrev=0 tags/v0.3.18^]
      • git result                output=warning: refname 'tags/v0.3.18' is ambiguous.
v0.3.17

      • running git               args=[-c log.showSignature=false log --pretty=oneline --abbrev-commit --no-decorate --no-color tags/warning: refname tags/v0.3.18 is ambiguous...tags/v0.3.18]
      • git result                output=fatal: invalid object name 'tags/warning'.

   ⨯ release failed after 1.59s error=fatal: invalid object name 'tags/warning'.
```
When disabling changelog generation everything is working as expected.

**To Reproduce**

I'm not able to reproduce this issue because it is working locally as expected.

`.goreleaser.yaml`:
```yaml
dist: ./artifacts/dist
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- main: ./cmd/enpxio/enpxio.go
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  ldflags:
    - -s -w -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.Version={{.Version}} -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.Commit={{.Commit}} -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.BuiltDate={{.Date}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
release:
  disable: true
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^style:'
    - '^refactor:'
```

**Expected behavior**

The release should create a changelog without errors.

**Environment:**

- OS: `linux`
- OS version: `Linux fv-az695 5.3.0-1034-azure #35~18.04.1-Ubuntu SMP Mon Jul 13 12:54:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- GoReleaser Version: `0.141.0`
- CI/CD: `Azure DevOps`

**Additional context**
Build Pipeline log with `--debug`:
```
Starting: Prepare release
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.171.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
make release
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/3cb79059-2fa7-44ad-9ad4-53c5fe3f281b.sh
goreleaser/goreleaser info checking GitHub for latest tag
goreleaser/goreleaser info found version: 0.141.0 for v0.141.0/Linux/x86_64
goreleaser/goreleaser info installed /home/vsts/work/1/go/bin/goreleaser

   • debug logs enabled       
   • releasing...             
   • loading config file       file=.goreleaser.yml
   • loaded config file        config={ [] {   false true   [] []} [] [] { {  } { }      [] } [{ [linux windows darwin] [] [] [] [] []  ./cmd/enpxio/enpxio.go [-s -w -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.Version={{.Version}} -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.Commit={{.Commit}} -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.BuiltDate={{.Date}}] []  {[] []} [CGO_ENABLED=0]  [] []  false}] [{ [] {{ .ProjectName }}_{{ .Os }}_{{ .Arch }} map[386:i386 amd64:x86_64 darwin:Darwin linux:Linux windows:Windows]  [{windows zip}]  []}] [] [] {} {checksums.txt } [] [] [] [] [] {{[^docs: ^test: ^chore: ^style: ^refactor:]} asc false} ./artifacts/dist [] {  } {[go mod download go generate ./...]} {  false} { [] [] [] [] [] []   [] []  {[] []} []  [] []  false} {   false} {  false} { false}}
   • parallelism: 2           
   • loading environment variables
   • getting and validating git state
      • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
      • git result                output=true

      • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
      • git result                output=true

      • running git               args=[-c log.showSignature=false show --format='%h' HEAD --quiet]
      • git result                output='40e3e27'

      • running git               args=[-c log.showSignature=false show --format='%H' HEAD --quiet]
      • git result                output='40e3e27461ec4a1532ce11e1f9cf7e31bbbd1bf5'

      • running git               args=[-c log.showSignature=false show --format='%ct' HEAD --quiet]
      • git result                output='1596967223'

      • running git               args=[-c log.showSignature=false ls-remote --get-url]
      • git result                output=https://myorg.visualstudio.com/myproject/_git/enpxio

      • running git               args=[-c log.showSignature=false describe --tags --abbrev=0]
      • git result                output=v0.3.18

      • releasing v0.3.18, commit 40e3e27461ec4a1532ce11e1f9cf7e31bbbd1bf5
      • running git               args=[-c log.showSignature=false status --porcelain]
      • git result                output=
      • running git               args=[-c log.showSignature=false describe --exact-match --tags --match v0.3.18]
      • git result                output=v0.3.18

   • parsing tag              
   • running before hooks     
      • running go mod download  
      •                           cmd=go mod download
      • running go generate ./...
      •                           cmd=go generate ./...
   • setting defaults         
      • snapshotting             
      • github/gitlab/gitea releases
         • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
         • git result                output=true

         • running git               args=[-c log.showSignature=false config --get remote.origin.url]
         • git result                output=https://myorg.visualstudio.com/myproject/_git/enpxio

         • pre-release for tag v0.3.18 set to false
      • project name             
      • building binaries        
      • creating source archive  
      • archives                 
      • linux packages           
      • snapcraft packages       
      • calculating checksums    
      • signing artifacts        
      • docker images            
      • artifactory              
      • blobs                    
      • homebrew tap formula     
      • scoop manifests          
      • milestones               
         • running git               args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
         • git result                output=true

         • running git               args=[-c log.showSignature=false config --get remote.origin.url]
         • git result                output=https://myorg.visualstudio.com/myproject/_git/enpxio

   • snapshotting             
      • pipe skipped              error=not a snapshot
   • checking ./dist          
      • ./dist doesn't exist, creating empty folder
   • writing effective config file
      • writing                   config=artifacts/dist/config.yaml
   • generating changelog     
      • running git               args=[-c log.showSignature=false describe --tags --abbrev=0 tags/v0.3.18^]
      • git result                output=warning: refname 'tags/v0.3.18' is ambiguous.
v0.3.17

      • running git               args=[-c log.showSignature=false log --pretty=oneline --abbrev-commit --no-decorate --no-color tags/warning: refname tags/v0.3.18 is ambiguous...tags/v0.3.18]
      • git result                output=fatal: invalid object name 'tags/warning'.

   ⨯ release failed after 1.59s error=fatal: invalid object name 'tags/warning'.

Makefile:56: recipe for target 'release' failed

make: *** [release] Error 1
##[error]Bash exited with code '2'.
Finishing: Prepare release
```

`git --no-pager tag` output:
```
v0.1.0
v0.1.1
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.2.0
v0.2.1
v0.2.2
v0.2.3
v0.3.0
v0.3.1
v0.3.10
v0.3.11
v0.3.12
v0.3.13
v0.3.14
v0.3.15
v0.3.16
v0.3.17
v0.3.18
v0.3.2
v0.3.3
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
```

Content of `artifacts/dist/config.yaml`:
```yaml
project_name: enpxio
release:
  github:
    owner: _git
    name: enpxio
  disable: true
  name_template: '{{.Tag}}'
milestones:
- repo:
    owner: _git
    name: enpxio
  name_template: '{{ .Tag }}'
scoop:
  name: enpxio
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
builds:
- id: enpxio
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  targets:
  - linux_amd64
  - linux_386
  - windows_amd64
  - windows_386
  - darwin_amd64
  - darwin_386
  dir: .
  main: ./cmd/enpxio/enpxio.go
  ldflags:
  - -s -w -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.Version={{.Version}} -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.Commit={{.Commit}} -X dev.azure.com/myorg/myproject/_git/enpxio.git/internal/meta.BuiltDate={{.Date}}
  binary: enpxio
  env:
  - CGO_ENABLED=0
  lang: go
archives:
- id: default
  builds:
  - enpxio
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    "386": i386
    amd64: x86_64
    darwin: Darwin
    linux: Linux
    windows: Windows
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^style:'
    - '^refactor:'
  sort: asc
dist: ./artifacts/dist
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
before:
  hooks:
  - go mod download
  - go generate ./...
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com
```
