### ISSUE TITLE
Snapcraft packages cannot be built on Mac

### ISSUE THREAD

**Issue by prantlf** [goreleaser/goreleaser#1749]
When running:

    goreleaser --skip-publish --snapshot --rm-dist

the execution fails with the following error:

    ...
    • snapcraft packages
      • creating                  arch=amd64 snap=dist/saz-tools_v0.0.16-next_linux_x86_64.snap
      • creating                  arch=arm64 snap=dist/saz-tools_v0.0.16-next_linux_arm64.snap
      • creating                  arch=armhf snap=dist/saz-tools_v0.0.16-next_linux_armv6.snap
    ⨯ release failed after 10.47s error=failed to generate snap package:
        A tool snapcraft depends on could not be found: 'snap'

    Recommended resolution:
    Ensure that 'snapd' is installed.

However, [installing `snapcraft` on Mac] installs only `snapcraft` binary. Neither `snap` nor `snapd`.

The relevant part of the [failing `.goreleaser.yml`]:

```yaml
snapcrafts:
- summary: Parsing, dumping, viewing and analysing tools for SAZ (Fiddler) files
  description: |
    Tools for parsing SAZ files (Fiddler logs) and either printing their
    content on the console, or viewing them on a web page and offering
    basic analysis and export.
  grade: stable
  confinement: strict
  publish: true
  license: MIT
  replacements:
    amd64: x86_64
  apps:
    sazdump:
      plugs: ["home"]
    sazserve:
      plugs: ["network"]
```

Can `goreleaser` pack and publish a snap package on Mac? Thank you!

- OS: OSX 10.14.6
- OS version: Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64
- GoReleaser Version goreleaser version 0.141.0 commit: bc940a90529ac9f6cf42c41081ae14a6534dcf2d built by: homebrew

[installing `snapcraft` on Mac]: https://snapcraft.io/docs/install-snapcraft-on-macos
[failing `.goreleaser.yml`]: https://github.com/prantlf/saz-tools/blob/v0.0.15/.goreleaser.yml#L75-L91
