### ISSUE TITLE
Brews does not work with template in the name field

### ISSUE THREAD

**Issue by timharris777** [goreleaser/goreleaser#1755]
**Describe the bug**

When using `Brews` section if I put a template tag in the `name` field multiple things don't work. 

I'm using:
```
goreleaser version 0.141.0
commit: bc940a90529ac9f6cf42c41081ae14a6534dcf2d
built by: homebrew
```

**To Reproduce**
Run `GITHUB_TOKEN_BREW=$GITHUB_TOKEN APP_VERSION=1.0.0 APP_RELEASE=-dev goreleaser --snapshot --skip-publish --rm-dist` with the yaml below:

```yaml
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- id: windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - 386
  ignore:
    - goos: windows
      goarch: amd64
  ldflags: -X "main.Version={{.Env.APP_VERSION}}"
- id: other
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - 386
  ldflags: -X "main.Version={{.Env.APP_VERSION}}"
archives:
- id: other
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  builds:
  - other
  replacements:
    darwin: Mac
    linux: Linux
    386: 32-bit
    amd64: 64-bit
  format: tar.gz
  format_overrides:
  - goos: windows
    format: binary
  files:
    - none*
- id: windows
  name_template: "{{ .Binary }}"
  builds: 
    - windows
  format: binary
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
brews:
  - name: "aws-login{{ .Env.APP_RELEASE }}"
    tap:
      owner: cfacorp
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN_BREW }}"
    folder: Formula
    description: A utiltity to login to aws accounts from cli using OKTA SSO
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "../custom_download_strategy"
    skip_upload: true
```

I get an error message saying `release failed after 6.52s error=homebrew tap formula: failed to publish artifacts: template: tmpl:3:20: executing "tmpl" at <.Env.APPRELEASE>: map has no entry for key "APPRELEASE"`. But if you look at my yaml file I have `{{ .Env.APP_RELEASE}}`. It seams to be stripping the underscore.

To humor this I removed the underscore from my env var and ran the following command: `GITHUB_TOKEN_BREW=$GITHUB_TOKEN APP_VERSION=1.0.0 APPRELEASE=-dev goreleaser --snapshot --skip-publish --rm-dist`

This time the build completed, but the brew formula file is named: `aws-login{{ .Env.APP_RELEASE }}.rb` and if I look in the Formula the class is `class AwsLogin-dev < Formula` when it should be `class AwsLoginDev < Formula`. It seems that templating is broken for the `name` field in the `Brews` section.
