### ISSUE TITLE
Add config option to add files based on OS

### ISSUE THREAD

**Issue by Blesmol** [goreleaser/goreleaser#1803]
I'd like to request a feature that allows to add files only to the archive for a specific OS.

Scenario in my case is that I want to add script files for end-users. On windows, this would be batch files, on Linux I want to add shell scripts instead and so on.

Something in the direction of the following:

```yaml
archives:
  files:
    - file1
    - file2
  files_overrides:
    - goos: windows
      files:
        - file3.bat
    - goos: linux
      files:
        - file3.sh
```

**Comment by caarlos0** [comment]
you can do this by creating one build and one archive config per OS - including only the relevant build IDs and all.

```yaml
builds:
- id: linux
  goos: [linux]
  # etc
- id: windows
  goos: [windows]
  # etc
archives:
- id: linux
  builds: [linux]
  # etc
- id: windows
  builds: [windows]
  # etc
```

```
