### ISSUE TITLE
Not having an ARM files makes brew formula un-tappable on ARM machines

### ISSUE THREAD

**Issue by gssbzn** [goreleaser/goreleaser#1804]
**Describe the bug**

Currently we got a report where not having an ARM url for one of our formulas makes the whole tap error

The generated formula can be seen [here](https://github.com/mongodb/homebrew-brew/blob/master/Formula/mongocli.rb)

**To Reproduce**

Users are doing `brew tap mongodb/brew` and getting:
```
Invalid formula <formula path>
Formulae require at least a URL

Cannot tap mongodb/brew
```

```yaml
before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      main: ./cmd/mongocli/mongocli.go
      ldflags:
        - -s -w -X github.com/mongodb/mongocli/internal/version.Version={{.Version}}
    id: macos
    goos: [darwin]
    goarch: [amd64]
    hooks:
      post: gon -log-level=error gon.json
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]
archives:
- id: linux
  builds: [linux]
  <<: &archive_defaults
    files:
      - README.md
      - LICENSE
      - third_party_notices/**/*
    replacements:
      darwin: macos
      amd64: x86_64
  wrap_in_directory: true
  format: tar.gz
- id: macos
  builds: [macos]
  <<: *archive_defaults
  format: zip
  wrap_in_directory: false
- id: windows
  builds: [windows]
  <<: *archive_defaults
  wrap_in_directory: false
  format: zip
brews:
- name: mongocli
  ids: [macos,linux]
  tap:
    owner: mongodb
    name: homebrew-brew
  folder: Formula
  skip_upload: auto
  description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  homepage: https://github.com/mongodb/mongocli
  install: |
    bin.install "mongocli"
    (bash_completion/"mongocli.sh").write `#{bin}/mongocli completion bash`
    (zsh_completion/"_mongocli").write `#{bin}/mongocli completion zsh`
    (fish_completion/"mongocli.fish").write `#{bin}/mongocli completion fish`
  test: |
    system "#{bin}/mongocli --version"
nfpms:
- package_name: mongocli
  vendor: MongoDB Inc.
  homepage: https://www.mongodb.com/
  maintainer: MongoDB Inc. <support@mongodb.com>
  description: The MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  license: Apache 2.0
  bindir: /usr/bin
  builds: [linux]
  formats: [deb,rpm]
  replacements:
    amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: next
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true
  prerelease: auto
  extra_files:
    - glob: ./dist/mongocli_macos_signed_x86_64.zip

```

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- GoReleaser Version [goreleaser --version]
- GitLab version (if using a private hosted one)

**Additional context**

We don't plan to support ARM at the moment but some other formulas in our tap plan to do so and was wondering if we should maybe have a default behaviour for brew on ARM, even if wrong, to at least allow tapping
