### ISSUE TITLE
resolve templates in env section

### ISSUE THREAD

**Issue by troian** [goreleaser/goreleaser#1820]
In some cases like [cross-compiling](https://gophers.slack.com/archives/C3T1JU24B/p1600905690004300) it is quite handy to substitute long strings especially when there are repetitive.
In [example](https://github.com/troian/golang-cross/blob/master/.goreleaser.yaml) instead of writing
```yaml
builds:
  - id: darwin-amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/go/src/github.com/troian/golang-cross/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/go/src/github.com/troian/golang-cross/sysroot/macos/amd64/usr/local/lib/pkgconfig
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_SYSROOT_DIR=/go/src/github.com/troian/golang-cross/sysroot/linux
      - PKG_CONFIG_PATH=/go/src/github.com/troian/golang-cross/sysroot/linux/usr/lib/x86_64-linux-gnu/pkgconfig
```
it would be good to use path prefixes from env variable
```yaml
builds:
  - id: darwin-amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR={{ .Env.SYSROOT_DIR }}/macos/amd64
      - PKG_CONFIG_PATH={{ .Env.SYSROOT_DIR }}/macos/amd64/usr/local/lib/pkgconfig
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_SYSROOT_DIR={{ .Env.SYSROOT_DIR }}/linux
      - PKG_CONFIG_PATH={{ .Env.SYSROOT_DIR }}/linux/usr/lib/x86_64-linux-gnu/pkgconfig
```
