### ISSUE TITLE
`archives.name_template` not respected when `format: binary`

### ISSUE THREAD

**Issue by coolaj86** [goreleaser/goreleaser#1821]
**Describe the bug**

When I set the `archives.format: binary` it no longer respects `name_template`.

**To Reproduce**

`.goreleaser.yml`:

```yml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: arc
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0
    main: ./cmd/foo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
    format: binary
    replacements:
      darwin: mac
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

```bash
goreleaser --snapshot --skip-publish --rm-dist
```

```txt
foo_darwin_amd64
foo_linux_386
foo_linux_amd64
foo_linux_arm64
foo_linux_arm_6
foo_linux_arm_7
foo_windows_386
foo_windows_amd64
```
This is the `target` format, not the `archive` format:
https://github.com/goreleaser/goreleaser/blob/master/internal/builders/golang/targets.go#L17

**Expected behavior**

I expect that the release files would still output in the specified template format:

```txt
foo_mac_amd64
foo_linux_386
foo_linux_amd64
foo_linux_arm64
foo_linux_arm6
foo_linux_arm7
foo_windows_386
foo_windows_amd64
```

Oddly, it looks like the default would actually do what I want:

- https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/archive/archive.go#L70

But it doesn't...

**Environment (please complete the following information):**

- OS: mac
- GoReleaser Version 

goreleaser version 0.143.0
commit: a92774f602331c53cd6b2c3c3ec8ec9058a26a7f
built at: 2020-09-06T14:53:58Z
built by: gorelease
