### ISSUE TITLE
proposal: move root changelog inside the release section

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1830]
currently its a bit confusing that it is in another section I think, as it makes no sense outside of the context of the release itself.

I propose to move it into the release, e.g.:

```yaml
release:
  changelog:
    # etc..
```

Thoughts?
