### ISSUE TITLE
Builds artefact are not uploaded on S3 (but archives are)

### ISSUE THREAD

**Issue by Tchoupinax** [goreleaser/goreleaser#1846]
**Describe the bug**

Using the blob section, i want to upload my build (targeting them with an "id". However, it does not work. When i try with uploading my archives, it works.

**To Reproduce**

```yaml
# I removed useless information to expose my issue
builds:
  - id: builds
    binary: myBin
    goos:
      - linux
      - windows
      - darwin
release:
  disable: true
archives:
  - id: archives
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
blobs:
  -
    provider: s3
    endpoint: xxxxxxx
    region: xxxxxxx
    bucket: xxxxxxx

    ids:
    - builds # builds are missing on my S3
    - archives # archives are present on my S3

    folder: "binaries/{{ .Date }}"
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

Complete configuration is valid !!

**Expected behavior**

For the moment, i just have archives artefact on my S3 bucket. I am expecting to have archives and *builds* artefacts (go binaries)

**Environment (please complete the following information):**

- OS: Docker container (FROM debian)
- OS version: Linux c3110e9ae4a3 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
- GoReleaser Version: goreleaser version 0.143.0 (installed with curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh)

Thank you !
