### ISSUE TITLE
Prevent checksums file from uploading

### ISSUE THREAD

**Issue by NorseGaud** [goreleaser/goreleaser#1847]
**Describe the bug**

```
builds:
  - id: builder
    binary: binary-name
    env:
      # Because we want to avoid coupling to system libraries.
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - id: zip
    builds:
      - builder
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: false
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

signs:
  - id: notarize-zip
    signature: "${artifact}.zip"
    cmd: gon
    args:
      - ".gon.hcl"
    artifacts: all
    ids:
      - builder

release:
  ids:
    - none
  extra_files:
    - glob: ./dist/*.zip
```

Using this yaml, I can notarize my zip/binary. However, the checksums file contents is then different from what the new signed/notarized .zip is.

There should be a way to disable the uploading of the checksums.txt file.
