### ISSUE TITLE
Add support for only building a subset of defined operating systems (GOOS) and architectures (GOARCH)

### ISSUE THREAD

**Issue by tjanez** [goreleaser/goreleaser#1852]
**Describe the solution you'd like**

I would like to be able to specify a subset of defined operating systems and/or architectures when doing a build, e.g. via `--os`/`--goos` or `--arch`/`--goarch` flags.

**Describe alternatives you've considered**

A possible alternative would be to allow specifying `goos` and/or` goarch` via environment variables, e.g. something like:

```yaml
builds:
  - ... trimmed ...
    goos:
      - "{{.Env.GOOS}}"
    goarch:
      - "{{.Env.GOARCH}}"
```

**Additional context**

The same thing was asked in https://github.com/goreleaser/goreleaser/discussions/1810.

A related idea also hinted at implementing `--goos` and `--goarch` flags: https://github.com/goreleaser/goreleaser/issues/1324#issuecomment-634257437.
