### ISSUE TITLE
release failed after 97.46s error=invalid archive

### ISSUE THREAD

**Issue by mrturkmencom** [goreleaser/goreleaser#1853]
**Describe the bug**

In Travis CI, goreleaser does not work as expected  I have been using goreleaser for a while and although I made couple of releases with it there was no problem, however today I started to face following annoying error, which has no more information, and there is no discussion about it as well. For this reason, I would like to open an issue for it, even if it is not a bug. It is good to have a solution here. 

![Screenshot 2020-10-13 at 15 16 10](https://user-images.githubusercontent.com/13614433/95866015-a66ebd80-0d67-11eb-92f6-c779b7aa34ad.png)

Note that, I have used same `.goreleaser.yml` file for other releases did not change something which is related to archiving name. 

**To Reproduce**

```yaml
# .goreleaser.yml
before:
  hooks:
    - go mod tidy
builds:
  # You can have multiple builds defined as a yaml list
  - # ID of the build.
    # Defaults to the project name.
    id: "hkn"

    # Path to main.go file or main package.
    # Default is `.`.
    main: ./client/main.go

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: hkn

    # Custom flags templates.
    # Default is empty.
    flags:
      - -tags=netgo

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{ .Version }} 

    # Custom environment variables to be set during the builds.
    # Default is empty.
    env:
      - CGO_ENABLED=0

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - windows
      - darwin
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
      - 386
  - id: "hknd"
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: hknd
    flags:
      - -tags=netgo
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
    goarch:
      - 386
      - amd64

archives:
  - # ID of this archive.
    # Defaults to `default`.
    id: app

    # Builds reference which build instances should be archived in this archive.
    builds:
      - hkn
      - hknd

    # Archive name template.
    # Defaults:
    # - if format is `tar.gz`, `gz` or `zip`:
    #   - `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    # - if format is `binary`:
    #   - `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Replacements for GOOS and GOARCH in the archive name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS

    # Set to true, if you want all files in the archive to be in a single directory.
    # If set to true and you extract the archive 'goreleaser_Linux_arm64.tar.gz',
    # you get a folder 'goreleaser_Linux_arm64'.
    # If set to false, all files are extracted separately.
    # You can also set it to a custom folder name (templating is supported).
    # Default is false.
    wrap_in_directory: true

    # Archive format. Valid options are `tar.gz`, `gz`, `zip` and `binary`.
    # If format is `binary`, no archives are created and the binaries are instead
    # uploaded directly.
    # Default is `tar.gz`.
    format: zip

    # Additional files/globs you want to add to the archive.
    # Defaults are any files matching `LICENCE*`, `LICENSE*`,
    # `README*` and `CHANGELOG*` (case-insensitive).
    files:
      - LICENSE
      - readme.md
      - dist/CHANGELOG.md

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "v_{{ .Version }}_{{ .ProjectName }}_checksums.txt"

  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256

brews:
  - tap:
      owner: <owner>
      name: <repo-name>
    folder: Formula
    homepage:  <homepage>
    description: CLI
    install: |
      bin.install "cli"
    test: |
      system "#{bin}/cli --help"

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

There should not be any error regarding to archiving things,  have used same .goreleaser.yml config file for other releases and there was no error at all. It triggered  me that there might be bug in recent release. 

**Environment (please complete the following information):**

- On TRAVIS CI

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.
