### ISSUE TITLE
Invalid goarch values are ignored

### ISSUE THREAD

**Issue by ahmetb** [goreleaser/goreleaser#1878]
**Describe the bug**

If you write a wrong `goarch:` field, it's simply ignored and no errors printed.

For example, I have `goarch: [i386, amd64]` and only `amd64` gets built –no errors are shown about i386 being a wrong GOARCH value

**To Reproduce**

```yaml
before:
  hooks:
  - go mod download
builds:
- main: .
  binary: grpc_health_probe
  flags:
  - -tags=netgo
  ldflags:
  - -w
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - "i386"
  - amd64
  - arm
  - arm64
  - ppc64le
  - s390x
  goarm: [6]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**It's valid**

**Expected behavior**

Expected to see an error.

**Environment (please complete the following information):**

- GoReleaser Version: 0.143.0
