### ISSUE TITLE
Using goreleaser behind a http(s) proxy

### ISSUE THREAD

**Issue by thiago** [goreleaser/goreleaser#1879]
**Describe the bug**

I'm using goreleaser to publish on gitlab behind a proxy. But the goreleaser is not using the proxy to call the gitlab endpoint.

I'm exporting `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy` and `https_proxy` and it is not working.

Looking the code and using the --debug flag, I can saw that most of commands are executed directly in the "terminal", like docker and git. But when will update the description of release page, goreleaser is calling it using a custom http transport ( https://github.com/goreleaser/goreleaser/blob/master/internal/client/gitlab.go#L30 ).

I think we need to use the `ProxyFromEnvironment` like the builtin `DefaultTransport RoundTripper`. Please, see https://golang.org/src/net/http/transport.go#L42

**To Reproduce**

```
export HTTP_PROXY=http://myproxy:3128
export HTTPS_PROXY=http://myproxy:3128
goreleaser
```

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
  - GOPRIVATE=gitlab.com/trsouz
before:
  hooks:
    - go mod download -x
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -w -s
      - -X {{.Env.GOPRIVATE}}/{{.ProjectName}}/version.GitCommit={{.ShortCommit}}
      - -X {{.Env.GOPRIVATE}}/{{.ProjectName}}/version.Version={{.Version}}
      - -X {{.Env.GOPRIVATE}}/{{.ProjectName}}/version.BuildTime={{.Date}}
      - -X {{.Env.GOPRIVATE}}/{{.ProjectName}}/version.OS={{.Os}}
      - -X {{.Env.GOPRIVATE}}/{{.ProjectName}}/version.Arch={{.Arch}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - image_templates:
      - registry.{{.Env.GOPRIVATE}}/{{.ProjectName}}:{{ .Tag }}
      - registry.{{.Env.GOPRIVATE}}/{{.ProjectName}}:v{{ .Major }}
      - registry.{{.Env.GOPRIVATE}}/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
changelog:
  sort: asc

  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

I expected that goreleaser uses the proxy to access external endpoints

**Environment (please complete the following information):**

- OS: `linux`
- OS version: `Linux runner-9by1bn8-project-21635938-concurrent-0d64t6 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 Linux`
- GoReleaser Version 
```
goreleaser version 0.146.0
commit: f629ac74edd09c2c6f59cb1b7473f199bb5b2231
built at: 2020-10-28T13:35:45Z
built by: goreleaser
```
- GitLab version: https://gitlab.com

**Additional context**

> release failed after 459.17s error=github/gitlab/gitea releases: failed to publish artifacts: Get "https://gitlab.com/api/v4/projects/trsouz%2Fzenimon/releases/v0.0.1": dial tcp 172.65.251.78:443: connect: connection timed out
