### ISSUE TITLE
Changelog empty in GitHub release

### ISSUE THREAD

**Issue by ccremer** [goreleaser/goreleaser#1896]
**Describe the bug**

Hi. Something seems off. We have just released a new [bugfix release](https://github.com/vshn/espejo/releases/tag/v0.3.2), which contains a few merged Pull requests, but the changelog is empty.

![image](https://user-images.githubusercontent.com/12159026/99065770-2d51c880-25a8-11eb-9c77-0acc75095308.png)

We have had added the `'^Merge pull request'` in the changelog exclude filter to not show the merge commits themselves, but we are expecting the individual commits within the Pull request to be listed. In previous releases this was all working as expected.

**To Reproduce**

From https://github.com/vshn/espejo/blob/dbf69ffe608d31df571f081e71943ca09ea6eabf/.goreleaser.yml

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  - arm
  - arm64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
- image_templates:
  - "docker.io/vshn/espejo:latest"
  - "docker.io/vshn/espejo:v{{ .Version }}"
  - "docker.io/vshn/espejo:v{{ .Major }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^Docs:'
    - '^Test:'
    - '^Refactor:'
    - '^Merge pull request'

release:
  github:
    owner: vshn
    name: espejo
  extra_files:
  - glob: ./espejo-crd.yaml
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

A changelog similar to [previsous release](https://github.com/vshn/espejo/releases/tag/v0.3.1). It shows the commits, even if they were in a Pull request, but the Merge commits themselves aren't displayed. No changes were made to .goreleaser.yaml

![image](https://user-images.githubusercontent.com/12159026/99065812-45c1e300-25a8-11eb-957b-e02578f7a9ea.png)

**Environment (please complete the following information):**

- OS: ubuntu-latest on GH action
- OS version: ubuntu-latest on GH action
- GoReleaser Version v0.147.0

**Additional context**

Goreleaser version for publishing previous release was v0.145.0, so maybe something changed there?
I searched the goreleaser release history, but could not find anything related to changelog feature.
