### ISSUE TITLE
Allow more flexible GOOS/GOARCH combinations

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#191]
I'm in the process of moving the Hugo builds from goxc/manual to Goreleaser. And we build for many OSes (because we can!) ... But the restrictions put in place by `goxc` isn't currently possible to express in Goreleaser config, I think. The following does neither build nor make sense:

```
  goos:
    - darwin
    - linux
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
  goarch:
    - amd64
    - 386
    - arm
    - arm64
```

Looking at the [goxc tests](https://github.com/laher/goxc/blob/f8fbb3b8c4df6c161348ae8a0047d562fcde8855/platforms/buildconstraints_test.go):

```
	"":                   "[{darwin 386} {darwin amd64} {linux 386} {linux amd64} {linux arm} {freebsd 386} {freebsd amd64} {openbsd 386} {openbsd amd64} {windows 386} {windows amd64}]",
```

The above may be too restrictive (It may make sense to build arm for more than Linux), but we need some way of adding some restrictions. I would be happy to submit a PR if we could agree on a way to express this.

**Comment by caarlos0** [comment]
yeah, I was thinking about it some days ago, maybe we should have only a `target` property or something like that in the format `goos-goarch` or something like that...

in this way, the user can specify what builds he want, but it'll be a little more verbose:

```yaml
  build:
    targets:
       - darwin-amd64
       - linux-arm64
       - etc
```

what do you think?

**Comment by caarlos0** [comment]
Another question: does it makes sense to have darwin 386 builds?

**Comment by bep** [comment]
> darwin 386 builds

Yes, that feels (almost) just as natural as having 386 Windows/Linux builds.

**Comment by bep** [comment]
```  
build:
    targets:
       - darwin-amd64
       - linux-arm64
       - etc
```

I think the idea is very good. But I suspect you will paint yourself into a corner with that magic "string pattern".

How about:

```
build:
    targets:
       darwin: 
          goarchs: 
            - amd64
         linux
            goarchs: 
              - amd64
              - arm

       - etc
```

I'm not sure the above is valid YAML, but you get my point.

**Comment by caarlos0** [comment]
Maybe for now we can do something simpler, just remove the invalid builds like goxc does.

We can achieve this very easy by changing https://github.com/goreleaser/goreleaser/blob/master/pipeline/build/valid_os.go

What do you think?

**Comment by bep** [comment]
>What do you think?

I think that is a good first step and covers my needs. And it avoids rushing into some ugly API ...

**Comment by caarlos0** [comment]
@bep yeah, we can think more about this meanwhile and maybe do a real good api some time ;)

**Comment by caarlos0** [comment]
@bep 

Assuming that we are already ignoring invalid combos, maybe it would make more sense to add a blacklist kind of option:

```yaml
build:
  goos:
    - linux
    - darwin
  goarch:
     - 386
     - amd64
   ignore:
     - goos: darwin
        goarch: 386
```

What do you think?
