### ISSUE TITLE
Docker builds fail "COPY failed: no source files were specified"

### ISSUE THREAD

**Issue by KeisukeYamashita** [goreleaser/goreleaser#1921]
**Describe the bug**

`goreleaser release` in my local mac and in the GitHub Actions workflow that uses the goreleaser-action always fail with `COPY failed: no source files were specified` error. 

When I run the same command that I can see in `goreleaser release --debug`, `docker build . -t KeisukeYamashita/sever:v0.0.1 --pull` it always fail. Running by `goreleaser release` fails.

**To Reproduce**

Create a any `main.go` with go module enabled.

Then, configure the Goreleaser.

```yaml
builds:
- main: ./cmd/server/main.go
  env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
dockers:
  - image_templates:
      - "KeisukeYamashita/server:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--build-arg=VERSION={{.Tag}}"
      - "--build-arg=COMMIT={{.ShortCommit}}"
      - "--build-arg=DATE={{.Date}}"
```

**Dockerfile**

```dockerfile
FROM golang:1.15.5

ARG VERSION
ARG COMMIT
ARG DATA

WORKDIR /project

RUN ls

COPY ./go.* ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go install -v \
            ./cmd/server/

# Build Docker with Only Server Binary
FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=0 /go/bin/registry /bin/server

RUN addgroup -g 1001 keke && adduser -D -G keke -u 1001 keke
USER 1001
CMD ["/bin/server"]
```

Then, run `goreleaser release --rm-dist` and it failed.

```
...
Step 7/20 : COPY ./go.* ./
COPY failed: no source files were specified
```

I didn't ignore these files. **.dockerignore**

```
/.git
/bin
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin PC2791 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
- GoReleaser Version version 0.147.2

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.
