### ISSUE TITLE
Option to exclude files from source archive

### ISSUE THREAD

**Issue by enamshah09** [goreleaser/goreleaser#1949]
**Is your feature request related to a problem? Please describe.**
With the source archive config can we add a section to exclude some files?
```
source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}'
  format: 'zip'
```

**Describe the solution you'd like**
Solution1: Add an exclude section as follows
```
source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}'
  format: 'zip'
  exclude:
     - "file1"
     - "file2"
```

Solution2: Have a pre and post section in global hooks
**Describe alternatives you've considered**
Tried to create a zip manually in the pre-hook section but it is like manually creating the zip file which is probably not a good idea
