### ISSUE TITLE
 gpg: signing failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by jbrunetext** [goreleaser/goreleaser#1966]
**Describe the bug**

i try to sign my artifacts  with goreleaser but i faced an issue with step signing artifacts

**To Reproduce**

.goreleaser.yaml
```yaml
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
- env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
#    - freebsd
#    - windows
    - linux
#    - darwin
  goarch:
    - amd64
#   - '386'
#    - arm
#    - arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
```

```yaml
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**

sign that artefact

**Environment (please complete the following information):**

- OS: [linux]
- OS version: ubuntu-latest
- GoReleaser Version 0.149.0
- Github action

**Additional context**
```
  • building binaries
      • building                  binary=/home/runner/work/terraform-provider-hashicup/terraform-provider-hashicup/dist/terraform-provider-hashicup_linux_amd64/terraform-provider-hashicup_v0.0.1
   • archives         
      • creating                  archive=dist/terraform-provider-hashicup_0.0.1_linux_amd64.zip
   • creating source archive
      • pipe skipped              error=source pipe is disabled
   • linux packages   
   • snapcraft packages
   • calculating checksums
      • checksumming              file=terraform-provider-hashicup_0.0.1_linux_amd64.zip
   • signing artifacts
      • signing                   cmd=[gpg --batch -u 9F3A7CC5AC1F7BA9C534DD5EXXXXXXXXXXXXXXXX --output dist/terraform-provider-hashicup_0.0.1_SHA256SUMS.sig --detach-sign dist/terraform-provider-hashicup_0.0.1_SHA256SUMS]
      • gpg: signing failed: Inappropriate ioctl for device
 cmd=gpg
      • gpg: signing failed: Inappropriate ioctl for device
 cmd=gpg
   ⨯ release failed after 38.41s error=sign: gpg failed
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.149.0/x64/goreleaser' failed with exit code 1
```
