### ISSUE TITLE
multi-arch docker won't build for non-native arch when using scratch.

### ISSUE THREAD

**Issue by koshatul** [goreleaser/goreleaser#1967]
**Describe the bug**

When attempting to build multi-arch docker images, `scratch` can't be used.

**To Reproduce**

build binary and then attempt to use `FROM scratch` in the Dockerfile:

```yaml
before:
  hooks:
    - make test

builds:
  - id: traefik-acme
    main: ./cmd/traefik-acme
    binary: traefik-acme
    targets:
      - linux_amd64
      - darwin_amd64
      - linux_arm_5
      - linux_arm_7
      - linux_arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--build-arg=PLATFORM=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-amd64"
    - "koshatul/traefik-acme:v{{ .Major }}-amd64"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-amd64"
  -
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--build-arg=PLATFORM=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-arm64v8"
    - "koshatul/traefik-acme:v{{ .Major }}-arm64v8"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-arm64v8"
  -
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--build-arg=PLATFORM=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-armv7"
    - "koshatul/traefik-acme:v{{ .Major }}-armv7"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-armv7"

docker_manifests:
  - name_template: koshatul/traefik-acme:v{{ .Major }}
    image_templates:
    - koshatul/traefik-acme:v{{ .Major }}-amd64
    - koshatul/traefik-acme:v{{ .Major }}-armv7
    - koshatul/traefik-acme:v{{ .Major }}-arm64v8
  - name_template: koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}
    image_templates:
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-amd64
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-armv7
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: koshatul/traefik-acme:latest
    image_templates:
    - koshatul/traefik-acme:latest-amd64
    - koshatul/traefik-acme:latest-armv7
    - koshatul/traefik-acme:latest-arm64v8
```

```Dockerfile
FROM scratch
COPY traefik-acme /
ENTRYPOINT [ "/traefik-acme" ]
```

**Expected behavior**

`docker build` command would be supplied the `--platform` argument to specify platform.

**Environment (please complete the following information):**

- OS: macOS, linux and github actions.
- GoReleaser Version 0.149.0

**Additional context**

Because `docker build` treats `FROM scratch` as a no-op, so `FROM --platform=linux/arm/7 scratch` does nothing, this works in case where you're not using scratch because the `FROM --platform=linux/arm/7 alpine:3.12` will pull an alpine:3.12 image that has already got the architecture set, so that is inherited.

The fix is probably to add a `platform` option to the `dockers` config so it can be specified if required, I can do a PR for this.

**Comment by caarlos0** [comment]
Pretty sure you can change your config to:

```yaml
before:
  hooks:
    - make test

builds:
  - id: traefik-acme
    main: ./cmd/traefik-acme
    binary: traefik-acme
    targets:
      - linux_amd64
      - darwin_amd64
      - linux_arm_5
      - linux_arm_7
      - linux_arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-amd64"
    - "koshatul/traefik-acme:v{{ .Major }}-amd64"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-amd64"
  -
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-arm64v8"
    - "koshatul/traefik-acme:v{{ .Major }}-arm64v8"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-arm64v8"
  -
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    binaries:
    - traefik-acme
    builds:
    - traefik-acme
    build_flag_templates:
    - "--platform=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    image_templates:
    - "koshatul/traefik-acme:latest-armv7"
    - "koshatul/traefik-acme:v{{ .Major }}-armv7"
    - "koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-armv7"

docker_manifests:
  - name_template: koshatul/traefik-acme:v{{ .Major }}
    image_templates:
    - koshatul/traefik-acme:v{{ .Major }}-amd64
    - koshatul/traefik-acme:v{{ .Major }}-armv7
    - koshatul/traefik-acme:v{{ .Major }}-arm64v8
  - name_template: koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}
    image_templates:
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-amd64
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-armv7
    - koshatul/traefik-acme:v{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: koshatul/traefik-acme:latest
    image_templates:
    - koshatul/traefik-acme:latest-amd64
    - koshatul/traefik-acme:latest-armv7
    - koshatul/traefik-acme:latest-arm64v8
```

and it should work.

> basically passing `--platform` in `build_flag_templates`.

GoReleaser doesn't translate goos/goarch/etc to docker platform names yet.
