### ISSUE TITLE
Empty image tag template fails docker build

### ISSUE THREAD

**Issue by ccremer** [goreleaser/goreleaser#1969]
**Describe the bug**

A .goreleaser.yml with an empty element in `dockers[*].image_templates` results in Goreleaser adding a docker --tag argument with an empty value.

**To Reproduce**

```yaml
builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux
dockers:
- image_templates:
  - "{{ if not .Prerelease }}docker.io/ccremer/clustercode:latest{{ end }}"
```
1. Make a prerelease Semver git tag  (e.g. `1.0.0-rc1`) on the latest commit
1. goreleaser release --rm-dist --skip-publish

Log excerpt:
```console
   • docker images    
      • building docker image     image=
   ⨯ release failed after 10.18s error=failed to build docker image: : 
invalid argument "" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
: exit status 125
```
(which is basically the same as `docker build . --tag .`

**Expected behavior**

* An empty image template should not be passed to docker build
* It should also not be listed in the Release on GitHub

**Environment (please complete the following information):**

- OS: linux
- OS version: 4.15.0-20-generic #21-Ubuntu
- GoReleaser version 0.149.0

**Additional context**

In my project, I want to build and push pre-releases to docker Hub and quay.io. However, for "real" releases I also want to push a `latest` tag so that it points to the latest stable release (and not to a pre-release).

A hack is to do magic like:
```
dockers:
- image_templates:
  - "docker.io/ccremer/clustercode:{{ if .Prerelease }}v{{ .Version }}{{ else }}latest{{ end }}"
  - "docker.io/ccremer/clustercode:v{{ .Version }}"
```
However, the hack will also display the same image tags twice in the Prerelease on GitHub
