### ISSUE TITLE
HTTP Upload hard-coded to require user & password

### ISSUE THREAD

**Issue by tomastzn** [goreleaser/goreleaser#2008]
**Describe the bug**

The documentation of HTTP Upload say that user and password are used if server requires it, yet it does fail without them. I have a local server that does not require authentication but I need to provide bogus values for user name and password anyway to make this work.

**To Reproduce**
Just using very simple configuration:
```yaml
uploads:
  - name: agent
    mode: archive
    target: http://uploader.local:9000/upload/{{ .ProjectName }}/{{ .Version }}
    checksum_header: X-SHA256-Sum
```
With the above configuration, the build process(running in local Gitlab CI runner) outputs:
```
      • http upload      
         • pipe skipped              error=upload section 'agent' is not configured properly (missing username or UPLOAD_AGENT_USERNAME environment variable)
```
**Expected behavior**

The HTTP Upload should be able to function without requiring user name and password. (a nice enhancement would be to support different types of values for authorization header, but that's for another issue).

**Environment (please complete the following information):**

- OS: [linux]
- OS version: [Ubuntu 20.04 server amd64]
- GoReleaser Version [0.154.0]
- GitLab version (13.7.1)
