### ISSUE TITLE
Add a release-notes-string option to release subcommand

### ISSUE THREAD

**Issue by daonb** [goreleaser/goreleaser#2014]
**Is your feature request related to a problem? Please describe.**
I have a CHANGELOG.md in my project and I want to get the release-notes from this file. As I'm using a github workflow, I found a flow "mindsers/changelog-reader-action@v2" that gets the notes from my project's well-formatted CHANGLEOG.md.  My Problem is that I get the notes as a string and goreleaser expect a file path in `--release-notes`.

**Describe the solution you'd like**
I want to be able to pass an argument with the release notes as it's value. e.g. `goreleaser release --release-notes-md "Release note....."` 

**Additional context**

Here's my current, failing, workflow where I try to create a file and echo in the string I go from CHANGELOG.md:

```
name: Release
on: 
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run:   echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Save ChangeLog to file
        id: save_changes
        run: |
          echo ::set-output name=changesfile::$(mktemp)
          echo "${{ steps.changelog_reader.outputs.changes }}" ${{ steps.save_changes.outputs.changesfile }}
        shell: bash
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args:
            release --rm-dist --release-notes ${{ steps.save_changes.outputs.changesfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
```

**Comment by caarlos0** [comment]
```
 echo "${{ steps.changelog_reader.outputs.changes }}" ${{ steps.save_changes.outputs.changesfile }}
```
shouldn't this be

```
 echo "${{ steps.changelog_reader.outputs.changes }}" > ${{ steps.save_changes.outputs.changesfile }}
```

?

**Comment by daonb** [comment]
Thanks and sorry about that. Guess I've been down this rabbit hole for too long.

I eventually got it working , changing the save_changes stage to:

```yaml
      - name: Save ChangeLog to file
        id: save_changes
        run: |
          export CF=$(mktemp)
          echo ::set-output name=changesfile::$CF
          echo "${{ steps.changelog_reader.outputs.changes }}" > $CF
        shell: bash

```

It works, but it's not elegant and I think goreleaser can support this common scenario better.  A cleaner interface will be for the  --release-notes to accept a string rather than a  file path. Strings are much easier to integrate and if you do need to read it from a file you can just pss in `$(cat <file>)`. 

Thinking some more, the cleanest way will be to change the github action so that I can add `release-notes: ${{...}}}` in the goreleaser step.

I'd be happy to help - If you like  either improvement let me know and I'll code it. If not, please close the issue.
