### ISSUE TITLE
"blobs" pipe does not upload expected artefacts to Google Cloud Storage if ids are specified

### ISSUE THREAD

**Issue by dkleuser** [goreleaser/goreleaser#2020]
**Describe the bug**

First of all: Thanks for creating this great tool, I really enjoy working with it and its well-thought capabilities.
 
I created a config that builds a Go project for Linux and other operating systems in two individual steps because only the Linux binary needs to be packaged in multiple formats (deb, rpm, Docker image) while the archives for Windows and macOS should just be uploaded to a Google Cloud Storage bucket. Based on the format different targets for uploading are required, this works fine for almost all steps by specifying one or multiple id(s). For example, my defined custom publishers are only uploading the resulting artefact of the specified id as expected.
But when specifying `ids` in the `blobs` configuration section, only the checksums file is being uploaded even though all artefacts are built and other steps do uploads based on an id. As soon as I remove the `ids` property, all artefacts (archives and Linux packages) are being uploaded to GCS bucket, which makes sense, but I only want the archives to be placed there.

Am I doing something wrong here?
Please let me know if you need additional information.

**To Reproduce**

Steps to reproduce the behaviour:

```yaml
project_name:  [REDACTED]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  -
    id: linux
    env:
      - GOPRIVATE= [REDACTED]
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - -X main.Version={{.Version}}

  -
    id: other
    env:
      - GOPRIVATE= [REDACTED]
    goarch:
      - amd64
    goos:
      - windows
      - darwin
    ldflags:
      - -X main.Version={{.Version}}

archives:
  -
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows-EXPERIMENTAL
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

blobs:
  -
    ids:
      - linux
      - other
    provider: gs
    bucket:  [REDACTED]


dockers:
  -
    ids:
      - linux
    goos: linux
    goarch: amd64
    image_templates:
      - " [REDACTED]"

nfpms:
  -
    id: deb
    builds:
      - linux
     [REDACTED]

  -
    id: rpm
    builds:
      - linux
    [REDACTED]

publishers:
  - name: artifactory-deb
    env:
      - CI=true
    ids:
      - deb
    cmd: "jfrog rt upload [REDACTED]"
  - name: artifactory-rpm
    env:
      - CI=true
    ids:
      - rpm
    cmd: "jfrog rt upload  [REDACTED]"

release:
  disable: true

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

```
goreleaser check -f .goreleaser.yml
   • loading config file       file=.goreleaser.yml
   • checking config:
      • snapshotting
      • github/gitlab/gitea releases
      • project name
      • building binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images
      • artifactory
      • blobs
      • homebrew tap formula
      • scoop manifests
      • milestones
   • config is valid
```

**Expected behavior**

Only the artefacts from the specified build ids are being uploaded to the blob storage.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] mac 
- OS version: [uname -a] 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
- GoReleaser Version [goreleaser --version] 0.154.0
- GitLab version (if using a private hosted one) n.a.

**Comment by patricksanders** [comment]
I'm also seeing this issue when trying to upload blobs to S3.

**Comment by caarlos0** [comment]
Haven't looked into it yet, PRs accepted if anyone has some free time.

**Comment by patricksanders** [comment]
I figured out my issue. `blobs.ids` appears to refer to an _archive_ ID, not a _build_ ID.

```yaml
archives:
  -
    builds:
      - default
    id: default
    format: tar.gz
  -
    builds:
      - demo
    id: demo
    format: binary
    name_template: "{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}/{{ .Binary }}"
blobs:
  -
    provider: s3
    ids:
      - demo
    bucket: [snip]
    region: us-west-2
    folder: [snip]
```

This configuration successfully uploads all of the binaries from the `demo` archive and skips the tar.gz uploads from the `default` archive.
