### ISSUE TITLE
map has no entry for key "Os"

### ISSUE THREAD

**Issue by azr** [goreleaser/goreleaser#2029]
**Describe the bug**

The Os ( and maybe Arch ? ) fields can't be accessed 

related: #2021, https://github.com/goreleaser/goreleaser/pull/1936

**To Reproduce**

Tag a release

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go test ./...

    # You may remove this if you generate these on your own
    - go install github.com/hashicorp/packer/cmd/mapstructure-to-hcl2
    - go generate ./...

    # Install packer-plugins-check to check binary compatibility with Packer
    - go install github.com/hashicorp/packer/cmd/packer-plugins-check

builds:
  # A separated build to run the packer-plugins-check only once for a linux_amd64 binary
  -
    id: plugin-check
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        # This will check plugin compatibility by making sure packer can load the binary
        - cmd: packer-plugins-check -load={{ .Name }}
          dir: "{{ dir .Path}}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.VersionPrerelease= '
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}_x5'
  - 
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'  ## can be useful to set variables 
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}_x5'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}_x5'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}_x5_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this is in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
```

**Expected behavior**

A release without an error

**Environment (please complete the following information):**

Its an action running on linux.

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- GoReleaser Version latest ( ✅ GoReleaser version found: v0.155.0 )
GH Action file:

```
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
