### ISSUE TITLE
bug: failed to build for darwin_arm64

### ISSUE THREAD

**Issue by mr-karan** [goreleaser/goreleaser#2066]
**Describe the bug**

While using `goreleaser` (config file below), I started to get this error since yesterday:

```
   • building binaries
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_linux_arm64/doggo
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_darwin_amd64/doggo
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_windows_amd64/doggo.exe
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_linux_amd64/doggo
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_darwin_arm64/doggo
   ⨯ release failed after 50.68s error=failed to build for darwin_arm64: # github.com/mr-karan/doggo/cmd/doggo
/opt/hostedtoolcache/go/1.15.8/x64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-445048011/go.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status


Error: The process '/opt/hostedtoolcache/goreleaser-action/0.156.2/x64/goreleaser' failed with exit code 1
```
**To Reproduce**

```yaml
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: doggo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/doggo/
```

**Expected behavior**

Last I tried this was on `goreleaser 0.155.2` which worked without issues (it automatically skipped the invalid platform I think):

```
   • building binaries
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_linux_arm64/doggo
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_darwin_amd64/doggo
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_linux_amd64/doggo
      • building                  binary=/home/runner/work/doggo/doggo/dist/doggo_windows_amd64/doggo.exe
```

**Environment (please complete the following information):**

- OS: linux
- OS version: ubuntu:20.04
- GoReleaser Version 0.156.2

**Additional context**
Github Actions log which failed: https://github.com/mr-karan/doggo/runs/1924185133?check_suite_focus=true
Github Actions log which worked: https://github.com/mr-karan/doggo/runs/1900666627?check_suite_focus=true
