### ISSUE TITLE
NFPMS build fails on windows

### ISSUE THREAD

**Issue by Niondir** [goreleaser/goreleaser#2068]
**Describe the bug**

On windows the build fails with:

` release failed after 9.09s error=invalid nfpm config: matching "C:devgopathsrcgithub.comlobaromy-projectbuildmy-project_linux_amd64my-project": file does not exist
`

**To Reproduce**

```yaml
nfpms:
  - id: default
    builds:
      - my-project
    formats:
      - deb
```

**Additional context**
Works in CI on linux
