### ISSUE TITLE
darmin/arm64 M1 build ignored from matrix?

### ISSUE THREAD

**Issue by andig** [goreleaser/goreleaser#2073]
**Describe the bug**

I'm running goreleaser on go1.16 and expect darwin-arm64 build to be included.

**To Reproduce**

```yaml
dist: goreleaser
release:
  github:
    owner: andig
    name: evcc
  extra_files:
  - glob: evcc_*.image.gz
  - glob: evcc_*.rootfs.gz
builds:
- id: evcc
  main: main.go
  flags:
  - -tags=release
  ldflags:
  - -X github.com/andig/evcc/server.Version={{.Version}} -X github.com/andig/evcc/server.Commit={{.ShortCommit}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
archives:
- builds:
  - evcc
  replacements:
    darwin: macOS
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - evcc.dist.yaml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^chore'
    - '^bump'
    - '^docs:'
    - '^test:'
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

Valid.

**Expected behavior**

Have darwin-arm64 build included.

**Environment (please complete the following information):**

- OS: `Mac
- OS version: `Darwin AndiMacPro 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`
- GoReleaser Version:
```
❯ bin/goreleaser --version                 
goreleaser version 0.157.0
commit: 0a16e2123647fbbf4e996a737ab1b3f96b4ab63f
built at: 2021-02-18T18:06:57Z
built by: goreleaser
```

**Additional context**

Here's what I'm seeing:

    ❯ goreleaser build --snapshot --rm-dist
    • building...      
    • loading config file       file=.goreleaser.yml
    • loading environment variables
    • getting and validating git state
        • releasing 0.46, commit 5e07db3b94f648b2b3242542719a9592b2ca9a19
        • pipe skipped              error=disabled during snapshot mode
    ...
    • building binaries
        • building                  binary=/Users/andig/htdocs/evcc/goreleaser/evcc_windows_amd64/evcc.exe
        • building                  binary=/Users/andig/htdocs/evcc/goreleaser/evcc_linux_amd64/evcc
        • building                  binary=/Users/andig/htdocs/evcc/goreleaser/evcc_linux_arm64/evcc
        • building                  binary=/Users/andig/htdocs/evcc/goreleaser/evcc_linux_arm_6/evcc
        • building                  binary=/Users/andig/htdocs/evcc/goreleaser/evcc_darwin_amd64/evcc
