### ISSUE TITLE
Releasing to private hosted gitlab with nested groups results in a target is invalid  error

### ISSUE THREAD

**Issue by mvanholsteijn** [goreleaser/goreleaser#2077]
**Describe the bug**

When releasing to gitlab to a project in the group infra/terraform/providers, the upload fails with the following error:

```
 ⨯ release failed after 10.91s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://gitlab.binx.io/api/v4/projects/infra/terraform/providers/terraform-provider-sentry/releases: 400 {message: Target fe6538b9c07686cdead134f54db22d70d83df746 is invalid}
```

**To Reproduce**

```yaml
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  #draft: true
  gitlab:
    owner: infra/terraform/providers
    name: terraform-provider-sentry
changelog:
  skip: true
gitlab_urls:
  api: https://gitlab.binx.io/api/v4/
  download: https://gitlab.binx.io

```

**Expected behavior**

The binaries to be uploaded :-)

**Environment (please complete the following information):**

```yaml
OS: Mac
OS version:  n/a
GoReleaser Version: 
  commit: a69839327f0015ebb0990d41a6fa73b880de2873 
  built at: 2020-12-01T00:53:47Z
GitLab version: 13.6.1-ee
```
