### ISSUE TITLE
Deb uninstallable with error: version number does not start with a digit

### ISSUE THREAD

**Issue by alephnull** [goreleaser/goreleaser#2081]
**Describe the bug**
_Sometimes_ deb files have non-compliant versions in them. This appears to be a re-occurance of nfpm#9. I have other repos which almost identical `nfpms` configurations where this problem does not occur.

**To Reproduce**

Config to reproduce:
```yaml
nfpms:
  - id: std
    vendor: "Tyk Technologies Ltd"
    homepage: "https://tyk.io"
    maintainer: "Tyk <info@tyk.io>"
    description: Archive analytics for the Tyk API gateway
    package_name: tyk-pump
    version_metadata: git
    builds:
      - std-linux
      - std-arm64
    formats:
      - deb
      - rpm
    contents:
      - src: "README.md"
        dst: "/opt/share/docs/tyk-pump/README.md"

      - src: "LICENSE.md"
        dst: "/opt/share/docs/tyk-pump/LICENSE.md"
      - src: "install/*"
        dst: "/opt/tyk-pump/install"
      - src: pump.example.conf
        dst: /opt/tyk-pump/pump.conf
        type: "config|noreplace"
    scripts:
      preinstall: "install/before_install.sh"
      postinstall: "install/post_install.sh"
      postremove: "install/post_remove.sh"
    bindir: "/opt/tyk-pump"
    overrides:
      rpm:
        replacements:
          amd64: x86_64
          arm: aarch64
      deb:
        replacements:
          arm: arm64
    rpm:
      signature:
        key_file: tyk.io.signing.key
    deb:
      signature:
        key_file: tyk.io.signing.key
        type: origin
```

```yaml
your goreleaser config file
```

> `goreleaser check -f path-to-config-file`.
```
   • loading config file       file=.goreleaser.yml
   • checking config: 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • config is valid  
```

**Expected behavior**

The deb file is installable.

**Environment (please complete the following information):**

- OS: linux 
- OS version: Linux gauss 5.8.0-34-generic #37-Ubuntu SMP Thu Dec 10 18:01:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser Version: goreleaser version 0.157.0
commit: 0a16e2123647fbbf4e996a737ab1b3f96b4ab63f
built at: 2021-02-18T18:06:57Z
built by: goreleaser
- GitLab version (if using a private hosted one): NA

**Additional context**
Here's the full debug log of the nfpm section
```
   • linux packages           
      • adding binary to package  arch=arm64 dst=/opt/tyk-pump/tyk-pump package=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.rpm src=/go/src/github.com/TykTechnologies/tyk-pump/dist/std-arm64_linux_arm64/tyk-pump
      • all archive files         files=[/opt/share/docs/tyk-pump/README.md /opt/share/docs/tyk-pump/LICENSE.md /opt/tyk-pump/install /opt/tyk-pump/pump.conf /opt/tyk-pump/tyk-pump]
      • adding binary to package  arch=amd64 dst=/opt/tyk-pump/tyk-pump package=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_x86_64.rpm src=/go/src/github.com/TykTechnologies/tyk-pump/dist/std-linux_linux_amd64/tyk-pump
      • all archive files         files=[/opt/share/docs/tyk-pump/README.md /opt/share/docs/tyk-pump/LICENSE.md /opt/tyk-pump/install /opt/tyk-pump/pump.conf /opt/tyk-pump/tyk-pump]
      • adding binary to package  arch=arm64 dst=/opt/tyk-pump/tyk-pump package=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.deb src=/go/src/github.com/TykTechnologies/tyk-pump/dist/std-arm64_linux_arm64/tyk-pump
      • all archive files         files=[/opt/share/docs/tyk-pump/README.md /opt/share/docs/tyk-pump/LICENSE.md /opt/tyk-pump/install /opt/tyk-pump/pump.conf /opt/tyk-pump/tyk-pump]
      • adding binary to package  arch=amd64 dst=/opt/tyk-pump/tyk-pump package=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_amd64.deb src=/go/src/github.com/TykTechnologies/tyk-pump/dist/std-linux_linux_amd64/tyk-pump
      • all archive files         files=[/opt/share/docs/tyk-pump/README.md /opt/share/docs/tyk-pump/LICENSE.md /opt/tyk-pump/install /opt/tyk-pump/pump.conf /opt/tyk-pump/tyk-pump]
      • creating                  file=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.rpm
      • creating                  file=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.deb
      • creating                  file=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_x86_64.rpm
      • creating                  file=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_amd64.deb
      • added new artifact        name=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.deb path=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.deb type=Linux Package
      • added new artifact        name=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_amd64.deb path=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_amd64.deb type=Linux Package
      • added new artifact        name=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.rpm path=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_arm64.rpm type=Linux Package
      • added new artifact        name=tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_x86_64.rpm path=dist/tyk-pump_v0.8.5.1-SNAPSHOT-ecb6104_linux_x86_64.rpm type=Linux Package
```
