### ISSUE TITLE
Missing GitHub builds on release

### ISSUE THREAD

**Issue by hazcod** [goreleaser/goreleaser#2093]
**Is your feature request related to a problem? Please describe.**
My current goreleaser schedule no longer attaches builds to my GitHub build.
e.g. https://github.com/hazcod/intigriti-slack-announce/runs/2047107449?check_suite_focus=true

**Describe the solution you'd like**
Builds being uploaded to the created GitHub release.

**Additional context**

**goreleaser.yml**:
```yaml
before:
  hooks:
    - go mod download

builds:
-
  binary: isa
  env:
  - CGO_ENABLED=0
  ldflags:
  - -w -s -extldflags "-static"
  dir: ./cmd
  goos:
  - darwin
  - linux
  - windows
  - freebsd

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
```

**GitHub Action**:
```yaml
name: goreleaser

on:
  push:
    master:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        uses: go-semantic-release/action@v1
        id: semantic
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: .changelog
      -
        name: Set up Go
        uses: actions/setup-go@v2.1.3
        if: steps.semantic.outputs.version != ''
      -
        name: Release
        uses: goreleaser/goreleaser-action@v2
        if: steps.semantic.outputs.version != ''
        with:
          version: latest
          args: release --config=.github/goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
