### ISSUE TITLE
nfpm `package_name` isn't used in deb file name

### ISSUE THREAD

**Issue by eriksw** [goreleaser/goreleaser#2095]
**Describe the bug**

Setting the `package_name` option doesn't affect the file name of the produced`.deb` file.

The package has the correct `Package: ...` in its control tarball, but it's a nontrivial violation of end-user expectations for a `.deb` to have a filename that has no relation to the actual package name.

**To Reproduce**

(For context, I encountered this while trying to prepare a PR to make [apt-gcs](https://github.com/dhaivat/apt-gcs) have built packages.)

```yaml
before:
  hooks:
    - go mod tidy
builds:
  - id: gs
    binary: gs
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
    ldflags:
      - -s -w
    main: ./cmd/main.go
nfpms:
  - package_name: apt-transport-gs
    builds:
      - gs
    maintainer: https://github.com/dhaivat/apt-gcs
    homepage: https://github.com/dhaivat/apt-gcs
    license: MIT
    formats:
      - deb
    bindir: /usr/lib/apt/methods
archives:
  - format: binary
checksum:
  disable: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

**Expected behavior**

Produces deb packages named like `apt-transport-gcs_[...].deb`

**Actual behavior**

```
➜  dist git:(master) ✗ ls *.deb | sort
apt-gcs_v0.0.0-SNAPSHOT-6e5a477_linux_386.deb
apt-gcs_v0.0.0-SNAPSHOT-6e5a477_linux_amd64.deb
apt-gcs_v0.0.0-SNAPSHOT-6e5a477_linux_arm64.deb
```

Note that the `Package:` is correct. Again, the issue is that the package does not match the filename:
```
➜  dist git:(master) ✗ ar x apt-gcs_v0.0.0-SNAPSHOT-6e5a477_linux_amd64.deb
➜  dist git:(master) ✗ tar xzvf control.tar.gz
x ./md5sums
x ./conffiles
x ./control
➜  dist git:(master) ✗ cat control
Package: apt-transport-gs
Version: 0.0.0~SNAPSHOT-6e5a477
Section:
Priority:
Architecture: amd64
Maintainer: https://github.com/dhaivat/apt-gcs
Installed-Size: 9144
Homepage: https://github.com/dhaivat/apt-gcs
Description: no description given
```

**Environment (please complete the following information):**

- OS: MacOS
- OS version: `Darwin [...] 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`
- GoReleaser Version `0.159.0` (via homebrew)

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.
