### ISSUE TITLE
nfpm: package architecture (mipshardfloat) does not match system (mips)

### ISSUE THREAD

**Issue by dmke** [goreleaser/goreleaser#2121]
**Describe the bug**

I'm trying to build and install a package on an EdgeRouter Lite. That system runs EdgeOS 2.0.x (derived from Debian 9) on an Cavium Octeon+ chip (MIPS64).

While `dpkg --print-architecture` just prints "mips", I can run binaries with built `GOARCH=mips` and `GOARCH=mips64`.

The `.deb` packages however cannot be installed:

```console
$ goreleaser release --skip-publish --rm-dist
$ scp dist/ping_exporter_0.4.5-1digineo0_linux_mips.deb  ubnt@172.16.1.87:/tmp/
$ ssh ubnt@172.16.1.87
$ sudo dpkg -i /tmp/ping_exporter_0.4.5-1digineo0_linux_mips.deb
dpkg: error processing archive /tmp/ping_exporter_0.4.5-1digineo0_linux_mips.deb (--install):
 package architecture (mipshardfloat) does not match system (mips)
Errors were encountered while processing:
 /tmp/ping_exporter_0.4.5-1digineo0_linux_mips.deb
```

**To Reproduce**

This is a condensed version of the [current work-in-progress `.goreleaser.yml`](https://github.com/digineo/ping_exporter/blob/erlite/.goreleaser.yml). I assume, this is pretty standard.

```yaml
builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [mips, mips64]
    gomips: [hardfloat]
nfpms:
  - # vendor/homepage/description omitted for brevity
    formats: [deb]
    file_name_template: 'default+{{ if eq .Mips "softfloat" }}sf{{ end }}'
```

The `.deb` file contains the following `control` file (some fields omitted):

```
Package: ping_exporter
Version: 0.4.5~1digineo0
Architecture: mipshardfloat
```

**Expected behavior**

As far as I can tell, there is no "mipshardfloat" architecture [anywhere in Debian](http://ftp.debian.org/debian/dists/stretch/main/), only "mips" (and "mipsel", "mips64el", but not "mips64").

**Environment (please complete the following information):**

- OS: Ubiquiti EdgeOS
- OS version: `Linux ubnt 4.9.79-UBNT #1 SMP Fri Jan 22 10:17:01 UTC 2021 mips64 GNU/Linux`
- GoReleaser Version: 0.155.0

**Additional context**

I'm not willing to run something like `dpkg --add-architecture mipshardfloat`, because the EdgeOS software is not the greatest software in the world, and Ubiquiti did some pretty horrific things to Debian (or Vyatta/VyOS, whatever the actual lineage is...). Adding an architecture might break that system.
