### ISSUE TITLE
Docker manifests does not work well when pushing tag like "latest"

### ISSUE THREAD

**Issue by cevian** [goreleaser/goreleaser#2127]
**Describe the bug**

Currently new images are amended (--amend) to the manifests. For manifests like "latest " this means both old and new versions end up in the latest manifest.

**To Reproduce**

a docker_manifests config like

```
docker_manifests:
- name_template: 'timescale/promscale:{{ .Tag }}'
  image_templates:
  - 'timescale/promscale:{{ .Tag }}-amd64'
  - 'timescale/promscale:{{ .Tag }}-arm64'
- name_template: 'timescale/promscale:{{ .Major }}.{{ .Minor }}'
  image_templates:
  - 'timescale/promscale:{{ .Tag }}-amd64'
  - 'timescale/promscale:{{ .Tag }}-arm64'
- name_template: 'timescale/promscale:latest'
  image_templates:
  - 'timescale/promscale:{{ .Tag }}-amd64'
  - 'timescale/promscale:{{ .Tag }}-arm64
 ```

**Expected behavior**

Expect latest manifest to have only 2 images, but has 4 (2 from previous version)

**Possible solution**
- run `docker manifest rm`
- don't amend but set (not sure it's possible)
