### ISSUE TITLE
windows/arm should not be ignored.

### ISSUE THREAD

**Issue by axetroy** [goreleaser/goreleaser#2143]
**Describe the bug**

I have described building `windows/arm` in the configuration file but it will not actually be built.

**To Reproduce**

```yaml
builds:
  - binary: watchdog
    main: ./cmd/watchdog/main.go
    goos:
      - windows
      - darwin
      - linux
      - openbsd
      - freebsd
      - netbsd
      - plan9
      - solaris
      - illumos
      - dragonfly
      - aix
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - s390x
      - ppc64
      - ppc64le
      - riscv64
      - mips
      - mips64
      - mipsle
      - mips64le
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath

archives:
  - files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

```

> Make sure your config file is valid by running

```bash
goreleaser check -f .goreleaser.yml
   • loading config file       file=.goreleaser.yml
   • checking config: 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • config is valid 
```

**Expected behavior**

`windows/arm ` and `darwin/arm` should not be ignored.

**I can build windows/arm normally with the `go build` command**

```bash
GOOS=windows GOARCH=arm go build -o dist/watchdog.exe cmd/watchdog/main.go
```

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin axetroydeMacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- GoReleaser Version: 0.161.1
- GitLab version (if using a private hosted one)

**Additional context**

build log: https://github.com/axetroy/watchdog/runs/2212058440
