### ISSUE TITLE
Gitlab release failed to upload 

### ISSUE THREAD

**Issue by tfournier** [goreleaser/goreleaser#2151]
**Describe the bug**

```shell
   • releasing...
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v0.1.0, commit 1b8946116c1bc3634026f02fa7ec05accec00627
   • parsing tag
   • running before hooks
      • running go mod download
   • setting defaults
      • snapshotting
      • github/gitlab/gitea releases
      • project name
      • building binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images
      • artifactory
      • blobs
      • homebrew tap formula
      • scoop manifests
      • milestones
   • snapshotting
      • pipe skipped              error=not a snapshot
   • checking ./dist
      • --rm-dist is set, cleaning it up
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • building                  binary=/Users/tfournier/projets/gitlab.com/evolves-fr/backup/dist/backup_darwin_amd64/backup
      • building                  binary=/Users/tfournier/projets/gitlab.com/evolves-fr/backup/dist/backup_linux_amd64/backup
   • archives
      • creating                  archive=dist/backup_0.1.0_linux_amd64.tar.gz
      • creating                  archive=dist/backup_0.1.0_darwin_amd64.tar.gz
   • creating source archive
      • pipe skipped              error=source pipe is disabled
   • linux packages
   • snapcraft packages
   • calculating checksums
      • checksumming              file=backup_0.1.0_darwin_amd64.tar.gz
      • checksumming              file=backup_0.1.0_linux_amd64.tar.gz
   • signing artifacts
      • signing                   cmd=[gpg -u 4903C52D --output dist/backup_0.1.0_linux_amd64.tar.gz.sig --detach-sign dist/backup_0.1.0_linux_amd64.tar.gz]
      • signing                   cmd=[gpg -u 4903C52D --output dist/backup_0.1.0_darwin_amd64.tar.gz.sig --detach-sign dist/backup_0.1.0_darwin_amd64.tar.gz]
      • signing                   cmd=[gpg -u 4903C52D --output dist/backup_0.1.0_checksums.txt.sig --detach-sign dist/backup_0.1.0_checksums.txt]
   • docker images
      • building docker image     buildx=false image=registry.gitlab.com/evolves-fr/backup:latest
   • publishing
      • blobs
         • pipe skipped              error=blobs section is not configured
      • http upload
         • pipe skipped              error=uploads section is not configured
      • custom publisher
         • pipe skipped              error=publishers section is not configured
      • artifactory
         • pipe skipped              error=artifactory section is not configured
      • docker images
         • pushing docker image      image=registry.gitlab.com/evolves-fr/backup:latest
         • pushing docker image      image=registry.gitlab.com/evolves-fr/backup:v0.1.0
         • pushing docker image      image=registry.gitlab.com/evolves-fr/backup:0.1.0
         • pushing docker image      image=registry.gitlab.com/evolves-fr/backup:v0.1
         • pushing docker image      image=registry.gitlab.com/evolves-fr/backup:0.1
      • docker manifests
      • snapcraft packages
      • github/gitlab/gitea releases
         • creating or updating release repo= tag=v0.1.0
         • release updated           name=v0.1.0
         • uploading to release      file=dist/backup_0.1.0_checksums.txt.sig name=backup_0.1.0_checksums.txt.sig
         • uploading to release      file=dist/backup_0.1.0_darwin_amd64.tar.gz name=backup_0.1.0_darwin_amd64.tar.gz
         • uploading to release      file=dist/backup_0.1.0_darwin_amd64.tar.gz.sig name=backup_0.1.0_darwin_amd64.tar.gz.sig
         • uploading to release      file=dist/backup_0.1.0_linux_amd64.tar.gz name=backup_0.1.0_linux_amd64.tar.gz
         • uploading to release      file=dist/backup_0.1.0_checksums.txt name=backup_0.1.0_checksums.txt
         • uploading to release      file=dist/backup_0.1.0_linux_amd64.tar.gz.sig name=backup_0.1.0_linux_amd64.tar.gz.sig
         • failed to upload artifact, will retry artifact=backup_0.1.0_darwin_amd64.tar.gz.sig error=Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=839 with Body length 0 try=1
         • failed to upload artifact, will retry artifact=backup_0.1.0_checksums.txt.sig error=Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=833 with Body length 0 try=1
         • failed to upload artifact, will retry artifact=backup_0.1.0_checksums.txt error=Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=460 with Body length 0 try=1
         • failed to upload artifact, will retry artifact=backup_0.1.0_linux_amd64.tar.gz.sig error=Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=838 with Body length 0 try=1
         • failed to upload artifact, will retry artifact=backup_0.1.0_darwin_amd64.tar.gz error=Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=4186932 with Body length 0 try=1
         • failed to upload artifact, will retry artifact=backup_0.1.0_linux_amd64.tar.gz error=Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=4013654 with Body length 0 try=1
   ⨯ release failed after 37.68s error=github/gitlab/gitea releases: failed to publish artifacts: failed to upload backup_0.1.0_darwin_amd64.tar.gz.sig after 1 tries: Post "https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads": http: ContentLength=839 with Body length 0
```

**To Reproduce**

```yaml
before:
  hooks:
    - go mod download

builds:
  - main: main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - "registry.gitlab.com/evolves-fr/backup:latest"
      - "registry.gitlab.com/evolves-fr/backup:v{{ .Version }}"
      - "registry.gitlab.com/evolves-fr/backup:{{ .Version }}"
      - "registry.gitlab.com/evolves-fr/backup:v{{ .Major }}.{{ .Minor }}"
      - "registry.gitlab.com/evolves-fr/backup:{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

release:
  gitlab:
    owner: evolves-fr
    name: backup

signs:
  - artifacts: all
    args: ["-u", "4903C52D", "--output", "${signature}", "--detach-sign", "${artifact}"]

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.
```
   • loading config file       file=.goreleaser.yml
   • checking config:
      • snapshotting
      • github/gitlab/gitea releases
      • project name
      • building binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images
      • artifactory
      • blobs
      • homebrew tap formula
      • scoop manifests
      • milestones
   • config is valid
```

**Expected behavior**

Upload assets to gitlab release 😄 🙏 

**Environment (please complete the following information):**

- OS: mac
- OS version: 11.2.2  (20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64)
- GoReleaser Version: version 0.161.1 commit: 00bf7455340c3b6dcba7c02fef3839b0778ea18f built at: 2021-03-25T02:26:14Z built by: goreleaser
- GitLab version: public

**Additional context**
By cURL, it's okay:
- https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/uploads => OK
- https://gitlab.com/api/v4/projects/evolves-fr%2Fbackup/releases/v0.1.0/assets/links => OK
