### ISSUE TITLE
Not able to change default checksum header on artifactories

### ISSUE THREAD

**Issue by anitabee** [goreleaser/goreleaser#2153]
**Describe the bug**
I'm trying to release the package on Artifactory using `X-Checksum-Sha1` header, but PUT call seems to still result in `X-Checksum-Sha256`.
 
Setting that I'm trying:
```
artifactories:
  - name: dev
    checksum_header: X-Checksum-Sha1
```

From debug log:
```
executing request: PUT https://my-artifactory.com/artifactory/go-local/cli-project/0.0.1/proj_0.0.1_Linux_x86_64.tar.gz (headers: map[Authorization:[Basic ***] X-Checksum-Sha256:[1429edd2107a58d5f981850.....]])
```

**To Reproduce**

```
project_name: my-project
before:
  hooks:.
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: my-project
    id: "my-project"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha1
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
artifactories:
  - name: dev
    checksum: true
    checksum_header: X-Checksum-Sha1
    target: https://my-artifactory.com/{{ .ProjectName }}/{{ .Version }}/
release:
  github: 
  disable: true
```
> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

```   • loading config file       file=.goreleaser.yml
   • checking config: 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • loading go mod information
      • building binaries
         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • config is valid
 ```

**Expected behavior**
Release package using `X-Checksum-Sha1` header and Sha1 calculation sum

**Environment (please complete the following information):**
- OS: linux
- OS version: Linux ****-XPS-13-9380 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser Version:
goreleaser version 0.162.0
commit: 8306b946d3ee38a25d30c46bcaa7b12071a7256e
built at: 2021-03-31T00:06:25Z
built by: goreleaser
module version: v0.162.0
- GitLab version: n.a
