### ISSUE TITLE
Upload to GCS fails due to dirty git state in github action

### ISSUE THREAD

**Issue by eahrend** [goreleaser/goreleaser#2162]
**Describe the bug**

After a release is published, I'm attempting to upload the artifacts to GCS using a github action

**To Reproduce**

Use this as your github action, set a github secret that's a base64 encoded string of a GCS json key.

```yaml
name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mbcom-devops
          service_account_key: ${{ secrets.GCS_UPLOAD }}
          export_default_credentials: true
          credentials_file_path: ./key.json
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ github.event.release.tag_name }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./key.json
```

```yaml
# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X cmd.version={{.Version}} -X cmd.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm64
    binary: 'tbd'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
release:
# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  skip: true
blobs:
  -
    provider: gs
    bucket: bucket-name
    folder: "{{.Version}}"
    extra_files:
      - glob: foo
  - provider: gs
    bucket: bucket-name
    folder: latest
    extra_files:
      - glob: foo

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

The release gets made, artifacts are created and pushed to GCS
**Environment (please complete the following information):**

Github Action, not running on local machine

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.

output from github action:
```
🏃 Running GoReleaser...
/opt/hostedtoolcache/goreleaser-action/0.162.0/x64/goreleaser release --rm-dist
   • releasing...     
   • loading config file       file=.goreleaser.yaml
   • loading environment variables
   • getting and validating git state
      • releasing v0.0.1-beta, commit 73dced39d1eff37be865be4d44f0394b6a69d6da
   ⨯ release failed after 0.01s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
 M key.json
 ```
