### ISSUE TITLE
go mod info check failed when only use the publish

### ISSUE THREAD

**Issue by akkuman** [goreleaser/goreleaser#2165]
**Describe the bug**

I only want to use its publishing functionality, but it forces go mod info checking,

I fork a repo and udpate its source, I use the makefile to build all release, and I only want to use goreleaser to publish them. But the check of go mod info will failed.

**To Reproduce**

```yaml
builds:
  - skip: true
checksum:
  name_template: 'checksums.txt'
gitea_urls:
  api: http://xxx.online/api/v1/
  download: http://xxx.online
  # set to true if you use a self-signed certificate
  skip_tls_verify: false
release:
  draft: false

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base). If
  # another file with the same name exists, the latest one found will be used.
  # Defaults to empty.
  extra_files:
    - glob: ./release/packages/*

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

I can control if the go mod info checking can be skipped

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- GoReleaser Version [goreleaser --version]
- GitLab version (if using a private hosted one)

**Additional context**

error message
```
loading go mod information
--
39 | • proxying github.com/xxx/xx@xxx-v0.36.2 to build github.com/xxx/xxx
40 | ⨯ release failed after 127.69s error=failed to proxy module: exit status 1: go: errors parsing go.mod:
41 | /drone/src/dist/proxy/xxx/go.mod:4: require github.com/xxx/xxx: version "xxx-v0.36.2" invalid: unknown revision xxx-v0.36.2
```

the `xxx-v0.36.2` is my new tag
