### ISSUE TITLE
goreleaser seems to fail building docker images

### ISSUE THREAD

**Issue by mgiessing** [goreleaser/goreleaser#2167]
**Describe the bug**

I want to create a PR to support ppc64le arch, but when I try to run goreleaser without any changes at all it even doesn't run properly on v0.162.0 for x86 / ARM

This error appears if I try to run goreleaser and it seems like the docker images cannot be build, neither for x86 nor ARM:
(full log in additional context section)
```
[...]
#5 [2/6] RUN apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base
#5 sha256:da70217d497a60d15556f65b23d597ce59e7f48c2c32c5a3f0bf4a80c971008c
#5 2.501 standard_init_linux.go:219: exec user process caused: exec format error
#5 ERROR: executor failed running [/bin/sh -c apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base]: exit code: 1
------
 > [2/6] RUN apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base:
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base]: exit code: 1
: exit status 1
```

**To Reproduce**

- Clone & checkout goreleaser
`git clone https://github.com/goreleaser/goreleaser.git`
`cd goreleaser && git checkout v0.162.0`
- Run goreleaser
`goreleaser release --snapshot --rm-dist`

This is my .goreleaser.yml file (the default one):

```
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
gomod:
  proxy: true
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
dockers:
- image_templates:
  - 'goreleaser/goreleaser:{{ .Tag }}-amd64'
  - 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use_buildx: true
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  extra_files:
  - scripts/entrypoint.sh
- image_templates:
  - 'goreleaser/goreleaser:{{ .Tag }}-arm64'
  - 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use_buildx: true
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  goarch: arm64
  extra_files:
  - scripts/entrypoint.sh
docker_manifests:
- name_template: 'goreleaser/goreleaser:{{ .Tag }}'
  image_templates:
  - 'goreleaser/goreleaser:{{ .Tag }}-amd64'
  - 'goreleaser/goreleaser:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}-amd64'
  - 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}-arm64'
- name_template: 'goreleaser/goreleaser:latest'
  image_templates:
  - 'goreleaser/goreleaser:{{ .Tag }}-amd64'
  - 'goreleaser/goreleaser:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/goreleaser/goreleaser:latest'
  image_templates:
  - 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}-amd64'
  - 'ghcr.io/goreleaser/goreleaser:{{ .Tag }}-arm64'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE.md
      - completions/*
brews:
  - tap:
      owner: goreleaser
      name: homebrew-tap
    folder: Formula
    homepage:  https://goreleaser.com
    description: Deliver Go binaries as fast and easily as possible
    license: MIT
    test: |
      system "#{bin}/goreleaser -v"
    dependencies:
    - name: go
    install: |-
      bin.install "goreleaser"
      bash_completion.install "completions/goreleaser.bash" => "goreleaser"
      zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
      fish_completion.install "completions/goreleaser.fish"
scoop:
  bucket:
    owner: goreleaser
    name: scoop-bucket
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://goreleaser.com
    description: Deliver Go binaries as fast and easily as possible
    maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
    license: MIT
    vendor: GoReleaser
    contents:
      - src: ./completions/goreleaser.bash
        dst: /etc/bash_completion.d/goreleaser
      - src: ./completions/goreleaser.fish
        dst: /usr/share/fish/completions/goreleaser.fish
      - src: ./completions/goreleaser.zsh
        dst: /usr/local/share/zsh/site-functions/_goreleaser
    formats:
    - apk
    - deb
    - rpm
    dependencies:
    - git
    recommends:
    - golang
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Deliver Go binaries as fast and easily as possible
    description: |
      GoReleaser builds Go binaries for several platforms, creates a GitHub
      release and then pushes a Homebrew formula to a repository. All that
      wrapped in your favorite CI.
    grade: stable
    confinement: classic
    publish: true
```

**Expected behavior**

I would expect, that the docker files are being built properly as this version was already released

**Environment (please complete the following information):**

- OS: 
`linux`
- OS version: 
`Linux x3850x5-5 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- GoReleaser Version [goreleaser --version]
`goreleaser version 0.162.0`
- GitLab version (if using a private hosted one)

**Additional context**
Complete output after I run `goreleaser release --snapshot --rm-dist`:

```
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v0.162.0, commit 8306b946d3ee38a25d30c46bcaa7b12071a7256e
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag      
   • running before hooks
      • running go mod tidy
      • running ./scripts/completions.sh
   • setting defaults 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • loading go mod information
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • snapshotting     
   • checking ./dist  
   • loading go mod information
      • pipe skipped              error=disabled during snapshot mode
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • pipe skipped              error=not available for snapshots
   • building binaries
      • building                  binary=/root/git/goreleaser/dist/goreleaser_windows_arm_6/goreleaser.exe
      • building                  binary=/root/git/goreleaser/dist/goreleaser_linux_386/goreleaser
      • building                  binary=/root/git/goreleaser/dist/goreleaser_linux_arm_6/goreleaser
      • building                  binary=/root/git/goreleaser/dist/goreleaser_windows_386/goreleaser.exe
      • building                  binary=/root/git/goreleaser/dist/goreleaser_windows_amd64/goreleaser.exe
      • building                  binary=/root/git/goreleaser/dist/goreleaser_linux_amd64/goreleaser
      • building                  binary=/root/git/goreleaser/dist/goreleaser_linux_arm64/goreleaser
      • building                  binary=/root/git/goreleaser/dist/goreleaser_darwin_amd64/goreleaser
      • building                  binary=/root/git/goreleaser/dist/goreleaser_darwin_arm64/goreleaser
   • archives         
      • creating                  archive=dist/goreleaser_Linux_x86_64.tar.gz
      • creating                  archive=dist/goreleaser_Windows_armv6.zip
      • creating                  archive=dist/goreleaser_Linux_arm64.tar.gz
      • creating                  archive=dist/goreleaser_Linux_i386.tar.gz
      • creating                  archive=dist/goreleaser_Windows_x86_64.zip
      • creating                  archive=dist/goreleaser_Darwin_arm64.tar.gz
      • creating                  archive=dist/goreleaser_Linux_armv6.tar.gz
      • creating                  archive=dist/goreleaser_Windows_i386.zip
      • creating                  archive=dist/goreleaser_Darwin_x86_64.tar.gz
   • creating source archive
      • pipe skipped              error=source pipe is disabled
   • linux packages   
      • creating                  file=dist/goreleaser_386.deb
      • creating                  file=dist/goreleaser_386.apk
      • creating                  file=dist/goreleaser_386.rpm
      • creating                  file=dist/goreleaser_armv6.deb
      • creating                  file=dist/goreleaser_arm64.apk
      • creating                  file=dist/goreleaser_armv6.rpm
      • creating                  file=dist/goreleaser_amd64.rpm
      • creating                  file=dist/goreleaser_armv6.apk
      • creating                  file=dist/goreleaser_arm64.rpm
      • creating                  file=dist/goreleaser_amd64.deb
      • creating                  file=dist/goreleaser_arm64.deb
      • creating                  file=dist/goreleaser_amd64.apk
   • snapcraft packages
      • creating                  arch=amd64 snap=dist/goreleaser_amd64.snap
      • creating                  arch=arm64 snap=dist/goreleaser_arm64.snap
      • creating                  arch=i386 snap=dist/goreleaser_386.snap
      • creating                  arch=armhf snap=dist/goreleaser_armv6.snap
   • calculating checksums
      • checksumming              file=goreleaser_amd64.rpm
      • checksumming              file=goreleaser_Linux_armv6.tar.gz
      • checksumming              file=goreleaser_arm64.apk
      • checksumming              file=goreleaser_Windows_i386.zip
      • checksumming              file=goreleaser_386.apk
      • checksumming              file=goreleaser_Windows_x86_64.zip
      • checksumming              file=goreleaser_386.deb
      • checksumming              file=goreleaser_armv6.rpm
      • checksumming              file=goreleaser_amd64.deb
      • checksumming              file=goreleaser_Linux_arm64.tar.gz
      • checksumming              file=goreleaser_armv6.apk
      • checksumming              file=goreleaser_arm64.deb
      • checksumming              file=goreleaser_amd64.apk
      • checksumming              file=goreleaser_arm64.rpm
      • checksumming              file=goreleaser_Darwin_x86_64.tar.gz
      • checksumming              file=goreleaser_386.rpm
      • checksumming              file=goreleaser_Darwin_arm64.tar.gz
      • checksumming              file=goreleaser_Windows_armv6.zip
      • checksumming              file=goreleaser_Linux_i386.tar.gz
      • checksumming              file=goreleaser_Linux_x86_64.tar.gz
      • checksumming              file=goreleaser_armv6.deb
   • signing artifacts
   • docker images    
      • building docker image     buildx=true image=goreleaser/goreleaser:v0.162.0-arm64
      • building docker image     buildx=true image=goreleaser/goreleaser:v0.162.0-amd64
   ⨯ release failed after 41.92s error=failed to build docker image: goreleaser/goreleaser:v0.162.0-arm64: 
#1 [internal] load build definition from Dockerfile
#1 sha256:9c48a326d133e0f68b319ea7816a291df5b0e4b2bb433f43bc8d85baf58463f0
#1 transferring dockerfile: 30B
#1 transferring dockerfile: 484B done
#1 DONE 0.4s

#2 [internal] load .dockerignore
#2 sha256:28c4eda7c65cdf786b5d34c66de615b50bf59802165545fb36b00a3d62b934eb
#2 transferring context: 2B done
#2 DONE 0.5s

#3 [internal] load metadata for docker.io/library/golang:1.16-alpine
#3 sha256:066c23f588b92c8811e28ac05785cd295f354b1e7f60b3e42c4008ec173536c2
#3 DONE 0.5s

#4 [1/6] FROM docker.io/library/golang:1.16-alpine@sha256:6c35b28ceee082c621c818c097f418cd55104a16e51003120c1bf37111ed9cfe
#4 sha256:9b1867e44c80a743849a386450941e3234d4470d5b14dda21674768b71b289d2
#4 CACHED

#5 [2/6] RUN apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base
#5 sha256:da70217d497a60d15556f65b23d597ce59e7f48c2c32c5a3f0bf4a80c971008c
#5 ...

#6 [internal] load build context
#6 sha256:1b713add46757af10b8e74053f08cf4a0f24ae5f2530066f2658e7fd471126f7
#6 transferring context: 8.81MB 0.2s done
#6 DONE 0.4s

#5 [2/6] RUN apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base
#5 sha256:da70217d497a60d15556f65b23d597ce59e7f48c2c32c5a3f0bf4a80c971008c
#5 2.501 standard_init_linux.go:219: exec user process caused: exec format error
#5 ERROR: executor failed running [/bin/sh -c apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base]: exit code: 1
------
 > [2/6] RUN apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base:
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apk add --no-cache bash                        curl                        docker-cli                        git                        mercurial                        make                        build-base]: exit code: 1
: exit status 1
```
