### ISSUE TITLE
docker manifests assume the rm command (introduced in 20.10)

### ISSUE THREAD

**Issue by alephnull** [goreleaser/goreleaser#2192]
**Describe the bug**
The code starts off with trying to remove an non-existent manifest in https://github.com/goreleaser/goreleaser/blob/df1ea4851ad1ea5afb323c1213ca6648ef2637f5/internal/pipe/docker/manifest.go#L88-L97 however, the `rm ` command is only available in 20.10. This normally would not be a prpblem but for various reasons, I have to build on Debian stretch which does not package 20.10. The last version available is 19.03 which does not have the rm command.

Shoehorning 20.10 into stretch appears to be a problem I suspect that the GLIBC version 2.28 in buster is required for 20.10. 

**To Reproduce**

Define `docker` and `docker_manifest` sections
Run goreleaser

The actual goreleaser config I use if quite voluminous but I am including it to show how constricted my options are:
```yaml
# Generated by: tyk-ci/wf-gen
# Generated on: Wed 28 Apr 14:40:48 UTC 2021

# Generation commands:
# ./pr.zsh -title releng: [TD-309] multiarch manifests for Hub and Cloudsmith -branch releng/arm64
# m4 -E -DxREPO=tyk


# Check the documentation at http://goreleaser.com
# This project needs CGO_ENABLED=1 and the cross-compiler toolchains for
# - arm64
# - macOS (only 10.15 is supported)
# - amd64


builds:
  - id: std-linux
    ldflags:
      - -X gateway.VERSION={{.Version}} -X gateway.commit={{.Commit}} -X gateway.buildDate={{.Date}} -X gateway.builtBy=goreleaser
    goos:
      - linux
    goarch:
      - amd64
  - id: std-darwin
    ldflags:
      - -X gateway.VERSION={{.Version}} -X gateway.commit={{.Commit}} -X gateway.buildDate={{.Date}} -X gateway.builtBy=goreleaser
    env:
      - CC=o64-clang
    goos:
      - darwin
    goarch:
      - amd64
  - id: std-arm64
    ldflags:
      - -X gateway.VERSION={{.Version}} -X gateway.commit={{.Commit}} -X gateway.buildDate={{.Date}} -X gateway.builtBy=goreleaser
    env:
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
  # static builds strip symbols and do not allow plugins
  - id: static-amd64
    ldflags:
      - -s -w -X gateway.VERSION={{.Version}} -X gateway.commit={{.Commit}} -X gateway.buildDate={{.Date}} -X gateway.builtBy=goreleaser
      - -linkmode external -extldflags -static
    goos:
      - linux
    goarch:
      - amd64



dockers:
- ids:
    - std
  image_templates:
    - "tykio/tyk-gateway:{{ .Tag }}-amd64"
    - "tykio/tyk-gateway:v{{ .Major }}.{{ .Minor }}-amd64"
    - "docker.tyk.io/tyk-gateway/tyk-gateway:{{ .Tag }}-amd64"
    - "docker.tyk.io/tyk-gateway/tyk-gateway:v{{ .Major }}.{{ .Minor }}-amd64"
  build_flag_templates:
    - "--build-arg=PORTS=8080"
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  use_buildx: true
  goarch: amd64
  goos: linux
  dockerfile: Dockerfile.std
  skip_push: auto
  extra_files:
    - "install/"
    - "README.md"

    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates"
    - "middleware"
    - "event_handlers/sample"
    - "policies"
    - "coprocess"
    - "tyk.conf.example"

- ids:
    - std
  image_templates:
    - "tykio/tyk-gateway:{{ .Tag }}-arm64"
    - "tykio/tyk-gateway:v{{ .Major }}.{{ .Minor }}-arm64"
    - "docker.tyk.io/tyk-gateway/tyk-gateway:v{{ .Major }}.{{ .Minor }}-arm64"
    - "docker.tyk.io/tyk-gateway/tyk-gateway:{{ .Tag }}-arm64"
  build_flag_templates:
    - "--build-arg=PORTS=8080"
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}-arm64"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  use_buildx: true
  goarch: arm64
  goos: linux
  dockerfile: Dockerfile.std
  skip_push: auto
  extra_files:
    - "install/"
    - "README.md"

    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates"
    - "middleware"
    - "event_handlers/sample"
    - "policies"
    - "coprocess"
    - "tyk.conf.example"

- ids:
    - static-amd64
  image_templates:
    - "tykio/tyk-gateway:s{{ .Version }}"
    - "tykio/tyk-gateway:s{{ .Major }}.{{ .Minor }}"
    - "docker.tyk.io/tyk-gateway/tyk-gateway:s{{ .Version }}"
    - "docker.tyk.io/tyk-gateway/tyk-gateway:s{{ .Major }}.{{ .Minor }}"
  build_flag_templates:
    - "--build-arg=PORTS=8080"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}-slim"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  goarch: amd64
  goos: linux
  dockerfile: Dockerfile.slim
  skip_push: auto
  extra_files:
    - "install/"
    - "README.md"

    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates"
    - "middleware"
    - "event_handlers/sample"
    - "policies"
    - "coprocess"
    - "tyk.conf.example"

- ids:
    - std
  image_templates:
    - "tykio/tyk-hybrid-docker:{{ .Tag }}"
    - "tykio/tyk-hybrid-docker:v{{ .Major }}.{{ .Minor }}"
  build_flag_templates:
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}-hybrid"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  goarch: amd64
  goos: linux
  dockerfile: images/hybrid/Dockerfile
  skip_push: auto
  extra_files:
    - "images/hybrid/"
- ids:
    - std
  image_templates:
    - "tykio/tyk-plugin-compiler:{{ .Tag }}"
    - "tykio/tyk-plugin-compiler:v{{ .Major }}.{{ .Minor }}"
  build_flag_templates:
    - "--build-arg=TYK_GW_TAG={{ .Commit }}"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title=tyk-plugin-compiler"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  goarch: amd64
  goos: linux
  dockerfile: images/plugin-compiler/Dockerfile
  skip_push: auto
  extra_files:
    - "images/plugin-compiler/"

docker_manifests:
  - name_template: tykio/tyk-gateway:{{ .Tag }}
    image_templates:
    - tykio/tyk-gateway:{{ .Tag }}-amd64
    - tykio/tyk-gateway:{{ .Tag }}-arm64
  - name_template: tykio/tyk-gateway:v{{ .Major }}.{{ .Minor }}
    image_templates:
    - tykio/tyk-gateway:v{{ .Major }}.{{ .Minor }}-amd64
    - tykio/tyk-gateway:v{{ .Major }}.{{ .Minor }}-arm64
  - name_template: docker.tyk.io/tyk-gateway/tyk-gateway:{{ .Tag }}
    image_templates:
    - docker.tyk.io/tyk-gateway/tyk-gateway:{{ .Tag }}-amd64
    - docker.tyk.io/tyk-gateway/tyk-gateway:{{ .Tag }}-arm64
  - name_template: docker.tyk.io/tyk-gateway/tyk-gateway:v{{ .Major }}.{{ .Minor }}
    image_templates:
    - docker.tyk.io/tyk-gateway/tyk-gateway:v{{ .Major }}.{{ .Minor }}-amd64
    - docker.tyk.io/tyk-gateway/tyk-gateway:v{{ .Major }}.{{ .Minor }}-amd64

nfpms:
  - id: std
    vendor: "Tyk Technologies Ltd"
    homepage: "https://tyk.io"
    maintainer: "Tyk <info@tyk.io>"
    description: Tyk API Gateway
    package_name: tyk-gateway
    builds:
      - std-linux
      - std-arm64
    formats:
      - deb
      - rpm
    contents:
      - src: "README.md"
        dst: "/opt/share/docs/tyk-gateway/README.md"
      - src: "install/*"
        dst: "/opt/tyk-gateway/install"

      - src: /opt/tyk-gateway
        dst: /opt/tyk
        type: "symlink"
      - src: "LICENSE.md"
        dst: "/opt/share/docs/tyk-gateway/LICENSE.md"
      - src: "apps/app_sample.json"
        dst: "/opt/tyk-gateway/apps"
      - src: "templates/*.json"
        dst: "/opt/tyk-gateway/templates"
      - src: "templates/playground/index.html"
        dst: "/opt/tyk-gateway/templates/playground/index.html"
      - src: "templates/playground/playground.js"
        dst: "/opt/tyk-gateway/templates/playground/playground.js"
      - src: "middleware/*.js"
        dst: "/opt/tyk-gateway/middleware"
      - src: "event_handlers/sample/*.js"
        dst: "/opt/tyk-gateway/event_handlers/sample"
      - src: "policies/*.json"
        dst: "/opt/tyk-gateway/policies"
      - src: "coprocess/*"
        dst: "/opt/tyk-gateway/coprocess"
      - src: tyk.conf.example
        dst: /opt/tyk-gateway/tyk.conf
        type: "config|noreplace"
    scripts:
      preinstall: "install/before_install.sh"
      postinstall: "install/post_install.sh"
      postremove: "install/post_remove.sh"
    bindir: "/opt/tyk-gateway"
    overrides:
      rpm:
        replacements:
          amd64: x86_64
          arm: aarch64
      deb:
        replacements:
          arm: arm64
    rpm:
      signature:
        key_file: tyk.io.signing.key
    deb:
      signature:
        key_file: tyk.io.signing.key
        type: origin



archives:
- id: std-linux
  builds:
    - std-linux
  files:
    - README.md
    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates/*.json"
    - "templates/playground/index.html"
    - "templates/playground/playground.js"
    - "install/*"
    - "middleware/*.js"
    - "event_handlers/sample/*.js"
    - "policies/*.json"
    - "coprocess/*"
    - tyk.conf.example

- id: std-darwin
  builds:
    - std-darwin
  files:
    - README.md
    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates/*.json"
    - "install/*"
    - "middleware/*.js"
    - "event_handlers/sample/*.js"
    - "policies/*.json"
    - "coprocess/*"
    - tyk.conf.example

- id: std-arm64
  builds:
    - std-arm64
  files:
    - README.md
    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates/*.json"
    - "install/*"
    - "middleware/*.js"
    - "event_handlers/sample/*.js"
    - "policies/*.json"
    - "coprocess/*"
    - tyk.conf.example
- id: static-amd64
  name_template: "{{ .ProjectName }}_{{ .Version }}_static_{{ .Os }}_{{ .Arch }}"
  builds:
    - static-amd64
  files:
    - README.md
    - "LICENSE.md"
    - "apps/app_sample.json"
    - "templates/*.json"
    - "install/*"
    - "middleware/*.js"
    - "event_handlers/sample/*.js"
    - "policies/*.json"
    - "coprocess/*"
    - tyk.conf.example



checksum:
  disable: false

signs:
  - id: std
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
    - '^utils:'
    - (?i)typo
    - 'Merge (pull request|branch)'
    - '\[CI\]'
    - '(?i)\[Buddy\]'
    - 'cherry picked'
    - '^rel-eng:'
    - '^minor:'

release:
  github:
    owner: TykTechnologies
    name: tyk
  prerelease: auto
  draft: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
```

```shellsession
% goreleaser check -f tyk/.goreleaser.yml
   • loading config file       file=tyk/.goreleaser.yml
   • checking config: 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • loading go mod information
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • config is valid  
```
**Expected behavior**

The manifests build.

**Environment (please complete the following information):**

- OS: linux
- OS version: Debian Stretch
- GoReleaser Version 0.164.0
- GitLab version (if using a private hosted one)

**Additional context**
Would you consider not doing the `rm` to begin with? The rest of the commands look like they should work.
