### ISSUE TITLE
Allow variable interpolation in sings[].signature

### ISSUE THREAD

**Issue by radeksimko** [goreleaser/goreleaser#2195]
**Is your feature request related to a problem? Please describe.**

Sometimes it can be useful to identify what key was used to generate a particular sig file (for example when keys are being rotated). This is currently only possibly by _hard coding_ the key identifier, such as

```yaml
signs:
  -
    id: with_key_id
    signature: "${artifact}.72D7468F.sig"
    args: ["--batch", "--no-tty", "-u", "{{ .Env.GPG_KEY_ID }}", "--output", "${artifact}.{{ .Env.GPG_KEY_ID }}.sig", "--detach-sign", "${artifact}"]
    artifacts: checksum
```

**Describe the solution you'd like**

I would like to be able to use variable such as `{{ .Env.GPG_KEY_ID }}` inside `signature` field.

**Describe alternatives you've considered**

Besides hard-coding the key ID I attempted to omit `signature` from configuration and just specify the sig filename in `args`:

```yaml
signs:
  -
    id: with_key_id
    args: ["--batch", "--no-tty", "-u", "{{ .Env.GPG_KEY_ID }}", "--output", "${artifact}.{{ .Env.GPG_KEY_ID }}.sig", "--detach-sign", "${artifact}"]
    artifacts: checksum
```

which does make `gpg` generate the file into the right location, but then following pipes can't find it, because they only look for the filename defined as part of `signature` - which makes sense as it's hard for GoReleaser to guess what `gpg` did and where did I write the sig file (if it even did).
