### ISSUE TITLE
Using `zip` format fails on Windows

### ISSUE THREAD

**Issue by aminya** [goreleaser/goreleaser#2224]
**Describe the bug**

Zip is a universal extension that is supported on all platforms, however, when I use `format: zip`, `goreleaser` fails with this error:

```
 • archives
   ⨯ release failed after 4.54s error=failed to create directory dist\lefthook_v0.7.5_Windows_i386.zip: open dist\lefthook_v0.7.5_Windows_i386.zip: Access is denied.
```

I had to use the default (tar.gz) to fix the issue

**To Reproduce**
```
goreleaser --snapshot --skip-publish --rm-dist
```

https://github.com/aminya/lefthook/blob/zip-test/.goreleaser.yml
```yaml
project_name: lefthook
before:
  hooks:
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - "386"
    - arm64
archives:
  - id: lefthook
    format: binary
    files:
    - none*
    replacements:
      windows: Windows
      darwin: MacOS
      linux: Linux
      386: i386
      amd64: x86_64
  - id: lefthook-zip
    format: zip
    files:
    - none*
    replacements:
      windows: Windows
      darwin: MacOS
      linux: Linux
      386: i386
      amd64: x86_64
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

Support using `zip` as a format for all operating systems

**Environment (please complete the following information):**

- OS: Win 10
- OS version: [winver] Win 10 19042.964
- GoReleaser Version [goreleaser --version]
	  
	    goreleaser version 0.164.0
		commit: d822baf11f7773f6c02eeaf7e187157b335935b3
		built at: 2021-04-22T13:58:58Z
		built by: goreleaser
		module version: v0.164.0, checksum: h1:w0zTtZSg9exA+eUoaFuZiJ5UuHaMom/TgXQvySAEJiY=

**Additional context**
