### ISSUE TITLE
Releasing on a private Gitlab Repository (subgroup)

### ISSUE THREAD

**Issue by jessequinn** [goreleaser/goreleaser#2245]
**Describe the bug**

The following error is received when using a private gitlab (V13.7.0) with goreleaser (latest):

```
release failed after 275.90s error=github/gitlab/gitea releases: failed to publish artifacts: GET https://xxx/api/v4/projects/terraform-providers/google-dns-transaction-provider/releases/1.0.6: 404 {message: 404 Project Not Found}
```

**To Reproduce**

```yaml
stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - goreleaser release --rm-dist
```

```yaml
gitlab_urls:
  api: https://xxx/api/v4/
  download: https://xxx/
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

before:
  hooks:
    - go mod tidy
    - go fmt ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
#      - openbsd
#      - solaris
#      - freebsd
#      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
#      - arm
#      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
#signs:
#  - artifacts: checksum
#    args:
#      # if you are using this in a GitHub action or some other automated pipeline, you
#      # need to pass the batch flag to indicate its not interactive.
#      - "--batch"
#      - "--local-user"
#      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"
release:
# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  skip: true
```

**Expected behavior**

The expected behaviour is to use the path `https://xxx/api/v4/projects/56/releases/1.0.6` rather than `https://xxx/api/v4/projects/terraform-providers/google-dns-transaction-provider/releases/1.0.6`

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin ZPEs-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
- GoReleaser Version: 0.165.0
- GitLab version: 13.7.0

**Additional context**
With `debug` the output remains the same:

```
release failed after 10.63s error=github/gitlab/gitea releases: failed to publish artifacts: GET https://xxx/api/v4/projects/terraform-providers/google-dns-transaction-provider/releases/1.0.6: 404 {message: 404 Project Not Found}
```
