### ISSUE TITLE
Homebrew formula generation fails on goreleaser 0.166.0

### ISSUE THREAD

**Issue by nadimkobeissi** [goreleaser/goreleaser#2252]
**Describe the bug**

Since updating to goreleaser 0.166.0, I am unable to produce builds using Homebrew formulas. My configuration remains unchanged. Here's what I get as output:

```
⨯ release failed after 29.85s error=homebrew tap formula: failed to publish artifacts: template: tmpl:1:62: executing "tmpl" at <.ArtifactUploadHash>: map has no entry for key "ArtifactUploadHash"
```

**To Reproduce**

```yaml
project_name: verifpal

gitlab_urls:
  api: https://source.symbolic.software/api/v4/
  download: https://source.symbolic.software
  skip_tls_verify: false

before:
  hooks:
    - go generate ./...

builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE
      - examples/*
      - README.md
    wrap_in_directory: true

signs:
  - artifacts: checksum

changelog:
  skip: false
  sort: asc

release:
  gitlab:
    owner: verifpal
    name: verifpal

brews:
  - tap:
      owner: verifpal
      name: verifpal
    url_template: "https://source.symbolic.software/verifpal/verifpal/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
    commit_author:
      name: drone
      email: drone@symbolic.software
    folder: HomebrewFormula
    homepage: "https://verifpal.com"
    description: "Cryptographic protocol analysis for students and engineers."

scoop:
  bucket:
    owner: verifpal
    name: verifpal
  url_template: "https://source.symbolic.software/verifpal/verifpal/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
  commit_author:
    name: drone
    email: drone@symbolic.software
  homepage: "https://verifpal.com"
  description: "Cryptographic protocol analysis for students and engineers."
  license: "https://www.gnu.org/licenses/gpl-3.0.en.html"
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

Homebrew formulas are generated and my software is released successfully.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] macOS Big Sur 11.4
- OS version: [uname -a] `Darwin Nadims-MacBook.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64`
- GoReleaser Version [goreleaser --version]
```
goreleaser version 0.166.0
commit: a2d7ccad2f71a7a050c3d9d3f53bdef2378f2b26
built at: 2021-05-25T03:45:59Z
built by: goreleaser
module version: v0.166.0, checksum: h1:n0CQjrmxp6kBULEASzZqxaGEenex5b/AItBL2D4o41k=
```

- GitLab version (if using a private hosted one): 13.12.0-ee
