### ISSUE TITLE
Have a separate builds.tags option for go tags

### ISSUE THREAD

**Issue by lukasmalkmus** [goreleaser/goreleaser#2262]
**Is your feature request related to a problem? Please describe.**

Most of my configurations look something like this:

```yaml
builds:
  - <<: &build_defaults
      binary: mybin
      main: ./cmd/mybin
      env:
        - CGO_ENABLED=0
      flags:
        - -buildmode=pie
        - -installsuffix=cgo
        - -trimpath
        - -tags="osusergo netgo static_build"
      ldflags:
        - -s -w -extldflags "-fno-PIC -static -Wl -z now -z relro"
        - -X github.com/lukasmalkmus/myapp/version.release={{ .Version }}
        - -X github.com/lukasmalkmus/myapp/version.revision={{ .ShortCommit }}
        - -X github.com/lukasmalkmus/myapp/version.buildDate={{ .CommitDate }}
        - -X github.com/lukasmalkmus/myapp/version.buildUser=goreleaser
      mod_timestamp: "{{ .CommitTimestamp }}"
    id: darwin_no_feature
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - <<: *build_defaults
    id: linux_with_feature
    flags:
      - -buildmode=pie
      - -installsuffix=cgo
      - -trimpath
      - -tags="osusergo netgo static_build feature"
    goos:
      - linux
    goarch:
      - amd64
```

As you can tell, I have to rewrite the whole `flags` config, just to add one single tag. Because the `flags` config off `linux_with_feature` completely overwrites the defaults, I cannot even just declare the `-tags` flag, only.

**Describe the solution you'd like**

It would be nice to have `tags` as a separate config key, like `ldflags`:

```yaml
builds:
  - <<: &build_defaults
      binary: mybin
      main: ./cmd/mybin
      env:
        - CGO_ENABLED=0
      tags:
        - osusergo
        - netgo
        - static_build
      flags:
        - -buildmode=pie
        - -installsuffix=cgo
        - -trimpath
      ldflags:
        - -s -w -extldflags "-fno-PIC -static -Wl -z now -z relro"
        - -X github.com/lukasmalkmus/myapp/version.release={{ .Version }}
        - -X github.com/lukasmalkmus/myapp/version.revision={{ .ShortCommit }}
        - -X github.com/lukasmalkmus/myapp/version.buildDate={{ .CommitDate }}
        - -X github.com/lukasmalkmus/myapp/version.buildUser=goreleaser
      mod_timestamp: "{{ .CommitTimestamp }}"
    id: darwin_no_feature
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - <<: *build_defaults
    id: linux_with_feature
    tags:
      - osusergo
      - netgo
      - static_build
      - feature
    flags:
      - -buildmode=pie
      - -installsuffix=cgo
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
```

**Describe alternatives you've considered**

None

**Additional context**

None
