### ISSUE TITLE
cmd under global hooks fails

### ISSUE THREAD

**Issue by donmstewart** [goreleaser/goreleaser#2264]
**Describe the bug**

Following the documentation on `cmd` definitions under before hooks is giving an error of `cannot unmarshal !!map into string`

**To Reproduce**

Following the documentation at https://goreleaser.com/customization/hooks/ the following should work

```yaml
project_name: my-project
env:
  - GO111MODULE=on
before:
  hooks:
  - cmd: go mod download # ensure all module dependencies are downloaded locally
```

**Expected behavior**

`go mod download` should run

**Environment (please complete the following information):**

- OS: Mac
- OS version: Darwin v19.6.0
- GoReleaser Version  0.166.1

**Additional context**

Reverting back to: -

```yaml
project_name: my-project
env:
  - GO111MODULE=on
before:
  hooks:
  - go mod download # ensure all module dependencies are downloaded locally
```

does work but I am needing to use something along the lines of the following in the docs

```yaml
before:
  hooks:
  - cmd: go mod tidy
     dir: ./submodule # specify command working directory
```

which also errors out.
