### ISSUE TITLE
ldflags per operating systems

### ISSUE THREAD

**Issue by tiago4orion** [goreleaser/goreleaser#228]
My project requires different ldflags for linux and OSX. Is there a way to setup this with goreleaser?
Sorry, I didn't find anything related.

**Comment by caarlos0** [comment]
There is no straightforward way, but you can create an specific goreleaser.yml for those cases and execute it with `goreleaser -f $FILE`...

**Comment by caarlos0** [comment]
@tiago4orion can you take a look at https://github.com/goreleaser/goreleaser/pull/267 ? thanks!

**Comment by caarlos0** [comment]
@tiago4orion should be possible now.

released on v0.22.0

**Comment by tiago4orion** [comment]
Thanks @caarlos0, but we rolled our own release script in the meantime. I really liked your tool, probably we'll switch to it in the future.

**Comment by caarlos0** [comment]
no problem :)

thanks for reporting the issue anyway =)

**Comment by zam6ak** [comment]
@caarlos0  the approach [you described](https://github.com/goreleaser/goreleaser/issues/228#issuecomment-312656262) above (for v0.22.0) does now work for me.
I am using v0.129.0
Has this behavior been changed or should I file a new bug?

**Comment by caarlos0** [comment]
What’s the error?

**Comment by zam6ak** [comment]
@caarlos0 

I started with this and it works:

```yaml
builds:
  - 
    id: "tool-build"
    binary: tool    
    main: ./cmd/tool/main.go
    ldflags: 
      - -s -w -X tool.version={{.Version}} -X tool.commit={{.ShortCommit}} -X tool.date={{.Date}}
      #- -H windowsgui
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
```
	  
I tried modifying as per comment (snippet below) and it fails with 
> "error=yaml: line 17: did not find expected key"	


```yaml
builds:
  - 
    id: "tool-build"
    binary: tool    
    main: ./cmd/tool/main.go
    ldflags: 
      - -s -w -X tool.version={{.Version}} -X tool.commit={{.ShortCommit}} -X tool.date={{.Date}}
    - goos:
      - windows
      ldflags: -H windowsgui
    - goos:
      - linux
      - darwin
    goarch:
      - amd64	
```  
	  
	  
And this is another attempt with outdenting goos section 	  

> fails with "error=found 2 builds with the ID 'tool', please fix your config"	

  
```yaml
builds:
  - 
    id: "tool-build"
    binary: tool    
    main: ./cmd/tool/main.go
    ldflags: 
      - -s -w -X tool.version={{.Version}} -X tool.commit={{.ShortCommit}} -X tool.date={{.Date}}
  - goos:
    - windows
    ldflags: -H windowsgui
  - goos:
    - linux
    - darwin
    goarch:
      - amd64
```
