### ISSUE TITLE
Unable to define repo url in Docker config via env

### ISSUE THREAD

**Issue by tebruno99** [goreleaser/goreleaser#2281]
Attempting to use Env vars in dockers: config section
```
dockers:
  -
    goos: linux
    goarch: amd64
    ids:
      - demourl
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
      - "{{ .Env.AWS_ECR_REPO }}:latest"
      - "{{ .Env.AWS_ECR_REPO }}:{{ .Tag }}"

```
Command:
```AWS_ECR_REPO="demorepo.dkr.ecr.us-west-2.amazonaws.com/demourl" goreleaser```

This results in the error:
```      • building docker image     buildx=false image={{ .Env.AWS_ECR_REPO }}:latest
   ⨯ release failed after 3.05s error=failed to build docker image: {{ .Env.AWS_ECR_REPO }}:latest: 
invalid argument "{{ .Env.AWS_ECR_REPO }}:latest" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
```

Rather than hard coding a repo I wanted to pass in the url from Travis/Github Actions so when someone forks they can define their own. I expected the value of .Env.AWS_ECR_REPO to be used during the docker build instead of the template text itself.

**Environment (please complete the following information):**

- OS: linux
- OS version: Ubuntu 21.04
- GoReleaser Version: 0.168.0
