### ISSUE TITLE
Docker Manifest failes when Dockers skip_push: auto 

### ISSUE THREAD

**Issue by tebruno99** [goreleaser/goreleaser#2294]
Failed build when Docker is set to skip_push: auto & tag is pre-release if Docker Manifests are defined.
(Real values replaced with placeholders, the docker repos are valid and work if skip_push: false)

```
   • docker images    
      • building docker image     buildx=true image=docker.io/private/private:latest-amd64
      • building docker image     buildx=true image=docker.io/private/private:latest-arm64v8
      • pipe skipped              error=prerelease detected with 'auto' push, skipping docker publish
   • publishing       
      • blobs            
      • http upload      
      • custom publisher 
      • artifactory      
      • docker images    
      • docker manifests 

• docker manifests 
         • removing local docker manifest manifest=docker.io/private/private:v0.0.10-rc1
         • creating docker manifest  images=[docker.io/private/private:v0.0.10-rc1-amd64 docker.io/private/private:v0.0.10-rc1-arm64v8] manifest=docker.io/private/private:v0.0.10-rc1
   ⨯ release failed after 4.01s error=docker manifests: failed to publish artifacts: failed to create docker manifest: docker.io/private/private:v0.0.10-rc1: 
no such manifest: docker.io/private/private:v0.0.10-rc1-amd64
: exit status 1
```

To Reproduce:

define dockers + manifest using the Docker Manifest documentation and set skip_push: auto,  tag version to v0.0.10-rc1 for example. 

```
dockers:
  -
    image_templates:
      - "{{ .Env.DOCKER_REPO }}:latest-amd64"
      - "{{ .Env.DOCKER_REPO }}:{{ .Tag }}-amd64"
    skip_push: auto
    use_buildx: true
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "{{ .Env.DOCKER_REPO }}:latest-arm64v8"
      - "{{ .Env.DOCKER_REPO }}:{{ .Tag }}-arm64v8"
    skip_push: auto
    use_buildx: true
    goarch: arm64
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
docker_manifests:
  -
    name_template: "{{ .Env.DOCKER_REPO }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_REPO }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_REPO }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --insecure
    push_flags:
      - --insecure
  -
    name_template: "{{ .Env.DOCKER_REPO }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_REPO }}:latest-amd64"
      - "{{ .Env.DOCKER_REPO }}:latest-arm64v8"
    create_flags:
      - --insecure
    push_flags:
      - --insecure
```

```
git tag v0.0.10-rc1
DOCKER_REPO="docker.io/myrepo/myimage" goreleaser --rm-dist
```

**Expected behavior**
I expected that the build would not fail on manifest upload if no docker builds were published

**Environment (please complete the following information):**

- OS: Linux
- OS Ubuntu 21.04
```
goreleaser version 0.169.0-pro
commit: afd6cb179a2fa4c425ead0ee95d788d2bd505d87
built at: 2021-06-05T02:14:19Z
built by: goreleaser
```
