### ISSUE TITLE
Go build tags won't be applied to builds

### ISSUE THREAD

**Issue by TheFireMike** [goreleaser/goreleaser#2300]
**Describe the bug**

In the current version the Go build tags (e.g. `go build --tags client`) won't be applied to the builds. I did some backtesting and it worked fine until v0.166.2 (Maybe #2268 in version v0.167.0 broke it?).

**To Reproduce**

Add a Go build tag to some build and run goreleaser.

```yaml
# .goreleaser.yml

builds:
  - id: "thola"

    ignore:
      - goos: linux
        goarch: 386

    main: ./main.go
    binary: thola

    env:
      - CGO_ENABLED=0

  - id: "thola-client"

    ignore:
      - goos: linux
        goarch: 386

    main: ./main.go
    binary: thola-client

    flags:
      - -tags=client
    env:
      - CGO_ENABLED=0

nfpms:
  - id: "thola"
    homepage: https://thola.io
    maintainer: team@thola.io
    description: Network Monitoring and Provisioning Tool.
    license: BSD-2-clause
    formats:
      - deb
    contents:
      - src: scripts/thola.service
        dst: /lib/systemd/system/thola.service
    scripts:
      preinstall: "scripts/pre-install.sh"
      postinstall: "scripts/post-install.sh"
      postremove: "scripts/post-uninstall.sh"

archives:
  - builds:
      - thola
      - thola-client

    replacements:
      amd64: 64-bit
      darwin: macOS
```

**Expected behavior**

If you run the config above, the `thola-client` build should have the `client` build tag applied. Unfortunately, it hasn't.

**Environment (please complete the following information):**

- GoReleaser Version > v0.166.2
