### ISSUE TITLE
Error Creating GitHub Discussions Entry

### ISSUE THREAD

**Issue by stack72** [goreleaser/goreleaser#2304]
As part of the Pulumi release, we want to create an entry in GitHub Discussions for our users. I have added the following code to our goreleaser.yml file:

```
release:
  discussion_category_name: Announcements
```

The build continues as expected until it gets to the release part and we get an error as follows:

```
error=github/gitlab/gitea releases: failed to publish artifacts: POST https://api.github.com/repos/pulumi/pulumi/releases: 404 Discussion could not be created. Make sure you passed a valid category name. []
```

We are using a GitHub Token that has access to read/write discussions. But it seems that the discussion_category_name is not being picked up in the config as it seems to be passing an empty name?

Runner configuration:

```
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -p 3 -f .goreleaser.yml --rm-dist --release-notes=CHANGELOG_PENDING.md
```

This installs:

```
✅ GoReleaser version found: v0.169.0
⬇️ Downloading goreleaser/goreleaser@v0.169.0 goreleaser_Darwin_x86_64.tar.gz... (download)
```

I am not sure where this bug lays to be honest - I am not sure if there is an issue with the yaml we have created or something else 

The .goreleaser.yml file can be found https://github.com/pulumi/pulumi/blob/master/.goreleaser.yml

We are using public github and the GitHub Actions runner is macos-latest and Go 1.16.5

Thanks

Paul
