### ISSUE TITLE
Goreleaser Archives not include subdirectory, promoting binary into top directory of tar.gz achive.

### ISSUE THREAD

**Issue by jspaleta** [goreleaser/goreleaser#2311]
**Describe the bug**
Goreleaser build correctly places binary in bin/ directory
```
$ tree dist/sensu-rocketchat-handler_linux_amd64
dist/sensu-rocketchat-handler_linux_amd64
└── bin
    └── sensu-rocketchat-handler
```
Goreleaser publish removes the bin/ directory from the archive
```
$ tar tzf dist/sensu-rocketchat-handler_v0.0.0-SNAPSHOT-84d8969_linux_amd64.tar.gz
CHANGELOG.md
LICENSE
README.md
sensu-rocketchat-handler
```

In previous versions of goreleaser it was possible to build archives such that the binary was in a subdirectory

**To Reproduce**

1. Set the build binary to use subdirectory `binary: bin/{{ .ProjectName }}`
2.  do a goreleaser release --snapshot --rm-dist --skip-publish
3.  check dist/ notice directory structure is as expected
4. check contents of generated archives... notice binary is not in the bin/ subdirectory

```yaml
builds:
  # List of builds
  - # First Build
    env:
    - CGO_ENABLED=0
    main: main.go
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    targets:
      - darwin_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - windows_386
      - windows_amd64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**
Expected the tar.gz to include the subdirectory 'bin/'  like this:
```
$ tar tzf dist/sensu-rocketchat-handler_manually_created_linux_amd64.tar.gz 
bin/
bin/sensu-rocketchat-handler
CHANGELOG.md
LICENSE
README.md
```
This is a change in behavior compared to older goreleaser releases, not sure exactly when it changed behavior.

- OS: Fedora Linux 33 
- OS version: `Linux 5.12.11-200.fc33.x86_64 #1 SMP Wed Jun 16 16:10:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- GoReleaser Version
```
goreleaser version 0.171.0
commit: 097c456a3b4f8f522a9d168bfb4f6a5d2661e659
built at: 2021-06-21T02:26:17Z
built by: goreleaser
module version: v0.171.0, checksum: h1:aM9boGNCuwst7uHr3QxsxAwdjHEQvKu84GxMJhVtofk=
```

**Additional context**
Also seeing this in the current github action
We've been relying on this behavior for Sensu asset build for awhile using goreleaser github action v1, something has changed somewhat recently.
