### ISSUE TITLE
Unexpected change on generated deb/rpm on latest release

### ISSUE THREAD

**Issue by gssbzn** [goreleaser/goreleaser#2325]
**Describe the bug**

Something changed between 0.169.0 and 0.172.1, not sure if this is related to a0dd45592e2ea2cb309ee586531961373270c48e but files generated by `nfpms` config don't respect the bindir anymore

**To Reproduce**

We were relying on the feature to place the generated bin in a sub folder `bin/{name}` and when doing this we had to define our `nfpms` config to set `bindir` to. `usr` it looks like it no longer behaves in the same way and we may need to go back to `usr/bin`

main reason to open the ticket is to confirm this is expected and we should update or is it actually a bug

```yaml
before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      binary: bin/mongocli
      main: ./cmd/mongocli/mongocli.go
      ldflags:
        - -s -w -X github.com/mongodb/mongocli/internal/version.Version={{.Version}} -X github.com/mongodb/mongocli/internal/version.GitCommit={{.FullCommit}}
    id: macos
    goos: [darwin]
    goarch: [amd64,arm64]
    hooks:
      # This will notirize Apple binaries and replace goreleaser bins with the notarized ones
      post: ./build/package/mac_notarize.sh
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64,arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]
archives:
- id: linux
  builds: [linux]
  <<: &archive_defaults
    files:
      - README.md
      - LICENSE
      - third_party_notices/**/*
    replacements:
      darwin: macos
      amd64: x86_64
  wrap_in_directory: true
  format: tar.gz
- id: macos
  builds: [macos]
  <<: *archive_defaults
  format: zip
  wrap_in_directory: false
- id: windows
  builds: [windows]
  <<: *archive_defaults
  wrap_in_directory: false
  format: zip
nfpms:
- package_name: mongocli
  vendor: MongoDB Inc.
  homepage: https://www.mongodb.com/
  maintainer: MongoDB Inc. <support@mongodb.com>
  description: MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  license: Apache 2.0
  bindir: /usr/bin
  builds: [linux]
  formats: [deb,rpm]
  replacements:
    amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: next
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^task:'
    - '^build(deps):'
release:
  prerelease: auto
  name_template: "MongoDB CLI {{.Version}}"
  extra_files:
    - glob: ./bin/*.msi

```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

**Environment (please complete the following information):**

- OS: mac
- OS version: 10.14
- GoReleaser Version: 0.172.1
