### ISSUE TITLE
Goreleaser Docker Image does not support Multi-Arch builds

### ISSUE THREAD

**Issue by msvechla** [goreleaser/goreleaser#2332]
**Describe the bug**

The current goreleaser Docker image does not support multi-arch builds, because the Docker buildx plugin is not installed in the image.

This currently results in the following error in CI:

```
   • building docker image     buildx=true image=msvechla/vaultbot:1.12.0-rc1-amd64
   ⨯ release failed after 162.95s error=failed to build docker image: msvechla/vaultbot:1.12.0-rc1-amd64: 
unknown flag: --load
See 'docker --help'.
```

**To Reproduce**

```yaml
project_name: vaultbot
builds:
  - env: [CGO_ENABLED=0]
    binary: vaultbot
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: 
  - "msvechla/vaultbot:{{ .Version }}-amd64"
  dockerfile: Dockerfile
  use_buildx: true
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates: 
  - "msvechla/vaultbot:{{ .Version }}-arm64"
  dockerfile: Dockerfile
  use_buildx: true
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: msvechla/vaultbot:{{ .Version }}
  image_templates:
  - "msvechla/vaultbot:{{ .Version }}-amd64"
  - "msvechla/vaultbot:{{ .Version }}-arm64"
```

**Expected behavior**

Working multi-arch builds with buildx.

**Environment (please complete the following information):**

- OS: linux
- OS version: -
- GoReleaser Version: 0.173.1

I will open a PR to add `buildx` to the goreleaser Docker image. Let me know what you think.
Thanks a lot for this awesome project!
