### ISSUE TITLE
[Bug]: goreleaser signing using gon - "bundle format unrecognized, invalid, or unsuitable"

### ISSUE THREAD

**Issue by JCzz** [goreleaser/goreleaser#2348]
### What happened?

I am trying to sign my golang using goreleaser - and eventually distribute using Homebrew. But this will require signing with Apple Developer ID to be able to distribute to MacOs.

Also posted on [Stackoverflow](https://stackoverflow.com/questions/68397720/goreleaser-signing-using-gon-bundle-format-unrecognized-invalid-or-unsuitabl)

### How can we reproduce this?

Have you seen the following error using [gon][1] and fixed it? 

yaml sample from [here](https://goreleaser.com/customization/sign/#executables)
```
## .goreleaser.yaml
# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
- binary: foo
  id: foo
  goos:
  - linux
  goarch:
  - amd64
# notice that we need a separated build for the MacOS binary only:
- binary: foo
  id: appbrew-macos
  goos:
  - darwin
  goarch:
  - amd64
  hooks:
    post: gon gon.hcl
```

## gon.hcl file

    # The path follows a pattern
    # ./dist/BUILD-ID_TARGET/BINARY-NAME
    
    source = ["."]
    bundle_id = "com.mydomain.mybrew"
    
    apple_id {
        username = "<my_developer_id@application.com>"
        password = "@keychain:developer_id_application"
    }
    
    sign {
      application_identity = "Developer ID Application: my name (452534542)"
    }

I can verify that the password is retrieve using: 

    security find-generic-password -w -s 'developer_id_application' -a '<my_developer_id@application.com>'

## Error:

       • archives         
          • creating                  archive=dist/appbrew_0.1.19_Darwin_x86_64.tar.gz
          • creating                  archive=dist/appbrew_0.1.19_Darwin_arm64.tar.gz
          • creating                  archive=dist/appbrew_0.1.19_Linux_i386.tar.gz
          • creating                  archive=dist/appbrew_0.1.19_Linux_x86_64.tar.gz
          • creating                  archive=dist/appbrew_0.1.19_Linux_arm64.tar.gz
       • creating source archive
       • linux packages   
       • snapcraft packages
       • calculating checksums
          • checksumming              file=appbrew_0.1.19_Linux_arm64.tar.gz
          • checksumming              file=appbrew_0.1.19_Darwin_arm64.tar.gz
          • checksumming              file=appbrew_0.1.19_Linux_x86_64.tar.gz
          • checksumming              file=appbrew_0.1.19_Darwin_x86_64.tar.gz
          • checksumming              file=appbrew_0.1.19_Linux_i386.tar.gz
       • signing artifacts
          • signing                   cmd=[gon gon.hcl]
          • ==> ✏️  Signing files...
     cmd=gon
          • ❗️ Error signing files:
    
    error signing:
    
    .: bundle format unrecognized, invalid, or unsuitable
    
     cmd=gon
       ⨯ release failed after 3.49s error=sign: gon failed

  [1]: https://github.com/mitchellh/gon

### goreleaser version

```bash
goreleaser --version                          
goreleaser version 0.173.2
commit: 5bcfa9042d0efd419b660a3b63c815a13d919e30
built by: homebrew
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
