### ISSUE TITLE
[Bug]: Docker build fails

### ISSUE THREAD

**Issue by safaci2000** [goreleaser/goreleaser#2354]
### What happened?

When trying to build a docker image using go-release, it's failing to copy the project files except for the Dockerfile to the docker container.  Same image executed via docker build or docker-compose build works fine.

### How can we reproduce this?

goreleaser release --snapshot --rm-dist --debug

the project is: https://github.com/netsage-project/grafana-dashboard-manager (Specifically this branch: https://github.com/netsage-project/grafana-dashboard-manager/tree/feature/docker )

Build config is:

```yaml
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
dockers:
  - image_templates: ["ghcr.io/netsage-project/gdg:{{ .Version }}-amd64"]
    ids: [gdg]
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}

builds:
  - env:
      - CGO_ENABLED=0
    binary: gdg
    ldflags: -X github.com/netsage-project/grafana-dashboard-manager/version.GitCommit={{ .Commit }} -X github.com/netsage-project/grafana-dashboard-manager/version.BuildDate={{ .Date }}  -X github.com/netsage-project/grafana-dashboard-manager/version.Version={{ .Tag }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README*
      - conf/importer-example.yml

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

```

Dockerfile:

```
# Build Stage
FROM golang:1.16.0  AS build-stage

LABEL app="build-grafana-dashboard-manager"
LABEL REPO="https://github.com/netsage-project/grafana-dashboard-manager"

ENV PROJPATH=/go/src/github.com/netsage-project/grafana-dashboard-manager

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

ADD . /go/src/github.com/netsage-project/grafana-dashboard-manager
WORKDIR /go/src/github.com/netsage-project/grafana-dashboard-manager

RUN ls -lh; pwd; make build-alpine

..... ## more follows but the line above fails.

```

output:

```sh
  • docker images
      • looking for artifacts matching docker={[] [] [gdg] linux amd64  Dockerfile [ghcr.io/netsage-project/gdg:{{ .Version }}-amd64]  [] [--platform=linux/amd64 --pull --label=org.opencontainers.image.created={{.Date}} --label=org.opencontainers.image.title={{.ProjectName}} --label=org.opencontainers.image.revision={{.FullCommit}} --label=org.opencontainers.image.version={{.Version}}] [] false docker}
      • found artifacts           artifacts=[]
      • tempdir: dist/goreleaserdocker227045175 image=ghcr.io/netsage-project/gdg:v0.1.5-next-amd64
      • building docker image     image=ghcr.io/netsage-project/gdg:v0.1.5-next-amd64
      • running                   cmd=[docker build . -t ghcr.io/netsage-project/gdg:v0.1.5-next-amd64 --platform=linux/amd64 --pull --label=org.opencontainers.image.created=2021-07-20T13:36:54Z --label=org.opencontainers.image.title=grafana-dashboard-manager --label=org.opencontainers.image.revision=c03561b2c7e0371c9e184fb82ee90d42246e357f --label=org.opencontainers.image.version=v0.1.5-next] cwd=dist/goreleaserdocker227045175
      • #1 [internal] load build definition from Dockerfile
#1 sha256:0f00b9f5a8b829513784976c9fa5bcb360511f9e796037ba52b61997e654ea3d
#1 transferring dockerfile: 1.44kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:bd8b059e3c720714132b4f4055c30b93ef7bbf8f14e28c7ac79377629c199383
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/golang:1.16.0
#3 sha256:da6ac1169b48c19f87fbf327be168047f65b03ff676204c28ab4b497f0c5e52e
#3 ...

#4 [auth] library/golang:pull token for registry-1.docker.io
#4 sha256:5258f6355e7ddcf65c1bfd493c57027ec3619bf4f3f15dea49ea4d84b4152f2a
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/golang:1.16.0
#3 sha256:da6ac1169b48c19f87fbf327be168047f65b03ff676204c28ab4b497f0c5e52e
#3 DONE 5.8s

#7 [internal] load build context
#7 sha256:08613b6166ade16afc04f308028c677330099766b55f970b1e0efc00f8bb83a6
#7 transferring context: 1.44kB done
#7 DONE 0.0s

#5 [build-stage 1/4] FROM docker.io/library/golang:1.16.0@sha256:b49b3a05d21c645a98425a006f4449bd155e74505ee19f772dd9b7432f8bd660
#5 sha256:4ba7eb3daebaf5675075bd3d3f67099e4608d70b67de4fcc69828ce9c0ca04f1
#5 CACHED

#8 [build-stage 2/4] ADD . /go/src/github.com/netsage-project/grafana-dashboard-manager
#8 sha256:52e5b84a83d3b56091bc0a9902c922dd68148574ce8fffab056eda39116b11d8
#8 DONE 0.0s

#9 [build-stage 3/4] WORKDIR /go/src/github.com/netsage-project/grafana-dashboard-manager
#9 sha256:73b889ddb63cc66b34fa1ad4125c813798753c757be1c41efedd8b04b6df6e3e
#9 DONE 0.0s

#10 [build-stage 4/4] RUN ls -lh; pwd; make build-alpine
#10 sha256:906d00747e04dd9801ebc2986acd718f9434ba4beb49d1606afa9d9e247fa24f
#10 0.206 total 4.0K
#10 0.206 -rw-r--r-- 1 root root 1.4K Jul 20 13:33 Dockerfile
#10 0.206 /go/src/github.com/netsage-project/grafana-dashboard-manager
#10 0.208 make: *** No rule to make target 'build-alpine'.  Stop.
#10 ERROR: executor failed running [/bin/sh -c ls -lh; pwd; make build-alpine]: exit code: 2
------
 > [build-stage 4/4] RUN ls -lh; pwd; make build-alpine:
------
executor failed running [/bin/sh -c ls -lh; pwd; make build-alpine]: exit code: 2
 cmd=[docker build . -t ghcr.io/netsage-project/gdg:v0.1.5-next-amd64 --platform=linux/amd64 --pull --label=org.opencontainers.image.created=2021-07-20T13:36:54Z --label=org.opencontainers.image.title=grafana-dashboard-manager --label=org.opencontainers.image.revision=c03561b2c7e0371c9e184fb82ee90d42246e357f --label=org.opencontainers.image.version=v0.1.5-next] cwd=dist/goreleaserdocker227045175
   ⨯ release failed after 11.99s error=failed to build ghcr.io/netsage-project/gdg:v0.1.5-next-amd64: exit status 1
```

### goreleaser version

```bash
goreleaser version 0.173.2
commit: 5bcfa9042d0efd419b660a3b63c815a13d919e30
built at: 2021-07-06T08:42:56Z
built by: goreleaser
module version: v0.173.2, checksum: h1:LhajqMn6G6kaXCdAWGn5cHwL1mCbhvX4QlHDL9O33Dc=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I feel like the issue is that the cwd where the command is executed isn't correct.  I couldn't find anything regarding how to set the cwd when invoking the command.  Any assistance is appreciated.  I imagine this is a user error but I can't find anything else online that points me in the right direction.  

Thank you!
