### ISSUE TITLE
[Bug]: goreleaser failed to publish artifacts to private Gitlab

### ISSUE THREAD

**Issue by hnlq715** [goreleaser/goreleaser#2356]
### What happened?

Goreleaser failed to publish artifacts to private Gitlab, the version is Community Edition 13.12.6.

I used the $CI_JOB_TOKEN as $GITLAB_TOKEN.

```
release failed after 26.95s error=github/gitlab/gitea releases: failed to publish artifacts: GET https://gitlab.com/api/v4/projects/xxx/xxx/releases/v1.9.0-rc16: 401 {message: 401 Unauthorized}
```

### How can we reproduce this?

Sorry, but this happens in my private gitlab environment.

### goreleaser version

```bash
goreleaser version dev
module version: v0.173.2, checksum: h1:LhajqMn6G6kaXCdAWGn5cHwL1mCbhvX4QlHDL9O33Dc=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by neomantra** [comment]
If you are using a `CI_JOB_TOKEN`, you must set `JOB_TOKEN` in your custom-headers.  See [this example](https://github.com/goreleaser/goreleaser/blob/master/www/docs/customization/upload.md#customization).

```
    custom_headers:
      JOB-TOKEN: "{{ .Env.CI_JOB_TOKEN }}"
```

**Comment by hnlq715** [comment]
@neoaggelos thanks for reply :-)

I think the key reason is the url https://**gitlab.com**/api/v4/projects/xxx/xxx/releases/v1.9.0-rc16
which should be my self hosted domain...

**Comment by caarlos0** [comment]
@hnlq715 did you set `gitlab_urls` as per [docs](https://goreleaser.com/scm/gitlab/)?

**Comment by hnlq715** [comment]
Still failed, with this config append

```
uploads:
- name: production
  custom_headers:
    JOB-TOKEN: "{{ .Env.CI_JOB_TOKEN }}"

gitlab_urls:
  api: https://git.dz11.com/api/v4/
  download: https://git.dz11.com
  skip_tls_verify: false
```
