### ISSUE TITLE
behavior of archive naming with and without archive.replacements sections

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#236]
hello!

in goreleaser releases we have `Darwin` and `Linux` (capital letters) in the file names

```
goreleaser_Darwin_x86_64.tar.gz
goreleaser_Linux_arm64.deb
```

ok, but why are they not `darwin` and `linux` given the `goreleaser.yaml file`?   Why are they not using the GOOS names (all lower case?).  I don't see any archive/overriders in the file:

https://github.com/goreleaser/goreleaser/blob/master/goreleaser.yml

```yaml
build:
  env:
   - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archive:
  format_overrides:
    - goos: windows
      format: zip
```

I saw this previously in my other projects when goreleaser was not reading the yaml file, it would use the upper-case names.   When I fixed the YAML name, they started reporting correctly.  See #235

**Comment by jorinvo** [comment]
The names are currently taken from `uname`.  I guess the idea here is to have more human-readable names than the default goos/goarch values.
> By default, `replacements` replace GOOS and GOARCH values with valid outputs
 of `uname -s` and `uname -m` respectively

But as you're pointing out the current defaults might not be the best naming either.

At the moment I always have a `replacements` section to change the naming.
Ideally we would find defaults a majority of the users are happy with. 
Especially when automating the download of multiple Go-based binaries it would nice if they have a common naming pattern.

What do you think, we come up with a better default naming pattern?
cc @caarlos0, @client9 @bep 


Here are the naming patterns from some projects in comparison:

[GoReleaser](https://github.com/goreleaser/goreleaser/releases/tag/v0.18.0) | [Hugo](https://github.com/spf13/hugo/releases/tag/v0.20.7) | [sleepto](https://github.com/qvl/sleepto/releases/tag/v1.7)
------------ | ------------- | -------------
x_Darwin_i386.tar.gz | x_2.7.13_macOS-32bit.tar.gz | x_2.7.13_mac_32bit.tar.gz
x_Darwin_x86_64.tar.gz | x_2.7.13_macOS-64bit.tar.gz | x_2.7.13_mac_64bit.tar.gz
x_Linux_arm64.tar.gz | x_2.7.13_Linux-ARM64.tar.gz | x_2.7.13_linux_ARM64.tar.gz
x_Linux_armv6.tar.gz | x_2.7.13_Linux-ARM.tar.gz | x_2.7.13_linux_ARM.tar.gz
x_Linux_i386.tar.gz | x_2.7.13_Linux-64bit.tar.gz | x_2.7.13_linux_64bit.tar.gz
x_Linux_x86_64.tar.gz | x_2.7.13_Linux-32bit.tar.gz | x_2.7.13_linux_32bit.tar.gz
x_Windows_i386.zip | x_2.7.13_Windows-32bit.zip | x_2.7.13_windows_32bit.zip
x_Windows_x86_64.zip  | x_2.7.13_Windows-64bit.zip | x_2.7.13_windows_64bit.zip

**Comment by caarlos0** [comment]
Yeah, the idea of defaulting to `uname` values is that you can `curl https://blah/myapp_$(uname -s)_$(uname -m).tar.gz` or something, like it is done [here](https://github.com/goreleaser/get/blob/master/get#L24).

Maybe the defaults are not ideal though.. we can discuss and change, of course :)

**Comment by client9** [comment]
Hi guys, totally get uname concept and get discussion!  From that it led me to understand the bug better.   I'll comment on defaults separately.

I think the "bug" (feature?) I bumped into is this:

If you *do not* use any archive/replacements, everything defaults to uname values.  That's what goreleaser is doing.  All good.

If you add *one* entry to archive/replacements, everything defaults to GOOS values.  Even for things you didn't specify.   

Here's my experiment:

https://github.com/client9/misspell/blob/master/goreleaser.yml

```yaml
# goreleaser.yml

build:
  main: cmd/misspell/main.go
  binary: misspell
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
  ignore:
    - goos: darwin
      goarch: 386

archive:
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}"

  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS

snapshot:
  name_template: SNAPSHOT-{{.Commit}}
```

Notice how I'm *not* specifying anything for `linux` in the `replacements` section.

but Yet...  here are my releases:   GOOS `linux` lower case.

a62640e4122a033cf4098d2de41dc335a8ad708b668ed41ac9a1304848fb8f57  misspell_0.1.0_linux_64-bit.tar.gz
5189df7b59e54a8439324eab7da6cbd708ca724b287c432dc950788de384cfb5  misspell_0.1.0_macOS_64-bit.tar.gz

That doesn't seem right.  If you want to change one default, you really have to change defaults for every possible value.
