### ISSUE TITLE
Get binary name as template var when building artifacts.

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#2395]
**Is your feature request related to a problem? Please describe.**
Ability to use the binary name in our artifact names using name templates.

**Describe the solution you'd like**
We are using the new `goreleaser-pro` feature `Includes` and trying to make our config as boilerplate/re-usable as possible. 

We would like to set the artifact name from the builds binary name. It looks like it may be possible, because it seems some `Extra` fields get set during Go build https://github.com/goreleaser/goreleaser/blob/master/internal/builders/golang/build.go#L91-L95. 

**Additional context**
Here is an example of what we are trying to accomplish. Where `Extra.Binary` might equal `awesome` or `super` from our example.

`.goreleaser.yml`

```yml
includes:
    - from_file:
        path: .goreleaser.common.yml
    - from_file:
        path: .goreleaser.dockers.yml
builds:
    - id: awesome-linux-amd64
      main: ./cmd/awesome/main.go
      flags:
        - -trimpath
      binary: awesome
      goos:
        - linux
      goarch:
        - amd64
      env:
        - CGO_ENABLED=1
    - id: awesome-linux-arm64
      main: ./cmd/awesome/main.go
      flags:
        - -trimpath
      binary: awesome
      goos:
        - linux
      goarch:
        - arm64
      env:
        - CGO_ENABLED=1
        - CC=aarch64-linux-gnu-gcc
    - id: super-linux-amd64
      main: ./cmd/super/main.go
      flags:
        - -trimpath
      binary: super
      goos:
        - linux
      goarch:
        - amd64
      env:
        - CGO_ENABLED=1
    - id: super-linux-arm64
      main: ./cmd/super/main.go
      flags:
        - -trimpath
      binary: super
      goos:
        - linux
      goarch:
        - arm64
      env:
        - CGO_ENABLED=1
        - CC=aarch64-linux-gnu-gcc
```

`.goreleaser.dockers.yml`

```yaml
dockers:
    - goos: linux
      goarch: amd64
      image_templates:
        - '{{ .Env.DOCKER_REGISTRY_URL }}/{{ .Env.DOCKER_REGISTRY_PATH }}/{{ .Extra.Binary }}:{{ .Version }}-amd64'
      dockerfile: Dockerfile
      use: buildx
      build_flag_templates:
        - '--pull'
        - '--build-arg=SERVICENAME={{ .Extra.Binary }}'
        - '--platform=linux/amd64'
    - goos: linux
      goarch: arm64
      image_templates:
        - '{{ .Env.DOCKER_REGISTRY_URL }}/{{ .Env.DOCKER_REGISTRY_PATH }}/{{ .Extra.Binary }}:{{ .Version }}-arm64v8'
      dockerfile: Dockerfile
      use: buildx
      build_flag_templates:
        - '--pull'
        - '--build-arg=SERVICENAME={{ .Extra.Binary }}'
        - '--platform=linux/arm64/v8'
```
