### ISSUE TITLE
Templateable NFPMs signatures

### ISSUE THREAD

**Issue by Nicocha30** [goreleaser/goreleaser#2419]
**Is your feature request related to a problem? Please describe.**

NFPM signatures are not templateable. This could be useful when running CI like GitLab using "Variable Files" (https://docs.gitlab.com/ee/ci/variables/#cicd-variable-types).

**Describe the solution you'd like**

Allow templateable signatures:

```yaml
    rpm:
      signature:
        key_file: "{{ .Env.CI_SIGNING_KEY }}"
    deb:
      signature:
        key_file: "{{ .Env.CI_SIGNING_KEY }}"
```

Thanks,

Nicolas
