### ISSUE TITLE
Allow overriding of `version` that goreleaser grabs from the git environment

### ISSUE THREAD

**Issue by aaomidi** [goreleaser/goreleaser#2421]
I would like to specify a `version` for my goreleaser builds. Unfortunately not all git packages follow semver versioning, which means the packages generated by `goreleaser` might not even be installable with apt/yum/etc due to the version name.

For example:
```
$ sudo dpkg -i dist/contact-auditor_release-2021-08-16_linux_amd64.deb 
dpkg: error processing archive dist/contact-auditor_release-2021-08-16_linux_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'contact-auditor':
 'Version' field value 'release-2021-08-16': version number does not start with digit
Errors were encountered while processing:
 dist/contact-auditor_release-2021-08-16_linux_amd64.deb
 ```
 
 So what I'm asking for would look like this in the configuration file:

```
version: {{ .ENV.SOMEVARIABLE }}
builds:    
  - id: contact-auditor
    main: ./cmd/contact-auditor
    binary: contact-auditor
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

nfpms:
  - id: contact-auditor-package
    package_name: contact-auditor
    builds:
      - contact-auditor
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin

```
