### ISSUE TITLE
Allow to override brew formulae version?

### ISSUE THREAD

**Issue by creekorful** [goreleaser/goreleaser#2445]
It could be great to have the possibility to override the version set in the brew Formulae.
Something like this for example:

```yaml
brews:
  - name: example
    version: "{{ replace .Tag \"v\" \"\" }}"
    [...]
```

In my use case, I publish tags prefixed by *v* but I want this prefix to be removed in the formulae version.
What do you think? I would be interested to do the PR.

Cheers,
