### ISSUE TITLE
[Bug]: docs: Typo in the Homebrew documentation

### ISSUE THREAD

**Issue by creekorful** [goreleaser/goreleaser#2446]
While reading the documentation for the Homebrew packaging available at: https://goreleaser.com/customization/homebrew, I've noticed that the download strategy (CurlDownloadStrategy) is being suffixed by a dot which results in an invalid Ruby file.

See:
```yaml
# .goreleaser.yml
brews:
  -
    # Allows you to set a custom download strategy. Note that you'll need
    # to implement the strategy and add it to your tap repository.
    # Example: https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly
    # Default is empty.
    download_strategy: CurlDownloadStrategy.
```

I guess this dot should be removed to prevent newcomers from facing any errors.

(I've tried to find your documentation Git repository, but couldn't find it so I've raised the issue here)
