### ISSUE TITLE
[Bug]: username and the ci token variables are shown in the message with the announce integration in Gitlab

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2456]
### What happened?

We added slack announcer support to our project with the following definition:
```YAML
announce:
  slack:
    enabled: true
    message_template: 'Defaults to `{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .GitURL }}/releases/tag/{{ .Tag }}'
    channel: '#kink'
    username: 'GoReleaser'
    icon_url: 'https://github.com/goreleaser/goreleaser/raw/939f2b002b29d2c8df6efd2d1f1d0b85c4ac5ee0/www/docs/static/logo.png'
```

then, we realized that there is a username and the token in the message that was sent by GoReleaser (we are using Gitlab, btw) like the following:

```shell
Defaults to `kink v0.1.4 is out! Check it out at https://gitlab-ci-token:SyYhsAghYFTvMoxw7GAg@gitlab.private.com/poc/kink.git/releases/tag/v0.1.4
```

I think we should avoid that somehow.

### How can we reproduce this?

You can use the same `announce` section within your `.goreleaser.yml`, then run the `release` command.

### goreleaser version

```bash
goreleaser version 0.177.0
commit: eb9950e794e60a8d1e3d7ad4616ccdd579fc2db3
built by: homebrew

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
