### ISSUE TITLE
[Bug]: NFPM does not respect binary subdirectories

### ISSUE THREAD

**Issue by jigish** [goreleaser/goreleaser#2476]
### What happened?

In goreleaser 0.170.0+, if your binary is in a subdirectory, that subdirectory is trimmed out when the binary is added to the package.

here is some debug output from a 0.169.0 release:

```
      • adding binary to package  arch=amd64 dst=/apps/testapp/bin/testbin package=testapp_latest.deb src=/build/dist/testbin_linux_amd64/testbin
      • adding binary to package  arch=amd64 dst=/apps/testapp/bin/nesteddir/nestedbin package=testapp_latest.deb src=/build/dist/nestedbin_linux_amd64/nesteddir/nestedbin
```

and here is some debug output from a 0.170.0 release:

```
      • adding binary to package  arch=amd64 dst=/apps/testapp/bin/testbin package=testapp_latest.deb src=/build/dist/testbin_linux_amd64/testbin
      • adding binary to package  arch=amd64 dst=/apps/testapp/bin/nestedbin package=testapp_latest.deb src=/build/dist/nestedbin_linux_amd64/nesteddir/nestedbin
```

I believe c49c7712 is the offending commit. It seems the commit a0dd4559, which was to fix #2311, fixed the archive part of the bug, but left the nfpm part of the bug there.

### How can we reproduce this?

In `builds`, specify a binary in a subdirectory (e.g. `binary: some/dir/mybinary`).

Then, create a deb with `nfpms`.

`some/dir` will be left out of the deb, and `mybinary` will exist directly in the `bindir` specified in `nfpms`.

### goreleaser version

```bash
The subdir is omitted in 0.170.0+. 0.169.0 works as I would expect.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Oh, indeed, thanks for opening this!

**Comment by caarlos0** [comment]
this change makes all places "work the same way" regarding that... 

I see that in your case it broke things because you prepend `bin` to your binary name, any reason for that?

**Comment by gssbzn** [comment]
Thanks for getting back @caarlos0, the reason we add `bin` to the binary so when is packaged the actual `bin` is inside the `bin` folder, so for our example the downloaded package (zip|tar) looks something like

![Screenshot 2021-09-13 at 16 04 49](https://user-images.githubusercontent.com/461027/133108576-20b5aca5-0ad3-4801-8ca0-9ed73f7b9789.png)

**Comment by caarlos0** [comment]
I think that, instead, you might want to set `wrap_in_directory: bin` in your archive settings...

**Comment by gssbzn** [comment]
Tried
```yml
before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      binary: mongocli
      main: ./cmd/mongocli/mongocli.go
      ldflags:
        - -s -w -X github.com/mongodb/mongocli/internal/version.Version={{.Version}} -X github.com/mongodb/mongocli/internal/version.GitCommit={{.FullCommit}}
    id: macos
    goos: [darwin]
    goarch: [amd64,arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64,arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]
archives:
- id: linux
  builds: [linux]
  <<: &archive_defaults
    files:
      - README.md
      - LICENSE
      - third_party_notices/**/*
    replacements:
      darwin: macos
      amd64: x86_64
    wrap_in_directory: bin
  format: tar.gz
- id: macos
  builds: [macos]
  <<: *archive_defaults
  format: zip
- id: windows
  builds: [windows]
  <<: *archive_defaults
  format: zip
nfpms:
- package_name: mongocli
  vendor: MongoDB Inc.
  homepage: https://www.mongodb.com/
  maintainer: MongoDB Inc. <support@mongodb.com>
  description: MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.
  license: Apache 2.0
  bindir: /usr/bin
  builds: [linux]
  formats: [deb,rpm]
  replacements:
    amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^task:'
    - '^build(deps):'
release:
  prerelease: auto
  name_template: "MongoDB CLI {{.Version}}"
  extra_files:
    - glob: ./bin/*.msi
```

that wraps all the files, we end up with the binary, `mongocli`, README and LICENSE files all under `bin`, we like our current structure, `bin/mongocli` and README and LICENSE at the top level

And to be clear I'm not saying there's a bug but the behaviour has been changing back and forth and I'd like some clarification here, the first time caught us by surprise, at least now we have a set of tests to make sure the RPM and DEB packages work as expected and how I came here to confirm the behaviour
