### ISSUE TITLE
Enable supporting Cloud Native Application Bundles to build and push container images by using Porter

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2497]
**Is your feature request related to a problem? Please describe.**
It isn't related to a problem, it is a feature request.

**Describe the solution you'd like**
[CNAB](https://cnab.io) Cloud Native Application Bundles is a spec for packaging distributed apps. CNABs facilitate the bundling, installing, and managing of container-native apps — and their coupled services. There are different implementations to implement this spec, one of them is [Porter](https://porter.sh). Porter has a concept called mixins. Of course, there is a mixin for Docker. We can use this [docker-mixin](https://porter.sh/mixins/docker/) to build and push container images. 

**Describe alternatives you've considered**
* There is an alternative implementation for CNAB spec which name is [Duffle](https://duffle.sh).
* There is an alternative implementation for CNAB spec which name is [Docker App](https://www.docker.com/products/docker-app).

**Additional Context**
Maybe, we can take a look at this [example](https://porter.sh/examples/docker/) to see the relation between Docker and Porter.

cc: @Dentrax @erkanzileli

**Comment by dirien** [comment]
Cool idea! 👍🏻 But I cant imagine right now a workflow... Can you elaborate the idea a little bit more? Is it just scanning the different mixins (in porter speak) and update the version nummer? So it would be more of a git create PR feature for goreleaser. 

Acutally this is somthing i would welcome for homebrew-core. I dont want to write a bot to update the Forumla and crate a PR...

**Comment by carolynvs** [comment]
I'm one of the Porter maintainers and would be happy to help with this. I'm not quite clear on what workflow you are aiming for but can help answer questions on how to use Porter/bundles in general, or integrating with it through mixins.

**Comment by developer-guy** [comment]
@carolynvs thanks for your interest, really appreciate that. Let me explain my idea here. Please fix me if I'm wrong but at the end of the day, Porter needs `porter.yaml` with a bunch of information to install the bundle. Here, to build and push container images, we should use docker-mixin in Porter, so I was thinking that if I create a `porter.yaml` file with the information that I take from the `goreleaser.yaml` file, then execute the following command, this all should work:

ping @dirien @Dentrax @erkanzileli 

```shell
$ porter bundles install porter.yaml --allow-docker-host-access 
```

<details>
<summary>
porter.yaml
</summary>
```YAML
name: whalesay
version: 0.1.2
description: "An example bundle that uses docker through the magic of whalespeak"
registry: getporter

required:
  - docker

parameters:
  - name: msg
    description: a message for the whales to speak
    type: string
    default: "whale hello there!"
    applyTo:
      - say

mixins:
  - docker

install:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - Hello World
      
upgrade:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - World 2.0

say:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - "{{ bundle.parameters.msg }}"

uninstall:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - Goodbye World
```
</details>

**Comment by carolynvs** [comment]
It sounds like that you would like to have the bundle help with part of users CI workflow: building docker images with their go binary and then publishing them. I'm assuming to help build/publish the [images specified in goreleaser](https://goreleaser.com/customization/docker/) but if I'm wrong, ignore everything I'm about to say. 😁 

```yaml
# .goreleaser.yml
dockers:
  -
    image_templates:
    - "myuser/myimage"
    use: porter
``` 

The most efficient way to do this with Porter would be to build a bundle ahead of time. Something that you could define in this repository and publish the bundle to a docker registry, so that everyone else can use the pre-compiled bundle. The bundle would have parameters for things like: the binary to include in the docker image, the template dockerfile, and the image template. This bundle's porter.yaml would use these parameters to handle building/publishing their binary in a docker image.

Here is something I made up off the top of my head but should give you an idea of what goes in the porter.yaml:
```yaml
# porter.yaml
name: goreleaser

mixins:
- docker

parameters:
- name: template
- name: dockerfile
   type: file
   path: /cnab/app/Dockerfile
- name: binary
   type: file
   path: /cnab/app/binary

credentials:
  - name: user
    env: DOCKER_USERNAME
  - name: password
    env: DOCKER_PASSWORD

customActions:
  publish: # Tell porter that it doesn't need to keep a record of running the publish action
    modifes: false
    stateless: true

publish:
- docker:
    build:
      tag: "{{ bundle.parameters.template}}"
- docker:
    login: # login using the DOCKER_USERNAME and DOCKER_PASSWORD env vars
- docker:
    push:
      image: "{{ bundle.parameters.template}}" # this needs a small fix to the docker mixin so you don't have to specify the image name and tag separately

install:
# noop
```

Inside everyone's CI environment, if their goreleaser.yaml used porter, then the bundle you built ahead of time would be called with something like this:

```
porter invoke --action=publish --param binary=./mybin --param dockerfile=./Dockerfile --param template=user/repo --cred ./docker-creds.yaml --reference goreleaser/porter-docker-publish:v1.2.3
```

* I am using invoke because I doubt you want to keep a record of running this bundle. Normally when you run install, porter will write a record out so that you can manage the installation of that bundle over time (useful for software installations, not so much for publishing docker images). When you use invoke, you are telling porter that you don't care about that part, you just want to run the logic in that publish action defined in porter.yaml.
* The parameter values are generated using the goreleaser.yaml.
* The --cred flag gives porter a hint as to where to find their docker login credentials to inject into the bundle when it runs. 
    ```yaml
    name: docker
    credentials:
      - name: user
        source:
          env: DOCKER_USER
      - name: password
        source:
          env: DOCKER_PASSWORD
    ```

Then when the bundle ran it would build their binary into a docker image and publish it. 🎉
