### ISSUE TITLE
filter pipes by id on the command line

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#2498]
**Is your feature request related to a problem? Please describe.**
Some Go modules within our company have a lot of micro-services, it can take a while to build all of them. Sometimes devs would like to only build and deploy a single service in order to save time.

**Describe the solution you'd like**
We would like a way to filter pipes that get ran by their IDs by passing a `--filter-ids` argument to the command line. 

The filter argument could be a regex of the pipe IDs we want to run. For example if we have micro-services `monkey`, `zebra` and `snake` in the Go module and we only want to build and release `monkey` and `snake` the filter argument might look like `--filter-ids "alpha.*|zebra.*"` (https://regex101.com/r/F8q1lu/1).

Example goreleaser YAML (shortened for brevity):

```yaml
builds:
    - id: monkey-build
    - id: zebra-build
    - id: snake-build
archives:
    - id: monkey-archive
    - id: zebra-archive
    - id: snake-archive
nfpms:
    - id: monkey-deb
    - id: zebra-deb
    - id: snake-deb
```

**Describe alternatives you've considered**
- A different goreleaser file per service.
- Automatically generate the goreleaser file at build time to only include the services we want to build.
