### ISSUE TITLE
[Bug]: publishing multiple artifacts broken from v0.178.0 to v0.179.0

### ISSUE THREAD

**Issue by mmllc-jsilverman** [goreleaser/goreleaser#2506]
### What happened?

I have a build that creates two tarballs, one for Darwin and one for Linux

The tarballs get created, a checksums file gets created OK

On publish, the upload step uploads checksums and Darwin tarball OK

But the Linux tarball gets the following error (I sanitized the names of the repo and org. Also, this error is all on one line -- i broke lines to make it easier to read):

```
⨯ release failed after 86.81s error=github/gitlab/gitea releases:
failed to publish artifacts: failed to upload <REPO_NAME> after 1 tries:
POST https://uploads.github.com/repos/<gh_org>/<repo_name>/releases/50153692/assets?name=<repo_name>2.1.2_Linux_x86_64.tar.gz:
422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

I had done a release on this repo only about 2 weeks ago and it ran fine.

I actually went into the GH API and deleted the uploaded assets -- maybe that's why this error occured? And re-ran the job; but the error happened identically.

Finally, I checked the last known working version of goreleaser and pinned the GH Actions run to use that. The build ran fine with no errors

The last known working was v0.178.0

The errors happened to me on v0.179.0

### How can we reproduce this?

Build repo to release tarballs for both Darwin and Linux, and see that the second tarball gets this error

### goreleaser version

```bash
0.179.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This was run inside a Github Actions runner; I can't do manual troubleshooting inside the runner. Therefore I was not able to run `goreleaser check`

**Comment by caarlos0** [comment]
Can you share your config file?

**Comment by mmllc-jsilverman** [comment]
Howdy. I'm not sure if you mean github actions workflow or something else? The github workflow is as follows:

```name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.178.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Where it currently says `          version: v0.178.0` -- it used to say `          version: latest`

Pinning it to `v0.178.0` fixed the issue I was having

**Comment by caarlos0** [comment]
Hey, sorry, I meant the  goreleaser.yaml...

The full log output with --debug would help a ton as well

**Comment by mmllc-jsilverman** [comment]
Hey. I'm not sure how to get this with --debug -- this runs on a github actions runner. I am unlikely to run this again with the broken goreleasrer since this is producing production artifacts and it is now working for me.

(I've sanitized the following content to remove institution-specific names.)

Here is the Github Actions log output from the broken run:

```
Run goreleaser/goreleaser-action@v2
  with:
    version: latest
    args: release --rm-dist
    distribution: goreleaser
    workdir: .
    install-only: false
  env:
    GOROOT: /opt/hostedtoolcache/go/1.16.8/x64
    GITHUB_TOKEN: ***
Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.179.0/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/bd089847-32d5-4982-a001-9ef9222d1e1f -f /home/runner/work/_temp/4c838162-d018-46f3-917a-627b92114e2e
GoReleaser latest installed successfully
v2.1.2 tag found for commit '8754868'
/opt/hostedtoolcache/goreleaser-action/0.179.0/x64/goreleaser release --rm-dist
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=875486843b20d8e3d64dfb129fa0bed05106c193 latest tag=v2.1.2
   • parsing tag      
   • running before hooks
   • setting defaults 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • loading go mod information
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images    
      • docker manifests 
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • discord          
      • reddit           
      • slack            
      • teams            
      • twitter          
      • milestones       
   • snapshotting     
   • checking ./dist  
   • loading go mod information
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/server_darwin_amd64/project_name-server
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/server_linux_amd64/project_name-server
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/stream_darwin_amd64/project_name-stream
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/stream_linux_amd64/project_name-stream
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/archive_linux_amd64/project_name-archive
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/archive_darwin_amd64/project_name-archive
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/archive-clean_darwin_amd64/project_name-archive-clean
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/archive-clean_linux_amd64/project_name-archive-clean
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/origin-archive_darwin_amd64/origin-archive
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/origin-archive_linux_amd64/origin-archive
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/replay-server_linux_amd64/project_name-replay-server
      • building                  binary=/home/runner/work/<project_name>/<project_name>/dist/replay-server_darwin_amd64/project_name-replay-server
   • archives         
      • creating                  archive=dist/<project_name>_2.1.2_Linux_x86_64.tar.gz
      • creating                  archive=dist/<project_name>_2.1.2_Darwin_x86_64.tar.gz
   • creating source archive
   • linux packages   
   • snapcraft packages
   • calculating checksums
      • checksumming              file=<project_name>_2.1.2_Darwin_x86_64.tar.gz
      • checksumming              file=<project_name>_2.1.2_Linux_x86_64.tar.gz
   • signing artifacts
   • docker images    
   • publishing       
      • blobs            
      • http upload      
      • custom publisher 
      • artifactory      
      • docker images    
      • docker manifests 
      • signing docker images
      • snapcraft packages
      • github/gitlab/gitea releases
         • creating or updating release repo=<org_name>/<project_name> tag=v2.1.2
         • release updated           url=https://github.com/<org_name>/<project_name>/releases/tag/v2.1.2
         • uploading to release      file=dist/<project_name>_2.1.2_checksums.txt name=<project_name>_2.1.2_checksums.txt
         • uploading to release      file=dist/<project_name>_2.1.2_Linux_x86_64.tar.gz name=<project_name>_2.1.2_Linux_x86_64.tar.gz
         • uploading to release      file=dist/<project_name>_2.1.2_Darwin_x86_64.tar.gz name=<project_name>_2.1.2_Darwin_x86_64.tar.gz
         • failed to upload artifact, will retry artifact=<project_name>_2.1.2_Linux_x86_64.tar.gz error=POST https://uploads.github.com/repos/<org_name>/<project_name>/releases/50153692/assets?name=<project_name>_2.1.2_Linux_x86_64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] try=1
   ⨯ release failed after 86.81s error=github/gitlab/gitea releases: failed to publish artifacts: failed to upload <project_name>_2.1.2_Linux_x86_64.tar.gz after 1 tries: POST https://uploads.github.com/repos/<org_name>/<project_name>/releases/50153692/assets?name=<project_name>_2.1.2_Linux_x86_64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.179.0/x64/goreleaser' failed with exit code 1
```

Here is the .goreleaser.yml:

```
builds:
  - id: "server"
    main: ./cmd/project_name-server/main.go
    binary: project_name-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - id: "stream"
    main: ./cmd/project_name-stream/main.go
    binary: project_name-stream
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - id: "archive"
    main: ./cmd/project_name-archive/main.go
    binary: project_name-archive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - id: "archive-clean"
    main: ./cmd/project_name-archive-clean/main.go
    binary: project_name-archive-clean
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - id: "origin-archive"
    main: ./cmd/origin-archive/main.go
    binary: origin-archive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - id: "replay-server"
    main: ./cmd/project_name-replay-server/main.go
    binary: project_name-replay-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - none*
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

**Comment by caarlos0** [comment]
oh, I think I know

you are running goreleaser against all commits and PRs... your config should be:

```yaml
on:
  push:
    tags:
      - '*'
```

see https://goreleaser.com/ci/actions/#run-on-new-tag for more info.

What likely happened is that it started multiple jobs and one "mess" with the other...

Closing as not a bug.
