### ISSUE TITLE
[Bug]: field slack not found in type config.Announce

### ISSUE THREAD

**Issue by mrz1836** [goreleaser/goreleaser#2513]
### What happened?

I attempted to add a slack announce configuration but I keep getting an error:

```script
$ goreleaser check
   • loading config file       file=.goreleaser.yml
   ⨯ command failed          error=yaml: unmarshal errors:
  line 34: field slack not found in type config.Announce
```

### How can we reproduce this?

Here is the config file I am using:

```yaml
# Make sure to check the documentation at http://goreleaser.com
# ---------------------------
# GENERAL
# ---------------------------
before:
  hooks:
    - make all
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^test:'

# ---------------------------
# BUILDER
# ---------------------------
build:
  skip: true

# ---------------------------
# Github Release
# ---------------------------
release:
  prerelease: true
  name_template: "Release v{{.Version}}"

# ---------------------------
# Announce
# ---------------------------
announce:
  slack:
    # Weather its enabled or not.
    # Defaults to false.
    enabled: true

    # Message template to use while publishing.
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .GitURL }}/releases/tag/{{ .Tag }}`
    # message_template: 'Awesome project {{.Tag}} is out!'

    # The name of the channel that the user selected as a destination for webhook messages.
    channel: '#test_slack'

    # Set your Webhook's username.
    # username: ''

    # Emoji to use as the icon for this message. Overrides icon_url.
    # icon_emoji: ''

    # URL to an image to use as the icon for this message.
    # icon_url: ''
```

### goreleaser version

```bash
goreleaser version dev
module version: v0.174.2, checksum: h1:EltDZkVGq0mC2Aqgc7uGT7A0aaXdt4KPV6OxTmUG4pk=
https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I checked the box for GoReleaser Check - but that's where it's failing.

I followed these instructions:

https://goreleaser.com/customization/announce/#slack
