### ISSUE TITLE
[Bug]: couldn't guess project_name, please add it to your config

### ISSUE THREAD

**Issue by stack72** [goreleaser/goreleaser#2520]
### What happened?

Since upgrading from v0.179 to v0.180, I have started getting the error:

```
   ⨯ release failed after 107.91s error=couldn't guess project_name, please add it to your config
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.180.0/x64/goreleaser' failed with exit code 1
```

No code has changed in my .goreleaser.yml file

```
archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
blobs:
- bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
  provider: s3
  region: us-west-2
builds:
- binary: pulumi-resource-azuread
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/pulumi/pulumi-azuread/provider/v5/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-azuread/
changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

```

### How can we reproduce this?

Error with v0.180.0 - https://github.com/pulumi/pulumi-azuread/runs/3719835886?check_suite_focus=true#step:9:50

Successful build with v0.179.0 - https://github.com/pulumi/pulumi-azuread/runs/3626082281?check_suite_focus=true#step:9:37

.goreleaser.yml file - https://github.com/pulumi/pulumi-azuread/blob/master/.goreleaser.yml

### goreleaser version

```bash
v0.180.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
