### ISSUE TITLE
skip all anouncers on patch releases

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#2523]
would be nice to have a way to skip announce based on a template, e.g.

```yaml
announce:
  skip: '{{gt .Patch 0}}'
  discord:
    # etc
```
