### ISSUE TITLE
linux ppc64le support

### ISSUE THREAD

**Issue by abduld** [goreleaser/goreleaser#255]
Currently I get

`Skipped invalid build target: linux/ppc64le`

even if I have

```
build:
  main: ./main.go
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - ppc64le
  ignore:
    - goos: darwin
      goarch: ppc64le
    - goos: windows
      goarch: ppc64le
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm
    - goos: linux
      goarch: arm
      goarm: 7
```

Is it possible to enable ppc64le linux target.

thank you
