### ISSUE TITLE
[Bug]: consider using top level environment variables within env section in docker section

### ISSUE THREAD

**Issue by developer-guy** [goreleaser/goreleaser#2585]
### What happened?

I noticed that while I was working on an issue about adding `google/ko` support to one of the supported builder engines. There is a special variable called `KO_DOCKER_REPO` and I wanted to define this variable within the top-level `env` section and use it within the `docker` section like the following `.goreleaser.yml`:

<details>
<summary>.goreleaser.yml </summary>

```YAML
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

env:
  - KO_DOCKER_REPO=ghcr.io/goturkiye
 
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/GoTurkiye/hello-world-cli/cmd.GitCommit={{ .Commit }} -X github.com/GoTurkiye/hello-world-cli/cmd.Version={{ .Version }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
    - "{{ .ProjectName }}"
    - "{{ .ProjectName }}:{{ .Tag }}"
    - "{{ .ProjectName }}:v{{ .Major }}"
    goos: linux
    goarch: amd64
    use: ko
```
</details>

Here is the output of the command `goreleaser release --rm-dist`:

```shell
• docker images
      • building docker image     image=hello-world-cli
   ⨯ release failed after 4.97s error=failed to build container image, please specify KO_DOCKER_REPO environment variable
```

### How can we reproduce this?

You can try setting some environment variable within the top-level `env` section and try to use it within `docker` section.

### goreleaser version

```bash
goreleaser version 0.182.1
commit: d5638991c81f81b1757b24c740b58344efb2dbc0
built by: homebrew

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
