### ISSUE TITLE
[Bug]: versions > 0.179.0 not updating Github release's release-notes when passed as an argument

### ISSUE THREAD

**Issue by anGie44** [goreleaser/goreleaser#2588]
### What happened?

In our Github Actions workflow, we are using the `goreleaser-action` github action and passing in a markdown file containing the release notes e.g.

```
  - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --release-notes /tmp/RELEASE-NOTES.md --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

When using this Github Action a while ago (goreleaser `v0.179.0`) , the release notes used to be pasted into the github release visible in the UI
<img width="1158" alt="Screen Shot 2021-10-15 at 4 21 02 PM" src="https://user-images.githubusercontent.com/13805595/137552354-e051ff59-3856-44ff-99ca-f4ff741c635e.png">

This behavior seems to be present since `v0.180.0` of goreleaser as pinning the github action to `v0.179.0` and `v0.180.0` produce different results..the following snapshot is the result of pinning the github action e.g.

```
  - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.180.0
          args: release --release-notes /tmp/RELEASE-NOTES.md --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

<img width="1190" alt="Screen Shot 2021-10-15 at 4 21 37 PM" src="https://user-images.githubusercontent.com/13805595/137552498-6e353e78-ba62-4541-9118-b27261fd085b.png">

### How can we reproduce this?

https://github.com/anGie44/terraform-provider-awscc (fork for experiments; original: https://github.com/hashicorp/terraform-provider-awscc)

Here are some example releases i've experimented by pinning to specific goreleaser versions in the `goreleaser-action` Github Action

### goreleaser version

```bash
v0.182.1 (when not pinning the version in the goreleaser-action)
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Thanks in advance! Lmk if there's any more info I can provide that could help as reference 😃
