### ISSUE TITLE
Release multiple binaries

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#259]
Add a `binaries` or something like that to the config file.

The idea is in [this comment](https://github.com/goreleaser/goreleaser/issues/49#issuecomment-300814646) by @hellais:

> This is currently the limiting fact for me using goreleaser for my releases. I have a single package where I would like to ship multiple binaries that each are generated from a separate main.go. I would like all the binaries to end up inside of the final .tar.gz so having separate goreleaser.yml files is not an option.
> 
> Could this issue be re-opened or should I file another one?

**Comment by caarlos0** [comment]
This would actually break lots of things. My idea so far is:

```yml
name: MyProject
build:
  binaries:
     - main: ./foo/main.go
        name: foo
     - main: ./bar/main.go
        name: bar
```

So, `build` will lost the options `binary` and `main`. Name templates related to archiving and etc would look into the root `name` property. We would have to change the brew templates to consider multiple binaries inside a single archive.

What do you guys think?
