### ISSUE TITLE
[Bug]: fix: add windows and arm 6/7 to invalid target

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2592]
### What happened?

Goreleaser creates a windows binary for arm 6 / 7 architecture. AFAIK only windows 10 supports ARM64.

### How can we reproduce this?

Create a build with

```yaml
...
goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
 ...
````
![image](https://user-images.githubusercontent.com/38325136/137974113-c7a981ca-d475-4e82-8f17-67abad338d6c.png)

### goreleaser version

```bash
goreleaser version 0.182.1
commit: d5638991c81f81b1757b24c740b58344efb2dbc0
built at: 2021-10-13T03:10:07Z
built by: goreleaser
module version: v0.182.1, checksum: h1:cKRlHfbMxejiyMCNACsl82slFXEW+k9RggADv6/Akqg=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Will create a fix for this
