### ISSUE TITLE
[Proposal] SBOM generation

### ISSUE THREAD

**Issue by VinodAnandan** [goreleaser/goreleaser#2597]
The proposal is to publish SBOM (“Software Bill of Materials”) artifacts for goreleaser as part of each release.

e.g.:  https://github.com/CycloneDX/cyclonedx-gomod#goreleaser-
https://github.com/CycloneDX/cyclonedx-gomod/releases/tag/v1.0.0

**Comment by caarlos0** [comment]
FWIW, `go version -m` can have a wrong output if using `go mod vendor`.

https://carlosbecker.com/posts/supply-chain-goreleaser-go-mod-proxy/

**Comment by caarlos0** [comment]
please take a look at #2618

**Comment by wagoodman** [comment]
_(this comment is meant to be a follow on to https://github.com/goreleaser/goreleaser/pull/2618#issuecomment-957825874 from the POC PR)_

While chatting the POC over with @spiffcs and @luhring we started to wonder if it made sense to explore the idea of raising SBOMs as a first-class artifact type. This new `sbom` artifact type would be defined as "a description of another artifact or set of artifacts". It would have it's own `sboms` config section and would act/look very similar to the `signs` config section. 

The docs for such a `sboms` section might look like this:

```yaml
# .goreleaser.yml
sboms:
  -
    # ID of the bom config, must be unique.
    #
    # Defaults to "default".
    id: foo

    # List of Names/templates of the bom files created at this step.
    #
    # Available environment variables:
    # - '${artifact}': the path to the artifact that will be cataloged
    # - '${artifactID}': the ID of the artifact that will be cataloged
    #
    # Defaults to empty list.
    sbom: 
      - "${artifact}.spdx.sbom"

    # Path to the signature command
    cmd: syft

    # Command line templateable arguments for the command
    args: ["-o", "spdx", "--file", "${bom}", "${artifact}"]

    # Which artifacts to catalog
    #
    #   source:   source archive
    #   package:  linux packages (deb, rpm, apk)
    #   archive:  archives from archive pipe
    #   binary:   binaries output from the build stage
    #   container:  reference to the unpublished container image 
    #... there maybe other artifacts that make sense here!
    #
    # Defaults to `binary`
    artifacts: container

    # IDs of the artifacts to catalog.
    #
    # If `artifacts` is source this fields has no effect.
    #
    # Defaults to empty (which implies no filtering).
    ids:
      - foo
      - bar

```

With example usage:

```yaml
sboms:
  - 
    id: source-sbom
    cmd: syft
    args: ["dir:${artifact}", "--file", "${artifact}.source.sbom"]
    sbom: ["${artifact}.source.sbom"]
    artifacts: source

  - 
    id: binary-sbom
    cmd: syft
    args: ["${artifact}", "--attest", "${artifact}.attestation.json"]
    sbom:
      - "${artifact}.sbom"
      - "${artifact}.attestation.json"
    artifacts: binary

  - 
    id: container-sbom
    cmd: syft
    args: ["docker:${artifact}"]
    sbom: ["${artifact}.container.sbom"]
    artifacts: docker

```

When running goreleaser you might see output like so:
```
...
  • building binaries
      • building                  binary=/Users/wagoodman/code/myproject/dist/myproject_linux_arm64/myproject
      • building                  binary=/Users/wagoodman/code/myproject/dist/myproject_linux_amd64/myproject
      • building                  binary=/Users/wagoodman/code/myproject/dist/myproject-win_windows_amd64/myproject.exe
...
   • creating source archive
      • creating source archive   file=myproject-1.31.0.tar.gz
...
   • calculating checksums
...
   • signing artifacts
...
   • docker images
      • building docker image     image=my/project:v1.31.0
   • cataloging artifacts
      • cataloging                   artifact=/Users/wagoodman/code/myproject/dist/myproject_linux_arm64/syft cmd=syft
      • cataloging                   artifact=/Users/wagoodman/code/myproject/dist/myproject_linux_amd64/syft cmd=syft
      • cataloging                   artifact=/Users/wagoodman/code/myproject/dist/myproject-win_windows_amd64/syft.exe cmd=syft
      • cataloging                   file=myproject-1.31.0.tar.gz cmd=syft
      • cataloging                   image=my/project:v1.31.0 cmd=syft
...
```

This creates 5 SBOMs and 3 attestations: 
- one SBOM for each built binary (3)
- one attestation for each binary SBOMs (3)
- one SBOM for the source tar
- one SBOM for the container image created
Each generated output file from the `sboms` section gets attached to the GitHub release (similar to signatures today).

This example implies that this new bom stage occurs after all building, signing, and packaging has been completed... which additionally means that signing/attestation of SBOMs would be an out-of-band operation by the SBOM tool itself. (note: syft does not support attestations, but was used to illustrate how goreleaser could support multiple SBOM artifacts being created).

This is a simple example that is meant to be illustrative, so isn't perfect. I also haven't checked the internals of goreleaser to see if these suggestions are easily achievable or impossible yet.

Happy to chat / explore further on this!
