### ISSUE TITLE
[Bug]:   flag provided but not defined: -tags

### ISSUE THREAD

**Issue by opvexe** [goreleaser/goreleaser#2605]
### What happened?

```
   ⨯ release failed after 5.04s error=failed to build for darwin_amd64: # gitlab.xiadata.com/goboot/query/cmd
flag provided but not defined: -tags
usage: link [options] main.o
```

### How can we reproduce this?

```
  - id: query
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: amd64
    main: ./query/cmd/
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=gcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
      - MACOSX_DEPLOYMENT_TARGET=10.11
    ldflags:
      - --tags='json1'
 ```

Run: 

```
go run --tags='json1'  main.go
```

### goreleaser version

```bash
goreleaser version dev
module version: v0.162.0, checksum: h1:u3Ba1DXY3qn1DUDr2If30irLWRg7RhkwFY3Y1XiZrzU=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
