### ISSUE TITLE
[Bug]: `docker_manifest` stage can't reference unpublished images from `dockers` stage

### ISSUE THREAD

**Issue by ecordell** [goreleaser/goreleaser#2606]
### What happened?

Adding `skip_push: true` to docker steps causes the subsequent manifest step to fail:

```
   • docker images
      • building docker image     image=quay.io/authzed/spicedb:v1.1.1-devel-amd64
      • building docker image     image=quay.io/authzed/spicedb:v1.1.1-devel-arm64
      • pipe skipped              error=docker.skip_push is set
   • publishing
      • docker images
      • docker manifests
         • creating docker manifest  images=[quay.io/authzed/spicedb:v1.1.1-devel-amd64 quay.io/authzed/spicedb:v1.1.1-devel-arm64] manifest=quay.io/authzed/spicedb:v1.1.1-devel
   ⨯ release failed after 10.69s error=docker manifests: failed to publish artifacts: failed to create quay.io/authzed/spicedb:v1.1.1-devel: exit status 1: no such manifest: quay.io/authzed/spicedb:v1.1.1-devel-amd64
```

### How can we reproduce this?

This is the config we have currently for publishing multi-arch images:

```yaml
dockers:
  - image_templates:
      - &amd_image "quay.io/authzed/spicedb:v{{ .Version }}-amd64"
    dockerfile: &dockerfile "Dockerfile.release"
    skip_push: true
    goos: "linux"
    goarch: "amd64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - &arm_image "quay.io/authzed/spicedb:v{{ .Version }}-arm64"
    dockerfile: *dockerfile
    skip_push: true
    goos: "linux"
    goarch: "arm64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "quay.io/authzed/spicedb:v{{ .Version }}"
    image_templates:
      - *amd_image
      - *arm_image
  - name_template: "quay.io/authzed/spicedb:latest"
    image_templates:
      - *amd_image
      - *arm_image
```

This works well, but it publishes three tagged images (for example):

- `quay.io/authzed/spicedb:v1.1.1-amd64`
- `quay.io/authzed/spicedb:v1.1.1-arm64`
- `quay.io/authzed/spicedb:v1.1.1`

This technically doesn't cause any problems, but it would be much nicer to only push the final multiarch image (`quay.io/authzed/spicedb:v1.1.1`). OCI image clients will either pick the right arch automatically or provide options for a user to pick the underlying image, so the extra tags are unneeded. Adding `skip_push: true` causes the error above.

### goreleaser version

```bash
goreleaser version 0.183.0
commit: be6199f08167cc85b0b16cefc02d8106237853b1
built by: homebrew
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
