### ISSUE TITLE
[Bug]: Missing permissions to publish on Github

### ISSUE THREAD

**Issue by shibumi** [goreleaser/goreleaser#2642]
### What happened?

I am working on keyless signatures with cosign and goreleaser for the in-toto project.
The signing part works well, but the release via goreleaser throws the following error:

```
   • publishing       
      • github/gitlab/gitea releases
         • creating or updating release repo=shibumi/in-toto-golang tag=v0.3.3-test.5
         • release updated           url=
   ⨯ release failed after 51.89s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://api.github.com/repos/shibumi/in-toto-golang/releases: 403 Resource not accessible by integration []
Error: The process '/opt/hostedtoolcache/goreleaser-action/0.180.2/x64/goreleaser' failed with exit code 1
```

### How can we reproduce this?

The related project is here: https://github.com/shibumi/in-toto-golang/tree/shibumi/add-go-releaser

The github action file looks like this:
```yaml
name: release
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Format Unix
        if: runner.os == 'Linux'
        run: test -z $(go fmt ./...)
      - name: Test
        run: go test -covermode atomic -coverprofile='profile.cov' ./...
      - name: Send coverage
        if: runner.os == 'Linux'
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.1'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v0.180.2'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
```

The goreleaser yaml looks like this:
```yaml
project_name: in-toto
builds:
  - ldflags:
      - "-s -w"
      - "-extldflags=-zrelro"
      - "-extldflags=-znow"
      - "-X cmd.tag={{.Version}}"
      - "-X cmd.commit={{.FullCommit}}"
      - "-X cmd.date={{.CommitDate}}"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    args: ["sign-blob", "-oidc-issuer=https://token.actions.githubusercontent.com", "-output=${signature}", "${artifact}"]
    artifacts: all
```

### goreleaser version

```bash
0.180.2 installed via github actions installer.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
