### ISSUE TITLE
[Bug]: changelog is too long

### ISSUE THREAD

**Issue by till** [goreleaser/goreleaser#2647]
### What happened?

I am re-publishing an old code base that hasn't been tagged before and currently the github release fails as it exceeds the number of allowed characters for the changelog:

```
  ⨯ release failed after 167.72s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://api.github.com/repos/org/repository/releases: 422 Validation Failed [{Resource:Release Field:body Code:custom Message:body is too long (maximum is 125000 characters)}]
```

### How can we reproduce this?

Have a changelog with more than `125000` characters. Unfortunately I can't give you access to the builds.

The workflow I am using is very straight forward:

```
---
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: docker/login-action@v1
        with:
          registry: registry.example.org
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Everything works (building and publishing docker images), just the release on Github doesn't get created and therefor no binaries are uploaded.

### goreleaser version

```bash
Via `goreleaser/goreleaser-action@v2`: v0.184.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
