### ISSUE TITLE
goreleaser pipeline should fail by default in case `cmd` not found

### ISSUE THREAD

**Issue by Dentrax** [goreleaser/goreleaser#2651]
**Is your feature request related to a problem? Please describe.**

Consider the following configuration:
```yaml
signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args: ["sign-blob", "-key=cosign.key", "-output=${signature}", "${artifact}"]
    artifacts: checksum
``` 

Notice that we used `cmd` variable here, which means _pipeline_ will call the `cosign` in the current step. But in case if we did not install the "given cmd" before in the system, goreleaser skipping the current step and does not error out.

What we expected is that command should fail, but it did not. That's because `cosign` was not installed [in the workflow.](https://github.com/Dentrax/ko/runs/4157383820?check_suite_focus=true)

**Describe the solution you'd like**
We can add an option called i.e. `fail_fast: true` or `fail_on_cmd_error: true` etc. to [global build](https://goreleaser.com/customization/build/) options.

**Describe alternatives you've considered**

**Additional context**

GoReleaser: [v0.183.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0)

_You can consider assigning us to the issue if you agree with the concern._

cc: @developer-guy @erkanzileli
