### ISSUE TITLE
Ability to Use Templates With checksum and release extra_files

### ISSUE THREAD

**Issue by bflad** [goreleaser/goreleaser#2655]
**Is your feature request related to a problem? Please describe.**

As part of the required release process for newer Terraform Providers, a "manifest" file that matches the versioned naming convention of other release files must be included so the Terraform Registry ingest process works correctly: https://www.terraform.io/docs/plugin/framework/publishing.html#add-a-version-manifest

It's currently possible to use the `extra_files` `glob` support to fuzzy match the correct file naming (as shown below), however this could introduce false negatives or positives. Given that other portions of the `goreleaser` configuration support templates, it would be wonderful if it could be included with `extra_files` as well for parity.

**Describe the solution you'd like**

The configuration could either support templates in the existing `glob` field, e.g.

```yaml
checksum:
  # ... other configuration ...
  extra_files:
    - glob: {{ .ProjectName }}_{{ .Version }}_manifest.json
release:
  # ... other configuration ...
  extra_files:
    - glob: {{ .ProjectName }}_{{ .Version }}_manifest.json
```

Or the extra files configuration could separately include a new template-supported field, e.g. `name_template`

```yaml
checksum:
  # ... other configuration ...
  extra_files:
    - name_template: {{ .ProjectName }}_{{ .Version }}_manifest.json
release:
  # ... other configuration ...
  extra_files:
    - name_template: {{ .ProjectName }}_{{ .Version }}_manifest.json
```

**Describe alternatives you've considered**

A current workaround that is possible today with `goreleaser` is moving/copying the file to the correct naming convention prior to executing the release then glob-ing against the expected pattern in `extra_files`, e.g.

```yaml
checksum:
  # ... other configuration ...
  extra_files:
    - glob: 'terraform-provider-*_*_manifest.json'
release:
  # ... other configuration ...
  extra_files:
    - glob: 'terraform-provider-*_*_manifest.json'
```

Unfortunately there is room for false negatives and false positives and it is a little unclear what exactly is desired without additional configuration comments.

**Additional context**

Thank you very much for this excellent project! Please let me know if you are interested in the feature and I would be happy to contribute the changes.

Aside: I will be filing a separate feature request to see if we could also have extra files support static file renaming as part of this process (so it doesn't need to also be done outside `goreleaser`), but it would likely best be paired with this feature so it matches a "source" and "target". Filed as https://github.com/goreleaser/goreleaser/issues/2656.
