### ISSUE TITLE
Ability to Remap Source Names with checksum and release extra_files

### ISSUE THREAD

**Issue by bflad** [goreleaser/goreleaser#2656]
**Is your feature request related to a problem? Please describe.**

As part of the required release process for newer Terraform Providers, a "manifest" file that matches the versioned naming convention of other release files must be included so the Terraform Registry ingest process works correctly: https://www.terraform.io/docs/plugin/framework/publishing.html#add-a-version-manifest

This file is expected to be fairly static in nature and included with each Terraform Provider project, similar to managing a NPM module `package.json` in that ecosystem. The below examples use `terraform-registry-manifest.json`, however there is not an expected naming standard of the source since the Terraform Registry's requirement is the final versioned naming during its ingress process. 

**Describe the solution you'd like**

The extra files configuration could introduce a source file name/template field, then paired with a "static" target file name/template field (see also: https://github.com/goreleaser/goreleaser/issues/2655), automatically handle the file name remapping as part of the release process, without actually copying/moving the file:

```yaml
checksum:
  # ... other configuration ...
  extra_files:
    - name_template: {{ .ProjectName }}_{{ .Version }}_manifest.json
      source: terraform-registry-manifest.json
release:
  # ... other configuration ...
  extra_files:
    - name_template: {{ .ProjectName }}_{{ .Version }}_manifest.json
      source: terraform-registry-manifest.json
```

**Describe alternatives you've considered**

Developers could theoretically move the file to match the next release naming before each release. This would be very tedious!

A more automated workaround that is possible today with `goreleaser` is moving/copying the file to the correct naming convention prior to executing the release, e.g. in GitHub Actions

```yaml
      - name: Copy Terraform Registry Manifest
        run: cp terraform-registry-manifest.json ${{ github.event.repository.name }}_${GITHUB_REF/refs\/tags\/v/}_manifest.json
      - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
```

Technically this introduces a dirty VCS state unless it is also ignored, e.g. via `.gitignore`, which is additional complexity for project maintainers who may not be familiar with this ecosystem.

**Additional context**

Thank you very much for this excellent project! Please let me know if you are interested in the feature and I would be happy to contribute the changes.
