### ISSUE TITLE
Brainstorming: Running reproducible-build checks just before publishing

### ISSUE THREAD

**Issue by Dentrax** [goreleaser/goreleaser#2666]
**Is your feature request related to a problem? Please describe.**
Several days ago, @naveensrinivasan created something noticeable https://github.com/sigstore/cosign/issues/1019 issue to [cosign](https://github.com/sigstore/cosign). This project has been using [goreleaser](https://github.com/sigstore/cosign/blob/main/.goreleaser.yml). So, we (@developer-guy @erkanzileli) decided to move the discussion here for further details and make some brainstorming: "What kind of automated action would have we take in the GoReleaser to avoid this inconsistency?"

Let's have in mind that GoReleaser already have a support for deterministic / reproducible builds if IIUC: https://github.com/goreleaser/goreleaser/commit/0d4f605388b535063099e22f1b2eafc58a7bf0bc [^1] The motivation behind is this issue is extending the power of this deterministic builds:

**Describe the solution you'd like**

I think we should run this **tests** just BEFORE [publishing pipeline](https://goreleaser.com/customization/release/). That said, we better NOT to publish (sending the release) across distribution platforms in case any tests fails. So, here is a small user story that defines what **tests** mean actually and referencing to:

**As a** builder _(i.e., user, developer, maintainer, etc.)_,
**I want** to build the entire project using a build system that provided by project _(i.e., makefile, justfile, custom shell script automation, etc.)_,
**So that** I can compare the checksum of the output binary against the binary that I downloaded from releases page

Between the `Signing` and `Publish` stages, we can consider bring brand-new friend to platter of the pipelines; something like: `check`, `sanity`, etc.  _(This one might be not necessary since we can run this tests end of the `Build` stage)_ to add `Reproducible test` pipe. Here are my two cents:

**High-level Overview**

![demo](https://user-images.githubusercontent.com/16493751/141537441-d5c1d367-1317-4f2c-832c-ff85f7befd20.png)

```yaml
sanity:
  reproducible_build:
    # notice this! i am calling build script here
    # i.e. build.sh, just build, etc.
    cmd: make build
    envs:
      - CGO_ENABLED: 0
    # how many times should we run this?
    runs: 5
    checks:
     - goos: linux
       goarch: arm64
       goarm: 7
       # assert the checksum against the output
       # that we defined in "binary" field in the each "builds" stages
       # notice that we did not assert "amd64" here!
       # we should append all the ARCH combinations here that we want to release
       # see the trade-off warning below!
       expect_build: myproject-linux-arm64-v7

- id: linux-arm64-v7
  binary: myproject-linux-{{ .Arch }}
  main: ./cmd/main
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  goarm:
    - 7
```

^ Et voilà!

**Trade-off warning:** We probably build the projects twice as much. One by from GoReleaser and one by from _custom build system_; and each combination of:
* GOOS
* GOARCH
* LDFLAGS
* CGO_ENABLED
* ... you name it!

**PROS:**
* easy to write custom checks

**CONS:**
* aforementioned trade-off concern
* hard to maintain all build matrix (combinations)

**Describe alternatives you've considered**
Since GoReleaser already have a support for deterministic builds, are we still willing to add post-checks? Would it bring unnecessary complex? Overengineering?

If we already use custom build system or scripts in the repository, would not it is that easy to entry point of build system to `builds` stage like the following spec:

```yaml
- id: linux-arm64-v7
  binary: myproject-linux-{{ .Arch }}
  # notice the brand new "cmd" field
  cmd: make build
  # some envs to pass into Makefile
  envs:
   - CGO_ENABLED: 0
   - GOOS: linux
   - GOARCH: arm64
   - GOARM: 7
```

**PROS:**
* no two times duplicate building
* no need to write additional post-check steps
* consistent build system for both developer and GoReleaser (guaranteeing same checksum?)

**CONS:**
* unnecessary complexity for such a building "simple" Go app?

**Additional context**
> [Reproducible Builds project](https://reproducible-builds.org/) generally desirable that building the same source code with the same set of tools is reproducible, i.e. the output is always exactly the same. This makes it possible to verify that the build infrastructure for a binary distribution or embedded system has not been subverted. This can also make it easier to verify that a source or tool change does not make any difference to the resulting binaries. [^2]

Any feedback would be greatly appreciated!

cc: @cpanato @shibumi @dekkagaijin

[^1]: https://github.com/goreleaser/goreleaser/blob/master/www/docs/customization/build.md#reproducible-builds
[^2]: https://www.kernel.org/doc/html/latest/kbuild/reproducible-builds.html#reproducible-builds
