### ISSUE TITLE
[Bug]: When skipping the build and extraf iels for checksums is not working

### ISSUE THREAD

**Issue by cpanato** [goreleaser/goreleaser#2691]
### What happened?

when having a config that skip the build but what to generate checksums for extra files the checksum is not being generated

### How can we reproduce this?

simple config file

```
project_name: test
builds:
  - skip: true
checksum:
  name_template: 'checksums.txt'
  extra_files:
  - glob: '.goreleaser.*l'
```

### goreleaser version

```bash
head/latest
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
