### ISSUE TITLE
[Bug]: changelog sort bug

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#2723]
### What happened?

I created a release here - https://github.com/blacktop/ipsw/releases and it's CHANGELOG is missing a commit.

`chore: minor reorg of sym/str in ipsw macho info and dyld macho cmds`

commits can be seen in the Summary here - https://github.com/blacktop/ipsw/compare/v3.1.21...v3.1.22

### How can we reproduce this?

```yaml 
changelog:
  sort: asc
  use: github
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
```      

### goreleaser version

```bash
goreleaser version 1.1.0
commit: af4a8642bddb171914ee932bfb5768f102c3516f
built by: homebrew

https://goreleaser.com
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_
