### ISSUE TITLE
[Bug]: incorrect casing in JSON schema

### ISSUE THREAD

**Issue by catthehacker** [goreleaser/goreleaser#2727]
### What happened?

![image](https://user-images.githubusercontent.com/31106839/144706840-7cb1e372-fb17-4a10-8aa7-08e52058682b.png)

### How can we reproduce this?

config:
```
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - '386'
      - arm64
      - arm
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: windows
        goarm: 6
```

### goreleaser version

```bash
goreleaser version dev
module version: v1.1.0, checksum: h1:YySqqYTX9kxRU0e/fGQrhivXk8/zD4iUOlL7h0I2gBk=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
