### ISSUE TITLE
[Bug]: goreleaser tries to publish a pem file of the checksum file

### ISSUE THREAD

**Issue by shibumi** [goreleaser/goreleaser#2751]
### What happened?

I am running the following `signs` configuration with cosign for keyless signatures:
```yaml
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args: ["sign-blob", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-signature=${signature}", "--output-certificate=${certificate}", "${artifact}"]
    artifacts: all
```

This leads to a fail of goreleaser, because it tried to publish the `checksum.pem` file:
See logs:

```
   ⨯ release failed after 334.74s error=scm releases: failed to publish artifacts: failed to upload kubectl-htpasswd_0.1.2_checksums.txt.pem after 10 tries: POST https://uploads.github.com/repos/shibumi/kubectl-htpasswd/releases/54922653/assets?name=kubectl-htpasswd_0.1.2_checksums.txt.pem: 400 Bad Content-Length:  []
```

### How can we reproduce this?

I use the following goreleaser config:

```yaml
project_name: kubectl-htpasswd
builds:
  - ldflags:
      - "-s -w"
      - "-extldflags=-zrelro"
      - "-extldflags=-znow"
      - "-X github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.tag={{.Version}}"
      - "-X github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.commit={{.FullCommit}}"
      - "-X github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.date={{.CommitDate}}"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/kubectl-htpasswd
source:
  enabled: true
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args: ["sign-blob", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-signature=${signature}", "--output-certificate=${certificate}", "${artifact}"]
    artifacts: all
```

The release github actions workflow looks like this:

```yaml
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.0'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v1.1.0'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
```

### goreleaser version

```bash
v1.1.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
