### ISSUE TITLE
[Feature]: Support multiple ids within same universal binary

### ISSUE THREAD

**Issue by troian** [goreleaser/goreleaser#2759]
Following this [conversation](https://gophers.slack.com/archives/C3T1JU24B/p1639154901035400)

**Describe the solution you'd like**

For now `universal_binaries` assumes all binaries for different arch created within the same build id
```yaml
  - id: app
    binary: akash
    main: ./cmd/app
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
universal_binaries:
  - id: app
    name_template: '{{ .ProjectName }}'
    replace: true
```

unfortunately, cross-compile cases put a limit in form of specific C/C++ compiler to be set for the particular arch
```yaml
  - id: app-darwin-amd64
    binary: akash
    main: ./cmd/app
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath
      - -mod=readonly
      - "{{ .Env.BUILD_FLAGS }}"
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -linkmode=external
  - id: app-darwin-arm64
    binary: app
    main: ./cmd/app
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath
      - -mod=readonly
      - "{{ .Env.BUILD_FLAGS }}"
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -linkmode=external
```

such a case could be resolved with following extension
```yaml
universal_binaries:
  - ids:
    - app-darwin-amd64
    - app-darwin-arm64
    name_template: '{{ .ProjectName }}'
    replace: true
```
