### ISSUE TITLE
[Feature]: configure brews.commit_author.name (and/or email)  from template/pipeline 

### ISSUE THREAD

**Issue by tredfield** [goreleaser/goreleaser#2761]
**Is your feature request related to a problem? Please describe.**
I would like to configure `brews.commit_author.name (and/or email) using pipeline. For example

```yaml
brews:
  - tap:
      owner: tredfield
      name: homebrew-tap
    description: A cli for calling
    commit_author:
      name: {{.Env.COMMIT_AUTHOR}}
      email: {{.Env.COMMIT_AUTHOR}}
```

running `goreleaser check` this produces

```bash
❯ goreleaser check
   • loading config file       file=.goreleaser.yml
   ⨯ command failed            error=yaml: unmarshal errors:
  line 44: cannot unmarshal !!map into string
  line 45: cannot unmarshal !!map into string
```

**Describe the solution you'd like**
Setting commit_author name and email from pipeline works like other fields

**Describe alternatives you've considered**
NA

**Additional context**
NA
