### ISSUE TITLE
[Bug]: After Hooks Env (Pro) does not work as advertised

### ISSUE THREAD

**Issue by aeneasr** [goreleaser/goreleaser#2762]
### What happened?

Following https://goreleaser.com/customization/hooks/ I wrote a hook like this:

```

after:
  hooks:
  - cmd: "bash <(curl -s https://raw.githubusercontent.com/ory/xgoreleaser/master/docs.sh)"
    env:
      TAG_VERSION: "{{ .Tag }}"
      DOCS_VERSION: "{{ .Major }}.{{ .Minor }}"
```

Running `goreleaser check` though results in:

```
% goreleaser check    
   • running goreleaser v1.1.0-pro
   • loading config file       file=.goreleaser.yml
   ⨯ command failed            error=failed to load config: yaml: unmarshal errors:
  line 21: cannot unmarshal !!map into []string
```

### How can we reproduce this?

See above

### goreleaser version

```bash
1.1.0-pro
```

### GoReleaser Check

- [ ] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
oh, bad documentation, `env` should be an array:

```yaml

after:
  hooks:
  - cmd: "bash <(curl -s https://raw.githubusercontent.com/ory/xgoreleaser/master/docs.sh)"
    env:
      - TAG_VERSION: "{{ .Tag }}"
      - DOCS_VERSION: "{{ .Major }}.{{ .Minor }}"
```

this should work :)
