### ISSUE TITLE
`dockers.#.dockerfile` does not support env var substitution in Pro

### ISSUE THREAD

**Issue by aeneasr** [goreleaser/goreleaser#2763]
### What happened?

I am trying to use var substitution in Goreleaser Pro because I need to customize the Dockerfile source:

```
dockers:
  - image_templates:
      - "oryd/{{ .ProjectName }}:v{{ .Version }}-amd64"
    use: buildx
    dockerfile: "{{ .dockerfile }}"
    goarch: amd64
    ids:
      - alpine-cgo-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
```

However, the template is used as a literal, so it's trying to find `./{{ .dockerfile }}` on the file path.

### How can we reproduce this?

See above

### goreleaser version

```bash
1.1.0-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
