### ISSUE TITLE
Add Git Owner and Repository names in templates

### ISSUE THREAD

**Issue by ccremer** [goreleaser/goreleaser#2805]
### Is your feature request related to a problem? Please describe.

When configuring docker images and manifests, it's a quite a pain to maintain the image names and tags, especially if also including prereleases.
See the following example:

```yaml
dockers:
- goarch: amd64
  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"
  image_templates:
  - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}-amd64"

- goarch: arm64
  use: buildx
  build_flag_templates:
    - "--platform=linux/arm64/v8"
  image_templates:
  - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}-arm64"

docker_manifests:
  ## ghcr.io
  - name_template: "{{ if not .Prerelease }}ghcr.io/vshn/go-bootstrap:latest{{ end }}"
    image_templates:
      - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}-amd64"
      - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}-arm64"

  - name_template: "ghcr.io/vshn/go-bootstrap:v{{ .Version }}"
    image_templates:
      - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}-amd64"
      - "ghcr.io/vshn/go-bootstrap:v{{ .Version }}-arm64"
```
The string `vshn/go-bootstrap` is repeated over and over.

### Describe the solution you'd like

Add a `{{ .Owner }}` and `{{ .RepositoryName }}` to the list of available templates in https://goreleaser.com/customization/templates. These values are parsed from the configured Git URL. (Alternative name: `{{ RepositoryOwner }}`)

```yaml
dockers:
- goarch: amd64
  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"
  image_templates:
  - "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}-amd64"

- goarch: arm64
  use: buildx
  build_flag_templates:
    - "--platform=linux/arm64/v8"
  image_templates:
  - "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}-arm64"

docker_manifests:
  ## ghcr.io
  - name_template: "{{ if not .Prerelease }}ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:latest{{ end }}"
    image_templates:
      - "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}-amd64"
      - "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}-arm64"

  - name_template: "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}-amd64"
      - "ghcr.io/{{ .Owner }}/{{ .RepositoryName }}:v{{ .Version }}-arm64"
```

### Describe alternatives you've considered

I guess the same could be achieved by extracting the owner and repository from the GitURL, e.g. `{{ trimPrefix (trimSuffix .GitURL "/") "ssh://git@github.com:<owner>/" }}` (didn't test it, but you get the gist). But seeing this all over the place just makes it more ugly and hard to understand.

Note: `{{ .ProjectName }}` is insufficient, because AFAIK, if this isn't defined in the file, then it takes the directory name, which may not be stable across all environments. Also this variable doesn't contain the owner name.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
