### ISSUE TITLE
Name Templates should support LICENSE

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#2857]
### Is your feature request related to a problem? Please describe.

Currently, we dont have in the Name Templates a license field

### Describe the solution you'd like

If there is a License File in the Source Code root folder, GoReleaser should pick this up and add the SPDX intendifer (https://spdx.org/licenses/) as a variable to use via the Name Templates

### Describe alternatives you've considered

-

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I'm not sure...  what should happen...

- if the repo has multiple license files?
- or a license file with multiple licenses in it?
- or some files with different license headers? 

imho, it'll be hard to get it right, and it seems easy enough to do something like:

```yaml
env:
  - LICENSE=MIT

something:
  license: '{{ .Env.LICENSE }}'
```

or, with goreleaser pro:

```yaml
variables:
  license: MIT

something:
  license: '{{ .Var.license }}'
```
