### ISSUE TITLE
build args for docker are not being passed during container image builds 

### ISSUE THREAD

**Issue by prabhatsharma** [goreleaser/goreleaser#2863]
### What happened?

build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT_HASH={{.FullCommit}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--platform=linux/arm64/v8"

platform arg is being passed to Docker build process but not the build-arg

### How can we reproduce this?

https://github.com/prabhatsharma/tf-goreleaser-ecr

contains the .goreleaser and Dockerfile

that can be used for reproducing the issue.

Logs for the build are at : https://raw.githubusercontent.com/prabhatsharma/tf-goreleaser-ecr/main/build-log.txt

### goreleaser version

```bash
Being pulled every time as part of build process in AWS code build using the below command.

> curl -sL https://git.io/goreleaser | bash
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I trying passing the args manually on my laptop directly to docker and it works well.

I used the below command 

> docker buildx build --platform=linux/arm64 --build-arg=VERSION=0.0.7 --build-arg=COMMIT_HASH=7270590e33e8dbce5b7f707009e5bb1a241fa108 . -t tfge:0.0.7

**Comment by caarlos0** [comment]
your dockerfile is building the binary again, which is not the way to use docker with goreleaser, the binary was already built, you only need to copy it and the envs you're passing as ldflags are also available in the build section,

that said, all args are being passed, goreleaser does not filter anything out. 

I created a test project here and it works just fine:

```sh
mkdir foo
cd foo
git init
go mod init foo
git remote add origin git@github.com:fake/foo.git
```

```dockerfile
# Dockerfile
FROM alpine
ARG VERSION
ARG COMMIT_HASH
ARG BUILD_DATE

RUN echo "$VERSION" >> /buildargs
RUN echo "$COMMIT_HASH" >> /buildargs
RUN echo "$BUILD_DATE" >> /buildargs

ENTRYPOINT ["cat", "/buildargs"]
```

```yaml
# .goreleaser.yaml
project_name: foobar
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
dockers:
  - image_templates:
    - foobar:{{.Version}}-arm64
    use: buildx
    build_flag_templates:
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=COMMIT_HASH={{.FullCommit}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--platform=linux/arm64"
```

```go
# main.go 
package main

func main() {
        print(1)
}
```

```console
$ goreleaser release --rm-dist --skip-validate --skip-sign --skip-sbom --skip-publish --snapshot
# ...

$ docker run foobar:0.0.0-SNAPSHOT-fb2f647-arm64
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
0.0.0-SNAPSHOT-fb2f647
fb2f647f1c3db35b03bcb076e1efb6c14f8d71b9
2022-01-31T18:52:54Z
```

so, this definitely works.
