### ISSUE TITLE
Single artifact variables are not exposed to the blobs release phase

### ISSUE THREAD

**Issue by attachmentgenie** [goreleaser/goreleaser#2868]
### What happened?

I am trying to release a program as a homebrew package, with the $package.rb artifact going into a git repo and the $package.tar.gz artifact being stored in s3.

When running `goreleaser release ` with a `.goreleaser.yml ` excerpt as provided below, the process terminates with the following error

`release failed after 290.99s error=blobs: failed to publish artifacts: template: tmpl:1:19: executing "tmpl" at <.Os>: map has no entry for key "Os" `

which according to [1] is exposed for single artifacts. So perhaps i am out of luck as to what i am trying to do,  however the $package.rb brewfile is being created which in my(limited) understanding is also a publish step but that file is rendered correctly.

[1] https://goreleaser.com/customization/templates/

### How can we reproduce this?

```
archives:
  - id: darwin
    builds:
      - darwin
blobs:
  - provider: s3
    bucket: myprivatebucket
    ids:
      - darwin
    folder: "{{.ProjectName}}/{{.Os}}/{{.Arch}}"
brews:
  - ids:
      - darwin
    url_template: "https://myprivatebucket.s3.amazonaws.com/{{.ProjectName}}/{{.Os}}/{{.Arch}}/{{.ArtifactName}}"
builds:
  - id: darwin
```

### goreleaser version

```bash
1.4.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Not sure this is a bug or a feature request, so please be kind/relabel if yes.
