### ISSUE TITLE
Universal Binary hooks missing build options

### ISSUE THREAD

**Issue by szechyjs** [goreleaser/goreleaser#2890]
### What happened?

When using any of the build options as template variables in an `universal_binaries`  post command it results in a error.

` ``
⨯ release failed after 14.88s error=post hook failed: template: tmpl:1:19: executing "tmpl" at <.Path>: map has no entry for key "Path"
```

### How can we reproduce this?

```yml
universal_binaries:
  - replace: true
    hooks:
      post: ./post.sh {{ .Path }} {{ .Target }} {{ .Version }}
```

### goreleaser version

```bash
goreleaser version 1.4.1
commit: a1447a363579365f489458ad7636fd088a5b66ab
built by: homebrew
goos: darwin
goarch: amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Looking at the code `WithBuildOptions` is never called on the template like it is on a regular build.

https://github.com/goreleaser/goreleaser/blob/f585f3be698ae1d3b86895a6f082518483283d94/internal/pipe/build/build.go#L125

https://github.com/goreleaser/goreleaser/blob/f585f3be698ae1d3b86895a6f082518483283d94/internal/pipe/universalbinary/universalbinary.go#L82
