### ISSUE TITLE
Ignore suggestion

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#293]
So I expected this to work:

```yaml
  ignore:
    - goos: openbsd
      goarch: arm
```

But I had to do:

```yaml
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
```

Which in my head is a little bit surprising. It should at least be documented somehow.
