### ISSUE TITLE
Docker manifests failing 

### ISSUE THREAD

**Issue by haad** [goreleaser/goreleaser#2934]
### What happened?

During build of my application docker_manifest stage is failing.

https://github.com/haad/confd/runs/5310917070?check_suite_focus=true

```
       •  ---> 9e46212b6db2        cmd=[docker build] cwd=dist/goreleaserdocker1235120552
         • Removing intermediate container c0f078fe2a12 cmd=[docker build] cwd=dist/goreleaserdocker200553135
         •  ---> 7aab80743dff        cmd=[docker build] cwd=dist/goreleaserdocker200553135
         • Successfully built 9e46212b6db2 cmd=[docker build] cwd=dist/goreleaserdocker1235120552
         • Successfully built 7aab80743dff cmd=[docker build] cwd=dist/goreleaserdocker200553135
         • Successfully tagged ghcr.io/haad/confd:v0.18.5-amd64 cmd=[docker build] cwd=dist/goreleaserdocker1235120552
      • added new artifact        name=ghcr.io/haad/confd:v0.18.5-amd64 path=ghcr.io/haad/confd:v0.18.5-amd64 type=Docker Image
         • Successfully tagged ghcr.io/haad/confd:v0.18.5-arm64v8 cmd=[docker build] cwd=dist/goreleaserdocker200553135
      • added new artifact        name=ghcr.io/haad/confd:v0.18.5-arm64v8 path=ghcr.io/haad/confd:v0.18.5-arm64v8 type=Docker Image
   • storing release metadata
      • writing                   file=dist/artifacts.json
      • writing                   file=dist/metadata.json
   • publishing       
      • skipped blobs            
      • skipped http upload      
      • skipped custom publisher 
      • skipped artifactory      
      • docker images    
         • pushing                   image=ghcr.io/haad/confd:v0.18.5-amd64
         • running                   args=[ghcr.io/haad/confd:v0.18.5-amd64] cmd=[docker push] cwd=.
            • The push refers to repository [ghcr.io/haad/confd] cmd=[docker push] cwd=.
            • ab01e0c03e13: Preparing   cmd=[docker push] cwd=.
            • ab01e0c03e13: Pushed      cmd=[docker push] cwd=.
            • v0.18.5-amd64: digest: sha256:ea6feabcb1daac15a705f65a2065b0f125abc2648860d966f599599061d2b7c2 size: 528 cmd=[docker push] cwd=.
         • added new artifact        name=ghcr.io/haad/confd:v0.18.5-amd64 path=ghcr.io/haad/confd:v0.18.5-amd64 type=Docker Image
         • pushing                   image=ghcr.io/haad/confd:v0.18.5-arm64v8
         • running                   args=[ghcr.io/haad/confd:v0.18.5-arm64v8] cmd=[docker push] cwd=.
            • The push refers to repository [ghcr.io/haad/confd] cmd=[docker push] cwd=.
            • b31ee24819c3: Preparing   cmd=[docker push] cwd=.
            • b31ee24819c3:             cmd=[docker push] cwd=.
            • Pushed                    cmd=[docker push] cwd=.
            • v0.18.5-arm64v8: digest: sha256:23839dd616585cd9e4c0e2bf6f2b7c05ce92f29efec368af46cfdcb043576b6e size: 528 cmd=[docker push] cwd=.
         • added new artifact        name=ghcr.io/haad/confd:v0.18.5-arm64v8 path=ghcr.io/haad/confd:v0.18.5-arm64v8 type=Docker Image
      • docker manifests 
         • creating                  images=[ghcr.io/haad/confd:0.18.5-amd64 ghcr.io/haad/confd:0.18.5-arm64v8] manifest=ghcr.io/haad/confd:0.18.5
         • running                   args=[rm ghcr.io/haad/confd:0.18.5] cmd=[docker manifest] cwd=.
            • No such manifest: ghcr.io/haad/confd:0.18.5 cmd=[docker manifest] cwd=.
         • running                   args=[create ghcr.io/haad/confd:0.18.5 ghcr.io/haad/confd:0.18.5-amd64 ghcr.io/haad/confd:0.18.5-arm64v8] cmd=[docker manifest] cwd=.
            • manifest unknown          cmd=[docker manifest] cwd=.
   ⨯ release failed after 217.11s error=docker manifests: failed to publish artifacts: failed to create ghcr.io/haad/confd:0.18.5: exit status 1: manifest unknown

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.5.0/x64/goreleaser' failed with exit code 1
```
Configuration file

```
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - dockerfile: Dockerfile
#    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/haad/{{ .ProjectName }}:{{ .Tag }}-amd64
    build_flag_templates:
      - --platform=linux/amd64
  - dockerfile: Dockerfile
#    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/haad/{{ .ProjectName }}:{{ .Tag }}-arm64v8
    build_flag_templates:
      - --platform=linux/arm64/v8

docker_manifests:
  - name_template: ghcr.io/haad/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/haad/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/haad/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/haad/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/haad/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/haad/{{ .ProjectName }}:{{ .Version }}-arm64v8

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

To me it looks like a race condition where original docker images ghcr.io/haad/confd:{{.Version}}-amd64/arm64v8 were pushed to repository but are not yet visible. I have seen this same code finish successfully before on a same repository.

https://github.com/haad/confd/runs/5253006730?check_suite_focus=true

### How can we reproduce this?

Just run a docker iamge build + manifest build. On my repository I can reproduce it regularly.

### goreleaser version

```bash
goreleaser/goreleaser-action@v2
  with:
    version: latest
    args: release --rm-dist --debug
    distribution: goreleaser
    workdir: .
    install-only: false
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    GOROOT: /opt/hostedtoolcache/go/1.17.7/x64
    GITHUB_TOKEN: ***
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.5.0/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/420b22b3-ec0f-4e40-bba2-aa36787890ab -f /home/runner/work/_temp/cbe53fda-d7c8-4728-9de9-0c69564befb2
GoReleaser latest installed successfully
0.18.3 tag found for commit '8756f8d'
/opt/hostedtoolcache/goreleaser-action/1.5.0/x64/goreleaser release --rm-dist --debug
   • debug logs enabled       
   • releasing...
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
