### ISSUE TITLE
GitLab Brew Tap Problem

### ISSUE THREAD

**Issue by anilmisirlioglu** [goreleaser/goreleaser#2954]
### What happened?

Hi, I'm trying to create a new brew tab on GitLab and getting some errors. 

When I looked into the problem, I noticed that; 

normally pattern should be like this: `/api/v4/projects/:projectId/repository/files/:file_path?ref=branch` ([GitLab API Docs of the related endpoint](https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository))
but goreleaser is sending in this pattern: `/api/v4/projects/:owner/:name/repository/files/:file_path?ref=branch`

and this reason, GitLab API returns the '404 Project Not Found' error.

---

Error in GitLab CI: 

![unknown-1](https://user-images.githubusercontent.com/20264712/156737246-c6868787-6f8f-4f07-961c-b4a890bcf4c9.png)

---

Here is my configuration:

(I tried to set owner empty to bypass this problem, but it's not work for create file section)

```
brews:
  - tap:
      owner: ""
      name: "11787"
      branch: master
      token: "{{ .Env.GITLAB_TOKEN }}"
```
---

Problem-related links:
https://github.com/goreleaser/goreleaser/blob/main/internal/client/gitlab.go#L133
https://github.com/goreleaser/goreleaser/blob/main/internal/client/client.go#L38-L43

### How can we reproduce this?

```
gitlab_urls:
  api: https://gitlab.company.com/api/v4/
  download: https://gitlab.company.com
  skip_tls_verify: false
  use_package_registry: true

brews:
  - tap:
      owner: ""
      name: "projectID"
      branch: master
      token: "{{ .Env.GITLAB_TOKEN }}"
    name: project-name
```

### goreleaser version

```bash
goreleaser version 1.5.0
commit: 55d7eabc79d41e073cc4592c350c1f4c7f527eb3
built at: 2022-02-12T17:22:26Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.5.0, checksum: h1:l4BxBt2Rrk5Tngmzyrcp7H/CszXSA0guzL4mPo4peAU=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Akaame** [comment]
An `owner/name` pair does not identify a GitLab repository. Old versions of goreleaser had `brew.github` yaml path to identify a GitHub repo to create formulae files on. Now, `brews.[:id].tap` is a `RepoRef` that is a collection of `owner/name/branch` which does not make sense for GitLab impl.

The following query returns a 404:

`https://gitlab.com/api/v4/projects/gitlab-org/gitlab-foss/repository/files/.dockerignore?ref=master`

whereas this succeeds (expectedly)

`https://gitlab.com/api/v4/projects/13083/repository/files/.dockerignore?ref=master`

Going from `owner/name` to `projectID` is not simple as far as I can see, as GitLab categorizes project ownership under either a single user or a group, so `api/v4/users/<owner-name>/projects` or `api/v4/groups/<name>/projects` are needed to be checked to fetch the `projectID`. 

Using only the `name` field as a workaround so that GitLab `projectID` can be correctly plugged into the URL, is one easy way out of this, but it is not explicit and will be a "bazinga" moment for all GitLab users.

**Comment by caarlos0** [comment]
cc/ @mavogel 

if anyone wants to work on a pr, happy to review/assist

**Comment by developer-guy** [comment]
@caarlos0 you can assign it to me, I can take care of that one.

**Comment by caarlos0** [comment]
> @caarlos0 you can assign it to me, I can take care of that one.

Done, thanks 🙏

**Comment by mnkg561** [comment]
@caarlos0 I'm getting same 404 for releases API in GitLab. I want to double check as whether this is related to GitLab or goreleaser? We are using GitLab 11.4 version at my company and see GitLab doesn't have releases feature until recent versions. 

```
$ goreleaser release --rm-dist
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=a1d1ce33c1f66aee4ea572e665373ad4e7990921 latest tag=v0.0.8
   • parsing tag      
   • running before hooks
      • running                   hook=go mod download
   • setting defaults 
   • checking distribution directory
   • loading go mod information
   • build prerequisites
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • building                  binary=dist/homebrew-go-example_linux_amd64_v1/homebrew-go-example
      • building                  binary=dist/homebrew-go-example_darwin_amd64_v1/homebrew-go-example
   • archives         
      • creating                  archive=dist/homebrew-go-example_0.0.8_linux_x86_64.tar.gz
      • creating                  archive=dist/homebrew-go-example_0.0.8_darwin_x86_64.tar.gz
   • calculating checksums
   • homebrew tap formula
      • guessing install to be "bin.install \"homebrew-go-example\""
      • guessing install to be "bin.install \"homebrew-go-example\""
      • writing                   formula=dist/homebrew-go-example.rb
   • storing release metadata
      • writing                   file=dist/artifacts.json
      • writing                   file=dist/metadata.json
   • publishing       
      • scm releases     
         • creating or updating release repo= tag=v0.0.8
   ⨯ release failed after 8.50s error=scm releases: failed to publish artifacts: POST https://code.privaterepo.org/api/v4/projects/3456/releases: 404 {error: 404 Not Found}
```

**Comment by caarlos0** [comment]
@mnkg561   there's a note on docs saying it needs gitlab 12.9+: https://goreleaser.com/scm/gitlab/

**Comment by caarlos0** [comment]
FWIW, I think @developer-guy is away for a while, so if anyone else wants to work on this, feel free to grab it

**Comment by metalmolly** [comment]
Facing the same problem. But after reading the GitLab API documentation I found that the namespace needs to be URL encoded. See https://docs.gitlab.com/ee/api/index.html#namespaced-path-encoding.

@Akaame mentioned 

> The following query returns a 404:
> https://gitlab.com/api/v4/projects/gitlab-org/gitlab-foss/repository/files/.dockerignore?ref=master

The correct url should be
https://gitlab.com/api/v4/projects/gitlab-org%2fgitlab-foss/repository/files/.dockerignore?ref=master

**Comment by caarlos0** [comment]
good find @metalmolly , wanna try and PR that?

**Comment by TanZng** [comment]
Any news about out these? Can I be assign? I can work on this :D

**Comment by caarlos0** [comment]
hey @TanZng, feel free to give this a shot!

**Comment by TanZng** [comment]
I was checking and the

**Comment by TanZng** [comment]
The `CreateFile` function in goreleaser uses the `go-gitlab` package to handle the file creation:
https://github.com/goreleaser/goreleaser/blob/5cfc78d92c49aad5624d0ea5f869481bd91d59ad/internal/client/gitlab.go#L206

The `go-gitlab` package already handles the url encoding

https://github.com/xanzy/go-gitlab/blob/f4f54fa4a42d2004e5b269921578bfe529ab19a0/repository_files.go#L283-L287

https://github.com/xanzy/go-gitlab/blob/f4f54fa4a42d2004e5b269921578bfe529ab19a0/gitlab.go#L853-L856

After a lot of test, using the goreleaser 1.10.3 and gitlab 12.9+ with these config in the `.goreleaser.yaml` everything worked:

```yaml
gitlab_urls:
  # CI_API_V4_URL is provided in by the GitLab CI/CD eg. https://gitlab.company.com/api/v4/
  api: "{{ .Env.CI_API_V4_URL }}"
  download: https://gitlab.company.com
  skip_tls_verify: true
  use_package_registry: true

brews:
  - tap:
      owner: group/subgroup
      name: homebrew-tap
      branch: main
      # TOKEN_BREW_REPO is an Access Token issued in the Brew Repo (https://gitlab.company.com/group/subgroup/homebrew-tap/-/settings/access_tokens)
      token: "{{ .Env.TOKEN_BREW_REPO }}"
    folder: Formula
    commit_author:
      name: bot
      email: bot@company.com
    goarm: "7"
    homepage:  docs.company.com
    url_template: "https://repo.company.com/repository/some-name/{{ .Version }}/{{ .ArtifactName }}"
    description: Bla bla bla bla.
    test: |
      system "#{bin}/command -v"
    # The project name and current git tag are used in the format string.
    download_strategy: CurlDownloadStrategy
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    dependencies:
    - name: git
    - name: wget
    - name: curl
    install: |-
      bin.install "{{.ProjectName}}"
```
