### ISSUE TITLE
goreleaser fails for android_386

### ISSUE THREAD

**Issue by gennaro-tedesco** [goreleaser/goreleaser#2959]
### What happened?

I am using `goreleaser` via GitHub actions to build go executables for different architectures. The build fails with
```
error=failed to build for android_386: exit status 2: # github.com/gennaro-tedesco/gh-s
loadinternal: cannot find runtime/cgo
/opt/hostedtoolcache/go/1.17.7/x64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
```
whereas it works for all other systems except android.

### How can we reproduce this?

- [GitHub actions release yml](https://github.com/gennaro-tedesco/gh-s/blob/master/.github/workflows/release.yml)

`.goreleaser.yml` of the form
```
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - android
      - darwin
      - linux
      - windows
      - netbsd
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
```
Run failure can be found [here](https://github.com/gennaro-tedesco/gh-s/runs/5435139752?check_suite_focus=true)

### goreleaser version

```bash
Irrelevant as running from CI/CD
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Since the error I see is in correspondence of `android_386` I tried to explicitly ignore it by only configuring the remaining android architectures (that do not fail): it is however extremely hard to understand what the right grammar is, from the docs. [Here](https://goreleaser.com/customization/build/) we can see that 

>>>Format is `{goos}_{goarch}`

in correspondence of `targets`, but nothing is said on whether such grammar also works to whitelist `goos` builds, and apparently it does not (or at least it does not for android).

- is it possible to explicitly specify `android_{goarch}`? If so, what is the correct grammar?

Do the docs contain examples of non-trivial architectures (namely examples that do not only show linux + darwin, for which `goreleaser` per sé would not be even needed)?
