### ISSUE TITLE
Publish goreleaser images with Go 1.18 support

### ISSUE THREAD

**Issue by omrishtam** [goreleaser/goreleaser#2994]
### Is your feature request related to a problem? Please describe.

I tried to upgrade my repository to use go 1.18 but my release stage fails when building using goreleaser v1.6.3

This is my release stage configuration in `.gitlab.yml`:
```
release:
  stage: release
  only:
    refs:
      - tags
  needs:
    - lint
  image:
    name: goreleaser/goreleaser:v1.6.3
    entrypoint: ['']
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  before_script:
    - *gitlab_access
  script:
    - goreleaser release --rm-dist
```
The output (and the error) is:
```
$ goreleaser release --rm-dist
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=**** latest tag=v*.*.*
   • parsing tag      
   • running before hooks
      • running                   hook=go mod tidy
   ⨯ release failed after 0.05s error=hook failed: go mod tidy: exit status 1; output: go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1
```

### Describe the solution you'd like

I'd like to know if you could create a new tag, build and publish new docker images with go1.18 installed.
It seems that you've already updated your base image to [go1.18-alpine](https://github.com/goreleaser/goreleaser/commit/3c4e797150ed062625d0672cc78b148ec39aa971), so if that's the case, could you please make a release?

### Describe alternatives you've considered

I've considered trying to build the goreleaser image from `main` and push it to my private image registry but that failed, I guess I'm not supposed to do that.
I also considered the `gobinary` option but that requires a bit too much time and effort than I have available due to the way my CI/CD pipeline is built.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Great project  :smile:
