### ISSUE TITLE
release fails when brew uses universal binaries

### ISSUE THREAD

**Issue by troian** [goreleaser/goreleaser#3027]
### What happened?

Two issues arise when using universal binaries for Darwin

### universal binaries config
```yaml
universal_binaries:
  - id: akash-darwin-universal
    ids:
      - akash-darwin-amd64
      - akash-darwin-arm64
    name_template: '{{ .ProjectName }}'
    replace: true
```

#### config
```yaml
archives:
  - id: akash
    builds:
      - akash-darwin-universal
      - akash-linux-amd64
      - akash-linux-arm64
      - akash-windows-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*
```

#### output
```
   • universal binaries       
      • creating from 2 binaries  binary=dist/akash_darwin_all/akash
   • archives                 
      • creating                  archive=dist/akash_0.15.0-rc16_linux_arm64.zip
      • creating                  archive=dist/akash_0.15.0-rc16_linux_amd64.zip
      • creating                  archive=dist/akash_0.15.0-rc16_windows_amd64.zip
```

#### expected output
```
   • universal binaries       
      • creating from 2 binaries  binary=dist/akash_darwin_all/akash
   • archives                 
      • creating                  archive=dist/akash_0.15.0-rc16_linux_arm64.zip
      • creating                  archive=dist/akash_0.15.0-rc16_linux_amd64.zip
      • creating                  archive=dist/akash_0.15.0-rc16_windows_amd64.zip
      • creating                  archive=dist/akash_0.15.0-rc16_darwin_universal.zip
```

#### config
```yaml
brews:
  - name: "{{ .Env.HOMEBREW_NAME }}"
    tap:
      owner: ovrclk
      name: homebrew-tap
    homepage: "https://akash.network"
    description: "Blockchain-powered decentralized compute platform"
    custom_block: |
      {{ .Env.HOMEBREW_CUSTOM }}
    install: |
      bin.install "akash"
    ids:
      - akash-darwin-universal
```

#### output
```
   • homebrew tap formula     
   ⨯ release failed after 147.34s error=no linux/macos archives found
```

### Full version of the .goreleaser.yml

<details>
<summary>Lost of characters</summary>

```yaml
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
  - id: akash-darwin-amd64
    binary: akash
    main: ./cmd/akash
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
  - id: akash-darwin-arm64
    binary: akash
    main: ./cmd/akash
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
  - id: akash-linux-amd64
    binary: akash
    main: ./cmd/akash
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-lc -lrt -lpthread --static"
  - id: akash-linux-arm64
    binary: akash
    main: ./cmd/akash
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-lc -lrt -lpthread --static"
  - id: akash-windows-amd64
    binary: akash
    main: ./cmd/akash
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
      - -buildmode=exe
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"

universal_binaries:
  - id: akash-darwin-universal
    ids:
      - akash-darwin-amd64
      - akash-darwin-arm64
    name_template: '{{ .ProjectName }}'
    replace: true

archives:
  - id: akash
    builds:
      - akash-darwin-universal
      - akash-linux-amd64
      - akash-linux-arm64
      - akash-windows-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*

dockers:
  - ids:
      - akash-linux-amd64
    dockerfile: _build/Dockerfile.akash
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/ovrclk/akash:{{if eq .Env.MAINNET "true"}}stable{{else}}latest{{end}}'
      - 'ghcr.io/ovrclk/akash:{{ .ShortCommit }}'
      - 'ghcr.io/ovrclk/akash:{{ .Version }}'

brews:
  - name: "{{ .Env.HOMEBREW_NAME }}"
    tap:
      owner: ovrclk
      name: homebrew-tap
    homepage: "https://akash.network"
    description: "Blockchain-powered decentralized compute platform"
    custom_block: |
      {{ .Env.HOMEBREW_CUSTOM }}
    install: |
      bin.install "akash"
    ids:
      - akash-darwin-universal

nfpms:
  - vendor: "Overclock Labs Inc."
    homepage: "http://ovrclk.com"
    maintainer: "Akash Network <hello@akash.network>"
    formats:
      - deb
      - rpm
    license: Apache 2.0

release:
  github:
    owner: ovrclk
    name: akash
  prerelease: auto
  mode: replace
  draft: false
```
</details>

### How can we reproduce this?

apply the following diff to the https://github.com/ovrclk/akash
```diff
diff --git a/.goreleaser.yaml b/.goreleaser.yaml
index 4b75e9f1..7176dcfe 100644
--- a/.goreleaser.yaml
+++ b/.goreleaser.yaml
@@ -95,11 +95,19 @@ builds:
       - "{{ .Env.BUILD_VARS }}"
       - "{{ .Env.STRIP_FLAGS }}"
       - "-linkmode={{ .Env.LINKMODE }}"
+
+universal_binaries:
+  - id: akash-darwin-universal
+    ids:
+      - akash-darwin-amd64
+      - akash-darwin-arm64
+    name_template: '{{ .ProjectName }}'
+    replace: true
+
 archives:
   - id: akash
     builds:
-      - akash-darwin-amd64
-      - akash-darwin-arm64
+      - akash-darwin-universal
       - akash-linux-amd64
       - akash-linux-arm64
       - akash-windows-amd64
@@ -119,6 +127,7 @@ dockers:
       - 'ghcr.io/ovrclk/akash:{{if eq .Env.MAINNET "true"}}stable{{else}}latest{{end}}'
       - 'ghcr.io/ovrclk/akash:{{ .ShortCommit }}'
       - 'ghcr.io/ovrclk/akash:{{ .Version }}'
+
 brews:
   - name: "{{ .Env.HOMEBREW_NAME }}"
     tap:
@@ -130,6 +139,8 @@ brews:
       {{ .Env.HOMEBREW_CUSTOM }}
     install: |
       bin.install "akash"
+    ids:
+      - akash-darwin-universal
 
 nfpms:
   - vendor: "Overclock Labs Inc."
```

**execute**
```shell
GORELEASER_SKIP_VALIDATE=true make release-dry-run
```

### goreleaser version

```bash
goreleaser version 1.5.0
commit: 55d7eabc79d41e073cc4592c350c1f4c7f527eb3
built at: 2022-02-12T17:22:26Z
built by: goreleaser
goos: linux
goarch: arm64
module version: v1.5.0, checksum: h1:l4BxBt2Rrk5Tngmzyrcp7H/CszXSA0guzL4mPo4peAU=

https://goreleaser.com
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_
