### ISSUE TITLE
Universal binaries clash between multiple ids when using the same name_template

### ISSUE THREAD

**Issue by lowdewijk** [goreleaser/goreleaser#3061]
### What happened?

I have a config that specifies two different builds of the same binary (one with full capabilities and one with limited capabiities). When I use `universal_binaries` with two different ids, referencing the two different build ids, but with the same `name_template` the file paths clash. The result is that one binary overwrites the other and that I get two archives with the same build in it (the one that was specified last). 

E.g.:

```
universal_binaries:
-
  id: my-cli-full
  ids:
  - my-cli-full
  name_template: 'cli'
  replace: true
-
  id: my-cli-limited
  ids:
  - my-cli-limited
  name_template: 'cli'
  replace: true
```

Will result in two universal binary artifacts, one named full and one named limited, with both only the limited binary in it. You can see why this is happening in the output of `goreleaser`:

```
   • universal binaries
      • creating from 2 binaries  binary=dist/cli_darwin_all/cli
      • creating from 2 binaries  binary=dist/cli_darwin_all/cli
```

### How can we reproduce this?

Take any two builds and create two respective universal binary ids for them. Then give them the same `name_template`.

### goreleaser version

```bash
1.8.3
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I've narrowed this down to:

https://github.com/goreleaser/goreleaser/blob/02595554de30243792f4ec803338258e23bf5702/internal/pipe/universalbinary/universalbinary.go 

Line 143 says:	`path := filepath.Join(ctx.Config.Dist, name+"_darwin_all", name)`

I believe it should say `path := filepath.Join(ctx.Config.Dist, unibin.Id +"_darwin_all", name)`
