### ISSUE TITLE
Customize Content-Disposition attribute for glob extra files

### ISSUE THREAD

**Issue by mbamber** [goreleaser/goreleaser#3069]
### Is your feature request related to a problem? Please describe.

As part of my release I would like to upload some simple files that should be viewed inline rather than be downloaded by the browser.

### Describe the solution you'd like

I'd like to be able to control if any extra files are for download or for inline-viewing, something like the below as a contrived example:
```yaml
extra_files:
  - glob: myfile.html
    isAttachment: false
```

### Describe alternatives you've considered

The only solution I can see right now is either uploading files and then modifying them after upload as part of a hook, or not upload these files with goreleaser (which seems like a shame)

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Line of interest:
https://github.com/goreleaser/goreleaser/blob/69cf1aa88754454d074626d49969d0751f2afa39/internal/pipe/blob/upload.go#L229

**Comment by caarlos0** [comment]
I would say to allow to set the whole content disposition instead, e.g.

```yaml
extra_files:
  - glob: myfile.html
    content_disposition: attachment
```

is it possible to set the content disposition to something that would allow it to be viewed in the browser or should it be empty instead?

another (similar) idea: set the content disposition only to files generated by goreleaser (archives, packages, etc) and do not set it for other files

**Comment by mbamber** [comment]
Yep that works too!

> is it possible to set the content disposition to something that would allow it to be viewed in the browser or should it be empty instead?

Yes I believe it can be set to `inline`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#as_a_response_header_for_the_main_body

> another (similar) idea: set the content disposition only to files generated by goreleaser (archives, packages, etc) and do not set it for other files

Personally I don't like this idea; it feels more restrictive for no real benefit. In my case, I am actually generating the file to upload as part of a post hook, so I definitely wouldn't want this to be affected.

**Comment by caarlos0** [comment]
this will be a rather big refactory, might get only on 1.10+

**Comment by till** [comment]
Is the idea to support _arbitrary_ writer opts? Or specific features?

**Comment by caarlos0** [comment]
initally, arbitrary content-types.

Do you think it should support arbitrarty opts? If so, can you share your usecase?

**Comment by till** [comment]
> initally, arbitrary content-types.
> 
> 
> 
> Do you think it should support arbitrarty opts? If so, can you share your usecase?

As outlined in the discussion, I need to set a another header (not `content-type`). 😅

**Comment by till** [comment]
Along these lines, maybe a `headers` option with `map[string]string` is best there? Then everyone can set whatever they need.

Whatever the user puts in the config wins over current defaults. No merging, etc..

**Comment by caarlos0** [comment]
> As outlined in the discussion, I need to set a another header (not `content-type`). 😅

ah, yes, for https://github.com/goreleaser/goreleaser/discussions/3129

**Comment by caarlos0** [comment]
was looking into this again today, and I didn't remember why it wasn't so simple, so here you go:

- extrafiles go through `extrafiles.Find`, which returns a `map[string]string`
- both that function and the `ExtraFile` struct is shared in several places

So, would have to probably have to more or less duplicate some code in order to add extra fields. 
Assuming we do that, we need to decide what happens with globs, e.g., if multiple globs match the same file, and they have different content dispositions, which one should prevail? Simpler impl would probably be "the last one found"... 

anyway, just brain dumping for now

**Comment by caarlos0** [comment]
an alternative idea, do something like this:


```yaml
blobs:
extra_files:
- content_disposition: attachment
  files:
  - glob: ./path/to/file.txt
- content_disposition: inline
  files:
  - glob: ./single_file.txt
    name_template: file.txt
```

so, basically, `extra_files` becomes a list of what is the current `extra_files`, plus a `content_disposition` field that is applied to all the actual files...

WDYT?

**Comment by till** [comment]
Maybe... Something like this:

```

blobs:
  - provider: s3
    # etc...
    extra_files:
      - headers:
          content-disposition: attachment
        files:
          - glob: ./path/to/file.txt
```
