### ISSUE TITLE
Gitlab Login on Docker Image

### ISSUE THREAD

**Issue by djarbz** [goreleaser/goreleaser#3078]
### Is your feature request related to a problem? Please describe.

I wish to deploy my image to both the Gitlab Registry for my project as well as the Docker Hub.
Currently, the only way I see this possible, when using the goreleaser docker image, is to run the build twice passing different DOCKER_... env variables.

### Describe the solution you'd like

I would like to be able to pass the following variable directly to the goreleaser docker image so that I can login to both Docker Hub and the Gitlab registry. I do see that an option is already added to the entrypoint script for Github.

```
CI_REGISTRY
CI_REGISTRY_USER
CI_REGISTRY_PASSWORD
```

### Describe alternatives you've considered

I could run the build twice and just pass the variable as the existing docker ones.
```
DOCKER_REGISTRY: "$CI_REGISTRY"
DOCKER_USERNAME: "$CI_REGISTRY_USER"
DOCKER_PASSWORD: "$CI_REGISTRY_PASSWORD"
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by djarbz** [comment]
Another option would be to add logins in the `.goreleaser.yaml` configuration that we can set our own environment variable to.
This would allow us to add an arbitrary amount of registries to login to.

For example:
```
docker_registries:
  - registry: '{ .Env.DOCKER_HUB_REGISTRY }'
    username: '{ .Env.DOCKER_HUB_USERNAME }'
    password: '{ .Env.DOCKER_HUB_PASSWORD }'
  - registry: '{ .Env.CI_REGISTRY }'
    username: '{ .Env.CI_REGISTRY_USER }'
    password: '{ .Env.CI_REGISTRY_PASSWORD }'
  - registry: '{ .Env.GITHUB_REGISTRY }'
    username: '{ .Env.GITHUB_REGISTRY_USER }'
    password: '{ .Env.GITHUB_TOKEN }'
```
