### ISSUE TITLE
Can't push a release with changelog Github Native

### ISSUE THREAD

**Issue by tiero** [goreleaser/goreleaser#3079]
### What happened?

I was using github-native to create changelog, but now can't anymore

https://github.com/tdex-network/tdex-daemon/runs/6256237648?check_suite_focus=true

I get 

```sh
  ⨯ release failed after 0.37s error=POST https://api.github.com/repos/tdex-network/tdex-daemon/releases/generate-notes: 400 Invalid previous_tag parameter []
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.8.3/x64/goreleaser' failed with exit code 1
```

### How can we reproduce this?

```yaml
builds:
  # daemon

  ### Linux
  - id: "tdexd-linux-amd64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X './cmd/tdexd/main.version={{.Version}}' -X './cmd/tdexd/main.commit={{.Commit}}' -X './cmd/tdexd/main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: tdexd-linux-amd64

  - id: "tdexd-linux-arm64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X './cmd/tdexd/main.version={{.Version}}' -X './cmd/tdexd/main.commit={{.Commit}}' -X './cmd/tdexd/main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    binary: tdexd-linux-arm64

  ### Darwin

  - id: "tdexd-darwin-amd64"
    main: ./cmd/tdexd
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    binary: tdexd-darwin-amd64

  - id: "tdexd-darwin-arm64"
    main: ./cmd/tdexd
    ldflags:
      - -s -X './cmd/tdexd/main.version={{.Version}}' -X './cmd/tdexd/main.commit={{.Commit}}' -X './cmd/tdexd/main.date={{.Date}}'
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/oa64-clang
      - CXX=/home/runner/work/osxcross/target/bin/oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    binary: tdexd-darwin-arm64

  # CLI
  - id: "tdex"
    main: ./cmd/tdex
    ldflags:
      - -s -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{.Date}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tdex-darwin

  # tdexdconnect
  - id: "tdexdconnect"
    main: ./cmd/tdexdconnect
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tdexdconnect
## flag the semver v**.**.**-<tag>.* as pre-release on Github
release:
  prerelease: auto

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

archives:
  - id: tdexd
    format: binary
    builds:
      - tdexd-linux-amd64
      - tdexd-linux-arm64
      - tdexd-darwin-amd64
      - tdexd-darwin-arm64
    name_template: "tdexd-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  - id: tdex
    format: binary
    builds:
      - tdex
    name_template: "tdex-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

  - id: tdexdconnect
    format: binary
    builds:
      - tdexdconnect
    name_template: "tdexdconnect-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

dockers:
  ###########################
  # tag latest & prerelease #
  ###########################

  #amd64
  - image_templates:
      - "ghcr.io/tdex-network/tdexd:{{ .Tag }}-amd64"
        # push always either release or prerelease with a docker tag with the semver only
    skip_push: "false"
    use: buildx
    dockerfile: Dockerfile
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Template of the docker build flags.
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=tdexd"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"

    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd
      - api-spec

  # arm64
  - image_templates:
      - "ghcr.io/tdex-network/tdexd:{{ .Tag }}-arm64v8"
        # push always either release or prerelease with a docker tag with the semver only
    skip_push: "false"
    use: buildx
    dockerfile: Dockerfile
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: arm64
    # Template of the docker build flags.
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=tdexd"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.Commit}}"
      - "--build-arg=DATE={{.Date}}"

    extra_files:
      - go.mod
      - go.sum
      - internal
      - config
      - pkg
      - cmd
      - api-spec

docker_manifests:
  - name_template: ghcr.io/tdex-network/tdexd:{{ .Tag }}
    image_templates:
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-amd64
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-arm64v8
    skip_push: "false"

  - name_template: ghcr.io/tdex-network/tdexd:latest
    image_templates:
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-amd64
      - ghcr.io/tdex-network/tdexd:{{ .Tag }}-arm64v8
    skip_push: auto

```

### goreleaser version

```bash
goreleaser/goreleaser-action@v2
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_
