### ISSUE TITLE
Archives arbitrary project files without binaries

### ISSUE THREAD

**Issue by 56KBs** [goreleaser/goreleaser#3085]
### Is your feature request related to a problem? Please describe.

We'd like to be able to publish the terraform module to our GitLab terraform registry for our Go project as part of GoReleaser. This requires archiving our terraform module directory and uploading it to GitLab.

### Describe the solution you'd like

I'd like to be able to create an archive from arbitrary files within the repository, without requiring a binary to be bundled with the archive. For example:

```yaml
archives:
  -
    id: terraform
    name_template: "{{ .ProjectName }}_{{ .Version }}_terraform"
    files:
      - terraform/*


```

### Describe alternatives you've considered

I've considered using a custom publisher which contains a script to archive + push to the terraform registry however this would become quite cumbersome to use as it'd require copying the script across numerous repositories with the same code.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
this seems like a good idea...

what do you think the API should look like?

**Comment by 56KBs** [comment]
> this seems like a good idea...
> 
> what do you think the API should look like?

Is it possible to make it so that the existing `archive` configuration can allow for an empty `builds:` list so you end up with something like:

```yaml
archives:
  -
    id: terraform
    builds: 
    name_template: "{{ .ProjectName }}_{{ .Version }}_terraform"
    files:
      - terraform/*
    allow_different_binary_count: true
```

I'm not sure if that'd cause any issues for existing users, but it seems like logical configuration to create an archive, without any builds within it.
