### ISSUE TITLE
Issue publishing new release on v1.9.0

### ISSUE THREAD

**Issue by G-Rath** [goreleaser/goreleaser#3115]
### What happened?

I went to publish a new version (v0.5.0) of [`osv-detector`](https://github.com/G-Rath/osv-detector) and it failed right at the end when trying to push the release to github:

```
   ⨯ release failed after 170.51s error=scm releases: failed to publish artifacts: PATCH https://api.github.com/repos/G-Rath/osv-detector/releases/0: 404 Not Found []
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.9.0/x64/goreleaser' failed with exit code 1
```

I tried restarting the build, and with a new tag (v0.5.1) just in case it was being thrown off by the release & tag previously being drafted and then deleted (which I _think_ I did for v0.5.0, but can't remember so I tried a new tag just incase).

* https://github.com/G-Rath/osv-detector/runs/6513401634?check_suite_focus=true
* https://github.com/G-Rath/osv-detector/runs/6513046522?check_suite_focus=true
* https://github.com/G-Rath/osv-detector/runs/6513271249?check_suite_focus=true

I've not changed anything in my GitHub profile or repository - the only difference I knew of between these runs and the last release (which was a month ago) was that that run was using v1.8.3, and these runs were using v1.9.0.

So I pinned `goreleaser` to v1.8.3 (https://github.com/G-Rath/osv-detector/pull/97) and that was successful: https://github.com/G-Rath/osv-detector/runs/6513592978?check_suite_focus=true

### How can we reproduce this?

I don't know for sure - hopefully it will be enough to use my actions workflow:

```
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 1.9.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### goreleaser version

```bash
v1.9.0
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Looking over the changelogs, the main change that jumped out at me was that `go-github` was updated from v43 to v44.
