### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by rsteube** [goreleaser/goreleaser#3118]
### Is your feature request related to a problem? Please describe.

Isn't #1310 fairly easy now with [nfpm](https://github.com/goreleaser/nfpm)?
Tried a `deb` build with different `bindir` and could install it successfully with `dpkg --force-all` (was just complaining about achitecture not being specified as `aarch64`).

### Describe the solution you'd like

Termux config or ability to set architecture name for deb file. Maybe not even needed and was just sth. related to installing it with `dpkg` instead of `pkg`. Ideally just needs documentation.

### Describe alternatives you've considered

Configuring a second `nfpm` build:
```yaml
    id: termux
    formats:
      - deb
    file_name_template: "{{ .ConventionalFileName }}_termux"
    bindir: /data/data/com.termux/files/usr/bin
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
