### ISSUE TITLE
Allow `env` in BuildDetailsOverride

### ISSUE THREAD

**Issue by arbourd** [goreleaser/goreleaser#3119]
### Is your feature request related to a problem? Please describe.

When cross building with CGO you often need to change the `env` vars to point to different compiler toolchains. I would like to set that with the `overrides` stanza.

### Describe the solution you'd like

```yaml
overrides:
  - goos: linux
    goarch: amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
  - goos: linux
    goarch: arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
```

Trying this yields:

```console
    ⨯ release failed after 0.00s error=failed to load config: yaml: unmarshal errors:
  line 34: field env not found in type config.BuildDetailsOverride
  line 43: field env not found in type config.BuildDetailsOverride 
```

### Describe alternatives you've considered

The alternative is just many `id:` blocks with the env, but that's less elegant. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
