### ISSUE TITLE
DEPRECATED: nfpms.maintainer

### ISSUE THREAD

**Issue by runeimp** [goreleaser/goreleaser#3124]
### What happened?

I ran GoReleaser v1.9.1 on macOS Big Sur and was getting

```
• loading config file       file=.goreleaser.yml
• checking config: 
      • DEPRECATED: `nfpms.maintainer` should not be used anymore, check https://goreleaser.com/deprecations#nfpmsmaintainer for more info
⨯ command failed            error=config is valid, but uses deprecated properties, check logs above for details
```

Which sounds like that config field is going away. Following the link provided says

> nFPM will soon make mandatory setting the maintainer field.

This was apparently updated a few weeks ago for version 1.9.0. These two statements seem incompatible to me.

### How can we reproduce this?

My `.goreleaser.yml` contains

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: alphanum
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  goos:
    - darwin
    - freebsd
    - linux
    - netbsd
    - openbsd
    - windows
  ignore:
    - goos: darwin
      goarch: 386
  ldflags:
    - -s -w
  main: ./cmd/alphanum/alphanum.go
archives:
  - files:
      - CHANGELOG.md
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
      # darwin: macOS
      # freebsd: FreeBSD
      # linux: Linux
      # netbsd: NetBSD
      # openbsd: OpenBSD
      # windows: Windows
    wrap_in_directory: true
nfpms:
  - formats:
      - deb
      - rpm
    # ID of the nfpm config, must be unique.
    # Defaults to "default".
    id: alphanum
    homepage: "https://github.com/runeimp/alphanum"
    license: MIT
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
checksum:
  name_template: 'checksums.txt'
# signs:
#   - artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

```

### goreleaser version

```bash
goreleaser version 1.9.1
commit: e8307e88345f36a84a3a1bb5c24d947ad68cce40
built by: homebrew
goos: darwin
goarch: amd64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Note that I checked the "goreleaser check shows no errors" box so I could submit this bug which will _NOT_ allow me to to run `goreleaser check` without generating errors.

Also the docs (at least for the deprecation page) show the hyphen for `maintainer` is directly bellow `nfpms` key instead of indented with two spaces. I added the field to my config to see if that would get rid of the error. Either way gives an error but with matching the docs when running `goreleaser check` I get

```
• loading config file       file=.goreleaser.yml
⨯ command failed            error=yaml: line 52: did not find expected key
```

Line 52 is the line I added `- maintainer: 'RuneImp <runeimp@gmail.com>'`. If I indent it two spaces I get the same error as when I don't have in my config at all.
