### ISSUE TITLE
GoReleaser Pro 1.9.1 cannot upload release artifacts

### ISSUE THREAD

**Issue by arbourd** [goreleaser/goreleaser#3132]
### What happened?

Running GoReleaser Pro 1.9.1 no longer works in private workflow (without any changes to the .goreleaser.yml)

```console
      • scm releases
         • token type                type=github
         • creating or updating release repo=github/example tag=example-v1.0.0
         • release updated           url=
   ⨯ release failed after 33.29s error=scm releases: failed to publish artifacts: PATCH https://api.github.com/repos/github/example/releases/123456789: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```

### How can we reproduce this?

Build a **monorepo** project with GoReleaser Pro 1.9.1

```yaml
project_name: example

monorepo:
  tag_prefix: example-
  dir: .

builds:
  - id: example
    main: .
    binary: example
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

archives:
  - id: example-archive
    name_template: 'example-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - example
```

```console
$ GORELEASER_KEY="" GITHUB_TOKEN="" goreleaser release --rm-dist -f example.goreleaser.yml
...
   ⨯ release failed after 33.29s error=scm releases: failed to publish artifacts: PATCH https://api.github.com/repos/github/example/releases/12345678: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```

### goreleaser version

```bash
$ goreleaser --version
goreleaser version 1.9.1-pro
commit: 20ccfaaa649e49b3e6c009d9be1e240c678e0106
built at: 2022-05-20T13:25:49Z
built by: goreleaser
goos: darwin
goarch: arm64

https://goreleaser.com/pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
