### ISSUE TITLE
How to build multiple binaries into one package?

### ISSUE THREAD

**Issue by lonnywong** [goreleaser/goreleaser#3168]
### Is your feature request related to a problem? Please describe.

There are 2 binaries in my package.

```
cmd
├── trz
│   └── main.go
└── tsz
    └── main.go
```

I want to release all of them into one package file. e.g.: `trzsz_1.0.0_linux_amd64.deb`.

How to do that?

### Describe the solution you'd like

```yml
builds:
  - id: trzsz
    - main: ./cmd/trz
      binary: trz
    - main: ./cmd/tsz
      binary: tsz
```

### Describe alternatives you've considered

```yml
builds:
  - id: trz
    main: ./cmd/trz
    binary: trz
  - id: tsz
    main: ./cmd/tsz
    binary: tsz
```

This is not what I want. It gives me 2 package files:
```
trz_1.0.0_linux_amd64.deb
tsz_1.0.0_linux_amd64.deb
```

What I want is to put them into one package file. e.g.:
```
trzsz_1.0.0_linux_amd64.deb
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
