### ISSUE TITLE
Parallel docker builds result in duplicate name error

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#3187]
### What happened?

My release process builds two container images. One for amd64 and one for arm64. These images are pushed with the `docker_manifests` feature in order to build a multi arch image.

I get this error most of the time. It seems to be more frequent on my AMD 5950x (32 thread) system. I also get this error on my Macbook pro but less frequently. It seems more common on the more powerful system.

```
   • docker images    
      • building docker image     image=myaccount/myapp-arm64:latest
      • building docker image     image=myaccount/myapp-amd64:latest
   ⨯ release failed after 80.69s error=docker build failed: failed to build myaccount/myapp-amd64:latest: exit status 1: #1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 3.4s done
#1 creating container buildx_buildkit_eloquent_lederberg0 done
#1 ERROR: Error response from daemon: Conflict. The container name "/buildx_buildkit_eloquent_lederberg0" is already in use by container "e3fb3308b53c663e6ebb3ee247d685aef4c6cf4955e63dd47a0e2e8539f7235f". You have to remove (or rename) that container to be able to reuse that name.
------
 > [internal] booting buildkit:
------
error: Error response from daemon: Conflict. The container name "/buildx_buildkit_eloquent_lederberg0" is already in use by container "e3fb3308b53c663e6ebb3ee247d685aef4c6cf4955e63dd47a0e2e8539f7235f". You have to remove (or rename) that container to be able to reuse that name.

Learn more at https://goreleaser.com/errors/docker-build

make: *** [Makefile:268: release-test] Error 1
```

### How can we reproduce this?

It feels like a race condition. It might play nice on your system, or it might not. Setup multiple docker builds and try to run the builld until it happens.

### goreleaser version

```bash
goreleaser version 1.9.1
commit: e8307e88345f36a84a3a1bb5c24d947ad68cce40
built at: 2022-05-20T14:44:16Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.9.1, checksum: h1:YtQg3W9MFYinzRPuWQ1uAV0ikLz49JKBgAnZWsXk7Q4=
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I can work around this issue by setting parallel to 1, but this is very slow as I am building 13 binaries, 13 archives, 15 packages, and two container images. All working wonderfully outside of this :+1:

**Comment by jsirianni** [comment]
Sure thing. Replaced dockerhub account / image name, otherwise accurate. 

```yaml
dockers:
- goos: linux
  goarch: amd64
  ids:
  - app
  image_templates:
  - "account/app-amd64:latest"
  - "account/app-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - "account/app-amd64:{{ .Major }}.{{ .Minor }}"
  - "account/app-amd64:{{ .Major }}"
  - "account/app-amd64:{{ .ShortCommit }}"
  dockerfile: ./Dockerfile
  use: buildx
  build_flag_templates:
  - "--label=created={{.Date}}"
  - "--label=title={{.ProjectName}}"
  - "--label=revision={{.FullCommit}}"
  - "--label=version={{.Version}}"
  - "--platform=linux/amd64"
- goos: linux
  goarch: arm64
  ids:
  - app
  image_templates:
  - "account/app-arm64:latest"
  - "account/app-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  - "account/app-arm64:{{ .Major }}.{{ .Minor }}"
  - "account/app-arm64:{{ .Major }}"
  - "account/app-arm64:{{ .ShortCommit }}"
  dockerfile: ./Dockerfile
  use: buildx
  build_flag_templates:
  - "--label=created={{.Date}}"
  - "--label=title={{.ProjectName}}"
  - "--label=revision={{.FullCommit}}"
  - "--label=version={{.Version}}"
  - "--platform=linux/arm64"

docker_manifests:
  - name_template: "account/app:latest"
    image_templates:
      - "account/app-amd64:latest"
      - "account/app-arm64:latest"
    skip_push: false
  - name_template: "account/app:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "account/app-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "account/app-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
  - name_template: "account/app:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "account/app-amd64:{{ .Major }}.{{ .Minor }}"
      - "account/app-arm64:{{ .Major }}.{{ .Minor }}"
    skip_push: false
  - name_template: "account/app:{{ .Major }}"
    image_templates:
      - "account/app-amd64:{{ .Major }}"
      - "account/app-arm64:{{ .Major }}"
    skip_push: false
  - name_template: "account/app:{{ .ShortCommit }}"
    image_templates:
      - "account/app-amd64:{{ .ShortCommit }}"
      - "account/app-arm64:{{ .ShortCommit }}"
```
