### ISSUE TITLE
Configure placement of binary in archive.

### ISSUE THREAD

**Issue by nathanhammond** [goreleaser/goreleaser#3215]
### Is your feature request related to a problem? Please describe.

I would like to be able to control the placement of the binary within the archive separately from placement within `dist`.

```yaml
builds:
  - id: turbo
    main: ./cmd/turbo
    binary: subdir/turbo
archives:
  - id: default
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
```

Archive output:
```
turbo-1.3.2-windows_arm64/LICENSE
turbo-1.3.2-windows_arm64/README.md
turbo-1.3.2-windows_arm64/subdir/turbo.exe
                          ^^^^^^
```

In many cases this is fine but if I want to toggle `no_unique_dist_dir` and then use the `binary` property to reimplement a different "unique" structure, the entirety of that path appears in the archive.

```yaml
builds:
  - id: turbo
    main: ./cmd/turbo
    no_unique_dist_dir: true
    binary: turbo-{{.Os}}-{{ if (eq .Arch "amd64") }}64{{ end }}{{ if not (eq .Arch "amd64") }}{{ if (eq .Arch "386") }}32{{ end }}{{ if not (eq .Arch "386") }}{{ .Arch }}{{ end }}{{ end }}{{ if not (eq .Ext ".exe") }}/bin{{ end }}/turbo
archives:
  - id: default
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
```

Archive output:
```
turbo-1.3.2-windows_arm64/LICENSE
turbo-1.3.2-windows_arm64/README.md
turbo-1.3.2-windows_arm64/turbo-windows-arm64/turbo.exe
                          ^^^^^^^^^^^^^^^^^^^
```

### Describe the solution you'd like

I'd propose a new `binary` key inside of the `archive` object which enables me to specify the name relative to the root of the produced archive.

(Aside: currently `Ext` isn't plumbed through to `archives` templates.)

```yaml
archives:
  - id: default
    wrap_in_directory: true
    binary: turbo{{ .Ext }}
    files:
      - LICENSE
      - README.md
```

Archive output:
```
turbo-1.3.2-windows_arm64/LICENSE
turbo-1.3.2-windows_arm64/README.md
turbo-1.3.2-windows_arm64/turbo.exe
```

### Describe alternatives you've considered

One attempted workaround which *almost* does what I want:
```yaml
archives:
  - id: default
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - src: dist/turbo-{{.Os}}-{{ if (eq .Arch "amd64") }}64{{ end }}{{ if not (eq .Arch "amd64") }}{{ if (eq .Arch "386") }}32{{ end }}{{ if not (eq .Arch "386") }}{{ .Arch }}{{ end }}{{ end }}{{ if (eq .Os "windows") }}/turbo.exe{{ end }}{{ if not (eq .Os "windows") }}/bin/turbo{{ end }}
        dst: .
        strip_parent: true
```

This enables me to place the asset where I want it; but I am unable to prevent the addition of the binary at the full path:

Archive output:
```
turbo-1.3.2-windows_arm64/LICENSE
turbo-1.3.2-windows_arm64/README.md
turbo-1.3.2-windows_arm64/turbo.exe
turbo-1.3.2-windows_arm64/turbo-windows-arm64/turbo.exe
                          ^^^^^^^^^^^^^^^^^^^
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

`meta: true` in the archive immediately breaks because it is no longer per-build.

**Comment by caarlos0** [comment]
an archive can have multiple binaries... maybe a different approach:

```yaml
archives:
  - id: default
    wrap_in_directory: true
    strip_binary_parent_dir: true # this
    files:
      - LICENSE
      - README.md
```

wdyt?
