### ISSUE TITLE
GitLab self-hosted 13.4.3 release link is a 404 link

### ISSUE THREAD

**Issue by laojianzi** [goreleaser/goreleaser#3299]
### What happened?

gitlab Self-hosted 13.4.3

release link `direct_asset_url` is a 404 link

### How can we reproduce this?

```yaml
project_name: test
gitlab_urls:
  api: https://domain/api/v4/
  download: https://domain
  skip_tls_verify: false
builds:
  - id: test
    binary: test
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: '{{ incpatch .Version }}'
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
release:
  gitlab:
    owner: repo
    name: test
  disable: false
```

### goreleaser version

```bash
goreleaser version 1.10.3
commit: 315935aedc9908b078ae525b33ddb42b2fafcc54
built by: homebrew
goos: darwin
goarch: amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

If you edit the release in gitlab and save it without changing any data

`direct_asset_url` will become the same as `url` and will be a downloadable link
