### ISSUE TITLE
Conditionally Replacements 

### ISSUE THREAD

**Issue by suntong** [goreleaser/goreleaser#332]
```yaml
  # Replacements for GOOS and GOARCH on the archive name.
  # The keys should be valid GOOS or GOARCH values followed by your custom
  # replacements.
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
```

Can I do the replacement conditionally? 
E.g., only rename `amd64: ` when `GOOS` is `windows`?

thx
