### ISSUE TITLE
FPM deb build failing

### ISSUE THREAD

**Issue by drewsonne** [goreleaser/goreleaser#333]
I'm having an error with fpm building deb packages on travis. I've tried locking my fpm version to a known working one, but that doesn't seem to be working.

The error I'm getting is 
`
error={:timestamp=>"2017-08-14T06:53:54.886278+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
`
https://travis-ci.org/drewsonne/go-gocd/jobs/264257111#L908

The FPM section of my config is
```yaml
fpm:
  homepage: https://github.com/drewsonne/go-gocd
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  license: LGPLv3
  formats:
    - deb
    - rpm
  dependencies:
    - git
```

https://github.com/drewsonne/go-gocd/blob/master/.goreleaser.yml#L49

Is this an issue with configuration, or fpm/goreleaser interaction?

I'm not sure it's a bug, but I'm at a dead end as to how to fix it.
