### ISSUE TITLE
Goreleaser can't find checksum.txt file

### ISSUE THREAD

**Issue by bobvanluijt** [goreleaser/goreleaser#334]
Running the following command: `goreleaser --rm-dist --snapshot --skip-validate` results in the following error: `error=open dist/project_checksums.txt: no such file or directory`

Yaml file:

```
project_name: project
builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: windows
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: linux
        goarch: ppc64
      - goos: linux
        goarch: mips
      - goos: linux
        goarch: mipsle
      - goos: linux
        goarch: mips64
      - goos: linux
        goarch: ppc64le
      - goos: linux
        goarch: amd64
      - goos: linux
        goarch: mips64le
      - goos: linux
        goarch: arm6
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  name_template: SNAPSHOT-{{.Commit}}
```
