### ISSUE TITLE
Error with the {{ .ReleaseURL }} templating field on Slack notification

### ISSUE THREAD

**Issue by jbouchery** [goreleaser/goreleaser#3356]
### What happened?

I enabled the Slack announce with the default `message_template` from a Gitlab CI/CD job and received a missing `{{.Env.CI_SERVER_URL}}` environment variable substitution in the message : 

```
myApp 2.0.0-rc1 is out! Check it out at {{.Env.CI_SERVER_URL}}/<myApp_project_path>/-/releases/2.0.0-rc1
```

I also tried it from my local and got the same. I was expecting this environment variable to be replaced.

### How can we reproduce this?

I tried to reproduce the behavior by exporting all environment variables needed and the `CI_SERVER_URL` one and tried a 
 `gorelease release` command

### goreleaser version

```bash
goreleaser --version
goreleaser version 1.11.2
commit: e31f7806dc0073159cc12dce7605073259105a67
built at: 2022-08-31T01:25:33Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.11.2, checksum: h1:LqKj+63p60dRF3PA15+y+DN9jP6IMrxvyOpZ40YLJ5E=
https://goreleaser.com
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

**Comment by caarlos0** [comment]
could you share your config file?

**Comment by caarlos0** [comment]
ah, I see, thanks!

**Comment by caarlos0** [comment]
we're probably setting it un-templated somewhere into the context: https://github.com/goreleaser/goreleaser/blob/main/internal/tmpl/tmpl.go#L100 

need to see where, and fix it there.

This likely affects more things...

**Comment by jonasagx** [comment]
Shouldn't it also process the username in a config like this one?
```yaml
artifactories:
  - name: production
    target: "{{ .Env.ARTIFACTORY_SERVER_ADDRESS }}/{{ .ProjectName }}/{{ .Version }}/" # rendered correctly
    mode: archive
    username: "{{ .USERNAME }}" # not rendered :( 
```
