### ISSUE TITLE
Gitlab changelog generation fails with 404

### ISSUE THREAD

**Issue by brumhard** [goreleaser/goreleaser#3358]
### What happened?

I tried to use the `use: gitlab` option for my project but it failed during generation with a 404 error.
The problem might be that it does not encode the project path in the request URL.
(around here: https://github.com/goreleaser/goreleaser/blob/57ef9f0220790f58d5531f718736d528ecb3c9a3/internal/client/gitlab.go#L58)

### How can we reproduce this?

goreleaser config (only relevant parts):

```yaml
project_name: kindacool

changelog:
  use: gitlab
  sort: asc
  groups:
    - title: New Features and updates
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Documentation updates
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other Work
      order: 999
  filters:
    # Commit messages matching the regexp listed here will be removed from
    # the changelog
    exclude:
      - "^refactor:"
      - "^chore"

gitlab_urls:
  api: https://gitlab.example.com/api/v4/
  download: https://gitlab.example.com
  use_package_registry: true
  # Set this if you set GITLAB_TOKEN to the value of CI_JOB_TOKEN:
  use_job_token: true
```

`git remote -vv` output:

```
origin  ssh://git@gitlab.example.com/tbrumhard/kindacool.git (fetch)
origin  ssh://git@gitlab.example.com/tbrumhard/kindacool.git (push)
```

goreleaser failing log:

```
• generating changelog
⨯ release failed after 0s                          error=GET https://gitlab.example.com/api/v4/projects/tbrumhard/kindacool/repository/compare: 404 {message: 404 Project Not Found}
```

The URL that works instead is `https://gitlab.example.com/api/v4/projects/tbrumhard%2Fkindacool/repository/compare` (project path URL encoded). See also the [gitlab docs](https://docs.gitlab.com/ee/api/index.html#namespaced-path-encoding) for encoding.

gitlab version: `15.3.2-ee`

### goreleaser version

```bash
v1.11.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Could be related to #1799
