### ISSUE TITLE
Linux packages (via nFPM) doc still contains nFPM v1 properties

### ISSUE THREAD

**Issue by e-grigorov** [goreleaser/goreleaser#3380]
### What happened?

I am looking at [Linux packages (via nFPM) document](https://goreleaser.com/customization/nfpm/), in the `available options` section, there are:
```
# Some attributes can be overridden per package format.
 overrides:
...
   rpm:
     replacements:
       amd64: x86_64
     file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
     files:
       "tmp/man.gz": "/usr/share/man/man8/app.8.gz"
...
```
The point is that `files` configuration property was part of nFPM v1 and with the migration to nFPM v2, it's not supported any more. I am not sure whether there is a replacement or it just has to be removed.

### How can we reproduce this?

It's a documentation issue and there are no steps to reproduce.

### goreleaser version

```bash
goreleaser version dev
goos: windows
goarch: amd64
module version: v1.11.2, checksum: h1:LqKj+63p60dRF3PA15+y+DN9jP6IMrxvyOpZ40YLJ5E=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
