### ISSUE TITLE
error updating brew formula file statusCode=403

### ISSUE THREAD

**Issue by buschco** [goreleaser/goreleaser#3399]
### What happened?

I created a Personal Access Token under https://gitlab.selfhost.com/-/profile/personal_access_tokens (I also tried Project a project access token created at the brew tap repo)

After publishing `publishing ->  scm releases` it fails:

```
⨯ error updating brew formula file             branch=main err=PUT https://gitlab.selfhost.com/api/v4/projects/buschco/homebrew-tap/repository/files/my-go-program.rb: 403 {message: 403 Forbidden} fileName=my-go-program.rb projectID=buschco/homebrew-tap statusCode=403
  • took: 3s
  ⨯ release failed after 2m29s               error=homebrew tap formula: failed to publish artifacts: PUT https://gitlab.selfhost.com/api/v4/projects/buschco/homebrew-tap/repository/files/my-go-program.rb: 403 {message: 403 Forbidden}
```

Either a GitLab upgrade or a new version of `goreleaser` broke my pipeline

### How can we reproduce this?

.goreleaser.yml
```yml
brews:
  - name: my-go-
    tap:
      owner: buschco
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaser
      email: bot@company.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
```

and this CI file:

```yml
release:
  dependencies:
    - "test"
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - HOMEBREW_TAP_TOKEN="$HOMEBREW_TAP_TOKEN" GITLAB_TOKEN="$CI_JOB_TOKEN" goreleaser release --rm-dist
```

### goreleaser version

```bash
goreleaser version 1.11.4
commit: d19ff6eb1eeca75e2bb3fbeaf473b3d0dc6ffc81
built at: 2022-09-19T00:31:33Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.11.4, checksum: h1:bmXfkrBa6xv3WzzZM7U0QCOmpFAanIm+91tFB4DYUnI=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

- It seems like the Personal Access Token is never used.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/14929556/192149995-51965d82-8ae6-4691-8388-3dcfb977cfb9.png">

- GitLab Community Edition [15.2.2](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v15.2.2)
