### ISSUE TITLE
[Pro] failed to parse tag 'nightly' as semver: Invalid Semantic Version

### ISSUE THREAD

**Issue by ruudk** [goreleaser/goreleaser#3483]
### What happened?

I'm using Pro and I automatically create a nightly release for every commit to main:
```yaml
      - if: "${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
        name: 'GoReleaser: Create nightly build'
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --nightly --debug
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
```

```
nightly:
  publish_release: true
  keep_single_release: true
```

This works fine.
<img width="1157" alt="Screenshot 2022-10-20 at 13 19 42@2x" src="https://user-images.githubusercontent.com/104180/196935067-f8c22cd7-c32b-4840-93e6-51303b8d8df7.png">

But as soon as I run the following action on Pull Requests it fails:
```yaml
      - if: "${{ github.event_name == 'pull_request' }}"
        name: 'GoReleaser: Create snapshot for Pull Request'
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --skip-publish --snapshot --debug
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
```

```
• by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • debug logs enabled
  • running goreleaser v1.12.2-pro
  • skipping license check on snapshot
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loaded config file                               REDACTED
  • parallelism: 2
  • loading environment variables
  • getting and validating git state
    • running git                                    args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
    • git result                                     stderr= stdout=true

    • running git                                    args=[-c log.showSignature=false rev-parse --is-inside-work-tree]
    • git result                                     stderr= stdout=true

    • running git                                    args=[-c log.showSignature=false rev-parse --abbrev-ref HEAD --quiet]
    • git result                                     stderr= stdout=HEAD

    • running git                                    args=[-c log.showSignature=false show --format=%h HEAD --quiet]
    • git result                                     stderr= stdout=83d1d20

    • running git                                    args=[-c log.showSignature=false show --format=%H HEAD --quiet]
    • git result                                     stderr= stdout=83d1d20ea5b419f6b7aa78ad145926ebf5583aaf

    • running git                                    args=[-c log.showSignature=false show --format='%ct' HEAD --quiet]
    • git result                                     stderr= stdout='1666264481'

    • running git                                    args=[-c log.showSignature=false describe --always --dirty --tags]
    • git result                                     stderr= stdout=nightly-4-g83d1d20

    • running git                                    args=[-c log.showSignature=false ls-remote --get-url]
    • git result                                     stderr= stdout=https://github.com/REDACTED

    • running git                                    args=[-c log.showSignature=false tag -l --format='%(contents:subject)' nightly]
    • git result                                     stderr= stdout='Keep default config for nightly'

    • running git                                    args=[-c log.showSignature=false tag -l --format='%(contents)' nightly]
    • git result                                     stderr= stdout='Keep default config for nightly
'

    • running git                                    args=[-c log.showSignature=false tag -l --format='%(contents:body)' nightly]
    • git result                                     stderr= stdout=''

    • running git                                    args=[-c log.showSignature=false describe --tags --abbrev=0 --match=* tags/nightly^]
    • git result                                     stderr= stdout=v1.3.2

    • running git                                    args=[-c log.showSignature=false rev-list -n1 v1.3.2]
    • git result                                     stderr= stdout=68db73c[22](https://github.com/REDACTED/actions/runs/3289098424/jobs/5420225454#step:7:23)51a1dec34c9f90a6f54e70f9c80f0cc

    • running git                                    args=[-c log.showSignature=false tag --points-at 68db73c2251a1dec34c9f90a6f54e70f9c80f0cc --sort -version:refname *]
    • git result                                     stderr= stdout=v1.3.2

    • building...                                    commit=83d1d20ea5b419f6b7aa78ad145926ebf5583aaf latest tag=nightly
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  ⨯ release failed after 0s                  error=failed to parse tag 'nightly' as semver: Invalid Semantic Version
```

### How can we reproduce this?

See above

### goreleaser version

```bash
v1.12.2-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
can repro, thank you, will take a look!

**Comment by caarlos0** [comment]
releasing v1.12.3 with a fix :)

**Comment by ruudk** [comment]
Do I have to wait before the github-action / goreleaser-pro binary is available?

Tried with `latest` and this:
```yaml
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser-pro
          version: v1.12.3
```

```
Run goreleaser/goreleaser-action@v2.9.1
Error: Cannot find GoReleaser v1.12.3 release
```
