### ISSUE TITLE
Add option to PR/MR a homebrew formula

### ISSUE THREAD

**Issue by bwagner5** [goreleaser/goreleaser#3485]
### Is your feature request related to a problem? Please describe.

Homebrew-taps are often used to aggregate tools vended by an organization and may not be maintained by tool maintainers who are posting formulas into the tap. 

The model that I've seen is tool owners will 
1. PR the formula and updates 
2. maintainer of the tap will approve and merge 
 
This allows for a more controlled setting where a single tool owner doesn't have push permissions to wipe out other formulas they don't own (accidentally or maliciously). 

### Describe the solution you'd like

I'd like an option under brews called `pull_request` or something similar which will fork the tap if not already forked, create an updated branch for the release, commit and push to the branch with the latest formula changes, and then open a PR on the tap.

```
# .goreleaser.yaml
brews:
  -
    name: myproject
    ## PullRequest indicates if goreleaser should open a PR on the tap instead of trying to commit directly
    pull_request: true
```

### Describe alternatives you've considered

An alternative solution is to create the forked tap first and specify that as the tap. goreleaser will then commit to the forked tap and the user can raise the PR manually or through an automated post release step. 

A second alternative is to set `skip_upload: true` and then use a post release step to perform the fork, branch, commit, push, and PR.  

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
