### ISSUE TITLE
Update CircleCI guide to 2.0

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#350]
As I fumbled a stupid amount before getting this right, I thought I would share my experience so you can consider updating the CircleCI info to v2.0. Which is pretty impressive once you get it.

For example project CircleCI config:

https://github.com/bep/s3deploy/blob/master/.circleci/config.yml

It uses this Dockerfile:

https://github.com/bep/dockerfiles/blob/master/ci-goreleaser/Dockerfile

Which supplies goreleaser + fpm.

The context "org-global" is where I have set my `GITHUB_TOKEN`. CircleCi currently only support one context, but more are coming.

**Comment by caarlos0** [comment]
Maybe we could have some sample repositories set up as well (for various CIs)

**Comment by dulanov** [comment]
I cant create a patch to this issue, for me right now work this variant:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/.../...
    steps:
      - checkout
      - run: ...
      - run: ...
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              curl -sL https://git.io/goreleaser | bash
            fi
deployment:
  trigger_tag:
    tag: /.*/
```

**Comment by bep** [comment]
I would strongly suggest that you create a Docker image for this. This is all about reproducible builds/releases, and always pulling in the latest Goreleaser sounds fine and dandy, but it will break at some point for someone.

Look at this: https://github.com/gohugoio/hugo/blob/master/.circleci/config.yml

If I don't need any of the new and shiny Goreleaser versions, I can just release with this config until the end of time without breaking a sweat.

**Comment by caarlos0** [comment]
not stale 📦

**Comment by abeMedia** [comment]
I think a general purpose CI build docker image would be great. That way it can be used on CIrcleCI 2.0 as well as GitLab CI, Drone etc.
Happy to submit a PR if you're OK with merging something like that in.

**Comment by caarlos0** [comment]
yeah, I was thinking that the goreleaser docker image right now is kind of useless, as it does not have git nor rpmbuild...

so maybe we can make only this one image that the user can use locally and that anyone could use in the CI... what do you think?

**Comment by bep** [comment]
This is the docker image we use in Hugo:

https://github.com/bep/dockerfiles/blob/master/ci-goreleaser/Dockerfile

I have not had time to update Goreleaser for some time, it has just worked great ... so this is "vintage Goreleaser" with fpm -- but a Goreleaser "official image" should have enough to build a Go project (Git and Go at least). There may be ways to "compose" docker files that I'm not aware of ...

**Comment by bep** [comment]
https://github.com/bep/dockerfiles/blob/master/ci-goreleaser/Dockerfile

Is what we use in Hugo (vintage Goreleaser with FPM ...).

**Comment by caarlos0** [comment]
yes, we could have an image with `goreleaser`, `git`, `rpmbuild` and maybe `go`, and the user could:

```Dockerfile
FROM goreleaser/goreleaser
RUN install my stuff
```

I said 'maybe go', because some people may want different versions of go for some reason, dunno if it's worth to deal with that or just document that the user should install whatever version they want...

**Comment by caarlos0** [comment]
wow, goreleaser v0.34, vintage indeed 😆

**Comment by abeMedia** [comment]
My feeling would be to include the latest version of go by default. Go is backwards compatible so until v2 is out I don't see any reason why not to use the latest release.
Also I think it would be great if we base it off `docker:dind` to allow pushing to docker hub from inside a docker-based CI.

**Comment by caarlos0** [comment]
@abeMedia I agree.
So, if you're willing to open a PR, I'm gladly accepting :D

**Comment by abeMedia** [comment]
Hey, sorry about the late reply! I'll have a bash at it this weekend and submit a PR then.
Thanks!

**Comment by caarlos0** [comment]
great, let me know if you need any help =)

**Comment by jimeh** [comment]
Hopefully this helps. I recently experimented with getting goreleaser working correctly with CircleCI, and I ended up something like this:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jimeh/casecmp
    # [...] - ensures code works and can be built to a binary
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jimeh/casecmp
    # [...] - downloads and runs goreleaser
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*/
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
```

It basically has two different workflows, one which runs on anything that isn't a version tag that only runs the `build` job. And another workflow that only runs on version tags thats runs the `build` and `release` jobs, requiring the `build` step to succeeded for it to run the `release` step.

Full source for my `config.yml` is here: https://github.com/jimeh/casecmp/blob/75542c3748a9c083c8b731d767ba37e6339371ce/.circleci/config.yml
