### ISSUE TITLE
Update Travis instructions

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#351]
We can use the travis deploy section, like this:

```yaml
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
```
