### ISSUE TITLE
Add option to push homebrew formula to arbitrary git repo

### ISSUE THREAD

**Issue by graytonio** [goreleaser/goreleaser#3525]
### Is your feature request related to a problem? Please describe.

We use an internal bitbucket server for hosting our source for tools as well as a private homebrew tap. Currently the workflow with gitreleaser requires us to manually move the generated formulas into the tap repository to update them.  It is a pain point in our workflow to have to move these formulas into place as an extra step to keep tools updated.

### Describe the solution you'd like

I would like the option to push the brew formula to any git repository not just a GitHub or GitLab one.  I have seen other publish targets like AUR have options for this with `git_url` and `private_key` to push artifacts.  I would imagine the config looking something like this.
```yaml
#.goreleaser.yaml
brews:
  - name: mytool
     tap:
       branch: main
       git_url: 'ssh://user@git.example.com/mytool.git'
       private_key: '{{ .Env.BREW_MYTOOL_SECRET }}'
```

So if a git_url is passed it uploads using those credentials.

### Describe alternatives you've considered

Currently the alternative is to have an extra step in the CI/CD to commit the artifact to the correct repo.  It creates another configuration to look at to resolve build issues which we are trying to reduce having more configurations in one place reduces points we have to check.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
