### ISSUE TITLE
NFPMS: no packager for archlinux

### ISSUE THREAD

**Issue by peltho** [goreleaser/goreleaser#3560]
### What happened?

`nfpms` option from goreleaser cannot understand the `archlinux` format.
The following command: `goreleaser release --snapshot --rm-dist` results in: 
```
⨯ release failed after 0s                  error=no packager registered for the format archlinux
```
However, `apk`, `rpm` and `deb` formats are working fine as expected producing corresponding packages.

### How can we reproduce this?

Here is my very basic `.goreleaser.yaml` file:
```yaml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/tufw/main.go
    binary: tufw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - 
    id: packages
    homepage: https://github.com/peltho/tufw
    maintainer: François Pignon <foo.bar@gmail.com>
    description: "A random description"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - ufw

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
```

### goreleaser version

```bash
goreleaser version 1.12.3
commit: e27e6a9e8c66ec5d2bbcafb1c047068bcf250269
built at: 2022-10-20T12:30:56Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.12.3, checksum: h1:sTJXdkGQO9eAP6pwEUazaD6ERJewZ7yzQexWEGPUVg4=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Here is the full output of the `goreleaser release --snapshot --rm-dist` command:

```
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loading environment variables
  • getting and validating git state
    • ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
    • building...                                    commit=6f56901ebf50e3ea8bcacd086819aae07d91d375 latest tag=v0.0.0
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • running before hooks
    • running                                        hook=go mod tidy
    • running                                        hook=go generate ./...
  • snapshotting
    • building snapshot...                           version=0.0.1-next
  • checking distribution directory
    • --rm-dist is set, cleaning it up
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/tufw_linux_386/tufw
    • building                                       binary=dist/tufw_linux_amd64_v1/tufw
    • building                                       binary=dist/tufw_linux_arm64/tufw
  • archives
    • creating                                       archive=dist/tufw_0.0.1-next_Linux_386.tar.gz
    • creating                                       archive=dist/tufw_0.0.1-next_Linux_amd64.tar.gz
    • creating                                       archive=dist/tufw_0.0.1-next_Linux_arm64.tar.gz
  • linux packages
    • creating                                       arch=amd64v1 file=dist/tufw_0.0.1-next_linux_amd64.apk format=apk package=tufw
    • creating                                       arch=arm64 file=dist/tufw_0.0.1-next_linux_arm64.deb format=deb package=tufw
    • creating                                       arch=arm64 file=dist/tufw_0.0.1-next_linux_arm64.apk format=apk package=tufw
    • creating                                       arch=amd64v1 file=dist/tufw_0.0.1-next_linux_amd64.deb format=deb package=tufw
    • creating                                       arch=386 file=dist/tufw_0.0.1-next_linux_386.apk format=apk package=tufw
    • creating                                       arch=arm64 file=dist/tufw_0.0.1-next_linux_arm64.rpm format=rpm package=tufw
    • creating                                       arch=amd64v1 file=dist/tufw_0.0.1-next_linux_amd64.rpm format=rpm package=tufw
    • creating                                       arch=386 file=dist/tufw_0.0.1-next_linux_386.rpm format=rpm package=tufw
    • creating                                       arch=386 file=dist/tufw_0.0.1-next_linux_386.deb format=deb package=tufw
  ⨯ release failed after 0s                  error=no packager registered for the format archlinux
```
