### ISSUE TITLE
support creating a reproducible tar archive

### ISSUE THREAD

**Issue by fho** [goreleaser/goreleaser#3582]
### Is your feature request related to a problem? Please describe.

I would like to create reproducible .tar archive for releases.
When running goreleaser with the same go version, on the same go source files on different systems it should produce the same archive.

### Describe the solution you'd like

Having a boolean `reproducible` option in the `archive` configuration file section.

By default i would be enabled and create a tar archive using the options described at:
https://reproducible-builds.org/docs/archives/

```sh
$ tar --sort=name \
      --mtime="@${SOURCE_DATE_EPOCH}" \
      --owner=0 --group=0 --numeric-owner \
      --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
      -cf product.tar build
```

### Describe alternatives you've considered

I tried to set owner and file mtime via:
```yml
info:
  owner: 0
  group: 0
  mode: 0755
  mtime: 2008-01-02T15:04:05Z
```

to create archives with a single binary.
I was not able to find a way to set these options for the binary created by `go build`. It seems that it is only possible use `info:` for other files then the compiled go binary. 

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
have you tried following https://goreleaser.com/customization/build/?h=reprodu#reproducible-builds ?

**Comment by fho** [comment]
@caarlos0 yes, that works  fine for building the binary. 
The issue is about making a created tar archive also reproducible

**Comment by caarlos0** [comment]
if you only have the binary in the archive, and the binary is reproducible, it should be reproducible too... did you find something different?

also, the options you linked can't be used because goreleaser does not use `tar`.

**Comment by fho** [comment]
> if you only have the binary in the archive, and the binary is reproducible, it should be reproducible too... did you find something different?

I had a deeper look, I think it's only missing to be able to enforce the uid/gid for the main binary in the tar archive.

I can't find a way to specify it, for additional files it can be set in `files.src.info:`.

This does not work:

```yml
project_name: "example"
builds:
  - goos:
      - linux
    goarch:
      - amd64
archives:
  - format: tar.xz
    files:
      - none*
      - src: 'example'
        strip_parent: true
        info:
          owner: 0
```

```sh
$ tree
.
├── go.mod
└── main.go

0 directories, 2 files
$ cat main.go
package main

import "fmt"

func main() {
	fmt.Println("HELLO")
}
$ cat go.mod
module goreleaserexample

go 1.19
```

result:
```
error=failed to find files to archive: globbing failed for pattern example: matching "./example": file does not exist
```

**Comment by caarlos0** [comment]
check #3618

**Comment by fho** [comment]
@caarlos0 awesome, thanks a lot! :-)

**Comment by myitcv** [comment]
@caarlos0 we've also just run into this when creating `.tar.gz` artefacts:

https://github.com/cue-lang/cue/issues/2177

I tried out https://github.com/goreleaser/goreleaser/pull/3618 but that didn't seem to work for me.

Please let us know if we can provide more information from our side to help with this?

**Comment by caarlos0** [comment]
@myitcv I made a PR at #3618, can you try it out? Hopefully it fixes this :)

**Comment by myitcv** [comment]
> @myitcv I made a PR at #3618, can you try it out? Hopefully it fixes this :)

As I commented above in https://github.com/goreleaser/goreleaser/issues/3582#issuecomment-1342384882, that PR doesn't fix things for me unfortunately. 

> I tried out https://github.com/goreleaser/goreleaser/pull/3618 but that didn't seem to work for me.

**Comment by myitcv** [comment]
@caarlos0 here's a test that demonstrates the problem:

```
# Test to show that goreleaser .tar.gz artefacts are not reproducible.
# The key here is the setting of GOCACHE to a new directory. This
# correctly simulates building a release binary with the same sha256sum
# (assuming -trimpath etc are used) but which has different timestamps
# because it was created fresh.

# To test https://github.com/goreleaser/goreleaser/pull/3618
# uncomment the following line
# mv .goreleaser.yaml.new .goreleaser.yaml

# run1
env GOCACHE=$WORK/cache1
exec goreleaser release --rm-dist --snapshot
exec sha256sum dist/hello_world_Linux_arm64.tar.gz
cp stdout run1

# run2
env GOCACHE=$WORK/cache2
exec goreleaser release --rm-dist --snapshot
exec sha256sum dist/hello_world_Linux_arm64.tar.gz
cp stdout run2

# Ensure the sums from both runs are identical
cmp run1 run2

-- go.mod --
module mod.com

go 1.18
-- main.go --
package main

import "fmt"

func main() {
	fmt.Println("Hello, world")
}
-- .goreleaser.yaml --
project_name: hello_world
gomod:
  proxy: true
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

-- .goreleaser.yaml.new --
project_name: hello_world
gomod:
  proxy: true
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    builds_info:
      group: root
      owner: root
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
```

The problem is that with a clear `GOCACHE`, then the binaries generated by `go build` have different timestamps. They have identical `sha256sum` values, but different timestamps. Hence, the test of simply running two consecutive builds is not sufficient AFAICT. 

The test above: 

* fails on current tip ddf7660b6d6621804c15cbbb3864a66de9f06876
* fails against #3618 (381a11b15ece27b08511d50b668fdf016e4d4c01), even with the uncommenting shown in the test above
* succeeds against a hack PR I put together in #3635 (c56e015c46334bf5695867f5c11f23116857cec7)

Please use from #3635 whatever you want. I'm quite happy for you to close it and submit a proper more clean fix. It was just a proof of concept.
