### ISSUE TITLE
Command `init` includes deprecated `archives.replacements` in config

### ISSUE THREAD

**Issue by trallnag** [goreleaser/goreleaser#3625]
### What happened?

Currently looking at GoReleaser for the first time. Noticed that in the generated config includes the deprecated `archives.replacements` section.

```
replacements:
  darwin: Darwin
  linux: Linux
  windows: Windows
  386: i386
  amd64: x86_64
```

According to <https://goreleaser.com/customization/archive/> this has been deprecated recently.

### How can we reproduce this?

```
goreleaser init
```

### goreleaser version

```
goreleaser version 1.13.1
commit: b0ffc7af05aa391b766e8e26f5ad5ec37c640d6e
built by: homebrew
goos: linux
goarch: amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
