### ISSUE TITLE
release not possible on private gitea instance

### ISSUE THREAD

**Issue by stsmdt** [goreleaser/goreleaser#3661]
### What happened?

When running `goreleaser release --rm-dist` the output is:
```
  ⨯ release failed after 2s                  error=scm releases: failed to publish artifacts: token is required
```
I checked `dist/config.yaml` and it shows the following:

```yaml
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
```

Running `cat ~/.config/goreleaser/gitea_token` prints out the token.

### How can we reproduce this?

Probably reproducible on another gitea instance. As I only have this private one, I cannot share anything for this.

### goreleaser version

```bash
goreleaser version 1.13.1
commit: b0ffc7af05aa391b766e8e26f5ad5ec37c640d6e
built by: homebrew
goos: darwin
goarch: arm64

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
