### ISSUE TITLE
Docker extra_files fails if path begins with ctx.Config.Dist 

### ISSUE THREAD

**Issue by FGummesson** [goreleaser/goreleaser#3790]
### What happened?

Adding docker.extra_files in directory `dist_files/*` fails with  `invalid docker.files: can't be . or inside dist folder: dist_files`. 

The problem occurs because the docker.extra_files only checks strings.HasPrefix() between `dist` folder and `files_extra` folder. 

### How can we reproduce this?

Create a config file and build a release. The build task will fail.
```yaml
# .goreleaser.yaml

dist: ./dist
dockers:     
    extra_files:
       - dist_files    #Fails
       - dist_files/   #Fails
       - ./dist_files/   #Works
```

### goreleaser version

```bash
$> goreleaser --version
goreleaser version 1.15.1
commit: 7c6bd86b286ee76cfb0a0b4ec17d18d4ee9daeec
built at: 2023-02-02T02:25:36Z
built by: goreleaser
goos: darwin
goarch: amd64
module version: v1.15.1, checksum: h1:GWI+6mpdyEsGU0rEtKvTA7/10L9JZhkHPh9wqXg7kSk=

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
