### ISSUE TITLE
Docker Manifests from Docker Image digests

### ISSUE THREAD

**Issue by nrwiersma** [goreleaser/goreleaser#3810]
### Is your feature request related to a problem? Please describe.

In order to not have multiple tags for every push for each platform with docker manifests, I would like to reuse docker tags for each platform (e.g latest-amd64, latest-arm64). There is a slight risk that the labels will be overridden before the manifest is created, leading to the manifest resolving the wrong digests.

### Describe the solution you'd like

Looking at the docker and manifest code, it seems once docker pushes an image, it stores the digest in the artefact. This digest could be used to in the image name template where it resolvable in the template, based on the docker id, for example:

```
docker
  - id: my-image-arm64
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    image_templates:
      - 'my/image:latest-arm64'

docker_manifests:
  - name_template: 'my/image:latest'
    image_templates:
      - 'my/image@sha256:{{ dockerDigest "my-image-arm64" }}'
  - name_template: 'my/image:{{ .Tag }}'
    image_templates:
      - 'my/image@sha256:{{ dockerDigest "my-image-arm64" }}'
```

### Describe alternatives you've considered

The only way around this is to have specific tags for each push, but this becomes very noisy in the tag list, as the tags themselves are never actually used.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

We often use nightly mode to create and push dev images when a commit is pushed to `main`.
