### ISSUE TITLE
GoReleaser fails with go 1.20

### ISSUE THREAD

**Issue by reuvenharrison** [goreleaser/goreleaser#3829]
### What happened?

GoReleaser failed:
https://github.com/Tufin/oasdiff/actions/runs/4323188375/jobs/7546495923

```
Run goreleaser/goreleaser-action@v4
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.15.2
/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/92768cdb-9a82-4554-94d0-6f01053f7d9a -f /home/runner/work/_temp/7de77643-ee58-4939-9b42-f3b573c8c922
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/1.15.2/x64/goreleaser release --clean
  • starting release...
  • loading config file                              file=.goreleaser.yml
  • loading environment variables
    • using token from "$GITHUB_TOKEN"
  • getting and validating git state
    • building...                                    commit=025e016a8edf39d65cb49fd1262b423b5de0c6cc latest tag=v1.3.7
  • parsing tag
  • setting defaults
  • checking distribution directory
  • loading go mod information
  ⨯ release failed after 0s                  error=failed to get module path: exit status 2: flag provided but not defined: -m
```

### How can we reproduce this?

Run GoReleaser with go 1.20:

```
name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
```

### goreleaser version

```bash
v1.15.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

If I downgrade to go 1.19, it works with no problem.
