### ISSUE TITLE
Deprecation notice about `archives.rlcp`, but I'm not using the rlcp option

### ISSUE THREAD

**Issue by mislav** [goreleaser/goreleaser#3944]
### What happened?

`goreleaser release` prints:
```
  • setting defaults
      • DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
      • DEPRECATED: `archives.rlcp` will be the default soon, check https://goreleaser.com/deprecations#archivesrlcp for more info
...
  • you are using deprecated options, check the output above for details
```

But I am not using rlcp at all in my goreleaser config.

### How can we reproduce this?

```yaml
archives:
  - id: nix
    builds: [macos, linux]
    name_template: >-
      gh_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}linux{{ end }}_
      {{- .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/gh*.1
  - id: windows
    builds: [windows]
    name_template: "gh_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE
```

### goreleaser version

```bash
goreleaser version 1.17.1
commit: 272f18d877a3364381ff228863985d0d479ec518
built by: homebrew
goos: darwin
goarch: arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Re: above checkbox that I had to check in the issue template: `goreleaser check` does show warnings about `rlcp` deprecated property, but those warnings are invalid.
