### ISSUE TITLE
Support Matrix Parameters for Artifactory Uploads

### ISSUE THREAD

**Issue by mbamber** [goreleaser/goreleaser#3951]
### Is your feature request related to a problem? Please describe.

Artifactory supports [matrix parameters](https://jfrog.com/help/r/jfrog-artifactory-documentation/using-properties-in-deployment-and-resolution) to add properties to artifacts upon deployment. It does not appear that these matrix parameters are handled correctly due to goreleaser automatically adding the artifact name to the end of the deployment URL e.g.

With a configuration snippet as follows:
```yaml
artifactories:
  -
    name: default
    exts:
      - deb
    target: my.jfrog.io/artifactory/repo/pool;deb.component=impish
```

The generated upload url (from `goreleaser release --debug`) is `https://my.jfrog.io/artifactory/repo/pool;deb.component=impish/artifact.deb` which results in my artifact being uploaded incorrectly, as the `deb.component` property is set to `impish/artifact.deb` 

### Describe the solution you'd like

I would like to be able to specify matrix parameters as part of the config file:
```yaml
artifactories:
  -
    name: default
    exts:
      - deb
    target: my.jfrog.io/artifactory/repo/pool
    parameters:
      "deb.component": impish
      "another_parameter": somethingElse
```

Note, parameter names must be able to contain a dot (`.`).

### Describe alternatives you've considered

I have tried placing these matrix parameters at various places within the `target` parameter (as the Artifactory docs seem to suggest this should be possible), but none of these seem to work. In any case, it would be much more simple and far more readable for the parameters to be defined separately.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mbamber** [comment]
Once I started looking into how to add this feature, I realised that goreleaser has support for the `custom_artifact_name` parameter which if `false` tells goreleaser not to append the artifact name automatically. By using this option I can actually solve the issue with a config such as:

```yaml
artifactories:
  -
    name: default
    exts:
      - deb
    target: my.jfrog.io/artifactory/repo/pool/{{ .ProjectName }}_{{ .Version }}.deb;deb.component=impish
    custom_artifact_name: true
```

I couldn't see this documented for Artifactory (but it is for HTTP uploads), so I added a small snippet to the docs which I think should be sufficient. See #3953 for this change.

However, if you think there's still mileage in adding matrix parameters separately, I did get a working version which I raised as #3952
