### ISSUE TITLE
Add template for package_name nfpms

### ISSUE THREAD

**Issue by jidckii** [goreleaser/goreleaser#3956]
### Is your feature request related to a problem? Please describe.

I want to have separate package names in the repository for nightly builds in fury.

```yaml
furies:
  - account: tuna
    secret_name: FURY_TOKEN
    ids:
      - tuna
    formats:
      - deb
      - rpm
nfpms:
  - id: tuna
    package_name: tuna.am
    builds:
      - tuna
```

### Describe the solution you'd like

If templates worked in this field, it would be great.
```yaml
nfpms:
  - id: tuna
    package_name: "{{- if .IsNightly -}}tuna.am-nightly{{ else }}tuna.am{{- end -}}"
```

### Describe alternatives you've considered

Right now I have to have 2 different config files for stable and nightly builds.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
