### ISSUE TITLE
HTTP Upload defaulting to GET not PUT

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [goreleaser/goreleaser#3959]
### What happened?

Configured a custom HTTP uploader like so:
```
uploads:
  # has to use underscores so the env var name is valid
  - name: xyzzy
    mode: archive
    ids:
      - debs
    target: 'https://mycompany.jfrog.io/mycompany/repo-name/pool/main/x/xyzzy...'
    username: my-username
```
Got a 404 error when trying to run this. Running with `--debug` showed:
```  • publishing
    • skipped blobs
    • http upload
      • will upload 2 artifacts
      • generated target url: https://mycompany.jfrog.io/...
      • executing request: GET https://mycompany.jfrog.io/... (headers: map[Authorization:[Basic <sekrit>]])
      ⨯ upload: upload failed                        error=unexpected http response status: 404  instance=xyzzy
```

Explicitly specifying `method: PUT` works around the issue

### How can we reproduce this?

I think this should be reproducible starting from any sample configuration

### goreleaser version

```bash
goreleaser version 1.17.2
commit: 6afe717dc9e716bb7e2d893d500fdf3d8b94b872
built at: 2023-04-18T00:10:09Z
built by: goreleaser
goos: linux
goarch: amd64
module version: v1.17.2, checksum: h1:31zA06Sz6/zMNDMvI7l6I4XwFMRoI/WnTMiX8Puu6tE=
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I did a little rummaging in the source code, and I have a suspicion that this is because `upload.Pipe{}` is missing from the list of defaulters here: https://github.com/goreleaser/goreleaser/blob/cbca47dcadc2a4ca3bcb5e9d23585c126231aa8e/pkg/defaults/defaults.go#L57
