### ISSUE TITLE
Support full yaml anchor power by allowing `x-` config fields

### ISSUE THREAD

**Issue by brumhard** [goreleaser/goreleaser#4000]
### Is your feature request related to a problem? Please describe.

I would like to DRY up the goreleaser config so it would be nice to be able to use yaml anchors.

### Describe the solution you'd like

YAML anchors are already somewhat supported, e.g.:

```yaml
nfpms:
  - description: &desc Inspect and dump OCI images
    homepage: &homepage https://github.com/brumhard/{{ .ProjectName }}
    license: &license "MIT"
brews:
  - description: *desc
    homepage: *homepage
    license: *license
```

but it could be even nicer if you could do sth like the following (which is std syntax e.g. used in docker compose https://www.howtogeek.com/devops/how-to-simplify-docker-compose-files-with-yaml-anchors-and-extensions/)

```yaml
x-shared: &shared
  description: sth
  homepage: sth
  license: sth
brews:
  - <<: *shared
nfpms:
  - <<: *shared
```

I think the only thing that would be necessary for that is allowing some more keys (e.g. all keys prefixed with `x-`) in the config. Currently it fails with:

```
 ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 1: field x-test not found in type config.Project
```

### Describe alternatives you've considered

Repeating myself

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
