### ISSUE TITLE
Announce telegram failed (Bad Request: can't parse entities: Character '.' )

### ISSUE THREAD

**Issue by jidckii** [goreleaser/goreleaser#4021]
### What happened?

I'm trying to send an announce to telegram, but I'm getting an error.
This is due to the fact that in the text there are not escaped characters that I cannot escape, because got them from variables.

```sh
    • telegram
      • posting: '🚀 New release 0.9.0-rc4'
  • skipped twitter
  • skipped webhook
  ⨯ announce failed after 0s                 error=failed to announce release: 1 error occurred:
	* telegram: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
```

### How can we reproduce this?

I have a simgle config

```yaml
announce:
  telegram:
    enabled: true
    chat_id: "{{ .Env.TELEGRAM_CHAT_ID }}"
    message_template: |-
      🚀 New release  {{.ProjectName}} {{.Version}}
```
also you can test with `curl`
```sh
curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "1234", "text": "🚀 New release 0.9.0-rc4", "disable_notification": false, "parse_mode": "MarkdownV2"}' \
     https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\\'"}
```

If escaped dot '.' this OK

```

curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "1234", "text": "🚀 New release 0\.9\.0-rc4, "disable_notification": false, "parse_mode": "MarkdownV2"}' \
     https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage
{"ok":true,"result":{"message_id":812,"from":{"id":1234,"is_bot":true,"first_name":"qwe qwe \ud83e\udd4b","username":"qwe_Bot"},"chat":{"id":1234,"first_name":"qwe","last_name":"qwe","username":"qwe","type":"private"},"date":1684417056,"text":"\ud83d\ude80 New release 0.9.0-rc4,"}}
```

### goreleaser version

```bash
1.18.2-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Maybe also add `parse_mode` as a option in telegram config 

```yaml
announce:
  telegram:
    enabled: true
    parse_mode: MarkdownV2 | HTML
```
