### ISSUE TITLE
"prebuilt:" discards the path information

### ISSUE THREAD

**Issue by edigaryev** [goreleaser/goreleaser#4143]
### What happened?

When using `prebuilt:`, it discards the path information and only seems to preserve the `filepath.Base()` as an artifact's name.

I think this is a bug, because:

1. The standard Golang builder has a proper behavior: it preserves the path to a binary.
2. Not preserving the path makes `strip_parent_binary_folder:` in `archive:` completely useless.

### How can we reproduce this?

`.goreleaser.yml` with `prebuilt:` does not preserve the path information:

```yaml
project_name: tart

before:
  hooks:
    - mkdir -p tart.app/Contents/MacOS
    - touch tart.app/Contents/MacOS/tart

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: tart.app/Contents/MacOS/tart

archives:
  - name_template: "{{ .ProjectName }}"
```

```
% tar tvf dist/tart.tar.gz 
-rwxr-xr-x  0 edi    staff       0 Jun 26 17:35 tart
```

`.goreleaser.yml` with standard Golang builder preserves the path information:

```yaml
project_name: tart

builds:
  - goos:
      - darwin
    goarch:
      - arm64
    binary: tart.app/Contents/MacOS/tart

archives:
  - name_template: "{{ .ProjectName }}"
```

```
% tar tvf dist/tart.tar.gz                   
-rwxr-xr-x  0 edi    staff 59973890 Jun 26 17:37 tart.app/Contents/MacOS/tart
```

### goreleaser version

```bash
Running directly from `main` branch.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
sounds like a bug indeed, thanks for reporting! will investigate

**Comment by caarlos0** [comment]
```yaml
project_name: tart

before:
  hooks:
    - mkdir -p tart.app/Contents/MacOS
    - touch tart.app/Contents/MacOS/tart

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    binary: tart.app/Contents/MacOS/tart
    prebuilt:
      path: tart.app/Contents/MacOS/tart

archives:
  - name_template: "{{ .ProjectName }}"
```

this should work.

You also need to set the `binary` property. Path is the path "outside" goreleaser's context, and you can set `binary` to the final name you want it to be, including the subfolders et al.

Hope this helps.

PS: Will improve the docs too.
