### ISSUE TITLE
Allow configuration of "make latest" for GitHub releases

### ISSUE THREAD

**Issue by hiddeco** [goreleaser/goreleaser#4159]
### Is your feature request related to a problem? Please describe.

At present, this is automatically set to `true` due to GitHub's [default API behavior around `make_latest`](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release), and goreleaser not [providing any value](https://github.com/goreleaser/goreleaser/blob/c57cdab0c6f30be07979669a465a17062345c3ef/internal/client/github.go#L346-L352).

This can be problematic when you are maintaining a series of minor release ranges, as any time a release is made it is marked as "latest" while this may not actually be true in terms of SemVer ordering.

### Describe the solution you'd like

```yaml
# .goreleaser.yaml
release:
  # If set to false, will not mark the release as "latest".
  # Not compatible with "prerelease". Default is true.
  latest: true|false|legacy
```

### Describe alternatives you've considered

One way around this is to draft the release before publishing, but this takes the pleasure around fully automated releases away.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
