### ISSUE TITLE
Setting "gitea_urls" results in failed scm release (invalid url)

### ISSUE THREAD

**Issue by seriousm4x** [goreleaser/goreleaser#4160]
### What happened?

I'm trying to use goreleaser with a self hosted gitea instance. When I specify `gitea_urls` in my yaml, the scm release will fail with `error=scm releases: failed to publish artifacts: invalid URL:` and then no url.

Goreleaser should use the url I specified, but it's empty.

### How can we reproduce this?

This is the yml I use:
```yml
release:
    prerelease: auto
before:
    hooks:
        - go mod tidy
builds:
    - binary: publish-podcasts
      env:
          - CGO_ENABLED=0
      ldflags:
          - -s -w
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
archives:
    - format: zip
checksum:
    name_template: "checksums.txt"
snapshot:
    name_template: "{{ .Version }}"
changelog:
    sort: asc
gitea_urls:
    api: http://our.internal.gitea.media/api/v1
    download: http://our.internal.gitea.media
```

And this is the output I get:
```bash
~/r/publish-podcasts ❯❯❯ GORELEASER_FORCE_TOKEN=gitea GITEA_TOKEN=mytoken goreleaser release --clean
  • starting release...
  • could not find a config file, using defaults...
  • loading environment variables
    • using token from "$GITEA_TOKEN"
  • getting and validating git state
    • couldn't find any tags before "1.0.0"
    • building...                                    commit=99034b0e5911813187e0d6d58c0c0c5758c5d093 latest tag=1.0.0
  • parsing tag
  • setting defaults
  • checking distribution directory
    • cleaning dist
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/publish-podcasts_linux_386/publish-podcasts
    • building                                       binary=dist/publish-podcasts_linux_arm64/publish-podcasts
    • building                                       binary=dist/publish-podcasts_windows_arm64/publish-podcasts.exe
    • building                                       binary=dist/publish-podcasts_darwin_amd64_v1/publish-podcasts
    • building                                       binary=dist/publish-podcasts_windows_386/publish-podcasts.exe
    • building                                       binary=dist/publish-podcasts_windows_amd64_v1/publish-podcasts.exe
    • building                                       binary=dist/publish-podcasts_linux_amd64_v1/publish-podcasts
    • building                                       binary=dist/publish-podcasts_darwin_arm64/publish-podcasts
    • took: 1s
  • generating changelog
    • writing                                        changelog=dist/CHANGELOG.md
  • archives
    • creating                                       archive=dist/publish-podcasts_1.0.0_windows_arm64.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_linux_amd64.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_linux_386.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_windows_386.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_darwin_amd64.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_darwin_arm64.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_linux_arm64.tar.gz
    • creating                                       archive=dist/publish-podcasts_1.0.0_windows_amd64.tar.gz
    • took: 1s
  • calculating checksums
  • publishing
    • scm releases
  ⨯ release failed after 1s                  error=scm releases: failed to publish artifacts: invalid URL:
```

Seems like the url is not read correctly. I've tried different urls for testing as well, but none show up.

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.18.1
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.20.4
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Same error happens on multiple platforms. Tested on windows, arch linux, goreleaser docker container (via drone ci). All with the latest release.

**Comment by caarlos0** [comment]
with the given url in the example it shouldn't give that error... please make sure that in your actual config file you don't have any typos in the URL...

**Comment by seriousm4x** [comment]
> with the given url in the example it shouldn't give that error... please make sure that in your actual config file you don't have any typos in the URL...

I just censored it because I don't wanna share our companys internal domain. It's still very similar. 4 blocks and ends with .media
I've checked so many times for typos now.

I just tried it with
```yml
gitea_urls:
    api: http://test.com/api/v1
    download: http://test.com
    skip_tls_verify: true
```
and it throws the same error.
