### ISSUE TITLE
Unable to use `cosign blob-sign --key env://COSIGN_KEY`

### ISSUE THREAD

**Issue by pjbgf** [goreleaser/goreleaser#4221]
### What happened?

`cosign` supports the use of loading keys directly from environment variables with the syntax:

`cosign blob-sign --key env://COSIGN_KEY`

When trying to use that syntax with goreleaser, it fails with:

```sh
  ⨯ release failed after 1s                  error=sign: cosign failed: exit status 1: Error: unknown flag: --key env://COSIGN_KEY
```

### How can we reproduce this?

Have this section on the `.goreleaser.yml`:

```yaml
signs:
  - cmd: cosign
    args:
      - sign-blob
      - '--key env://COSIGN_KEY'
      - '--yes'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true
```

### goreleaser version

```bash
On my pipelines, `goreleaser/goreleaser-action@v4` is using:
`https://github.com/goreleaser/goreleaser/releases/download/v1.19.2`.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] #4231

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
the signing command only uses declared environment variables, so you can probably make it work with:

```yaml
signs:
  - cmd: cosign
    args:
      - sign-blob
      - '--key env://COSIGN_KEY'
      - '--yes'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true
    env:
      - "COSIGN_KEY={{ .Env.COSIGN_KEY }}"
```

**Comment by caarlos0** [comment]
Easy way to test it:

```yaml
# .goreleaser.yaml
env:
  - "COSIGN_KEY={{ .Env.COSIGN_KEY }}"

signs:
  - cmd: sh
    args:
      - -c
      - "env | grep -i COSIGN"
    artifacts: checksum
    output: true
```

cmd: 

```bash
COSIGN_KEY=foo.key goreleaser release --snapshot --clean
```

**Comment by caarlos0** [comment]
_(deleted my previous comments because they were wrong)_

---

OK, this works here as expected:

```yaml
project_name: example
builds:
  - env: [CGO_ENABLED=0]
    targets: [go_first_class]

signs:
  - cmd: cosign
    args:
      - sign-blob
      - "--key env://COSIGN_KEY"
      - "--yes"
      - "--output-signature=${signature}"
      - "${artifact}"

```

judging by the error, you might be using an old version of cosign?

it says that the flag `--key` doesn't exist... that error comes from `cosign` itself, not from goreleaser.

all that said, this does not look like a bug.

closing, but feel free to comment otherwise
