### ISSUE TITLE
docker build failed: exit status 1: ERROR: use `docker --context=default buildx` to switch to context "default"

### ISSUE THREAD

**Issue by koddr** [goreleaser/goreleaser#4392]
### What happened?

When I run `goreleaser release`, the process reaches the section with Docker image creation and an error appears:

```console
docker build failed: failed to build gowebly/gowebly:latest-arm64: exit status 1: ERROR: use `docker --context=default buildx` to switch to context "default"
```

My `.goreleaser.yml`:

```yaml
...

dockers:
  -
    id: '{{ .ProjectName }}_linux_amd64' # For GNU/Linux x86_64
    ids: [ default ]
    use: buildx
    skip_push: auto
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest-linux-amd64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-linux-amd64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=linux/amd64'
    push_flags:
      - '--tls-verify=false'
  -
    id: '{{ .ProjectName }}_linux_arm64' # For GNU/Linux ARM
    ids: [ default ]
    use: buildx
    skip_push: auto
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest-linux-arm64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-linux-arm64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=linux/arm64'
    push_flags:
      - '--tls-verify=false'
  -
    id: '{{ .ProjectName }}_darwin_amd64' # For Apple macOS x86_64
    ids: [ default ]
    use: buildx
    skip_push: auto
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest-darwin-amd64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-darwin-amd64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=darwin/amd64'
    push_flags:
      - '--tls-verify=false'
  -
    id: '{{ .ProjectName }}_darwin_arm64' # For Apple macOS ARM
    ids: [ default ]
    use: buildx
    skip_push: auto
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest-darwin-arm64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-darwin-arm64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=darwin/arm64'
    push_flags:
      - '--tls-verify=false'

docker_manifests:
  -
    name_template: 'gowebly/{{ .ProjectName }}:latest'
    skip_push: auto
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest-linux-amd64'
      - 'gowebly/{{ .ProjectName }}:latest-linux-arm64'
      - 'gowebly/{{ .ProjectName }}:latest-darwin-amd64'
      - 'gowebly/{{ .ProjectName }}:latest-darwin-arm64'
  -
    name_template: 'gowebly/{{ .ProjectName }}:{{ .Tag }}'
    skip_push: auto
    image_templates:
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-linux-amd64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-linux-arm64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-darwin-amd64'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}-darwin-arm64'

...
```

### How can we reproduce this?

1. Clone project https://github.com/gowebly/gowebly
2. Run `goreleaser release`
3. See error

### goreleaser version

```bash
GitVersion:    1.21.2
GitCommit:     26fed97a0defe4e73e3094cb903225d5445e5f0d
GitTreeState:  false
BuildDate:     2023-09-26T11:20:15Z
BuiltBy:       goreleaser
GoVersion:     go1.21.1
Compiler:      gc
ModuleSum:     h1:dgYtIS7aZlQuRMUMLCjDCOs4lWss85Oh60RDSO0rbWU=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

```console
$ docker-buildx version

github.com/docker/buildx v0.11.2 9872040b6626fb7d87ef7296fd5b832e8cc2ad17
```

**Comment by caarlos0** [comment]
could you paste the output of `docker buildx ls`?

**Comment by koddr** [comment]
Hmmm... 

```console
ERROR: open /Users/user/.docker/buildx/activity/desktop-linux: permission denied
```

**Comment by tcurdt** [comment]
I just ran into the same/similar error:

```
goreleaser release --skip=publish --skip=validate --clean
...
release failed after 1s
error=docker build failed: failed to build tcurdt/foo:latest:
exit status 1:
ERROR: use `docker --context=default buildx` to switch to context "default"
```

This is the config:

```
dockers:
  - image_templates:
    - "tcurdt/{{ .ProjectName }}:latest"
    - "tcurdt/{{ .ProjectName }}:v{{ .Version }}"
    - "tcurdt/{{ .ProjectName }}:v{{ .Major }}"
    build_flag_templates:
    - "--label=sha={{.FullCommit}}"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--pull"
    - "--platform=linux/amd64"
    use: buildx
```

But I my `buildx ls` does work

```
$ docker buildx ls
NAME/NODE       DRIVER/ENDPOINT STATUS  BUILDKIT             PLATFORMS
default         docker                                       
  default       default         running v0.11.6+616c3f613b54 linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
desktop-linux * docker                                       
  desktop-linux desktop-linux   running v0.11.6+616c3f613b54 linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```
