### ISSUE TITLE
build.hooks template has no entry key for "Amd64"

### ISSUE THREAD

**Issue by coolaj86** [goreleaser/goreleaser#4399]
### What happened?

Some of the docs show that `{{ .Amd64 }}` is available:
- https://goreleaser.com/customization/templates/#artifacts

Other of the docs do not:
- https://goreleaser.com/customization/builds/

Regardless, it's not supported in v1.21.2:

```text
⨯ release failed after 0s                  error=post hook failed: template: failed to apply "./.goreleaser/build.sh \"{{ .Os }}\" \"{{ .Arch }}\" \"{{ .ProjectName }}\" \"{{ .Amd64 }}\"": map has no entry for key "Amd64"
```

### How can we reproduce this?

```yml
builds:
    # The Zig executable name (specified in build.zig)
  - binary: hello-zig
    # We should be able to use this, no go-dummy, but it seems broken right now
    #builder: prebuilt
    gobinary: ./.goreleaser/go-dummy
    main: ./.goreleaser/dummy.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    goamd64:
      - v1

    hooks:
      # This is called for every architecture.
      # eg: ./build.sh linux_amd64 csv2json
      post: ./.goreleaser/build.sh "{{ .Os }}" "{{ .Arch }}" "{{ .ProjectName }}" "{{ .Arm }}"
```

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.21.2
GitCommit:     26fed97a0defe4e73e3094cb903225d5445e5f0d
GitTreeState:  false
BuildDate:     2023-09-26T11:20:15Z
BuiltBy:       goreleaser
GoVersion:     go1.21.1
Compiler:      gc
ModuleSum:     h1:dgYtIS7aZlQuRMUMLCjDCOs4lWss85Oh60RDSO0rbWU=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
