### ISSUE TITLE
single-target cannot find build

### ISSUE THREAD

**Issue by till** [goreleaser/goreleaser#4437]
We got this error with `1.22.1`:

```
 /opt/hostedtoolcache/goreleaser-action/1.22.1/x64/goreleaser build --snapshot --rm-dist --single-target
  • starting build...
  • loading                                          path=.goreleaser.yaml
  • DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
  • building only for linux/amd64                    reason=single target is enabled
  ⨯ build failed after 0s                    error=no builds matching --single-target linux/amd64
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.22.1/x64/goreleaser' failed with exit code 1
```

_Originally posted by @till in https://github.com/goreleaser/goreleaser/issues/4411#issuecomment-1821034379_

My goreleaser config is very simple:

```yaml
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      -  -s -w -X main.Version={{.Version}}
    main: ./cmd/foo
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "darwin" }}Darwin
      {{- else if eq .Arch "linux" }}Linux
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files: # don't add README/LICENSE files
      - none*
```

There's more, but it's docker and docker manifests.

My guess is, that the `--single-target` cannot match because we are not explicitly defining amd64, arm64 (aka `goarch`), etc. in the `builds:`?

At least, that's my guess. We downgraded the build on that one project for the time being. We usually just build `amd64` and `--single-target` works there, but this project _needs_ everything.
