### ISSUE TITLE
monorepo config should evaluate go templates

### ISSUE THREAD

**Issue by librucha** [goreleaser/goreleaser#4440]
### Is your feature request related to a problem? Please describe.

in Pro version monorepo featue config is not evaluating Go templates and raw text have to be used.
e.g.:
```yaml
monorepo:
  tag_prefix: "component_"
  dir: "component"
```

I'm very often copying goreleaser config to new subdirectories and expecting only change project_name field.

### Describe the solution you'd like

```yaml
monorepo:
  tag_prefix: "{{ .ProjectName }}_"
  dir: "{{ .ProjectName }}"
```

### Describe alternatives you've considered

using raw strings but it is not prefect :)

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
