### ISSUE TITLE
Redirections and pipes don't work in before hooks

### ISSUE THREAD

**Issue by brianstrauch** [goreleaser/goreleaser#4465]
### What happened?

My pipeline needs to write to a file in a before hook, but the "|" and ">" characters are not supported

### How can we reproduce this?

Including the following in any goreleaser file will print "test" to stdout and fail to create test.txt
```
before:
  hooks:
    - cmd: echo "test" > test.txt
      output: true
    - cmd: ls
      output: true
```

### goreleaser version

```bash
GitVersion:    1.22.1-pro
GitCommit:     cd4e8e12ca404cb7ccc21ddac4f8455b54e60366
GitTreeState:  clean
BuildDate:     2023-11-08T12:12:16Z
BuiltBy:       goreleaser
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brianstrauch** [comment]
Fixed by using the suggestion here: https://goreleaser.com/customization/hooks/#complex-commands
```
before:
  hooks:
    - cmd: sh -c 'echo "test" > test.txt'
      output: true
    - cmd: ls
      output: true
```
