### ISSUE TITLE
Unable to run GoReleaser locally to test changes

### ISSUE THREAD

**Issue by jalseth** [goreleaser/goreleaser#4475]
### What happened?

I want to verify my changes to the GoReleaser config locally before the next release. However,  `goreleaser` fails to run. 

```sh
$ goreleaser release --auto-snapshot --skip-docker --skip-publish --clean
  • starting release...
  • loading                                          path=.goreleaser.yml
  • DEPRECATED: --skip-publish was deprecated in favor of --skip=publish, check https://goreleaser.com/deprecations#-skip for more details
  • DEPRECATED: --skip-docker was deprecated in favor of --skip=docker, check https://goreleaser.com/deprecations#-skip for more details
  • skipping announce, docker and publish...
  • loading environment variables
  • getting and validating git state
    • git state                                      commit=8a6e121535b53a042ac121a4ea10a98f68f8a95d branch=master current_tag=v0.47.0 previous_tag=v0.46.0 dirty=false
  ⨯ release failed after 0s                  error=git tag v0.47.0 was not made against commit 8a6e121535b53a042ac121a4ea10a98f68f8a95d
```

This worked for me previously in https://github.com/open-policy-agent/conftest/pull/842. I have reviewed the output from `goreleaser release --help` but don't see anything that would help me.

### How can we reproduce this?

Clone https://github.com/open-policy-agent/conftest

Run `goreleaser release --auto-snapshot --skip-docker --skip-publish --clean`

### goreleaser version

```bash
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.22.1
GitCommit:     52d976beaea9ba8a5b0f09f90f22135b468c33c2
GitTreeState:  dirty
BuildDate:     2023-11-08T23:40:43
BuiltBy:       homebrew
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you might need to force a snapshot with `--snapshot`

**Comment by jalseth** [comment]
That was the issue, thanks. It is a bit counter-intuitive that there are two options that essentially perform the same operation.

**Comment by caarlos0** [comment]
It's not the same, auto snapshot sets snapshot automatically if the repo is dirty, and snapshot sets it regardless of anything else.

**Comment by petr-stupka** [comment]
See example here: https://github.com/goreleaser/example-auto-snapshot/blob/main/.github/workflows/releaser.yml

```yaml
...
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
