### ISSUE TITLE
Add support for storing many packages in the same AUR git repo

### ISSUE THREAD

**Issue by bartekpacia** [goreleaser/goreleaser#4482]
### Is your feature request related to a problem? Please describe.

I'm a mainly a macOS user, but plan on using ArchLinux soon. That's why I'm currently in process of creating [my private Arch User Repository](https://github.com/bartekpacia/aur) (mirroring my [private Homebrew Tap](https://github.com/bartekpacia/homebrew-tools)). However I'm having a problem with storing many packages in the same repo.

### Describe the solution you'd like

Let's say I have two programs: `fhome` (the client for my smart home) and `fhomed` (the server for my smart home).

Here's how I define `brews` in my `.goreleaser.yaml`:

```yaml
brews:
  - name: fhome
    ids:
      - fhome
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    license: MIT
  - name: fhomed
    # ... doesn't matter
```

The above creates [a **separate** formula file](https://github.com/bartekpacia/homebrew-tools/blob/master/Formula/fhome.rb), so I can store other formulas in [my `homebrew-tools` repo](https://github.com/bartekpacia/homebrew-tools/blob/master/Formula).

I wanted to do the same for my `aur`s - that is, have many directories (1 for every package of mine), and a single `PKGBUILD`s inside each of those directories. But I am not able to achieve this – the following `aur` config creates `PKGBUILD` and `.SRCINFO` in the root of my repository:

```yaml
aurs:
  - name: fhome-bin
    ids:
      - fhome
    homepage: https://github.com/bartekpacia/fhome
    description: Interact with smart home devices connected to F&Home
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: git@github.com:bartekpacia/aur.git

    package: |-
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 fhome "${pkgdir}/usr/bin/fhome"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/mybin/LICENSE"
```

And here comes my feature requst:

I would like to be able to specify the directory in which the `PKGBUILD` and `.SRCINFO` files will be created. Idea:

```yaml
...
private_key: '{{ .Env.AUR_SSH_KEY }}'
git_url: git@github.com:bartekpacia/aur.git
directory: fhome # <-- this would let me store many PKGBUILDs in a single repo
...
```

### Describe alternatives you've considered

None

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Thanks for this awesome program!
