### ISSUE TITLE
homebrew doesn't work with nightly and without release?

### ISSUE THREAD

**Issue by jidckii** [goreleaser/goreleaser#4487]
### What happened?

Hello.
I'm trying to add publishing to homebrew, but it doesn't seem to work unless release is enabled and it's not a nightly build. When launched, the program is built and published to S3, I skip docker and others, but it seems that brews needs a full release. It's not clear how to debug this.

### How can we reproduce this?

```
brews:
  - name: tuna
    alternative_names:
      - "tuna@{{ .Version }}"
    repository:
      owner: yuccastream
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://tuna.am
    description: Tuna - software for create HTTP/TCP tunnels to local network
    license: Copyright YuccaStream Team (https://tuna.am/tos.html)
    test: |
      system "#{bin}/tuna version"
    ids:
      - tuna
    url_template: "https://releases.tuna.am/{{- if .IsNightly }}tuna/nightly/{{.Version}}{{- else if .Prerelease }}tuna/beta/{{.Tag}}{{ else }}tuna/{{.Tag}}{{- end }}/{{.ArtifactName}}"
    extra_install: |-
      bash_completion.install "completions/tuna.bash" => "tuna"
      zsh_completion.install "completions/tuna.zsh" => "_tuna"
      fish_completion.install "completions/tuna.fish"

release:
  disable: true
```

`goreleaser release --nightly --clean  --skip=after,docker,fury`

### goreleaser version

```bash
$ goreleaser --version

GitVersion:    1.22.1-pro
GitCommit:     cd4e8e12ca404cb7ccc21ddac4f8455b54e60366
GitTreeState:  clean
BuildDate:     2023-11-08T12:12:16Z
BuiltBy:       goreleaser
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
