### ISSUE TITLE
Certificate pem file is not generated when a COSIGN PWD is provided

### ISSUE THREAD

**Issue by xavidop** [goreleaser/goreleaser#4503]
### What happened?

when you specify the cosign password:
```
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    # stdin: '{{ .Env.COSIGN_PWD }}'
    args:
      - sign-blob
      - "--key=cosign.key"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes
```
the certificate in this case checksum.txt.pem is not generated

### How can we reproduce this?

running goreleaser with the config above.

Here you have an execution: https://github.com/xavidop/dialogflow-cx-cli/actions/runs/7329677702/job/19959654472

### goreleaser version

```bash
latest version
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
