### ISSUE TITLE
401 when releasing on gitlab

### ISSUE THREAD

**Issue by night-gold** [goreleaser/goreleaser#4509]
### What happened?

While releasing my project I get this 401 error :

>  ⨯ release failed after 32s                 error=scm releases: failed to publish artifacts: GET https://gitlab.com/api/v4/projects/gitlab.com/USERNAME/PROJECTNAME/releases/0.0.12: 401 {message: 401 Unauthorized}

### How can we reproduce this?

I tried using this gitlab-ci.yml
```
stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GITLAB_TOKEN: $GITLAB_TOKEN
  script:
    - goreleaser release --clean
```

And this .goreleaser.yaml:
```
project_name: PROJECT-NAME
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```

### goreleaser version

```bash
v1.23.0
docker image: goreleaser/goreleaser:sha256-7ab42c63268ba14f272f8a7ae4ac3d9aa3e6f4b7ea1dde866a5c0c68e74f2627
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I've been testing multiple thing and found out that the url it's trying to access that returns a 401 is in fact a 404.

When trying to access this url you get nothing, you have to access the url using the project id:
- from: https://gitlab.com/api/v4/projects/gitlab.com/USERNAME/PROJECTNAME > 404
- to: https://gitlab.com/api/v4/projects/gitlab.com/PROJECT_ID > 202

I tried a lot of different things and that is the only lead I have that would explain why it's not working.
