### ISSUE TITLE
Why do arm64 artifacts end up with a `default.` prefix?

### ISSUE THREAD

**Issue by zeke** [goreleaser/goreleaser#4513]
### What happened?

Some of the artifacts that get published with our GitHub releases inexplicably now have a `default.` prefix, while others don't:

```
cog_darwin_x86_64
cog_linux_x86_64
default.cog_darwin_arm64
default.cog_linux_arm64
```

Ideally that prefix would not exist, and the filenames would be:

```
cog_darwin_x86_64
cog_linux_x86_64
cog_darwin_arm64
cog_linux_arm64
```

### How can we reproduce this?

The (probably) relevant bits of our `.goreleaser.yaml` file is this:

```yaml
builds:
  - binary: cog
    id: cog

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}
      {{end}}
```

The full `.goreleaser.yaml` file is [here](https://github.com/replicate/cog/blob/b28dd14e90a6a5d84b372dbd5cd51dadccfd9bbc/.goreleaser.yaml)

Here's how I am doing a dry run locally:

```
git clone http://github.com/replicate/cog
cd cog
brew install goreleaser/tap/goreleaser
goreleaser release --snapshot --skip=publish --clean
```

When I view the artifact data for on of the arm64 binaries:

```
cat dist/artifacts.json | jq ".[5]"
```

I can see that `extra.ID` is `default` but this is confusing because the `archives.name_template` makes no mention of ID, and the `build.id` is set to `cog`

```json
{
  "name": "cog_linux_arm64 ",
  "path": "dist/cog_linux_arm64/cog",
  "goos": "linux",
  "goarch": "arm64",
  "internal_type": 2,
  "type": "Binary",
  "extra": {
    "Binary": "cog",
    "Checksum": "sha256:d557e9595251d587c29e749ae6afaef169db29a730f33886d48b489f170f4fd7",
    "Format": "binary",
    "ID": "default",
    "Replaces": null
  }
}
```

I am not sure what process this metadata goes through to become a named artifact on a GitHub release, but hopefully this helps illustrate the issue.

### goreleaser version

Testing locally with the latest from `brew install goreleaser/tap/goreleaser`

On GitHub, we're using the goreleaser-action@v4 with the latest version of goreleaser. See https://github.com/replicate/cog/blob/b28dd14e90a6a5d84b372dbd5cd51dadccfd9bbc/.github/workflows/ci.yaml#L124-L127

```yml
- uses: goreleaser/goreleaser-action@v4
  with:
    version: latest
    args: release --clean
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Thank you @caarlos0 for making this awesome project. We use it at @replicate to automate releases of a lot of our open-source software. 🙏🏼
