### ISSUE TITLE
gitlab: publish a brew formula throws an 400: "You can only create or edit files when you are on a branch" when creating brew formula  

### ISSUE THREAD

**Issue by metalmolly** [goreleaser/goreleaser#4543]
### What happened?

While running our GitLab CI/CD tag (GitLab Enterprise Edition v16.4.5) pipeline it executes the command: `goreleaser release --clean`. But the publishing step for the homebrew tap formula always fails with the following error:

`⨯ error creating brew formula file             fileName=Formula/formula.rb branch=brew-releases/0.1.0 projectID=xxx/tooling/homebrew-xxx statusCode=400 error=POST https://gitlab.test.de/api/v4/projects/xxx/tooling/homebrew-repository/repository/files/Formula/formula.rb: 400 {message: You can only create or edit files when you are on a branch}`

### How can we reproduce this?

Use the goreleaser configuration below and run the command `goreleaser release --clean`
```
brews:
  - name: formula
    # Repository to push the generated files to.
    repository:
      owner: xxx/tooling
      name: homebrew-repository
      branch: brew-releases/{{ .Version }}
    folder: Formula
    commit_author:
      name: user
      email: "user@email.com"
    homepage: "{{ .GitURL }}"
    description: "Support tool"
    install: |
      bin.install "xxx"
    test: |
      system "#{bin}/xxx --version"

```

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.23.0
GitCommit:     3ec68fbf8c3a1b16ca0f69aeccfb93765685b643
GitTreeState:  dirty
BuildDate:     2023-12-26T14:29:46
BuiltBy:       homebrew
GoVersion:     go1.21.5
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

According to GitLab REST API, the start_branch attribute is optional but when not set it throws the above mentioned error.
