### ISSUE TITLE
Adding a double quote into a Slack notification string results in a template error

### ISSUE THREAD

**Issue by jamietanna** [goreleaser/goreleaser#4556]
### What happened?

When using Slack notifications via `blocks` or `attachments`, a template error is seen when using `"` in the message, for instance when `{{ envOrDefault "USER" "" }}`

We receive the following error:

```
slack blocks: failed to evaluate template: template: failed to apply "[{\"text\":{\"text\":\"The current user is {{ envOrDefault \\\"USER\\\" \\\"\\\" }}\",\"type\":\"plain_text\"},\"type\":\"header\"}]": unexpected "\\" in operand
```

This occurs for both single quoted strings and double quoted strings containing the values:

```yaml
    blocks:
      - type: header
        text:
          type: plain_text
          text: 'The current user is {{ envOrDefault "USER" "" }}'
    attachments:
        -
          title: Release artifacts
          color: '#2eb886'
            text: |
              The current user is {{ envOrDefault "USER" "" }}
```

### How can we reproduce this?

I've raised a draft PR at #4555 which introduces the test code to reproduce.

### goreleaser version

```bash
Reproducible on HEAD, commit d15dab3a797e744fac0d0577fc2e3c4ab7a2b758
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

https://github.com/goreleaser/goreleaser/pull/4555 is the tests to show the issue
