### ISSUE TITLE
Prebuilt binary builder  doesn't work for both macOS `arm64` and `amd64`

### ISSUE THREAD

**Issue by fkorotkov** [goreleaser/goreleaser#4572]
### What happened?

I'm trying to use a prebuilt feature to release both `arm64` and `amd64` versions of a Rust program. I'm using the following config:

```yaml
project_name: softnet

builds:
  - id: softnet
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    prebuilt:
      path: 'target/{{- if eq .Arch "arm64" }}aarch64{{- else }}x86_64{{ end }}-apple-darwin/release-with-debug/softnet'

archives:
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: softnet
    repository:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/softnet
    description: Software networking with isolation for Tart
    skip_upload: auto
```

### How can we reproduce this?

You can go to https://github.com/cirruslabs/softnet/pull/30 and checkout `goreleaser-bug` branch. Then install `rustup` if you already don't have it:

```console
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
```

Build two binaries:

```console
rustup target add x86_64-apple-darwin
cargo build --target aarch64-apple-darwin --target x86_64-apple-darwin
```

And finally dry-run Goreleaser Pro:

```console
goreleaser release --skip=publish --snapshot
```

After which `dist` folder will only contain `arm64` build.

### goreleaser version

```bash
GitVersion:    1.23.0-pro
GitCommit:     3973205d96767d1f1b0d378584a75697cad58444
GitTreeState:  clean
BuildDate:     2023-12-26T15:04:19Z
BuiltBy:       goreleaser
GoVersion:     go1.21.5
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I've also tried to split builds but with no luck:

```yaml
project_name: softnet

builds:
  - id: softnet-arm64
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: "target/aarch64-apple-darwin/release-with-debug/softnet"
  - id: softnet-x86
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - amd64
    prebuilt:
      path: "target/x86_64-apple-darwin/release-with-debug/softnet"

archives:
  - id: regular-arm64
    builds:
      - softnet-arm64
    name_template: "{{ .ProjectName }}-{{ .Arch }}"
  - id: regular-x86
    builds:
      - softnet-x86
    name_template: "{{ .ProjectName }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: softnet
    ids:
      - regular-arm64
      - regular-x86
    repository:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/softnet
    description: Software networking with isolation for Tart
    skip_upload: auto
```
