### ISSUE TITLE
Conditional build flags or per-build hooks.

### ISSUE THREAD

**Issue by evilsocket** [goreleaser/goreleaser#459]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

For a [project of mine](https://github.com/evilsocket/arc), I need to override the `CC` variable with `arm-linux-gnueabi-gcc` but *only* when `GOARCH ' is `arm` (otherwise it'd override the C compiler for every build with the ARM one, causing chaos :D), from the documentation this does not look possible.

So I thought to use a pre hook script, which checks what value GOARCH has and override CC conditionally ... but unfortunately, the pre hook is executed only once, globally, not per build as I'd need.

### Environment

Please paste the output of:

* `go version go1.8.3 linux/amd64`
* `Linux shiva 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by caarlos0** [comment]
Hi, I think you can hack around this with multiple builds:

```yaml
builds:
- main: foo.go
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=1
- main: foo.go
  goos:
  - linux
  goarch:
  - arm
  env:
  - CGO_ENABLED=1
  - CC=arm-linux-gnueabi-gcc
```

let me know how that work out for you :)

**Comment by evilsocket** [comment]
wow I did not think about that :D will check it asap and let you know :D

**Comment by evilsocket** [comment]
btw, even if this hack works, do we agree that the point of using a tool like goreleaser is exactly to avoid such type of redundancy, don't we? :P

Also, think about conditional ldflags per OS ( on windows you might want to link against some libraries which do not exist on other operating systems ) ... I believe you'll need to implement it at some point ;)

**Comment by caarlos0** [comment]
indeed, but probably only on v2.

I'm trying to make it stable enough to be a solid 1.0.0 at some point :) 

For v2 I can change the config format and etc more freely then :P

**Comment by caarlos0** [comment]
also I'm not sure how to make this conditional without repeating things... at some point you'll have to say which variables are for which builds...

the current way allows more robust configurations I think...

**Comment by evilsocket** [comment]
Make it hierarchical, as it should be, like (just brainstorming here):

```yaml
builds:
  - global
  - flags
  - here
  arm:
    - specific flags
  windows:
    - also works for os
```

m2c

**Comment by caarlos0** [comment]
yeah, makes sense... well, for v2 I'll think about it =D

**Comment by caarlos0** [comment]
BTW: did my suggestion work on your case?

**Comment by evilsocket** [comment]
testing it right now, will update asap

**Comment by evilsocket** [comment]
like a charm, if we ever meet remember i owe you a beer 👍 

![itworked](https://user-images.githubusercontent.com/86922/33845306-4da0bf78-dea3-11e7-9f40-8be266360b33.png)

**Comment by caarlos0** [comment]
Sweet!

Thanks for reporting the issue =D

**Comment by jimafisk** [comment]
The multiple builds tip worked for me, thanks! Just wanted to drop a quick note that I needed to add ID's when I added the second build, here's my `.goreleaser.yml` in case it's helpful to someone: https://github.com/plentico/plenti/blob/8074dcc021058f04f349a79f905339d44f361d88/.goreleaser.yml#L8

**Comment by coolaj86** [comment]
I'm trying to do multiple bulids with this config:

```yml
builds:                                                                                                                                
  - main: ./cmd/unarr/unarr.go                                                                                                         
    env:                                                                                                                               
      - CGO_ENABLED=1                                                                                                                  
      - CC=x86_64-w64-mingw32-gcc                                                                                                      
    goos:                                                                                                                              
      - windows                                                                                                                        
  - main: ./cmd/unarr/unarr.go                                                                                                         
    env:                                                                                                                               
      - CGO_ENABLED=0                                                                                                                  
    goos:                                                                                                                              
      - linux                                                                                                                          
      - darwin
```

But I get this error:

```txt
   ⨯ release failed after 0.17s error=found 2 builds with the ID 'go-unarr', please fix your config
```
