### ISSUE TITLE
Global config file

### ISSUE THREAD

**Issue by jspc** [goreleaser/goreleaser#46]
To help DRY up configuration, and to help with global options (perhaps a particular machine, developer expects to build mainly on ARM with BSD) I propose a global releaser.yml file.

It would look like:

```yaml
github:
  token: github-token
build:
  oses:
    - freebsd
  arches:
    - amd64
```

Note the addition of a github token. This would allow the omission of the env var, and without the concern of committing it to source control given this file is outside of the repo.

It would introduce an order of precedence:

1. default values in releaser
1. global config
1. repo config
1. env vars/ cli args
