### ISSUE TITLE
bin.install <url_sha256> => <bin_name>

### ISSUE THREAD

**Issue by h0tbird** [goreleaser/goreleaser#4625]
### Is your feature request related to a problem? Please describe.

I am a bit lost here but I _think_ I need this for my setup to work.

**e.g.** the [url_sha256](https://github.com/Homebrew/brew/blob/024eb6419b650c2ad6e67b79de1537d459ccbfce/Library/Homebrew/download_strategy.rb#L308) below 👇 ...

```
 ~ echo -n "https://github.com/octoroot/k-swarm/releases/download/v0.1.0/swarmctl_0.1.0_darwin_arm64" | sha256sum
233b7152278c49ebdddcc56906ff36899c075f3f991f4bcd13d02b33f4973a05  -
```

...needs to be automagically generated by `goreleaser` so that my config looks something along the lines of:
```yaml
brews:
  - name: swarmctl
    ids: [swarmctl]
    repository:
      owner: octoroot
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/octoroot/k-swarm
    description: A k8s service swarm
    license: MIT
    test: |
      system "#{bin}/swarmctl -v"
    install: |
      bin.install "233b7152278c49ebdddcc56906ff36899c075f3f991f4bcd13d02b33f4973a05--" => "swarmctl"
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
```

Does my request make any sense? I have few hours with `goreleaser` and brew taps so please close if I am completely wrong.

If I use the default Formula generated by `goreleaser`...
```ruby
def install
  bin.install "swarmctl_0.1.0_darwin_arm64" => "swarmctl"
end
```
...then, I get the error below when I run `HOMEBREW_GITHUB_API_TOKEN=${GITHUB_TOKEN} brew install octoroot/tap/swarmctl -d`:
```
==> Installing swarmctl from octoroot/tap
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7-133-g024eb64\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/octoroot/k-swarm --header Accept:\ application/vnd.github+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20240211-16267-iztlxq
/usr/bin/env hdiutil imageinfo -format /Users/h0tbird/Library/Caches/Homebrew/downloads/233b7152278c49ebdddcc56906ff36899c075f3f991f4bcd13d02b33f4973a05--
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
Errno::ENOENT: No such file or directory - swarmctl_0.1.0_darwin_arm64
```

On the other hand, if I manually set this in the Formula...
```ruby
def install
   bin.install "233b7152278c49ebdddcc56906ff36899c075f3f991f4bcd13d02b33f4973a05--" => "swarmctl"
end
```
...it succeeds.

### Describe the solution you'd like

Whatever works, including showing me how wrong I am.

### Describe alternatives you've considered

Calculate the `url_sha256` hash outside of `goreleaser` and pass it as an environment variable.

### Search

- [x] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by h0tbird** [comment]
Well, I've looked at it a little more and it seems to me that `brew` is failing when trying to [parse the basename](https://github.com/Homebrew/brew/blob/024eb6419b650c2ad6e67b79de1537d459ccbfce/Library/Homebrew/download_strategy.rb#L342) of my URL. In that case is when what I'm asking for here would make sense, although the ideal would be for `brew` to be able to determine my basename 🤔

**Comment by h0tbird** [comment]
Closing because it seems a `brew` issue.

**Comment by h0tbird** [comment]
FTR, `brew` was able to parse the basename after I switched from:
```yaml
archives:
  - id: swarmctl
    format: binary
```
to:
```yaml
archives:
  - id: swarmctl
    format: tar.gz
```
