### ISSUE TITLE
Add none format of an artifact

### ISSUE THREAD

**Issue by janisz** [goreleaser/goreleaser#4644]
### Is your feature request related to a problem? Please describe.

Currently we can override format for platform but what if we would like to have zip and tar.gz for given platform. In that case we should add a new build and make config a bit more complex. If we could use `format: none` in the override then we can have more flexibility.

    

### Describe the solution you'd like

```yaml
format_overrides:
    - goos: [linux, darwin]
      format: none
```    

### Describe alternatives you've considered

Creating additional build for a single platform and then create archives from it.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you want to ship the binaries without archiving? 

```yaml
format_overrides:
  - goos: [ x, y, z]
    format: binary
```
