### ISSUE TITLE
Store all of packages in one GitLab project

### ISSUE THREAD

**Issue by tinboxw** [goreleaser/goreleaser#4684]
### Is your feature request related to a problem? Please describe.

I have multiple projects in a private GitLab repository, with one project being public and designated to store all release packages. I need to use the GitLab `Packages Registry` feature and would like to configure the corresponding settings in the `.goreleaser.yml` file. The aim is to push release packages from different projects to the Packages Registry of the same project.
[Store all of your packages in one GitLab project](https://docs.gitlab.com/ee/user/packages/workflows/project_registry.html)

thx

### Describe the solution you'd like

```
gitlab_urls:
  api: https://git.company.com/api/v4
  download: https://git.company.com
  use_package_registry: true
  use_job_token: true
  package_registry_name:  "release_repo"
```
Is it possible to add a configuration option `package_registry_name: "release_repo"` to specify the project address for the packages registry?

### Describe alternatives you've considered

---

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
I'm willing to merge it if someone wants to works on it.

Also worth noting that it should probably be on `release` as it would affect the release artifacts only. 
Docker images et al can be handled via registry name.

**Comment by ericbrown30** [comment]
@caarlos0 May I pick it up? is it in progress??

**Comment by caarlos0** [comment]
its not in progress no, feel free to work on it if you want to :)

**Comment by ericbrown30** [comment]
Hello,
@caarlos0 @tinboxw 
Could you clarify the preferred approach? Are we aiming to continue creating releases in the current repository while storing artifacts in a different repository, or should we forgo the release process in the current repository and instead upload artifacts exclusively to another repository designated as the GitLab Package Registry?

**Comment by mavogel** [comment]
Hello together :) 

AFAICS and understand it you use the Gitlab package registry from one public repo as general registry for the other private repos. So the registry could also be artifactory/dockerregistry/harbor or any other. 

I can see 2 possible solutions here for the gitlab case

1. it could implemented in goreleaser, but under the publish section, such as the one for [artifactory](https://goreleaser.com/customization/artifactory/). My proposal would be `gitlabRegistries` (the generic [registry](https://docs.gitlab.com/user/packages/package_registry/)) where the spec could be
```yaml
gitlabRegistries:
  - name: production
    target: http://<Your-Instance>:8080/api/v4/projects/:id/packages/generic/{{ .ProjectName }}/{{ .Version }}/{{ .FileName }}
    token: <token> # which has package write access
```
So each private repo would need this config then.

2. or use gitlab features by having a separate job / [downstream pipeline](https://docs.gitlab.com/ci/pipelines/downstream_pipelines/) which gets the artifacts passed from the goreleaser release job and then publishes them via http or [glab cli](https://gitlab.com/gitlab-org/cli) the the desired registry

This is my opinion on this case. Happy to get it challenged and hear other proposals
