### ISSUE TITLE
Document how to upload documents to GCS with json credentials.

### ISSUE THREAD

**Issue by flowchartsman** [goreleaser/goreleaser#4696]
### What happened?

Try as I might, I cannot get the blob target for GCS to work with the Goreleaser github action. I have created SA json credentials that are authorized to upload, and stored them as secrets in my publish environment. Then I place them at a location like so:

```
      - name: save secret to file
        run: |
          echo $BLOB_CREDS > /tmp/blob_creds.json
        env:
          BLOB_CREDS: ${{ secrets.BLOB_CREDS }}
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: "/tmp/blob_creds.json"
      - name: Cleanup
        run: |
          rm -f /tmp/blob_creds.json
```

This has never worked properly, and always results in the following error:

```
error=blobs: failed to publish artifacts: failed to write to bucket: blob (key "<target folder>/<target rpm>") (code=Unknown): Post "https://storage.googleapis.com/upload/storage/v1/b/<folder>/o?alt=json&name=<rpm name>&prettyPrint=false&projection=full&uploadType=multipart": private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: syntax error: sequence 
```

If I reproduce the workflow steps locally  using shell environment variables, `goreleaser release`, works and the artifacts are published, so my credentials are correct and the method I'm using to write them to disk seems like it should work.

It's possible I'm missing a step or not  doing this correctly, but the goreleaser documentation doesn't say anything other than "[these are the credentials we use](https://goreleaser.com/blog/cloud-native-storage/#gcs)".

### How can we reproduce this?

Try and upload artifacts to GCS using goreleaser.

### goreleaser version

```bash
action v5
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
