### ISSUE TITLE
Integrate go-licenses to provides licenses of used libraries

### ISSUE THREAD

**Issue by jkroepke** [goreleaser/goreleaser#4703]
### Is your feature request related to a problem? Please describe.

I'm author of a [software](https://github.com/jkroepke/openvpn-auth-oauth2) that is using libraries licenses under Apache 2.0 license.

Reading https://www.apache.org/licenses/LICENSE-2.0 (Section 4a & 4d), I have to redistribute at least any NOTES files from libraries as well as the license itself.

I would like to licenses files as part of the archives which contains the binaries itself.

### Describe the solution you'd like

Google provides a [lightweight](https://github.com/google/go-licenses) tool to generate such licenses from libraries.

For example

> go run github.com/google/go-licenses@latest save . --save_path="licenses" 

would generate a folder structure which all license and note files. I would like to generate it as part of the goreleaser release.

### Describe alternatives you've considered

Run 

> go run github.com/google/go-licenses@latest save . --save_path="licenses" 

inside CI and add the directory to `files` .

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you could run it in a before hook, and then archive the folder to add to the release...


e.g.:

```yaml
# .goreleaser.yml
before:
  hooks:
    - go run github.com/google/go-licenses@latest save . --save_path="licenses"

archives:
  - id: default
    # add your default archive configuration here
  - id: licenses
    name_template: licenses
    format: tar.gz
    meta: true
    files:
      - ./dist/licenses
```

this should add a `licenses.tar.gz` to the release artifacts...


if you want to add to the regular release archive, just add the `./dist/licenses` to its files section...
