### ISSUE TITLE
Ability to specify the platform for publishing in homebrew

### ISSUE THREAD

**Issue by jidckii** [goreleaser/goreleaser#4719]
### Is your feature request related to a problem? Please describe.

My application is stored in gitlab, but the homebrew-tap repository is in github.
When I start publishing, goreleaser goes to a non-existent repository.
```
 • homebrew tap formula
      • error checking for default branch            projectID=yuccastream/homebrew-tap statusCode=401 error=GET https://gitlab.com/api/v4/projects/yuccastream/homebrew-tap: 401 {message: 401 Unauthorized}
```

My config:
```
...
brews:
  - name: yucca
    alternative_names:
      - "yucca@{{ .Version }}"
    repository:
      owner: yuccastream
      name: homebrew-tap
      token: "{{ .Env.GITHUB_HOMEBREW_TOKEN }}"
    folder: Formula
    goarm: "7"
    homepage: https://yucca.app
    description: Yucca - simple NVR CCTV solution (free edition)
    license: Copyright YuccaStream Team (https://yucca.app/en/terms)
    test: |
      system "#{bin}/yucca version"
    ids:
      - yucca
    url_template: "https://releases.yucca.app/{{- if .IsNightly }}nightly/{{.Version}}{{- else if .Prerelease }}beta/{{.Tag}}{{ else }}{{.Tag}}{{- end }}/{{.ArtifactName}}"

...
gitlab_urls:
  use_job_token: false

release:
  disable: true
...

```

### Describe the solution you'd like

Maybe in the `brews[].repository:` add a platform (github|gitlab) option or a link?

### Describe alternatives you've considered

I don't know

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
