### ISSUE TITLE
enterprise broken?

### ISSUE THREAD

**Issue by automaticgiant** [goreleaser/goreleaser#472]
### Prerequisites

* [x] Are you running the latest version? (39)
* [x] Did you perform a search to see if this problem was already reported?

### Description

enterprise support seems broken.

### Environment

* homebrew, freshly tapped
* `Darwin f45c89bd73ab 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

### Steps to Reproduce

`   • loaded config file        config={c1cacert { false false  map[]} { { }     []  []   map[]} [{[linux darwin windows] [amd64] [] [] .   c1cacert {  map[]} [] map[]}] { []  false map[] [] map[]} {[] [] []       map[] map[]} {     map[] map[]} { map[]} { map[]} [] [] {{[] map[]}  map[]}  { []  } {[] [] [] []     {  map[]} [] map[]} {https://github.redacted/api/v3/ https://github.redacted/api/uploads/ https://github.redacted/} map[]}`

**Expected behavior:** [What you expected to happen]

stuff to release

**Actual behavior:** [What actually happened]

404s, weird interpolation.

with ssh origin:
```
   • RELEASING TO GITHUB
      • creating or updating release repo=git@github.redacted:automaticgiant/c1cacert tag=v0.0.1
      • release updated           url=
      ⨯ release failed after 15.42s error=POST https://github.redacted/api/v3/repos/git@github.redacted:automaticgiant/c1cacert/releases: 404 Not Found []
```

after changing origin to http:
```
   • RELEASING TO GITHUB
      • creating or updating release repo=https:/ tag=v0.0.1
      • release updated           url=
      ⨯ release failed after 12.91s error=POST https://github.redacted/api/v3/repos/https://releases: 404 Not Found []
```

**Comment by caarlos0** [comment]
Hi @automaticgiant 

How dows your `goreleaser.yml` file looks like?

this `creating or updating release repo=git@github.redacted:automaticgiant/c1cacert ` log doesn't seem right...

**Comment by caarlos0** [comment]
closing due to lack of info and inactivity

**Comment by mohanraj-r** [comment]
@caarlos0 I am also facing the same issue
Cool project btw 👍 
Wish I could get it to working..

Here is my `.goreleaser.yml`
```yaml
# Build customization
builds:
  -
    main: ./cmd/main.go
    binary: reporter
    goos:
      - darwin
      - linux
    goarch:
      - amd64
before:
  hooks:
    - gometalinter ./... --exclude=/usr/local
    - go test -v -cover ./...
release:
  github:
    owner: me
    name: reporter
github_urls:
    api: https://git.redacted.com/api/v3/
    upload: https://git.redacted.com/api/v3/
    download: https://git.redacted.com/api/v3/
env_files:
  github_token : goreleaser
```

# Output

```
$ goreleaser --rm-dist --release-notes=Changelog.md --skip-validate --debug
   • RELEASING TO GITHUB
      • creating or updating release repo=me/reporter tag=v0.1.0
      • release updated           url=https://git.redacted.com/me/reporter/releases/tag/v0.1.0
      • uploading to release      file=dist/reporter_0.1.0_darwin_amd64.tar.gz name=reporter_0.1.0_darwin_amd64.tar.gz
      • uploading to release      file=dist/reporter_0.1.0_checksums.txt name=reporter_0.1.0_checksums.txt
      • uploading to release      file=dist/reporter_0.1.0_linux_amd64.tar.gz name=reporter_0.1.0_linux_amd64.tar.gz
   ⨯ release failed after 6.85s error=POST https://git.redacted.com/api/v3/repos/me/reporter/releases/5382/assets?name=reporter_0.1.0_checksums.txt: 404 Not Found []
```
