### ISSUE TITLE
Incorrect default documentation for `build.id`

### ISSUE THREAD

**Issue by hhromic** [goreleaser/goreleaser#4731]
### What happened?

While following the [official documentation](https://goreleaser.com/customization/builds/) for the `build` config section, I discovered that the documented (or implemented?) default is not correct. The documentation states that the default ID is the _Binary Name_:
```yaml
# .goreleaser.yaml
builds:
  # You can have multiple builds defined as a yaml list
  - #
    # ID of the build.
    #
    # Default: Binary name
    id: "my-build"
```

However, the following GoReleaser configuration fails with an error:
```yaml
project_name: example

builds:
  - main: ./cmd/binary-one
    binary: binary-one
  - main: ./cmd/binary-two
    binary: binary-two
```
```
  ⨯ build failed after 0s                    error=found 2 builds with the ID 'example', please fix your config
```

When inspecting the source code, it can be seen that the implemented default is indeed the Project Name:

https://github.com/goreleaser/goreleaser/blob/8cd325eb5a8536708c50bd90dfca2a81cd9bad4c/internal/pipe/build/build.go#L74-L88

### How can we reproduce this?

See "What happened?".

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.24.0
GitCommit:     00c2ff733758f63201811c337f8d043e8fcc9d58
GitTreeState:  false
BuildDate:     2024-02-05T12:18:01Z
BuiltBy:       goreleaser
GoVersion:     go1.21.6
Compiler:      gc
ModuleSum:     h1:jsoS5T2CvPKOyECPATAo8hCvUaX8ok4iAq9m5Zyl1L0=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

It is not clear what is the intended behaviour, so I'm not sure to send a PR fixing the documented default or fixing the implemented default.
