### ISSUE TITLE
Naming inconsistency betweeen `folder` for Homebrew and `directory` for AUR

### ISSUE THREAD

**Issue by bartekpacia** [goreleaser/goreleaser#4732]
# Description

### For AUR ([docs](https://goreleaser.com/customization/aur)):

```yaml
# .goreleaser.yaml
aurs:
  -
    name: foo-bin
    directory: foo-bin
```

Results in:

```
$ tree -a .
.
├── foo-bin
│   ├── .SRCINFO
│   └── PKGBUILD
```

### For Homebrew ([docs](https://goreleaser.com/customization/homebrew)):

```yaml
# .goreleaser.yaml
brews:
  -
    name: foo

    # Folder inside the repository to put the formula.
    folder: Formula
```

Results in:

```
$ tree -a .
.
├── Formula
│   ├── foo.rb
```

### Proposal

Would be nice (for consistency) to settle either on `directory` or `folder`.

### goreleaser version

<details><summary>output</summary>

```
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v1.24.1-0.20240308165802-85f213c9da5e
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.22.1
Compiler:      gc
ModuleSum:     h1:DvK8/lL/M513VkviSCuNSZXImqyP7Df+AjpdyTqbejU=
Platform:      darwin/arm64
```

</details> 

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
