### ISSUE TITLE
Prebuilt binaries cannot be used with dockers

### ISSUE THREAD

**Issue by jsirianni** [goreleaser/goreleaser#4746]
### What happened?

This bug seems to be introduced after v1.23.0. Reproducible on v1.24 and v1.25.

I have a prebuilt builder that registers a binary that is downloaded using a script called by a pre hook.

```yaml
before:
  hooks:
    - make download-prometheus-release ARCH=amd64
    - make download-prometheus-release ARCH=arm64
...
...
  - id: bindplane-prometheus
    builder: prebuilt
    prebuilt:
      path: prometheus-download/{{ .Arch }}/prometheus/prometheus
    binary: prometheus
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # When builder is "prebuilt" there are no default build targets,
    # specifically "goamd64". We would normally omit this specific
    # option.
    goamd64:
      - v1
```

This binary is successfully used with Linux packages using nfpms. My docker step fails, and looks like this:

```yaml
  - id: prometheus-amd64
    goos: linux
    goarch: amd64
    ids:
      - prometheus
    image_templates:
      - "redacted/redacted-prometheus-amd64:latest"
    dockerfile: ./package/prometheus/Dockerfile
    use: buildx
    extra_files:
      - package/prometheus/config/prometheus.yml
      - package/prometheus/config/rules.yml
      - package/prometheus/config/web.yml
      - package/prometheus/service/container-entrypoint.sh
```

The dockerfile does not actually COPY the prebuilt binary, it  looks like this:

```
ARG TAG

FROM prom/prometheus:v${TAG}

# Prometheus user has uid 65534
COPY --chown=65534 --chmod=0600 package/prometheus/config/prometheus.yml /etc/prometheus/prometheus.yml
COPY --chown=65534 --chmod=0600 package/prometheus/config/rules.yml /etc/prometheus/rules.yml
COPY --chown=65534 --chmod=0600 package/prometheus/config/web.yml /etc/prometheus/web.yml
COPY --chown=65534 --chmod=0700 package/prometheus/service/container-entrypoint.sh /container-entrypoint.sh

EXPOSE 9090

ENTRYPOINT [ "/container-entrypoint.sh" ]
```

I get this error 

```
    • pipe skipped                                   reason=2 errors occurred:
	* expected to find 1 artifacts for ids [prometheus], found 0
	* expected to find 1 artifacts for ids [prometheus], found 0
```

### How can we reproduce this?

Use a prebuilt binary builder and a docker configuration that uses that binary. On v1.23.0, it works. On v1.24 / v1.25 it fails.

### goreleaser version

```bash
GitVersion:    1.25.0-pro
GitCommit:     3a9f31b650a9b9e56786b76e1688e1ad0b97fdf1
GitTreeState:  clean
BuildDate:     2024-04-03T01:32:57Z
BuiltBy:       goreleaser
GoVersion:     go1.22.1
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Hey!

Yeah, the problem is that it wasn't properly checking things before.

In your case, the problem is that you are including builds with id `prometheus`, but seems like there aren't any. You can simply remove that line:

```yml
 - id: prometheus-amd64
    goos: linux
    goarch: amd64
    # remove these:
    # ids:
    #  - prometheus
    image_templates:
      - "redacted/redacted-prometheus-amd64:latest"
    dockerfile: ./package/prometheus/Dockerfile
    use: buildx
    extra_files:
      - package/prometheus/config/prometheus.yml
      - package/prometheus/config/rules.yml
      - package/prometheus/config/web.yml
      - package/prometheus/service/container-entrypoint.sh
```

that way, you'll hint goreleaser you don't expect to include any builds, and everything should be fine.
