### ISSUE TITLE
Sign step fails with: `Non-interactive mode detected, using device flow.`

### ISSUE THREAD

**Issue by dirien** [goreleaser/goreleaser#4803]
### What happened?

Not sure if it's a Goreleaser issue or Cosign, but I can't release a signed binary anymore. I get all the time this:

![image](https://github.com/goreleaser/goreleaser/assets/38325136/48ff89b9-5396-487b-a520-99592d19e4b5)

```shell
    • signing                                        cmd=cosign artifact=pulumi-resource-akp-v0.6.2-darwin-arm64.tar.gz signature=dist/pulumi-resource-akp-v0.6.2-darwin-arm64.tar.gz.sig certificate=dist/pulumi-resource-akp-v0.6.2-darwin-arm64.tar.gz.pem
Using payload from: dist/pulumi-resource-akp-v0.6.2-darwin-arm64.tar.gz
Generating ephemeral keys...
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code JHFH-NWNV in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=JHFH-NWNV
Code will be valid for 300 seconds
```

### How can we reproduce this?

Cosign: 2.2.4

This is a snippet I use in my `goreleaser.yaml`

```yaml
#signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '-y'
      - '--output-certificate=${certificate}'
      - '--bundle=${signature}'
      - '${artifact}'
    artifacts: all
    output: true
```

### goreleaser version

```bash
v1.25.1
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
