### ISSUE TITLE
Prebuilt builder error `prebuilt not found in type config.Build`

### ISSUE THREAD

**Issue by Gjergj** [goreleaser/goreleaser#4899]
### What happened?

I run `goreleaser build --snapshot` and get error `field prebuilt not found in type config.Build`

### How can we reproduce this?

```
builds:
  - id: macos-arm64
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    goamd64:
      - v1
    prebuilt:
      path: ./build/bin/binary_file
    binary: bin/binary_file
```

### goreleaser version

```bash
GitVersion:    1.26.2
GitCommit:     d7c23c168fa61d738cd6fba03a645071e174bba5
GitTreeState:  false
BuildDate:     2024-05-23T12:15:05Z
BuiltBy:       goreleaser
GoVersion:     go1.22.3
Compiler:      gc
ModuleSum:     h1:1iY1HaXtRiMTrwy6KE1sNjkRjsjMi+9l0k6WUX8GpWw=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
