### ISSUE TITLE
wrong current directory

### ISSUE THREAD

**Issue by tcurdt** [goreleaser/goreleaser#4913]
### What happened?

I am running this github workflow

```
      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Release Test
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --skip=announce,publish,validate
```
but the docker build fails with `pattern ./...: directory prefix . does not contain main module or its selected dependencies`

To confirm the build locally first I tried `docker buildx build -t testimage:arm64 . --platform=linux/arm64` which works.

It seems the content of `/app` directory (the directory of go build) just does not contain the expected copy of the source code when building via `goreleaser`.

And fair enough. `ADD . /app` seems to copy the wrong resources.

```
RUN ls -la
#10 0.040 total 11756
#10 0.040 drwxr-xr-x    1 root     root          4096 Jun  5 17:25 .
#10 0.040 drwxr-xr-x    1 root     root          4096 Jun  5 17:25 ..
#10 0.040 -rw-r--r--    1 root     root           448 Jun  5 17:25 Dockerfile
#10 0.040 -rwxr-xr-x    1 root     root       6381720 Jun  5 17:25 oci-resolve
#10 0.040 -rw-r--r--    1 root     root       2769070 Jun  5 17:25 oci-resolve_0.0.1_amd64.deb
#10 0.040 -rw-r--r--    1 root     root       2862832 Jun  5 17:25 oci-resolve_0.0.1_x86_64.apk
#10 0.040 -rw-r--r--    1 root     root            31 Jun  5 17:25 passwd
```

I seems `goreleaser` starts the docker build from the wrong directory. Which means that `.` is not the root of the project.

### How can we reproduce this?

https://github.com/tcurdt/oci-resolve

commit 377a1fb

### goreleaser version

```bash
Locally:
goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.26.2
GitCommit:     d7c23c168fa61d738cd6fba03a645071e174bba5
GitTreeState:  clean
BuildDate:     2024-05-23T12:15:05
BuiltBy:       homebrew
GoVersion:     go1.22.3
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64

And otherwise version 2 installed via github action.
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
