### ISSUE TITLE
When `blobs: ids: []` is set, no artifacts should be uploaded

### ISSUE THREAD

**Issue by brianstrauch** [goreleaser/goreleaser#4920]
### What happened?

I'm attempting to upload a single text file to S3 with the following configuration:
```
blobs:
  - acl: public-read
    bucket: <bucket>
    ids: []
    extra_files:
      - glob: release-notes.txt
    provider: s3
    region: us-west-2
```

I would expect no artifacts to be uploaded (only release-notes.txt), but instead GoReleaser treats `ids: []` the same as if you were to not specify the `ids` field. This causes all artifacts to be uploaded in addition to release-notes.txt.

### How can we reproduce this?

Our repository is private 😢 but the snippet above should work just fine!

### goreleaser version

```bash
1.25.1-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
