### ISSUE TITLE
Building Multiple Binaries with a Single Command

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#4927]
see discussion: https://github.com/orgs/goreleaser/discussions/4886

**Comment by caarlos0** [comment]
this is going to be a big change, actually... still thinking on how to do it.

currently we define the final binary name, and the main.

this change would require us to be able to pass multiple mains, and the binary names would be inferred from them

not yet sure how to do this in a good way

**Comment by caarlos0** [comment]
I'm thinking, maybe, we could do something like this:

```yaml
builds:
  - builder: go
    binaries: 
    - foo
    - bar
    mains: 
    - "./cmd/foo/..."
    - "./cmd/bar/..." 
```

The go builder could then do it at a single pass, whilst others may need to "explode" the build into multiple commands 🤔
