### ISSUE TITLE
Support cloudsmith as publish target

### ISSUE THREAD

**Issue by obs-gh-alexlew** [goreleaser/goreleaser#4957]
### Is your feature request related to a problem? Please describe.

The existing publishing option for deb and rpm repos is Gemfury but Gemfury seems to be in a questionable state as a company. I've opened multiple support tickets including ones regarding GPG signing support and haven't heard anything back. 

### Describe the solution you'd like

I'd like to switch to a different cloud repo provider and I'd like to use Cloudsmith. They seem to provide a best in class solution for hosting packages, especially ones that are signed. 

### Describe alternatives you've considered

My current build process runs on GH Actions, I'd probably just create a new GH Action that pushes artifacts up to Cloudsmith via their action. It should be fairly straight forward but I'd like to see native support in goreleaser so that it can run in other contexts as well as in GH Actions. Also, it saves some complexity in my build chain. 

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
Worked on it today, and have a working version already!

Will finish polishing/docs/etc it and it'll be on v2.1 🙏

**Comment by obs-gh-alexlew** [comment]
beautiful, thank you very much!

**Comment by Nmishin** [comment]
Is it possible to configure multiple distributions for format?
For example I want to have something like this:
```
cloudsmiths:
  - organization: myorg
    repository: myrepo
    distributions:
      deb: [ "ubuntu/xenial", "ubuntu/focal", "ubuntu/noble" ]
```

**Comment by caarlos0** [comment]
@Nmishin no, but we could add that I think.

Right now you would have to add multiple cloudsmith configurations, e.g.:

```yaml
cloudsmiths:
  - organization: myorg
    repository: myrepo
    distributions:
      deb: "ubuntu/xenial"
  - organization: myorg
    repository: myrepo
    distributions:
      deb: "ubuntu/focal"
```

but yeah, your idea is probably better
