### ISSUE TITLE
make_latest & prerelease to false but draft github release with param latest to true 

### ISSUE THREAD

**Issue by bcaurel** [goreleaser/goreleaser#4961]
### What happened?

Here my goreleaser config 
```yaml
release:
  prerelease: false
  draft: true
  replace_existing_draft: true
  make_latest: false
```
  
  In this case the draft release created have the latest checked : 
  
![image](https://github.com/goreleaser/goreleaser/assets/17043146/9c315d45-08b4-423e-b875-d1509ca22f61)

Another wrong behavior related: 
If I use this config
```yaml
release:
  prerelease: auto
  draft: true
  replace_existing_draft: true
  make_latest: false
```  

  the draft release created have the prerelease checked : 
  
![image](https://github.com/goreleaser/goreleaser/assets/17043146/91d463ab-d304-4612-8556-687a3986a2b8)

  

### How can we reproduce this?

```yaml
release:
  prerelease: false
  draft: true
  replace_existing_draft: true
  make_latest: false
```

### goreleaser version

```bash
v2.0.1pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
