### ISSUE TITLE
Releasing a debian-based official Goreleaser container image

### ISSUE THREAD

**Issue by Nicolas-Peiffer** [goreleaser/goreleaser#4968]
### Is your feature request related to a problem? Please describe.

The current `goreleaser` official image [docker.io/goreleaser/goreleaser](https://hub.docker.com/r/goreleaser/goreleaser) is based on the Golang Alpine image like [`docker.io/golang:1.22.4-alpine`](https://hub.docker.com/_/golang) ( source [goreleaser/Dockerfile](https://github.com/goreleaser/goreleaser/blob/b7ba1826a7d8a0516ed4904b265c44988cc32ca0/Dockerfile#L1C6-L1C26) ).

I would like to have the choice between an Alpine-based goreleaser official image and a Debian-based goreleaser official image.

The debian-based goreleaser official image could be based on the on the Golang debian image like [`docker.io/golang:1.22.4-bookworm`](https://github.com/docker-library/golang/blob/81c0d3115b37997c04828faba09440fd9fffce33/1.22/bookworm/Dockerfile).

One of the reason is the support of `glibc` by debian and `libc-musl` by Alpine. And sometimes I need CGO enabled and I need standard `glibc` and not the musl one.

### Describe the solution you'd like

The debian-based goreleaser official image could be based on the on the Golang debian image like [`docker.io/golang:1.22.4-bookworm`](https://github.com/docker-library/golang/blob/81c0d3115b37997c04828faba09440fd9fffce33/1.22/bookworm/Dockerfile).

### Describe alternatives you've considered

Today, to compensate for the lack of an official debian-based `goreleaser` image on [docker.io/goreleaser/goreleaser](https://hub.docker.com/r/goreleaser/goreleaser), I create my own custom Goreleaser image thanks to a Gitlab-ci job.

I use the debian-based version of [docker.io/golang](https://hub.docker.com/_/golang) as base image, and I install `goreleaser` and some tools like `cosign`, `ko-build` and `trivy` on top of the base image.

I could create my own image outside of the Gitlab-ci job, but I do not want to maintain a custom Goreleaser image.

**However, having a pre-build debian-based `goreleaser` image would make my CI pipeline faster**, as I don't have to wait for `goreleaser`, `cosign`, `ko-build` and `trivy` to finish install. It also is friendlier for my network.

```yaml
# .gitlab-ci.yml
release:
  stage: goreleaser
  image:
    # We are not using the docker.io/goreleaser/goreleaser image because it is
    # based on Alpine and it uses libc.musl-x86_64.so.1
    name: docker.io/golang:1.22.4-bookworm
    entrypoint: [""]
  only:
    - tags
  variables:
    WORKSPACE: $CI_PROJECT_DIR
    CI_DEBUG_TRACE: "true"
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
    GIT_DEPTH: 0
    GITLAB_TOKEN: $GITLAB_TOKEN
    CI_JOB_TOKEN: $CI_JOB_TOKEN
  before_script: 
    - go install github.com/goreleaser/goreleaser/v2@latest
    - go install github.com/sigstore/cosign/v2/cmd/cosign@latest
    - go install github.com/google/ko@latest
    - curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.49.1
    - ko login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - make release
```

On GitHUB actions, I do not have this musl libc issue since GitHUB linux runners are Ubuntu-based.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
