### ISSUE TITLE
Windows x64 could not have its enviroment variable overriden

### ISSUE THREAD

**Issue by LucasSnatiago** [goreleaser/goreleaser#4986]
### What happened?

I have a ebiten game project being automatic built by goreleaser. Linux version and Windows 32 bit is building fine, but when it comes to Windows amd64, that I need to have some environment variables overridden it is ignored.

### How can we reproduce this?

If you want to take a look at the repository: [PongEbiten](https://github.com/Captain-Santiago/PongEbiten).
Build with the bug: [PongEbiten Action](https://github.com/Captain-Santiago/PongEbiten/actions/runs/9894061842/job/27330690303)

My .goreleaser.yml:
```
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - '386'
    ldflags:
      - -s -w

    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
          - CGO_ENABLED=1
        ldflags:
          - -s -w -extldflags "-static"

      - goos: windows
        goarch: '386'
        env:
          - CC=i686-w64-mingw32-gcc
          - CXX=i686-w64-mingw32-g++
          - CGO_ENABLED=1
        ldflags:
          - -s -w -extldflags "-static"

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

upx:
  - enabled: true
    compress: best
    lzma: true
    brute: true
```

Error message from Github CI. It does not say Windows amd64 is being overridden. Also, this error message ```gcc: error: unrecognized command-line option ‘-mthreads’; did you mean ‘-pthread’?``` only happens when it is in fact no being overridden.
```
Run goreleaser/goreleaser-action@v6
  with:
    distribution: goreleaser
    version: ~> v2
    args: release --clean
    workdir: .
    install-only: false
  env:
    GITHUB_TOKEN: ***
Downloading https://github.com/goreleaser/goreleaser/releases/download/v2.0.1/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/27bcd62c-8b34-4261-b442-41b406b77069 -f /home/runner/work/_temp/c91c4e2c-092d-4484-b85d-eb6a35e57746
GoReleaser ~> v2 installed successfully
/opt/hostedtoolcache/goreleaser-action/2.0.1/x64/goreleaser release --clean
  • starting release...
  • loading                                          path=.goreleaser.yaml
  • loading environment variables
    • using token from  $GITHUB_TOKEN 
  • getting and validating git state
    • git state                                      commit=df5190fa03ba30a9750df59d310fddabc3a76b44 branch=HEAD current_tag=v1.0.7 previous_tag=v1.0.6 dirty=false
  • parsing tag
  • setting defaults
  • running before hooks
    • running                                        hook=go mod tidy
    • running                                        hook=go generate ./...
    • took: 3s
  • checking distribution directory
  • setting up metadata
  • storing release metadata
    • writing                                        file=dist/metadata.json
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/PongEbiten_windows_386/PongEbiten.exe
    • building                                       binary=dist/PongEbiten_linux_amd64_v1/PongEbiten
    • overridden build details for windows386        details={ [-s -w -extldflags "-static"] [] [] [] [] [CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++]}
    • building                                       binary=dist/PongEbiten_windows_amd64_v1/PongEbiten.exe
    • building                                       binary=dist/PongEbiten_linux_386/PongEbiten
    • took: 1m8s
  ⨯ release failed after 1m11s               error=failed to build for windows_amd64_v1: exit status 1: # runtime/cgo
gcc: error: unrecognized command-line option ‘-mthreads’; did you mean ‘-pthread’?

Error: The process '/opt/hostedtoolcache/goreleaser-action/2.0.1/x64/goreleaser' failed with exit code 1
```

### goreleaser version

```bash
I don't know how to run it inside Github CI, but that's the version specified there: 

Run goreleaser/goreleaser-action@v6
  with:
    distribution: goreleaser
    version: ~> v2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
