### ISSUE TITLE
[build] add command-line flag for setting `builds.no_unique_dist_dir`

### ISSUE THREAD

**Issue by hhromic** [goreleaser/goreleaser#5024]
### Is your feature request related to a problem? Please describe.

The `builds.no_unique_dist_dir` configuration is very handy for more advanced use-cases, however it would be nice if it could be provided on-the-fly via a command-line flag such as `--no-unique-dist-dir`.

We use GoReleaser inside of Dockerfiles to build our Go applications.
To explain the feature request, consider the following example snippet of a GoReleaser config file:
```yaml
builds:
  - id: binary1
    main: ./cmd/binary1
    binary: binary1
  - id: binary2
    main: ./cmd/binary2
    binary: binary2
```
And the following example snippet of a Dockerfile:
```Dockerfile
FROM golang AS builder
WORKDIR /build
COPY . .
RUN goreleaser build --clean --single-target

FROM cgr.dev/chainguard/static:latest AS final
COPY --from=builder /build/dist/binary1_*/binary1 /binary1
COPY --from=builder /build/dist/binary2_*/binary2 /binary2
```
The usage of wildcards there is not ideal and not very robust/reliable.

To improve on this, we can use the `builds.no_unique_dist_dir` configuration to generate predictable binary names:
```yaml
builds:
  - id: binary1
    main: ./cmd/binary1
    binary: binary1
    no_unique_dist_dir: true
  - id: binary2
    main: ./cmd/binary2
    binary: binary2
    no_unique_dist_dir: true
```
```Dockerfile
FROM cgr.dev/chainguard/static:latest AS final
COPY --from=builder /build/dist/binary1 /binary1
COPY --from=builder /build/dist/binary2 /binary2
```

The problem is that we don't want to hard-code `builds.no_unique_dist_dir` because it will not work for developers that want to build for multiple targets, that is, users that do not use `--single-target` for building. Using `builds.no_unique_dist_dir` creates a restriction that requires documenting details on how to build the application.

### Describe the solution you'd like

Instead of hard-coding the `builds.no_unique_dist_dir` option in the config file itself which creates restrictions in our case, we would like to be able to tell GoReleaser to enable this option on demand via the command-line, to be used together with `--single-target` for example.

In this way, users calling GoReleaser with all targets or single-target can both use the same config file:
```
# users can build with multi-target with no problem
$ goreleaser build --clean --snapshot  

# in Dockerfile we can use `--no-unique-dist-dir` with `--single-target` to have predictable binary names
$ goreleaser build --clean --single-target --no-unique-dist-dir
```
To keep it simple, this option would be applied globally to all the configured binaries in the build.

### Describe alternatives you've considered

There are no direct alternatives at the moment.
What we are doing for the moment is what was described in the first section, copying binaries using wildcards.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
