### ISSUE TITLE
error=PUT https://api.github.com/repos/[user]/homebrew-tap/contents/[project].rb: 404 Not Found []

### ISSUE THREAD

**Issue by drgrib** [goreleaser/goreleaser#504]
I followed the instructions on the [main page](https://goreleaser.com/) and am getting this:

```
release failed after 16.34s error=PUT https://api.github.com/repos/drgrib/homebrew-tap/contents/ttimer.rb: 404 Not Found []
```

I'm confused because the documentation says all of these homebrew files will be generated for me but then the program errors out because I don't have them.

Here are the contents of my `goreleaser.yml` file:

```
brew:
  homepage: https://github.com/drgrib/ttimer
  github:
    owner: drgrib
    name: homebrew-tap
```
