### ISSUE TITLE
Support multiple Docker tags using the same Dockerfile

### ISSUE THREAD

**Issue by mattmoyer** [goreleaser/goreleaser#505]
### Describe the feature and how you think it should work.
I have multiple Docker images that use the same binary, but build on top of different upstream base images. For example, I can set these up easily with something like:
```yaml
# [...]
dockers:
  - image: myrepo/myimage
    dockerfile: Dockerfile.debian-stretch
    tag_template: "{{ .Tag }}-debian-stretch"
    latest: false
  - image: myrepo/myimage
    dockerfile: Dockerfile.debian-jessie
    tag_template: "{{ .Tag }}-debian-jessie"
    latest: false
  - image: myrepo/myimage
    dockerfile: Dockerfile.alpine-3.6
    tag_template: "{{ .Tag }}-alpine-3.6"
    latest: false
  - image: myrepo/myimage
    dockerfile: Dockerfile.alpine-3.7
    tag_template: "{{ .Tag }}-alpine-3.7"
    latest: false
# [...]
```

This will tag, for example:
 - `myrepo/myimage:v1.0.0-debian-stretch`
 - `myrepo/myimage:v1.0.0-debian-jessie`
 - `myrepo/myimage:v1.0.0-alpine-3.6`
 - `myrepo/myimage:v1.0.0-alpine-3.7`

So far so good, but I would also like to easily tag my Debian Stretch image with `myrepo/myimage:v1.0.0-debian` and tag my Alpine 3.7 image with `myrepo/myimage:v1.0.0-alpine`. I'd also like to have a "default" image `myrepo/myimage:v1.0.0` that points to one of them. For example:
 - `myrepo/myimage:v1.0.0` (built from `Dockerfile.alpine-3.7`)
 - `myrepo/myimage:v1.0.0-debian` (built from `Dockerfile.debian-stretch`)
 - `myrepo/myimage:v1.0.0-debian-jessie` (built from `Dockerfile.debian-jessie`)
 - `myrepo/myimage:v1.0.0-debian-stretch` (built from `Dockerfile.debian-stretch`)
 - `myrepo/myimage:v1.0.0-alpine` (built from `Dockerfile.alpine-3.7`)
 - `myrepo/myimage:v1.0.0-alpine-3.6` (built from `Dockerfile.alpine-3.6`)
 - `myrepo/myimage:v1.0.0-alpine-3.7` (built from `Dockerfile.alpine-3.7`)

This is awkward to do right now. I was able to get it working locally with symlinks, but my hosted CI tool didn't support them correctly.

I also tried specifying the same `dockerfile` value multiple times with different `tag_template` values, but got an error `failed to link dockerfile: link Dockerfile.alpine-3.7 dist/linuxamd64/Dockerfile.alpine-3.7: file exists`.

I was able to do this by copying each Dockerfile (e.g., `cp Dockerfile.alpine-3.7 Dockerfile.alpine`). But this leaves you with a lot of duplicated files.

### Proposal
Allow `tag_template` to take a list value in addition to the current single value. For example:
```yaml
# [...]
dockers:
  - image: myrepo/myimage
    dockerfile: Dockerfile.debian-stretch
    tag_template:
    - "{{ .Tag }}-debian"
    - "{{ .Tag }}-debian-stretch"
    latest: false
  - image: myrepo/myimage
    dockerfile: Dockerfile.debian-jessie
    tag_template: "{{ .Tag }}-debian-jessie"
    latest: false
  - image: myrepo/myimage
    dockerfile: Dockerfile.alpine-3.6
    tag_template: "{{ .Tag }}-alpine-3.6"
    latest: false
  - image: myrepo/myimage
    dockerfile: Dockerfile.alpine-3.7
    tag_template:
    - "{{ .Tag }}"
    - "{{ .Tag }}-alpine"
    - "{{ .Tag }}-alpine-3.7"
    latest: false
# [...]
```
