### ISSUE TITLE
Allow template for `tag_name` in `nightly` block

### ISSUE THREAD

**Issue by sw360cab** [goreleaser/goreleaser#5061]
### Is your feature request related to a problem? Please describe.

It would be useful in the `nightly` block if the field `tag_name` is: _Templates: allowed_

### Describe the solution you'd like

Change to

```yaml
# .goreleaser.yml
nightly:
  ...

  # Tag name to create if publish_release is enabled.
  # Templates: allowed.
  tag_name: devel
```

### Describe alternatives you've considered

I think this being a descriptive field may be useful to be templated.
Feel free to decline this.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
