### ISSUE TITLE
ADD support for toYaml 

### ISSUE THREAD

**Issue by mattclegg** [goreleaser/goreleaser#5068]
### Is your feature request related to a problem? Please describe.

I would like to be able to calculate boolean values & then use them in yaml to determine if specific actions should run.

### Describe the solution you'd like

```
dockers:
  - goos: linux
    goarch: amd64
    skip_push: "{{ ne .GitURL \"https://github.com/helm/chart-releaser\" | toYaml }}"
```

### Describe alternatives you've considered

```
dockers:
  - goos: linux
    goarch: amd64
    skip_push: "{{ if ne .GitURL \"https://github.com/helm/chart-releaser\" }}true{{ else }}false{{ end }}"
```

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
you can do:

```yaml
dockers:
  - goos: linux
    goarch: amd64
    skip_push: "{{ ne .GitURL \"https://github.com/helm/chart-releaser\" }}"
```

no need to `toYaml` I think
