### ISSUE TITLE
Enable Homebrew to download releases from private GitHub repo

### ISSUE THREAD

**Issue by loa** [goreleaser/goreleaser#507]
We plan using goreleaser + homebrew for handling new internal tools. We will be using a private homebrew tap and private repos for the tools on GitHub. Homebrew added the functionality to download release assets from private GitHub repos last year [Homebrew 1.2.0](https://brew.sh/2017/05/01/homebrew-1.2.0/).

Can we add an option to the brew provider to be able to support this?

Example options:
```
brew:
   # narrow example
  private_github_repo: true
  
  # generic but verbose
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
```

What is needed in the generated Formulas to be able to download releases from private GitHub repositories:
```diff
class Tinkernetes < Formula
-   url "https://github.com/loa/foobar/releases/download/0.1.0/foobar_0.1.0_darwin_amd64.tar.gz"
+   url "https://github.com/loa/foobar/releases/download/0.1.0/foobar_0.1.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
end
```

## References:
- New feature: Allow download from private GitHub repository -
 https://github.com/Homebrew/brew/pull/1763
