### ISSUE TITLE
goreleaser (woodpecker) - go.mod requires go >= 1.23

### ISSUE THREAD

**Issue by enzofoucaud** [goreleaser/goreleaser#5102]
### What happened?

Hello,

I get this error when using goreleaser in Woodpecker. Are the latest images up to date with version 1.23? Or have I made a mistake?

⨯ release failed after 0s                  error=hook failed: shell: 'go mod tidy': exit status 1: go: go.mod requires go >= 1.23 (running go 1.21.6; GOTOOLCHAIN=local)

### How can we reproduce this?

```yaml
version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

gitea_urls:
  api: https://git.XXX.local/api/v1
  download: https://git.XXX.local
  skip_tls_verify: true
```

### goreleaser version

goreleaser/goreleaser (last version i supposed)
```yaml
when:
  - event: [tag]

variables:
  - &git_plugin woodpeckerci/plugin-git:2.5.0
  - &goreleaser_image goreleaser/goreleaser

clone:
  git:
    image: *git_plugin
    settings:
      skip-verify: true

steps:
  release:
    image: *goreleaser_image
    commands:
      - goreleaser release
    secrets:
      - gitea_token
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
