### ISSUE TITLE
`--single-target` option builds for multiple targets in some situations

### ISSUE THREAD

**Issue by uubulb** [goreleaser/goreleaser#5112]
### What happened?

When using a partial build by specifying the `--single-target` argument for the build command, there are cases where it may build for more than one target.

### How can we reproduce this?

When you specify an architecture that is a prefix of another architecture, it will also build for that target. (e.g. arm and arm64, mips and mipsle...)
Here is an example configuration to reproduce the issue:
```yaml
version: 2
builds:
  - id: linux_arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -s -w
      - -extldflags "-static -fpic"
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/example
    binary: example-{{ .Os }}-{{ .Arch }}
  - id: linux_arm
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -s -w
      - -extldflags "-static -fpic"
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    main: ./cmd/example
    binary: example-{{ .Os }}-{{ .Arch }}
```
Run the build command `GOOS=linux GOARCH=arm goreleaser build --single-target --clean`, and you will see that arm64 is included in the build.

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.2.0
GitCommit:     111121bbd98df17cc5d81888aa94a8d3694bc157
GitTreeState:  clean
BuildDate:     2024-08-15T01:56:53
BuiltBy:       homebrew
GoVersion:     go1.22.6
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

The issue might lie in the following code, where only the prefix of targets is being checked. https://github.com/goreleaser/goreleaser/blob/00f237aa6ec0e87f8c51ea1553befa8841946774/internal/pipe/build/filter.go#L11-L28
