### ISSUE TITLE
Example GitHub config file does not pass checks

### ISSUE THREAD

**Issue by Aptimex** [goreleaser/goreleaser#5120]
### What happened?

The example config file for using GitHub Actions does not pass a `goreleaser check` check. 

### How can we reproduce this?

Copy the example snippet at https://goreleaser.com/ci/actions/#workflow to a local file (Linux), call it `test.yml`:
```
# .github/workflows/release.yml
name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
```

Run `goreleaser check ./test.yml`. 

Note the error output:
```
  • only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
  ⨯ command failed                                   error=only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
```

### goreleaser version

```bash
/snap/bin/goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.2.0
GitCommit:     111121bbd98df17cc5d81888aa94a8d3694bc157
GitTreeState:  false
BuildDate:     2024-08-15T01:56:53Z
BuiltBy:       goreleaser
GoVersion:     go1.23.0
Compiler:      gc
ModuleSum:     h1:IKWOpyx4A9gG/8o2AEN46PlV3qR/HqXVTHT6W+G8Qi0=
Platform:      linux/amd64
```

### GoReleaser Check

- [ ] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm getting the same error when running an actual GitHub action configured very similarly to the example config (which ran fine before the V2.2.0 release), and tried running the check against the example config as a sanity check. Figured getting the example fixed would probably be enough to figure out how to fix my actual config. 

Can't for the life of me figure out where `version: 2` is supposed to go in that file to make it happy.
