### ISSUE TITLE
Unhandled `upx` exception `UnknownExecutableFormatException`

### ISSUE THREAD

**Issue by WangYihang** [goreleaser/goreleaser#5141]
### What happened?

```bash
$ goreleaser build --snapshot --clean
  • skipping validate...
  • cleaning distribution directory
  • loading environment variables
  • getting and validating git state
    • accepting to run without a git repository because this is a snapshot
    • git state                                      commit=none branch=none current_tag=v0.0.0 previous_tag=<unknown> dirty=false
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=0.0.0-SNAPSHOT-none
  • running before hooks
    • running                                        hook=go mod tidy
    • running                                        hook=go generate ./...
  • ensuring distribution directory
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • building                                       binary=dist/m_freebsd_arm_6/m
    • building                                       binary=dist/m_freebsd_amd64_v1/m
    ...
    • building                                       binary=dist/m_windows_arm64/m.exe
    • building                                       binary=dist/m_darwin_amd64_v1/m
  • upx
    • could not pack                                 binary=dist/m_darwin_arm64/m exception=CantPackException
    • could not pack                                 binary=dist/m_windows_arm64/m.exe exception=CantPackException
    • could not pack                                 binary=dist/m_windows_arm_6/m.exe exception=CantPackException
    • could not pack                                 binary=dist/m_darwin_amd64_v1/m exception=CantPackException
    • could not pack                                 binary=dist/m_freebsd_386/m exception=CantPackException
    • could not pack                                 binary=dist/m_netbsd_386/m exception=CantPackException
    • could not pack                                 binary=dist/m_openbsd_386/m exception=CantPackException
    • packed                                         before=1.049MB after=282.3kB ratio=26% binary=dist/m_linux_mips_hardfloat/m
    • packed                                         before=926.7kB after=329.7kB ratio=35% binary=dist/m_windows_amd64_v1/m.exe
    • packed                                         before=983.2kB after=292.5kB ratio=29% binary=dist/m_linux_arm64/m
    • packed                                         before=893.1kB after=327.8kB ratio=36% binary=dist/m_linux_amd64_v1/m
    • packed                                         before=869.4kB after=308.2kB ratio=35% binary=dist/m_windows_386/m.exe
    • packed                                         before=1.049MB after=305.6kB ratio=29% binary=dist/m_linux_ppc64le/m
    • packed                                         before=1.049MB after=286.4kB ratio=27% binary=dist/m_linux_mipsle_hardfloat/m
    • packed                                         before=885kB after=324.3kB ratio=36% binary=dist/m_solaris_amd64_v1/m
    • packed                                         before=983.2kB after=288.6kB ratio=29% binary=dist/m_linux_arm_6/m
    • packed                                         before=1.049MB after=287.8kB ratio=27% binary=dist/m_linux_ppc64/m
    • packed                                         before=848kB after=307.4kB ratio=36% binary=dist/m_linux_386/m
  ⨯ build failed after 0s                    error=could not pack dist/m_netbsd_amd64_v1/m: exit status 1:                        Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX git-40b7e2+ Markus Oberhumer, Laszlo Molnar & John Reiser   May 10th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: dist/m_netbsd_amd64_v1/m: UnknownExecutableFormatException

Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
```

### How can we reproduce this?

```yaml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - solaris
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - ppc64
      - ppc64le

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

upx:
  -
    # Whether to enable it or not.
    enabled: true

    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best

    # Whether to try LZMA (slower).
    lzma: true

    # Whether to try all methods and filters (slow).
    brute: false

```

### goreleaser version

```bash
$ goreleaser --version                
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v2.3.1
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     h1:yPL8rveS1O7ciSL2nvE2jIvODsbft/sZn00tTbD06Yg=
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
