### ISSUE TITLE
Cannot find docker image for push after build

### ISSUE THREAD

**Issue by aristosvo** [goreleaser/goreleaser#5146]
### What happened?

I try to release a go app as image:
```yaml
version: 2
gitlab_urls:
  use_package_registry: true

builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
dockers:
  - image_templates:
      - "{{ .Env.CI_REGISTRY_IMAGE }}:latest"
      - "{{ .Env.CI_REGISTRY_IMAGE }}:{{ .Tag }}"
```

```cmd 
 • docker images
    • building docker image                          image=registry.gitlab.com/xxx/afctl:latest
    • took: 26s
  • publishing
    • docker images
      • pushing                                      image=registry.gitlab.com/xxx/afctl:latest
  ⨯ release failed after 5m6s                error=docker images: failed to publish artifacts: failed to push registry.gitlab.com/xxx/afctl:latest after 0 tries: failed to push registry.gitlab.com/xxx/afctl:latest: exit status 1: Error response from daemon: failed to find image registry.gitlab.com/xxx/afctl:latest: image not known

```

### How can we reproduce this?

No idea..

### goreleaser version

```bash
2.2.0, but also 2.3.2
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
