### ISSUE TITLE
GoReleaser Pro: field dmg not found in type config.Project

### ISSUE THREAD

**Issue by tiero** [goreleaser/goreleaser#5168]
### What happened?

I have purchased a Pro license and added the `# yaml-language-server` comment at the beginning of my file. Running any command like `check` or `release` will complain about the `dmg` field.

```
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

before:
  hooks:
    - go mod tidy
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate
    - make icon


dmg:
  - name: "my-proj-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    extra_files:
      - icon.png
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
```

### How can we reproduce this?

```sh
export GORELEASER_KEY=[REDACTED]
goreleaser release
```

### goreleaser version

```bash
goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.3.2
GitCommit:     e8c2ef77358b4b1e59b904322824ccbfa3487ab2
GitTreeState:  false
BuildDate:     2024-09-17T12:30:49Z
BuiltBy:       goreleaser
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     h1:/fSs+KwmCXCXN4eeI27z/xp1+FwIS4rWisL6aTUeiGw=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
