### ISSUE TITLE
create MacOS bundle before packaging as .dmg

### ISSUE THREAD

**Issue by tiero** [goreleaser/goreleaser#5172]
### Is your feature request related to a problem? Please describe.

Now when using the `dmg` feature works well, but it package inside the "bare" binary instead of a bundled MacOS .app, so an icon can be displayed inside the Application folder and the terminal is not started.

### Describe the solution you'd like

Something like

```yml
macOS_bundle:
  - id: app-desktop
    name: AppDesktop
    identifier: com.app.desktop
    icon: build/icon.icns
    version: "{{ .Version }}"
    resources:
      - icon.png
    extra_files:
      - LICENSE
      - README.md
```

### Describe alternatives you've considered

not using goreleaser and hacing my script by hand

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
