### ISSUE TITLE
Release fails if filename template contains directories (i.e. slashes)

### ISSUE THREAD

**Issue by aol-nnov** [goreleaser/goreleaser#5204]
### Is your feature request related to a problem? Please describe.

I'd like packages of same type sit in separate directories under `dist`, so, I've made the following template:

```
nfpms:
  - id: first
    package_name: first-pkg
    file_name_template: "{{ .Format }}/{{ .ConventionalFileName }}"
...
  - id: second
    package_name: second-pkg
    file_name_template: "{{ .Format }}/{{ .ConventionalFileName }}"
...
```

But goreleaser fails with
```
release failed after 3s                  error=open dist/deb/first-pkg_0.0.0~gitnone_arm64.deb: no such file or directory
```

### Describe the solution you'd like

Create all needed directories under `dist` automatically during packaging.

### Describe alternatives you've considered

No alternatives came to my mind so far...

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Am I missing something obvious or such templates are, indeed, not supported?

It works for archives, but not for packages, interesting...
