### ISSUE TITLE
Regression: Incorrect architecture field value while packaging .deb for arm64

### ISSUE THREAD

**Issue by aol-nnov** [goreleaser/goreleaser#5238]
### What happened?

.deb package file has incorrect suffix and corresponding `Architecture` field in debian metadata.

### How can we reproduce this?

Given the `.goreleaser.yaml` file:

```yaml
builds:
  - id: my-bin
    binary: my-bin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
 nfpms:
  - package_name: my-bin
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
```

And a commmand:  `goreleaser --snapshot --clean` which yields among other the following output:

```bash
  • linux packages
    • creating                                       package=my-bin format=deb arch=arm64v8.0 file=dist/my-bin_0.0.0~SNAPSHOT-none_arm64v8.0.deb
    • creating                                       package=my-bin format=deb arch=arm6 file=dist/my-bin_0.0.0~SNAPSHOT-none_armhf.deb
    • creating                                       package=my-bin format=deb arch=amd64v1 file=dist/my-bin_0.0.0~SNAPSHOT-none_amd64.deb
```

If we unpack `dist/my-bin_0.0.0~gitnone_arm64v8.0.deb` to inspect Debian metadata, we'll see erroneous value of `Architecture` field:

```
Package: my-bin
Version: 0.0.0~SNAPSHOT-none
Section:
Priority: optional
Architecture: arm64v8.0
```

Per [Debian wiki](https://wiki.debian.org/SupportedArchitectures) correct value is `arm64`

### goreleaser version

```bash
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v2.3.3-0.20241028110116-f92937b2a96f
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.2
Compiler:      gc
ModuleSum:     h1:+Wp1XVLlD9WJq5Po9OQLHq9dSj9sAPbHjQPKTG5ZUz0=
Platform:      darwin/amd64
```

Versions I've checked so far (2.1.0 - 2.3.2 and `v2@latest` ) work as expected and set `Architecture` field to the correct value of `arm64`
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_
