### ISSUE TITLE
Ko package can't use complex environment variables 

### ISSUE THREAD

**Issue by drewgonzales360** [goreleaser/goreleaser#5247]
### What happened?

I would expect that when `ko.env` is evaluated, it uses the same template variables as when `build.env` is evaluated. Instead, I get 

```
error=template: failed to apply "CGO_ENABLED={{ if eq .Arch \"amd64\" }}1{{ else }}0{{ end }}": map has no entry for key "Arch"
```

### How can we reproduce this?

To reproduce this, create these two files, then run `go run github.com/goreleaser/goreleaser/v2@v2.4.4 release --snapshot --clean`

<details>
<summary>.goreleaser.yaml</summary>

```yaml
project_name: hello-world
version: 2

builds:
  - id: hello-world
    env:
    # .Arch should be available when ko uses this build
    # set up
    - CGO_ENABLED={{ if eq .Arch "amd64" }}1{{ else }}0{{ end }}
    goos:
      - linux
    goarch:
      - arm64
      - amd64

kos:
  - id: hello-world
    build: hello-world
    repository: docker.io/drewgonzales360/hello-world
    base_image: alpine
    platforms:
      - linux/arm64
      - linux/amd64
```
</details>

<details>
<summary>main.go</summary>

```go
package main

import "fmt"

func main() {
  fmt.Println("Hello world")
}
```

</details>

This should output

```
  • skipping announce, publish and validate...
  • cleaning distribution directory
  • loading environment variables
    • using token from  $GITLAB_TOKEN 
  • getting and validating git state
    • git state                                      commit=ce68a7748228068568f817e59b87636223c9f011 branch=drew/install-instructions current_tag=v0.3.2 previous_tag=v0.3.1 dirty=true
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=0.3.2-SNAPSHOT-ce68a77
  • ensuring distribution directory
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • building                                       binary=dist/hello-world_darwin_arm64_v8.0/hello-world
  • archives
    • creating                                       archive=dist/hello-world_0.3.2-SNAPSHOT-ce68a77_darwin_arm64.tar.gz
  • calculating checksums
  • ko
  ⨯ release failed after 1s                  error=template: failed to apply "CGO_ENABLED={{ if eq .Arch \"amd64\" }}1{{ else }}0{{ end }}": map has no entry for key "Arch"
exit status 1
```

### goreleaser version

```bash
❯ go run github.com/goreleaser/goreleaser/v2@v2.4.4 --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    v2.4.4
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.1
Compiler:      gc
ModuleSum:     h1:rnBXKmcA3BXBUVBw9u+ExyxOtrXGLhVjggYuDs31NkI=
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm not sure if this is expected behavior. In goreleaser 1.26, we are able to use the templated information in the builds.
