### ISSUE TITLE
Support Sources AUR (!= archlinux format)

### ISSUE THREAD

**Issue by ldez** [goreleaser/goreleaser#5278]
### Is your feature request related to a problem? Please describe.

I know there is the `archlinux` format for `nfpms`.

EDIT: I removed the previous description because I was misled by my own commit message error... Sorry.

### Describe the solution you'd like

Currently, only pre-compiled packages (`-bin`) are supported.

I think it's possible to use the [source archive](https://goreleaser.com/customization/source/) to create a package from sources.

As a user should respect the difference between `-bin` or not, I think a new "type" can be introduced to be sure that only sources are used in this context.

Something like that:

```yml
aurs:
  -
    git_url: "ssh://aur@aur.archlinux.org/foo-bin.git"
    # ...
  -
    git_url: "ssh://aur@aur.archlinux.org/foo.git"
    type: "source"
    # ...
```

```go
ctx.Artifacts.Filter(artifact.ByType(artifact.UploadableSourceArchive))
```

Also, some extra configurations can be required:

```yml
aurs:
  -
    git_url: "ssh://aur@aur.archlinux.org/foo.git"
    type: "source"
    # ...
    makedepends: ...
    prepare: ...
    build: ...
    package: ...
```

ref: https://wiki.archlinux.org/title/Creating_packages

This is just a raw idea, and I don't know the architecture of goreleaser, maybe there is a better way than the `type` field.

### Describe alternatives you've considered

Uses `archlinux` format?

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

To be able to publish automatically [nfpm](https://aur.archlinux.org/packages/nfpm) and [nfpm-bin](https://aur.archlinux.org/packages/nfpm-bin).

**Comment by caarlos0** [comment]
I think your `type: source` idea is ok, but I would make the source-specific fields in a subtype, something like:

```yaml
aurs:
  -
    git_url: "ssh://aur@aur.archlinux.org/foo.git"
    type: "source"
    # ...
    source:
      makedepends: ...
      prepare: ...
      build: ...
    # ...
    package: ...
```

at which point we might even drop the `type: source` thing, and assume that if `makedepends`, `prepare`, and/or `build` are set, this is of type source. 🤔

**Comment by ldez** [comment]
> at which point we might even drop the type: source thing, and assume that if makedepends, prepare, and/or build are set, this is of type source

We also can assume that the 2 git repos are "linked" by the name `foo-bin` `foo`.

```yml
aurs:
  -
    homepage: "https://example.com/"
    description: "Software to create fast and easy drum rolls."
    maintainers:
      - "Foo Bar <foo at bar dot com>"
    contributors:
      - "Foo Zaz <foo at zaz dot com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    skip_upload: true
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "pkgbuild updates"
    git_url_template: "ssh://aur@aur.archlinux.org/mypackage{{.Suffix}}.git"
    git_ssh_command: "ssh -i {{ .Env.KEY }} -o SomeOption=yes"
    ## Bin only
    bin:
      name: package-bin
      ids:
        - foo
        - bar
      provides:
        - mypackage
      conflicts:
        - otherpkg
      depends: ...
      optdepends: ...
      backup:
        - /etc/foo.conf
      package: ...
    ## Sources only
    sources:
      name: package
      ids:
        - foo
        - bar
      provides:
        - mypackage-bin
      conflicts:
        - otherpkg
      depends:
        - curl
      optdepends: ...
      backup:
        - /etc/foo.conf
      package: ...
      makedepends: ...
      prepare: ...
      build: ...
```
