### ISSUE TITLE
Getting Invalid object name 'warning' when attempting to release

### ISSUE THREAD

**Issue by daenney** [goreleaser/goreleaser#529]
### Prerequisites

* [X] Are you running the latest version?

I ran a `go install` just prior to issuing the command.

* [X] Did you perform a search to see if this problem was already reported?

All reports referencing "warning" do not seem to match this issue and nothing is matching the whole "Invalid object name 'warning'" message.

### Description

When attempting to release I get:

```
   • GENERATING CHANGELOG
   ⨯ release failed after 0.03s error=fatal: Invalid object name 'warning'.
```
Adding the `--debug` switch does not provide any additional information.

### Environment

Please paste the output of:

* `go version`: `go version go1.9.2 linux/amd64`
* `uname -a`: `Linux monoceros 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux`
* `goreleaser --debug`:

```
14:47:56 ~/D/g/s/g/h/hemtjanst (master) $ goreleaser --debug

   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loaded config file        config={ { %!s(bool=false) %!s(bool=false) } { { }     []  []   %!s(bool=false) } [{[windows darwin linux] [amd64 arm] [6 7] [] ./cmd/hemtjanst/main.go   hemtjanst { } []}] { map[]  [{windows zip}] %!s(bool=false) [LICENSE README.md CHANGELOG.md]} { map[] [] [] []       map[]} { map[]      map[]} {} {} [] [] {{[]} }  { []  } {[] [] [] []     { } []} {  }}
   • parallelism: 4           
   • SETTING DEFAULTS FOR:
      • snapshoting              
      • releasing to GitHub      
      • creating archives        
      • building binaries        
      • creating Linux packages with fpm
      • creating Linux packages with snapcraft
      • calculating checksums    
      • signing artifacts        
      • creating Docker images   
      • releasing to Artifactory 
      • creating homebrew formula
   • CHECKING ./DIST  
      • ./dist doesn't exist, creating empty folder
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.2.0, commit 90fd424a8e93eda73fe32c3741719140a6714626
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG
   ⨯ release failed after 0.04s error=fatal: Invalid object name 'warning'.

```
* Content of `dist/config.yaml`:

```
project_name: hemtjanst
release:
  github:
    owner: hemtjanst
    name: hemtjanst
  name_template: '{{.Tag}}'
brew:
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  install: bin.install "hemtjanst"
builds:
- goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm
  goarm:
  - "6"
  - "7"
  main: ./cmd/hemtjanst/main.go
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: hemtjanst
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE
  - README.md
  - CHANGELOG.md
fpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
```

### Steps to Reproduce

1. Check out github.com/hemtjanst/hemtjanst
2. `goreleaser`

**Expected behavior:** It releases, like it has done in the past

**Actual behavior:** It errors out with the above error message
