### ISSUE TITLE
Cannot override ldflags

### ISSUE THREAD

**Issue by andig** [goreleaser/goreleaser#5322]
### What happened?

Trying to fix https://github.com/evcc-io/evcc/issues/17251 according to https://github.com/golang/go/issues/68678#issuecomment-2447965386 I need to define linker flags. Per https://github.com/orgs/goreleaser/discussions/5321 I'm trying to user `override` for MacOS:

```yaml
builds:
  - id: evcc
    main: .
    flags:
      - -trimpath
      - -tags=release
    ldflags:
      - -X github.com/evcc-io/evcc/server.Version={{ .Version }} -X github.com/evcc-io/evcc/vehicle/tesla.TESLA_CLIENT_ID={{ .Env.TESLA_CLIENT_ID }} -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    overrides:
      - goos: darwin
        ldflags:
          - -B gobuildid
```

Using `ps aux` I can see that the override does apparently not trigger:

    go build -trimpath -tags=release -ldflags=-X github.com/evcc-io/evcc/server.Version=0.131.7-next -X github.com/evcc-io/evcc/vehicle/tesla.TESLA_CLIENT_ID=foo -s -w -o /Users/andig/htdocs/evcc/release/evcc_darwin_arm64_v8.0/evcc .

but it is present in the build config:

```
  • building binaries
    • building                                       build={evcc [darwin] [arm64] [v1] [sse2] [6] [v8.0] [hardfloat] [power8] [rva20u64] [darwin_arm64_v8.0] [{windows arm       } {windows arm64       }] . . evcc {[] []} go   go build  false   { [-X github.com/evcc-io/evcc/server.Version={{ .Version }} -X github.com/evcc-io/evcc/vehicle/tesla.TESLA_CLIENT_ID={{ .Env.TESLA_CLIENT_ID }} -s -w] [] [-trimpath -tags=release] [] [] [CGO_ENABLED=0]} [{darwin         { [-B gobuildid] [] [] [] [] []}}]}
```

### How can we reproduce this?

https://github.com/evcc-io/evcc, build using

    TESLA_CLIENT_ID=foo goreleaser --snapshot --clean --verbose

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    2.4.8
GitCommit:     377981ebd76e1bbb0dbe07d5428239ec8c5381a8
GitTreeState:  clean
BuildDate:     2024-11-22T12:56:52
BuiltBy:       homebrew
GoVersion:     go1.23.3
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
