### ISSUE TITLE
support for cargo publish

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#5343]
for 2.6, probably

**Comment by caarlos0** [comment]
i wonder if here it would be enough to add a tutorial on how to use custom publishers to do this?

it would basically look something like this:

```yaml
publishers:
  - name: cargo
    cmd: "cargo publish {{ with .Snapshot }}--dry-run{{ end }} --quiet --no-verify --all-features --etc"
```

cc/ @vedantmgoyal9 wdyt?
