### ISSUE TITLE
failed to find files to archive: globbing failed for pattern none*

### ISSUE THREAD

**Issue by ryancurrah** [goreleaser/goreleaser#5361]
### What happened?

Unable to create an archive with just the binary on Go Releaser v2.4.4-pro, I get an error saying that `none*` does not exist.

I'm following the instructions here: https://goreleaser.com/customization/archive/#packaging-only-the-binaries

```console
goreleaser check
  • by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • running goreleaser v2.4.4-pro (outdated, latest is v2.4.8-pro)
    • importing .goreleaser.common.yml
  • checking                                         path=.goreleaser.yml
  • pipe skipped                                     reason=release is disabled
  • 1 configuration file(s) validated
  • thanks for using goreleaser-pro!
```

### How can we reproduce this?

`.goreleaser.common.yml`

```yaml
version: 2
snapshot:
    version_template: '{{ .Version }}'
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
    algorithm: sha256
changelog:
    disable: true
archives:
    - id: binary
      format: binary
release:
    disable: true
```

`.goreleaser.yml`

```yaml
version: 2
includes:
  - from_file:
      path: .goreleaser.common.yml
project_name: workspace
builds:
  - id: workspace-server
    main: ./cmd/workspace/server/
    binary: workspace-server
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
  - id: workspace-client
    main: ./cmd/workspace/client/
    binary: workspace-client
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: workspace-server
    builds:
      - workspace-server
    name_template: '{{ replace .Binary "_" "-" }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - none*
  - id: workspace-client
    builds:
      - workspace-client
    name_template: '{{ replace .Binary "_" "-" }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - none*
```

```console
goreleaser release  --clean --snapshot

  • by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • running goreleaser v2.4.4-pro (outdated, latest is v2.4.8-pro)
  • skipping license check on snapshot
    • importing .goreleaser.common.yml
  • skipping announce, publish and validate...
  • cleaning distribution directory
  • loading environment variables
  • getting and validating git state
    • couldn't find any tags before "v0.0.0"
    • git state                                      commit=e9a28a5995cf651808e67f40be8f6d4ac383ed60 branch=initial-implemenation current_tag=v0.0.0 previous_tag=<unknown> dirty=true
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
    • pipe skipped                                   reason=release is disabled
  • snapshotting
    • building snapshot...                           version=0.0.0
  • ensuring distribution directory
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • building                                       binary=dist/workspace-server_linux_arm64_v8.0/workspace-server
    • building                                       binary=dist/workspace-server_linux_amd64_v1/workspace-server
    • building                                       binary=dist/workspace-server_darwin_amd64_v1/workspace-server
    • building                                       binary=dist/workspace-server_darwin_arm64_v8.0/workspace-server
    • building                                       binary=dist/workspace-client_linux_amd64_v1/workspace-client
    • building                                       binary=dist/workspace-client_linux_arm64_v8.0/workspace-client
    • building                                       binary=dist/workspace-client_darwin_amd64_v1/workspace-client
    • building                                       binary=dist/workspace-client_darwin_arm64_v8.0/workspace-client
  • archives
    • creating                                       archive=dist/workspace-server_0.0.0_Linux_x86_64.tar.gz
    • creating                                       archive=dist/workspace-server_0.0.0_Darwin_x86_64.tar.gz
    • creating                                       archive=dist/workspace-server_0.0.0_Darwin_arm64.tar.gz
    • creating                                       archive=dist/workspace-server_0.0.0_Linux_arm64.tar.gz
    • creating                                       archive=dist/workspace-client_0.0.0_Linux_x86_64.tar.gz
    • creating                                       archive=dist/workspace-client_0.0.0_Darwin_arm64.tar.gz
    • creating                                       archive=dist/workspace-client_0.0.0_Linux_arm64.tar.gz
    • creating                                       archive=dist/workspace-client_0.0.0_Darwin_x86_64.tar.gz
    • skip archiving                                 binary=workspace-server name=workspace-server_0.0.0_linux_arm64
    • skip archiving                                 binary=workspace-server name=workspace-server_0.0.0_linux_amd64
    • skip archiving                                 binary=workspace-client name=workspace-client_0.0.0_linux_amd64
    • skip archiving                                 binary=workspace-client name=workspace-client_0.0.0_linux_arm64
    • skip archiving                                 binary=workspace-server name=workspace-server_0.0.0_darwin_amd64
    • skip archiving                                 binary=workspace-client name=workspace-client_0.0.0_darwin_amd64
    • skip archiving                                 binary=workspace-server name=workspace-server_0.0.0_darwin_arm64
    • skip archiving                                 binary=workspace-client name=workspace-client_0.0.0_darwin_arm64
  ⨯ release failed after 3s                          error=failed to find files to archive: globbing failed for pattern none*: glob failed: open test/output: no such file or directory
```

### goreleaser version

```bash
goreleaser --version
  ____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com/pro

GitVersion:    2.4.4-pro
GitCommit:     47773750ff6a1889663b95df5ea7eadd15466d99
GitTreeState:  clean
BuildDate:     2024-11-05T02:13:12Z
BuiltBy:       goreleaser
GoVersion:     go1.23.2
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
