### ISSUE TITLE
Duplicate packages being created when attempting to package a go and rust build together

### ISSUE THREAD

**Issue by fach** [goreleaser/goreleaser#5371]
### What happened?

While testing out the rust build support in the nightly, I noticed when attempting to package a go and rust binary together in the same rpm/deb package, it appears two packages are created (one for the go binary and another with the rust binary) with the same name and one is overwritten in`dist/`.

My expectation would be both binaries would be placed in the same deb/rpm package.

packaging logs:
```
• linux packages
    • adding artifact to package                     package=combined format=rpm arch=amd64 src=dist/cli_x86_64-unknown-linux-gnu/cli dst=/usr/local/bin/cli type=Binary
    • all archive files                              package=combined format=rpm arch=amd64 files=[/usr/local/bin/cli]
    • creating                                       package=combined format=rpm arch=amd64 file=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.rpm
    • adding artifact to package                     package=combined format=rpm arch=amd64v1 src=dist/service1_linux_amd64_v1/service1 dst=/usr/local/bin/service1 type=Binary
    • all archive files                              package=combined format=rpm arch=amd64v1 files=[/usr/local/bin/service1]
    • creating                                       package=combined format=rpm arch=amd64v1 file=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.rpm
    • adding artifact to package                     package=combined format=deb arch=amd64v1 src=dist/service1_linux_amd64_v1/service1 dst=/usr/local/bin/service1 type=Binary
    • all archive files                              package=combined format=deb arch=amd64v1 files=[/usr/local/bin/service1]
    • adding artifact to package                     package=combined format=deb arch=amd64 src=dist/cli_x86_64-unknown-linux-gnu/cli dst=/usr/local/bin/cli type=Binary
    • all archive files                              package=combined format=deb arch=amd64 files=[/usr/local/bin/cli]
    • creating                                       package=combined format=deb arch=amd64 file=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.deb
    • creating                                       package=combined format=deb arch=amd64v1 file=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.deb
    • added new artifact                             name=combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.rpm type=Linux Package path=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.rpm
    • added new artifact                             name=combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.rpm type=Linux Package path=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.rpm
    • added new artifact                             name=combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.deb type=Linux Package path=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.deb
    • added new artifact                             name=combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.deb type=Linux Package path=dist/combined_0.0.1-SNAPSHOT-9740fc0_linux_amd64.deb
```

### How can we reproduce this?

```
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: service1
    main: service1/main.go
    binary: service1
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: cli
    builder: rust
    tool: cargo
    binary: cli
    targets:
      - x86_64-unknown-linux-gnu
    dir: cli/
    command: build
    env:
      - RUSTFLAGS=-C linker=x86_64-linux-gnu-gcc

archives:
  - id: service_archive
    format: binary
    builds:
      - service1
      - cli  
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: combined
    package_name: combined
    builds:
      - service1
      - cli
    vendor: blah
    homepage: blah.com
    maintainer: blah <blah@blah.com>
    description: |-
      service client and cli
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    release: 1
    section: default

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

      ```

### goreleaser version

```bash
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Release engineering, simplified.
https://goreleaser.com

GitVersion:    v2.4.9-0.20241213173047-8872f00467de
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.3
Compiler:      gc
ModuleSum:     h1:0XZkUe1xg+qUgZaOjHwxiOkCWbOWRLPqoj2+CXaayAQ=
Platform:      linux/arm64
```
```


### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_
