### ISSUE TITLE
Unable to set make_latest using environment variable

### ISSUE THREAD

**Issue by duberton** [goreleaser/goreleaser#5418]
Hello! It seems that attempting to set **make_latest** based on an environment variable isn't working as expected. Should this work?

```
version: 2

project_name: gh-actions

release:
  github:
    owner: duberton
    name: gh-actions
  draft: false
  prerelease: false
  make_latest: "{{ .Env.GORELEASER_MAKE_LATEST }}"
```

Action call:

```
- name: GoReleaser
  uses: goreleaser/goreleaser-action@v6
  with:
    distribution: goreleaser
    version: '~> v2'
    args: release --clean --verbose
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    GITHUB_SHA: ${{ github.sha }}
    GORELEASER_CURRENT_TAG: ${{ steps.v1-tag.outputs.new_tag }}
    GORELEASER_MAKE_LATEST: false
```
