### ISSUE TITLE
WiX Toolset Extensions

### ISSUE THREAD

**Issue by bencurio** [goreleaser/goreleaser#5427]
### Is your feature request related to a problem? Please describe.

I would like to use UI using the Wix Toolset with an extension called WixUIExtension. Unfortunately I cannot do this as there is no way to enable extensions.

Error:
```console
  ⨯ release failed after 18s                 error=msi: exit status 94: Windows Installer XML Toolset Linker version 3.14.1.8722
Copyright (c) .NET Foundation and contributors. All rights reserved.

D:\Workspace\githost\orgname\artifactname\dist\windows_amd64_v1\msi\artifactname-x64\artifactname-x64.wxs(101) : error LGHT0094 : Unresolved reference to symbol 'WixUI:WixUI_InstallDir' in section 'Product:*'.
```

Example Config:
```xml
<Directory Id="TARGETDIR" Name="SourceDir">
  <Directory Id="ProgramFilesFolder" Name="PFiles">
    <Directory Id="TESTFILEPRODUCTDIR" Name="Test File">
      ...
    </Directory>
   </Directory>
</Directory>
...
<Property Id="WIXUI_INSTALLDIR" Value="TESTFILEPRODUCTDIR" />
<UIRef Id="WixUI_InstallDir" />
```

Reference: https://wixtoolset.org/docs/v3/wixui/dialog_reference/wixui_installdir/

### Describe the solution you'd like

One solution might be to specify in the configuration which built-in extensions you want to use, such as:
```yaml
# [...]
msi:
  - id: msi
    ids: [windows]
    name: "{{ .ProjectName }}-{{ .MsiArch }}"
    wxs: ./windows/Package.wsx
    ext:
      - WixUIExtension
      - WixUtilExtension
      - "C:\\My WiX Extensions\\FooExtension.dll"
      - ...
      # @see https://wixtoolset.org/docs/v3/howtos/general/extension_usage_introduction/
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
```

The command should run like this:
```cmd
light.exe -ext WixUIExtension -ext WixUtilExtension -ext [...] .\artifactname-arch.wixobj -out artifactname.msi
```

### Describe alternatives you've considered

Since it is not currently possible to specify extensions in the [MSI configuration](https://goreleaser.com/customization/msi/), a separate CI job would have to be created independently of GoReleaser, which would perform the MSI build separately.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bencurio** [comment]
Workaround:

- Rename `light.exe` to `light_.exe`.
- Create following `light.bat` file:

```cmd filename="light.bat"
@echo off
light_.exe -ext WixUIExtension %*
```

I first tried with environmental variables, but unfortunately that doesn't pass.

**Comment by caarlos0** [comment]
ah, that's a nice addition indeed! gonna work on it for v2.6 (due sometime this month).

**Comment by bencurio** [comment]
> ah, that's a nice addition indeed! gonna work on it for v2.6 (due sometime this month).

Thank you for the quick response and for considering this enhancement! I really appreciate it, and I'm looking forward to the upcoming v2.6 release.

**Comment by bencurio** [comment]
🗒️ On Linux, `wixl` uses `--ext` with a double dash, while on Windows, `light` uses `-ext` with a single dash.

**Comment by francesco-furlan** [comment]
hey folks! I still get `error CNDL0200 : The Component element contains an unhandled extension element 'util:EventSource'.  Please ensure that the extension for elements in the 'http://schemas.microsoft.com/wix/UtilExtension' namespace has been provided.` could it be that the extension is missing from `candle`?

**Comment by bencurio** [comment]
👋 It seems that based on the [documentation here](https://wixtoolset.org/docs/v3/xsd/util/eventsource/), you need the `WixUtilExtension`. Does the error persist even after enabling it?

For example:

```yml
msi:
  - # [...]
    extensions:
      - WixUtilExtension
```

Additional information: On Linux, the options for extensions are very limited. Some people use Wine, but it’s quite problematic. Using a Windows-based runner is the best approach.
