### ISSUE TITLE
build windows_amd64_v1 and linux_amd64_v1 failed

### ISSUE THREAD

**Issue by chaunsin** [goreleaser/goreleaser#5429]
### What happened?

hello！
I failed to build windows_amd64_v1 and linux_amd64_v1 locally

### os
```shell
uname -a
Darwin MacBook-Pro-5.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

### go env
```
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/edy/Library/Caches/go-build'
GOENV='/Users/edy/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/edy/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/edy/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/Users/edy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/edy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-amd64/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.23.3'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/edy/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/d2/b3x_gdyn3q3c0p4fn_tn4_fm0000gn/T/go-build984441015=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### .goreleaser.yaml

```yaml
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    # - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    dir: ./go/nocgo/
    main: main.go
    binary: nocgo
    ldflags:
      - -s -w -X main.Version={{.Version}} main.Commit={{.ShortCommit}} main.BuildTime={{.CommitDate}}

    goos:
      - windows
      - linux

    # Default: [ '386', 'amd64', 'arm64' ]
    goarch:
      - amd64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

```

### I test compile code without cgo

<img width="474" alt="image" src="https://github.com/user-attachments/assets/1ce31205-0c02-43b6-a5ad-9f1e2b477d5b" />

/go/nocgo/main.go
```go
package main

import "fmt"

var (
	Version   string
	Commit    string
	BuildTime string
)

func main() {
	fmt.Printf("Version: %s\nCommit: %s\nBuildTime: %s\n", Version, Commit, BuildTime)
	fmt.Println("hello nocgo!")
}

```

### Execution result
```shell
 goreleaser release --snapshot --clean --verbose
  • verbose output enabled
  • using configuration                              path=.goreleaser.yaml
  • parallelism: 8
  • skipping announce, publish and validate...
  • cleaning distribution directory
  • loading environment variables
  • getting and validating git state
    • git command result                             args=[-c log.showSignature=false rev-parse --is-inside-work-tree] stdout=true stderr=
    • git command result                             args=[-c log.showSignature=false rev-parse --is-inside-work-tree] stdout=true stderr=
    • git command result                             args=[-c log.showSignature=false rev-parse --abbrev-ref HEAD --quiet] stdout=master stderr=
    • git command result                             args=[-c log.showSignature=false show --format=%h HEAD --quiet] stdout=aded03e stderr=
    • git command result                             args=[-c log.showSignature=false show --format=%H HEAD --quiet] stdout=aded03e0d638a83d7e00af8bddf70dee60554136 stderr=
    • git command result                             args=[-c log.showSignature=false rev-list --max-parents=0 HEAD] stdout=b80a6db97d479a76c581bdaf795e0ac6cfc0ee96
79c3d64cf8162a9a9f5393db4b142b48864d16ad
42e3f8a54c98e24e144be7cf65f3a17bdd6f42cc
1edb9e4b7cc82c5d064868c2bd1049462f185a72 stderr=
    • git command result                             args=[-c log.showSignature=false show --format='%ct' HEAD --quiet] stdout='1734362477' stderr=
    • git command result                             args=[-c log.showSignature=false describe --always --dirty --tags] stdout=aded03e-dirty stderr=
    • git command result                             args=[-c log.showSignature=false ls-remote --get-url] stdout=git@github.com:chaunsin/github-test.git stderr=
    • git command result                             args=[-c log.showSignature=false tag --points-at HEAD --sort -version:refname] stdout= stderr=
    • git command result                             args=[-c log.showSignature=false describe --tags --abbrev=0 HEAD] stdout= stderr=fatal: No names found, cannot describe anything.
    • ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
    • git state                                      commit=aded03e0d638a83d7e00af8bddf70dee60554136 branch=master current_tag=v0.0.0 previous_tag=<unknown> dirty=false
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
    • git command result                             args=[-c log.showSignature=false rev-parse --is-inside-work-tree] stdout=true stderr=
    • git command result                             args=[-c log.showSignature=false ls-remote --get-url] stdout=git@github.com:chaunsin/github-test.git stderr=
    • got git url                                    rawurl=git@github.com:chaunsin/github-test.git
    • parsed url                                     owner=chaunsin name=github-test
    • pre-release for tag v0.0.0 set to false
    • git command result                             args=[-c log.showSignature=false rev-parse --is-inside-work-tree] stdout=true stderr=
    • git command result                             args=[-c log.showSignature=false ls-remote --get-url] stdout=git@github.com:chaunsin/github-test.git stderr=
    • got git url                                    rawurl=git@github.com:chaunsin/github-test.git
    • parsed url                                     owner=chaunsin name=github-test
    • git command result                             args=[-c log.showSignature=false config gpg.program] stdout= stderr=
    • git command result                             args=[-c log.showSignature=false config gpg.program] stdout= stderr=
  • skipped partial
  • snapshotting
    • building snapshot...                           version=0.0.0-SNAPSHOT-aded03e
  • skipped running before hooks
  • ensuring distribution directory
    • dist doesn't exist, creating empty directory
  • setting up metadata
  • writing release metadata
    • writing                                        path=dist/metadata.json
    • added new artifact                             name=metadata.json type=Metadata path=dist/metadata.json
  • loading go mod information
    • pipe skipped                                   reason=not a go module
  • build prerequisites
  • skipped checking go.mod
  • skipped proxying go module
  • writing effective configuration                  path=dist/config.yaml
  • building binaries
    • building                                       build={github-test [windows linux] [amd64] [v1] [sse2] [6] [v8.0] [hardfloat] [power8] [rva20u64] [windows_amd64_v1 linux_amd64_v1] [] ./go/nocgo/ main.go nocgo {[] []} go    go build  false   { [-s -w -X main.Version={{.Version}} main.Commit={{.ShortCommit}} main.BuildTime={{.CommitDate}}] [] [] [] [] [CGO_ENABLED=0]} []}
    • building                                       binary=dist/github-test_linux_amd64_v1/nocgo
    • building                                       binary=dist/github-test_windows_amd64_v1/nocgo.exe
    • env "CGO_ENABLED=0" evaluated to "CGO_ENABLED=0"
    • env "CGO_ENABLED=0" evaluated to "CGO_ENABLED=0"
    • running
    • running
  ⨯ release failed after 1s                  error=build failed: failed to build for linux_amd64_v1: exit status 1: # command-line-arguments
usage: link [options] main.o
  -B note
        set ELF NT_GNU_BUILD_ID note or Mach-O UUID; use "gobuildid" to generate it from the Go build ID
  -E entry
        set entry symbol name
  -H type
        set header type
  -I linker
        use linker as ELF dynamic linker
  -L directory
        add specified directory to library path
  -R quantum
        set address rounding quantum (default -1)
  -T int
        set the start address of text symbols (default -1)
  -V    print version and exit
  -X definition
        add string value definition of the form importpath.name=value
  -a    no-op (deprecated)
  -asan
        enable ASan interface
  -aslr
        enable ASLR for buildmode=c-shared on windows (default true)
  -benchmark string
        set to 'mem' or 'cpu' to enable phase benchmarking
  -benchmarkprofile base
        emit phase profiles to base_phase.{cpu,mem}prof
  -bindnow
        mark a dynamically linked ELF object for immediate function binding
  -buildid id
        record id as Go toolchain build id
  -buildmode mode
        set build mode
  -c    dump call graph
  -capturehostobjs string
        capture host object files loaded during internal linking to specified dir
  -checklinkname
        check linkname symbol references (default true)
  -compressdwarf
        compress DWARF if possible (default true)
  -cpuprofile file
        write cpu profile to file
  -d    disable dynamic executable
  -debugnosplit
        dump nosplit call graph
  -debugtextsize int
        debug text section max size
  -debugtramp int
        debug trampolines
  -dumpdep
        dump symbol dependency graph
  -extar string
        archive program for buildmode=c-archive
  -extld linker
        use linker when linking in external mode
  -extldflags flags
        pass flags to external linker
  -f    ignore version mismatch
  -g    disable go package data checks
  -h    halt on error
  -importcfg file
        read import configuration from file
  -installsuffix suffix
        set package directory suffix
  -k symbol
        set field tracking symbol
  -libgcc string
        compiler support lib for internal linking; use "none" to disable
  -linkmode mode
        set link mode
  -linkshared
        link against installed Go shared libraries
  -memprofile file
        write memory profile to file
  -memprofilerate rate
        set runtime.MemProfileRate to rate
  -msan
        enable MSan interface
  -n    no-op (deprecated)
  -o file
        write output to file
  -pluginpath string
        full path name for plugin
  -pruneweakmap
        prune weak mapinit refs (default true)
  -r path
        set the ELF dynamic linker search path to dir1:dir2:...
  -race
        enable race detector
  -randlayout int
        randomize function layout
  -s    disable symbol table
  -strictdups int
        sanity check duplicate symbol contents during object file reading (1=warn 2=err).
  -tmpdir directory
        use directory for temporary files
  -v    print link trace
  -w    disable DWARF generation

target: linux_amd64_v1

```

`windows_amd64_v1` also reports an error

I can compile it manually
```shelll
$ pwd
/Users/edy/code/github-test/go/nocgo
$ CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v1 go build main.go
```
detail
```shell
$ go version -m main.exe 
main.exe: go1.23.3
        path    command-line-arguments
        build   -buildmode=exe
        build   -compiler=gc
        build   CGO_ENABLED=0
        build   GOARCH=amd64
        build   GOOS=windows
        build   GOAMD64=v1
```

Ask for help. Thank you.

### How can we reproduce this?

goreleaser release --snapshot --clean --verbose

### goreleaser version

```bash
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Release engineering, simplified.
https://goreleaser.com

GitVersion:    v2.5.1
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.23.3
Compiler:      gc
ModuleSum:     h1:c94/danKV3hwyX28Sg4mY+jtJYxW9BEJq5RpSLN7b0c=
Platform:      darwin/amd64
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
