### ISSUE TITLE
Add archive format instead of overriding it

### ISSUE THREAD

**Issue by klaernie** [goreleaser/goreleaser#5436]
### Is your feature request related to a problem? Please describe.

In [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) we recently started using goreleaser. 

One of the historic manual release process caveats is that we used to only provide .tar.gz archives, but later got asked to provide .zip archives for our windows users, since this obscure distribution has (or at least had at the time) no native support for .tar.gz. Using our previous manual process it was fairly easy to just create another compression step to build an additional archive with zip. This meant, that for the last couple releases we provided .tar.gz archives for all platforms, including windows, plus an additional archive with the windows build as a zip. 

In the process of migrating to goreleaser I opted for the well documented pattern of building an archive defaulting to .tar.gz and overriding the format for `goos: windows`. This of course means, that we no longer generate a .tar.gz for windows. Unfortunately we have integrations into multiple language infrastructures to run our (Javascript, PHP, Python, GitHub Actions) which all will need adjusting. Since I missed this during the first release using goreleaser, our users rightfully complained that the integrations no longer work, since they expected a .tar.gz under windows, which was not present in our releases.

So I resorted to duplicating the archive definition in order to provide both archives types.
But with this we now also have releases in zip format for all non-windows platforms, which use disk space and make the already extensive list of archives more cumbersome for users not knowing exactly what they are looking for.

### Describe the solution you'd like

Ideally I'd like specify for a `format_override` that the override should be generated in addition, not as a replacement. This way one would only need one instance under `archive:` , adding `format_overrides:` for each additional format needed.

Example how a  config doing this could look like (the last line is the example):
```yaml
archives:
  - id: archive-ec
    builds:
      - ec-compat
    format: tar.gz
    name_template: >-
      ec-{{- .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
        add_format: true
```

If that approach is not suitable, I think an option to restrict archives to specific platforms would be nice option too.

### Describe alternatives you've considered

I have not seen an option to restrict archives to a singular platform.
I did consider to add an additional build restricted to the windows platform we would like a zip file for, duplicating the build but reducing the build matrix to the GOOS and GOARCH needed in the zip, then duplicating the archive for only this build, and excluding it from the nfpms and docker steps.

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Our .goreleaser.yaml: https://github.com/editorconfig-checker/editorconfig-checker/blob/main/.goreleaser.yaml
As probably valuable information for reading it: we are currently gearing up to replace the binary name we distribute from `ec` to `editorconfig-checker` in our next major release. So we are currently building the binary twice, once with each name, and are building archives for both names using a different name template.

**Comment by caarlos0** [comment]
I think a better solution would be to make `format` accept an array:

```yaml
archives:
  - id: archive-ec
    builds:
      - ec-compat
    formats: [ 'tar.gz' ]
    name_template: >-
      ec-{{- .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' 'tar.gz' ]
```


that way is more future proof I guess 🤔
