### ISSUE TITLE
Support builds' `binary` option in `universal_binaries`

### ISSUE THREAD

**Issue by fkorotkov** [goreleaser/goreleaser#5460]
### Is your feature request related to a problem? Please describe.

Right now I'm building a macOS `.app` with GoReleaser. In order for it to properly work we need to have a special structure inside an `archive`:

```yaml
universal_binaries:
  - replace: true
    hooks:
      post: gon gon.hcl

archives:
  - name_template: "{{ .ProjectName }}"
    files:
      - src: Resources/embedded.provisionprofile
        dst: tart.app/Contents
        strip_parent: true
      - src: Resources/Info.plist
        dst: tart.app/Contents
        strip_parent: true
      - src: Resources/AppIcon.png
        dst: tart.app/Contents/Resources
        strip_parent: true
      - LICENSE
```

I would love to put binary from the `universal_binaries` into `tart.app/Contents/MacOS/tart` within the archive. Right now `tart` binary is in the root of the archive.

### Describe the solution you'd like

`binary` field configuration within the `universal_binary`.

### Describe alternatives you've considered

Since we have the Pro version, I tried hooks for archives but wasn't able to make it work. Previously with different bianries for each architecture we had the follwoing `prebuilt` config:

```yaml
builds:
  - id: tart
    builder: prebuilt
    goamd64: [v1]
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    binary: tart.app/Contents/MacOS/tart
    prebuilt:
      path: '.build/{{- if eq .Arch "arm64" }}arm64{{- else }}x86_64{{ end }}-apple-macosx/release/tart'
```

`binary` field above did the trick for us.

### Search

- [x] I did search for other open and closed issues before opening this

### Supporter

- [x] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
