### ISSUE TITLE
support entitlements in macOS signing process

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#5464]
### Is your feature request related to a problem? Please describe.

we should support entitlements in the macOS signing feature

### Describe the solution you'd like

```yaml
notarize:
  macos:
    - sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
        entitlements: [ 'foo' 'bar' ]
```

### Describe alternatives you've considered

n/a

### Search

- [x] I did search for other open and closed issues before opening this

### Supporter

- [x] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Additional context

quill seems to support it
