### ISSUE TITLE
App Bundles feature: cannot unmarshal !!map into []config.AppBundle

### ISSUE THREAD

**Issue by Nibroc00** [goreleaser/goreleaser#5472]
### What happened?

Just upgraded to goreleaser v2.6.1-pro and wanted to use the new app_bundles feature but got an error saying 
```
nibroc@julius:~/PROJECT$ goreleaser check
  • by using this software you agree with its EULA, available at https://goreleaser.com/eula
  • running goreleaser v2.6.1-pro
  ⨯ command failed                                  
    error=
    │ failed to load configuration: yaml: unmarshal errors:
    │   line 160: cannot unmarshal !!map into []config.AppBundle
```
I'll drop my attempt at using app_bundles but I have tried removing more and more fields and templates from app_bundles to see if I could pinpoint the issue but to no avail. Having any of the subfields of app_bundle filled will cause this error. I also tried looking at the schema-pro.json to see if I could find my issue as well, which also lead to nothing.
```
app_bundles:
    id: PROJECT-app-bundles
    name: '{{ .ProjectName }}'
    # name: '{{ .ProjectName }}-{{ .Arch }}'
    ids:
      - PROJECT-archives
    if: '{{ eq .Os "darwin" }}'

    # Must be a `icns` file.
    icon: '{{ .Var.IconsetPath }}'
    bundle: com.PROJECT
    mod_timestamp: '{{ .CommitTimestamp }}'

    # Templates: allowed.
    extra_files:
      - src: '{{ .Var.IconsetPath }}'
        dst: Contents/Resources/iconfile.icns

    # Since: v2.6-unreleased.
    # Templates: allowed.
    # Extra template fields: `AppName`, `BinaryName`, and `Bundle`.
    templated_extra_files:
      - src: '{{ .Var.PlistPath }}'
        dst: Contents/Info.plist
```
Closest thing I could find in the issues was [here](https://github.com/goreleaser/goreleaser/issues/5460)

### How can we reproduce this?

1. Have a goreleaser file with a build and archive step
2. Add app_bundles: field with any of the sub fields filled in
3. Run `goreleaser release` or `goreleaser check`

### goreleaser version

```bash
____       ____      _                            ____
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __  |  _ \ _ __ ___
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__| | |_) | '__/ _ \
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |    |  __/| | | (_) |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|    |_|   |_|  \___/
goreleaser-pro: Release engineering, simplified.
https://goreleaser.com/pro

GitVersion:    2.6.1-pro
GitCommit:     6b3f8c7d383031ee7cdd4d8129bf5459c923ae8b
GitTreeState:  clean
BuildDate:     2025-01-22T11:12:23Z
BuiltBy:       goreleaser
GoVersion:     go1.23.5
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64
```

### GoReleaser Check

- [x] goreleaser check shows no errors

### Search

- [x] I did search for other open and closed issues before opening this

### Supporter

- [x] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Additional context

Apologies for checking "goreleaser check shows no errors" because that's a lie, but nothing I could do would remove the error.

**Comment by caarlos0** [comment]
Hey!

`app_bundles` is a list, so you need to do something like this instead:

```yaml
app_bundles:
  - # <----- make it a list
    id: PROJECT-app-bundles
    # etc ...
```
