### ISSUE TITLE
Make goos and goarch templated

### ISSUE THREAD

**Issue by mholt** [goreleaser/goreleaser#5505]
### Is your feature request related to a problem? Please describe.

I have a workflow that requires building only on the runner's actual OS + arch, i.e.:

```yaml
    goos:
      - '{{ .Runtime.Goos }}'
    goarch:
      - '{{ .Runtime.Goarch }}'
```

But this doesn't work 😦 (the templates don't get evaluated).

### Describe the solution you'd like

It would be _really nice_ if we could just evaluate templates in `goos` and `goarch`. Pretty please? 😃 

### Describe alternatives you've considered

Our workaround involves running `sed` in our workflow:

```yaml
      - name: Configure for Linux-only build
        if: matrix.os == 'ubuntu-latest'
        run: |
          sed -i 's/_GOOS_/linux/g' .goreleaser.yml
          sed -i 's/_GOARCH_/amd64/g' .goreleaser.yml
```

(x3-4, one for each platform)

But then we have to commit the changes:

```yaml
      - name: Commit changes
        run: |
          git add . && git commit --amend --no-edit
          git tag -f "${{  github.ref_name }}"
```

Unfortunately, this breaks the compiled-in git SHA left via goreleaser.

### Search

- [x] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Additional context

Thanks for goreleaser! We use it for Caddy, although this is for something else; this is my first time really starting to use it myself (rather than other contributors managing it).
