### ISSUE TITLE
Artifactory not uploading all archive types

### ISSUE THREAD

**Issue by Lngramos** [goreleaser/goreleaser#552]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

Archives created by the `fpm` pipeline aren't being pushed to Artifactory, only those created by the `archive` pipeline are.

I can only confirm that this is the case with deb formats in particular, although other formats such as rpm might also be affected.

### Environment

Please paste the output of:

* `go version`
* `uname -a`
* `goreleaser --debug`

### Steps to Reproduce

Run with following config:

1. Configure FPM to output deb archives
2. Configure Artifactory with default mode set to `archive`

```yml
# .goreleaser.yml
# Build customization

project_name: test_project

snapshot:
  name_template: "{{ .Tag }}"

builds:
  - binary: test_project
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archive:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

fpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  formats:
    - deb

artifactories:
  - name: production
    target: http://<Your-Instance>:8081/artifactory/example-repo-local/{{ .ProjectName }}/{{ .Version }}/
    username: goreleaser

```

**Expected behavior:** All generated archives, including the deb package generated by FPM should be uploaded to Artifactory, as it is the case with GitHub releases, etc.

**Actual behavior:** Only those created by https://goreleaser.com/#archive seem to be getting uploaded to Artifactory. All archive types should be found visible in both GoReleaser's stdout output and in Artifactory itself.
