### ISSUE TITLE
aur.disable/skip

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#5593]
add a `aurs.disable`, so users can:

```yaml
aurs:
- disable: '{{ not (isEnvSet "AUR_KEY") }}'
aur_sources:
- disable: '{{ not (isEnvSet "AUR_KEY") }}'
```
