### ISSUE TITLE
upx evaluation bug?

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#5719]
### Discussed in https://github.com/orgs/goreleaser/discussions/5718

<div type='discussions-op-text'>

<sup>Originally posted by **LeeTeng2001** April 14, 2025</sup>
```yaml
upx:
  - enabled: false
    ids: [binary1]
    compress: 1
    lzma: true
  - enabled: true
    ids: [binary2]
    compress: 1
    lzma: true
```

upx will not run even though binary2 is enabled, there might be an evaluation bug in upx configuration</div>
