### ISSUE TITLE
Generic HTTP uploads

### ISSUE THREAD

**Issue by jaxxstorm** [goreleaser/goreleaser#583]
Instead of adding contexts for each different artifact repo being considered, would it be possible to add a generic http config option?

For example, the artifactory component looks like this:
```
artifactories:
  - name: production
    target: http://<Your-Instance>:8081/artifactory/example-repo-local/{{ .ProjectName }}/{{ .Version }}/
    username: goreleaser
```
Instead of building support for things like packagecloud.io etc, it might be worth having the option for uploading via HTTP directly, like so:

```
https:
  - name: nexus
     target: http://url/{{.ProjectName}}/{{.Version}}
     username: username # for http basic auth
     password: $PASSWORD
```

We could then work in options for adding http headers as well, if considered.
