### ISSUE TITLE
unexpected behavior in archive:files: section -- how to specify no additional files

### ISSUE THREAD

**Issue by client9** [goreleaser/goreleaser#602]
### Prerequisites

* [x] Are you running the latest version?  HEAD
* [x] Did you perform a search to see if this problem was already reported?

For more information, see the `CONTRIBUTING` guide.

### Description

It's not clear how to specify no additional files to be included in the archive.  Bug? Doc Bug?  Feature?

### Environment

```
$go version
go version go1.10 darwin/amd64

$ uname -a
Darwin nickg-macbook 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

### Steps to Reproduce

i wanted "classic goreleaser" behavior where the tar.gz contained just the binary.  Currently, it tries to add license, readme and changelog info.

In the `archive` stanza, in the `files` section, I tried

* empty.  That just used the default behavior, and not no additional files -- expected no additional files, but I get it... sorta a yaml limitation
* "none"  (an non-existent file) That broke the build saying it couldn't find the file - definitely not expected, but I guess I get it
* "none*"  -- that worked.   Weird.

```
archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: mac
  files:
    - none*
```

you can screw around in 

```
git clone https://github.com/client9/misspell.git
cd misspell
./scripts/goreleaser-dryrun.sh
```

This could be just a documentation bug.
