### ISSUE TITLE
Allow `.Commit` resolution in Dockers build

### ISSUE THREAD

**Issue by jrnt30** [goreleaser/goreleaser#658]
First off, thanks!  The project is wonderful and greatly simplifies and streamlines a lot of practices, thank you for all the work and vision here. 

**Requested Enhancement** 

It would be helpful to expand the current interpolation targets in `dockers[].tag_templates` to include access to the `.Commit` attribute similar to the `builds`, `snapshots`, etc. 

In the past I have seen people "repurpose" the Tag and it would be nice to also have a concrete (and easy) way of injecting this.  

If this is something acceptable, I could take a stab at implementing it. 

ex: 
```
dockers:
- image: jrnt30/k8-kms-enc-provider
  dockerfile: Dockerfile.gorelease
  tag_templates:
    - "{{ .Tag }}"
    - "{{ .Commit }}"
    - latest
```
