### ISSUE TITLE
Build multiple dockers with the same Dockerfile: failed to link dockerfile

### ISSUE THREAD

**Issue by areed** [goreleaser/goreleaser#673]
**Describe the bug**

I have two items under the `dockers` section of my goreleaser yaml and they both use the same Dockerfile. The first item builds succcessfully, but the second fails with error:

```
⨯ release failed after 52.02s error=failed to link dockerfile: link build/Dockerfile-release dist/linux_amd64/Dockerfile-release: file exists
```

**To Reproduce**

```yaml
project_name: my-bundle
release:
  github:
    owner: areed
    name: my-bundle
builds:
- goos:
  - linux
  goarch:
  - amd64
  - "386"
  main: cmd/my-bundle/main.go
  ldflags: -s -w 
    -X github.com/areed/my-bundle/pkg/version.version={{.Version}} 
    -X github.com/areed/my-bundle/pkg/version.gitSHA={{.Commit}} 
    -X github.com/areed/my-bundle/pkg/version.buildTime={{.Date}}
  binary: my-bundle
  hooks: {}
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
dockers:
  - image: quay.io/library/areed-bundle
    dockerfile: build/Dockerfile-release
    goos: linux
    goarch: amd64
    binary: my-bundle
    tag_templates:
      - "{{ .Tag }}"
  - image: areed/my-bundle
    dockerfile: build/Dockerfile-release
    goos: linux
    goarch: amd64
    binary: my-bundle
    tag_templates:
      - "alpha"
      - "stable"
      - "{{ .Tag }}"
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
```

**Expected behavior**

Docker images for both repos should be built.

**Environment (please complete the following information):**

* OS: linux
* OS version: Linux 7bddf2ec2f0c 4.4.0-124-generic #148~14.04.1-Ubuntu SMP Thu May 3 07:26:53 UTC 2018 x86_64 GNU/Linux
* GoReleaser Version 0.74.0

**Additional context**
This happened on CircleCI.

The error happens here:
https://github.com/goreleaser/goreleaser/blob/ad118b0f7c64c46265a3a05737c3e0d4d6d1c2be/pipeline/docker/docker.go#L160
