### ISSUE TITLE
Allow creating empty directories in RPMs

### ISSUE THREAD

**Issue by nhinds** [goreleaser/goreleaser#676]
**Is your feature request related to a problem? Please describe.**
I'm trying to build multiple RPMs which share a log and lib directory. These directories are initially empty.

With raw `.spec` files, this can be accomplished by something like this in each of the RPMs:

```
%install
mkdir -vp $RPM_BUILD_ROOT/var/log/myapp
mkdir -vp $RPM_BUILD_ROOT/var/lib/myapp

...
%files
/var/lib/myapp
/var/log/myapp
```

When either RPM is installed the directories are created, and the directories continue to exist until both RPMs are uninstalled.

**Describe the solution you'd like**
I would like an option in the `nfpm` section of `.goreleaser.yaml` for creating empty directories as part of the RPM.

This could perhaps be a parameter specifying a list of directories to create:
```
nfpm:
  ...
  files:
    build/something.init: /etc/init.d/something
  directories:
  - /var/lib/myapp
  - /var/log/myapp
```

...or by enhancing the existing `files` section to allow empty directories to be specified:
```
nfpm:
  ...
  files:
    build/something.init: /etc/init.d/something
    build/empty-dir-for-var-log: /var/log/myapp
    build/empty-dir-for-var-lib: /var/lib/myapp
```

**Describe alternatives you've considered**
I have attempted to create the empty directory by creating empty directories locally and specifying them in the nfpm `files: ...` directive. However, it seems like nfpm [does not add directories to the .tar.gz if they have no files in them](https://github.com/goreleaser/nfpm/blob/ee5a988/rpm/rpm.go#L285-L287) so the directories are not created under `BUILDROOT` and the build fails during RPM creation:
```
Processing files: myapp-0.0.0-1.x86_64
error: File not found: /tmp/myapp774619009/BUILDROOT/myapp-0.0.0-1.x86_64/var/lib/myapp
error: File not found: /tmp/myapp774619009/BUILDROOT/myapp-0.0.0-1.x86_64/var/log/myapp
```

I have attempted to create the empty directories as part of the RPM's `postinstall` script. However this does not result in the directory being managed by the RPM, so if the other existing RPM which also manages the directory is uninstalled, the /var/lib/myapp / /var/log/myapp directories are removed with it, breaking the RPM created from `goreleaser`. For now this is probably the workaround I'm going to use, along with a message asking users nicely to not uninstall the other RPM.

**Additional context**
Using goreleaser v0.73.2
