### ISSUE TITLE
File placement inside a archive

### ISSUE THREAD

**Issue by diegobernardes** [goreleaser/goreleaser#679]
**Is your feature request related to a problem? Please describe.**

With this config:
```yaml
archive:
  files:
    - readme.md
    - LICENSE
    - service/flare/cmd/flare.sample.toml
```
I want to to chose where the files gonna stay inside the archive.

**Describe the solution you'd like**

We could do something like Docker does to volumes and ports. (`path:destination`)

```yaml
archive:
  files:
    - readme.md
    - misc/LICENSE:.
    - service/flare/cmd/flare.sample.toml:flare.sample.toml
```

If the destination is a folder, copy the file to the folder, if it's a file, copy and rename the file.

**Describe alternatives you've considered**

Don't have much alternative besides change the project structure.
