### ISSUE TITLE
Archive files glob "**" works for .tar.gz but not for .zip

### ISSUE THREAD

**Issue by tliron** [goreleaser/goreleaser#696]
If I add files with "**" glob to an archive, the .tar.gz adds them but not the .zip.

```
archive:
  files:
  - README.md
  - LICENSE
  - NOTICE
  - examples/**

  format_overrides:
  - goos: windows
    format: zip
```

The workaround is to use single "*" globs and add individual directories:

```
archive:
  files:
  - README.md
  - LICENSE
  - NOTICE
  - examples/main/*
  - examples/secondary/*
```

- OS: linux
- OS version: Linux foucault 4.16.14-300.fc28.x86_64 #1 SMP Tue Jun 5 16:23:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser 0.76.0
