### ISSUE TITLE
Tag is committed to master branch even if build is triggered on a different branch

### ISSUE THREAD

**Issue by tombh** [goreleaser/goreleaser#697]
**Describe the bug**
The released tag had the incorrect date. I assumed that there was just a date issue on Travis, so I manually reuploaded the tag. However, upon reflection I now believe the tag was just committed to the repo's master branch, which is not the branch that was committed to Github.

The Travis build is here, but there doesn't seem to be any relevant info; https://travis-ci.org/tombh/texttop/builds/391711883

**To Reproduce**
Release a branch that isn't master.

```yaml
project_name: browsh
builds:
  - main: .
    binary: browsh
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
    ldflags: -s -w
    hooks:
      post: ../contrib/upx_compress_binary.sh

archive:
  format: binary

nfpm:
  vendor: Browsh
  homepage: https://brow.sh
  maintainer: Thomas Buckley-Houston <tom@tombh.co.uk>
  description: A fully interactive, realtime and modern browser rendered to TTY
  license: GPL v3
  formats:
    - deb
    - rpm

  dependencies:
    - firefox

```

**Expected behavior**
The release tag should be committed to the same branch as the release was triggered on.

**Environment**
Travis, see; https://travis-ci.org/tombh/texttop/builds/391711883
GoReleaser Version: 0.77.1

**Additional context**
I'm pretty sure this has happened before. Look at this release: https://github.com/tombh/texttop/releases/tag/v1.0.2 It happened "3 days ago", but it is associated to [this commit](https://github.com/tombh/texttop/commit/421b0dfd55e79ec339de9f499d84b44a1ee1f97c) (421b0), which is the head of the master branch which received its last commit 5 months ago.

However, also note that this repo has had several releases in the last few days since `v1.0.2` and this bug has not consistently occurred.
