### ISSUE TITLE
Binaries per build tag

### ISSUE THREAD

**Issue by bep** [goreleaser/goreleaser#698]
I tried to read up on the documentation on this ...

I may be Tweeted that Hugo is adding SASS support. This currently means Libsass and CGO. Which is unfortunate, but I really want it, so it happens. 

But it will mean that 

1. there will be some platforms that I cannot provide the fully featured binary
2. someone would also probably also prefer a "fully static Hugo binary". And you should need the SASS support when you are done with the design ...

I plan to implement this in a way so you will only need the SASS enabled binary when you are doing SASS edits.

 But what would be great is if I could somehow add "build tag" to the goos/goarch matrix? I notice that you can only set `env` on the top level (i.e. `CGO_ENABLED=0`), which is also problematic.

The goal would be to build two variants of the Linux binary, but only one for the netbsd.

**Comment by caarlos0** [comment]
Hi @bep!

I saw that tweet, this will be an awesome feature!

Right now the `builds` accept multiple `build` structures. So I think you may be able to get what you need with something like:

```yaml
builds:
- env:
    CGO_ENABLED=0
  binary: hugo-without-sass # this is actually a template, so you can do other things here if you want...
  # etc
- env:
    CGO_ENABLED=1
  binary: hugo-with-sass
  # etc
```

What do you think?
