### ISSUE TITLE
Create Multiple Archives

### ISSUE THREAD

**Issue by tdmanv** [goreleaser/goreleaser#705]
**Is your feature request related to a problem? Please describe.**
We would like to release a server/client from a single repo using goreleaser. 

**Describe the solution you'd like**
Ideally we'd be able to create multiple archives - one for the server and one for the client. When installing the client, it shouldn't be required to get the server binary as well. We should also be able to limit the number of os/arch for client/server independently.

**Describe alternatives you've considered**
We're currently using multiple builds and the client and server get packaged in every archive. 

----

Edit by @caarlos0:

- [x] add multiple archives (with everything else using `archives[0]`)
- [x] add multiple nfpm support
- [x] add multiple brew support
- [x] add multiple scoop support
- [x] add multiple snap support
- [x] add multiple http/artifactory support
- [x] add multiple s3/blob support

**Comment by bep** [comment]
Hugo really needs this ... I'm in semi-manual build mode at the moment, and that is a pain when we're doing a fair amount of releases.

**Comment by caarlos0** [comment]
I was thinking in doing something similar to the docker image:


```yaml
archives:
  - binaries: [] # empty means all
    format: zip
    name_template: full
  - binaries: ['foo']
    name_template: foo
  - binaries: ['bar']
    name_template: bar
```

what do you folks think?

**Comment by bep** [comment]
>what do you folks think?

Not sure. In the "Hugo use case", we have a set of builds producing `hugo` (name of binary), which should be packaged in different archives. 

```
{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}
```

The above is is the current archive name template. The above works because we have 2 goreleaser config: One with `project_name` `hugo`, one with `hugo_extended`.

The creator of this issue has probably a simpler requirement that fits your outline better, e.g. binaries `myapp-server` and `myapp-client`.

But I think that in the Go world where plugins are hard, I think having a way to package different bundles of the same app would be really useful for many. And you would want these to be named the same so they could be "drop-in-replacements".

**Comment by caarlos0** [comment]
@bep hmm

so, yeah, my example maybe wasn't good, in hugo use case it would look like:

```yaml
archives:
  - binaries: ['hugo']
    name_template: 'hugo_{{.Version}}_{{.Os}}-{{.Arch}}'
  - binaries: ['hugo_extended']
    name_template: 'hugo_extended_{{.Version}}_{{.Os}}-{{.Arch}}'
```

so, in the end you'll have the `hugo` archives and the `hugo_extended` archives for each build...

**Comment by bep** [comment]
Ah, OK, then I misunderstood. Yea, that looks good.

**Comment by tdmanv** [comment]
That also works for our use case. Thanks!

**Comment by caarlos0** [comment]
check the WIP on https://github.com/goreleaser/goreleaser/pull/787

**Comment by caarlos0** [comment]
So, I've been thinking about this, and I think we can split it in several steps:

- [ ] scoop pipe doesn't even support multiple builds yet, this need to be fix so it can support multiple archives too
- [ ] same thing with brew pipe
- [ ] in the config, we need to be able to reference a build in an archive config
- [ ] in the config, we need to be able to reference an archive in different pipes (and reference the build from which the binary came from)

From here we have 2 possible strategies:

###### 1. add multiple support to everything else first, and then multiple archives 

- [ ] add multiple brew support
- [ ] add multiple scoop support
- [ ] add multiple snap support
- [ ] add multiple http/artifactory support
- [ ] add multiple archives

###### 2. add multiple archive first, and then everything else

- [ ] add multiple archives (with everything else using `archives[0]`)
- [ ] add multiple brew support
- [ ] add multiple scoop support
- [ ] add multiple snap support
- [ ] add multiple http/artifactory support
 
My idea would be to start implementing this and releasing small pieces of it until we get everything done.

**Comment by frapposelli** [comment]
this looks like a sizable change, any chance that this can be implemented with a feature flag? I'm sure there are people (like me 😅) that are interested only in a subset of these features.

**Comment by caarlos0** [comment]
problem is that goreleaser was designed on the premise of a single archive, so there are a lot of places where that is very coupled... I'm reluctant to even work on this because I can break several things, unfortunately.... but I will! One of those rainy saturdays I'll get to it and get it done haha 

Meanwhile, there is a WIP on #942 and some feedback would be lovely! I'm not sure, for example, in what's a good way to reference an archive inside another pipe (eg. brew).
Right now, my idea was to add a `id` field to each archive, so the user can:

```yaml
archives:
- id: archive1
  # etc..
brews:
- id: brew1
  archives:
  - archive1
  - archive2
 # etc
```

but it seems confusing... I was even thinking about migrating the config to HCL because of that (terraform does it very well IMO).

Anyway, not sure how this will work yet :/

**Comment by codyaray** [comment]
My use case is that I want to upload the raw binaries to S3 (my CLI uses for auto-update mechanism) as well as tar/zip for humans to download.

Here's what I think this might look like:

```
archives:
- id: archive1
  format: binary

- id: archive2
  format: tar.gz
    files:
    - LICENSE
    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

s3:
    -
      archives:
        - archive1
      bucket: mybucket
      region: us-west-2
      folder: "autoupdater/{{.Version}}"
      acl: public-read
    -
      archives:
        - archive2
      bucket: mybucket
      region: us-west-2
      folder: "downloads/{{.Version}}"
      acl: public-read
```
