### ISSUE TITLE
nfpm on windows

### ISSUE THREAD

**Issue by wxio** [goreleaser/goreleaser#714]
**Describe the bug**
Using goreleaser on windows produced a deb package with incorrect folder paths.
i.e. `\`s instead of `/`s

**To Reproduce**

```yaml
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  empty_folders:
  - /var/log/imgsvr
  files:
    "init.d/imgsvr": "/etc/init.d/imgsvr"
```

Got 
```
$ dpkg -L imgsvr
/var
/var\log
/var\log\imgsvr
/etc
/etc\init.d
/etc\init.d\imgsvr
/usr
/usr\bin
/usr\bin\imgsvr
```

Expected
```
$ dpkg -L imgsvr
/var
/var/log
/var/log/imgsvr
/etc
/etc/init.d
/etc/init.d/imgsvr
/usr
/usr/bin
/usr/bin/imgsvr
```

**Environment (please complete the following information):**

- OS: windows
- GoReleaser Version: 0.79.1, commit 47b6bd5f502050dd1ebd94896d009e7aa87785b1, built at 2018-07-04T15:52:18Z
