### ISSUE TITLE
nfpm on windows - file permissions & post install scripts

### ISSUE THREAD

**Issue by millergarym** [goreleaser/goreleaser#717]
**Describe the bug**

The file permissions are all `-rw-rw-rw-`.
Also, scripts don't seem to being bundled with the package.

**To Reproduce**

```yaml
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  vendor: xxx
  description: Image server, upload images and get a url
  maintainer: ImgSvr <info@aaa.bbb>
  formats:
    - deb
  dependencies:
  bindir: /usr/bin
  empty_folders:
  - /var/log/imgsvr
  - /opt/imgsvr
  files:
    "scripts/etc/init.d/imgsvr": "/etc/init.d/imgsvr"
  # config_files:
  #   "tmp/app_generated.conf": "/etc/app.conf"
  scripts:
    # preinstall: "scripts/preinstall.sh"
    postinstall: "scripts/postinstall.sh"
    # preremove: "scripts/preremove.sh"
    # postremove: "scripts/postremove.sh"
```

**Expected behavior**

I expected nfpm to magically know which files need to be executable ;-)
Not quite, I hoped to chmod the files and install the server in postinstall.sh

```
#!/bin/sh

chmod a+xr /etc/init.d/imgsvr
chmod a+xr /usr/bin/imgsvr
/usr/sbin/update-rc.d imgsvr enable
service imgsvr start
```

**Environment (please complete the following information):**

- OS: windows
- GoReleaser Version [goreleaser --version]
0.79.2, commit 8f675d8d9134457e6713df1ec2b63e86a0849080, built at 2018-07-09T03:14:17Z
