### ISSUE TITLE
how to archive a folder ?

### ISSUE THREAD

**Issue by TruthHun** [goreleaser/goreleaser#719]
I have many static files in a folder，and how to archive them with a folder？
thinks.

**Comment by TruthHun** [comment]
OK，I have solved it by myself.
my `.goreleaser.yml`：
```
builds:
- binary: gin
  main: main.go
  goos:
     - windows
     - darwin
     - linux
     - freebsd
  goarch:
     - amd64
     - 386
     - arm
     - arm64
  goarm:
    - 6
    - 7
archive:
  format: zip
  files:
    - views/*
    - conf/*
    - static/*
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: amd64
```
