### ISSUE TITLE
Homebrew code doesn't acknowledge `format_overrides`

### ISSUE THREAD

**Issue by tombh** [goreleaser/goreleaser#720]
**Describe the bug**
When using a main format of `binary` and a format override of `zip` the Homebrew code doesn't acknowledge override for `darwin`.

**To Reproduce**
Specify the default format as `binary` and specify the format override for `darwin` as `zip`.

```yaml
project_name: browsh
builds:
  - main: .
    binary: browsh
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
    ldflags: -s -w
    hooks:
      post: ../contrib/upx_compress_binary.sh

archive:
  format: binary
  format_overrides:
    - goos: darwin
      format: zip

nfpm:
  vendor: Browsh
  homepage: https://brow.sh
  maintainer: Thomas Buckley-Houston <tom@tombh.co.uk>
  description: A fully interactive, realtime and modern browser rendered to TTY
  license: GPL v3
  formats:
    - deb
    - rpm

  dependencies:
    - firefox

release:
  disable: true

brew:
  name: browsh

  # Reporitory to push the tap to.
  github:
    owner: browsh-org
    name: homebrew-browsh

  commit_author:
    name: Goreleaser Bot care of Travis CI
    email: builds@travis-ci.com

  homepage: "https://www.brow.sh"

  description: "The modern, text-based browser"

  dependencies:
    - firefox

```

**Expected behavior**
Homebrew code should run without this response:
```
• CREATING HOMEBREW FORMULA
      • skipped                   reason=archive format is binary
``` 

Using `curl -sL http://git.io/goreleaser | bash`
