### ISSUE TITLE
wrap_in_directory with custom directory name

### ISSUE THREAD

**Issue by lzjluzijie** [goreleaser/goreleaser#728]
For example, my project name is `websocks`. When I enable `wrap_in_directory`, the directory name inside the windows archive will be `websocks_Windows_x86_64`. I want only project name or project name with version, but I can't find anywhere for it.

Can you add a new field like "sub_directory_name"?

**Comment by caarlos0** [comment]
you're the first asking for this, let's see if more people are interested...

**Comment by lzjluzijie** [comment]
https://github.com/goreleaser/archive/issues/4 

By the way, I found a problem with packing files in subdirectories. I want to pack all the files and files in directories in `templates` directory, but it will only pack the `home.html` file and empty directories. 

```yaml
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  wrap_in_directory: true
  files:
    - LICENSE
    - README.md
    - README-en.md
    - templates/*
```

```bash
templates
├── base
│   └── base.html
├── client
│   └── client.html
├── server
│   ├── login.html
│   └── server.html
└── home.html
```
