### ISSUE TITLE
goreleaser produces more builds than expected

### ISSUE THREAD

**Issue by nicksnyder** [goreleaser/goreleaser#729]
**Describe the bug**

goreleaser produces 386 builds when I don't expect it to.

**To Reproduce**

```yaml
builds:
  - binary: yj
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - env:
    - CGO_ENABLED=0
checksum:
 name_template: 'checksums.txt'
snapshot:
 name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

`goreleaser release` produces i386 builds for darwin and linux (but not windows?)
- windows_amd64
- darwin_amd64
- darwin_386
- linux_amd64
- linux_386

https://github.com/sourcegraph/yj/releases/tag/v1.0.0

**Expected behavior**

Produce only amd64 builds since that is the only entry I configured in goarch.
- windows_amd64
- darwin_amd64
- linux_amd64

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin Nicks-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
- GoReleaser Version 0.80.2, commit ce83c85bfc74fd5551f89e4e8aff6dd28264a31b, built at 2018-07-17T17:05:34Z
