### ISSUE TITLE
archive zip include subfolder files error in windows 10

### ISSUE THREAD

**Issue by foolin** [goreleaser/goreleaser#734]
archive zip include  files error in windows 10, the project struct such as:
```
|-- app/views/
    |-- admin/
        |--- index.html
        ....
    |-- lark/
        |--- index.html
        |-- layouts/
            |--- footer.html
            ....
```
the config file:
```yaml
archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
    - views/**/*
....
```

the zip file screenshot：
![zip](https://user-images.githubusercontent.com/2344587/43091709-5e0f29ea-8edd-11e8-93b4-29d207147d0d.png)

This is bad zip file, it can't unzip! But when I set format "tar.gz" is going well. Is this a bug?
