### ISSUE TITLE
Snapshot artifacts do not include name_template patterns and are uploaded to s3 despite --skip-publish

### ISSUE THREAD

**Issue by cludden** [goreleaser/goreleaser#737]
**Describe the bug**

using goreleaser with `--snapshot` is generating artifacts without honoring the `name_template` field and overwriting prior artifacts. I can see in the debug log statements that the version variable has the snapshot tag, however the resulting artifact does not. also, snapshots are published to s3 even when the `--skip-publish` flag is included. is this the expected behavior?

**To Reproduce**
cmd:

```shell
$ goreleaser --snapshot --skip-publish --rm-dist --debug
```

config:

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - main: ./cmd/xxxxxx
    binary: xxxxxx
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

  - main: ./cmd/xxxxxx
    binary: xxxxxx
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  
  - main: ./cmd/xxxxxx
    binary: xxxxxx
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
    - README.md
    - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: xxxxxx
    name: xxxxxx

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  name_template: "{{.Tag}}"

s3:
  - bucket: xxxxxx
    region: xxxxxx
```
debug:

```
      • running git               args=[describe --tags --abbrev=0]
      • git result                output=v1.3.0-beta.0

      • releasing v1.3.0-beta.0, commit xxxxx
      • skipped                   reason=disabled during snapshot mode
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG
      • skipped                   reason=not available for snapshots
   • LOADING ENVIRONMENT VARIABLES
      • skipped                   reason=publishing is disabled
   • BUILDING BINARIES
      • building                  build={[linux] [amd64] [6] [linux_amd64] [] ./cmd/xxxxx [-s -w -X main.version={{.Version}}] [] xxxxxx { } [CGO_ENABLED=0] go [] []}
      • building                  binary=dist/linux_amd64/xxxxx
      • running                   cmd=[go build -ldflags=-s -w -X main.version=v1.3.0-beta.0-next -o dist/linux_amd64/xxxxx ./cmd/xxxxxx] env=[CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOARM=]
      • added new artifact        name=xxxxx path=dist/linux_amd64/xxxxx type=Binary
      • building                  build={[linux] [amd64] [6] [linux_amd64] [] ./cmd/xxxxx [-s -w -X main.version={{.Version}}] [] xxxxx { } [CGO_ENABLED=0] go [] []}
      • building                  binary=dist/linux_amd64/xxxxx
      • running                   cmd=[go build -ldflags=-s -w -X main.version=v1.3.0-beta.0-next -o dist/linux_amd64/xxxxx ./cmd/xxxx] env=[CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOARM=]
      • added new artifact        name=xxxxx path=dist/linux_amd64/xxxxx type=Binary
      • building                  build={[linux] [amd64] [6] [linux_amd64] [] ./cmd/xxxxx [-s -w -X main.version={{.Version}}] [] xxxxx { } [CGO_ENABLED=0] go [] []}
      • building                  binary=dist/linux_amd64/xxxxxx
      • running                   cmd=[go build -ldflags=-s -w -X main.version=v1.3.0-beta.0-next -o dist/linux_amd64/xxxxx ./cmd/xxxxx] env=[CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOARM=]
      • added new artifact        name=xxxxx path=dist/linux_amd64/xxxxxx type=Binary
   • CREATING ARCHIVES
      • creating                  archive=dist/xxxxx_v1.3.0-beta.0_linux_amd64.zip
      • adding CHANGELOG.md      
      • adding README.md         
      • adding events            
      • adding history           
      • adding indexer           
      • added new artifact        name=xxxxx_v1.3.0-beta.0_linux_amd64.zip path=dist/xxxxx_v1.3.0-beta.0_linux_amd64.zip type=UploadableArchive
   • CREATING LINUX PACKAGES WITH NFPM
      • skipped                   reason=no output formats configured
   • CREATING LINUX PACKAGES WITH SNAPCRAFT
      • skipped                   reason=no summary nor description were provided
   • CALCULATING CHECKSUMS
      • added new artifact        name=checksums.txt path=dist/checksums.txt type=Checksum
      • checksumming              file=xxxxx_v1.3.0-beta.0_linux_amd64.zip
   • SIGNING ARTIFACTS
      • skipped                   reason=artifact signing is disabled
   • CREATING DOCKER IMAGES
      • skipped                   reason=docker section is not configured
   • RELEASING TO ARTIFACTORY
      • skipped                   reason=artifactory section is not configured
   • RELEASING TO S3  
      • uploading                 artifact=checksums.txt bucket=xxxxx folder=xxxxx/v1.3.0-beta.0
      • uploading                 artifact=xxxxx_v1.3.0-beta.0_linux_amd64.zip bucket=xxxxx folder=xxxxx/v1.3.0-beta.0

```
**Expected behavior**

expected to resulting artifact to include the snapshot name template result (eg `vX.X.X-next`)

**Environment (please complete the following information):**

- OS: linux (ubuntu)
- OS version: Linux xxxxx 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- GoReleaser Version: 0.77.1

**Additional context**
