### ISSUE TITLE
goreleaser in travis fails: "error=tmpl: Invalid Semantic Version"

### ISSUE THREAD

**Issue by deimosfr** [goreleaser/goreleaser#750]
**Describe the bug**

On travis (and only on travis), I can't run successfully goreleaser after pushing a tag. Here are the logs I got:

```
Deploying application
   • releasing using goreleaser 0.82.1...
   • loading config file       file=.goreleaser.yml
   • SETTING DEFAULTS FOR:    
      • loading environment variables
      • snapshoting              
      • releasing to GitHub      
      • project name             
      • creating archives        
      • building binaries        
      • creating Linux packages with fpm
      • creating Linux packages with nfpm
      • creating Linux packages with snapcraft
      • calculating checksums    
      • signing artifacts        
      • creating Docker images   
      • releasing to Artifactory 
      • releasing to s3          
      • creating homebrew formula
      • creating Scoop Manifest  
   • RUNNING BEFORE HOOKS     
   • CHECKING ./DIST          
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.2.16b, commit f80a4090229ab0050edc629b3f3e86ce09352bad
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG     
      • writing                   changelog=dist/CHANGELOG.md
   • LOADING ENVIRONMENT VARIABLES
   • BUILDING BINARIES        
   ⨯ release failed after 0.11s error=tmpl: Invalid Semantic Version
Script failed with status 1
```

**To Reproduce**

Steps to reproduce the behavior, here is the config:

```yaml
builds:
- main: main.go
  binary: k8s-dns-updater
  goos:
  - linux
  goarch:
  - amd64
```

The travis config:
```yaml
sudo: required

language: go

services:
- docker

env:
- PROJECT_ID="mysocialapp" PROJECT_NAME="k8s-dns-updater" APP_VERSION="$TRAVIS_TAG"

script:
- go build
- rm -f ${PROJECT_NAME}

deploy:
- provider: script
  skip_cleanup: true
  script: "curl -sL http://git.io/goreleaser | bash"
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
```

**Expected behavior**

As working outside travis, I expect it to work build the binaries.
