### ISSUE TITLE
Misleading error when checking git.IsRepo

### ISSUE THREAD

**Issue by omerxx** [goreleaser/goreleaser#753]
**Describe the bug**

When running the releaser on a platform that doesn't have git installed (e.g a Drone plugin running on an alpine image), the returned error is "current folder is not a git repository".
This is not true, the error is not having git and it has to be checked (and tested).
IMHO this line - https://github.com/goreleaser/goreleaser/blob/2ea883e0c44860e14aab39c935cbd4df5a8720ca/pipeline/release/remote.go#L14 should be checked with returned values (`var, err := git.IsRepo()`) and 
check whether this is actually not a repo, or simple git is not installed / failing for some reason.  

**To Reproduce**
```bash
# Runnning a container while mounting my project to use the releaser with:
docker run -v <location of release project>:<container path> golang:alpine

# Exec into the container:
docker exec -it <container id> sh

# Trying to release
curl -sL https://git.io/goreleaser | sh

# Installing git to make release work:
apk update && apk add curl git -y
curl -sL https://git.io/goreleaser | sh
```

**Config file**
```yaml
project_name: fed-cli
release:
  github:
    owner: SpotIM
    name: fed-cli
  name_template: '{{.Tag}}'
brew:
  name: fed
  github:
    owner: spotim
    name: homebrew-tools
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  folder: formula
  install: |
    bin.install "fed"
  dependencies:
  - awscli
  test: |
    system "fed --version"
  description: CLI to deploy Frontend modules
  homepage: https://github.com/spotim/fed-cli
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
scoop:
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
builds:
- goos:
  - darwin
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - linux_amd64
  main: ./fed/main.go
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: fed
  env:
  - CGO_ENABLED=0
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com

```

**Expected behavior**

A return error message that identifies the real problem i.e "Error: git is not installed"

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
- GoReleaser Version: 0.82.2, commit f0413af071cd3635fe51c6204a72f6af2cf6cd03, built at 2018-08-08T17:32:08Z

**Additional context**
