### ISSUE TITLE
error=yaml: line 4: did not find expected key -> binary

### ISSUE THREAD

**Issue by cmoulliard** [goreleaser/goreleaser#756]
**Describe the bug**

**To Reproduce**

run the goreleaser command with this yaml file

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- binary: sb
  - env:
    - CGO_ENABLED=0
  archive:
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  checksum:
    name_template: 'checksums.txt'
  snapshot:
    name_template: "{{ .Tag }}-next"
  changelog:
    sort: asc
    filters:
      exclude:
      - '^docs:'
      - '^test:'
```

Error generated

```
goreleaser   

   • releasing using goreleaser 0.82.2...
   • loading config file       file=.goreleaser.yml
   ⨯ release failed after 0.00s error=yaml: line 4: did not find expected key
```

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin dabou 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- GoReleaser Version : 0.82.2

**Comment by caarlos0** [comment]
you config file is wrong.

Please check the [documentation](https://goreleaser.com/customization/).

I think you wanted to do something like this:

```yaml
builds:
- binary: sb
  env:
    - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```
