### ISSUE TITLE
Duplicated docker extra_files leads to build error

### ISSUE THREAD

**Issue by michelvocks** [goreleaser/goreleaser#765]
**Describe the bug**

First of all, thanks a lot for goreleaser. Awesome tool! 🤗 

We are generating multiple docker images with goreleaser. Some images share files (for example `docker-entrypoint.sh` file). If you specify for every docker image via `extra_files` the same file, the release process will abort and fail with the following message:

 `release failed after 59.91s error=failed to link extra file 'docker/settings-docker.xml': link docker/settings-docker.xml dist/linux_amd64/settings-docker.xml: file exists`

**To Reproduce**

```yaml
before:
  hooks:
    - make compile_frontend static_assets
builds:
  - main: ./cmd/gaia/main.go
    binary: gaia-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile
    extra_files:
      - docker/docker-entrypoint.sh
      - docker/settings-docker.xml
    tag_templates:
    - latest
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.golang
    extra_files:
      - docker/docker-entrypoint.sh
      - docker/settings-docker.xml
    tag_templates:
    - "{{ .Tag }}-go"
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.java
    extra_files:
      - docker/docker-entrypoint.sh
      - docker/settings-docker.xml
    tag_templates:
    - "{{ .Tag }}-java"
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.python
    extra_files:
      - docker/docker-entrypoint.sh
      - docker/settings-docker.xml
    tag_templates:
    - "{{ .Tag }}-python"
```

**Expected behavior**

It should be clearly mentioned in the documentation that a file just needs to be defined once and where it should be defined (only first entry?). 
Or even better, it is possible to define one file multiple times. 

**Environment (please complete the following information):**

- OS: mac
- OS version: 17.7.0 Darwin Kernel Version
- GoReleaser Version: 0.79.0
