### ISSUE TITLE
Valid PUT ends up in error

### ISSUE THREAD

**Issue by jbaruch** [goreleaser/goreleaser#790]
**Describe the bug**

An HTTP PUT successful with CURL ends up with `error=put: upload failed: getting http response location: http: no Location header in response` in goreleaser

**To Reproduce**

```yaml
puts:
  - name: bintray
    mode: archive
    target: https://api.bintray.com/content/your.org/your.repo/{{ .ProjectName }}/{{ .Version }}/
    username: username
```

**Expected behavior**

Looks like the put is valid in CURL. Should work in Goreleaser as well.

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- GoReleaser Version [goreleaser --version]

**Additional context**
I am trying to produce and document a "standard" Bintray PUT example.
