### ISSUE TITLE
template support for goos and goarch

### ISSUE THREAD

**Issue by jeffreystoke** [goreleaser/goreleaser#796]
**Is your feature request related to a problem? Please describe.**

I was trying to start a native build with CGO_ENABLED=1, and cross build with CGO_ENABLED=0, so I wrote the config like this

```yaml
builds:
  # native build (cgo enabled)
  - binary: config-server
    main: cmd/server/main.go
    env:
    - CGO_ENABLED=1
    - GIN_MODE=release
    ldflags:
    - -s -w -X main.version={{.Version}}
    - -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    goos:
    - "{{ .Env.GOHOSTOS }}"
    goarch:
    - "{{ .Env.GOHOSTARCH }}"
  # cross build (cgo disabled)
  - binary: config-server
    main: cmd/server/main.go
    env:
    - CGO_ENABLED=0
    - GIN_MODE=release
    ldflags:
    - -s -w -X main.version={{.Version}}
    - -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    goos:
    - darwin
    - linux
    goarch:
    - amd64
    - 386
    - arm
    - arm64
    goarm:
    - 5
    - 6
    - 7
    ignore:
    # ignore native build
    - goos: "{{ .Env.GOHOSTOS }}"
      goarch: "{{ .Env.GOHOSTARCH }}"
    - goos: darwin
      goarch: 386
```

then I started build as

```bash
GOHOSTOS=$(go env GOHOSTOS) \
GOHOSTARCH=$(go env GOHOSTARCH) \
GOVERSION=$(go version | awk '{print $3;}') \
goreleaser --snapshot --rm-dist --debug
```

but the output (build section)

```
   • BUILDING BINARIES
      • building                  build={[{{ .Env.GOHOSTOS }}] [{{ .Env.GOHOSTARCH }}] [6] [] [] cmd/server/main.go [-s -w -X main.version={{.Version}} -X main.commit={{ .Commit }} -X main.date={{ .Date }}] [] config-server { } [CGO_ENABLED=1 GIN_MODE=release] go [] []}
      • building                  build={[darwin linux] [amd64 386 arm arm64] [5 6 7] [darwin_amd64 linux_amd64 linux_386 linux_arm_5 linux_arm_6 linux_arm_7 linux_arm64] [{{{ .Env.GOHOSTOS }} {{ .Env.GOHOSTARCH }} } {darwin 386 }] cmd/server/main.go [-s -w -X main.version={{.Version}} -X main.commit={{ .Commit }} -X main.date={{ .Date }}] [] config-server { } [CGO_ENABLED=0 GIN_MODE=release] go [] []}
```

suggests the template not being replaced.

**Describe the solution you'd like**

Support environment variables (template) for goos and goarch inside build pipeline, could be helpful for some native and cross build.

**Describe alternatives you've considered**
Not yet came to me.

**Additional context**
None.

Many thanks for this great project.

**Comment by caarlos0** [comment]
yeap, that field is not templateable...

**Comment by caarlos0** [comment]
I rather not allow this.

For the use case you need, I think its better to use something like envsubst to replace something in the goreleaser file, eg:

```yaml
  - binary: config-server
    main: cmd/server/main.go
    env:
    - CGO_ENABLED=1
    - GIN_MODE=release
    ldflags:
    - -s -w -X main.version={{.Version}}
    - -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    goos:
    - "${GOHOSTOS}"
    goarch:
    - "${GOHOSTARCH}"
```

```sh
export GOHOSTOS=$(go env GOHOSTOS)
export GOHOSTARCH=$(go env GOHOSTARCH)
goreleaser -f <( envsubst .goreleaser.yml )
```

Thanks for the issue anyways!
