### ISSUE TITLE
Goreleaser pushes full Changelog when using release-branch pattern

### ISSUE THREAD

**Issue by andscoop** [goreleaser/goreleaser#817]
**Describe the bug**

We are using go releaser in our https://github.com/astronomerio/astro-cli project. We recently moved into a pattern of using release branches. This means that every major release gets a new release branch and a new tag/release. Every minor and patch release get tags/releases cut against the major release branch.

This has resulted in the entire commit history being publishes to the changelog on each major release. Subsequent minor releases and patch releases behave as expected.

Major Release Ex.
https://github.com/astronomerio/astro-cli/releases/tag/v0.6.0

Minor Release Ex.
https://github.com/astronomerio/astro-cli/releases/tag/v0.6.1

**To Reproduce**

```yaml
project_name: astro
release:
  github:
    owner: astronomerio
    name: astro-cli
brew:
  install: bin.install "astro"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X github.com/astronomerio/astro-cli/cmd.currVersion={{ .Version }} -X github.com/astronomerio/astro-cli/cmd.currCommit={{ .Commit }}
  binary: astro
  ignore:
    - goos: windows
      goarch: amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
```

Create a new branch titled release-X.0 and cut a release against that branch. This will cause the entire commit history to be pushed against that branch.

**Expected behavior**

I would expect this to behave the same way cutting a new release against master works. Only showing commits on curr branch that have occurred since the last release even if that release occurred on a separate branch.

**Environment (please complete the following information):**

- OS: Alpine
- OS version: 3.7, or 3.8 (golang:1.10 docker tag)
- GoReleaser Version goreleaser/goreleaser:v0.86

**Additional context**
I can understand why this might be difficult due to branching, but I am curious if it is possible.
