### ISSUE TITLE
make: brew: No such file or directory

### ISSUE THREAD

**Issue by conradwt** [goreleaser/goreleaser#823]
**Describe the bug**

Homebrew isn't installed but I have `dep` installed via `go get`

```bash
$ cd $GOPATH/src/github.com/golang/dep && git describe --tags
v0.5.0-15-g22125cfa
```

**To Reproduce**

```
$ go get -d github.com/goreleaser/goreleaser
$ cd $GOPATH/src/github.com/goreleaser/goreleaser
$ dep ensure -vendor-only
$ make setup build
```

I received the following error:

```bash
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.10.2 for v1.10.2/darwin/amd64
golangci/golangci-lint info installed ./bin/golangci-lint
curl -sfL https://install.goreleaser.com/github.com/gohugoio/hugo.sh | sh
gohugoio/hugo info checking GitHub for latest tag
gohugoio/hugo info found version: 0.49 for v0.49/macOS/64bit
gohugoio/hugo info installed ./bin/hugo
curl -sfL https://install.goreleaser.com/github.com/caarlos0/bandep.sh | sh
caarlos0/bandep info checking GitHub for latest tag
caarlos0/bandep info found version: 0.1.3 for v0.1.3/darwin/amd64
caarlos0/bandep info installed ./bin/bandep
brew install dep
make: brew: No such file or directory
make: *** [setup] Error 1
```

```yaml
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
dockers:
- image: goreleaser/goreleaser
  extra_files:
  - scripts/entrypoint.sh
  tag_templates:
  - '{{ .Tag }}'
  - 'v{{ .Major }}.{{ .Minor }}'
  - 'latest'
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
brew:
  github:
    owner: goreleaser
    name: homebrew-tap
  folder: Formula
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  test: |
    system "#{bin}/goreleaser -v"
scoop:
  bucket:
    owner: goreleaser
    name: scoop-bucket
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  license: MIT
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
  license: MIT
  vendor: GoReleaser
  formats:
  - deb
  - rpm
  dependencies:
  - git
  recommends:
  - rpm
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  summary: Deliver Go binaries as fast and easily as possible
  description: |
    GoReleaser builds Go binaries for several platforms, creates a GitHub
    release and then pushes a Homebrew formula to a repository. All that
    wrapped in your favorite CI.
  grade: stable
  confinement: classic
```

**Expected behavior**

Complete without error.

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]

macOS 10.14.1

- OS version: [uname -a]
N/A

- GoReleaser Version [goreleaser --version]

```bash
$ goreleaser --version

dev, commit none, built at unknown
```
Note:  `goreleaser --version` doesn't output an actual version.

```bash
$ goreleaser

   • releasing using goreleaser dev...
   • loading config file       file=.goreleaser.yml
   • SETTING DEFAULTS FOR:
      • loading environment variables
      • snapshoting              
      • releasing to GitHub      
      • project name             
      • creating archives        
      • building binaries        
      • creating Linux packages with nfpm
      • creating Linux packages with snapcraft
      • calculating checksums    
      • signing artifacts        
      • creating Docker images   
      • releasing to Artifactory 
      • releasing to s3          
      • creating homebrew formula
      • creating Scoop Manifest  
   • RUNNING BEFORE HOOKS
   • CHECKING ./DIST  
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.87.0, commit 60b0bc24166e81c720ef0bec838e8c4b019a04c2
   ⨯ release failed after 0.11s error=git is currently in a dirty state:
 M Gopkg.lock
 M Makefile
```
Note:  Using `gorelease` without the version option displayed what appears to be version information.

**Additional context**

After removing `brew install dep`, I was able to complete the build of `goreleaser`.  However, I also needed to perform `go install` in the root of the `goreleaser` directory to make the binary available globally.
