### ISSUE TITLE
Archive contains duplicates of the binary.

### ISSUE THREAD

**Issue by kb18951452** [goreleaser/goreleaser#836]
**Describe the bug**

The archive contains multiple copies of the build binary. 

**To Reproduce**

Run `goreleaser`
Run `unzip -l [archive.zip]`
Note multiple copies of binary

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
- goos:
  - darwin
  - freebsd
  - linux
  - openbsd
  - solaris
  - windows
- goarch:
  - 386
  - amd64
  - arm
- ignore:
  - goos: darwin
    goarch: 386
  - goos: darwin
    goarch: arm
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    freebsd: Freebsd
    386: 32-bit
    amd64: 64-bit
    solaris: solaris
  format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

```

**Expected behavior**

A single copy of binary contained in [archive.zip]

**Environment (please complete the following information):**

- OS: mac
- OS version: ```Darwin kenneth-mac 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64```
- GoReleaser Version: ```0.88.0, commit f99940ff5397b099bf606cf1323c00c63afcd153, built at 2018-10-05T02:57:17Z```

**Additional context**
