### ISSUE TITLE
Artifacts cannot be extracted

### ISSUE THREAD

**Issue by threkk** [goreleaser/goreleaser#863]
**Describe the bug**

Before publishing my release, I wanted to test the files. Every time I try to extract the binaries, I get the following error:

```
$ tar -xzf myip_macos-1.0.2.tar.gz
myip: gzip decompression failed
tar: Error exit delayed from previous errors.
```

**To Reproduce**

1. `goreleaser release --rm-dist --skip-publish`
2. `tar -xzf dist/*.tar.gz`

```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - main: ./cmd/myip
    binary: myip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Version }}'
  replacements:
    darwin: macos
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

**Expected behavior**

The binary should be extracted without errors.

**Environment (please complete the following information):**

- OS: MacOS
- OS version: `Darwin trantor.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
- GoReleaser Version: `0.92.1, commit none, built at unknown` (installed with brew).

**Comment by threkk** [comment]
Hi @caarlos0 ! Thanks for your quick response. This is the content of the file:

```
project_name: myip
release:
  github:
    owner: threkk
    name: myip
  name_template: '{{.Tag}}'
brew:
  name: myip
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  install: bin.install "myip"
scoop:
  name: myip
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  url_template: https://github.com/threkk/myip/releases/download/{{ .Tag }}/{{ .ArtifactName
    }}
builds:
- goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - darwin_386
  - linux_amd64
  - linux_386
  - windows_amd64
  - windows_386
  main: ./cmd/myip
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: myip
  env:
  - CGO_ENABLED=0
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Version }}'
  replacements:
    darwin: macos
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
```
