### ISSUE TITLE
brew folder config param doesn't work as expected on windows 10

### ISSUE THREAD

**Issue by pmi** [goreleaser/goreleaser#865]
**Describe the bug**

Homebrew recipe is placed in the root of the brew tap repo, having folder as part of the name when built on Windows 10, i.e `"Formula\myapp".rb` instead of being put inside the Formula folder `Formula/myapp.rb` when folder config param is set to Formula. Adding slashes had no effect.
Probably related to system path separator being applied to github recipe path. (backslash instead of slash)

**To Reproduce**

  Specify *folder: Formula* for the brew config and use it on windows 10

```yaml
brew:

  # Repository to push the tap to.
  github:
    owner: mycompany
    name: myapp

  # Template for the url.
  # Default is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#  url_template: "http://github.mycompany.com/foo/bar/releases/{{ .Tag }}/{{ .ArtifactName }}"

  # Allows you to set a custom download strategy.
  # Default is empty.
#  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: "http://mycompany.com/"

  # Your app's description.
  # Default is empty.
  description: "My company command line interface."
```

**Expected behavior**

The brew recipe should be placed inside the Formula folder

**Environment (please complete the following information):**

- OS: [e.g. mac, linux] Windows
- OS version: [uname -a] 10
- GoReleaser Version [goreleaser --version] 0.92.1, commit 8eaca29766e2f635bb68994111ccefd6ee342e14, built at 2018-10-31T03:39:21Z

**Additional context**
