### ISSUE TITLE
Dockers/extra_files do not support wildcards

### ISSUE THREAD

**Issue by tisba** [goreleaser/goreleaser#887]
`dockers` -> `extra_files` does not support wildcards like `archive` -> `files` does, although they look more or less like the same functionality.

**To Reproduce**

```yaml
dockers:
  extra_files:
  - 'go.*'
```

**Expected behavior**

I would expect that `go.sum` and `go.mod` in my case would get copied to the temp directory so that I can use them in my Dockerfile.

**Environment**

- OS: mac
- OS version: `Darwin shakti 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`
- GoReleaser Version `0.94.0, commit e7bec044a0013a7c64c3eaa40c606617b8bc7953, built at 2018-11-29T23:13:48Z`

**Comment by caarlos0** [comment]
thinking on this, the extra files are actually just folders or files that should be linked to the temporary folder in which the docker image will be built, so, you can do things like:

```yaml
dockers:
  extra_files:
  - some/folder
```

then:

```dockerfile
FROM blah
ADD some/folder/*.go /somewhere
```

That being said, I'll just improve the docs about it...

**Comment by caarlos0** [comment]
also found a bug related to this, will fix it too :D

**Comment by tisba** [comment]
Sorry coming back after so long :-/

Right now I'm still running into issues with this, or maybe I'm overlooking something.

I'd like to use Goreleaser's docker feature, to actually build the artefacts that will be used in docker. Release artefacts for GitHub releases etc can be build via goreleaser directly.

The project I'm trying to apply this to, lives here: https://github.com/stormforger/testapp/pull/1

The `.goreleaser.yml` can be found here:
https://github.com/stormforger/testapp/pull/1/commits/c7748bdef7ff967a8995a5f292478f9c65beb5f2

The important parts are:

```yaml
before:
  hooks:
    - go mod download
# ...
dockers:
  - image_templates:
    - 'stormforger/testapp:{{ .Tag }}'
    - 'stormforger/testapp:latest'
    extra_files:
    - '.'
```

The `Dockerfile` is a very simple, two stage process ([see here](https://github.com/stormforger/testapp/blob/master/Dockerfile)). Since I'd like to build the artefacts within docker (alpine based in this case), I need basically the entire repository available, not a specific folder. Using `extra_files: ['.']` does not work: `release failed after 1.39s error=failed to link extra file '.': link Dockerfile dist/goreleaserdocker536227750/Dockerfile: file exists`.

The reason behind my approach is, that the build environment is not alpine based, but the docker images are. To minimize the moving parts and complexity it would be nice to be able to use goreleaser go **build** the artefacts via docker as well (as apposed to just copy ready to go binaries).
