### ISSUE TITLE
Support additional checksum options specifically sha512

### ISSUE THREAD

**Issue by jspaleta** [goreleaser/goreleaser#898]
**Is your feature request related to a problem? Please describe.**
I have a need to output sha512 checksum file from goreleaser instead of the default sha256 as part of CI deployment.

**Describe the solution you'd like**
I'd like to be able to specify the checksum algorithm supported by golang crypto package in the goreleaser.yml 
Naively, I would think this is a matter introducing a new yml configuration option by which to specify the desired checksum algorithm,, and then using a switch statement in artifact.Checksum to choose matching crypto package checksum function in artifact.Checksum, taking sha256 as the fallback default.

**Describe alternatives you've considered**
Currently i use a travis post deploy hook and a little shell script to generate the sha512 and then upload it into a github release. But I would really like to be able to do this inside goreleaser as a much cleaner solution.

**Comment by caarlos0** [comment]
The only problem I could think about this is that brew requires sha256... not sure what's the best way to solve it though...

**Comment by jspaleta** [comment]
can the config support multiple checksum files maybe?
a list of yaml dictionaries that describe each  checksum file
Strawman config:
```
checksum:
  - name_template: " {{ .ProjectName }}_{{ .Version }}_{{.Algorithm }}-checksums.txt"
    algorithm: "sha256"
  - name_template: " {{ .ProjectName }}_{{ .Version }}_{{.Algorithm }}-checksums.txt"
    algorithm: "sha512"
```
Here i'm using a new template variable to reference the checsum algorithm string.
You can even have the default name_template encode the algorithm when the checksum attribute contains a list.

If the checksum isn't a list, config parser behaves like it does now.. just using the sha256 as the fallback.

Strawman multiple files is effectively what I'm doing now.. adding the algo name into the checksum filename to make it clear which file is which in the github release. I'm just producing the sha512 outside of goreleaser which is just hacky enough to be distasteful to even myself.
