### ISSUE TITLE
builds.ldflags have ambiguity

### ISSUE THREAD

**Issue by WPH95** [goreleaser/goreleaser#911]
in goreleaser document https://github.com/goreleaser/goreleaser/blame/master/www/content/build.md#L46-L49
```
builds:
    flags:
      - -tags=dev
    ldflags:
     - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
     - ./usemsan=-msan
``` 
```
[go build -ldflags=-s -w -X main.version=1.0.0-alpha -X main.commit=bb4bf04 -X main.date=2019-01-03T08:33:03Z  .......
```

I see build.ldflags required a *array*
so I try to 
```yaml
builds:
    flags:
      - -tags=dev
    ldflags:
     - -s -w 
     - -X main.version={{.Version}}
     - -X main.commit={{.Commit}} 
     - -X main.date={{.Date}}
```

```
[go build -ldflags=-s -w -ldflags=-X main.version=1.0.0-alpha -ldflags=-X main.commit=bb4bf04 -ldflags=-X main.date=2019-01-03T08:33:03Z  .......
equal
[go build -ldflags=-X main.date=2019-01-03T08:33:03Z  .......
```
This didn't work as I expected

in my opinion
1.  build.ldflags required an *str*
2.  
    ```python
    "-ldflags=" + " ".join(build.ldflags)  instead of 
    " -ldflags=".join(build.ldflags) 
     ```
