### ISSUE TITLE
Support GHE with self signed cert

### ISSUE THREAD

**Issue by vshiva** [goreleaser/goreleaser#916]
**Is your feature request related to a problem? Please describe.**
Need support to specify ca-cert that for the github urls hosted by the company.

**Describe the solution you'd like**
allow ca cert location or ca cert data or simply say insecure-skip-tls-verify

for example

```yaml
github_urls:
  api: https://git.company.com/api/v3/
  upload: https://git.company.com/api/uploads/
  download: https://git.company.com/
  insecure-skip-tls-verify: true
  certificate-authority-data: <in-line ca cert data that client can use>
  certificate-authority: <file-path of ca cert that http client can use>
```
however only one of ` insecure-skip-tls-verify` or  `certificate-authority-data` or `certificate-authority` will take precedence

**Describe alternatives you've considered**
None.

**Additional context**
 `go-github` allows specifying a http.Client. If not specified, uses the default client.  One option is to allow the user to specify ca-cert that `goreleaser` can use to create a http.Client and initialize the github.Client with that
