### ISSUE TITLE
trouble with pre-release

### ISSUE THREAD

**Issue by ryanking** [goreleaser/goreleaser#917]
**Describe the bug**

We currently use goreleaser to release [fogg](https://github.com/chanzuckerberg/fogg), and I am trying to addd support to our tools for pre-releases.

The code is in this branch– https://github.com/chanzuckerberg/fogg/compare/ryanking/fogg_setup

Notably the Makefile, which calls goreleaser, after setting the version to something like `0.17.0-abcdef` and the changes to .goreleaser.yml to turn the prerelease support on.

**To Reproduce**

See code in above branch. I run `make release-prerelease`. When I do, it creates a github release, but does not mark it as a pre-release.

**Expected behavior**

I expect that it will be a pre-release

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin CZIPA1OSX149.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

- GoReleaser Version: 0.95.2, commit 47f1fd81ea544f3197eff92f68d9a7a600cb4e34, built at 2018-12-28T22:24:11Z

**Additional context**

**Comment by ryanking** [comment]
Note that I am actively playing with this branch, including setting prerelease:true

**Comment by caarlos0** [comment]
just tested with `prerelease: true`, and it works: https://github.com/caarlos0/test/releases/tag/v5.4.2

another test, with `auto`: https://github.com/caarlos0/test/releases/tag/v5.4.3-beta1

and another also with `auto`, but tag without `prerelease`: https://github.com/caarlos0/test/releases/tag/v5.4.3

**Comment by caarlos0** [comment]
on the dist folder there should be a `config.yaml`, which is the config after defaults were applied, can you paste its contents here?

**Comment by ryanking** [comment]
Yeah I just ran a release, which created [this](https://github.com/chanzuckerberg/fogg/releases/tag/v0.17.0-773bb1f).

In my dist folder now I have–

```
project_name: fogg
release:
  github:
    owner: chanzuckerberg
    name: fogg
  prerelease: "true"
  name_template: '{{.Tag}}'
brew:
  name: fogg
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  install: bin.install "fogg"
scoop:
  name: fogg
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  url_template: https://github.com/chanzuckerberg/fogg/releases/download/{{ .Tag }}/{{
    .ArtifactName }}
builds:
- goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - linux_amd64
  - windows_amd64
  main: .
  ldflags:
  - -w -s -X github.com/chanzuckerberg/fogg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/fogg/util.Version={{.Version}}
    -X github.com/chanzuckerberg/fogg/util.Dirty=false -X github.com/chanzuckerberg/fogg/util.Release=true
  binary: fogg
  env:
  - CGO_ENABLED=0
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - none*
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
  - make clean
  - make packr
github_urls:
  download: https://github.com
```
