### ISSUE TITLE
multiple binaries to one docker image

### ISSUE THREAD

**Issue by jacobmarble** [goreleaser/goreleaser#918]
**Is your feature request related to a problem? Please describe.**
My service `influxd` can stand on it's own just fine, but it would be *super helpful* to have the companion CLI tool in the same image, so that I can exec into a running container and debug things.

**Describe the solution you'd like**
Given a Dockerfile like with multiple binary dependencies:
```Dockerfile
FROM debian:stable-slim
COPY influxd /usr/bin/influxd
COPY influx /usr/bin/influx
ENTRYPOINT ["/usr/bin/influxd"]
CMD ["influxd"]
```

And multiple binaries like:
```yaml
builds:
  - main: ./cmd/influx/
    binary: influx
  - main: ./cmd/influxd/
    binary: influxd
```

Either:
```yaml
dockers:
  - binaries:
    - influxd
    - influx
    image_templates:
      - quay.io/influxdb/influx
    dockerfile: docker/influxd/Dockerfile
```
Or:
```yaml
dockers:
  - binary: influxd
    image_templates:
      - quay.io/influxdb/influx
    dockerfile: docker/influxd/Dockerfile
    extra_files:
      - dist/linux_amd64/influx
```

**Describe alternatives you've considered**
Tried to reference the built binary relative to the running goreleaser instance:
```yaml
dockers:
  - ...
    extra_files:
      - dist/linux_amd64/influx
```

Tried naming the other binary:
```yaml
dockers:
  - ...
    extra_files:
      - influx
```

**Additional context**
`goreleaser` is a great tool, thanks for your hard work over the last two years!
