### ISSUE TITLE
Travis build fail "can't find package" when following documentation

### ISSUE THREAD

**Issue by jmvbxx** [goreleaser/goreleaser#921]
**Describe the bug**

We're test driving your solution, looks great btw, and have tried to implement the `.travis.yml` file included in the documentation.

**To Reproduce**

After pushing the code I get the following:
```
0.05s$ go test -v ./...
main.go:17:8: cannot find package "cyberduck-s3-config/cmd" in any of:
	/home/travis/.gimme/versions/go1.10.7.linux.amd64/src/cyberduck-s3-config/cmd (from $GOROOT)
	/home/travis/gopath/src/cyberduck-s3-config/cmd (from $GOPATH)
cmd/append.go:6:2: cannot find package "github.com/spf13/cobra" in any of:
	/home/travis/.gimme/versions/go1.10.7.linux.amd64/src/github.com/spf13/cobra (from $GOROOT)
	/home/travis/gopath/src/github.com/spf13/cobra (from $GOPATH)
The command "go test -v ./..." exited with 1.
Done. Your build exited with 1.
```

My goreleaser configuration file:
```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

And my `.travis.yml` file:
```yaml
# .travis.yml
language: go

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm
    # needed for the snap pipe:
    - snapd

env:
# needed for the snap pipe:
- PATH=/snap/bin:$PATH

install:
# needed for the snap pipe:
- sudo snap install snapcraft --classic

# needed for the docker pipe
services:
- docker

after_success:
# docker login is required if you want to push docker images.
# DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
- test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"
# snapcraft login is required if you want to push snapcraft packages to the
# store.
# You'll need to run `snapcraft export-login snap.login` and
# `travis encrypt-file snap.login --add` to add the key to the travis
# environment.
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
```

**Expected behavior**

I expected a successful build

**Environment (please complete the following information):**

- OS: mac
- OS version: Darwin Kernel Version 18.2.0: Fri Dec 14 18:43:36 PST 2018; root:xnu-4903.240.10~4/RELEASE_X86_64 x86_64
- GoReleaser Version 0.96.0

**Additional context**
N/A
