### ISSUE TITLE
Allow templating for docker binaries

### ISSUE THREAD

**Issue by dmlemos** [goreleaser/goreleaser#925]
**Is your feature request related to a problem? Please describe.**
Since the build binaries can already be _templateable_, I would like to see the same for docker binaries.

**Describe the solution you'd like**
```yaml
dockers:
- binaries:
  - "{{ .Env.APP_BIN }}"

  image_templates:
  - "{{ .Env.IMAGE_NAME }}:{{ .Env.IMAGE_TAG }}"
  - "{{ .Env.IMAGE_NAME }}:latest"

  build_flag_templates:
  - "--build-arg {{ .Env.IMAGE_ARGS }}"
```

```yaml
builds:
- binary: "{{ .Env.APP_BIN }}"

  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64

archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE

checksum:
  name_template: 'checksums.txt'
```

**Describe alternatives you've considered**
Alternatively I use `sed` to replace these variables

**Additional context**
This is a similar type of request to #922
