### ISSUE TITLE
Release failed after 15.26s error=failed to build for linux_amd64

### ISSUE THREAD

**Issue by warrensbox** [goreleaser/goreleaser#944]
**Describe the bug**

```
release failed after 15.26s error=failed to build for linux_amd64: # _/home/circleci/project
./main.go:74:17: cannot use session (type *"github.com/aws/aws-sdk-go/aws/session".Session) as type *"github.com/warrensbox/aws-find/vendor/github.com/aws/aws-sdk-go/aws/session".Session in argument to lib.FindEC2
```

**To Reproduce**

Please see my circle ci yaml

```yaml
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warrensbox/aws-find

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet -tests=false ./...
      - run: go test -v ./...
      - run: mkdir -p build
      - run: go build -v -o build/awsfind

      - persist_to_workspace:
          root: build
          paths: awsfind

  test-ubuntu:
    docker:
      - image: "circleci/ubuntu-server"

    steps:
    
      - run: ls

      - attach_workspace:
          at: build

  test-alpine:
    docker:
      - image: "mhart/alpine-node"

    steps:
      - run: ls

  develop-master:
    docker:
      - image: warrensbox/go-rb-py-aws

    steps:
      - checkout
      - run: 
          command: |
            echo "Placeholder"
            # cd docs; bundle install --path vendor/bundler; bundle exec jekyll build -c _config.yml; cd ..
            # git config user.email "warren.veerasingam@gmail.com"
            # git config user.name "warrensbox"
            # git add .
            # git commit -m "Release Version"
            # git push origin ${RELEASE_VERSION}


  release:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - run: 
          command: |
            pwd
            ls
            echo $GOPATH
             
            set +e
            source version
            export RELEASE_VERSION; 
            RELEASE_VERSION=$RELEASE_VERSION.${CIRCLE_BUILD_NUM}
            export RELEASE_VERSION;
            echo $RELEASE_VERSION

            mkdir -p /home/circleci/bin
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            export PATH="/home/warrensbox/bin:${PATH}"

            go get -v -t -d ./...
            dep ensure
            git config user.email "warren@gmail.com"
            git config user.name "warrensbox"
            git tag -a ${RELEASE_VERSION} -m "Release Version"
            git push origin ${RELEASE_VERSION}
            curl -L https://git.io/goreleaser | VERSION=v0.76.1 bash

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: 
              - release


``` 

My .goreleaser.yaml
```yaml
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - ldflags:
    - -s -w -X "main.version={{.Env.RELEASE_VERSION}}"
  - main: ./main.go
    binary: awsfind
    goos:
      - darwin
    goarch:
      - amd64
    ignore:
      - goos: linux
        goarch: amd64
checksum:
  name_template: '{{ .ProjectName }}_{{.Env.RELEASE_VERSION}}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archive:
  name_template: '{{ .ProjectName }}_{{.Env.RELEASE_VERSION}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: darwin
  format_overrides:
  - goos: windows
    format: zip
brew:
  # Name of the recipe
  # Default to project name
  name: awsfind

  # Reporitory to push the tap to.
  github:
    owner: warrensbox
    name: homebrew-tap

  # Allows you to set a custom download strategy.
  # Default is empty.
  #download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: Warren Veerasingam
    email: warren.veerasingam@gmail.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  caveats: "Type 'awsfind' on your command line and choose the terragrunt version that you want from the dropdown. This command currently only works on MacOs and Linux"

  # Your app's homepage.
  # Default is empty.
  homepage: "https://warrensbox.github.io/aws-find"

  # Your app's description.
  # Default is empty.
  description: "The awsfind command lets you switch between terragrunt versions."

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # Default is false.
  skip_upload: false

  # Packages that conflict with your package.
  # conflicts:
  #   - terragrunt

  # So you can `brew test` your formula.
  # Default is empty.
  test: |
    system "#{bin}/awsfind --version"

  # Custom install script for brew.
  # Default is 'bin.install "program"'.
  install: |
    bin.install "awsfind"
```

**Expected behavior**

It should build and release. It works well on my Mac OS (darwin amd64). It it fails 

**Environment (please complete the following information):**

- OS: circleci/golang:1.11
- OS version: circleci/golang:1.11
- GoReleaser Version v0.76.1

**Additional context**
I think it has to do with the fact that go releaser is not using the vendor directory
