### ISSUE TITLE
commit none, built at unknown

### ISSUE THREAD

**Issue by kaihendry** [goreleaser/goreleaser#960]
My version variables are in https://github.com/unee-t/invite/blob/master/invite.go but IIUC goreleaser's entrypoint is https://github.com/unee-t/invite/blob/master/web/main.go

```
build:
  main: ./web/main.go
  env:
    - CGO_ENABLED=0

dockers:
  - image_templates:
      - uneet/invite
```
https://github.com/unee-t/invite/blob/master/goreleaser.yml

Therefore when I try get version information out of this, I get `dev, commit none, built at unknown`. How do I tell goreleaser to fill in the values inside the "library" (for want of a better word) of https://github.com/unee-t/invite/blob/master/invite.go

Bonus points: Would be nice if goreleaser could somehow put version info in `docker image inspect uneet/invite`, so that I knew what version my user is running without relying on this version interpolation which is not working for me.

Thank you in advance,

```
[hendry@t480s ~]$ goreleaser -v
0.101.0, commit d2fa6d58211569acedb6c63303477e129da8f32f, built at 2019-02-07T16:31:28Z
```
I use Archlinux btw

**Comment by caarlos0** [comment]
🤔

Ok, let's see...

Run:

```sh
goreleaser --rm-dist --skip-validate --skip-publish --debug
```

It should print the exact command line it is using to compile. Check if the version is there.

It should run something like this:

```sh
go build -s -w -X main.version=x -X main.commit=y -X main.date=z -o dist/blah ./path/to/main.go
```

if the version, commit and date are there, its something on your side.

About the docker part, you can use:

```yaml
  build_flag_templates:
    - "--label=org.label-schema.version={{.Version}}"
```

Check [docs](https://goreleaser.com/customization/#Docker) for more details...

**Comment by kaihendry** [comment]
It would appear the variables are being set https://media.dev.unee-t.com/2019-02-12/build.mp4 ... but in web/main.go and not in invite.go

wrt **build_flag_templates** https://media.dev.unee-t.com/2019-02-12/docker-template.mp4 ... is my YAML incorrect to trigger a `error=failed to link dockerfile`?

```
build:
  main: ./web/main.go
  env:
    - CGO_ENABLED=0

dockers:
  - image_templates:
      - uneet/invite
  - build_flag_templates:
      - "--label=org.label-schema.version={{.Version}}"



```

**Comment by caarlos0** [comment]
```yml
dockers:
  - image_templates:
      - uneet/invite
  - build_flag_templates:
      - "--label=org.label-schema.version={{.Version}}"
```

this is creating 2 images, should be:

```yml
dockers:
  - image_templates:
      - uneet/invite
     build_flag_templates:
       - "--label=org.label-schema.version={{.Version}}"
```
