### ISSUE TITLE
Ability to disable specific pipelines

### ISSUE THREAD

**Issue by d3sire** [goreleaser/goreleaser#964]
I am trying to use goreleaser inside travis. However, I want to use it with some custom commands as a result I am installing it from source. The installation goes fine but after I am trying to run do a dry-run with
```
goreleaser release --skip-publish
```

I receive following error inside travis related to snapcraft:

```
snapcraft: error: argument cmd: invalid choice: 'pack' (choose from 'init', 'shell', 'run', 'list-plugins', 'clean', 'pull', 'build', 'stage', 'snap', 'assemble', 'all', 'version', 'help')
```

My goreleaser file:

```
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/app/.
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

So I have two questions:
1) Is it possible to disable a step, i.e. snapcraft step all together? 
2) What is the fix for the error above? It looks like it's related to the platform in which travis runs but it would be problematic to change that.
