### ISSUE TITLE
CI error "git is currently in a dirty state" was occured on Travis CI

### ISSUE THREAD

**Issue by goldeneggg** [goreleaser/goreleaser#965]
**Describe the bug**

CI error "git is currently in a dirty state" was occured on Travis CI.

- [goldeneggg/gat](https://github.com/goldeneggg/gat) is a target repository of mine.
- [This job](https://travis-ci.org/goldeneggg/gat/jobs/497706270) failed because of "git is currently in a dirty state" error.
  - __Diffrences of `go.mod` and `go sum` were generated. But I can't understand the reason.__
- I can't reproduce a same error on my local machine. My local environments are as follows:
  - OS X Mojave 10.14.3
  - Go ver1 .11.5
  - goreleaser ver 0.101.0

CI's log as follows:

```
Deploying application
   • releasing using goreleaser 0.101.0...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
      • running go mod download
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.8.5, commit b00cdcf0f2c913295acf6b1307137fd20038476d
   ⨯ release failed after 0.03s error=git is currently in a dirty state:
 M go.mod
 M go.sum
```

**To Reproduce**

1. Merge pull request my project [goldeneggg/gat](https://github.com/goldeneggg/gat) is a target repository of mine.
1. `git tag NEWTAG`
1. `git push --tags`
1. Auto start CI for deploy

.goreleaser.yml as follows:
```yaml
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - '386'
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386

archive:
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  github:
    owner: goldeneggg
    name: homebrew-tap
  commit_author:
    name: Fuminori Sakamoto
    email: jpshadowapps@gmail.com
  folder: Formula
  homepage: 'https://github.com/goldeneggg/gat'
  description: 'Utility tool of concatnating and printing file to various services'
  test: |
    system '#{bin}/gat -v'
```

and .travis.yml of my project [goldeneggg/gat](https://github.com/goldeneggg/gat) as follows:

```yml
language: go

go:
  - 1.11.x
  - master

matrix:
  allow_failures:
    - go: master

sudo: false

env:
  - GO111MODULE=on

before_install:
  - go get -u github.com/golang/lint/golint

install:
  - go mod download

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

# This is deploy process
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
```

**Expected behavior**

Deploy CI success

**Environment (please complete the following information):**

- OS: [(Travis CI `linux/amd64`)]
- OS version: [(Travis CI)]
- Go version : [1.11.5]
- GoReleaser Version [0.101.0]

Thank you for your great product!
