### ISSUE TITLE
use my own Makefile or shell commands to build binaries

### ISSUE THREAD

**Issue by szuecs** [goreleaser/goreleaser#986]
Feature request

Today, I tested goreleaser with one of my toy projects https://github.com/szuecs/binary-patch/releases.

**Describe the solution you'd like**

I have a quite complex build process and would like to use [Makefile](https://github.com/zalando/skipper/blob/master/Makefile) targets from goreleaser to build the binaries and upload them from a [CI pipeline](https://github.com/zalando/skipper/blob/master/delivery.yaml). 
I would like to use the releasing part of goreleaser including file upload and templated release notes. 

Rough example .goreleaser.yaml (see the new `cmd` key in builds), which would trigger 
`make  build.darwin.amd64` for example, which could write all binaries into `dist/darwin_amd64/`:

```
---
project_name: skipper

release:
  github:
    owner: zalando
    name: skipper

builds:
  - main : ./cmd/eskip/
    binary: eskip
    cmd: make eskip.$GOOS.$GOARCH
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - main : ./cmd/skipper/
    binary: skipper
    cmd: make skipper.$GOOS.$GOARCH
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archive:
  files:
    - readme.md
    - LICENSE
    - Makefile

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^doc'
    - '^test'

sign:
   artifacts: checksum
```
